### ISSUE TITLE
(-)Infinity or (-)1e1000 handling

### ISSUE THREAD

**Issue by SebastienAndreo** [json-editor/json-editor#1006]
### General information

The number 1e1000 (and -1e1000) is wrongly interpreted which leads to validation error in the UI  and to output generation errors.

- json-editor version: latest

### Expected behavior

The UI does not display Infinity but 1e1000 or do not report validation errors
and when exporting the form the value 1e1000 is written instead of Infinity

### Actual behavior
See steps below

### Steps to reproduce the behavior

defines a simple schema like the following: 
```javascript
{
  "type": "object",
  "title": "Infinity",
 
  "properties": {
    "max_value": {
      "type": "number",
      "default": 1e1000
    }
  }
}
```
The UI reports an error which is true because Infinity is not really a number but a JS reinterpretation
![image](https://user-images.githubusercontent.com/4866237/121538271-f4c28200-ca04-11eb-9702-2784b234e3e0.png)

The value Infinity is written back which is not correct regarding the schema
![image](https://user-images.githubusercontent.com/4866237/121538392-099f1580-ca05-11eb-867c-8f6245143ff4.png)

**Comment by robocoder** [comment]
This isn't a json-editor issue. JSON doesn't allow for the serialization of NaN or Infinity. These would just end up as nulls.

**Comment by SebastienAndreo** [comment]
I really guess it is a json-editor issue or a Javascript issue. The second image,

![image](https://user-images.githubusercontent.com/4866237/121538271-f4c28200-ca04-11eb-9702-2784b234e3e0.png)

 is the result of the default value of the schema, I did **not** wrote my self Infinity in the test field.

**Comment by germanbisurgi** [comment]
I don't think JavaScript can deal with numbers that big: see [here](https://stackoverflow.com/questions/20577930/bit-shift-vs-multiplication)

**Comment by SebastienAndreo** [comment]
JS specify it: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by germanbisurgi** [comment]
[This](https://github.com/json-editor/json-editor/blob/8f2b5ec5ca5787b3cd1c6b83ee3ec2ef29aeb34c/src/utilities.js#L78) is the isNumber validator. It checks also if is finite. If we take it out it will not show the error **IF** the value is less than Number.MAX_VALUE (1.7976931348623157e+308). Greater than that will be parsed and displayed as Infinity, wich by the way is still a number in JavaScript (typeof Infinity -> "number").

**Comment by SebastienAndreo** [comment]
but the validator indicates an error when it receives Infinity

**Comment by germanbisurgi** [comment]
Yes, like i said. We could remove the part that checks if the number is finite in the isNumber validator because Infinity is a number (for JavaScript). But it will not display "1e1000" because its already in the Infinity range.

**Comment by SebastienAndreo** [comment]
It is ok To display "infinity" instead of "1e1000" in the text field but the serialization should write back 1e1000

**Comment by germanbisurgi** [comment]
Not possible because the value is always typecasted to prevent types errors. And 1e1000 will be typecasted to Infinity because it is bigger than Number.MAX_VALUE.

If you really need to use that value use a string editor and use some sort of JS plugin that can deal with parsing those types of numbers. A PR for a new editor that can handle would be also nice.
