### ISSUE TITLE
user input not reflected in the output for the type boolean

### ISSUE THREAD

**Issue by sayleechandavarkar** [json-editor/json-editor#1007]
### General information

- json-editor version: using the live playground --> latest version

### Expected behavior
I am currently using a boolean enum to get a dropdown. Any change made on the selection of the dropdown should be reflected in the corresponding output json. I haven't set any defaults in the schema. 

### Actual behavior
Despite making a change in the UI dropdown the resultant output JSON is set to true for that particular property. In other words, user input is not being reflected in the output for the type boolean unless I specify the default to null. I see that this works fine for the string type but not for boolean. The selection is reflected on the output JSON for the type boolean only when I specifically set the default to null.  Setting it to null doesn't show the form to start with the null. It instead starts with true. 

### Also is there any way I can make the form default to null/undefined for the type boolean when the user does not make any selection, I guess I tried a bunch of things but nothing gives me the output I expect. Any help in this regard would be greatly appreciated. Thanks!

<img width="1059" alt="Screen Shot 2021-06-10 at 2 36 58 PM" src="https://user-images.githubusercontent.com/31837045/121579102-64327480-c9f9-11eb-94ce-316531a0ffbe.png">
<img width="249" alt="Screen Shot 2021-06-10 at 2 37 11 PM" src="https://user-images.githubusercontent.com/31837045/121579106-64cb0b00-c9f9-11eb-9ef9-448ce5426d48.png">

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "fragment",
  "type": "object",
  "properties": {
    "fragment": {
      "title": "Fragmentation",
      "description": "Allow sending of fragmented packets",
      "type": "boolean",
      "enum": [
        true,
        false
      ],
      "options": {
        "enum_titles": [
          "Allow",
          "Prevent"
        ]
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Remove the enum part:

```
{
  "title": "fragment",
  "type": "object",
  "properties": {
    "fragment": {
      "title": "Fragmentation",
      "description": "Allow sending of fragmented packets",
      "type": "boolean",
      "options": {
        "enum_titles": [
          "Allow",
          "Prevent"
        ]
      }
    }
  }
}
```

**Comment by sayleechandavarkar** [comment]
That did it. Thank you so much!!
