### ISSUE TITLE
Load document in read-only mode, to use json-editor as viewer

### ISSUE THREAD

**Issue by IanMayo** [json-editor/json-editor#1020]
We've created our JSON-schema to allow users to logically enter their data in a sensible structure, using grids and tables as appropriate.

Great - thanks @json-editor/json-editor :-)

We also display those documents in the browser.  It would be great if we could use `json-editor` to render that content using those same grids & tables.

Is this possible?

If it isn't can anybody offer pointers on the best approach, so we can produce a PR?

**Comment by schmunk42** [comment]
> We also display those documents in the browser. It would be great if we could use json-editor to render that content using those same grids & tables.

> Is this possible?

You can disable the editor, see https://github.com/json-editor/json-editor#enable-and-disable-the-editor
