### ISSUE TITLE
grid_columns does not work in array object

### ISSUE THREAD

**Issue by shaojun** [json-editor/json-editor#1028]
### General information

- json-editor version:2.5.4

### Expected behavior
`grid_columns ` should control the width of the property UI, in ny sample, by set the value to 6, each properties should 50% of the width.
### Actual behavior
does not work no matter set what value for `grid_columns `, the property always taking the full row.
### Steps to reproduce the behavior

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "pets"
  ],
  "properties": {
    "pets": {
      "type": "array",
      "format": "grid-strict",
      "title": "Pets",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string",
            "default": "dog",
            "options": {
              "grid_columns": 6
            }
          },
          "name": {
            "type": "string",
            "default": "sam",
            "options": {
              "grid_columns": 6
            }
          }
        }
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/3241829/127808571-8f444f00-ddf6-4533-b9cb-fa09b34f6c05.png)

**Comment by germanbisurgi** [comment]
`"format": "grid-strict"` works only in type object editors

**Comment by shaojun** [comment]
so any solution to control the width for `array` type object?

**Comment by germanbisurgi** [comment]
Yes, use `"format": "grid-strict"` in the object editor an set the with in the property option [like this](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIC1GQBdNhIZMnErAHMpGFcAWkQoSNs2CClIQ1gaDW8qX0zIWARkNBAIqN4sbBE6JFQANgBfNjMLQjIpKSFTGG1LEAMcthF4GCcqAEkoNUL4kSo2LsnMpp6wTm5xRq6dfWyFZNSpdMLNc0tj5qs4yPgwhVcqIjIRbFCQVzAbhpB4MgZFk8JLjBrrd7o9ngCfiA6tCYWxEMowBReIYUkZCECJu0eHATI1VL8rHgwGBfPEyBAACxQupAA=)

```json
{
  "title": "Person",
  "type": "object",
  "required": [
    "pets"
  ],
  "format": "grid-strict",
  "properties": {
    "pets": {
      "options": {
        "grid_columns": 6
      },
      "type": "array",
      "title": "Pets",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string",
            "default": "dog"
          },
          "name": {
            "type": "string",
            "default": "sam"
          }
        }
      }
    }
  }
}
```

**Comment by Garito** [comment]
I have this schema:
``` json
{
  "type": "object",
  "format": "grid-strict",
  "required": [ "name" ],
  "properties": {
    "name": {
      "title": "Name",
      "type": "string",
      "options": {
        "grid_columns": 6
      }
    },
    "symbol": {
      "title": "Symbol",
      "type": "string",
      "options": {
        "grid_columns": 6
      }
    }
  }
}
```
and the grid system doesn't work for me neither
Any clue why?

**Comment by schmunk42** [comment]
@Garito What is your issue, link below looks good to me.

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWxIyy4lCADmUmABMAtIig2eCqVQCOImO9uoA2iDwZAwgALpsEFKQVFKwNBpBIbpoILBQ2CkgAHLJClo6hE428JYKkLAIyKnWdrxY2CJ0SKgAbAC+7WyIgnR4YPKp6ZmEAMq9/fJsBVnFMKXl0HAtNTa29QNNKx2dXYrKYBS8sdFS1SDzULFkPMv5qqEW/WBQxWQQACwgnUA=

![Bildschirmfoto von 2021-11-09 12-58-00](https://user-images.githubusercontent.com/649031/140920200-b2142993-cc2a-453b-8264-6fb3ab323bd8.png)

**Comment by Garito** [comment]
I'm using barebones
What I've done is using css to limit the size
BTW the class system scares me as f: it is not possible to select a field by name, for instance

**Comment by Garito** [comment]
a grid_break must be used to split the rows...
