### ISSUE TITLE
how to condition control `minimum` ?

### ISSUE THREAD

**Issue by Demi1024** [json-editor/json-editor#1029]
### General information

- json-editor version: 

### Expected behavior

When I set the value of fruits to `Apple`, I want another property to be able to set the minimum value to 0

### Actual behavior

minimum property only work in init

### Steps to reproduce the behavior

Direct link to example: [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAVNRAFRdbKIIi6U7LjwUQpkKlNg0NxKTDHI0Ic5cJEKE94AHMFKngROlQAbRAAQQgjUxAAITJ4TLIQAF0AXzY6GHheADc5EStNCysQKLo8ZwVi+Bg6aNQABnzetkRlMApeZ0cpHxASkykyHjh4BShVBkI8MDAoIJmIABYQXqA===)

```javascript
{
  "title": "Template",
  "type": "object",
  "properties": {
    "fruits": {
      "type": "string",
      "enum": [
        "Apple",
        "Banana"
      ]
    },
    "min_value": {
      "type": "number",
      "minimum": 0
    }
  }
}
```
hope to get help

**Comment by germanbisurgi** [comment]
It is not possible to redefine schemas (fully or partially) when creating the json-editor instance. However, you could create your own [custom validator](https://github.com/json-editor/json-editor#custom-validation) for your case
