### ISSUE TITLE
AllOf Condition not working

### ISSUE THREAD

**Issue by MST1122** [json-editor/json-editor#1034]
Hi Guys,

for my schema, validation is not working or giving an error for allOf conditions. like if the height unit is "Centimeter", then the height value must be less than 2540.  
Please take a look.

[example link](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AE%2BzMAJAZwMYAsCmBbAhkgFyLCYAu5ADqkQPR0Y4GoB0%2BBAXgPbSvrdcjbABsRAS2gBzALRV8EctGwRUdACbYAZpPHlxvNVQjd1AV3TkZ5AJ5Vsa3NnL4ZTPPjoA3AIxIANJAwCKTI4urEpBTUtAzuLOxcvPyCwmKSsvKKyqoa2rr6hnTGphZWtvZq8Z6%2BdAAKAEoA8gAiAKoAwgAqAUFwCEjIArhO0OSRSACCSXAl5pawFdiwmjrQegZwWtwQsI2tnV2wc2WLdti9UP3wSKsFm6iR4FchIUgEEADWzlQi%2BOjYAD64SefVe4NIq3wZhE42AJCmPjqkwAbAB2ACcAFY2gBpACyADEGhjLsEIW9gNh1Hp8AAjEQXeGwLT4ESobCBF4UgZkcKaaCRcgQMycsE8m5UgAeHF%2BDkiAG1xRLKdN8Dw%2BJokMqeQBdLnkiVIJYTYCoYUZMnXHlIfDQGxNLSKnUq2DPQ2u17G86m80QS3AF0qgC%2BButrvd4c9kpNzKQfoDYej4KQ2GgZlwzu5yYhiOR6OxeKJJO12ZzsH1QejqfTuAAchx5cylWXy7y1RrWFrA63k7qqzzgwOQv3e%2FBQwOkH9pGZ8FIgS4pKCx17gFCYXCEWugS0AKJW12pmkuBlMkis9lileUzD8tNCkVXj0U1My3Byx7N4e54AAcRUBBwAAFP%2BECATYACUpbPhClbXrysZbgm0gHiqtr2o6WYwRKkZtjGPpxmaFooT22GDkmya4Xh3r2L6xFLsAFFtjWGZYVGzHAOgqCAh0ABaqF4by0AiICdYADICYJpBpoCv4AEKSYJtw7vujHftWwC%2FICdQSWp8EaQ4gK7gAyop1FUtxbSmXpZE5saECAl0DTQexnpwbZaFUrWDZOJ%2BJAth5GkdJw2BYLAQHBaFt74FBNmuXZwAtGY5BhUBdbODgEDTuoqCxUxUlILu0gSKgmDhW06zkNSsC4hk6iCHl6mekgoGAeFrV2pBZkcXU3AlWVQG9dljX6c1wDGfI6yleFE34JII2BWNs1TQNFV6NVxkuFVuXdeWSBdGYXziNNQEHV82BdaR8UqqOi0hEOo23a5D0ehOZY0WepDcHSABWoVwvlSAlPYijiE2JBUSmwDrbggKaFQ5CYICADu4SI4CODiFIFDLotgzDKMm6kF0OArNgCNlXa6iwKj6iI7A3BaIspMw7AkiwBA2D4OoNiLNwsBmBysACNAx6bKwsANFzPN8wLQvHWTazVfgqAM8lDNM%2FI6CfHOGSwFTKzHb8%2BA2MrquC9V2y7Ngb5yiyMIiLzJhiNV3Dq1b%2Bsc2YUgM7sDJ2t85CsLtlL6OQjKmgAklVuCwC04ijKgDxx7AUqwAA6qnsAABIh7ymgYP6CObKaJPLPD9MG7T9OM8zyys%2BznPc7z5D8xbwu8GLySS9LLdt%2FLqt3Mo1Mq2r5Aa8c%2Fw61IesGzSqDG6bI%2Fmxy1MezbsqMvbYhO31jLU2748e%2FgXs%2BzssD%2B9AgfB3Fh7Spv4OwAF11QwALAADLAkfQFgTZNe5L9SCIVIAoCAJs86SlwJIaOeA%2FKwB8PlF8wAoHQDWgAR1FDA3AcCEFNXePgKU6DMExxwYgn8HJGSWB2HA5%2BCUPiB2NgCYEEQrqugAXfGGcDIZjWAUgb6f1LAQNXJzDB4hOYsP8k1JBFdMBCKQZjbGAMpE%2FnoT8P4TCQS33MtXWRrC%2BxkKNJpEwIN9CP24QlGRuNAF32pLSU8kQLwcgMXtPk6gBQPlFM4hKvDgD8P%2BnIzyIizBiOpGxKSP4zCVQCRpLwbJRQuXCfAdhiSgbGJUKYrhyiYlxM%2BuYxJoc9AR0IlguO5N6aEhMGMWAXR%2BZySntElxBd0BF0KIKQidQTBeHCMsRGywnAq0OngNM49a69LZjHFkJhY5aEqePVuF8p5szgHafWqAOS4FPNTc0%2BAqo3y8Skqkx56RFJIMKTxWSXG3jcfeZkjinzWPMhvd8jIaEXKUsAD%2BCT8mwX2eEj6ppax0hUA0uhuhcCsWZO%2FN5IZfkuMiXoKx3yfxhxOaQEpMjYBrSUaNd5TSWkl0IsZUQ%2F064C0qhPfpqBBksnPuispmA9nQoMkc%2BxzIzn3KRVDK57jblsicUysaTyPxhM5Ug7%2Bv9PwCrYbC95PjkIMRlY82sIrRVQwBGMBOzgVCSpxXhZJqrpLeUbK83VfzgAdGGZqqqqgvkGqeqKl6DyJRvTup5bmXdoBsg6dwExYM4F3MVYYtkIhMJflNZ6PJSKkDiCdMySNqr%2FmET8YIrRBrKTA3SX6xFaakHwqJvGnNocCJIXoiCzlLFMxhtdYW0g6r9BOGtTq6tqr9U1p%2FGmDMPlH60LbXfOtVrtW2t7a8e1w7xxSuTI6nNLqnUuN6W0iGE6NI%2BOTdi5t7yM2gzMUulxsSRDxLjTu2VxbSCAuBamsdvICBSgThCkgAAmLEnzw35KnW2t9BqZ05tTJebNNbo2xsXS%2Bg5K7fr%2BIvb21JPrM3buA1G4Aea%2F2XqhnK0tEHkO8g7ZWyRcHC3Rp%2FjgJts6c2tow5ho1vkVVkZ%2FJICVQ7qMViPXhD9w6WPTsDQVYA86kOQa4yevhYGU0cfyVB31sH13luAHug9QGJMGsTVuM9UB0NkfwTe8F2H4Hv200xtsbH326cHIZ%2B6hn9NtlHXp4TvIFE40PbhyktiTyooDTupA3KbmnMfFZlD%2FHfGCbXcRn8QSQkSKfoZpAiGVOcek0yHdpHzKboyTxg5MXkvwZRZ9JAJTs7YCxhQWAhIRDcHPjU6pPqy0aTxeIYuvBTTeq6ZoUllLBmEwnmM1mMzBCkq0EV8%2B8yxmtyoEs%2FWyy1l4E2bAbZuyv5M3axMhWNtJrqGOZyUlNnx4K2a%2BI4bKzImLaptVKg3Ak6tMZfZzyjmVseI5Wmtzd4F0sj5Td%2BT99nnduMz%2BAAzFCvRdrvM8N80pirY0UG3s01C874Iv2Sci7JwLy7CmZeANl3LijMXktrviLmVLObA7vlVmrD2kBEsoXM0meaKXY%2BpR7VmOW8sBe%2FYcuxqL2X%2Fbvu5h7LnIc2le8Kqt8OXHisI%2FRzl8X0u%2BflXji7yr%2Be8f7Q2wdv2W1s%2Bl5241VHGcWo1Qrm1SvRUWe%2BWZ8s0OzXuo2LwL1aSt3%2BqeyryUwbQ04bkzyAtByY1pYTXx2iSb%2FNS40olrNdnnfvNh26D7y6Jdobt5xrDGvqNIHl1q3X4e3LR%2FeVhrtJrg%2BScT42kXY6De9qNw6lPJvPfcaDwL7xvnV1%2B7GgH8TVfzKpcrwxhTp6MxAuU2n8y16weREfc%2B7PemU8me5xSMvoqf0cg91P6GgGw%2Fj%2BTO3gTAiGeXtEzBzJS%2BOKh9d2OlfRF%2FQkR72a2PsuGM0YI3%2FHfUkxcYYrZnuPl%2FSC0eF3r6jhfL3F7TT%2FpFk%2FbsuMcAHt99y8a9fcotGcG9t9h9osclZ8N8vckcgdIDEC%2B8NNIgfBtMIdYDBI%2F9VV8DX1S9TM4sBUACNJVFqB1EgRNE4cRMUBOYF8kAABiPINYc3aARwBQBhag5hfPT0cgsaHRBA5lZnT6LnWAu7a5B7VnVzJA00WvVAjSYLcRZ%2FTjSLU%2FUgFvOLaPTfa3EQ3deA1vQAjLKOCZdONGMqYybpMrWAaw7sTQykAnVpOrTpGwsZLbIZKpTrWOJORreZPw5YUZUmTrKpYI%2BuebZZUbdZCbKbbAM7XA9tFlFnLzFPKQnlc8W3NI3nF5NQufb7fg%2FJe%2FegnxFAxwq9MFO9WAHApvKHTQiLKJYwl7Uw4pcwyw9HBFJQzjZwglLcEnElMZCnWuTwmlXYVmHRBI2onnS7VlTzc5W%2FG8e7BxLIhYzDW2XIi%2Ff9ZHa%2FIjEjco%2FCb3EtY%2FBVbI8%2FJ3KYvtS1HXXYtNYog5DPdXTYvDc1K4pPG4u1Eg7nQQhKM3VpS3aDfQ3lS8XQ4AB3BfHtJFUA95d3Jo540DNfOvO%2BaAgwufPfUfTyVDY4xEpVKoiEy%2FfDOjD%2FAvfYwVCjd7VYjiN%2FG%2FRI8zdEqHOk2AQg5jEk40YAlEkDcAhEro%2Bg5E2E3jFvOg%2BPeQwiMohkpBdAqorAnTCkozGUsfGk14b4%2B439PkwAmEwUg%2FYUrcRQkkpBXkjUh%2FBDRog0tvLU0gSXbkttCtPIoU3PRXMUm6XU5fLyNXSjJ4l%2FSUO05POUvsB0%2Bkn0%2F0hUifJ0mMNk1UrY%2BE8DEM1cfUxfIM50gUuMi4jkw4jvDZc9aMu%2BCUzTQfGohjJk%2F%2FBkgs43T42Ar%2FaMYspUqGX4zYf4sTG3X9UaI3FjMvW0NxDgusrfZYxsmAYMYAIAA%3D%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

@schmunk42 please take a look.

**Comment by germanbisurgi** [comment]
`If then else` is still not supported in this library
