### ISSUE TITLE
Bootstrap 3.4.1 requires a fix to work properly

### ISSUE THREAD

**Issue by ccancellieri** [json-editor/json-editor#1042]
### General information

- json-editor version: latest

### Expected behavior

I'm working with Bootstrap 3.4.1 (imposed by my host application) and I'm getting problem with nested panels and activation of **format categories panels**.

Here https://is.gd/oSthU0 you may see that the demo works properly with bootstrap 3.4.0 but with version 3.4.1 there are some css changes that are preventing json-editor to work properly.

### Actual behavior

Here is what I have:
![image](https://user-images.githubusercontent.com/908123/130055797-50175d4e-2f12-49e8-83e7-4f61f44b0330.png)

The tab content is not active so the panels are all collapsed.

The problem is that both the bootstrap versions 3.4.x are defining:
![image](https://user-images.githubusercontent.com/908123/130056487-dadf8a99-3a86-470e-9835-eabed220f887.png)

But on 3.4.1 we also have:
![image](https://user-images.githubusercontent.com/908123/130056626-1fcd4d09-f138-406b-ac92-12818832c083.png)

_I'm using snapshots so you can also locate them into the original css source with row numbers..._

### Steps to reproduce the behavior

Try to upgrade bootstrap to 3.4.1 (and select bootstrap3 into jsoneditor options)

### Proposal

I'm not sure about which is the best way to fix this but I would like to propose to modify the resulting dom of 'tab-content' from:

```html
<div class="tab-content well well-small" id="...">
   <div class="tab-pane active" role="tabpanel" id="Basic">
 ....
   </div>
</div>
```
To:

```html
<div class="tab-content active well well-small" id="...">
   <div class="tab-pane active" role="tabpanel" id="Basic">
 ....
   </div>
</div>
```
Adding 'active' to the tab-content class list.

This will result in a fully working bootstrap3 style as shown:
![image](https://user-images.githubusercontent.com/908123/130057836-0bf93c4e-981d-4bff-b985-a6e51359823c.png)

**Comment by schmunk42** [comment]
PRs welcome...

**Comment by ccancellieri** [comment]
Just few more notes...
I was wondering why that selector:

```css
.js .tab-content {
  display: none;
}
.js .tab-content.active {
  display: block;
}
```
May affect my json-editor, this is because my application defines the page as following:

```html
<html lang="en" class=" js">
    ...
</html>
```

I'm investigating why, (my stack is quite complex: jinja2, python, existing javascripts and css, bootstrap3.4.1).
