### ISSUE TITLE
Decision trees with dependencies support

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1045]
I apologize in advance if this is already in place. English is not my native language and I may just not know what terms to use to identify what I want to do.

Essentially I need to implement a sort of decision tree where components selected make form sections appear or disappear. 

Is this supported? I can't tell from docs but it may be that I just don't know the terminology. 

A very basic example: "Add a contact method" with options for "postal address", "email address" and "mobile phone", selecting each uncovers the corresponding form with different fields depending on context.

I'm not sure if this is supported and if it is, how it's specified.

**Comment by schmunk42** [comment]
Have a look into `anyOf`, see https://github.com/json-editor/json-editor/blob/8f2b5ec5ca5787b3cd1c6b83ee3ec2ef29aeb34c/tests/pages/array-anyof.html

@germanbisurgi Do we have something about this in the docs actually?

**Comment by eduo** [comment]
Thanks, I was definitively barking up the wrong tree and I was going nowhere. The solution was indeed much simpler.

One question: Validation for nested fields is generic. The error is always "Value must validate against at least one of the provided schemas" even if the validation is "required": true or "minLength": 3 (and it's 2 characters".

Is this something that can be avoided to provide errors the users can understand?

Example 1: Nested fields displayed by default, validation message is generic (I add two text fields to show the same validations working elsewhere in the form)
Interactive Playground: https://is.gd/oTW1Z3

Example 2: Nested fields not displayed by default, when selected from popup fields appear but no validation is run. If you tab or click the fields the "required" validation is not triggered. Typing one character does trigger the minimum length validation.
Interactive Playground: https://is.gd/iPfyKN 

Additionally: I couldn't put default data for the second example because I can't find a way to pre-populate a field that depends on an anyOf selection. Ideally when selecting the option and having the additional fields popup, default values should also appear.

**Comment by eduo** [comment]
Ok. Even this was unnecessarrily complex. I used the dependencies model and while less neat, it's perfectly functional.
