### ISSUE TITLE
Require default-unchecked checkbox to be checked before submit

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1046]
Hello,

Is the only way to require a value not set by default in a checkbox to handle via javascript? I have managed to not have any javascript logic and build everything into the schema itself, but I can't find a way around this.

It's for one of those legal "I confirm I have filled all data correctly" checkboxes. I have it defaulted to false so it always loads empty, but I need it to be true before submission.

**Comment by schmunk42** [comment]
Try this: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgIUyFSmwaGkFjoRcBtCCiCIVQnjBhsVMvAWwoTwgBEwAAmEivsamggD8CgAmVERkItjiKDHYiFRsJDJkCUaqGADW9gAeClTwInSoANpQUiJUALoAvk1siMpgFLy62lLIKCAw8FC6ZDxwrmxQqgx2DlCI1WQQACwgTUA

```
{
  "properties": {
    "complies": {
      "type": "boolean",
      "title": "Do you comply?",
      "default": false,
      "format": "checkbox",
      "enum": [
        true
      ]
    }
  }
}
```

**Comment by eduo** [comment]
Oh, this works. I hadn't thought of giving an enum with a single value. Thanks!
