### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. 

### ISSUE THREAD

**Issue by IMEVEN** [json-editor/json-editor#1061]
### General information
While config:
`
        JSONEditor.defaults.options.upload = {
          auto_upload: true
       }
`
I got this error:

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at upload.refreshPreview
    at FileReader.e.onload`

By the way, I use the theme of bootstrap4.

- json-editor version: 2.4.0

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/upload.html 
**and** add config like:

```javascript

        JSONEditor.defaults.options.upload = {
          auto_upload: true
       }

```

**Comment by germanbisurgi** [comment]
Fixed in https://github.com/json-editor/json-editor/pull/1062
