### ISSUE TITLE
Error message 'No additional properties allowed, but property is Set'

### ISSUE THREAD

**Issue by ItSkary** [json-editor/json-editor#1078]
### General information

- json-editor version: 2.6.1

### Expected behavior
Correctly load a json with it's schema, and view the result into the editor (both json and json schema are valid)

### Actual behavior
Editor load as expected, and data are presented correctly, but on top of the editor there are few error message that state :  'No additional properties allowed, but property {name_of_the_property} is Set'

### Steps to reproduce the behavior

Direct link to example: 
https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYALDQ648AYkQAaSDHiIyASzIAbLERIBJfHyynKvMgGEWo7XwCuInS1Xq4JQVgfRd2iwoRuBQXprAdtAAblgQKIHQAPKUbtAhnvBZJGQAnpSGwMSITABG9FhoZB5h2RF4goIBLHh6AAoQTAUQOljBRbCirShYarV1iJSd3b39xKEadREA6roYxtBt2gAeWHoZ40sReQVGiNrQZFjmUMBji0ckorz41QPnlwDMAEyImUcAX3u4QmwAAElhHOQNltdvsBgsQUstPlCsVgBcrjcag8johnhBXmcMV9fsB%2FksgRTQQARSjaA645HAE5okiY65xHFI0EEonvElkH5%2FQ51Kmi7KIAByWCwghs00ZPMlLNRxNKTCYBjw6XJEqy4qZWUQAGUnKIHNslY9jmqBgBtamPRDQJx6eHAm3G4AoMgQC58EVG7IAXSdBs9eOAADEXng3vNwyrWUZHfrma73dyvRFff7oIG9cGsmH07AAeGK6LDSDEAAhPAjGl4XAsVZkDAAQScHaiDmcrkS1tBrT0SVEqaTsERXsQSAgvmJiiEvguzWgKBoDZGfccLnjiRpZCYQeV5cjSxnNpRpwFZQqVWz1%2BADSaaVaHS6cVmRiGehGF5RlMX49NofTDrOwAAKojBAAAyTB8BcEE5jebJpsWzrAJmHpTlheYBqeOYlnhEakREMFxG0jYoAA7rwggoZBKYOuRoI4U%2BxG5n6hFFmeSylphBqkVWxaiTygkgjWKrblgu4DgeLBHieCLhmhxL3pUbyAfUjTrh%2B0zfmBcyDMMoxqcAwEzMZTHesYjGqWWtq3uiHLYncpH4nGCbsqSRGAjp3omkwLhoGyV5YSxxAYfx3ocR5TnegRBb%2BY8kmPNJUYALJYGQDTxgQjlCSU0BYOOk6JfAEWoaqLkkPFbGZV61WQfOi4CsuPh%2BOum45XlggFalNriV66WApW1JNSQfX5XltnqXe5RaZx3qvvp7SGaB4EDH%2BAEWVZRnbYmZaIAqWCKdAAAq2g4OFnm1WyiDJYWgUqny8bEgNVysDot1DdkU0qnBjZkAAom%2B11%2FUVsULeiz0rcy70%2BYgX1YD9N2FFOgPejSey5YkkN3YlsMkPDCXFcASOffGaO%2FZjZbYxEZ004Ida5JRtzHRTUWwDFxEum6uGVaTPEpXxo1Y6901ME0DhymzHO2cmdrRWxAtZuTsXcfmhakWNlJS4gwO%2Bp2VRDtDzEq7zavYYLCNRmTetYxN1b%2FJliCjuVrGii1JBtROHUrt1aSbrJzattA7Zdj2GDyfuaRDVNvskyUS2PprzJre%2BG0gT%2BO1mYFkybXnXNnogGyUD2sZ6D4EDUR2SvejzfM1fFUsqo7iX62KhvAMsvAANZIdA1e1%2FXGCN856E223Nud0J3cA73JrHiI5ij1R8YTxbz7NzPdsZzV8%2BxYvZEnTG2gGCgDZkJgJraAAXkT3NWx8WJcofWFUwKmLCuLAVTkQCkOIF1CYhTIFlE0k8civ0FJyW47cnjeWJL%2FMkktAHABSCHaBJMW6QTwBAEQuR7YZgPnrRB5wrg4BMr7Zk%2FslxBzXCHGgURYjxESFg82Ilnb6hGsJcYkkATACAA%3D%3D&value=EQbwOgTmB2AE%2BzMAktADgVwC4DED2ANgCYCmEACgIZYAWSAXIsGgIxIA0kMCTA6nhADWAcwCW0fMTJVaDJmgBMHLnARIAylgGVhJSaQrU6wRkjQBmZVGhgsSAMJ4Atk8rQiAGXElH0AG5kWNJGSLCmzAAsVtxqwDiiBCQAzgBC1ADGNOqiAF4kcgAcLACcCpzWPEgA8mhk1KJ40AAqok4keNgAsupyAGwADIOD5THw1WhYDdBJcgDa4BU8S2PAvKK0qOSiAB4kBHLmwyrLy0gAEiSiwjRYmzt7B0eLJ7EAImiicgDsZccvsQA5EgkIj2CB4NByABmlAISRII1U%2FyY6gwUKhOzkSAA%2BklXAR9sBEciVvgIK47CYmAB3EgAI0hwD%2BywAvuxYAtRv8kGsNtAtrtCYxDv1iSTzpdrrd%2BfchbARWLkUh3p8qT9FdzgECQWCIdDYfCNS8NGiMdsscBcfjCUaTkgyRSLQArWrCJDMpZsjke42rdY0O6CvpPLm%2Bi5XG6Bh5Ugain124Aq76%2FZ6a7Wg8GMxgwuEI%2BOnYCo9GYqk4tpEUQYJzRJGah3UC20hnu1M8L2c2u%2B3kBmVBmMhzsJ8NSqNy2O2gtJtUp0MJ9O6rOwHOG%2FNLE3F82ly3lyvVomrypxASOrcukhupmthDtg%2BxbujuQsfoFONXgvDyO96OMJ8vidrxMPmTf9D3nTN9VzEDYiLM0LWxAhKAgXQaxJJh60pcIm0ZVcbzfAD7y%2FOVf1fWd30lT8BW%2FWBiKglYp0YdVbxWMC9SpZc8zww8YJLcJ4MQ5D9042J0OdV0W1I2AWQ9ABdDUkAAVXhCAPDwMQbC3VodEuJw0AELBsSISgSCcRoUNiRTgiSJJqQEIgLTQSgrJsiA7MErkkGQVzGBI2sNA6CB0nyLdkFcXQQt0iB9NeIyTP5AgMDUsyVk6EgsEoQy0rkDtfTBEh6kaFo2gtBR%2BgUFgAFoWAUcr%2BmKJoWAKegWC%2BegAFZigAOmKQ5ihYCIFAAan6Fh6EGJKAI8RysAAUQrLBCqC8ISrKyrqtq%2BrGuatrOu62q%2BsG4bRv6cbD1ePZUqmBbiqGGqKuGppBiOo6TtiXLqBBFIAE8LKgLcFFa3oXuSvAKwxD7vqU4qAaBphJqSLAAEF0kmUytzeoJxNrKTrBZYAgA%3D%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0

**Comment by schmunk42** [comment]
Looks like a tough one.

Could you create a much more condensed example?
That would ease debugging.

**Comment by ItSkary** [comment]
I have generated by hand a simpler example, basically removing all the properties not involved in the error and related definition in JSON Schema.

https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYALDQ648AYkQAaSDHiIyASzIAbLERIBJfHyynKvMgGEWo7XwCuInS1Xq4JQVgfRd2iwoRuBQXprAdtAAblgQKIHQAPKUbtAhnvBZJGQAnpSGwMSITABG9FhoZB5h2RF4goIBLHh6AAoQTAUQOljBRbCirShYarV1iJSd3b39xKEadREA6roYxtBt2gAeWHoZ40sReQVGiNrQZFjmUMBji0ckorz41QPnlwDMAEyImUcAX3u4QmwAAElhHOQNltdvsBgsQUstPlCsVgBcrjcag8johnhBXmcMV9fsB%2FksgRTQQARSjaA645HAE5okiY65xHFI0EEonvElkH5%2FQ51Kmi7KIAByWCwghs00ZPMlLNRxNKTCYBjw6XJEqy4qZWUQAGUnKIHNslY9jmqBgBtamPRDQJx6eHAm3G4AoMgQC58EVG7IAXSdBs9eOAADEXng3vNwyrWUZHfrma73dyvRFff7oIG9cGsmH07AAeGK6LDSDEAAhPAjGl4XAsVZkDAAQScHaiDmcrkS1tBrT0SVEqaTsERXsQSAgvmJiiEvguzWgKBoDZGfccLnjiRpZCYQeV5cjSxnNpRpwFZQqVWz1%2BADSaaVaHS6cVmRiGehGF5RlMX49NofTDrOwAAKojBAAAyTB8BcEE5jebJpsWzrAJmHpTlheYBqeOYlnhEakREMFxG0jYoAA7rwggoZBKYOuRoI4U%2BxG5n6hFFmeSylphBqkVWxaiTygkgjWKrblgu4DgeLBHieCLhmhxL3pUbyAfUjTrh%2B0zfmBcyDMMoxqcAwEzMZTHesYjGqWWtq3uiHLYncpH4nGCbsqSRGAjp3omkwLhoGyV5YSxxAYfx3ocR5TnegRBb%2BY8kmPOJlLUpl57%2FIgo7jpOooRd686LgKy4%2BH466brJzattA7Zdj2GDyfuaSpblxUWVFJCaY%2BCVGvlenvu0hmgeBAx%2FgBFlWUZk2JvqOXwDlkkAsAQA%3D&value=EQbwOgdgBFbAkgEzgLigBgDSRnAygPYCuATgMYCmqsCAtgIYDmF8tADgSQC4D6AIvQq0CEAAoAbIowCWEOJAC%2BwIA%3D%3D%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0

**Comment by ItSkary** [comment]
> Looks like a tough one.

I have the doubt to have missunderstood you. With a more condensated example, did you mean i should avoid the playground and prepare adhoc example?

Because i have used the playground as suggested during issue opening, but i find hard to debug in that environment.

Best regards.

**Comment by schmunk42** [comment]
No it's fine now, much easier to understand.
PRs also welcome.

But, I'll ask @germanbisurgi to take a look.

**Comment by ItSkary** [comment]
@schmunk42  : thanks a lot, it's not cleart to me what PRs is, but if i can help in any way let me know i will try.

Best regards.

**Comment by schmunk42** [comment]
A PR is a [pull-request](https://github.com/json-editor/json-editor/pulls) with a change which fixes the issue.

**Comment by ItSkary** [comment]
Recently i have udpated the project and re-searched the issue list to find out if my issue is solved.
I find out that still in 2018 another user point out the same behaviour i get :
https://github.com/json-editor/json-editor/issues/130

Here a workaround suggested is to produce a JSON schema with allways the property '"additionalProperties": true' instead of '"additionalProperties": false'.
If i well understood the comment seems that an user (https://github.com/json-editor/json-editor/issues/130#issuecomment-470504482) is questioning how that property is interpreted by this implementation.

I have tried the workaround and can confirm that solve the issue. Probably a better solution should be change how 'additionalProperties' is intepreted into the library

**Comment by germanbisurgi** [comment]
`allOf` will validate only when the editor validates against all of the schemas listed in its array.

It is throwing an error because the schema says, that it must be an object with no properties but it must be also an object with x properties.
