### ISSUE TITLE
Feature: Add delete confirm prompt before deleting nodes with UI controls

### ISSUE THREAD

**Issue by theBull** [json-editor/json-editor#108]
### Expected behavior
Json Editor could alert the user that they are about to delete a node with something like a confirm dialog. This helps prevent them from deleting nodes accidentally due to a mis-click.

Something like the following would be helpful:
![image](https://user-images.githubusercontent.com/3451643/41619898-cf1d8fa0-73bc-11e8-93db-0a9c7ecaea8c.png)

### Actual behavior
When working within the editor, particularly within a large json file, it can sometimes be easy to accidentally click on the delete button instead of the collapse or add button. Not sure how better/worse this is for other themes, but I am currently using bootstrap3.

The screenshot below shows the UI proximity of the delete button to other controls. A mis-placed click can delete a node without warning.
![image](https://user-images.githubusercontent.com/3451643/41619829-74d36308-73bc-11e8-8428-418e079ba75f.png)

---

Perhaps it is config-specific, perhaps not. It seems like the ability to configure json-editor to `options.prompt_before_delete` could be helpful. It could also be added to nested schemas / properties in light of how the functionality currently works.

If this sounds feasible, I'm happy to provide a PR if I get a chance. And of course, feel free to correct me if there's already a sound way to do this :).
https://github.com/json-editor/json-editor/blob/master/CONTRIBUTING.md

**Comment by schmunk42** [comment]
I think that would be a very useful addition. Having an option to enable this also sounds good (to keep BC). I think there's nothing about this in the JSON schema spec.

PRs highly appreciated, a test would be cool also.

**Comment by schmunk42** [comment]
@germanbisurgi Nice.
@theBull Could you have a look at https://github.com/json-editor/json-editor/pull/109 and give us some feedback?

**Comment by theBull** [comment]
Done. Wow, fantastic turn-around time. Very impressive. Provided some feedback to the PR and approved. I'm hoping to contribute some actual code soon. Thanks!
