### ISSUE TITLE
Enum label are not presented

### ISSUE THREAD

**Issue by ItSkary** [json-editor/json-editor#1080]
### General information

- json-editor version: 2.6.1

### Expected behavior
When an enum type is defined in json schema, the UI DropDown should display enum textual representation as text in drop-down and use enum value as associated values (associated with the displaied text).

### Actual behavior
Only enum domain as values (intenger) is displayed in the drop-down, doing so prevent the user to understand the meaning of those values.

### Steps to reproduce the behavior
Seems that this enum definition (i don't know the details of json-schema i use a component to generate it, but so far every time i checked it produce compliant json-schema) does not show labels of the domain but only values.

``` "Currency": {
      "type": "integer",
      "description": "",
      "x-enumNames": [
        "NIL",
        "NONE",
        "EURO",
        "DOLLAR",
        "YEN",
        "POUND",
        "RENMINBI",
        "RUPEE",
        "RUBLE",
        "LIRA"
      ],
      "enum": [
        0,
        1,
        10,
        20,
        30,
        40,
        50,
        60,
        70,
        80
      ]
    },
```

![image](https://user-images.githubusercontent.com/6507710/145969175-82f53f1f-26eb-499f-bdc7-6993622e3480.png)

(previous example for another issue)

[Direct link to example: https://json-editor.github.io/json-editor/](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYALDQ648AYkQAaSDHiIyASzIAbLERIBJfHyynKvMgGEWo7XwCuInS1Xq4JQVgfRd2iwoRuBQXprAdtAAblgQKIHQAPKUbtAhnvBZJGQAnpSGwMSITABG9FhoZB5h2RF4goIBLHh6AAoQTAUQOljBRbCirShYarV1iJSd3b39xKEadREA6roYxtBt2gAeWHoZ40sReQVGiNrQZFjmUMBji0ckorz41QPnlwDMAEyImUcAX3u4QmwAAElhHOQNltdvsBgsQUstPlCsVgBcrjcag8johnhBXmcMV9fsB%2FksgRTQQARSjaA645HAE5okiY65xHFI0EEonvElkH5%2FQ51Kmi7KIAByWCwghs00ZPMlLNRxNKTCYBjw6XJEqy4qZWUQAGUnKIHNslY9jmqBgBtamPRDQJx6eHAm3G4AoMgQC58EVG7IAXSdBs9eOAADEXng3vNwyrWUZHfrma73dyvRFff7oIG9cGsmH07AAeGK6LDSDEAAhPAjGl4XAsVZkDAAQScHaiDmcrkS1tBrT0SVEqaTsERXsQSAgvmJiiEvguzWgKBoDZGfccLnjiRpZCYQeV5cjSxnNpRpwFZQqVWz1%2BADSaaVaHS6cVmRiGehGF5RlMX49NofTDrOwAAKojBAAAyTB8BcEE5jebJpsWzrAJmHpTlheYBqeOYlnhEakREMFxG0jYoAA7rwggoZBKYOuRoI4U%2BxG5n6hFFmeSylphBqkVWxaiTygkgjWKrblgu4DgeLBHieCLhmhxL3pUbyAfUjTrh%2B0zfmBcyDMMoxqcAwEzMZTHesYjGqWWtq3uiHLYncpH4nGCbsqSRGAjp3omkwLhoGyV5YSxxAYfx3ocR5TnegRBb%2BY8kmPNJUYALJYGQDTxgQjlCSU0BYOOk6JfAEWoaqLkkPFbGZV61WQfOi4CsuPh%2BOum45XlggFalNriV66WApW1JNSQfX5XltnqXe5RaZx3qvvp7SGaB4EDH%2BAEWVZRnbYmZaIAqWCKdAAAq2g4OFnm1WyiDJYWgUqny8bEgNVysDot1DdkU0qnBjZkAAom%2B11%2FUVsULeiz0rcy70%2BYgX1YD9N2FFOgPejSey5YkkN3YlsMkPDCXFcASOffGaO%2FZjZbYxEZ004Ida5JRtzHRTUWwDFxEum6uGVaTPEpXxo1Y6901ME0DhymzHO2cmdrRWxAtZuTsXcfmhakWNlJS4gwO%2Bp2VRDtDzEq7zavYYLCNRmTetYxN1b%2FJliCjuVrGii1JBtROHUrt1aSbrJzattA7Zdj2GDyfuaRDVNvskyUS2PprzJre%2BG0gT%2BO1mYFkybXnXNnogGyUD2sZ6D4EDUR2SvejzfM1fFUsqo7iX62KhvAMsvAANZIdA1e1%2FXGCN856E223Nud0J3cA73JrHiI5ij1R8YTxbz7NzPdsZzV8%2BxYvZEnTG2gGCgDZkJgJraAAXkT3NWx8WJcofWFUwKmLCuLAVTkQCkOIF1CYhTIFlE0k8civ0FJyW47cnjeWJL%2FMkktAHABSCHaBJMW6QTwBAEQuR7YZgPnrRB5wrg4BMr7Zk%2FslxBzXCHGgURYjxESFg82Ilnb6hGsJcYkkATACAA%3D%3D&value=EQbwOgTmB2AE%2BzMAktADgVwC4DED2ANgCYCmEACgIZYAWSAXIsGgIxIA0kMCTA6nhADWAcwCW0fMTJVaDJmgBMHLnARIAylgGVhJSaQrU6wRkjQBmZVGhgsSAMJ4Atk8rQiAGXElH0AG5kWNJGSLCmzAAsVtxqwDiiBCQAzgBC1ADGNOqiAF4kcgAcLACcCpzWPEgA8mhk1KJ40AAqok4keNgAsupyAGwADIOD5THw1WhYDdBJcgDa4BU8S2PAvKK0qOSiAB4kBHLmwyrLy0gAEiSiwjRYmzt7B0eLJ7EAImiicgDsZccvsQA5EgkIj2CB4NByABmlAISRII1U%2FyY6gwUKhOzkSAA%2BklXAR9sBEciVvgIK47CYmAB3EgAI0hwD%2BywAvuxYAtRv8kGsNtAtrtCYxDv1iSTzpdrrd%2BfchbARWLkUh3p8qT9FdzgECQWCIdDYfCNS8NGiMdsscBcfjCUaTkgyRSLQArWrCJDMpZsjke42rdY0O6CvpPLm%2Bi5XG6Bh5Ugain124Aq76%2FZ6a7Wg8GMxgwuEI%2BOnYCo9GYqk4tpEUQYJzRJGah3UC20hnu1M8L2c2u%2B3kBmVBmMhzsJ8NSqNy2O2gtJtUp0MJ9O6rOwHOG%2FNLE3F82ly3lyvVomrypxASOrcukhupmthDtg%2BxbujuQsfoFONXgvDyO96OMJ8vidrxMPmTf9D3nTN9VzEDYiLM0LWxAhKAgXQaxJJh60pcIm0ZVcbzfAD7y%2FOVf1fWd30lT8BW%2FWBiKglYp0YdVbxWMC9SpZc8zww8YJLcJ4MQ5D9042J0OdV0W1I2AWQ9ABdDUkAAVXhCAPDwMQbC3VodEuJw0AELBsSISgSCcRoUNiRTgiSJJqQEIgLTQSgrJsiA7MErkkGQVzGBI2sNA6CB0nyLdkFcXQQt0iB9NeIyTP5AgMDUsyVk6EgsEoQy0rkDtfTBEh6kaFo2gtBR%2BgUFgAFoWAUcr%2BmKJoWAKegWC%2BegAFZigAOmKQ5ihYCIFAAan6Fh6EGJKAI8RysAAUQrLBCqC8ISrKyrqtq%2BrGuatrOu62q%2BsG4bRv6cbD1ePZUqmBbiqGGqKuGppBiOo6TtiXLqBBFIAE8LKgLcFFa3oXuSvAKwxD7vqU4qAaBphJqSLAAEF0kmUytzeoJxNrKTrBZYAgA%3D%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)

**Comment by schmunk42** [comment]
Did you try `enum_titles`?
https://github.com/json-editor/json-editor#editor-options

Examples:
https://github.com/json-editor/json-editor/search?l=HTML&q=enum_titles&type=code

**Comment by ItSkary** [comment]
Just tried, seems to work as intended. 
Thanks for help, i will extend the schema generation to include that property
