### ISSUE TITLE
Generate schema from JSON

### ISSUE THREAD

**Issue by HussainYousuf** [json-editor/json-editor#1084]
### General information

- json-editor version: last version on https://json-editor.github.io/json-editor/
- is this supported?
- is this being worked upon?

### Expected behavior
generate schema from JSON  

### Example 
input: {name: "John Doe"}
output: {name: {type: "string"}}

**Comment by schmunk42** [comment]
I do not really understand the question, but you might have a look at the meta-schema:
https://github.com/json-editor/json-editor/blob/8f2b5ec5ca5787b3cd1c6b83ee3ec2ef29aeb34c/tests/pages/meta_schema.json

[Online Example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJlSIx4MWAmRpFKtWQCCUqUI0gogiFUJlrttnT0BJKGuMBGNgM/OwASKR1CAGIAem1dfUMkGKVVdTZYKGxnFFM0shAAX0K2eBFseRMIKUgqKVgaOwcnOyoyulQAbRAyipAAXRKQNpEOk2C6Y1BmnJ7y+WK2eLJy8RMZiXmFatr6wQB5KW0pVH8ABmKhvDAwbLJ4Ox2nephG9ccc0BGx7uvbqnuAyG3zsEym9g+hD+dwei2I0lka2mkNyiCgUj0AHMFCCUN1EFRsjwFGYMABra4ADyBSx0K2wSIhLVy0IBDzYTzqDkOx1OFzhaIx8GxVRqzwa4MgSXBnJeb3Q8AgYl4FBgmigyiaKMU6KxRSCiuVqhgmOUjI2qN1wv1w0pEHuml4xtN5u1rMBQwogkQMC9IuRzJA7thcJIMjIrsDgr1HLFXIORzqqAATGc2LjulhsNIFJoI84lvnYAxc0WYAwALTZjByHGyGDyDykTWlUZ4JNsGzCgv2QkKXyU8QZKiD1wA/vlnsiKSNkDUKhkhRkHhwJAYDHQBR4CMqXTZEkkgDUh5JEAgJLARCIVB7GEQylcQ5Ad+QhfquY490xYBxHFfwxnL8FG/ARrTYTEajAAA3QQFAfeBNGybcpH/B9EDJQlZwfSkezNOhZz0GAFE/bRiLIKCCjYT8KKUDcnz/BAFGyRB/1wRBzzYbAREokBZAwvce1kKQyU0MAKHZXiIwEAgPG9ABHWcwE4bhYCg7htjIJRaw5OpZwgTFEAU7ZlA4kAIEEDVGM7BQpBEPBYLYRBNP/LSBAUJQWPcoSHHcozHIcLiXKg7EMlVEKQCgvBaJgTc2EpfCFEEMgEsGDw9AAGTaTENS1QM9F8TEO14wi6FGVA0zMuM9h5JMUGTRghlkSlMuFHL3jy+ACqKzx9FKsYKtlblExOFAAGYLg5CNfCkB52tmaMwPhcM1hACJCupWNdiG3kxoajIUS+douh1IVsVS4YjvGXxJly+arWxOFllWW7CAW8LBoTHbzkaqhNBgAo5sIJSuGJNgyE0P6kjkAAFKqJVQIg5AJTbxVecELQDO7TqKOFrogARfBey1scuVs6HbEbQEGtG7ClVcZThmnxkNPhVXVTVAeJvUhj0JU+GdM0iZO7n0ztB0nSoE1Bc5oMbhhHGhgxi6yrxOZyaTc7cXQa70e1doKZx2lEeemX9aTRqSpVzHNnVk4UfjGqRvqxqyEpcsraZWYzbtyqts+2rxsa1YYuyfYiCF73tjh/2RtGhq4XyqhCsp33UflcBoHpx5GfT3nlTZtrra560eZZiWpcjLGRdte0EPLl0heDBWjfpSvCET5ObR692xiLtWDft6rhpTPbJLdvqI7bIqPsd1BA48YP8aoMPJ9tqO/dn3bFYO5WfhADuNeBS7tZCGWD5OS4hmBlS7CehlYa2pnumpxp+kH+GTDpoxs8f9OswECABJNCNzlmyG0f0nJ4GyLwf+ZBAGfE9lCUBHolgwEgdA36BheAMVmn3JuQwIFkCgVQXgL9daBnwZ2NQ0ESFqGgIIUhOdyGzEoSAAQwgxBCzejiS63QIJqiBLjHeGZ2Ag3EOdO+bdcjX2JEMMhQsZFPntFAaa8AH5p3BAAOgAFRhAiOHXIsR4iEWlCkMw6hSZmSmnUNRTCFHKVBlYlRNj1FciZqAHRejIiGLiDoEx9MzH5GbiAcGkNVwwzsTLVhEQ5IiBgBEYBMtXA2AciAEQ+hYlUB8KfdEIgqBsDDIiQg5BiEKDBFw+6E4sizA+obJaRSZbcPTLwkA/DgGDDhMk2wJhJGuLlMYbo5S36pzcenL+SAf4aLsLA+BiS8HINhKg9BJCukMNCSA/4KCQCEOIbwVZvBtDZEJlEhZ4C0FEOgfsw5VBfB7IqLwGoFBmFIM2Ys7Z5zdlXMJDckhAg0QPLEhs+WBCPmXLcAwiI0gdrzNeWc5ZMDbgAIJECsBlilYiNWTSbZdITZ90xQUhEEZikXOcDzHWtN4DLwMZ0UA4RvEgCMX4xIATUjmH1Hi8FCg6UGIZb4hIBgWXmMsJygly1iVRSKOddJMBMnZJuic2FFt4Byuebkc+Chu4TxQBNMeKqhbqrSr1FWOrQkCoQHIPVJhuXRD5f4owgS2VDEKUSxplTmkq26Pi+wJL+xEP/CUxAFYoCQBJKockVJ3LfMcTWAq0gaYdKGKy2QAAhTSCCLSiJvi3VYfSP7dEyPufaLRhkxLiQk46GxhnyM5lTaOm9AiIOLuFcZ4JlBqm0LNXJVAE5zMbcLRazqVrTiIkMUISaAZ9yafUl1aSMQ2gLem7UU6Z7DzqgQmg64YpJAqdjd+MdUAABYj4ewzV6nqlqG3StleSlAXa92b0YBVQd4r9zHroAAZVEFIDACCEBUq6NMAw+5cjvvLEvAABJ+6cP7+xLsqSUQD1TCAAGF6BL0pJBr9MGi2zC9c+3IAaNXeBvQ28pn9KUrzxIh4DIBUNIHIJ1cDAA1OQeT/Xajw4SlaJTC1pIyXky1d7943snfBhD9ggOzCg9+nsGbFFLghma+AETf7GERtgZGq0qCxPib9Y6tBoPOGGb0yJ+IsNGffu4xQ5mKX/qoxJpDuQADqO5VCaHAwAMVeNgYBOHXrwZYNR2YdG0T3CgMx1jjQ/O5E42KgjPrDUXqCCJhzNGKJcVk9qeTYNFNQ2wLmpm6nNPVtAOlvJO7q4LoqyXS451EC4Bg0kkV07uMJeKsqm9yYPCu0tV14Tp8+7qtDA2aa1WHoZEk2Nm0ZXF1RjE4UDp51rWupJmwP9lHaX6JtcY5l9rx1WBSTae4BwDGbfpYy/lpj9ucqGHIbAG2QDLd5TtpTiAHWyAO7YIYkhGRPYu3a5I46bQruhX2yO2aGR8jODq3A8AySqpCc1/D3rSnJYG327LqXZiw8XDlsJ5r8uRKK/kkZ/S7AREqKJ1bIBlBbZWzGFrhBpwLDYBgP5CPuEELEvAbM4NbOUZpX2yhVPubnQYH9MgAAVHeGbOeWIoK5+xYiNLOJmgV9Onj6c1aGKocGdRJd0IJrNquJc1uZ2/jLTHLa7AYSoBAXgf7Ly8Bm2ppG3aIdInXcbe+kTgByN97vXgC6EdeqvQJm9Qnkc8Z7GRkXi1YAMlmFVuEbSEVcToBMs+nUk5FUkacQ1Pd89j0LygfwyYdftraCirZtv7eO6IM7yLCP8GX0ckKrxPL/u7cB0K1NyKzfShtzeOvlKncu4Rm7r3rclc3yvhR6lQXCD7AcU+U1eX1eu40yTv7tru9vfk+JqruRPupLX+EwnqmJ9b7YDvl7pjMWH8myBt1ITcvn431fzTt+mWvZSAFxfuQAAclPD7GfgTh/igMTjfnTs9j/qYpHI/o5iAF4Nnp3HjkpiplMpAW7tAedrvr/kNoFljoQMmqcugevkTjgY9jAV3r/sLsQUAVsOQe/pQdftQXgXfgEr0AsB0hNkgQAFLvr7CAGQbt64Gd74FXZiGk4fxaBwFZyW4r4q6qIQEeK6JWo0GSGCpBKXyJrKBiS8B1A1AoTtzZ42ArhWT2BpAsI3BQCChwIHo4xAA==)
