### ISSUE TITLE
tranlation options for upload editor

### ISSUE THREAD

**Issue by damon-t** [json-editor/json-editor#1086]
Hi,

is it possible to translate these text for the upload editor?
![image](https://user-images.githubusercontent.com/48483164/148391071-b4942250-9cef-4199-ad09-465a33d6097d.png)

**Comment by schernaya** [comment]
Could you please provide steps to reproduce the issue?

**Comment by germanbisurgi** [comment]
@damon-t: The text is now a translatable string. It can be configured following this section on the [readme](https://github.com/json-editor/json-editor#language-and-string-customization)
