### ISSUE TITLE
Any idea about the library used to achieve this JSON editor?

### ISSUE THREAD

**Issue by hamzahamidi** [json-editor/json-editor#110]
### question
Any idea about the library used to achieve this JSON editor?
![json](https://user-images.githubusercontent.com/22576950/41765345-1c5a2118-7604-11e8-8a16-0539cfe80586.png)

It's available [here](http://schemaform.io/examples/bootstrap-example.html). Does it have any relation with this repository?

**Comment by germanbisurgi** [comment]
json-editor/json-editor !== json-schema-form/angular-schema-form
