### ISSUE TITLE
(QUESTION) How to filter by field?

### ISSUE THREAD

**Issue by marcjordanavila** [json-editor/json-editor#1101]
Is there a way to filter the fields of the JSON? I want to implement a search bar to find out the fields easier. I would like that the editor only showed the fields that contains those text.

**Comment by schmunk42** [comment]
Currently there's no built-in way.

**Comment by ryanhamilton** [comment]
I would also like this. Grafana has a nice UI for filtering editable fields:
![image](https://user-images.githubusercontent.com/7273208/202440912-bb5fdaef-2ad8-4f4b-8c5d-581f9558dbad.png)

**Comment by Hitabis** [comment]
@ryanhamilton did you find a solution? 
Looking for something similar.
