### ISSUE TITLE
markdown fields are not disabled with editor.disable()

### ISSUE THREAD

**Issue by ajboni** [json-editor/json-editor#1107]
Everything else seems to work.

**Comment by schmunk42** [comment]
Could you provide an example schema?

**Comment by ajboni** [comment]
sure., here is an example. https://is.gd/RdGfMd

**Comment by ajboni** [comment]
Temporary workaround:
```js
    if (disabled) editor.disable();
    editor.on("ready", () => {
      setTimeout(() => {
        var editors = document.querySelectorAll(".CodeMirror");
        editors.forEach((editor) => {
          editor.CodeMirror.setOption("readOnly", disabled);
          editor.CodeMirror.refresh();
        });
      }, 100);
    });
```

**Comment by gluxor2000** [comment]
> Temporary workaround:
> 
> ```js
>     if (disabled) editor.disable();
>     editor.on("ready", () => {
>       setTimeout(() => {
>         var editors = document.querySelectorAll(".CodeMirror");
>         editors.forEach((editor) => {
>           editor.CodeMirror.setOption("readOnly", disabled);
>           editor.CodeMirror.refresh();
>         });
>       }, 100);
>     });
> ```

not work

**Comment by gluxor2000** [comment]
> sure., here is an example. https://is.gd/RdGfMd

not work

**Comment by ajboni** [comment]
https://is.gd/YMOGpI

**Comment by schmunk42** [comment]
Might be something for the docs:

```
document.addEventListener('DOMContentLoaded', function () {
  jseditor.disable()
}, false);
```

Or a general note that you need to wait with disabling editors until the document is fully loaded.

@germanbisurgi @ajboni WDYT?

**Comment by ajboni** [comment]
yes,  that was the cause, only knew it because after 2.7.0 it started throwing (#1153) for init. If this is recommended maybe consider updating the examples as well even if no disable action is needed? (https://github.com/json-editor/json-editor#initialize)

**Comment by germanbisurgi** [comment]
This is the way:

```
jseditor.on('ready', function () {
  jseditor.disable()
})
```
