### ISSUE TITLE
change type from template?

### ISSUE THREAD

**Issue by qqsea** [json-editor/json-editor#1110]
The is 'type' menu which provide to chagne type, but the type must within ['auto', 'array', 'string', 'object'], I want to change type which is from custom template, how to deal with this? 

Thank you very much!

**Comment by germanbisurgi** [comment]
I did not understand the question. Can you use Google Translate or Deepl to make the question?

**Comment by qqsea** [comment]
I made custom template which contains some itmes (object), and I can select these items when click menu 'append' or 'insert'. now I also want to select these items when click 'type' menu. But there are only four items within 'type' menu ['auto', 'array', 'string', 'object'], could you give some suggestion?

Thank you!

**Comment by qqsea** [comment]
In another word, now Jsoneditor only enable change type function on ['auto', 'array', 'string', 'object']  four types. I want to enable change type function to the items defined within custom template. How to do this?

Thank you!

**Comment by germanbisurgi** [comment]
I don't know exactly what your goal is. I assume that when you say "template" you mean "editor". Have a look at the readme. JSONEditor have some features that could help you to reach your goal. Especially the dependencies section that allow you to show editors dynamically, or the oneOf feature. Also have a look to the examples in the docs folder.
