### ISSUE TITLE
infoText does not show up with checkbox boolean porperty

### ISSUE THREAD

**Issue by ajboni** [json-editor/json-editor#1117]
Hello, if a boolean is set as checkbox, `infoText` does not appear on the field. works fine as a select.

Reproduction:
https://is.gd/FQMnPH

```json
{
  "type": "object",
  "title": "test",
  "properties": {
    "item1": {
      "type": "boolean",
      "options": {
        "infoText": "Works! "
      }
    },
    "item2": {
    "type": "boolean",
    "format": "checkbox",
    "options": {
      "infoText": "Does not Work! "
    }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Just tried it on the interactive page and seems to work. Do you have an old version of the JSONEditor?

<img width="804" alt="Bildschirmfoto 2022-02-17 um 08 57 56" src="https://user-images.githubusercontent.com/13135260/154430888-a61acaf7-47be-409a-8f7a-236c9aa4cb49.png">

**Comment by germanbisurgi** [comment]
I always test [here](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cW1hRsulCCg0jICFMhUpsGhpAwrdAIyutOwnjAwMzJ4BUhYBGQ0N3gSABUqAA9xCwB1aQBrRABCAAIQAF8Ctnc1ACYfbXMQAKCqEIUSGTIUkBVuDIDEsOg4JFcYWLAE5MIAETAaXMkoXPSpDLzCouLFZTAKXkd7KSiYqykyHj6FKFUGf0CoRChDiAAWZaA===)

**Comment by ajboni** [comment]
Thanks! I think you are right, as I'm using Spectre on my app and it also fails:
https://is.gd/eF4EH2

In conclusion, it fails with:
- Bootstrap 2 
- Tailwind
- Spectre

I'd love to contribute some PRs but I still need time to setup and learn about the codebase. Do you think this could be a good "first contribution" issue?

**Comment by schmunk42** [comment]
> Do you think this could be a good "first contribution" issue?

@ajboni Yeah, give it a try.

**Comment by germanbisurgi** [comment]
Fixed in https://github.com/json-editor/json-editor/pull/1123
