### ISSUE TITLE
Boolean Select Box doesn't return true values

### ISSUE THREAD

**Issue by samirelkhatib** [json-editor/json-editor#112]
When you select true or false and then call the getValue function, you should get the value selected

### Behavior:
When dealing with booleans:
-- Setting the editor value to a previously stored json gives correct values
-- Setting the input value to false and getting it back gives false
-- Setting to true after being false gives false!

Only false can be selected

### Code to reproduce the behavior

```html
<script src="./lib/json-editor.js"></script>

<div id="editor"></div>

<button onclick="getForm()">Get Form Data</button>

<script>
    schema = {
        "type": "object",
        "properties": {
            "Boolean": {
                "type": "boolean",
                "title": "Boolean!",
                "default": false
            }
        }
    }

    var editor = new JSONEditor(document.getElementById("editor"), {
        schema: schema,
    })

    function getForm(schema) {
        console.log(editor.getValue());
    }
</script>
```

Note that when choosing type: "checkbox" the editor works fine

**Comment by haskasu** [comment]
in select editor, onInputChange, 
`
if(this.enum_options.indexOf(val) === -1) {
    new_val = this.enum_values[0];
}
`
enum_options has string values "1" and "0"
but enum_values are boolean values true / false
so the if test is always false

**Comment by KostadinP** [comment]
I have the same problem on the last version too.

**Comment by haskasu** [comment]
I've created a pr here
https://github.com/json-editor/json-editor/pull/117
