### ISSUE TITLE
patternProperties add new item

### ISSUE THREAD

**Issue by coolimo** [json-editor/json-editor#1122]
### General information

Using:

https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

### Expected behavior

Like in array, patternProperty is expected to have "+ item" to add key-value to the dictionary.

### Actual behavior

There is no button to add items in an object .

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "pets",
  "type": "object",
  "patternProperties": {
    "^[a-zA-Z][a-zA-Z_0-9]+$": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "cat",
            "dog",
            "bird",
            "reptile",
            "other"
          ]
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by coolimo** [comment]
Another schema with the same issue; we want to add free style attributes - list of key -value pairs; in this case, because array is defined, "add item" appears. But there is no structured form to edit the key and the value.

```
{
        "description": "A simple form example.",
        "type": "object",
        "required": [
            "firstName",
            "lastName"
        ],
        "properties": {
            "firstName": {
            "type": "string",
            "title": "First name",
            "default": "Chuck"
            },
            "lastName": {
            "type": "string",
            "title": "Last name"
            },
            "telephone": {
            "type": "string",
            "title": "Telephone",
            "minLength": 10
            },
            "attributes": {     
                "type": "array",  
                "items": {
                "type": "object" ,
                    "patternProperties": {
                        "^[a-zA-Z_0-9]+$": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
```

**Comment by germanbisurgi** [comment]
Use the Properties dropdown to add properties.

<img width="809" alt="Bildschirmfoto 2022-02-21 um 10 20 05" src="https://user-images.githubusercontent.com/13135260/154925372-eddfd097-183a-480e-974e-541eac8c3514.png">

**Comment by coolimo** [comment]
That work well; I guess this can be closed.
