### ISSUE TITLE
Set Icon of button defined in schema

### ISSUE THREAD

**Issue by sirijo-uk** [json-editor/json-editor#1128]
### Expected behavior

Be able to set an icon from the defined theme similar to to root.getButton for a button defined in the schema

`var button = jsonEditor.root.getButton('Save Result As File', 'save', 'Save Result As File')`

```
"search": {
                        "type": "button",
                        "title": "Search",
                        "options": {
                            "grid_columns": 2,
                            "button" : {
                                "action": "getData",
                                "icon": "search"
                            }
                        }
                    }
```

### Actual behavior

`jQuery.Deferred exception: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

I had a poke around in the button editor source and it seems the icon is always set to null?

`
const options = this.expandCallbacks('button', extend({}, {
      icon: '',
      validated: false,
      align: 'left',
      action: (jseditor, e) => {
        window.alert(`No button action defined for "${jseditor.path}"`)
      }
    }, this.defaults.options.button || {}, this.options.button || {}))
`

**Comment by schmunk42** [comment]
Might not be available in the demo, since there's no release yet...

**Comment by sirijo-uk** [comment]
> Might not be available in the demo, since there's no release yet...

Just curious how often a 'release' is compiled at https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js
Our project requires self host!

**Comment by schmunk42** [comment]
A release is usually compiled with a tag from our side.

But you can always compile one on your own ;)
