### ISSUE TITLE
UUID fields should be regenerated when copying array items

### ISSUE THREAD

**Issue by ajboni** [json-editor/json-editor#1129]
When cloning an array item which has uuid field, I would expect the uuid to be regenerated.

[Reproduction](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWwhTIVKbBoaQIkTAAm1rTsKIoUmPADmCkjLLiKDZ2jmywUNi6QYieXpEABLYOClJUAI52qY4o7iJUbPZURGQi2IEgeGTwVWQgAL5sSfYAglJSQk7aUSBkbR1hMBHdTfG97YIp6ZlU2bn5IINqyGggzt36XDwKJmYWMFYrTZ0u0e6xvtKy5Ud1t3dsiMpgFLzmplLLC/BQ5mQ8cPAFFBVAxCHgwGAoG52hAACz1OpAA==)

**Comment by germanbisurgi** [comment]
fixed in #1134
