### ISSUE TITLE
[Question/Help] Table Format with Dependency

### ISSUE THREAD

**Issue by PydPiper** [json-editor/json-editor#1137]
Hi, i am battling a formatting issue with JSONEditor table formats. I am not sure if it is possible but i would be curious if anyone had a good solution for help to have a dependency work with tables so it only shows up in the table headers if its selected?

![image](https://user-images.githubusercontent.com/35475223/157337389-b046f00f-cf99-4444-9586-83486fb88e3b.png)

[link to example issue](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJkpUoQpIyy4lCHJ5sutjChrkaEBCmQqU2DQ0gACgEEAJQAVHy0dQkQoKRh4AHMFKngROlQAbXB4W0sKMBAAXQBfNn9g4MCARjDtXQsomPjE5NSUDLNoqrZ2qQqq/LZIWAQnUAATKh14cfgMGG9nAJDCBF1CtZKywIAmaoi66NiEtiSU9JBuna6oaK2d/vBoOCQfccnp2fnQRdCLKFyQNaAtjjIhkETYcxpL5BH6ZbKlcpVCzdTogBHbPTXKQ7QpFNiIZRgCi8DxuKROECxByGHhPBRQVQMQh4MBgKD1MgQAAsAMKQA===)

**Comment by germanbisurgi** [comment]
I think this was purposely so made because you can have a scenario when ATTR1 is hidden in some rows but in others is visible
<img width="774" alt="Bildschirmfoto 2022-03-09 um 08 56 54" src="https://user-images.githubusercontent.com/13135260/157397823-a52fcbf8-18c6-4c39-aaaf-adca3a34c2bd.png">

**Comment by PydPiper** [comment]
Way cool, i did not know about tabs! That works, thanks!
