### ISSUE TITLE
enum_titles sort

### ISSUE THREAD

**Issue by coikoo** [json-editor/json-editor#1149]
![image](https://user-images.githubusercontent.com/93319556/163770023-7b3d4683-5e7b-4489-9bc5-5c3dfff038c2.png)
"ageband": {
      "title": "年龄段",
      "name": "ageband",
      "type": "array",
      "uniqueItems": true,
      "format": "checkbox",
      "items": {
        "type": "string",
        "enum": [
          "01",
          "02",
          "03",
          "04",
          "05",
          "06",
          "07",
          "08",
          "09",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15"
        ],
        "options": {
          "grid_columns": 6,
          "enum_titles": [
            "0~6岁",
            "7~12岁",
            "13~15岁",
            "16~18岁",
            "19~24岁",
            "25~29岁",
            "30~34岁",
            "35~39岁",
            "40~44岁",
            "45~49岁",
            "50~54岁",
            "55~59岁",
            "60~64岁",
            "65~69岁",
            "70岁以上"
          ]
        }
      }
    }

Hi, Use enum_titles.
The sorting is out of order

**Comment by schmunk42** [comment]
Could you please provide an example link.

**Comment by coikoo** [comment]
@schmunk42  https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgIUyFSmwaGkGQDmVPGXgATQ7CjYqhQC56gEPzArdYL4ZBoRNmL1tihBCAcUIykpIQUReBgARxEqAEkoNWQUKClEthIZMnEwlW4AazwwAA8FGFS6dNAgkMJETJh4YwUqeBE6VABtEAAGAEYFAYAmUYBmUYAWUeY2AYA2UYB2UYAOUYBOBSGBvZG2IYnj6eO54+YAXTZIWAQ6kE7u3lt7dP6BgD8lwECdBSrb4nAFnYGMUEgIZLYEbSFDbbfMYzSFjRhI7aQyY/SYohSTdGTTEKGY/GZ4tgzdEzYlsRg/RgUkCMdGMWkgJY/JZMpbopbs1YDP6AU7lAFByIGuAF9pdK2IhlGAKLxdNopOkQK1UpEeHB4AooKpvGEymAoM1IhA5tKgA===

**Comment by germanbisurgi** [comment]
Fixed in #1151
