### ISSUE TITLE
Cant preview markdown: marked.set option is not a function

### ISSUE THREAD

**Issue by ajboni** [json-editor/json-editor#1150]
Whenever I try to preview markdown I get this error. 

```
simplemde.js:1413 Uncaught TypeError: marked.setOptions is not a function
    at SimpleMDE.markdown (simplemde.js:1413:1)
    at Object.SimpleMDE.options.previewRender (simplemde.js:1341:1)
    at Object.togglePreview [as action] (simplemde.js:783:1)
    at HTMLAnchorElement.el.onclick (simplemde.js:1715:1)
```
Im using json-editor  on a create-react app so maybe its failing to require, this is "imported" `marked` object
![image](https://user-images.githubusercontent.com/12578313/164297812-26e2059f-167e-41a3-adf3-3a616ee3ce0c.png)

whereas codemirror looks fine

![image](https://user-images.githubusercontent.com/12578313/164298232-33dac43d-031c-4025-930f-0f34892cd2f3.png)

Any ideas?

**Comment by schmunk42** [comment]
Could you provide an example here https://pmk65.github.io/jedemov2/dist/demo.html or https://json-editor.github.io/json-editor/

**Comment by ajboni** [comment]
Seems to be a webpack config on my project, as I tried to replicate [here](https://codesandbox.io/s/react-playground-forked-094cps?file=/index.js) and worked just fine...
I eventually gave up and just imported the js and css in the HTML...

Thank you anyway!
