### ISSUE TITLE
feature custom checktype or check the type in editor itself

### ISSUE THREAD

**Issue by DebuggerAK** [json-editor/json-editor#1155]
Hi,

the "checkType" function cannot be changed externally. If an editor is supplemented with a different format, corresponding errors are displayed, like "Value must be of type object". 

my schema
- type object
- format custom

current error check
- object: value => value !== null && !(Array.isArray(value)) && typeof value === 'object'

You can add editors, but the dependencies are not pretty. :( Whereby a class inheriation was done quickly!!!

Best regards

**Comment by germanbisurgi** [comment]
Im not sure I understand correctly what you want to achieve. If you want to do Custom Validators, you could check this in our docs: [this](https://github.com/json-editor/json-editor#custom-validation).

If that is not what you want, I'm afraid im going to need a bit more of information.

Cheers

**Comment by DebuggerAK** [comment]
The problem is that I get an error: value is no object, because of my schema is no object. (type = object and schema = custom) 

I created an custom editor with own values, but cannot change the base type check of the core. (object: value => value !== null && !(Array.isArray(value)) && typeof value === 'object')

The custom validation does not manipulate this error, no type parameter.

Apparently it is not intended to overwrite the basic type, an object must always return an object. It would be nice if an editor could manage his own validation.

example
class CustomEditor extend ObjectEditor
.... 
return custom type
....

**Comment by DebuggerAK** [comment]
Background: Simplification of the structure but extended input masks.

An Object has n properties but the value is a short array with n numbers or values. ArrayEditor is to much.

Thank you!

**Comment by DebuggerAK** [comment]
or this idea: Transform pipe for input/output of JSON files, like:
transformCustom(path, schema, type, value, ...)
// do custom
return value

to override the value of objects or something else...

**Comment by germanbisurgi** [comment]
I am still not sure what you are trying to accomplish. Could you provide the schema you are currently using and provide more information about your goal?

> Simplification of the structure but extended input masks.

What do you mean with simplification?

> ArrayEditor is too much.

Why? is the UI? You can use the format property to change that ("tabs", "table")

**Comment by DebuggerAK** [comment]
Of course, see here:
```
JSONEditor.defaults.resolvers.unshift((schema: any) => {
      if(schema.type === 'object' && schema.format === 'location') {
        return 'location';
      }
    });

JSONEditor.defaults.editors['location'] = LocationEditor;

...
center: {
            type: 'object',
            title: 'Center-Koordinate',
            required: [
              'x', 'y'
            ],
            description: 'Abfrage durch beispielsweise Ausschnittsinfo',
            format: 'location',
            default: [1, 2],
            properties: {
              x: {
                type: 'number',
                title: 'Längengrad',
                description: 'Rechtswert/Ostwert/Längengrad/Longitude'
              },
              y: {
                type: 'number',
                title: 'Breitengrad',
                description: 'Hochwert/Nordwert/Breitengrad/Latitude'
              }
            }
          },
...


export class LocationEditor extends ObjectEditor{

  getDefault () {
    return this['schema'].default || []
  }

  setValue (value: any, initial: boolean) {
    console.log(this, value, initial);
    value = value || {}


    console.log('LocationEditor setValue');

    if (!Array.isArray(value)) value = []

    /* First, set the values for all of the defined properties */
    Object.entries(this['cached_editors']).forEach(([i, editor], index) => {
      /* Value explicitly set */
      if (typeof value[index] !== 'undefined') {
        this['addObjectProperty'](i)
        editor['setValue'](value[index], initial)
        editor['activate']()
        /* Otherwise, remove value unless this is the initial set or it's required */
      } else if (!initial && !this['isRequiredObject'](editor)) {
        if (this['jsoneditor'].options.show_opt_in || this['options'].show_opt_in) {
          editor['deactivate']()
        } else {
          this['removeObjectProperty'](i)
        }
        /* Otherwise, set the value to the default */
      } else {
        editor['setValue'](editor['getDefault'](), initial)
      }
    })

    this['refreshValue']()
    this['layoutEditors']()
    this['onChange']()
  }

  getValue () {
    const preResult = super.getValue();
    const result = [];

    if (preResult) {
      for (const [key, value] of Object.entries(preResult)) {
        result.push(value);
      }
    }

    return result
  }
}


```

The problem is the error "Value must be of type object" because of "object: value => value !== null && !(Array.isArray(value)) && typeof value === 'object".

Table approach is too much and the object approach is like {x; number, y: number} too much too. Easy transform and we can use objects to fill arrays with smart inputs.

![Screenshot_2022_04_28_002](https://user-images.githubusercontent.com/51321287/165758251-7afe5355-80be-40b8-9bbb-4cfdb639ad98.png)

**Comment by DebuggerAK** [comment]
Is it possible to make new custom types?

**Comment by germanbisurgi** [comment]
I see. That checkType is there by design. One does not describe an object to and get array. That would defeat the purpose of this library. I would suggest you to use an Object editor and convert the output object data into an array after. You could use the "change" event of the editor and in the callback function to get the value and do the transformation there.

**Comment by DebuggerAK** [comment]
Okay, I will use https://github.com/eclipsesource/jsonforms-angular-seed 

thank you very much
