### ISSUE TITLE
use $ref schema with oneOf/anyOf cause crash

### ISSUE THREAD

**Issue by Djuvl** [json-editor/json-editor#1158]
### General information

- json-editor version: 2.7.0

### Expected behavior
use $ref schema should display same as inline
### Actual behavior
browser crash
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [],
  "definitions": {
    "schema": {
      "type": "string",
      "oneOf": [
        {
          "format": "url"
        },
        {
          "format": "uuid"
        }
      ]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/schema"
    }
  }
}
```

**Comment by yawor** [comment]
I've experienced the same behaviour.

What's interesting, I've found a working example:
```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "schema",
  "$ref": "#/definitions/elementDef",
  "definitions": {
    "elementDef": {
      "type": "object",
      "oneOf": [
        {
          "$ref": "#/definitions/elementListElementDef"
        },
        {
          "$ref": "#/definitions/someOtherElementDef"
        }
      ]
    },
    "elementListElementDef": {
      "title": "List",
      "type": "object",
      "properties": {
        "div": {
          "title": "List",
          "type": "object",
          "properties": {
            "elements": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/elementDef"
              }
            }
          },
          "required": [
            "elements"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "div"
      ],
      "additionalProperties": false
    },
    "someOtherElementDef": {
      "title": "Other",
      "type": "object",
      "properties": {
        "other": {
          "type": "object",
          "properties": {
            "some_prop": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "other"
      ],
      "additionalProperties": false
    }
  }
}
```

**Comment by yawor** [comment]
@Djuvl here's a working version of your example:
```json
{
  "title": "Person",
  "type": "object",
  "required": [],
  "definitions": {
    "schema": {
      "type": "string",
      "oneOf": [
        {
          "$ref": "#/definitions/urlFormat"
        },
        {
          "$ref": "#/definitions/uuidFormat"
        }
      ]
    },
    "urlFormat": {
      "format": "url"
    },
    "uuidFormat": {
      "format": "uuid"
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/schema"
    }
  }
}
```

It seems that if variants of `oneOf` are all also `$ref`s, then it works.

**Comment by schmunk42** [comment]
615de2daefd86873532a13e2b84fc1f00907a293 broke this

```
615de2daefd86873532a13e2b84fc1f00907a293 is the first bad commit
commit 615de2daefd86873532a13e2b84fc1f00907a293
Author: Clément Hurel <clement.hurel@gmail.com>
Date:   Tue Oct 12 16:28:11 2021 -0600

    Json pointer support
    
     * Add all external schemas into $refs
     * Remove internal def from $refs
     * Reading directly from schema for internal pointer
     * Reading from $refs for external ones
     * Editing tests to reflect the changes

 src/schemaloader.js             | 173 +++++++++++++++++++++++++++++-----------
 tests/fixtures/definitions.json |   6 +-
 tests/fixtures/properties.json  |  20 +++++
 tests/pages/references.html     |  45 ++++++-----
 tests/unit/schemaloader.spec.js |  16 ++--
 tests/unit/validator.spec.js    |   4 +-
 6 files changed, 187 insertions(+), 77 deletions(-)
 create mode 100644 tests/fixtures/properties.json
```

**Comment by germanbisurgi** [comment]
But this works

@churel: FYI 

```json
{
  "title": "Person",
  "type": "object",
  "required": [],
  "definitions": {
    "schemaBase": {
      "type": "string"
    },
    "schema": {
      "allOf": [
        {
          "$ref": "#/definitions/schemaBase",
        }
      ],
      "oneOf": [
        {
          "format": "url"
        },
        {
          "format": "uuid"
        }
      ]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/schema"
    }
  }
}
```

Strangely this does not work

```json
{
  "title": "Person",
  "type": "object",
  "required": [],
  "definitions": {
    "schema": {
      "allOf": [
        {
          "type": "string"
        }
      ],
      "oneOf": [
        {
          "format": "url"
        },
        {
          "format": "uuid"
        }
      ]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/schema"
    }
  }
}
```

**Comment by eduo** [comment]
I found this same error in an example that [used to work](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgCVUBzWgZ3gCccUACqomAWwCHdYjgpVsAE1Q9i%2FWsjo4ImbADEc%2FcQFcGAQ3VDkFs1DPH4OcWboAvC1DFR%2BXXo6jwYqhSMkLKUHi0qBAqUCaoeEw8AHTy0NjIgmj8dCq64OnUwBY%2BEIouFrQ4PPkKMEUAJD4AZrpwAMQA9MrNtBD0VRA8nSXR5fCV1XB1UAC%2BCrOU6XA9fQPaNSxQBfXYtIo8xgS1hfU0KMysuIQkZMBLu0U4moObWDuPRQDWqKjIAPraVA4Zr%2FABuZgYxjyW2akJ46FOMEWMyKmWeqByUTe21RZwQFxOn125zQbWAfHUEE4aWJ%2BOeWiGRLp%2BIAFvtlDotgJoXjdvMkfUBZ8UYK4ECAPKtLYAbT5uMFJIQ9CY5L0pgYUAAcmZxMwHiy4GZFIp1hBIQAFLKY3I4uEMBEGulwdHZW3MlnYJBkrYfT1Fb2XbCUvo0%2B7yz5waLGcS6OWKw3AZoanV66YJz4AXSd%2FvFLw2Hv9RXZJuiuh5iKLyIjQpzzqTKd1Qb9uYJPquIeptKrNBVQbg6oYmvNaeANerGbmdcepP71yIpG79YZr0L9Z%2Bf0BMRB4Mh0Lt8MrLOFxNFdJbkeVjDnelo%2FD4djKUAAMmYH6n9TWjSazZbrViYSwe1HS%2FYBXRtbE12JWcoPrQNyU7MNp3raNY1lccZyTO8%2BAAWnMXCR2YDCYGzYjsBXAtfTI4sOTLbl%2BF5Sd%2BQws9W16e94A%2FWDoLbOdEKXVs6GvNVsPgKBCPTItWM9OB8M4ptuMveCtjgfjwyY%2FEhNVFTgFfB8JLHDSTzpaSeOUq58AXO5kPpfMmSojS4A3AEgR3CEoUAqBgKPEz5VM3YL0wrS5wleBWUxcSFPUmTih%2FRk%2FwxACDwdVAbLRf93QcosYKynteIQgRQwEmLULjajyLCzEcIMsjSI0p47JxQKYpLTlywYnz%2FWM480vpSr%2BFvDiuNy7L8p0tSWN6p5%2Br0%2BTR3eMico7Qqu0MqSa38oLCR0yzbmKzCKPshbHOAZyt2BUF3P3XRvI2vybOazS%2B3JABZQxUEi0deu%2FU14oYK1EsyoDD2%2BsCMsgkbE3MhUqy9bblqpJDFuAUr0Pq%2FFxHe6qotqqbbMZJryrgVq6KwCsyO6ky8bgTGfEHBhhuO2GluDFawxYjbQeh8UbkXaLE0OwmTrO1zLr3TzbsnSmhTxTMZlMo1%2BFKcZJiFpTnp0gBBNg2AAUS1AARTXhG1gBJCUAGV9pWFQ1A0RlyU1pWxgqSweCgZRNVkCABBcOR%2BaVbniiVsxEGt4B6GCNWzI1q5tb1w3jbNiV9oDeHyN56z5RdcHPMeopnwttgAAYABZFKe4SdNNzk6F6YgzGIWgAGfoE9qBDiIRxU8wppUGlK4ulWfoCc6fZO8knrQJ8TIVGiCYfbzjDeyrq4OFnhEfbMRfNmpsarhKUOe6VSPxGj0bgvJPWLT1i39ZNrVhF14%2FMPApKK8vQuS4Adg%2Fni%2B4HtgIe%2Fc1ijxnpPWGm0YpfwAIzFz%2FpeAB5JgG9BHq8MeBwjgQKrNLXyRk7oJigUofu9gGDwABm6CGWB4zQKLmXF%2BcAZ4%2BE3gvQImx5Ry0FN1E8rEbZwlMOQ3OOIaH4lGGUV2VR2HpE4bMYAQA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=grid&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=0&disable_properties=1&disable_array_add=0&disable_array_reorder=1&disable_array_delete=0&enable_array_copy=1&array_controls_top=0&disable_array_delete_all_rows=1&disable_array_delete_last_row=1&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1).

I will keep track of the #1233 ticket for resolution.

**Comment by germanbisurgi** [comment]
This issue was fixed. Feel free to reopen.
