### ISSUE TITLE
disable collapse and edit not correctly hidden in firefox

### ISSUE THREAD

**Issue by freddupont** [json-editor/json-editor#116]
First of all thanks for this great project!

regarding the JSON Editor v0.7.28

### Expected behavior
when the option                        
```
                      disable_properties: true,
                      disable_edit_json: true,
                      disable_collapse: true,
```
the corresponding button should be hidden

### Actual behavior
only the button corresponding to properties is correctly hidden the two other are not visible but still take some empty space at the screen

### proposition of modification
like in the property button, hide the control and not the button

I have done the following change which solved the issue (modification in bold)

initial code

// Collapse button disabled
this.schema.options&&"undefined"!=typeof this.schema.options.disable_collapse?this.schema.options.disable_collapse&&(this.toggle_button.style.display="none"):this.jsoneditor.options.disable_collapse&&(this.toggle_button.style.display="none"),
// Edit JSON Button
this.editjson_button=this.getButton("JSON","edit","Edit JSON"),this.editjson_button.addEventListener("click",function(b){b.preventDefault(),b.stopPropagation(),a.toggleEditJSON()}),this.editjson_controls.appendChild(this.editjson_button),this.editjson_controls.appendChild(this.editjson_holder),
// Edit JSON Buttton disabled
this.schema.options&&"undefined"!=typeof this.schema.options.disable_edit_json?this.schema.options.disable_edit_json&&(this.editjson_button.style.display="none"):this.jsoneditor.options.disable_edit_json&&(this.editjson_button.style.display="none"),

Modified code

// Collapse button disabled
this.schema.options&&"undefined"!=typeof this.schema.options.disable_collapse?this.schema.options.disable_collapse&&(**this.title_controls.style.display**="none"):this.jsoneditor.options.disable_collapse&&(**this.title_controls.style.display**="none"),
// Edit JSON Button
this.editjson_button=this.getButton("JSON","edit","Edit JSON"),this.editjson_button.addEventListener("click",function(b){b.preventDefault(),b.stopPropagation(),a.toggleEditJSON()}),this.editjson_controls.appendChild(this.editjson_button),this.editjson_controls.appendChild(this.editjson_holder),
// Edit JSON Buttton disabled
this.schema.options&&"undefined"!=typeof this.schema.options.disable_edit_json?this.schema.options.disable_edit_json&&(**this.editjson_controls.style.display**="none"):this.jsoneditor.options.disable_edit_json&&(**this.editjson_controls.style.display**="none"),

**Comment by schmunk42** [comment]
> regarding the JSON Editor v0.7.28

Did you also try this with the latest version?

**Comment by freddupont** [comment]
I just checked with the online version 

`src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.min.js"`

wich is @version 1.1.0-beta.2
same behaviour

**Comment by pmk65** [comment]
@freddupont What theme are you using?

**Comment by pmk65** [comment]
Closing this one due to lack of feedback.
