### ISSUE TITLE
$ref not working inside oneOf for ajax-fetched schemas

### ISSUE THREAD

**Issue by diegodlh** [json-editor/json-editor#1165]
### General information
The same schema which includes a `$ref` inside a `oneOf` works if used directly, but fails if fetched from an external URL.

### Expected behavior
A schema fetched from an external URL should work just as schema used directly.

### Actual behavior
The schema fetched from an external URL is failing.

### Steps to reproduce the behavior

Direct link to example using schema directly (works): [link](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJEtXqUIZVCgREKAPRmOteAFodasgDppAczMATKWSJQzAJgAGQJsARj8ze3U2KEEIKkIwTm5xNggpSCopWBoNRSpsZLgkXJi4wjIpL0EFGCg1ZDRweCoAeSJUAG1QUvj9RCgpGHgXEABfFi0pKnb9AGIPaaHaosQzRK4eABFpsYBdUfHwKFUpEtjekAqqmrq6BsmduYWiJdgEVfXk7faDw6mARxEMCm7k6eQKPBWIF2bHci3gy3euU+W0e3XOCSSPAUaQyWRgOUaADc5CJeuiyn0BkMRr8DmxEMowBReJl0lIGiAhnUvJCEApjmoLngwGAoP0vBAACwKAFAkG8PCCXhwohkETYcQoNXYRBUWEwRAQATKuXAqjuXg4arauR6hlMlmQPhDVA6+0gSS8MjudyI+ByXi4uL4wnu/WXDhkAAeqAGZINiDIeAKrL9fCs/NtuojfqTKaovCw2AEJl64cTydTwcy2QaFZAearhauQm9vrddtzhub3sqbam0jhp2zHqbBb7VRV+SodU7ObYVADE9byqwEBtDdXRdI6V1vCgkHnY57K/7yrhBTq3pLvHSFHrXcrZ6nl9nhYE/TvzOPVAOQA=)
Direct link to example fetching the same schema from an external URL (doesn't work): [link](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJFKpFCyqFAiIUAelMBzGIigA6K1GUi8IxFSlZ4UKl9tY6pgAmMFQWYIHYyqYAbABMZAAMjAnRCVTRABxUGQDMcRkAjLE5RIEFJRmMGQDsORlEplKUpqVEACwFgQCcsV0FjG0YRAlE1bFEjGMJRZ3VZOk5bQnj0YEppt42tkqqsrYctPAgAL5siMpgFLzuUtLIKCAwXu5kPHBHbI5qVIR4YGBQGxNCBtBQ6ACOIhgOkCvDwgl4gV0ZBE2HEKCIcjcbGCiAgAgREKhMN4OEEqEx2GxiguV0gfCeFKxVDYkl4ZECwVgCDkvAgtwg7lgNCZVJZIDIHDIAA9UFApCJxbiyHhsFRrlzeAcEKLqcrVeqsNgBMYfhjmTjrCq1XyBUKQvdKXqrQb2VImgiOYFdUqXTayO6hLwdNIkVIfZbENb1QGPYiqGrvBGQD5o2641gIOTzWK2LGg555WAqbwoJBk/r/YGEUjEzHjcHLo6LSBKzHq/G6/wyDZGxQfcdjkA=); fails with `reference: https://.../test.schema.json#/definitions/objectDef)' not found!`

```javascript
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "selections": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "$ref": "#/definitions/objectDef"
          }
        ]
      }
    },
    "other": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/objectDef"
      }
    }
  },
  "required": ["selections"],
  "definitions": {
    "objectDef": {
      "type": "object",
      "properties": {
        "value": { "type": "string" }
      }
    }
  }
}
```

Note that nesting the main object into a definition does work when used directly, so I think this issue is not due to #1158. Direct link to example: [link](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJEtXqUIZVCgREKAPRmOteAFodasgDppAczMATKWSJQzAJgAGQJsARj8ze3U2TSkqIkIAYg84mHgYWAREM1lUhXcUtIykDRAc+BKoQQgqQjBObnE2CClIKilYGhLEKmwGuGK0EErqwjIpL0EFdLVkQYQqAHl4lABtUGGa/UQoKVSXEABfFi1Y5ZAk/KJU9P6suq4eABE4w4BdA6PwKFUpCqrNkBjCZTKAzEoxF76C4FG6ZMz3BrPeIfT6xACOIhgsXcqBWih6fUyIHebART0h63+tXqPAUzVa7RgnUGADc5CJNpSRlsdntDijPohlGAKLw2i0pLMQKlQV4eP0FN81AC8GAwFBtl4IAAWBTozHY3h4QS8S5kETYcQoIhybpsdwwRAQAQm/VYqjuXg4SbW21UNhCkVe6C8XK+7B2kCSXhkdwOopyXj06qM5k2iP+wEcMgAD1QOw59sdZDwvTF8d4VgQqHTkYdiBLZaw2AEJk2tcz9cbVCTLRTHVmHaLDdLPaBQhjcZrfuH3Zj4wnsWk+V+4brxdH84mpoJoOnGbYVHgc/HJqwEB9Q8BC7PpBaEd4UEg+/XI7Lp53vVBMZbvBaFEHGcQC7TcP3yL8ewEbY/xFF8qA+IA=)

**Comment by schmunk42** [comment]
is this similar to https://github.com/json-editor/json-editor/issues/1158 ?

**Comment by diegodlh** [comment]
> is this similar to https://github.com/json-editor/json-editor/issues/1158 ?

Hi, @schmunk42. That's what I thought. But I understood that #1158 is about using oneOf/anyOf inside a schema invoked via $ref.

That's why I tried moving the schema to the "definitions" block and refer to it from the root, to see what happened. But it worked! (see my note at the bottom of my original post). So I thought it could be unrelated to #1158. But maybe I'm losing something.

**Comment by StephanSchuster** [comment]
Same here. Any idea already?

**Comment by germanbisurgi** [comment]
Hello @diegodlh, I am looking at the schema-loader component to solve this issue. Unfortunately this component is very complex and i can't tell yet where the problem is.

If you are in a hurry and need this feature ASAP i can recommend using a package called [json-schema-ref-parser](https://www.npmjs.com/package/@apidevtools/json-schema-ref-parser) as a temporary solution.

**Comment by germanbisurgi** [comment]
This issue was fixed. Feel free to reopen.
