### ISSUE TITLE
Empty "oneOf" 

### ISSUE THREAD

**Issue by slow-loris** [json-editor/json-editor#1174]
### General information

We use pretty old version of the json-editor so far (v0.7.27).
I try to update to the current version and ran into an issue with using the oneOf property with and empty list.
The empty list is because the schema is generated automatically and no class was created from the interface.

- json-editor version: 2.8.0

### Expected behavior

In the old version, the select control was just empty and saving the datasheet will result in an empty "services":
![reporting](https://user-images.githubusercontent.com/7202192/174679394-7c7918c0-a377-47ec-8559-e89e44283675.png)

### Actual behavior

The actual behavior will cause the editor to crash. This can be reproduced in the example below.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cW1hRsulCAAKUsBhqIABABEqRGPBiwECiDZ1TYGg1FKikAN0wgtBAtHUIyKSkhBRMzQgBlUIi7ZDYRDwBHESoASSg1ZBQoKWK2Twrg1PMQTPDIhQASKVdCAGIAegATV3dPOCR+hCowIl4AdWkAa3TyiAAlKghpcqkQAF8Dtm6imG7B1ABtELackABdNjJBwbGEOWtIUMDKojlEKjYJBkZHEFgA5lIYOc6ucLL5bMMiApEaMvEhglMZvMlitNhstgFQo1tM19FweApIGjKqAXogyHgzLwsNgBBB/qhqsU9mwpgB5JEoC53A48xTKMAUXihGxSSogdw7Mg8cYpVQMQh4MBgKCIapkCAAFn2eyAA

```javascript
{
   "type": "object", 
   "title": "Process Definition", 
   "properties": {
      "services": {
         "type": "array", 
         "title": "Services", 
         "uniqueItems": true, 
         "items": {
            "title": "Service", 
            "$ref": "#/definitions/oneof_WorkStepReporter"
         }
      }
   }, 
   "required": [
      "services"
   ], 
   "additionalProperties": false, 
   "format": "grid", 
   "id": "procdef", 
   "definitions": {
      "oneof_WorkStepReporter": {
         "type": "object", 
         "options": {
            "disable_collapse": true
         }, 
         "oneOf": []
      }
   }
}
```

**Comment by schmunk42** [comment]
probably related https://github.com/json-editor/json-editor/issues/1158

**Comment by schmunk42** [comment]
The editor should not crash, but the empty `oneOf` should also not be in the schema.
If you remove it, it looks OK the me.

**Comment by germanbisurgi** [comment]
I agree, `oneOf` should also not be in the schema if empty.
