### ISSUE TITLE
a way to setValue of editor and keep the original schema ?

### ISSUE THREAD

**Issue by madruga8** [json-editor/json-editor#1176]
When i set value of editor and theres a new field in the schema that is not in the data this field dont appear on editor so the user could insert this new field...

theres a method to work around it ? 

thanks.

**Comment by germanbisurgi** [comment]
Schema do not change. They are set once and the editor builds form fields based on it. When setting the value you new properties can be added to Object editors unless specified with the `no_additional_properties ` option.

**Comment by madruga8** [comment]
unfortunately even with no_additional_properties, if i load a record with setvalue that dont have the new item in the schema this field wont show and the user is not able to fill it on the form.

**Comment by madruga8** [comment]
> unfortunately even with no_additional_properties, if i load a record with setvalue that dont have the new item in the schema this field wont show and the user is not able to fill it on the form.


unfortunately even with no_additional_properties, if i load a record with setvalue that dont have the new item in the schema this field wont show and the user is not able to fill it on the form.
