### ISSUE TITLE
Styling "Containers" with custom classes

### ISSUE THREAD

**Issue by molster** [json-editor/json-editor#1189]
Hello!

So I was originally  planning to style heavily based on the containers. I saw there was a nice class property, but it looks like that is only tied to very few things.

For context, I have an array of "oneOf"  object types.   Each one is unique, and wanted to style based on the type selected.

It would be great, if the `<div class="card card-body mb-3 bg-light" data-schematype="object" data-schemapath="root.0">` that gets wrapped around them, I could supply a class either from a "class" prop, or even using the title in some form to generate it...etc

Looking over the docs, it looks like I might be able to do something with a custom theme, maybe? Hook into the template for object, and then append a class based on a set class field or title field?

Another way to look at it, is style based on the selected 'switcher' name

**Comment by germanbisurgi** [comment]
At the moment there is no options to assign classes to the containers. If the goal is to give general styling, a CSS attribute selector like [data-schemapath] should do the trick.

**Comment by molster** [comment]
Thanks for the reply!

Yeah the goal in this case is styling based off the selected oneOf , so the path would be unrelated as they are all on the root.0 path

I think in this case I’ll have to fork to be able to get some classes based on the current oneOf.

If I have time to make it a little more dynamic over hard coding some stuff I’ll see if I can throw a pull request back

**Comment by germanbisurgi** [comment]
If the styling of the oneOf is dependent on the type of data the attribute selector [data-schematype] can be used

<img width="773" alt="Bildschirmfoto 2022-08-23 um 12 26 15" src="https://user-images.githubusercontent.com/13135260/186135729-9ef9a863-9bd0-4830-bb88-3069ae2c64ef.png">

**Comment by molster** [comment]
In my case, each of the oneOfs are all of type object , so nothing unique in the type to key off of sadly ( about 30 unique object types) that the array can be filled with any number of in any order.

The attributes were the first thing I checked, as even if it slugged the title you give the object ( to populate the switcher drop down) would be perfect to class off of .

Honestly, the order in which they are in oneOf array would always be the same, so if it was in a switcher even having a data-switcherID ( starting at 0 for first oneOf (or anyOf …ect) would work for styling.

that might be a general enough solution honestly.

**Comment by germanbisurgi** [comment]
Just for information, there is a way to add classes to the inputs though.

```json
"options": {
    "inputAttributes": {
      "class": "some-class"
    }
  }
```
I tried it before but since there is not really supported "parent selector" in css it will be not a css only solution. But a little JS can do the work (to add a class to the parent element of an element with a defined attribute).

**Comment by germanbisurgi** [comment]
A new PR was merged to help with this issue. Here the [docs](https://github.com/json-editor/json-editor#string-editors-input-attributes).

**Comment by molster** [comment]
This seems perfect! 

will pull latest tonight and give it a go.

**Comment by germanbisurgi** [comment]
Glad to help. Feel free to reopen the issue if we missed something.
