### ISSUE TITLE
Ordering in array

### ISSUE THREAD

**Issue by caliph007** [json-editor/json-editor#119]
In a list of objects I have the buttons to move up and move down.

Where is the order reflected in the output-json?
I cannot manage to add the order property and I need it.

**Comment by caliph007** [comment]
This is my simplified schema:

```
type: "object",
            title: "Service",
            format: "grid",
            properties: {
                categoryCode: {type: "string"},
                timestamp: {type: "number"},
                services: {
                    title: "List of Services",
                    type: "array",
                    items: {
                        type: "object",
                        title: "Single Service",
                        format: "grid",
                        properties: {
                            productGroup: {type: "string"},
                            price: {type: "number"},
                            currency: {type: "string"},
                        }
                    },
                }
            }
```

The GUI has moveup and movedown buttons displayed - per default.

But editor.getValue() provides no sorting attribute in the json message.
Can the editor provide a order attribute?
e.g. propertyOrder or other attribute?

**Comment by caliph007** [comment]
Maybe I have trouble getting my issue across:
Currently I get:
```
{
  "categoryCode": "",
  "timestamp": 0,
  "services": [
    {
      "productGroup": "BBB",
      "price": 0,
      "currency": ""
    },
    {
      "productGroup": "AAA",
      "price": 0,
      "currency": ""
    }
  ]
}
```

But when I use it in backend processing in dict or provide json via API to other frontend the ortder can get lost too easily.
I am looking for an attribute such as "order":
```
{
  "categoryCode": "",
  "timestamp": 0,
  "services": [
    {
      "productGroup": "BBB",
      "price": 0,
      "currency": ""
      "order": 0,
    },
    {
      "productGroup": "AAA",
      "price": 0,
      "currency": ""
      "order": 1,
    }
  ]
}
```

Can propertyOrder somehow do that?

**Comment by germanbisurgi** [comment]
> But when I use it in backend processing in dict or provide json via API to other frontend the ortder can get lost too easily

Thats out of our scope i think :/

**Comment by robocoder** [comment]
You should use an object instead of an array where the key is your product group.
