### ISSUE TITLE
Unclear documentation on dependencies and optional schemas

### ISSUE THREAD

**Issue by dhawalbhanushali** [json-editor/json-editor#1191]
I have the below schema

```javascript
{
    "Country": {
        "title": "Country",
        "type": "string",
        "enum": [
            "CA",
            "IN",
            "PL",
            "US"
        ],
        "default": "US",
        "options": {
            "input_width": "20%"
        }
    },
    "State": {
        "title": "State",
        "type": "string",
        "enum": [
            "AA",
            "AB",
            "AE",
            "AK"
        ],
        "default": "AL",
        "options": {
            "input_width": "10%",
            "dependencies": {
                "Country": "US"
            }
        }
    },
    "ZipCode": {
        "title": "Zip Code",
        "type": "string",
        "options": {
            "input_width": "10%"
        }
    }
}
```

I want state to be a text box when the country selected is anything but `US`. For `US`, state should be a dropdown.

Is there any way to do it? `dependencies` does not work as it expects a different property for each condition. What I want is `State` in all the conditions.

**Comment by germanbisurgi** [comment]
A second property is needed:

```json
{
  "type": "object",
  "properties": {
    "Country": {
      "title": "Country",
      "type": "string",
      "enum": [
        "CA",
        "IN",
        "PL",
        "US"
      ],
      "default": "US",
      "options": {
        "input_width": "20%"
      }
    },
    "State_text": {
      "title": "State",
      "type": "string",
      "default": "AL",
      "options": {
        "input_width": "10%",
        "dependencies": {
          "Country": [
            "CA",
            "IN",
            "PL"
          ]
        }
      }
    },
    "State_enum": {
      "title": "State",
      "type": "string",
      "enum": [
        "AA",
        "AB",
        "AE",
        "AK"
      ],
      "default": "AA",
      "options": {
        "input_width": "10%",
        "dependencies": {
          "Country": "US"
        }
      }
    },
    "ZipCode": {
      "title": "Zip Code",
      "type": "string",
      "options": {
        "input_width": "10%"
      }
    }
  }
}
```

**Comment by dhawalbhanushali** [comment]
@germanbisurgi

- I tried this but in this case the title for both is appearing at the same time.
- The order is changing for `State` based on country selection
- Can we not do this with the same property name? I do not want the property name to be anything apart from `State`.

<img width="703" alt="Screenshot 2022-08-23 at 10 44 24 AM" src="https://user-images.githubusercontent.com/3923121/186188525-0fb9d558-7c15-478c-b2dc-0c1c7a90f5a4.png">
<img width="715" alt="Screenshot 2022-08-23 at 10 44 34 AM" src="https://user-images.githubusercontent.com/3923121/186188528-aaadabf2-f71a-401e-ae7c-96615d7db353.png">

**Comment by germanbisurgi** [comment]
If i remember right, this doesn't work with format table because in that case there is the assumption that some items will be or not be present. It's like a db table where null values are allowed

**Comment by dhawalbhanushali** [comment]
Ok. There is no workaround is what you are implying?

**Comment by germanbisurgi** [comment]
I mean that you could set a custom attribute to each input and use JavaScript to get the parent elements (Containers) and add css classes them. It would be neater to have a similar feature for the containers like `"containerAttributes"`

**Comment by dhawalbhanushali** [comment]
Ok. Let me check what can be done. Having the same property for different html form elements, which was my original concern however does not seem possible with this. Thank you for your help @germanbisurgi.
