### ISSUE TITLE
Preserve order customized

### ISSUE THREAD

**Issue by lbrossault** [json-editor/json-editor#1192]
### General information

- json-editor version: 2.8.0

### Expected behavior
I need to get form filled to send result to a MongoDB (new or update document).

### Actual behavior
When I use getValues() data can be retrieved from my Flask route BUT in alphabetic order (JSON limitation).
BUT, when I tested 'Save as file' button option I saw field order has been preserved from json-editor playground !?!

My questions:
- Is it possible to keep order defined using "propertyOrder" setting defined in schema from getValues() function by default ?
- WHy it works fine from 'Save as a file' option from json-editor playground but not when I try to do the same from my internal web site ?

NOTE: 
- Schema is stored on dedicated JSON file (not defined in javascript instance)
- I have always an internal error code 500 (jquery 3.6) but data are sent to my flask route.

### Steps to reproduce the behavior

Direct link to example: https://is.gd/sWTH36

Regards,

**Comment by germanbisurgi** [comment]
> Is it possible to keep order defined using "propertyOrder" setting defined in schema from getValues() function by default ?
No, it has to be set pro editor with a number that dictates it's position in the form.

`WHy it works fine from 'Save as a file' option from json-editor playground but not when I try to do the same from my internal web site ?`
I believe Python works differently than JavaScript. Also there is no guaranty that in JavaScript is the order of the properties will be preserved.

**Comment by germanbisurgi** [comment]
Feel free to reopen this
