### ISSUE TITLE
[Question] is there an option to hide a field in the form?

### ISSUE THREAD

**Issue by rake1191** [json-editor/json-editor#1193]
### General information

i would want to include hidden form fields. but would want the output json to have the hidden fields as well.
i plan to include few token id in the form, and its not something that user might not have to see.
it this possible?

**Comment by schmunk42** [comment]
Just use `"type": "hidden",`

Example:

```
{
  "title": "Person",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "hidden",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    }
  }
}
```
