### ISSUE TITLE
click event listener is not removed with destruction of the editor

### ISSUE THREAD

**Issue by Bene-Kaffai** [json-editor/json-editor#1194]
### General information

A click event listener remains on the document after the editor is destroyed. This is probably due to the _Object Editor_ registering the callback `this.onOutsideModalClick` with .`bind(this)`. 
https://github.com/json-editor/json-editor/blob/6fdb741e6c63d493007f0cd567304ecfa212cb15/src/editors/object.js#L640

In the `destroy` method an attempt is made to remove the event listener (with `this.onOutsideModalClick`). Since bind(this) creates a new function, the removal fails.  

https://github.com/json-editor/json-editor/blob/6fdb741e6c63d493007f0cd567304ecfa212cb15/src/editors/object.js#L1075

In applications that frequently create and close a json-editor, a relatively large number of unneccessary eventListeners accumulate in the document.

- json-editor version: 26.1

### Expected behavior

Calling `editor.destroy()` should remove all active event listeners.

### Actual behavior

A click event listener will continue to exist.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/form-submission.html

See inspector on document with remaining click event listener after calling `window.editor.destroy()` in web developer console.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/8007221/186000027-b2e0182d-64d3-4cfa-9330-6ace4674b60a.png">

**Comment by schmunk42** [comment]
Fixed #1198

**Comment by Bene-Kaffai** [comment]
That was quick. Thank you!
