### ISSUE TITLE
Allow optional fields that are null to still show in the "getValue()"

### ISSUE THREAD

**Issue by molster** [json-editor/json-editor#1199]
After digging in more, I see what is going on, and wonder if there is a solution im not thinking of. And if not, where would be the right place to make an edit?

The issue here is, I have an object, that has an array of objects. In that object, there are a few drop downs that can be null ( a valid option)

**Example**
https://is.gd/u8lYmC 

You can see, when building it for the first time, it works great, you can add a few and all works good. However, as soon as you delete one [which makes for a weird work flow] or load it again all the fields that were null, are gone. (hidden)

This is because `dropdown1` and `dropdown2` were not in the generated json output (I guess cause they were null, and optional).

Is there a way to make it still include the null'ed field in the output?

obviously the first thought was, make it "required"
https://is.gd/4ijxnq

however, that makes it so null is no longer an option. and so if I add null to the list in the enum, that does not give the expected results (even tho null in an enum of strings is what looks like, part of the json schema format)

I know I could set the "type" to an array of "string" or "null" but that really does not make the form look ideal. (have to select a dropdown, to select a dropdown)

------------

The tl;dr
1: Without it being required, is there a property to simply still output all the fields in the schema to the output, even if null? (EG, "include_all_optional"
2: Is there a way to make a required field, allowed to be null in a enum, without the weird type selector if it is a "selector".

if no to the above, is there any  recommendation on what I would change to make the editor still output "optional" fields to the output when null? Im guessing I need to look at the getVal() function, and make it return optional fields that are null. OR update the selector editor, to include null as an option, when its set as required. 

One solution I might due to avoid a fork branch. Is have a string value default of "----" on all fields I want to be null, and simply run a function on the output after getVal to replace all `"---"` with null. This seems to work, as when I return the edited json back with null, it does not know what value to set, and it goes back to the defualt of ---- so might be a good work around.

**Comment by germanbisurgi** [comment]
A combination of the `show_opt_in` option and `required` property do the work. I also added `"formtat": grid-strict` in the [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cW1hRsulCCg0oAAn1ceCiFMhUpsGhpBUAHmToQZgCCUlJCXlo6hGSh4WwwVnTIaJba5uwORsTSsuIWAOZSMAAmALSIUEWOxglmhACifgFmNgDyBtUgUlQAjiIw3cWoANogkjJyAGIwVNhDbOOy2NOzxQBMIAC6bJCwCMmgiMpgFLy7vDDwqJUiVAC+bM6u7jMHYzlTM3MRaYQVRfB8gpdnAkF5CiVeFhsCI6GCUABmO4PEDFFwQYoneAARh+UQs/0uQLYVHgsJGIAAbnJbjZcWxqTCqDYNgyacyEVsdtBQW8IcUoWAYXDkkiUYtPqsNilIulCYDgTz9uCigLobD4WK2GjIJiKPBpZpfgTKkSFKTyShRozafSqeyWQobRyueAlfDQPzBcLNci/ci2EcTrw3C4pMkQJcrGEeKCFFBVAxCHgwGAoP8yBAACwgZFAA===) .

**Comment by molster** [comment]
Hey, thanks for the reply and the example!

‘show_opt_in’ was one of the other options I played with. It however does not include the result of the field in the getValue as null when not selected sadly. It does however make them show in the list regardless ( but has the same ux result of having the type be an array of “string” and “null” ( requiring a click to get into the drop down)

I may just end up going with my workaround as I’m sure this might be an odd use case. ( tho it would still be wonderful if a selector could just have null as a valid required field in the drop down)
