### ISSUE TITLE
Prompt before delete not working

### ISSUE THREAD

**Issue by adiba** [json-editor/json-editor#120]
### Expected behavior
When clicking any delete button, a confirm dialog should show up.

### Actual behavior
When clicking any delete button, the row(s) are deleted immediately.

### Steps to reproduce the behavior
```javascript
const editor = new JSONEditor(document.getElementById('editor_holder'), {
    schema: {
        type: "array",
        title: "People",
        format: "table",
        items: {
            type: "string"
        }
    },
    prompt_before_delete: true // default anyway
});
```
The included script is `https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.js`

**Comment by germanbisurgi** [comment]
yep, he´s right. I made a pull request for this #122. Thanks for notifying, adiba.

**Comment by germanbisurgi** [comment]
this issue can be closed
