### ISSUE TITLE
Reactive value in vue.js - how to fetch current data?

### ISSUE THREAD

**Issue by donmb1** [json-editor/json-editor#1206]
I am using the `json-editor` with vue.js and have a general question

```
import { JSONEditor } from '@json-editor/json-editor/dist/jsoneditor'
...
initEditor () {
      // initi editor via refs
      const element = this.$refs.jsonEditor
      const options = {
        form_name_root: '',
        schema: this.schema,
        // setting the start value
        startval: this.value,
        disable_array_add: true,
        disable_array_delete: true,
        disable_array_delete_all_rows: true,
        disable_array_delete_last_row: true,
        disable_array_reorder: true,
        enable_array_copy: false,
        disable_collapse: true,
        disable_edit_json: true,
        disable_properties: true,
        array_controls_top: true,
        no_additional_properties: true,
        theme: 'barebones'
      }
      this.editor = new JSONEditor(element, options)

      this.editor.on('change',() => {
        // how to catch current value here?
      });
    }
```

My goal is to send the current data of the editor to some other component. Thus I need to fetch the data in the same object structure which `startval` has. How can I achieve that?
Unfortunately the docu does not state how to access the current value of the editor or I misread it. Thanks for help.

**Comment by germanbisurgi** [comment]
`this.editor.getValue()`

**Comment by donmb1** [comment]
@germanbisurgi this works! Thank you. I totally missed it in the docu.

What I found is that the `change` event only triggers when I click outside the editor. Is there a way to catch the value even while typing? like `oninput`?

**Comment by germanbisurgi** [comment]
There is only on change.

**Comment by schmunk42** [comment]
Closing, reopen or create a new issue if neccessary.
