### ISSUE TITLE
Unknown editor for schema / using flatpickr

### ISSUE THREAD

**Issue by donmb1** [json-editor/json-editor#1208]
### General information

- json-editor version: 2.9.0-beta.0

### Expected behavior

Expecting the datepicker to work when working with `type="date"`

### Actual behavior

Uncaught (in promise) Error: Unknown editor for schema {"type":"date","description":"xxxxxx","propertyOrder":1002}
    at t.value (jsoneditor.js?d1f2:14:1)
    at o.value (jsoneditor.js?d1f2:14:1)
    at eval (jsoneditor.js?d1f2:14:1)
    at Array.forEach (<anonymous>)
    at o.value (jsoneditor.js?d1f2:14:1)
    at t.eval (jsoneditor.js?d1f2:14:1)
    at l (jsoneditor.js?d1f2:14:1)
    at Generator.eval [as _invoke] (jsoneditor.js?d1f2:14:1)
    at Generator.eval [as next] (jsoneditor.js?d1f2:14:1)
    at fc (jsoneditor.js?d1f2:14:1)
value @ jsoneditor.js?d1f2:14
value @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
value @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
l @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
fc @ jsoneditor.js?d1f2:14
a @ jsoneditor.js?d1f2:14
Promise.then (async)
fc @ jsoneditor.js?d1f2:14
a @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
o @ jsoneditor.js?d1f2:14
n.value @ jsoneditor.js?d1f2:14
t @ jsoneditor.js?d1f2:14
initEditor @ JsonEditor.vue?d8fb:66
mounted @ JsonEditor.vue?d8fb:43
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
callHook @ vue.runtime.esm.js?2b0e:4235
insert @ vue.runtime.esm.js?2b0e:3158
invokeInsertHook @ vue.runtime.esm.js?2b0e:6390
patch @ vue.runtime.esm.js?2b0e:6609
Vue._update @ vue.runtime.esm.js?2b0e:3963
updateComponent @ vue.runtime.esm.js?2b0e:4075
get @ vue.runtime.esm.js?2b0e:4495
run @ vue.runtime.esm.js?2b0e:4570
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4326
eval @ vue.runtime.esm.js?2b0e:1989
flushCallbacks @ vue.runtime.esm.js?2b0e:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1942
nextTick @ vue.runtime.esm.js?2b0e:1999
queueWatcher @ vue.runtime.esm.js?2b0e:4418
update @ vue.runtime.esm.js?2b0e:4560
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4644
_callee4$ @ api.js?de71:271
l @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
eval @ jsoneditor.js?d1f2:14
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
getItem @ api.js?de71:257
created @ CreateEditItem.vue?844d:80
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
callHook @ vue.runtime.esm.js?2b0e:4235
Vue._init @ vue.runtime.esm.js?2b0e:5022
VueComponent @ vue.runtime.esm.js?2b0e:5168
createComponentInstanceForVnode @ vue.runtime.esm.js?2b0e:3304
init @ vue.runtime.esm.js?2b0e:3133
createComponent @ vue.runtime.esm.js?2b0e:6022
createElm @ vue.runtime.esm.js?2b0e:5969
updateChildren @ vue.runtime.esm.js?2b0e:6260
patchVnode @ vue.runtime.esm.js?2b0e:6363
patch @ vue.runtime.esm.js?2b0e:6526
Vue._update @ vue.runtime.esm.js?2b0e:3963
updateComponent @ vue.runtime.esm.js?2b0e:4075
get @ vue.runtime.esm.js?2b0e:4495
run @ vue.runtime.esm.js?2b0e:4570
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4326
eval @ vue.runtime.esm.js?2b0e:1989
flushCallbacks @ vue.runtime.esm.js?2b0e:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1942
nextTick @ vue.runtime.esm.js?2b0e:1999
queueWatcher @ vue.runtime.esm.js?2b0e:4418
update @ vue.runtime.esm.js?2b0e:4560
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4644
click @ items.vue?f194:268
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
original._wrapper @ vue.runtime.esm.js?2b0e:6961

### Steps to reproduce the behavior

I am using the exact same setup as on https://json-editor.github.io/json-editor/datetime.html but using it within the Vue.js framwork.
The flatpickr css and js is loaded in head.
What I don't understand is how to tell `JSONEditor` that it should use `flatpickr` as the date editor?

I tried to initialize it directly on the element like so:

```
import flatpickr from "flatpickr"
...

initEditor () {
      const element = this.$refs.jsonEditor
      const options = {
        form_name_root: '',
        schema: this.schema,
        startval: this.value,
        disable_array_add: true,
        disable_array_delete: true,
        disable_array_delete_all_rows: true,
        disable_array_delete_last_row: true,
        disable_array_reorder: true,
        enable_array_copy: false,
        disable_collapse: true,
        disable_edit_json: true,
        disable_properties: true,
        array_controls_top: true,
        no_additional_properties: true,
        theme: 'barebones'
      }
      flatpickr(element, {})
      this.editor = new JSONEditor(element, options)
      this.editor.on('change',() => {
        this.$emit('input', this.editor.getValue())
      });
    },
```

However, I get the error above.

When using CDN its also not working "out of the box".

**Comment by germanbisurgi** [comment]
There is no date type in json

```json
{
  "type": "string",
  "format": "date",
  "description": "xxxxxx",
  "propertyOrder": 1002
}
```

[demo](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUKIoUmPADmCkjLLiUIACaXdbGzQyHoceIQAe3nwohTIKiktAHkpJylUAEYABhiAJgBfNkRlMApeIICpZGsjKCCyHncFKFUGQjwwMCh9KTIIABYQRMSgA==)

**Comment by donmb1** [comment]
You are right. Thank you
