### ISSUE TITLE
Can't load spectre css when using in vue

### ISSUE THREAD

**Issue by Dearest** [json-editor/json-editor#1212]
### General information

- json-editor version: 2.8.0
 
### Expected behavior
expect like  https://json-editor.github.io/json-editor/css_integration.html
<img width="902" alt="image" src="https://user-images.githubusercontent.com/7935414/191495586-69239d09-ec5c-474a-a656-283ec0fdca42.png">

### Actual behavior
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7935414/191495623-7ce3cf71-464d-4f1b-aa46-bd71efd44fb0.png">

### Steps to reproduce the behavior

visit https://stackblitz.com/edit/vue-myzc81?file=src/components/HelloWorld.vue
```

**Comment by germanbisurgi** [comment]
JSONEditor has a theme for spectre but does not install spectre per se. You have to add spectre to the project too.
