### ISSUE TITLE
newline character "\n" dropped when using editor

### ISSUE THREAD

**Issue by roberso** [json-editor/json-editor#1217]
### General information

- json-editor version: 2.9.0-beta.0

### Expected behavior
strings with "\n" in them should retain the "\n" character when loaded in
```javascript
{
 "description": "hello,\n how are you?"
}
```

### Actual behavior
the new line "\n" is stripped from the string.  You can enter it back in, but it is dropped when loaded into the tool
```javascript
{
 "description": "hello, how are you?"
}
```

### Steps to reproduce the behavior
import the sample json above and it will drop the \n character.  if you convert it to a string \\n then it save it.  Problem is, \\n and \n are two different things.

**Comment by schmunk42** [comment]
This works for `format: textarea` - am I assuming correctly that your report is about default sting format or single line input-tag?

@germanbisurgi Where and in which cases is the sanitation of `\n` done in the code or is this done by the browser (html input type)?

**Comment by germanbisurgi** [comment]
@schmunk42 Texts for description are treated [hier](https://github.com/json-editor/json-editor/blob/b83d35a6b56d5b2630f639e7844e0edd8d289429/src/theme.js#L601). 

I found a workaround [here](https://stackoverflow.com/questions/9980416/how-can-i-insert-new-line-carriage-returns-into-an-element-textcontent)

schema: `"description": "hello, \r\n how are you?"`

css: `white-space: break-spaces;`

**Comment by schmunk42** [comment]
Another SO issue: https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json

I am not sure how to proceed here... 

> strings with "\n" in them should retain the "\n" character when loaded in

Actually I'd tend to say that your raw JSON should contain `\\n` to represent `\n`. I think we can't really handle this in the editor.
Also, if you enter `\n` manually in an input field it becomes `\\n` in JSON data.

**Comment by roberso** [comment]
> Another SO issue: https://stackoverflow.com/questions/42068/how-do-i-handle-newlines-in-json
> 
> I am not sure how to proceed here...
> 
> > strings with "\n" in them should retain the "\n" character when loaded in
> 
> Actually I'd tend to say that your raw JSON should contain `\\n` to represent `\n`. I think we can't really handle this in the editor. Also, if you enter `\n` manually in an input field it becomes `\\n` in JSON data.

I'm kind of in a catch 22.  I agree it probably should be encoded as \\n, but the tool that I feed it into later (handlebars then Jira) needs it as a \n (a true new line).  I did a quick workaround by doing a scan for \n and replacing with \\n before sending the data into json-editor.  Then when I pull the data out, I reverse it.

**Comment by schmunk42** [comment]
Closing as out of scope, feel free to comment/reopen if needed.
