### ISSUE TITLE
Query: is it possible to store id values, but present labels to user?

### ISSUE THREAD

**Issue by IanMayo** [json-editor/json-editor#1220]
I have a form that is populated from a json document that contains an array of UUIDs.

My users don't work with the UUIDs, they work with the actual product names.  So, I wish to configure the editor to use a lookup table of UUID to human-readable label.  So, the JSON-Editor presents the nice neat labels to the user.  But, these labels are generated from UUIDs, and if the user adds more entries (displayed as labels), then it's the UUIDs that actually get stored.

I've been through the README and the example instances, but haven't found the above described anywhere.

**Comment by schmunk42** [comment]
Have a look at https://github.com/json-editor/json-editor/blob/7aae08475840b6b7bd018690e7b24bd8460c9ff9/README_ADDON.md#autocomplete

Or maybe `select2` - there's nothing out-of-the-box at the moment, but it's certainly a nice feature.

**Comment by IanMayo** [comment]
Thanks for coming back to me so promptly @schmunk42 

After reading up on `autocomplete`, and then `select2`, I understand more about what I'm looking for.

Equipped with this knowledge I was able to find a demo of what I'm looking for:
https://is.gd/K3U6em

This construct can be used to provide separate values and labels for drop-downs:
![image](https://user-images.githubusercontent.com/1108513/198276043-71fed499-4f00-4a3f-9eb5-f6fec8ce719f.png)

**Comment by schmunk42** [comment]
Yeah, `autocomplete` and `select2` might be more useful, when you need to query the label from an API.

**Comment by IanMayo** [comment]
Thanks again for your support @schmunk42 .
