### ISSUE TITLE
Editor textarea is no longer resizable

### ISSUE THREAD

**Issue by petermallett** [json-editor/json-editor#1221]
### General information

- json-editor version: [2.9.0-beta.0](https://github.com/json-editor/json-editor/releases/tag/2.9.0-beta.0)

### Expected behavior

The JSON Editor textarea should be re-sizable as indicated by the UI.

### Actual behavior

The textarea is fixed at 294x164 px dimensions due to the element's style property (+ padding, border = 300x170).

### Steps to reproduce the behavior

1. Go to the example linked below
2. Click the "Edit JSON" button
3. attempt to resize the textarea element with the bottom-right drag handle

Direct link to example: https://json-editor.github.io/json-editor/basic.html

---

This was introduced in c730c4bd when the styles were moved from js to css; these styles previously did not have `!important`.

**Comment by schmunk42** [comment]
While removing the `!important` is fine, the PR does not fix this issue completely.

I tried it manually and I still can't change the width of the textarea.

![Bildschirmfoto vom 2022-11-07 15-36-28](https://user-images.githubusercontent.com/649031/200336917-aef0f076-dbaf-4508-b47d-34439b93cde4.png)

**Comment by petermallett** [comment]
@schmunk42 That example is due to a different issue.
For some reason on this page https://json-editor.github.io/json-editor/ the text area has the style `resize: vertical`.

If you try on the simpler layout example here: https://json-editor.github.io/json-editor/basic.html you can see resizing in both directions working once the `!important`'s are gone.

**Comment by germanbisurgi** [comment]
The `resize` rule comes form bootstrap (4  & 5). Feel free to reopen.
