### ISSUE TITLE
Question about 'form_name_root'

### ISSUE THREAD

**Issue by HeberPcL** [json-editor/json-editor#1223]
### General information

- json-editor version: **latest**

- Question:
Would it be possible not to use this name structure for properties? `(root[ValueInput])`
I'm implementing with **Razor C#** and by default it expects only `ValueInput`.

- My Test
I'm try set `form_name_root` equals `string emply`, in the intention that he removes the `[]`. But not worked.

- Examples:
### Latest
```csharp
<input type="text" class="form-control" pattern=".{3,}" name="root[MessageExample]" aria-label="root[MessageExample]" id="root[MessageExample]">
```

### I would like:
```csharp
<input type="text" class="form-control" pattern=".{3,}" name="MessageExample" aria-label="MessageExample" id="MessageExample">
```

**Comment by germanbisurgi** [comment]
There is no `form_edit_json`. I assume you meant `form_name_root` like in the title.

The `form_name_root` can be changed to another string can not be omited.

**Comment by HeberPcL** [comment]
Exactly, sorry for the slip. I understand, it is a little difficult to integrate with Razor/Blazor.

Don't you think it's possible and interesting to give this possibility?

**Comment by HeberPcL** [comment]
You're right, it would be really hard. 
I will study a way to use it with Razor and if I manage to share it with the community.

Thank you all.

**Comment by mattborja** [comment]
Not sure why this got closed when it hasn't been resolved. I'm also running into the same issue and am either needing to come up with a solution or find another library at this point.

I could go into some more advanced topics of coming up with a custom `[FromJsonRoot("form_name_root")]` model binder for your `[HttpPost]` route, but for the simple fact that this is a question of the client-side library and what appears to be a limitation in the library itself (i.e. we would benefit from a `disable_form_name_root` option as with the other mode overrides available todo), I'm providing the following as a client-side workaround leveraging jQuery to intercept and *append* (duplicate) the outgoing form data with a subset of normalized fields (preserving the original `root[FieldName]`):

```html
<form class="json-editor-normalize" action="..." method="post">
    @Html.AntiForgeryToken()

    <div id="json-editor"></div>

    <div class="form-group">
        <button type="submit">Submit</button>
    </div>
</form>

<script>
  // Requires jQuery
  (function() {
    const formRootNameFieldRegex = /root\[([^\]]+)\]/;

    $('form.json-editor-normalize').submit(function(e) {
      var $self = $(this);
        
      // Enumerate only fields matching form_root_name
      $self.serializeArray()
           .filter(f => f.name.match(formRootNameFieldRegex)
           .forEach(function(f) {

              // Normalize field name (see matching group pattern in formRootNameFieldRegex)
              var normalField = f.name.replace(formRootNameFieldRegex, '$1');
              var $field = $('<input type="hidden" />')
                             .attr('name', normalField)
                             .val(f.value);

              // Scaffold normalized fields as new hidden inputs into current form
              $self.append($field);
          });
      
      // Inspect your form to verify fields are being correctly appended
      // debugger;

      // Explicit return (other conditions may exist where aborting submission is appropriate)
      return true;
    });
  })();
</script>
```

On the server-side, you can then inspect `Request.Form` during debug to verify values are coming through for their fields as you intended:

<img width="726" alt="image" src="https://github.com/json-editor/json-editor/assets/3855027/a302f4d7-9fac-44a7-8581-4c9acaa53154">

Again, it would be better if the library could do this for us (i.e. `disable_form_root_name`) seeing that we also have an ample amount of simple forms out there that are "record-level" (properties of a *single object* being saved) vs. nested, namespaced, collections, etc.
