### ISSUE TITLE
Table in table in table....add item is confusing in such situation!

### ISSUE THREAD

**Issue by fabifabi** [json-editor/json-editor#1225]
i read the doc many time,and perhaps template are solution, but , bit complicate
a scemario is compose of many videos, who have many texts...
"+ item" is confusing in such case : i add new video,or new text ?

Thank you for this library, i loveeeee
another question : where is the shared component ? thats exist ? if i do a beautifull template for, by example, google map chose by mouse but save lat/lg in json, where i can publish it ?

**Comment by fabifabi** [comment]
let s be more simple : "add item" for normal people .... not very good... if i am in video,i want "add a new video"...when i am in pets "add a new pets",etc... for resume, have a contextual name for each tables (videos,projects,pets,cars...).

**Comment by schmunk42** [comment]
Please create an example schema here https://json-editor.github.io/json-editor/ and provide the link.

**Comment by fabifabi** [comment]
Ok, my mistake...if item of table is define inside the array : item appear
but if item is a $ref, the name of the $ref is take,not "item"...
