### ISSUE TITLE
Schemaloader $ref parser is broken

### ISSUE THREAD

**Issue by germanbisurgi** [json-editor/json-editor#1233]
### General information

After a big change in the schemaloader.js $ref pointers parsing is not working correctly. It's broken since commit https://github.com/json-editor/json-editor/commit/615de2daefd86873532a13e2b84fc1f00907a293 .

@churel could you help us to find the issue?

Simptoms: 
 - Refs are partially or completely not being tracked in Schemaloader
 - infinite recursion breaks page

- json-editor version: 2.8.0 but the bug is there since 2.7.0

### Expected behavior

 Schema loader to track all $ref pointers and expand schemas correctly

### Actual behavior

`$ref` pointers are partially or completely not tracked by schemaloader.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

### Example 1

```json
{
  "title": "Person",
  "type": "object",
  "required": [],
  "definitions": {
    "schema": {
      "type": "string",
      "oneOf": [
        {
          "format": "url"
        },
        {
          "format": "uuid"
        }
      ]
    }
  },
  "properties": {
    "name": {
      "$ref": "#/definitions/schema"
    }
  }
}
```

This will result in an infinite loop that breaks the page

### Example 2 

Testing with this [meta-schema](https://raw.githubusercontent.com/json-editor/json-editor/master/docs/meta_schema.json) 

2.6.1 is working like expected
<img width="448" alt="v2 6 1 editor" src="https://user-images.githubusercontent.com/13135260/205029335-cf9e31ad-db1d-4e96-8186-209ac7f5274c.png">

`schemaloader.$refs`
<img width="688" alt="v2 6 1 refs" src="https://user-images.githubusercontent.com/13135260/205029359-0ff2348c-8a1b-410d-88c1-71cb90618dea.png">

2.8.0 is showing error messages due to missing pointed schemas being parsed
<img width="432" alt="v2 8 0 errors" src="https://user-images.githubusercontent.com/13135260/205029907-007a04dd-d5cf-4d7b-a485-f1663ce42ac4.png">

`schemaloader.$refs`
<img width="697" alt="v2 8 0 schemaloaderrefs" src="https://user-images.githubusercontent.com/13135260/205029932-a344ae5e-95cf-4253-90d8-403f2acdb474.png">

**Comment by robocoder** [comment]
Linking: #988 / #1082 / #1158

**Comment by karol-gro** [comment]
Hi,
from what I understand, #1158 and example 1 of this issues are just duplicates and refer to the same problem with the same input, aren't they?

**Comment by germanbisurgi** [comment]
This issue was fixed. Feel free to reopen.
