### ISSUE TITLE
Array type fields are not rendering 

### ISSUE THREAD

**Issue by kittu444** [json-editor/json-editor#1235]
### General information

- json-editor version:  2.9.0-beta.0

### Expected behavior
We have array of fields. when we try to replicate a field, the fields in array fields create Html text fields.

### Actual behavior
We have array of fields. when we try to replicate a field, the fields in array fields are not showing what we had in schema.

### Steps to reproduce the behavior

Direct link to example: 
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJEtXqUIZVCgQUAelMda8ALQ61ZAHTSA5qYAmUskSjWADABZTO1kAYgUoQQgqQjBObnE2CClIKilYGg0QeDIGTIiowkQoKRh4ZxAAX0SqKGQ0EHzo/TIpT0EFGCg1OoBtUEaYuJ4FJJS0mAz6ganIpsVi0vKqrJym/tnChbLK5akqAEcRGD23VB6GjbZs3IBdCrvdg6OTs5Xc6tqQO7ZEZTAKXipZJSOogUpdTw8ODwcK6OZ4MBgWrFMgQfw7IA===

#### Below is the Schema
*Using the below schema I try to add more than one two pet since it is an array type, I can add first(0 index)pet fields are showing. again if I try to add another pet then the fields not rendering*
```{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "pets": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "name",
    "pets"
  ]
}```

**Comment by germanbisurgi** [comment]
Items should be an object, not an array

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "pets": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "name"
        ]
      }
    }
  },
  "required": [
    "name",
    "pets"
  ]
}
```
