### ISSUE TITLE
what the relationship between https://github.com/json-editor/json-editor and https://github.com/josdejong/jsoneditor

### ISSUE THREAD

**Issue by Tridu33** [json-editor/json-editor#1246]
### General information

what the relationship between https://github.com/json-editor/json-editor and https://github.com/josdejong/jsoneditor ?

I found they are too similar fot me to distinguish .

**Comment by germanbisurgi** [comment]
json-editor/json-editor generates forms

**Comment by schmunk42** [comment]
> json-editor/json-editor generates forms

especially from `json-schema`s
