### ISSUE TITLE
Editor crashes when using a recursive json-schema

### ISSUE THREAD

**Issue by charel-felten-rq** [json-editor/json-editor#1256]
### General information

- json-editor version: I dont know, the one of the online editor on 2023-01-04

### Expected behavior

Input form where I can input the fields

### Actual behavior

Editor seems stuck, no input form appears

![image](https://user-images.githubusercontent.com/116723764/210575541-e38b6389-ca2f-4114-ab95-5c8c81333ab5.png)

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIANBVEERdKdlx4KIUyFSmwaGkBjLi0IACRSqRQgGIAegATHxh4GFgERACAYVcqAHNpQRAAX1S2bwBHERhvINQAbWdXEABdNhCiMIi4JCc4qETkpy0dQkbmqRS2IxNCME5ucTZrW3sYR3d4MgZWiPazADlZ3V7jU0UoKTCEtLYsEPntTZiwI/X+s0Rt3f2QCDJveDdQLx9/YNDwyKRY+KS3TSGRA2Vy+SKIBmcwO510ZXSIMQyjAFF4dhsUmQZjCTSkZB4dUMqjmZjwYDAUBu+IgABZgUA

I have the following python (pydantic) code:

```python
from __future__ import annotations
from pydantic import BaseModel

class Category(BaseModel):
    name: str
    code: str
    parent: Category | None = None

class X(BaseModel):
    cat: Category

x = X.schema_json()
```

this generates the following schema (**Note:** its possible this schema is wrong, as I am unable to generate this same schema in another container (I dont know why, the pydantic versions are identical). However, I have seen that recursive definitions seem to be allowed by json-schema so maybe the schema is right...)

```json
{
    "title": "X",
    "type": "object",
    "properties": {
        "cat": {
            "$ref": "#/definitions/Category"
        }
    },
    "required": [
        "cat"
    ],
    "definitions": {
        "Category": {
            "title": "Category",
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "type": "string"
                },
                "code": {
                    "title": "Code",
                    "type": "string"
                },
                "parent": {
                    "$ref": "#/definitions/Category"
                }
            },
            "required": [
                "name",
                "code"
            ]
        }
    }
}
```

I put this into the editor and no input appears and it seems frozen / stuck.

**Comment by charel-felten-rq** [comment]
Potentially related to #795

**Comment by robocoder** [comment]
This isn't a regression by 615de2daefd86873532a13e2b84fc1f00907a293 -- before/after that commit, the schema loader dies with "RangeError: Maximum call stack size exceeded"

**Comment by schmunk42** [comment]
@robocoder Would the solution be the same as in https://github.com/json-editor/json-editor/issues/795#issuecomment-1375491588

**Comment by robocoder** [comment]
I'd treat them as separate issues for now since they exhibit different behaviour. In #795, it errors during the schema load. Here, the schema loads but it hangs after pressing the button to add an item.

**Comment by charel-felten-rq** [comment]
Actually I think they are the same issue, its just that the code that makes the editor hang is run immediately in my case, but its only run after the button press in #795. Because when I played around with this, I had a more complex object where this recursive object was only one property, and then the editor also only got stuck once I added this property.

**Comment by germanbisurgi** [comment]
The schema it self is self recursive. To avoid the max stack call error the editor option `max_depth` can be used.
@czue: That pinned version (json-editor@2.6) behaves the same as the new (fixed version).

**Comment by niebert** [comment]
May be problem is related to reserved work 'parent' that is used in the editor hierarchy for implementing the tree chain of JSON editors  and the variable is required to access parent JSON editor from the child editor and for propagating (bubble up) the onChange() events . Does changing 'parent' to 'myparent' solve the problem for recursive schema?
