### ISSUE TITLE
Make corresponding input 'readonly' instead of 'disabled' for 'readonly' option

### ISSUE THREAD

**Issue by adiba** [json-editor/json-editor#126]
### Expected behavior
When setting `"readonly": true` on a property, the input should be readonly, i.e. the input's value should be immutable but still copyable.

### Actual behavior
For instance, the `disabled` property of an `input` with `type="text"` is set. The text is therefore not selectable or copyable.

### Steps to reproduce the behavior

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "readonly": true
    }
  }
}
```

**Comment by pmk65** [comment]
Looks like this have been fixed. [Test Link](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QCsDOB7AdgAlQYwAtYBbAQ21gA9TiAHOEAGnAE9b4l0AjZWPMJiFoAndO2GRYqRKCo16HUGDYcQqMMIiYA5oIAmsAGakArtAFIW6E9jykceMS2xgCEVC6oDmw2KT1Y0CyIGiawAL6RQA=&value=N4IgpgHghgtgDgGzCAXCAngewK4AIDGUAdgZnOrgC4AWAlgM5WSUgC+QA===&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) 
I wish people would close issues once they are solved. 😞
