### ISSUE TITLE
Is there a way to set HTML attribute: autocomplete to autocomplete="off" on given schema  <input />

### ISSUE THREAD

**Issue by mjhn** [json-editor/json-editor#1261]
### General information

- json-editor version: @latest

https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

**HTML attribute: autocomplete**

I would like to be able to set  autocomplete="off"

eg:
`<input type="text" class="form-control"  autocomplete="off"  id="" name="root[string-sample]" aria-label="root[string-sample]">`

Any suggestions on how this could be acceptably achieved - without going to browser settings.

### Expected behaviour

N/A

### Actual behaviour

N/A

**Comment by germanbisurgi** [comment]
[inputAttributes](https://github.com/json-editor/json-editor#string-editors-input-attributes)

**Comment by germanbisurgi** [comment]
Welcome :-)
