### ISSUE TITLE
transform editor output from formatted editor input

### ISSUE THREAD

**Issue by mjhn** [json-editor/json-editor#1263]
### General information

- json-editor version: @latest

A Question.

Is it possible to accept a format via the editor input and transform that output and have it reflected in the output.

ie:  The user enters $20.00 into the editor. I need to have that value represented in cents, ie: 2000 in the output.

Any guidance would be greatly appreciated.

**Comment by germanbisurgi** [comment]
JSONEditor does not perform data conversions. However, you can use getValue(), convert the data and then submit it.

**Comment by mjhn** [comment]
Thank you again
