### ISSUE TITLE
Need help on defining key-value pairs dynamic in json schema

### ISSUE THREAD

**Issue by kittu444** [json-editor/json-editor#1265]
### General information
I have a json which have the key : value pairs trying to convert to json schema. Can you help me how can I have the values dynamic or editable for key, i.e: test, testa,testb - needs to be dynamic similar to testc, testd for the below json.

### Expected behavior
It needs to be dynamic for both key : value

### Actual behavior
currently key is getting the fixed or constant value
### Steps to reproduce the behavior
1) I have tried converting the below json with the help of json-schema conversion

```
{
 "test":{
    "content":{
        "testa": "testb",
        "testc" : "testd"
      }
    }
}
```
2) Direct link to example: https://json-editor.github.io/json-editor/

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWwhTIVKbBoaQUGlABM1rTr0GeCk2YswraEFnhbQKdtXRR2LndjUx1vX007MhCXcMQoKRh4AHMQAF82WzSMZLDFdMyc3Krq/MVlMApec1MpZHDM2ykyHjh4BShVBkI8MDAoNK6IABY83KA===

**Comment by schmunk42** [comment]
You could use additional properties, like so:

![Bildschirmfoto vom 2023-01-16 17-40-36](https://user-images.githubusercontent.com/649031/212728374-fdf3decb-ef01-4496-8ac7-ac05a1987ff9.png)

**Comment by schmunk42** [comment]
You can't **edit** the key, only create new ones or (de)select existing ones.

**Comment by kittu444** [comment]
thanks @schmunk42 I'm trying to edit the "title" as well in the form, can I know if we have any option or properties in schema to make it editable. For example:

```
{
  "test2": {
    "content": {
      "key":"value",
    }
  },
  "test3": {
    "content": {
      "key":"value",
    }
  }
}
```

**Comment by schmunk42** [comment]
Actually the schema is meant to be static.

But you can create json-schemas with the [meta-schema](https://github.com/json-editor/json-editor/blob/master/docs/meta_schema.json).

See [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJlSIx4MWAmRpFKtWQCCUqUI0gogiFUJlrttnT0BJKGuMBGNgM/OwASKR1CAGIAem1dfUMkGKVVdTZYKGxnFFM0shAAX0K2eBFseRMIKUgqKVgaOwcnOyoyulQAbRAyipAAXRKQNpEOk2C6Y1BmnJ7y+WK2eLJy8RMZiXmFatr6wQB5KW0pVH8ABmKhvDAwbLJ4Ox2nephG9ccc0BGx7uvbqnuAyG3zsEym9g+hD+dwei2I0lka2mkNyiCgUj0AHMFCCUN1EFRsjwFGYMABra4ADyBSx0K2wSIhLVy0IBDzYTzqDkOx1OFzhaIx8GxVRqzwa4MgSXBnJeb3Q8AgYl4FBgmigyiaKMU6KxRSCiuVqhgmOUjI2qN1wv1w0pEHuml4xtN5u1rMBQwogkQMC9IuRzJA7thcJIMjIrsDgr1HLFXIORzqqAATGc2LjulhsNIFJoI84lvnYAwALTZjByHGyGDyDykTWlUZ4JNsGzCgv2QkKXyU8QZKi91wA7swBgKERSWsgahUMkKMg8OBIDAY6AKPARlS6bIkkkAaj3JIgEBJYCIRCoHYwiGUrj7IGvyEL9VzHHumLAOI4T+Gk/fCg/ARrTYTEajAAA3QQFFveBNGyDcpB/W9EDJQkp1vSkOzNOgpz0GAFDfbQCLIcCCjYN9SKUVd72/BAFGyRAf1wRATzYbARDIkBZFQ7cO1kKQyU0MAKHZLiIwEAgPG9ABHKcwE4bhYHA7htjIJRKw5OopwgTFEFk7ZlFYkAIEEDU6NbBQpBEPAoLYRA1J/dSBAUJRGJc/iHBc/S7IcdjHPA7EMlVQKQHAvAqJgNc2EpHCFEEMhYsGDw9AAGTaTENS1QM9F8TEWy4vC6FGVA02MuM9h5JMUGTRghlkSk0uFTL3my+Bcvyzx9CKsZStlblExOFAAGYLg5CNfCkB4WtmaNgPhcM1hACI8upWNdn63lhtqjIUS+douh1IVsSS4Z9vGXxJiymarWxOFllWK7CFmkK+oTTbzjqqhNBgAppsIeSuGJNgyE0b6kjkAAFcqJVQIg5AJNbxVecELQDa6jqKOELogARfEey0McuRs6GbQbQD65G7ClJcZWhynxkNPhVXVTU/oJvUhj0JU+GdM18cOjn0ztB0nSoE0+bZoMbhhTGhlR07irxOYSaTE7cXQC6Ue1dpScx2k4YeyWdaTOrCsVtHNhVk5EfjSrBpquqyEpUdzaZWZjetsr1reqqRrq1ZIuyfYiH5j3tmhn3BqG2q4Ryqg8rJr2kflcBoBpx46ZTrnlWZ5qLfZ61OcZ0XxcjdHBdte1YJLl1+eDWX9fpMvCDjhObU6l2xnz5XdZtiqBpTbaxOd7rQ6bfLXrt1A/Y8AOcaoYOx6t8Pvanra5d2hWfhAVvVeBM6NZCSXd5OS4hgBxS7HuhkofW+nugpxp+j7mGTGpowM7vlOswECACU0Ou0s2Q2m+vZPA2ReA/zIH/T4bsoRAI9EsGAYCIFfQMLwWiU1u71yGKAsg4CqC8EflrQMODWxqAgoQtQ0BBBEMziQ2YZCQACGEGIfmz0cRnW6KBNUQIsabwzOwQG4gTrX2brkC+xIhjEP5pI+89ooATXgLfZO4IAB0AAqMIEQQ65FiPEPC0oUhmHUETYy406jKPobIhSQNzGKMsSork9NQCaO0ZEPRcQdCGJpsY/IDcQAgzBkuSG1jJZMIiNJEQMAIgAMlq4GwtkQAiH0FEqgPgj7ohEFQNgYZESEHIAQhQYJ2E3RHFkWYr09bzXyZLDh6YuEgB4QAwYcIEm2BMGIpxcpjDdBKc/JOziU7vyQJ/VRdgoEwLidghBsIkEoMIe02hQTAH/EQSAPBBDeBLN4NobIeNwmzJAcg/BECdl7KoL4bZFReA1AoAw+Bay5kbJOVs85hJLmEIEGiW5wlVky1wa8s5bhaERGkJtGZTzjkLMgbcX+BJ/nALMfLQRSyaQbLpIbbuaLckIgjAU05zhOaaypvABeujOigHCB4kA+jvGJF8akcw+psUgoUNS3RtKvEJAMIykxlg2W4oWgS8KRQTopJgGkjJl1DlQtNvAaVDzcgnwUB3UeKBRrD0VfzFVyUuqK01UE3lCA5DapMBy6I3KfFGD8cyoYeT8V1LKQ0xW3QcX2EJd2fBP5CmIBLFASAJJVDkipC5D5diKy5WkJTVpQwmWyAAEJqVgRaIRl9G6rG6a/bomQdw7RaAMyJ0TYkHQ2AMmRbNyYRzXoEOBBcQojPBMoNU2gppZKoLHaZdaBZzQdYtCc+EhihHjb9bu9SamOuSRiG0uaU3anHZPAe1VcE0BXJFJIpSMYv0jqgAALPvV2qb3WdTNbWiVUqSUoHbdutejBSp9pFTuA9dAADKogpAYFgQgclXRpgGB3LkF9o554AAI30Tk/d2edZSSh/oqYQAAwvQeelIwPvsg/m2Y7qH25F9aq7wl7a0lLfmSxeeI4MAZAEhpA5A2ogYAGpyGyT67U2G8WLUKXm5JqTslmuvTvS9Y6YOwfsP+2Y4GP0dlTXI+coNjXwFCV/YwcNsAIyWlQKJMSvoHVoBB5wAyulhPxOh/TL8XGKBM6Sn95HRPwdyAAdU3KoTQIGABirxsAAMw09GDLAKOzGo2ie4UAGNMcaN53IbHhW4c9Xq09QRBO2co6RdiUntQyeBnJ8G2As30xU2pitoAUvZM3RXWdpXC6XBOogXAkH4mConRx2LBUFWXuTB4J2Zr2sCaPt3FVoYawTQq7dDIYnhs2mK3OqMwnCitJOhap1hM2DfrI1SnRlqDEMptSOqwiSbT3AOLotbNK6U8qMTttlQw5DYFWyABbXLNvycQLa2Qu3bBDEkIye7p3rXJBHTaRdELu1hwzQyPkZxNW4HgGSJVgSGs4Y9UUhLvXu0ZaS7MKHc5MvBJNTlsJ+WcmDJ6XYCIlQhNLZAModbi2YyNcIBOBYbAMDfNhxw3Bwl4DZhBlZsjlLu1kPJxzE6DBvpkAACqb1TWzsxFAnM2OEapBxk1cspzcTTyrQxVAgzqGL6huMpvl0LsttOH9JZo8bXYVCVAIC8G/WeXgk3lPww7aDpEK6DY3zCcAaRXut68FnbD9157eOXv4wjzjHZiOC7mrABksxytwmabC9idBRnHzavHfKYjTh6s7jn4eeeUD+GTJrltbREXrKtzbu3RAHdhdhzgs+dl+V2Gu7z47nKftbb+/ypNCLZvG+lJby81eyX28d7DZ37um7y8vufUjFL/OEH2LY+8Rrssq6d6pwn32rXd+ezJkT5XchvaSevkJeOlOT+32wXfj2jFoqP2NwDzrAlZYv5v6/am7/0qeykXzS+uQAAcuPJ7Ofrjp/igATrftTg9r/kYmHE/nZiAF4Bnm3NjvJopuMlAc7jASdnvn/v1n5ujoQAmkchgRvvjrgXdrAV3n/gLiQcAVsBQR/lQTfjQfgffr4r0AsK0qNsgQAFIvr7BAFgYt54Gd4EHnbiFE6vxaDwHpxm6r6K5KKQGuJaLmq0FSF8r+JnxxrKDCS8B1A1CIQtwZ42CLjmT2BpCMI3BQCCjQK7qYxAA)
