### ISSUE TITLE
required properties need to be contained within defaultProperties 

### ISSUE THREAD

**Issue by simontaurus** [json-editor/json-editor#1275]
### General information

- json-editor version: 2.9.0-beta.1

- schema with non-overlapping required and defaultProperties 

### Expected behavior

I'm not sure if this is intended, but I would expect that both required and defaultProperties  are shown.

### Actual behavior

Only defaultProperties  are shown. Editor displays "Object is missing the required property 'id'"

### Steps to reproduce the behavior

shows "Object is missing the required property 'id'":

[minimal example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWylUAjiJgmAJqgDaIGDYC6bK1SJkR2KAAUpkKilYGjsQeDIGEBcQCH8dIJgQtAcbZK0dQkQoKRh4AHMQAF82cMi07V0URWzcgsL6tkRlMApeQP8pZCrcqECyHjh4BShVMpA8MDAoLKkyCAAWBRNzSyorXjxBXjcPL3EUD2xEKlcYRAgBLeWLa14cQVRD48bm1sg+XMe5Z7CwXjIrFYYLAEHJeLEAgkkk8TiAyBwyAAPL5HWFAxBkPDYKhtIF8Di0IYHb5os6Y7G8LDYAQQY4on7o8k4iHxYJdGGnDFYnFkKSzLYA1IckCM7n/PlCXgmaRuKT00lcim8/nbKjY3rythUcJi5WSrAQB7E1FsPVbLDwbJgI68KCQTUism6iVbNzqnnUqUtdkkzlM8Uqt1UXr8MhZL0UeX1IA===)
```javascript
{
  "type": "object",
  "required": [
    "id"
  ],
  "defaultProperties": [
    "name"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    }
  }
}
```

while duplicating 'id' in defaultProperties leads to the expected behavior:
[working example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWylUAjiJgmAJqgDaIGDYC6bK1SJkR2KAAUpkKilYGjsHGzZ4MgYQFxAIfx0gmBC0MI0QLR1CRCgpGHgAcxAAXwio3VTMisVc/KLihrZEZTAKXkD/KWQUB3goQLIeOHgFKFVonrwwMCgcqTIIABYFE3NLKitePEFeNw8vcRQPbEQqVxhECAEd1YtrXhxBVGPTppa2yD5857lXkEleGQrFYYLAEHJePEAkkUi8ziAyBwyAAPH4neEgxBkPDYKjtEF8Di0EZHX4Yi7Y3G8LDYAQQU5ov6Yyl4qGJYLdOHnLE4vFkKTzHZAmyk9HclmAgVCXgmaRuKSM8k8qn8wW7Ki4/qKthUSK8yVqrAQJ6iv6q6VYPr+E68KCQbUgZn6807Nyavm0mWtTlk8XOqWujVUfr8Mg5L0URUNIA===)
```javascript
{
  "type": "object",
  "required": [
    "id"
  ],
  "defaultProperties": [
    "id",
    "name"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    }
  }
}
```

this might be relevant if an referenced schema is not under direct control and when option display_required_only is set:
[example with referenced schema](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWznYA8kVQBtTdt0p2XHgoAmNDFJjQ48QlQAeUFRS8HIABEqqsqGSUKEi8K5Soc4wUoahWPBQUmDybGkAjiKpVM5WIDBlALpsEDk6UrA0GhVlaCBaOoSI2TDwAOYgAL4jNSCuRGQi2FAACvVBTcgoliAhDCBjdZCLMM3t63Y2XfY9HgPDI2yIymAUvEE5UssVWUFkPN4KUJF2IHhgMBQM5kCAAFkuQA==)
```javascript
{
  "type": "object",
  "allOf": [
    {
      "type": "object",
      "description": "external schema not under direct control",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  ],
  "defaultProperties": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

here, the 'local' schema has to list a property from the referenced schema in defaultProperties:
[working example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWznYA8kVQBtTdt0p2XHgoAmNDFJjQ48QlQAeUFRS8HIABEqqsqGSUKEi8K5Soc4wUoahWPBQUmDybGkAjiKpVM5WIDBlALpsEDk6UrA0GhVlaCBaOoSI2TDwAOYgAL4jNSCuRGQi2FAACvVBTcgolq0KIQwgY3WQizDN7Rt2Nl32PR4DwyNsiMpgFLxBOVLLFVlBZDzeClCRdiB4MBgKDnMgQAAsVyAA)
```javascript
{
  "type": "object",
  "allOf": [
    {
      "type": "object",
      "description": "external schema not under direct control",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  ],
  "defaultProperties": [
    "id",
    "name"
  ],
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
```

In case this is intended, a possible workaround is to preprocess the schema and collect all required properties within defaultProperties

**Comment by germanbisurgi** [comment]
`defaultProperties` is not a replace nor an extension for `required`.  It overrides the normal behaviour. Meaning that only properties that are included in `defaultProperties` are displayed in the form, including required properties.
