### ISSUE TITLE
When using data generated by a schema containing anyof, the result is incorrect after assignment to the editor.

### ISSUE THREAD

**Issue by wclssdn** [json-editor/json-editor#128]
### Expected behavior

The editor can correctly assign values based on json

### Actual behavior

The editor cannot use the correct anyOf subkey when assigning the anyOf field

### Steps to reproduce the behavior

[schema](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QEMB2BPA9gMwAQCNkATAY2QGd4AacdAB3iU3wCtYSwQa6AnTBnpFjlEoKLAC2IhKEgxG4KHC60GiFDx7J0K7Jh4TknJGGT4RNcVNGL56qyoAWsYrB4AVSXWhGFwYJTQ2AB0jmhEcDwAvlEq/JCYqNKgANawsHQA+omwOJkAbsjQAK7CiNhFlFE0aOgA8tiIANqySgpWuMgqvPxuQskgYagRbjZEsBXF0MYoyF3VIJlLXTK2ykhLmSpg9ArkYDwQqADmIDHVrXZIHfjdfAL9NkMjPGMTyFMz+N9nNJu3qzk60WS22u3U+0OJzOMSol2BHRId16gggZVWdGQWmsGPufTRAysAyBe2K+FwRLBaiQWK0OhoegMRnUpnMKkpq3iEESAzSGWyqFy2AKRVK0gq0CqNBJELJFLAkicLnGHi8PgV6n8gRCz0iMRUtQazXh7QVEk6yIeBKe4Uib0m03Uc3mf2WNhlG1B0vBSEhR1O5zha1NkgIlvx6NAutGq3GDq+PwW/3dbXUmypewO/phUQAuucFtHXrH3p91CQK78QZkkYDU56tt7qSA/dDzvnYSA4x9pgAFPGo9FNECU/NAAAA=&value=N4IglgLgpgtgziAXAbVACwIYDsAmAbKAJyRAzJABoQB9WjEkAXwvW3yJICNvKbbOGzUAAcMhDPCShIsBCla4CxRKXJVa1eiqYsQmRRxXcB6/oIC6zPWyUkAxg94a7FxkAAA=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

```javascript
{
  "title": "anyof badcase",
  "type": "object",
  "properties": {
    "items": {
      "title": "title",
      "type": "array",
      "format": "tabs",
      "items": {
        "title": "item",
        "headerTemplate": "{{self.handler}}",
        "options": {
          "keep_oneof_values": false
        },
        "anyOf": [
          {
            "title": "item a",
            "properties": {
              "handler": {
                "default": "aaa"
              },
              "___a": {
                "title": "___",
                "type": "string"
              }
            }
          },
          {
            "title": "item b",
            "properties": {
              "handler": {
                "default": "bbb"
              },
              "___b": {
                "title": "___",
                "type": "string"
              }
            }
          },
          {
            "title": "item c",
            "properties": {
              "params": {
                "properties": {
                  "items": {
                    "title": "sub items",
                    "type": "array",
                    "format": "tabs",
                    "items": {
                      "options": {
                        "keep_oneof_values": false
                      },
                      "title": "sub item",
                      "headerTemplate": "{{self.handler}}",
                      "anyOf": [
                        {
                          "title": "item a",
                          "properties": {
                            "handler": {
                              "default": "aaa"
                            },
                            "___a": {
                              "title": "___",
                              "type": "string"
                            }
                          }
                        },
                        {
                          "title": "item b",
                          "properties": {
                            "handler": {
                              "default": "bbb"
                            },
                            "___b": {
                              "title": "___",
                              "type": "string"
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              },
              "handler": {
                "default": "ccc"
              },
              "___c": {
                "title": "___",
                "type": "string"
              }
            }
          }
        ]
      }
    }
  }
}
```

generated data:

```javascript
{
  "items": [
    {
      "handler": "aaa",
      "___a": ""
    },
    {
      "handler": "bbb",
      "___b": ""
    },
    {
      "params": {
        "items": [
          {
            "handler": "aaa",
            "___a": ""
          },
          {
            "handler": "bbb",
            "___b": ""
          },
          {
            "handler": "aaa",
            "___a": ""
          }
        ]
      },
      "handler": "ccc",
      "___c": ""
    }
  ]
}
```

Update the editor with the generated data. 

screenshot

![screenshot](http://feeds.images.bootsphp.com/badcase.png)

**Comment by wclssdn** [comment]
help ~~

**Comment by Richacinas** [comment]
Just a workaround so everyone is able to use this feature properly until it is fixed.

Add this to each one of your elements that will be available to choose from:

"additionalProperties": false

Put it after the title property, for example. It should work.

**Comment by wclssdn** [comment]
thanks @Richacinas , but it doesn't work well..

1. open [schema after add additionalProperties](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QEMB2BPA9gMwAQCNkATAY2QGd4AaFIoqCTVZaABQCdMAHWdyWcomwtKNMOh6IQmfACtYJMCBpdOPPhAGJQUWAFtBCUJBjwkJuMtr1ITFh269+h4dFHgJZlO3bJ0V7Ex2PWQlc2R8QRpdA21wKEskGKtiG0ZmNjUnTRcRWBoAC1hiXgAVfS5oUK9gYEpobAA6ArQiOHYAXw6rbltUQ1AAa1hYLgB9JlgcMYA3FgBXLQRXSg6aNHQAeWxEAG1jBK8Y3GQUugY7TMcNJZX8kFVr5ziW1DbeOKJYYXnoMJRkKc1iAxqDTkZ4qYpKCxlZxJIkOQwOwIKgAOYgLprA5QpJgfQEM5pS4OdTPZZ5FRZG4DECvd7sT7fZC/f74dmYmgw/BxCxeGFwzxSJEo9GYrpUHGJEDHEhEi4ZUnZW6Uh7U8mgLjIXyxCGPMk5OIxWl84XzfC4Y3yvr2dWGilue7wrza3z+GiBYKhKRgCJRGX43WgXrpWnDUYTVBTbCzBYqx3A02I82WwPW9K2p72u6FYpfdjlPSVapSWr1Jr09pdFIYbZ7KVHQMndMku3x9z65W0ysfCFfH5/KSAoFcsG8w7Q0GChEgEWojFYyWQ6XHHnrc42q4G9v3Ts0l6tdpMgdsjnA7nj3EgqdiIWI5Hz8UdAC6WOBPcZfeZrKkJD/nOvMY5QhJNAOnLw5zFLFXwlEB+xZP4lX3BBdgDfRBFfIAAA=&value=N4IglgLgpgtgziAXAbVACwIYDsAmAbKAJyRAzJABoQB9WjEkAXwvW3yJICNvKbbOGzVrgLFEIAMZSmAXUZAAAA==&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

2. paste data into `JSON Output` and click `Update Form` button

```
{
  "items": [
    {
      "handler": "aaa",
      "___a": ""
    },
    {
      "handler": "bbb",
      "___b": ""
    },
    {
      "params": {
        "items": [
          {
            "handler": "aaa",
            "___a": ""
          },
          {
            "handler": "bbb",
            "___b": ""
          }
        ]
      },
      "handler": "ccc",
      "___c": ""
    }
  ]
}
```

3. see the third element `ccc`, with wrong type

![see this image](http://feeds.images.bootsphp.com/badcase.png)

**Comment by wclssdn** [comment]
help....

**Comment by germanbisurgi** [comment]
you have to specify the type of values:

`"handler": {
								"default": "aaa",
								"type": "string"
							}`

Then it will work :)

**Comment by Richacinas** [comment]
@wclssdn You are right... What I could tell, from trying with a few different approaches, is that if you provide data with at least one more field that belongs only to each handler, the library will tell and assign a proper type on the select.

Like this:

{
  "items": [
    {
      "handler": "aaa",
      "___a": ""
    },
    {
      "handler": "bbb",
      "___b": ""
    },
    {
      "handler": "ccc",
      "___c": ""
    }
  ]
}

**Comment by wclssdn** [comment]
@Richacinas It doesn't work for more complex object...

**Comment by schmunk42** [comment]
@pmk65 Thank you for reporting!

**Comment by pmk65** [comment]
@drzax I suggest you open a new issue with specific examples etc. As it looks like the the original reporters is no longer around.

**Comment by drzax** [comment]
Sorry, I don't have time for that and the bug is already explained quite
well here. I just wanted to point out that this is still a bug, and rather
an annoying one which is difficult to track down. Feel free to use/manage
this bug report however you think is appropriate.

**Comment by pmk65** [comment]
Then I'll leave it closed for now, as I am only focusing on issues with active reporters. 
But maybe someone else will look at it at a later time.

**Comment by wclssdn** [comment]
I got it.
In file [`src/editors/multiple.js` line `241`](https://github.com/json-editor/json-editor/blob/HEAD/src/editors/multiple.js#L241), the given value pass through the `"wrong"` validator. 
e.g.
the `anyOf` contain two schemas:
```
{
  "anyOf": [
    {
      "title": "item a",
      "properties": {
        "handler": {
          "default": "aaa"
        },
        "___a": {
          "title": "___",
          "type": "string"
        }
      }
    },
    {
      "title": "item b",
      "properties": {
        "handler": {
          "default": "bbb"
        },
        "___b": {
          "title": "___",
          "type": "string"
        }
      }
    }
  ]
}
```
and given value is 
```
{
  "items": [
    {
      "handler": "aaa",
      "___a": ""
    },
    {
      "handler": "bbb",
      "___b": ""
    }
  ]
}
```
when set the first value to the editor, it's complete correct.
but when set the second value to the editor, it's `wrong`!~
because the value 
```
{
  "handler": "bbb",
  "___b": ""
}
```
just fit the schema(`value.___a === "undefined" but not required`)
```
{
  "title": "item a",
  "properties": {
    "handler": {
      "default": "aaa"
    },
    "___a": {
      "title": "___",
      "type": "string"
    }
  }
}
```
The second schema must be test, then choose the best one to use.
