### ISSUE TITLE
Json schema editor autocomplete is not working in Vue JS

### ISSUE THREAD

**Issue by RajiSudharmaSoman** [json-editor/json-editor#1296]
```
<template><div class="container"><div class="json-editor-container"></div></div></template><script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
<script>
const autocomplete=require('@trevoreyre/autocomplete-vue/dist/autocomplete.min.js')
import Autocomplete from '@trevoreyre/autocomplete-vue'
import { JSONEditor } from "@json-editor/json-editor/dist/nonmin/jsoneditor.js";
import schema from "../schema/autocomplete.json";
export default {
  name: "AutoVue",
  components: {
    Autocomplete
  },
  mounted: function () {
    var self = this;
    this.populate_grid(self.$el, this.defaults);
  },
  created: function () {
    console.log("ahhh" + autocomplete);
  },

  methods: {
       search(input) {
         var countries = [
                            'germany',
                            'iran',
                            'iraq',
                            'spain',
                            'georgia'
                        ]

      if (input.length < 1) { return [] }
      return countries.filter(country => {
        return country.toLowerCase()
          .startsWith(input.toLowerCase())
      })
    },
  
    reloadPage: function () {
      alert("reload");
    },
    populate_grid: function (element,k) {
      
       JSONEditor.defaults.callbacks = {
                'autocomplete': {
                    'search': function (editor, input) {
                      alert(input)
                        var countries = [
                            'germany',
                            'iran',
                            'iraq',
                            'spain',
                            'georgia'
                        ]

                        if (input.length < 1) { return [] }

                        return countries.filter(country => {
                            return country.toLowerCase().startsWith(input.toLowerCase())
                        })
                    }
                }
            }

            var schema = {
                'title': 'Test',
                'type': 'string',
                'format': 'autocomplete',
                'options': {
                    'autocomplete': {
                        'search': 'search',
                        'autoSelect': true,
                        'baseClass':'autocomplete'
                    }
                }
            }

            var editor = new JSONEditor(element, {
                schema: schema,
                theme: 'bootstrap4',
                required_by_default: true,
                show_errors: 'always'
            })

            editor.on('change', function () {
                console.log(JSON.stringify(editor.getValue()))
            })
    },
  },
};
</script>
```

**Comment by RajiSudharmaSoman** [comment]
The above code is not working. Autocomplete option is not working. Please help me

**Comment by RajiSudharmaSoman** [comment]
<template><div class="container"><div class="json-editor-container"></div></div></template>

**Comment by RajiSudharmaSoman** [comment]
Please provide me an example if this Json schema editor tool can be integrate with Vue js. If so, Kindly provide me an example.
with the above code, call back to search method is not happening

**Comment by RajiSudharmaSoman** [comment]
<template>
 
<div class="container"></div>
</template>

<script>
//const autocomplete = require("@trevoreyre/autocomplete-vue/dist/autocomplete.min.js");
// import Autocomplete from "@trevoreyre/autocomplete-vue";
import "@trevoreyre/autocomplete-vue/dist/style.css"
import { JSONEditor } from "@json-editor/json-editor/dist/nonmin/jsoneditor.js";
export default {
  name: "AutoVue",
  mounted: function () {
    var self = this;
    this.populate_grid(self.$el);
  },
  created: function () {
  },

  methods: {
    search(input) {
      var countries = ["germany", "iran", "iraq", "spain", "georgia"];

      if (input.length < 1) {
        return [];
      }
      return countries.filter((country) => {
        return country.toLowerCase().startsWith(input.toLowerCase());
      });
    },


    populate_grid: function (element) {
      JSONEditor.defaults.callbacks = {
        autocomplete: {
          search: function (editor, input) {
            var countries = ["germany", "iran", "iraq", "spain", "georgia"];

            if (input.length < 1) {
              return [];
            }

            return countries.filter((country) => {
              return country.toLowerCase().startsWith(input.toLowerCase());
            });
          },
        },
      };

      var schema = {
        title: "Test",
        type: "string",
        format: "autocomplete",
        options: {
          autocomplete: {
            search: "search",
            autoSelect: true,
            baseClass: "autocomplete",
          },
        },
      };

      var editor = new JSONEditor(element, {
        schema: schema,
        theme: "bootstrap4",
        required_by_default: true,
        show_errors: "always",
      });

      editor.on("change", function () {
        console.log(JSON.stringify(editor.getValue()));
      });
    },
  },
};
</script>

**Comment by schmunk42** [comment]
Here's a vanilla autocomplete example: https://github.com/json-editor/json-editor/blob/master/README_ADDON.md#autocomplete

Which error do you get with VueJS?

CC: @marc7000

**Comment by RajiSudharmaSoman** [comment]
Below Autocomplete call back is not getting invoked

JSONEditor.defaults.callbacks = {
        autocomplete: {
          search: function (editor, input) {
            var countries = ["germany", "iran", "iraq", "spain", "georgia"];

            if (input.length < 1) {
              return [];
            }

            return countries.filter((country) => {
              return country.toLowerCase().startsWith(input.toLowerCase());
            });
          },
        },
      };

**Comment by RajiSudharmaSoman** [comment]
This link https://github.com/json-editor/json-editor/blob/master/README_ADDON.md#autocomplete is not helping me.
Please try to provide a sample Vue js with Json schema autocomplete

**Comment by RajiSudharmaSoman** [comment]
countries are not auto populated
<img width="491" alt="image" src="https://user-images.githubusercontent.com/26257600/223399078-a697eac8-b854-4645-abde-f63b25a234a8.png">

**Comment by RajiSudharmaSoman** [comment]
@schmunk42 Please help me

**Comment by marc7000** [comment]
@RajiSudharmaSoman use the JavaScript Component and not the Vue Component of the Autocomplete Library.
Add the Script & CSS in our index.html File:

```
<script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
<link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"/>
```
This works:
```
<template>
  <div ref="jsonEditor"></div>
</template>

<script>
import { JSONEditor } from '@json-editor/json-editor'

export default {
  name: 'AutoVue',
  mounted () {
    this.initJSONEditor(this.$refs.jsonEditor)
  },
  methods: {
    initJSONEditor (element) {
      JSONEditor.defaults.callbacks = {
        autocomplete: {
          search (jseditorEditor, input) {
            const countries = ['germany', 'iran', 'iraq', 'spain', 'georgia']

            if (input.length < 1) {
              return []
            }

            return countries.filter((country) => {
              return country.toLowerCase().startsWith(input.toLowerCase())
            })
          }
        }
      }

      const schema = {
        title: 'Test',
        type: 'string',
        format: 'autocomplete',
        options: {
          autocomplete: {
            search: 'search',
            autoSelect: true
          }
        }
      }

      const editor = new JSONEditor(element, {
        schema: schema,
        theme: 'bootstrap4',
        required_by_default: true,
        show_errors: 'always'
      })

      editor.on('change', function () {
        console.log(JSON.stringify(editor.getValue()))
      })
    }
  }
}
</script>
```

<img width="544" alt="autocomplete" src="https://user-images.githubusercontent.com/1118837/223662772-974f9aeb-265a-433c-8a25-0cd727877c50.png">

**Comment by RajiSudharmaSoman** [comment]
Thank you. Let me try it out

**Comment by RajiSudharmaSoman** [comment]
This solution is working. Thanks
