### ISSUE TITLE
Compilation warning because ./boostrap3.css is empty

### ISSUE THREAD

**Issue by rroger** [json-editor/json-editor#1298]
### General information

There might be a compilation warning:
Compiled with problems:X

WARNING in ./node_modules/@json-editor/json-editor/src/themes/bootstrap3.js 305:24-29

export 'default' (imported as 'rules') was not found in './bootstrap3.css' (module has no exports)

https://github.com/json-editor/json-editor/blob/2.9.1/src/themes/bootstrap3.css

- json-editor version: 2.9.1

**Comment by rroger** [comment]
If it is really a bug and not a problem on my machine, than this could be the fix:
https://github.com/json-editor/json-editor/pull/1299

**Comment by germanbisurgi** [comment]
fixed in https://github.com/json-editor/json-editor/pull/1299
