### ISSUE TITLE
Proper way to make nested dropdowns

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#13]
Hi.

Is there a clear guideline to making nested dropdowns? I see several comments across multiple forks but nothing clear.

Perhaps a simple example? Something that can select between category 1 and category 2 and then from subcategories 1-1, 1-2 and 1-3 or subcategories 2-1, 2-2 or 2-3?

I'm not sure if it's supposed to be oneOf or Enumsources + watch.

**Comment by pmk65** [comment]
dependencies
