### ISSUE TITLE
Problem with "required" in combination with "additionalProperties: false"

### ISSUE THREAD

**Issue by Radouch** [json-editor/json-editor#130]
### Expected behavior
Required properties should be required, all other properties specified in JSON schema should be allowed.

### Actual behavior
If there is 
"additionalProperties": false,
and some properties in : "required"
then any value of non-required property is interpreted as error:
"No additional properties allowed, but property XYZ is set"

### Steps to reproduce the behavior

1. Create the folowing JSON schema and load it into the JSON Editor:

```javascript
{
  "type": "object",
  "title": "Error: Only required properties are allowed",
  "description": "If required properties are specified, non-required properties are considered as errors",
  "additionalProperties": false,
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "title": "name"
    },
    "description": {
      "type": "string",
      "title": "description"
    }
  }
}
```
2. Then enter anything in the "description" field.

**Comment by trsh** [comment]
Same here. I almost made new issue.

**Comment by trsh** [comment]
Btw the setting is `no_additional_properties: true`, not `additionalProperties: fase`?

**Comment by Radouch** [comment]
a) `no_additional_properties: true` is an option for JSON Editor.
b) `additionalProperties: false` is an option in JSON schema, see https://spacetelescope.github.io/understanding-json-schema/reference/object.html
I mean b) (did not test a) ).

**Comment by trsh** [comment]
@Radouch same with a) :)

**Comment by reinesvs** [comment]
@pmk65 Where in the specification is the relation between required and additionalProperties described as you have interpreted above?
Accordning to [Required Properties](https://json-schema.org/understanding-json-schema/reference/object.html#required-properties) there is not relation between required properties and disallowing any other properties defined in the schema. additionalProperties only controls if you can add properties not defined in the schema. Thus all properties defined in the schema is allowed, regardless of what subset is marked as required.

**Comment by germanbisurgi** [comment]
clarified in #943
