### ISSUE TITLE
Any chance of updating the info customly from nodes to items!

### ISSUE THREAD

**Issue by vishnu947** [json-editor/json-editor#1301]
If we click on the Last Items button or any other Delete button, it gives the below popup message. In the message word “node” is mentioned, should we update this to something like “item” to match the button name?

<img width="553" alt="editor issue" src="https://user-images.githubusercontent.com/99916723/223781578-6f0987c2-f064-4cf4-a7cc-2e0f3df9d4e4.png">

**Comment by germanbisurgi** [comment]
Items makes more sense to me than node too. @schmunk42 what do you think?

Meanwhile you could use this:

```javascript
JSONEditor.defaults.languages.en = {
  button_delete_node_warning: 'Are you sure you want to remove this item?'
}
```

**Comment by schmunk42** [comment]
> Items makes more sense to me than node too. @schmunk42 what do you think?

Yeah, better if it matches the button.

**Comment by germanbisurgi** [comment]
Updated in #1310
