### ISSUE TITLE
Properties not defined in JSON schema cause "TypeError"

### ISSUE THREAD

**Issue by Radouch** [json-editor/json-editor#131]
### Expected behavior
Properties not defined in JSON schema can be added if it is allowed by the schema.

### Actual behavior
Any property added to JSON and not described in JSON schema causes error in console:
`TypeError: can't convert null to object`

### Steps to reproduce the behavior
1. Create JSON schema:
```javascript
{
  "type": "object",
  "title": "Error: Properties not descibed in schema cause error",
  "description": "Create schema for one property, then add another one",
  "additionalProperties": true,
  "required": ["name"],
  "properties": {
    "name": {
      "type": "string",
      "title": "name"
    }
  }
}
```
2. Load the schema into the JSON Editor, then try to add any property.
3. The new property will be successfully added, but there will appear above mentioned error in browser console.

**Comment by marc7000** [comment]
@pmk65 Thank you for reporting!

**Comment by Radouch** [comment]
I have to disagree. 
The release mentioned by @pmk65 does not seem to be the current release (it loads this: 
http://jeremydorn.com/json-editor/dist/jsoneditor.min.js.php )
Still the same problem with this version:
https://cdn.jsdelivr.net/npm/@json-editor/json-editor@1.1.0/dist/jsoneditor.js

**Comment by schmunk42** [comment]
@Radouch I also can not reproduce - see https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyICiATpUpfAAQAKNslYBMAzvQHZJj0AJl0wEUMQfQI96nTAAsYAWwCG9TCoCunGPRjVaeEMLmUCUdkh4IQAYUowVYXXMWr6AM1r0ruqC31IXHowRRkVQUkVPlD9Hx44fAjBIgIrFWJmJFZ2LgQwSk0YfAcAR00CB0EEAG0QHhUlOABdfH9swI5OBFAGpp7waDIQTgLpAHMjdhJhvrgAX0WgA=&value=N4IgdghgtgpiBcIQBoQDMD2GEgEYQCcQBfIAAA==&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

Can you post an example, jsfiddle and/or screenshot?

**Comment by Radouch** [comment]
I can confirm it works OK with the editor at  https://json-editor.github.io/json-editor (cannot send direct link - URL too long - my scheme is a bit complicated :-) ).

Unfortunatelly, there is still the same error (TypeError: Cannot convert undefined or null to object) at my local version of the editor, although I use the same version of the editor (https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.min.js).

I will try to find the cause of the problem and report it here.

**Comment by Radouch** [comment]
See https://jsfiddle.net/9kcyL7g3/1/ (look at the browser console, too).
There is a problem with an option:
`remove_empty_properties: true`

**Comment by schmunk42** [comment]
@germanbisurgi Can you take a look?

**Comment by pmk65** [comment]
@Radouch I added an extra check to test if the value is really an object before deleting (Seems like null values falls through the current check.)

**Comment by pmk65** [comment]
@Radouch  can you test and see if my fix worked for you? Then we can close this issue.

**Comment by Radouch** [comment]
@pmk65 I have built dist files locally and it works ok. The issue can be closed. Thank you!
