### ISSUE TITLE
Schema, tabs broken and etc issue

### ISSUE THREAD

**Issue by fhnb16** [json-editor/json-editor#1311]
### General information

- json-editor version: 2.9.1
- In Playground and demos
- Windows 10 22H2, Edge Chromium Dev Channel and Firefox latest

### Expected behavior

Expected all works

### Actual behavior

Wierd behavior
I paste my schema and json, but schema properties (like array "format": "tabs", "headerTemplate": "{{self.Name}}" and etc..) **works only at first child Array item**. All of the following items are broken.

https://user-images.githubusercontent.com/1816594/228812346-4f451844-6005-4598-9274-af69afc67c6f.mp4

Same issue in old [jdorn/json-editor](http://jeremydorn.com/json-editor/) and new [json-editor/json-editor](https://json-editor.github.io/json-editor/) demos

> Maybe schema incorrect? Help please

Direct link to example: https://is.gd/qWGjjQ

<details>
  <summary>Sample json</summary>
<pre><code>
{
  "Name": "Name",
  "Categories": [
    {
      "Name": "yay",
      "Priority": 0,
      "Visibility": "Visible",
      "Items": [
        {
          "Name": "Hello World",
          "Priority": 0,
          "Visibility": "Visible",
          "Media": {
            "Mode": "Default",
            "Items": []
          },
          "Description": {
            "ru": "",
            "en": ""
          },
          "Buttons": [],
          "Tags": [],
          "Released": ""
        },
        {
          "Name": "Hello World2",
          "Priority": 0,
          "Visibility": "Visible",
          "Media": {
            "Mode": "Default",
            "Items": []
          },
          "Description": {
            "ru": "",
            "en": ""
          },
          "Buttons": [],
          "Tags": [],
          "Released": ""
        }
      ]
    },
    {
      "Name": "yay2",
      "Priority": 0,
      "Visibility": "Visible",
      "Items": [
        {
          "Name": "Hello World3",
          "Priority": 0,
          "Visibility": "Visible",
          "Media": {
            "Mode": "Default",
            "Items": []
          },
          "Description": {
            "ru": "",
            "en": ""
          },
          "Buttons": [],
          "Tags": [],
          "Released": ""
        },
        {
          "Name": "Hello World4",
          "Priority": 0,
          "Visibility": "Visible",
          "Media": {
            "Mode": "Default",
            "Items": []
          },
          "Description": {
            "ru": "",
            "en": ""
          },
          "Buttons": [],
          "Tags": [],
          "Released": ""
        }
      ]
    }
  ]
}
</code></pre>
</details>

<details>
  <summary>Sample scheme</summary>
<pre><code>
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string",
      "default": "Name",
      "description": "Website Title"
    },
    "Categories": {
      "type": "array",
      "format": "tabs",
      "description": "Category",
      "items": [{
        "description": "Category Item",
        "headerTemplate": "{{self.Name}}",
        "type": "object",
        "format": "grid",
        "properties": {
          "Name": {
            "type": "string"
          },
          "Priority": {
            "type": "integer",
            "minimum": 0,
            "default": 0
          },
          "Visibility": {
            "type": "string",
            "enum": [
              "Visible",
              "Hidden",
              "Spoiler"
            ],
            "default": "Visible"
          },
          "Items": {
            "type": "array",
            "format": "tabs-top",
            "items": [{
              "type": "object",
              "headerTemplate": "{{self.Name}}",
              "properties": {
                "Name": {
                  "type": "string"
                },
                "Priority": {
                  "type": "integer",
                  "minimum": 0,
                  "default": 0
                },
                "Visibility": {
                  "type": "string",
                  "enum": [
                    "Visible",
                    "Hidden",
                    "Spoiler"
                  ],
                  "default": "Visible"
                },
                "Media": {
                  "type": "object",
                  "format": "grid",
                  "properties": {
                    "Mode": {
                      "type": "string",
                      "enum": [
                        "Single",
                        "Grid",
                        "Gallery",
                        "Default",
                        ""
                      ],
                      "default": "Default"
                    },
                    "Items": {
                      "type": "array",
                      "items": [{
                        "type": "object",
                        "properties": {
                          "Type": {
                            "type": "string",
                            "enum": [
                              "Video",
                              "Gif",
                              "Img",
                              "Frame"
                            ],
                            "default": "Img"
                          },
                          "Source": {
                            "type": "string"
                          },
                          "Cover": {
                            "type": "string"
                          },
                          "Caption": {
                            "type": "string"
                          },
                          "Alt": {
                            "type": "string"
                          },
                          "Title": {
                            "type": "string"
                          },
                          "Args": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "Type",
                          "Source",
                          "Cover",
                          "Caption",
                          "Alt",
                          "Title",
                          "Args"
                        ]
                      }]
                    }
                  },
                  "required": [
                    "Mode",
                    "Items"
                  ]
                },
                "Description": {
                  "type": "object",
                  "properties": {
                    "ru": {
                      "type": "string",
                      "format": "textarea"
                    },
                    "en": {
                      "type": "string",
                      "format": "textarea"
                    }
                  },
                  "required": [
                    "en"
                  ]
                },
                "Buttons": {
                  "type": "array",
                  "items": [{
                    "type": "object",
                    "format": "grid",
                    "properties": {
                      "Text": {
                        "type": "string"
                      },
                      "Type": {
                        "type": "string",
                        "enum": [
                          "Button",
                          "Link"
                        ],
                        "default": "Link"
                      },
                      "Mode": {
                        "type": "string",
                        "enum": [
                          "Wide",
                          "Fill",
                          ""
                        ],
                        "default": ""
                      },
                      "Args": {
                        "type": "string"
                      },
                      "Link": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "Text",
                      "Type",
                      "Mode",
                      "Args",
                      "Link"
                    ]
                  }]
                },
                "Tags": {
                  "type": "array",
                  "items": [{
                    "type": "string"
                  }]
                },
                "Released": {
                  "type": "string"
                }
              },
              "required": [
                "Name",
                "Priority",
                "Visibility",
                "Media",
                "Description",
                "Buttons",
                "Tags",
                "Released"
              ]
            }]
          }
        },
        "required": [
          "Name",
          "Priority",
          "Visibility",
          "Items"
        ]
      }]
    }
  },
  "required": [
    "Name",
    "Categories"
  ]
}
</code></pre>
</details>

**Comment by germanbisurgi** [comment]
In the provided schema all the array `items` keyword are arrays. This is used for tuples in JSON schema draft 4. More info  [here](http://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation).

Tuple schema:
```json
{
  "type": "array",
  "items": [
    { "type": "string" },
    { "type": "integer" },
    { "type": "boolean" }
  ]
}
```

Tutple:
```javascript
["Chile", 1, true ]
```


I believe that what is wanted here is a single schema for the `items` keywords:

<details>
  <summary>Updated schema</summary>
<pre><code>
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string",
      "default": "Name",
      "description": "Website Title"
    },
    "Categories": {
      "type": "array",
      "format": "tabs",
      "description": "Category",
      "items": {
        "description": "Category Item",
        "headerTemplate": "{{self.Name}}",
        "type": "object",
        "format": "grid",
        "properties": {
          "Name": {
            "type": "string"
          },
          "Priority": {
            "type": "integer",
            "minimum": 0,
            "default": 0
          },
          "Visibility": {
            "type": "string",
            "enum": [
              "Visible",
              "Hidden",
              "Spoiler"
            ],
            "default": "Visible"
          },
          "Items": {
            "type": "array",
            "format": "tabs-top",
            "items": {
              "type": "object",
              "headerTemplate": "{{self.Name}}",
              "properties": {
                "Name": {
                  "type": "string"
                },
                "Priority": {
                  "type": "integer",
                  "minimum": 0,
                  "default": 0
                },
                "Visibility": {
                  "type": "string",
                  "enum": [
                    "Visible",
                    "Hidden",
                    "Spoiler"
                  ],
                  "default": "Visible"
                },
                "Media": {
                  "type": "object",
                  "format": "grid",
                  "properties": {
                    "Mode": {
                      "type": "string",
                      "enum": [
                        "Single",
                        "Grid",
                        "Gallery",
                        "Default",
                        ""
                      ],
                      "default": "Default"
                    },
                    "Items": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "Type": {
                            "type": "string",
                            "enum": [
                              "Video",
                              "Gif",
                              "Img",
                              "Frame"
                            ],
                            "default": "Img"
                          },
                          "Source": {
                            "type": "string"
                          },
                          "Cover": {
                            "type": "string"
                          },
                          "Caption": {
                            "type": "string"
                          },
                          "Alt": {
                            "type": "string"
                          },
                          "Title": {
                            "type": "string"
                          },
                          "Args": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "Type",
                          "Source",
                          "Cover",
                          "Caption",
                          "Alt",
                          "Title",
                          "Args"
                        ]
                      }
                    }
                  },
                  "required": [
                    "Mode",
                    "Items"
                  ]
                },
                "Description": {
                  "type": "object",
                  "properties": {
                    "ru": {
                      "type": "string",
                      "format": "textarea"
                    },
                    "en": {
                      "type": "string",
                      "format": "textarea"
                    }
                  },
                  "required": [
                    "en"
                  ]
                },
                "Buttons": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "format": "grid",
                    "properties": {
                      "Text": {
                        "type": "string"
                      },
                      "Type": {
                        "type": "string",
                        "enum": [
                          "Button",
                          "Link"
                        ],
                        "default": "Link"
                      },
                      "Mode": {
                        "type": "string",
                        "enum": [
                          "Wide",
                          "Fill",
                          ""
                        ],
                        "default": ""
                      },
                      "Args": {
                        "type": "string"
                      },
                      "Link": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "Text",
                      "Type",
                      "Mode",
                      "Args",
                      "Link"
                    ]
                  }
                },
                "Tags": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "Released": {
                  "type": "string"
                }
              },
              "required": [
                "Name",
                "Priority",
                "Visibility",
                "Media",
                "Description",
                "Buttons",
                "Tags",
                "Released"
              ]
            }
          }
        },
        "required": [
          "Name",
          "Priority",
          "Visibility",
          "Items"
        ]
      }
    }
  },
  "required": [
    "Name",
    "Categories"
  ]
}

</code></pre>
</details>

**Comment by germanbisurgi** [comment]
Feel free to reopen
