### ISSUE TITLE
Missing css for when using CDN

### ISSUE THREAD

**Issue by shirecoding** [json-editor/json-editor#1314]
I'm using the CDN version if the json editor however the link to the css file is not specified anywhere?

**Comment by germanbisurgi** [comment]
JSONEditor does not come with CSS libraries. Themes like Bootstrap should be added in addition to your project.

**Comment by shirecoding** [comment]
hmm however i do see html.css and barebones.css as well as styles.css in the source folder, dont i need those?

**Comment by germanbisurgi** [comment]
These CSS files are imported as JavaScript files into their own theme classes and stored in the property `rules`. When the editor is initialized, these rules are then injected into a DOM shadow root.
