### ISSUE TITLE
je-object__controls group not has margin-top/bottom  when "root.oneOf"

### ISSUE THREAD

**Issue by RelicOfTesla** [json-editor/json-editor#1315]
### General information

- json-editor version: 2.9.1

### Expected behavior
je-object__controls group has margin-top/bottom  when "root.oneOf"
BTW, the size of the label and options is a bit small.
 
### Actual behavior
not has margin-top/bottom

### Steps to reproduce the behavior

Direct link to example: https://is.gd/A6Uj8q

"oneOf - Name" Example , add "disable_collapse" in "root.options"

```javascript
{
  "options": {
    "disable_collapse":true
  },
  "oneOf": [.....]
}
```

**Comment by schmunk42** [comment]
Object controls always have this style:

```
.je-object__controls {
    margin: 0px 0px 0px 10px;
}
```

You can override the style if you need to.
