### ISSUE TITLE
How to be unique enough for oneOf

### ISSUE THREAD

**Issue by mjhn** [json-editor/json-editor#1319]
### General information

- json-editor version: 2.9.1

### Actual behavior - Get error message - "Value must validate against exactly one of the provided schemas. It currently validates against 0 of the schemas." Display incorrect type from oneOf[]  - Manually changing to correct type via dropdown results in validation passing.

Direct link to example: [sample](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAlgEzgLlsAzgYwE4FM8JE8AzeCeAF3gHsIA6AKwzrgBpIY5rKAbPVOmz5CxMhWqtgHaOgg0A%2BgENEiKrQhLeCgA44aOvDmp4MgyjgCueGV2CUAnocFwaAI0Z4sldp3QHJCDNgNHBZOzUMJTd%2BBTw1SgVmKTQLa1sYdEjo2L0DIxNg1KsbPzssGl5eJR0MeMESLTq%2FAF8MuHwAR0t4fGQQqABtMqEsAAs8AFslBSRfcNGRCDg%2FAF124DzDY3hTQTDM0Ynp2f7QkbtHZwG4DAtyAHN5w4jSJUteHxvMXAIiUnI6joTBYy2kF38OkCRSgBxedjGSGIYOK1ghLRGbRGt1%2BhFQcMO3Co%2FBcwAAyriwRlCfYnAJvu5PN5ni9XFCNDCCazgNkYng4gkkqDzCVqdzebl9NtCiL0hDypVqrV6gNGrxmgsYFjNeguj0%2BoJhjq7HNwcb0DwSWb4Zc6Sz4dwpjpqpR6WKaeMaPAsHtgBD1hC4FsCrtOfL0Kbzubbdc0Ld7hAntabXZJuQADKEB6UMaCACM4e1KaJfHpUZTMbLQgTSfd3LTEEziZz%2BcLdcr%2B3DHe%2Bdxwj3tNrghEsk0NXcytzw%2FG8GhW0agAfncDE70%2BpLq08Cc5TRcH9idLqrXIdtNj1b7iYHJ4bTezuYGBfNu5Pnu9vvLFZLVrjwFfPuC7YTqeVZwEoOA4EoDhXtylgUN0eAAJKupMMJpKUS7AA2SFTDCeaAXYJA0Dg0xfD%2BlA5G645wFQOGdvOlzEiBwBKAAbko8DVHyUAYJYbjcZSAAUGAAJTQSeAQcnRFbcgA1gQOgKHQeA0CQChsbw1gwmqGrSVq%2BFAUpADyJBjvRmTHrpcAACT4CZ3wAMQAPRiIC0KORMKhGNuul6eOhwWdJ1m2aSTkuRIHKObw8APGMFjsbw3k%2BRiZmrOOyU7uimKtBsK4fJQAAKUohu%2BQzYj8xwzKaYo4ks3mLq84hAkEUlAR5xA4C1NKWkxAASeCeR1yZdXaDIeF4Xx1my0KdeK8BRHyApUEKKRQGhgHLnNFG6EVOwlWt4ZwBUVQ1HUZxQNpAg6s%2BQHBrtYbmnAbVeQMAVAVcTGMuNYkGeydD3T5G3zbE8RLckKKrSUaX6R0eDdL0KpoEaAO%2FtUGAAX56AVEQTXfV1jG40BSgzlI471Z%2Bmw7TKL0Y4dqP%2FT5FojT%2Bvb9kNlmYRmWYtg%2BGPXcWv50Aks7U2ZDGlqSADCgs42zgXABJf0zcjcl4ApSkqWpWiaQ0TSXQzUB8%2BTSgQA4xmmfrMCvXLNmkCFzkAuFf2ORUOjbAo%2BADYlDPpQzqVmYbJ7dUr5PvagrhjcysvkwrzUixbWSbQtIOJGDsrofHgNbbdVOounFuHYqJ0I%2BdusY75ovoNnob4mXQGEAAtAAqmSwfI6HITxheSa1%2BXGfAKYTct3H8eM7Gnesz3Bu1z70kB9yRNbsPbdM%2BHTITbXU2SUvDOZ0ngqpwM%2B0VxEieSvkd1p%2FpL6F8qZ0XdPV83ZT1chFbe7CH8NfH29K%2BYDWXtJUfjSHQYElCTDwK6HA9M%2B7txQOPS8fpv4z10sgjK84WiBSfJlBY104BRRinFDiwcvxMXwbFCCRCo7cCZv4CO68dSb0VtvGkEp%2BTJ2WuDI%2B%2FNWHbXPjnCGcoHoC2OrfHW6o9YvENjDOGBoBhIz3GQwhCVEHwjJsA5%2BJVXp4OiuQ%2BKrcf5jz%2Fl3Amy43h5VJIoihyjoYc0bFze8aA8wACZCzYMOLggWrsjDu36u1Yh9h8bfBdm7D2fiqHAVJJ9SOk15a%2FVjh%2BE8PD2EH1zutHkp9%2BRVz2qKA6wilSnTETpSRMSsnQO5BUc%2BPjPbMO5LA88rMbHDlHHImmwBQlQSjieRolDH5wFgjJeQAB3MEpNXFXSyrIZKLRgBAA%3D%3D%3D&value=EQbwOgdgBGwM4GMAWBTAtgQwPoEsAmsAXDPAgE4ooR4oBmOEOALjgPYQB0AVnO7ADSQSiClSJRw0EvnGwZwQVNgsmAGxSzgK9QKEkmATwAOG4MVhwU6hCz4K9y9EdUYmp81qcu3upcGSsOAgocOIA2noSkSSoGDRk4pJQycmwCC5woWYk6RiZvimp%2Fux4zGwQidFFCKysJmRYFHEoCdmwTXgGsFUAvoqF%2Bsw62UkDsFQAtACqAMqaVADmqjhwSAVjwCHTc23wRhiMq91SKX1VsBg25ZUnKRbklBW7Io%2FrhbD7ZBhoKG5kWR5Pj8%2FlletEepEzidRkVlgskEwvjhVJo4QikSjgJC9ABdIQQiA9YBAA%3D%3D%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=grid&template=default&show_errors=change&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=1&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

Hi, I know it's been asked before but not with a tip that I can apply. I have 2 objects. First with multiple properties - all required. The second has a single required property. Looking for advice on how to be unique enough for the input to pass validation and resolve the oneOf[] $ref without error. Thanks.

**Comment by schmunk42** [comment]
It's a bit hard to dig in ... can you create a simpler example with the same problem?

**Comment by mjhn** [comment]
Hi,
Thank you for the reply. 

I've attempted to simplify my example. Sorry for the noise. Same scenario. An array has `oneOf[]` used for defining `items` property. The `oneOf[]` has still have 2 objects defined. Both containing 1 property each ( `objA` has `string` prop and `objB` has `number` prop). With these changes I now get a variation of the error raised.
**Value must validate against exactly one of the provided schemas. It currently validates against 2 of the schemas.**
The structure of the choices array (and array of objects) remains the same as previous example. One change is I can no longer create output. Whereas initial posting I was able to create output but NOT able to reload it's own output and have correct `oneOf[]` type resolution. Different but still about what is unique enough.

Example [sample-2](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAlgEzgLlsAFgFywBxQPQGICmAtgPYB0AVgM4URwA0kMcW8WANiaunQDGAJxIkIpAGbwIXeIxZt0WAJ64%2BwNHAoAjGiUFZF0dKICOAV3ijkmqAG0l7YENHi4SgLqsTcXMIp1YU4SOn5wE3ZIgRExJk0ImCTlLl5%2BOABlWPdgH2TnVXV04F19Q2N80xJLaxJbNHtKqKb0QQwKeEFQj2iYbyckvwCgkLC7RKa4No6usbQJlo5UjS1gac7u3IHKjjUV9ABDYWEDlQqW9AtZSxIASSxyOagsYQsSPIu4Mhl7x%2F4ARg%2Bi2AkgowjIByMdg4Bx0aS2vXycC4f3G20mwE4PH2cAOADcDvBuLDeFA6BYdGTshAABR0ACU5wu6ECnEYTwWzPQAGsxLgAPqMEgUST8gncN5PSQHbh0PiIyoAXyBnxKEBIAHlJPxHAqmpyuegACSibXQ4AAYmIJGksjZEDoBAeZFwxIeAEEeoaYMr0S0DVy4CabcUrVIZHJ2U7yK7ISQAEJe72Kv35Typn2plOI7PJXNQX2%2BYBSA4WbhYAAKwxIwXgmwaAzgrjiSf6RfDdvkDvCjcxMbdJE9aMRS2xxWdsYeUAAtFAhyqCntiqUDFCF%2Bh%2FIEa6Me3rtHoh%2FMM8ol%2BaV%2BUEcztLh7Rzj85EPA6CSSPy6lx%2BfQFHYXm9j4Wr2AcwrBsHV7yqMx%2BToF4ZAAcyTFo20AzcRjrO89WSOBzCgmCIHg4dvRPIpzWg4Q4KZQNgG%2BCAABlxFgrAMABcD8xaRUrz1Viki4gDBj7F0B0TAikUxZZx37OMZygIT112YjVnPNd0SGLda3rKAA2cUohKPDCiJxEo9FXCidhKG8u3Qw04EfZ84Vfd8sE%2FBh4jQX95WZXjgWA2p6gccCsOqfkIAsMgEKaJDVRQ7c0N3KygMC4LQuEuLCgMxKdBrMK2P%2FDjspzAZ82zRVgCAA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=grid&template=default&show_errors=change&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=1&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

**Comment by schmunk42** [comment]
When having similar `anyOf`s you should set `no_additional_properties: true`, see https://is.gd/XWcc8H
This shows a message for `TempateA` since `req_string` has no valid default value. 
An integer field always has a valid default value `0` (eg. no empty string, unless you manually delete it).

The reason why `TemplateB`, in your example, is valid against 2 schemas is, that there *could* be an additional property `req_string` added, which would validate against both schema, hence the `no_additional_properties` above. Same applies for `TemplateA` vice-versa.

The reason why `TemplateA` seems initially to do what you want is ineed somehow strange, it appears it actually validates against `TemplateB`, but since it's just one (1) valid schema the editor thinks it's OK - the sub-schema-name of the `anyOf` is not part of the json-data, we always have to guess it.
Also, when entering a string in `TemplateA` it makes it valid against both schemas.

CC: @germanbisurgi Please have a look into the validation issue mentioned above.

**Comment by mjhn** [comment]
Awesome - both of my uses cases now work with `no_additional_properties: true`
Many Thanks 😊
