### ISSUE TITLE
custom-editor-interfaces

### ISSUE THREAD

**Issue by KES777** [json-editor/json-editor#1327]
### General information

May you please provide step-by-step documentation how to create minimal custom editor?

### Actual behavior
[Here](https://github.com/json-editor/json-editor#custom-editor-interfaces) described only how to trigger custom editor, but how this editor will look? Where I should provide the HTML which will be rendered for this editor?

Thank you.

**Comment by germanbisurgi** [comment]
There is a good introductory guide in the [wiki](https://github.com/json-editor/json-editor/wiki#editor-srceditorjs). 

The core concepts are:

- extend AbstractEditor class
- modify methods (preBuild, build, postBuild, etc)
- add resolver

I think we could create a simple example page for this.

**Comment by KES777** [comment]
@germanbisurgi Thanks for links. It seems `this.control` is not described there (but used in the example)

**Comment by germanbisurgi** [comment]
Correct, i used a custom variable to contain the html wrapper.

**Comment by KES777** [comment]
Could it be possible to add more comments to that example?

**Comment by schmunk42** [comment]
> Could it be possible to add more comments to that example?

PRs welcome ;)

**Comment by KES777** [comment]
@schmunk42: No problem. But before PRs I need to learn and understand what is coming on.
