### ISSUE TITLE
Compile without webpack

### ISSUE THREAD

**Issue by taksebe-user** [json-editor/json-editor#1328]
Hi to all. I need help to compile the project without webpack. Now, I use version 1.3.5 and wish to update to latest.

**Comment by germanbisurgi** [comment]
Old versions of json-editor used grunt to build the project. Running `npm install` to install dependencies and `npm run build` to build the project should work with 1.3.5.

Newer versions work the same way.

json-editor can also be installed via CDN and npm.

**Comment by germanbisurgi** [comment]
Feel free to reopen
