### ISSUE TITLE
Missing validation by type

### ISSUE THREAD

**Issue by vrockai** [json-editor/json-editor#133]
### Expected behavior

Want to see validation error about wrong type used.

### Actual behavior

The value is automatically converted to the right type.

### Steps to reproduce the behavior

In the demo: https://json-editor.github.io/json-editor/

If I type "30r" into the age input and press enter, the value is automatically converted to "30" instead of showing me the error about not having integer in the input.

**Comment by germanbisurgi** [comment]
wow. its that an issue or a feature?

**Comment by vrockai** [comment]
It depends on what the original requirements were :) From where I stand it's a bug. The schema is:
```
"age": {
      "type": "integer",
      "default": 25,
      "minimum": 18,
      "maximum": 99
    },
```

If I type `12`, I got an error, exactly as I would expect for anything not matching the schema:
![image](https://user-images.githubusercontent.com/1726340/42635206-ba0fe1a4-85e5-11e8-9f69-fbabb591e055.png)

But if I type `25weqd`, there is no error and the value is auto-corrected to `25`, while the value is clearly invalid since it's not matching the schema.

**Comment by germanbisurgi** [comment]
Looking at the editors code i found that they follow this pattern.

1) listen for "change" on the editor's input.
2) on input changed -> sanitize value (here is where typecast occurs depending on the editor's type)
3) set value
4) trigger onChange
5) root editor validate all sub editors
6) display errors if needed

Here is the number sanitize method

```
sanitize: function(value) {
    return (value+"").replace(/[^0-9\.\-eE]/g,'');
}
```

**Comment by germanbisurgi** [comment]
I think we can close this problem if we agree that it is a feature.

**Comment by vrockai** [comment]
Personally, I don't really care if it's a feature or a bug, because my priority is having this working as I described in "expected behavior". In the worst case I would need to fork this and implement it myself in the future or switch to a different json editor lib. One way or another, your analysis would really help me once I get to this fix, thank you very much!

In other words. If this is a feature, please consider this issue a "feature request".

**Comment by pmk65** [comment]
@vrockai You don't need to create a custom fork. Just override the sanitize function for integers, like this:
````javascript
JSONEditor.defaults.editors.integer.prototype.sanitize = function(value) {return value}; 
````
Then it wil return the original value back (same as it does for strings)

**Comment by schmunk42** [comment]
@germanbisurgi Can you add this as an example to the docs.

**Comment by pmk65** [comment]
It is also possible to override it for a specific path/field, like this:

````javascript
var path ="root.integerfield";
editor.getEditor(path).sanitize = function(value) {return value};
````

**Comment by germanbisurgi** [comment]
validation by type was added
