### ISSUE TITLE
Evaluate dependency from a variable out of the editor

### ISSUE THREAD

**Issue by djice** [json-editor/json-editor#1332]
### General information

- json-editor version: latest (2.9.1)

### Expected behavior

Dependency can be evaluated from an external javascript value

### Actual behavior

Dependency is evaluated from a field of the editor value

### Steps to reproduce the behavior

Direct link to example: https://is.gd/6hSJnK

```javascript
 {
   "title": "a awesome form",
        "type": "array",
        "items": {
        "title": "an array",
            "type": "object",
            "properties": {
            "aFirstField": {
                "type": "integer"
            },
            "aSecondField": {
                "type": "integer",
                "options": {
                    "dependencies": {
                        "a_variable": 100
                    }
                }
            }
            }
        }
 }
```

Display or hide a field depending of a variable out of the editor.

Is there a trick to do it please ?

**Comment by djice** [comment]
Hi,

I just wanted to hide a field like the dependency feature do it.

My generated form is an array, I think it's no possible to use watch:

`editor.watch('path.to.0.field', () => {
  // Do something
})
editor.watch('path.to.1.field', () => {
  // Do something
})
....`

And even if I use watch, how can I hide the field ?

**Comment by aethy** [comment]
I think you should watch the entire array object (or in your test example, the 'root'). Anytime it changes, you could iterate over the array and based on your condition set `aSecondField.options.hidden` to `true`.

**Comment by germanbisurgi** [comment]
I second @aethy solution :)
