### ISSUE TITLE
Option to change the default behavior of insert

### ISSUE THREAD

**Issue by vricosti** [json-editor/json-editor#1333]
Hi,

I am testing this library and I cannot get used to the way it works (and unfortunately for the moment I havent found an alternative), but 
when I click on insert a node on a node, I would like the node to be inserted as a child of the current node and not at the same level.
Is there an option for that ?

**Comment by schmunk42** [comment]
You need to define the schema accordingly with something like `children`.
See https://json-editor.github.io/json-editor/recursive.html for an example.
