### ISSUE TITLE
Validate against at least one of two fields

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1338]
I have two text fields where the validation requires that at least one of the two is filled out, but also both can be.

I first used a "type of field" and a text field but the requirement that both can be filled out came later.

Making either field mandatory is easy with minLength. Making "at least one" mandatory is proving challenging.

**Comment by germanbisurgi** [comment]
I would use `anyOf`. [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWzLxBAeSKoA2qAhTIVKbBoaQasjHloQWnYURQUjDwAOYKJDJk4ihusp4KdMEAMlShUMqoAIwAvrkstvY6TjAu3jAAJq6+ujEBQaEJyakh6Vm52QC6bHYOxaWg7vHe1f6BwWFsEbLRsR7y2WwVVdo1imMN7WyIymAUvI72UsgxwVCOZDxw8Arpaqt4YGBQdWQQACwguUA)

```json
{
  "type": "object",
  "anyOf": [
    {
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "minLength": 1
        }
      }
    },
    {
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  ],
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "id": {
      "type": "string"
    }
  }
}
```

**Comment by eduo** [comment]
Hi.

Not sure it works out. I tried it and I get a "root" menu with json in the options and selecting anything in it makes no difference. Unless the menu is supposed to be used for something (it shows in your example).  

I'd need to understand what it's for so I ca remove it via JS events

**Comment by eduo** [comment]
I'm looking into custom_validators in the meantime, but there's not a lot of information there. I assume I can have either a custom validator validating the concatenation of both fields and is triggered when none has data.

**Comment by germanbisurgi** [comment]
@schmunk42 This could be a good example for if-then-else. The feature is still to be released but meanwhile we could add a test for this case.

```json
{
  "title": "Test",
  "type": "object",
  "required": [
    "field_a",
    "field_b"
  ],
  "properties": {
    "field_a": {
      "type": "string"
    },
    "field_b": {
      "type": "string"
    },
  },
  "if": {
    "properties": {
      "field_a": {
        "const": ""
      },
      "field_b": {
        "const": ""
      }
    }
  },
  "then": {
    "properties": {
      "field_a": {
        "minLength": 1
      },
      "field_b": {
        "minLength": 1
      }
    }
  }
}
```
