### ISSUE TITLE
Is it possible to load startval using ajax like the schema?

### ISSUE THREAD

**Issue by rodmonic** [json-editor/json-editor#134]
### Expected behavior
I tried to load my start value JSON from an existing API call using the same format as with schema:

        // Initialize the editor
        var editor = new JSONEditor(document.getElementById('editor_holder'),{
            // Enable fetching schemas via ajax
            ajax: true,

            // The schema for the editor
            schema:  {
                $ref: "/api/schema/"
            },
            theme: 'bootstrap4',
            iconlib: 'fontawesome4',
            // no_additional_properties: true,
            disable_properties: true,
            disable_edit_json: true,
            disable_collapse: true,
            disable_array_reorder: true,
            startval:{
                $ref: "/api/item/id=121323"
            },
        });

This did not work, is this expected behavior? 

Is there another way of loading a startval json from an API call? I'm having trouble getting to work.

**Comment by jeremy21212121** [comment]
I would try making the API call before initializing the editor.

It would look similar to the example here: https://github.com/json-editor/json-editor/blob/6fc274970c7a67259e93258e67022fd0a3f14e45/tests/pages/advanced.html

In that example, "starting_value" is manually defined. Instead, store the result of the API call as "starting_value" then use that as the startval.

I hope that makes sense. I haven't tried this yet myself, I will try to post a follow up when I do.

**Comment by niebert** [comment]
You can also initialize the JSON Editor without a starting value, that builds the editor in the DOM and then call the API call `editor.setValue(starting_value)` when the API call was successful. 
```javascript
    // Initialize the editor
    var editor = new JSONEditor(document.getElementById('editor_holder'),{
        // Enable fetching schemas via ajax
        ajax: true,

        // The schema for the editor
        schema:  {
            $ref: "/api/schema/"
        },
        theme: 'bootstrap4',
        iconlib: 'fontawesome4',
        // no_additional_properties: true,
        disable_properties: true,
        disable_edit_json: true,
        disable_collapse: true,
        disable_array_reorder: true
    });

// Call the API with a Promise on success call populate edito with starting_json by

editor.setValue(starting_json)
```
When what to create the editor if and only if the API call was succesful use a promise.

**Comment by pouledodue** [comment]
would be great to add the functionality suggested by @rodmonic

**Comment by pmk65** [comment]
> 
> 
> would be great to add the functionality suggested by @rodmonic

Just do as @niebert described. You can even do it wit ES5 code, like this:

````javascript
var editor = new JSONEditor(document.getElementById('editor_holder'),{
        // Enable fetching schemas via ajax
        ajax: true,

        // The schema for the editor
        schema:  {
            $ref: "/api/schema/"
        },
        theme: 'bootstrap4',
        iconlib: 'fontawesome4',
        // no_additional_properties: true,
        disable_properties: true,
        disable_edit_json: true,
        disable_collapse: true,
        disable_array_reorder: true
    });

editor.on('ready', function() {
    var xobj = new XMLHttpRequest();
    xobj.open('GET', 'json-startdata.json, true);
    xobj.onreadystatechange = function() {
      if (xobj.readyState == 4) {
        if (xobj.status == '200') editor.setValue(JSON.parse(xobj.responseText));
      }
    };
    xobj.send(null);
}
````
