### ISSUE TITLE
##Info needed. Difference between anyOf, oneOf,allOf

### ISSUE THREAD

**Issue by 744825** [json-editor/json-editor#1342]
Hi,

Can someone explain the difference between the above. They work the same in in form rendering. Was not able to understand difference. Documentation link will also helpful.
Thank you

**Comment by germanbisurgi** [comment]
[json schema](https://json-schema.org/understanding-json-schema/reference/combining.html) explains the difference very well.

In JSONEditor the  `anyOf` and `oneOf` UI is the same but the validation is different.
