### ISSUE TITLE
 Custom Validation message

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1345]
Regex pattern matching is great for validation, but errors showing the regex are very hostile.

Is there a way to customize the error message when validation is not met? Sometimes you just want to put "Enter a valid vehicle plate number" or "enter a valid IBAN number" without showing the validation itself.

Custom validation can be set in code, but there might be a way to set it in the schema itself that I'm missing.

**Comment by germanbisurgi** [comment]
You can also override translations per editor in the it's schema options. Here is the documentation for that. [readme](https://github.com/json-editor/json-editor#language-and-string-customization)
