### ISSUE TITLE
JSONEditor.AbstractEditor.extend is not a function

### ISSUE THREAD

**Issue by StacyMader** [json-editor/json-editor#1349]
### General information

- json-editor version: 2.9.1

### Expected behavior

JSONEditor.AbstractEditor.extend is a function

### Actual behavior

I see an exception:  JSONEditor.AbstractEditor.extend is not a function.

### Steps to reproduce the behavior

My code i below, however, I don't see the "extend" method in JSONEditor.AbstractEditor from the console either.
```javascript

			JSONEditor.defaults.resolvers.unshift(function (schema) {
				if (schema.format === "footprintui") {
					return "footprintui";
				}
			});

			JSONEditor.defaults.editors.footprintui = JSONEditor.AbstractEditor.extend({
				build: function () {
					var self = this;

					// Create a button element
					this.button = document.createElement("button");
					this.button.innerHTML = "Open Modal";
					this.button.className = "btn btn-primary";

					// Append the button to the editor container
					this.container.appendChild(this.button);

					// Define the action when the button is clicked
					$(this.button).on("click", function () {
						//$("#footprint").modal("show");
						console.log("hello");
					});
				}
			});

```

**Comment by germanbisurgi** [comment]
[Here](https://github.com/json-editor/json-editor/blob/master/docs/custom-editor.html) is an example on how to do this

**Comment by StacyMader** [comment]
Thanks @germanbisurgi , I was looking at an example of the Wiki so thanks for the update.
