### ISSUE TITLE
properties not displaying form elements when required property is enforced

### ISSUE THREAD

**Issue by sriks316** [json-editor/json-editor#135]
I have a schema which has an array called LaneList which in turn has an array called LinkList.

Here is an example where it is working fine:

http://jsfiddle.net/ytcqN/123/

As soon as i add required properties under link list, the first link breaks and shows up the array instead of form elements. Here is an example where linklist does not work for one of the lanes when required is added:

http://jsfiddle.net/ytcqN/135/

`"required": ["DataCapRocStart", "DataCapRocEnd", "DataCapRecordPerCap", "DataCapMID", "DataCapBankID", "DataCapTID", "DCVitalVisaIIMerName", "DCVitalVisaIIMerStreet", "DCVitalVisaIIZip", "DCVitalVisaIIPhone", "DCVitalVisaIICountryCode", "DataCapCurrency", "DataCapIndustry", "DataCapBatchSettleMode", "DCVitalVisaIIMerCity", "DCVitalVisaIIMerState", "Prompt_Cashback_Debit", "DataCapACTime", "DataCapFileSize", "DataCapLifeSpan", "DataCapInitBatchNo", "DataCapMaxBatchNo", "NoSigLimit", "DataCapDupCheck", "DataCapPartial", "CreditCard4Void", "CreditSurcharge", "Prompt_CVV_Credit", "Prompt_CVV", "Prompt_AVS", "TipType", "DataCapServerIDOpt", "Surcharge", "DataCapNegBalance", "merchantlink_uri", "paymentech_uri", "hostkey", "hostcert", "saf_enable", "saf_type", "saf_max_transaction", "saf_max_retry", "saf_allow_emv", "PinpadSN", "EmvPinpadType", "MPG_WorkstationId", "MPG_POSVendor", "MPG_POSModel", "MPG_POSVersion", "MPG_MWVendor", "MPG_MWModel", "MPG_MWVersion", "MPG_RevenueCenter"]`

EDIT: let me know if additional details or examples are required.

**Comment by sriks316** [comment]
Hello, can someone review my schema if verify if it's an issue on my end?

**Comment by sriks316** [comment]
@germanbisurgi .. Could you please take a look at the jsfiddle example and help me out?

**Comment by germanbisurgi** [comment]
Hi srik, i saw and i understood very little, There where also some weird behaviors lke every time i add an item the item looks different from the last one and so on. 

I am on holidays at the time of writing but if you could make an example on the interactive page of this repository i will glad to spend some time on it :)

**Comment by pmk65** [comment]
@sriks316 Your jsfiddle examples use the old jdorn version of json-editor, not the updated one.
So If this is still a problem, please post an example link using the interactive demo on the repository. Otherwise, this issue will be closed.
