### ISSUE TITLE
Validation is not working with Autocomplete

### ISSUE THREAD

**Issue by RajiSudharmaSoman** [json-editor/json-editor#1352]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by RajiSudharmaSoman** [comment]
Hi ,

I would like to dsiplay of message 'Value required' when the form loads and goes off when the user enter value in the text box or select an item from the drop down. This is not working. I do not have any samples in this site.

My code is given below: Please send me samples

<template>
  <div ref="jsonEditor"></div>
</template>
<script>
import "@trevoreyre/autocomplete-js/dist/style.css";

import { JSONEditor } from "@json-editor/json-editor/dist/nonmin/jsoneditor.js";
export default {
  name: "PossibleFonts",

  mounted: function () {
    this.initJSONEditor(this.$refs.jsonEditor);
  },
  data() {
    return {
      schema: {
        properties: {
          text4: {
            type: "string",
            format: "autocomplete",
            title: "Local form lookup (Font names from 'possibleFonts' array)",
            description: "Enter a text of minimum 1 characters. (Try 'a')",

            options: {
              autocomplete: {
                search: "search_local",
                autoSelect: true,
              },
            },
          },
          possibleFonts: {
            type: "array",
            format: "table",
            items: {
              type: "string",
            },
            default: [
              "Arial",
              "Arial Black",
              "Times",
              "Tahoma",
              "Helvetica",
              "Comic Sans",
            ],
            options: {
              collapsed: true,
            },
          },
        },
      },
    };
  },

  methods: {
    initJSONEditor(element) {
      JSONEditor.defaults.callbacks = {
        autocomplete: {
          // Lookup using data from form
          search_local: function search(jseditor_editor, input) {
            var ed = jseditor_editor.jsoneditor.getEditor("root.possibleFonts");
            if (input.length < 1 || !ed) {
              return [];
            }
            var data = ed.getValue();
            return data.filter(function (item) {
              return item.toLowerCase().startsWith(input.toLowerCase());
            });
          },
        },
      };

      const editor = new JSONEditor(element, {
        schema: this.schema,
        theme: "bootstrap4",
        required_by_default: true,
        show_errors: "always",
      });

      editor.on("change", function () {
        //var json = editor.getValue()
        var validate = editor.validate();
        console.log("valiii " + validate);
        // console.log(JSON.stringify(editor.getValue()));
      });
    },
  },
};
</script>

<style scoped>
</style>

**Comment by RajiSudharmaSoman** [comment]
Hi, This seems to be working if I not passing 'theme' in the below creation
 const editor = new JSONEditor(element, {
        schema: this.schema,
        required_by_default: true,
        show_errors: "always",
      });

Please help me it working with  theme 'bootstrap4'

**Comment by RajiSudharmaSoman** [comment]
Please find the below screenshot with specifying theme and without specifying theme
**with Theme**
   const editor = new JSONEditor(element, {
        schema: this.schema,
        theme: 'bootstrap4',
        show_errors: "always",
      });
<img width="947" alt="image" src="https://github.com/json-editor/json-editor/assets/26257600/e9dab364-48d9-4203-87e9-6792a90501bc">
![screenshot](https://github.com/json-editor/json-editor/assets/26257600/10166c14-d47b-4fac-9c9c-275273efd446)

**without Theme**
   const editor = new JSONEditor(element, {
        schema: this.schema,
        // theme: 'bootstrap4',
        show_errors: "always",
      });

![screenshot_with_theme](https://github.com/json-editor/json-editor/assets/26257600/ef4363d9-d81a-4cf2-ae1f-9c9084e14aac)

**Comment by schmunk42** [comment]
Here's an [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgEEBXeHYnAW2RN4qKKgAeAQwFMKVbMgBOONArqoAzpijhoMbAH0AFqgkATVAq069emimatg6%2BAtoQA5rN024AMxwKfBJkLNiGtKbmEF421Aj0MqHsXDz8gqjCopLSzJTetsDm6sSuyHQ40UnAADzIAHwAKuHqWVLpUOqGOADuLQBuEq44HC3qGRzILSNu7lDwxlASKbw5maim9AHkUHgSY6ZQFXML1RJQhgqovgC8YHfAhvDwkxgA9K9L3CvpwgB0Lqg%2BgFUIhLr8Vq8AMSvAgSAbFUrwAC03wqqAgZHuc0G7gyt3u%2BjwDAkEAA1nc4HVPqlVqhqh86lAGLQ8ApBohflAmiIxvAJlB%2FApRBJiIYmTgcKT%2Bej3G4RLQWuZfHKDm5Fh00MRaBIGFBiDqGLtiKSmQr4L96fUYrE4MpyhBNKFrLE4u5XKZ9LwGBw%2BA6tABGABMchsAF8Q1BQ3kfAhxCEsM6Y0g0Fo4M5XB5rTG%2BG4ADIy%2BYB6M24CCoLx7DU75CXIRuJ0RgObAAdVopNoaA2ZwYEqlyCgAAoAAoSXFzBIaACUWYKRRKHftqeAAFEMRZ1cIxPBDr4oDmILQ%2BD6oABmPWGQYi4QKdS%2FGdxO20CqOhN1gpuiKenDe30vqAANmLF04CrNIaysN8YzGQZRSXaCFFFfRujbDt1m1e8S1xeAACUNA4Bh4AANR1DgmzgLDcPUfCiJI1AkJQzt0OAICXWwS4IHMBRKOopd2M47iCPo9tGIkDCY2pABlVAmFILQXFIyDIzfcN8ijCMaDjYMnTfOwUyqdMZgwuB93zDxC1Cf0WLiMtgiXUDaSM%2BJGyXAARNhmzYcVJX5AcXJJBUxXTVAMggKQp0cudESfSpHFXa8NzjHc9zcQ9jzPUVL1ICxb0cx9nwg%2FIYw%2FD0vR9P1QkAxSQOWMCMibRNWLTEwEMMODmsQ0wJG6UTmMU10MgEmjvTI4AKLwgjiOG%2FROu6sSCkk6SSAreT0EKvQVJdDb1pYjStxPArgIQew4JcQzerWvwAnLOyaoc87DobRJHEo%2BBeA4DFXA0Ly%2B0HABhYYPtocL7pLSKF2ipc4vXM5N23HBd33VK%2BFPc9MuvHKQZjPLytfNbXXdL8fxxgCrPm26fnqvrsHg2D9Pawx9EuZw3sBjQ5v6nDxqGhSqjGqiJtoxmNFegHTrZzHGuAPiLEG3j0X4rmheZ0XPsdUnxJSKSZOWhQFLxpS1q2mA1PyXb4AAFgOktkxGgzMwl6yrtsqp7IpxzHpG3MeB1AUru%2BnyADEKm3UK%2BC%2B3wlGRgByZAcHUdQWSYIOMXUKPFgUNlEGnB3sDBsoIaqKGhRhxL4eSg8j2R%2F1UbZLKb05AcGgURAoCjiQo%2Bz0nbXz%2FLtP18iCdK38tEq%2FvgFd8C%2B9YgoadaumYIZnt9QYdnK01xbZNCFbFKN9aIxNmNY%2FjxPUGT%2BA%2Fwa%2BtjpdjOJEQRybIrGgJCJWsLuAehUD4C%2BqqOvTHDtp4YAyku6FCuEsAiWgADav82CuB1HNdg8DdQACFiTGkQcABoh5xbq2wA0CQXQgiYIABLST6BkWg%2BpMH%2FRzMQKAEkSSOjfAAXVAdjH%2BY8vTEkmOsOSutVqbX3nIFSoZgBAA%3D%3D%3D&value=ETI%3D&code=EQehAIEsDsGMBsCuATApgYQMqYBQB1gALAF2IAcBnALjFmWgCsKA6BAexQDN4BDAJ1Ss2AWxA8GPAB4h4kAEYUQ3HgHMAtJFhtoa2BUUBmZkYAMIPYuXrN21voIBKPNGfOw4AOLw2cnvHCwfvC%2BsADW4LIUxM4A7jDIbDHMAFKYAPIAcgCiyJDEbHzMaJw8iPDELIHwwTxhFOAAvOAA3s7g4ASl%2BVrCZPCoxKgEVC1t7eDuACqEkPWzAUEh4ZyIcMSQ2vWcBeDEhKgdwF1sPX0DQ8DgqLn5fGPt7gCS0Lv74BSw%2B8I84ACeHOABJxUHxdmxXgcqjUwuAVmsNi85L9wKFUL97hMIBk2IMRgBGKLgMj8HjCc6gmALapLKD1ACCABkAOp0gCamHAPyBINQcAO%2BQhAUQfAE0GIVxuBWYGPcmHB%2F0Q4GgqGuYM5yGQnPAADd%2BJAeHJ%2Bmq9pDFrVwgLCGx4Jq9vMcLJURCZRACExrnkCgB9D23Ag6vUGo2Uk1XSSks71OSobxJJwuF7jdwMthsUKIMjgRAUGAqcDIHjEH6cPgiWEFYQYggUVD8T5e7xVYaw1awdbad61vifHDuyV8H39gA0UGgZEQxAco0T4wDoNVTT7noHvqlTG0q8KKgGOWXOAA5KWccwyGx9PJ%2BgAxbQVfcOADcGPakE44BwMHHxGY%2FWgKj24AAHnAPFwAAH1A8AAEJrinVoZ1nQEBmFF4AG0AF1H3g9oAF8nznfNCx%2BJprmYbdiAANT8RBUBwB88IEYhkIIotmE4SByhBHA4TbBF30GYRYLw9oGKYvJUGEZh8hTGIQXQHga1o5gon4ComTyQh3zHCdJLYaTZPkmiHDorDwGw4zZ2wocq3g2UkMzbZQQAETpFkIlTdMyCrYAazrQgvQLGIeGbbj2xeHzuw0pdbkHZcRw%2FCdBJM3VQWFfwmn3EhyGoMAAp4ZgeBiFhkFCEBtVQBhoB4bVlTECcThEM5BgAfgARwafdwAAaiuOA2DQABVAAlR5NM%2FYz6KQvgXmVGJwAABVLYRZhokLeIEChrTKxKEPGF833ir8fz%2FQhAPAAxtp28YRKmxCNvgMqcHQ8zLtwhNLthAYe1ShxJP2aAuNbUKcHW09oBrC73uul4Qc2QR13%2B56drM37eQB%2BEOxwAsiwhy71s2misZ4RGELMzCkeJyyvLIwbUAoMoKKo1B%2FIKoLgBGVaO2p2n6copAaKi71NxHdb6Zx4TJuh7nykk1BQiiMnxkpt6kwgTA7PLUE1NCSAyA9H5vDTDMvPC%2Bs4m13XclZ9nAYRTtfN7Gt%2Bxi244q0ydpx25Ksz4NLwAy0hKBoEBeWYM2db15gChUEAYjEMhIBPQgyCa2pQoaFrqL4X4ADJImIBoTcIbOHO%2BfP4ezgpIBUGAGgAKmzig%2BEL9qup6rQBuG0aEswibGJumb5sW5a0Z4jG8fu1Axd218u8O3ljtO86PfexC%2B8lu6HqehWkdcEz2mBYgvp9n6TX%2BjmXmB2nQfB5fIYl27r7hjaEe3kmT7%2BkfQrfQmp9nceHsJswDOIJfhKS7J8YmFlIGmQplZeCBAuZ03KLzaiXow4W31MFG2nMBg0yQQzPmDtNzOwKMLKW7s4I7Shrdemkk8j9FfkrWcBBRRoD4Hg%2BmaDIDmz1lg9G%2F0BYrmHDQ8oI4yClkoFPahKF9wAVkH7Vu4i2CUFbvuAAfPuOB71ZG5G1AEXg%2BgGgEDDmodYxB%2BgEA0a3EW0szFGm6rIkAuiNFaMujoyAeiEDyQoEY4AJiKDQB1rraIwA1EAQoN8aoVjuo2K%2FAEoJAxVHhMifAMJTiPEuKEn7ACMhIAaLQswBgbAYAHjvIwuBLpwBq0YvZHY61D4cDFHwSAtNmCoEVFoJpLT6gGw8sbcBfl6laFWMQZptM%2BGjzCgMohTshajjGrfcYXtUqND9plQOYAhmNNGd0tpiAQD1NKgAJhAJVMkIAOrdV5O3VAQ0RoHXGiZahA8FoiGHufN8%2F9J6LNnHtWe3557%2FiAkvShK9qFfMemhaBOFd7vQPkfeA79UYfMvhQR%2Bv8rr3xhmDJ%2B2haKvygSjM%2B2CL4%2Fx%2BQhP5kE6Qih4KA2Y1K%2BC0sxoRIyzEiLgHQgShCEKf5cpwtA0mGImHjAQbg8hKCmZbJGWMigEyv6IJ5ozGZy4SF8DIfgqRWLyHMDOagcpXlWEgg4eUL0UqunjLZi2fhyropzNiWIiRFBNVrw5bI%2BRlyiSOtUZkve2TdH6O8b44Z5qKCmPoRcH12jwnEheF4wxBArAaE6bCXg1hOlqA9bE%2FK8AyCEB4Ec9AfVBBSUSPpBSU4HGWJyWing0A1EKJidq3VST0nakjW4gC%2Fq40%2BIIMGnZtM1DxLIMEqtESghqLkvHIs8ARiZu1YEKdfgkljqiTk5xmismONkPkwpxT%2Fr7jKUKsYr1sI92gFMN42xqiJFzBEGAtNOQCHAN8aAWMCjIlrZqAQPAEjQHgKA8ArIASBBeD%2BzUsBsz5GEAEItnI5BsDKpyV94BoyxmlIEmegjRzKT5GwV8cRX2JBSOkbI%2FYpyCKKLTUZbBfj4ucFhpoA8CMJCSKkTIu5biYxOIgMkYogGZ1%2BGrfobYCj4GAAAYnhmoTcagS6OBHAwa4LL7zACAA%3D%3D&style=ETI%3D&theme=bootstrap3&iconlib=fontawesome3&object_layout=grid&template=default&show_errors=always&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=1&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1), it uses `minLength` and `showErrors=always`

**Comment by RajiSudharmaSoman** [comment]
Thanks,
But I am not seeing showErrors in the code. Please send me the complete code
jseditor = new window.JSONEditor(document.querySelector("#json-editor-form"), jedata);

**Comment by schmunk42** [comment]
> But I am not seeing showErrors in the code. 

It's an editor option: `show_errors`, same as BS4.
https://github.com/json-editor/json-editor#options

![Bildschirmfoto vom 2023-06-19 21-32-27](https://github.com/json-editor/json-editor/assets/649031/c704bce0-147e-48dd-bf57-bec51de03361)

**Comment by RajiSudharmaSoman** [comment]
@schmunk42 Thank you. I understood what you suggested. But in my code it actual bootstrap css is not applying. In the bwlo imgae you can see 
Value Required' text is in black colour instead of red. Not sure what all settings we need to define.
Code is attached here. In the code the below line
    const editor = new JSONEditor(element, {
        schema: this.jeData,
        theme: "bootstrap4",
        show_errors: "always",
      }); is not working
Since this.jeData is not working I set it as this.jeData.schema and   set 'theme' and 'show_errors_always' manually like below. But still not working
   const editor = new JSONEditor(element, {
        schema: this.jeData.schema,
        // schema: this.jeData,
        theme: "bootstrap4",
        show_errors: "always",
      });

Full code is attached here
[PissibleFontsVue.txt](https://github.com/json-editor/json-editor/files/11797622/PissibleFontsVue.txt)

**Comment by schmunk42** [comment]
> Full code is attached here

This is not a complete html page.

**Comment by schmunk42** [comment]
>  I cannot send the full code as it is restricted. 

We'd need to have a minimal working example to reproduce.
Besides from that, have a look at your browser console and vue debug tools.

**Comment by RajiSudharmaSoman** [comment]
@schmunk42 Thankss. Let me check if I can send you the html. But meanwhile please check the console logs in the below image. <p invalid-feedback style is 'display:none'

<img width="251" alt="image" src="https://github.com/json-editor/json-editor/assets/26257600/0693428b-a1f6-4dff-9c71-2b93b504a785">

**Comment by RajiSudharmaSoman** [comment]
@schmunk42 Finally it got worked. Issue was with the version  @json-editor/json-editor@2.3.0. I updated version to latest @json-editor/json-editor@2.9.1 and it got worked. 
Here I am attaching the html with both versions
[json-editor-2.3.0.txt](https://github.com/json-editor/json-editor/files/11816909/json-editor-2.3.0.txt) //Not working
[json-editor-2.9.1.txt](https://github.com/json-editor/json-editor/files/11816911/json-editor-2.9.1.txt) //Working
