### ISSUE TITLE
Could this works on yaml, xml too?

### ISSUE THREAD

**Issue by MennaEwas** [json-editor/json-editor#1353]
### General information
What If I want to use the same version and make it possible on yaml and xml too without specifying the type before
- json-editor version: 4.0

### Expected behavior
It should know the extension of the file alone (yaml - xml - json - ini) and have the same behave it has

### Steps to reproduce the behavior

> as It came to my mind the following steps could be helpful.
1. Auto-recognition of the form-like using some logic 
2. translate the updating fields according to the new formula
3. The ability of converting a file from any type of the above type to json or ini formate 
4. allow downloading of the new file

Direct link to example: https://json-editor.github.io/json-editor/

I would like to work on this issue for enhancement if you can assign it to me @schmunk42

**Comment by schmunk42** [comment]
Using another format than JSON is out-of-scope for this project, since it relies on JSON-schema.

You'll have to do the conversion on your own.
