### ISSUE TITLE
Better Upload Files

### ISSUE THREAD

**Issue by ctaity** [json-editor/json-editor#136]
Hi, is possible integrate jQuery-File-Upload (https://github.com/blueimp/jQuery-File-Upload) to have better file upload. Can you send me a guide to implement? Thanks

**Comment by schmunk42** [comment]
We won't support another lib in the core, but I think it should be feasible to integrate other uploaders like so: https://github.com/json-editor/json-editor/issues/111#issuecomment-400331222
