### ISSUE TITLE
Select Field Remote Options

### ISSUE THREAD

**Issue by ctaity** [json-editor/json-editor#137]
Is a way to use a selectize or select2 to load values from remote url ?

**Comment by marc7000** [comment]
You can configure the plugins via `JSONEditor.plugins`
```
JSONEditor.plugins.select2.allowClear = true;
JSONEditor.plugins.select2.placeholder = {
    'id': 'undefined',
    'text': 'Select or type to autocomplete'
};
```
https://select2.org/data-sources/ajax
Maybe this could work i haven't tested yet:
```
JSONEditor.plugins.select2.ajax: {
    url: 'https://api.github.com/search/repositories',
    dataType: 'json'
    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
}
```
It's a bit more complex for the selectize plugin, see section "loading remote data":
http://selectize.github.io/selectize.js/

**Comment by evowise** [comment]
Has someone figured out how to get select2 or selectize to work with asynchronus obtained data ?

**Comment by germanbisurgi** [comment]
like marc7000 suggest
