### ISSUE TITLE
Bootstrap5 range background not visible

### ISSUE THREAD

**Issue by PythonFZ** [json-editor/json-editor#1378]
### General information

- json-editor version: cdn, latest

### Expected behavior

Using the `theme: bootstrap5` the range slider background is equal to the background of the form.
This is caused by the `class="card card-body my-3 bg-light"` background color, which is equal to the background color of the range.

### Steps to reproduce the behavior

Direct link to example: https://jsfiddle.net/90v231de/

```javascript
{
        theme: 'bootstrap5',
        schema: {
            type: "object",
            title: "Car",
            properties: {
                safety: {
                    type: "integer",
                    minimum: "0",
                    maximum: "5",
                    format: "range",
                }
            }
        }
    }
```

### Potential fix

Change
https://github.com/json-editor/json-editor/blob/9a8da95b2fefcc2302e4ab624e204e83e0ce25c2/src/themes/bootstrap5.js#L10
to `bg-white` (quickfix: `JSONEditor.defaults.options.object_background = 'bg-white';`)

**Comment by germanbisurgi** [comment]
This happens with bootstrap@5.3.1 but not with bootstrap@5.2.2. There is also an [issue](https://github.com/twbs/bootstrap/issues/38999) in the bootstrap repo so this might change.
I will suggest using css or bootstrap variables to change the color.

**Comment by germanbisurgi** [comment]
Bootstrap suggested the same [solution](https://github.com/twbs/bootstrap/issues/38999#issuecomment-1685236465)
