### ISSUE TITLE
"class" property not supported aside from "links"?

### ISSUE THREAD

**Issue by roypardi** [json-editor/json-editor#138]
The documentation page has this example:
```{
  "title": "Blog Post Id",
  "type": "integer",
  "links": [
    {
      "rel": "comments",
      "href": "/posts/{{self}}/comments/",
      // Optional - set CSS classes for the link
      "class": "comment-link open-in-modal primary-text"
    }
  ]
}
```

I could not get the `class` property to be recognized by any other elements and from looking over the source code, it looks like it just isn't implemented.

Can anyone confirm this? – maybe I am reading the code wrong.

**Comment by pmk65** [comment]
Styling Info added to wiki
