### ISSUE TITLE
[Question] get value of  `anyOf`?

### ISSUE THREAD

**Issue by PythonFZ** [json-editor/json-editor#1382]
### General information

- json-editor version: "2.10.1"

### Expected behavior

I have the following form [json-editor.github.io](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJABMqRZGhABhGFIzYqAcSr0qUKYI0gIUyFSmwaTqWW0wRBqC6RGQi2OIojGywUBaEAEq+/sjRghBUEiJ0eO4gAL550TCxGSjGpuZWNgz2jqnphGCc3OKFIADKEKpSVba1Ti5uHjBehj5+AU7BoeGoUSAxcWWJEykLaaUg8Fk5Uvlti5ud3b01DgpQG43NPPtsg+nDo6AA5tV254Zk8IIA8kSoADaWh6ALKAGIAPQ6PSISHHdynD6OQogvSEKEw/SQkxmCzWPrnPIAXTY0zCEVA42ScwOxSWIAJZxRbAopj0PgYUz0MwiIWwiCoRRKhAA6uyiJyMvVNngwGALN87gt6ZsmciLlcyk0uLc2ohlGAKLx3K4pAYQDB4FB3GQeHB4BdVFyynKwFBEPYyBAACwKHoARxE7O0vDwgl45NmKH5grJMEQEAEEcDwZ6oZwjhjcjjikNxsgfCtqFjQq2YF4vj8sAQcl4D3cngMpbYZA4ZAAHiWc2W/IgyHgLCbq7wOLRHSh7CJewmB0OsNgBBBBagpzP+4OqPXXI8m6upNP4xuh2QpD4I1XuwL13Ot6fz7wetJdHts9ej7fK2ehJGqBYbVeuZUPAn73j+WAQFmLYgGBEZYNargCrwUCQIBN6bl+D66P+d6Lo+RrNj2H4YbBv44fwZCevhFBoQUQA)

generated from pydantic via

```python
from pydantic import BaseModel, Field
import typing as t

class SphereGeometry(BaseModel):
    radius: float = 5.0

class CircleGeometry(BaseModel):
    radius: float = 5.0

class Geometry(BaseModel):
    geometry: t.Union[SphereGeometry, CircleGeometry] = SphereGeometry()
    wireframe: bool = False

schema = Geometry.model_json_schema()
```

I can selected either `SphereGeometry` or `CircleGeometry` and get the same values e.g.
```json
{
  "geometry": {
    "radius": 5
  },
  "wireframe": false
}
```

Is it possible to either
- add a default value that is not displayed in the form, such as `_name: <name of the field>`
- get the value of the drop-down from the editor object?

What would be the expected way of doing this?

**Comment by germanbisurgi** [comment]
1) use `hidden` option to hide fields.
2) use `jsoneditor.getEditor('root.geometry').getValue()`

```json
{
  "$defs": {
    "CircleGeometry": {
      "properties": {
        "radius": {
          "default": 5,
          "title": "Radius",
          "type": "number"
        },
        "hidden_field": {
          "default": 5,
          "type": "number",
          "options": {
            "hidden": true
          }
        }
      },
      "title": "CircleGeometry",
      "type": "object"
    },
    "SphereGeometry": {
      "properties": {
        "radius": {
          "default": 5,
          "title": "Radius",
          "type": "number"
        },
        "hidden_field": {
          "default": 5,
          "type": "number",
          "options": {
            "hidden": true
          }
        }
      },
      "title": "SphereGeometry",
      "type": "object"
    }
  },
  "properties": {
    "geometry": {
      "anyOf": [
        {
          "$ref": "#/$defs/SphereGeometry"
        },
        {
          "$ref": "#/$defs/CircleGeometry"
        }
      ],
      "default": {
        "radius": 5
      },
      "title": "Geometry"
    },
    "wireframe": {
      "default": false,
      "title": "Wireframe",
      "type": "boolean"
    }
  },
  "title": "Geometry",
  "type": "object"
}
```

**Comment by PythonFZ** [comment]
@germanbisurgi Thank you for the very fast answer. This does partially work and would be a very nice workaround, but the values aren't updated when I switch between different `anyOf` values.
Is it possible to reset the editor to the default values of the specific property when changing the `anyOf`?
I was looking at
```JS
editor.on('change', (my_event) => {
      console.log(my_event); // undefined
      console.log(editor.getValue()); // does not contain information which anyOf is selected
    });
```

My workaround would be, defining the `<select>` manually and creating / destroying the editor `onchange`.
Is this a rare scenario or am I missing the intended way of doing it?

**Comment by schmunk42** [comment]
If you set `keep_oneof_values` to `false` the fields will be updated to the default or last set value, see https://is.gd/4ybqdg

The default demo does not have this option to be set in the UI. And the option name is a bit misleading since it applies to `anyof` also - CC: @germanbisurgi or are there differences I did not see?
