### ISSUE TITLE
Enum with mixed types

### ISSUE THREAD

**Issue by djeasterbrook** [json-editor/json-editor#1389]
question
=======

using json schema, how can i create an enum with mixed types.
For example: [ 1, 2, 3 , "A", "B",  99.99 ]

Thanks

**Comment by schmunk42** [comment]
While you can specify multiple types, you still need to set them manually in the dropdown.
There's no auto-detection for types by their input.

You could try binding a function on post change of a dropdown and set the type.
Or give `if-then-else` a try, like `if pattern (0..9) then type = integer` (untested).

**Comment by germanbisurgi** [comment]
In JSONEditor is still handled by an alternate form of the `items` keyword (specified in Draft 4). When `items` is an array of schemas instead of a single schema, it behaved the way `prefixItems`  (2019-09) behaves.

```json
{
  "type": "array",
  "format": "tabs",
  "items": [
    {
      "type": "number"
    },
    {
      "type": "number"
    },
    {
      "type": "string"
    },
    {
      "type": "string"
    },
    {
      "type": "number"
    }
  ]
}
```

`"format": "tabs"` is optional
