### ISSUE TITLE
Should a top-level `oneOf` label always be required?

### ISSUE THREAD

**Issue by flys1ck** [json-editor/json-editor#1398]
### General information

- json-editor version: `2.8.0`

I am using json-editor with a custom theme, where I render optional after a label instead of a required star. My schema is using a top-level `oneOf` to toggle between different form inputs.

![CleanShot 2023-10-11 at 14 45 58@2x](https://github.com/json-editor/json-editor/assets/34650380/6b9740e1-45a2-4819-8dcd-a2b4dcac7fe9)

Shouldn't the top-level `oneOf` always be required? I wasn't able to make it required using the schema. Here is the workaround I am currently using, which will make all `oneOf`s required:

```js
const isRequired = JSONEditor.defaults.editors.multiple.prototype.isRequired;
JSONEditor.defaults.editors.multiple.prototype.isRequired = function () {
  if (this.oneOf === true) return true;
  return isRequired.call(this);
};
```

Is there a better way to do this?

### Expected behavior

The label for the top-level `oneOf` shows required.

### Actual behavior

The label shows optional.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgEVAPJFUAbVAQpkKlNg0NIDgEcrx0+cHapAEzOoAjGyiCIVQkQoKRh4AHMQAF82Dlp4exN/Jxd3KVQABh8/AJRFYNCI6JApSgBaUSgIMSt3IjIRbHEUYJEqNhIZMiaQFW4AazwwAA8FByTfFI8UACYfGChsHJAAJUoAAm0xKvEs/0JBsEWyeMiiqSobERhz1wNrOIVbEABdOYWlgCkH3aWwTm5xNEjIkzBZkGhiDBFglHBM3FNMiBfHtckEQuEojE7BCxqDnPC0ihvEjsoF8hizmUKtsalQ6g0mi02sRpLJur0MANhqMQckCahZkj5tDcqsKBsttUfvswIcqMcomcLlcbnciFCAliXm8RSAAGIahTI37/HhRZ5FRDKMAUXhmExScEgeBUABuHh8qgYMrAUDRZAgABYFOdLtcqK5eHhBLxavVGqg6thEMzXDBEBABDHQyqI7wcIJE3IU2wrTb89BeKEi8nmZJeGRXGnYAg5LxceYYJZmlJWmwyBwyCMUEmSyA04gyHhFnbm7xYghUEy2BOpzOsNgBBAU0ve6n02uqO3eWDd33xwfp0eyFISjHG7cR8X95Orw3b0JeOdpKka2PV2+N53rGVCLFAOSjsyVDwIe77AVgECFk+tb9h+MZYPAwSHIgvBQJAf4vrBQGfu4YHXpuX42uCkErpeM7ETGpFUOB/BkEElEUARpxAA%3D

```json
{
  "oneOf": [
    {
      "properties": {
        "jq": {
          "propertyOrder": 1,
          "type": "string"
        },
        "json": {
          "propertyOrder": 0,
          "type": "string"
        },
        "raw-output": {
          "default": true,
          "format": "checkbox",
          "propertyOrder": 2,
          "title": "Raw Output",
          "type": "boolean"
        }
      },
      "required": [
        "json",
        "jq"
      ],
      "title": "Json",
      "type": "object"
    },
    {
      "properties": {
        "file": {
          "propertyOrder": 0,
          "type": "string"
        },
        "jq": {
          "propertyOrder": 1,
          "type": "string"
        },
        "raw-output": {
          "default": true,
          "format": "checkbox",
          "propertyOrder": 2,
          "title": "Raw Output",
          "type": "boolean"
        }
      },
      "required": [
        "file",
        "jq"
      ],
      "title": "File",
      "type": "object"
    }
  ]
}
```

**Comment by germanbisurgi** [comment]
No, a top-level oneOf in a JSON schema does not have to be required. To make an instance required, it should be defined as a property within an object, and the "required" keyword must be employed.

https://json-schema.org/understanding-json-schema/reference/object#required

**Comment by flys1ck** [comment]
Thanks for the response. That seems like a more logical solution than overriding `isRequired` to fit my use case.
