### ISSUE TITLE
Validation edge scenarios

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#14]
Hi

I may be missing something, but I can't find this in the documentation.

I can't find any option that will trigger a validation error if at least one option in a select (checkbox or multi-select list) is not chosen, or how to trigger an error when a required number field is empty (minLength helps with strings, but for numbers validation doesn't seem to persist).

Are there docs that explain special scenarios for validation? I can't find them. I imagine that jsonschema rules are followed but these don't seem to be covered.

**Comment by Zalasanjay** [comment]
i am also facing same issue. if there is any documentation that explain how to implement validation.
and is there any way to highlight manually catched error on json-editor using editor object.

**Comment by pmk65** [comment]
> 
> 
> i am also facing same issue. if there is any documentation that explain how to implement validation.
> and is there any way to highlight manually catched error on json-editor using editor object.

https://github.com/json-editor/json-editor#custom-validation
