### ISSUE TITLE
pattern of greater than 35 chars doesn't display properly

### ISSUE THREAD

**Issue by mrehder** [json-editor/json-editor#140]
### Expected behavior
GIven this variant in the pattern of a string
   "IDs": {
      "type": "array",

      "items": {
        "type": "string",
        "anyOf": [
          {
            "pattern": "^x$"
          },
          {
            "pattern": "123456789012345678901234567890123456"
          }
        ]
      },
      "minItems": 1,
      "description": "some description.",
      "uniqueItems": true
    }

There should be a pick of the pattern to use.

### Actual behavior
Only the first pattern is shown. A second pattern called "type" is shown.

### Steps to reproduce the behavior
Use a pattern of greater than 35 char length in an anyOf of patterns.
Any of the patterns and they show as "type" on the UI.

https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iACSAEQxMcAQwC28QhIDmskADMJANyxoosAPp0s0TU0U5u6JoboTIuJmTBiAuoRJosZNJFhiEoET9AwUnIQCTQ0CSImbSkA4jJEEAwwLRx5JgkcIgB5ZX5QEmswdDwkAD0ADwASEABffAKiksSARgAmAGYAFgBWADYAdgAOAE4ABnbu/uHxyd7B0YnO+brHepApCBxBYtjEFsIzDDotEhtSkAAlbyx2NDpYAAIRR7AsR4kSEmgiV4ALJ4sbB3B6POh/TKKV5YAB0THYOAgHFgO1gewQKXYsHWkhkiECwUSyVS6UO3hOEDOEFsSAAYlxkh9TI8ADISRm4pSbHAs2BpMB/RBdMmqdjQRhIABS6DRv2EmjwLiaaAuc2mizVC1my3V2qmdTkinx8RCW2KijQTDMovFiDaPUI3IgUnYUn2Q0dEgqztdiBGI3Wqg0WmKegMRl8JqJKS2pJUmik1kS+kMlsIkBgISDmm0YPDaZA1okYolIAAxMpVD0xmMDSATGZLZGggkkMTY0w+b6EAJE3AmMo0RJ+2tCJZrNTSgTWyAqLQGEwM/2kCysFZznY3B4vHE6FAos3CW2Y2krbAbaWAMqZR60iI4PfHLB15LWcjTkLt08i4u2pAAYQAQTrPcglfYpjRbT8TzjI4KSpGkQAAFT+CAMEeNDHhMdA324D52DeRNICsaAfkeZQ3Ckf4nlcWA1Gpdh0LAAB3d5lAgWBoG4MR0zRb430SYBgFAohanqR4hPA7FaiYZjrHBY0RMScdzhhJTCCk5S1wnXAYU0sSxJcWAHEgo9QnCSIBwTJMkDACRKH7dMoGXFBjJ4kAESRLFUXRTFYEIGI4igxI53oRgnMzRJUHCkBXHcdAd1M1sP2jElOxwbsBHXK0sDjSguF4QgWCpRzZwFcxnELc9f1LbhcrrTkkugtKDJ/Et8ijJA6rjRqkAAdWHYpLVqNYxKAAAA=&value=N4IgkgIgziBcDaIQF0A0IB2BDAtgUzhACk8AnPHATwAIIB7UjEdLAcwNgCYBWdAMywA3BgEsALngD6AYzoAbBoQDEfAdwAM65iHYYAJmUI4scgugXSsYkXSaxgAX3QAHPGJgJQYyq8J66rNrY+IQA6iYSpCAOyA5AAA=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by pmk65** [comment]
@mrehder @schmunk42 @marc7000 @germanbisurgi 
I have pinpointed the problem to the "getDisplayText" function in "src/editor.js":

````javascript
      else if(JSON.stringify(el).length < 50) name = JSON.stringify(el);
      else name = "type";
````

Doing a JSON.stringify on the el object with a pattern of 35 characters gives exactly the length 50. This also explains why the 2nd option gets the value "type".

I'm not sure why there is this 50 character limit (Don't want to change it if it breaks other functionality), but maybe someone can shed some light on this?

**Comment by pmk65** [comment]
If there are no objections, I'll go ahead and fix this by increasing the 50 value to 150.

**Comment by schmunk42** [comment]
I think the value could be even higher, like 500. I don't know about issues with large patterns.

CC: @marc7000 @jdorn

**Comment by mrehder** [comment]
I agree is must be large.
A regexp pattern for something like an ipv4/ipv6 address is quite large.

Thanks
Mike

**Comment by pmk65** [comment]
Ok. I have changed the 50 character limit to 500 now.
