### ISSUE TITLE
Please help to support case insensitive for properties search

### ISSUE THREAD

**Issue by alen-yao** [json-editor/json-editor#1400]
As attached, please help to support case insensitive for properties search.
when input OSS, can search out all related values, but if oss, no values.
![pic2](https://github.com/json-editor/json-editor/assets/17844393/b105d254-5f7d-4316-a7b5-3f53426713d7)
![2023-10-12_10h18_28](https://github.com/json-editor/json-editor/assets/17844393/467cf9d4-b5db-45f0-a63b-b90605f8c483)

**Comment by schmunk42** [comment]
Note: We'd need a new editor option like `caseSensitivePropertySearch = true` to maintain BC.

**Comment by alen-yao** [comment]
Thanks a lot.
will it be included in next release version?

**Comment by germanbisurgi** [comment]
Yes :)

**Comment by alen-yao** [comment]
Thanks for the support, I will close this issue.
