### ISSUE TITLE
Improvement: Allow iMask/Cleave/etc to reference definitions.

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1409]
For forms that have many many fields of the same type, with ellaborate imask or cleave set-up, it would be great if the styles could be defined in definitions and referenced.

What today is:

```
"total": {
	"title": "Total Amount",
	"type": "string",
	"default": "0",
	"options": {
		"imask": {
			"mask":"num €",
			"blocks":{
				"num":{
					"mask": "Number",
					"scale": 2,
					"signed": false,
					"thousandsSeparator": ".",
					"padFractionalZeros": true,
					"normalizeZeros": false,
					"radix": ",",
					"mapToRadix": [
						"."
					]
				}
			}
		}
	}
},
```

could become:

```
"total": {
	"title": "Total amount",
	"type": "string",
	"default": "0",
	"options": {"imask": {"$ref": "schema.json#/definitions/currmask"}}
}

```
And in definitions the mask could be defined and reused dozens of times without wasting space or being prone to a typo.

```
"definitions":{
	"currmask":{
		"mask":"num€",
		"blocks":{
			"num":{
				"mask": "Number",
				"scale": 2,
				"signed": false,
				"thousandsSeparator": ".",
				"padFractionalZeros": true,
				"normalizeZeros": false,
				"radix": ",",
				"mapToRadix": [
					"."
				]
			}
		}
	}
}
```

**Comment by schmunk42** [comment]
@germanbisurgi Is this related to [unevaluated properties](https://json-schema.org/understanding-json-schema/reference/object#unevaluated-properties)? a.k.a merging of definitions.

**Comment by eduo** [comment]
I tried this but couldn't make it work. I assumed it wouldn't work and didn't keep at it. I'll try again. Thanks.

**Comment by germanbisurgi** [comment]
feelfree to reopen

**Comment by eduo** [comment]
> feelfree to reopen

Wanted to add a final update, even though I couldn't fix my personal issue:

It is indeed possible to define cleave and imask "templates" to be called as references in this way. They work. 

My particular issue wasn't solved because there's some problem with how Cleave is applied that breaks a lot when the decimal mark is not ".", which I'm still looking after.
