### ISSUE TITLE
Schema for "additionalProperties" does not override "no_additional_properties: true"

### ISSUE THREAD

**Issue by StephanSchuster** [json-editor/json-editor#1410]
### General information

- json-editor version: 2.10.1

### Expected behavior

Globally, I want to disable additional properties. Hence I set `no_additional_properties: true` which works fine. But for one dedicated property somewhere in my schema, I need to enable additional properties. If I do this via the code below, it also works (globally still disabled, enabled for "extras" property).

```javascript
"extras": {
  "type": "object",
  "additionalProperties": true
}
```

But I not only need to enable additional properties for my "extras" property, I also need to restrict them - in my case to certain types. Hence I need to do this instead of the above (true):

```javascript
"extras": {
  "type": "object",
  "additionalProperties": {
    "type": ["number", "boolean", "string", "array"],
    "items": {
      "type": ["number", "boolean", "string"]
    }
  }
}
```

But now additional properties are disabled again for my "extras" property. This is due to the [implementation](https://github.com/json-editor/json-editor/blob/68b4bbf140fc28f96d6fcf05cab9b549935766fc/src/editors/object.js#L1070C1-L1070C1) of `canHaveAdditionalProperties()` which explicitly requires a boolean to enable additional properties for a specific property.

I would expect that if someone (like me) globally disabled additional properties via `no_additional_properties: true` but then at some point specifies a schema for additional properties (object, not boolean), it is valid to say that this guy wants to have additional properties enabled in that place. So I suggest to extend the `canHaveAdditionalProperties()` to not only check for boolean but also return true if "additionalProperties" is an object/schema.

### Actual behavior

When disabling additional properties via `no_additional_properties: true` and at the same time enabling it for a dedicated property is not possible when additional properties is not a boolean but an object/schema.

### Steps to reproduce the behavior

See above.

**Comment by germanbisurgi** [comment]
fixed in #1415
