### ISSUE TITLE
How to check if remote schema is not loaded properly?

### ISSUE THREAD

**Issue by djdance** [json-editor/json-editor#1417]
I use remote schema like so:

`editor = new JSONEditor(el,{ ajax:true, schema: {"$ref": "https://..... " })`

I need to know if there is no site, no schema on the url, or schema was loaded but appeared invalid. And it will be nice, if I could check empty schema like `{}`. Then I have to implement some fallback. 

- **How could I watch the result of schema loading? or get an error?**
- Does `on('ready',() => {`   reacts on schema loading?
- Where are all callbacks/events of JSONEditor in documentation?

thank you, all supporters!

**Comment by germanbisurgi** [comment]
> How could I watch the result of schema loading? or get an error?

network panel in the browser developer tool

> Does on('ready',() => { reacts on schema loading?

From readme.md: *Note If the AJAX property is true and JSON Editor needs to fetch an external url, the api methods won't be available immediately. Listen for the ready event before calling them.

> Where are all callbacks/events of JSONEditor in documentation?

In the README.md

**Comment by djdance** [comment]
> network panel in the browser developer tool

I mean, how to check it programmatically?
'ready' event fired the same for good and broken URL of schema, I can't see where is difference.

> In the README.md
There are only two events: ready and change. But there is no event for something like "schemaLoaded". Is it exist?

**Comment by germanbisurgi** [comment]
There is not an event that triggers when schemas are loaded, or similar

**Comment by schmunk42** [comment]
@germanbisurgi This sound like a nice enhancement, but it might be tricky to create an "final" event (promise) when all schemas are loaded, or?

**Comment by germanbisurgi** [comment]
I was working on this, and all I need are reasonable names for the events. Currently, I have the following:

```javascript
editor.on('schemaLoaded', function (schema) {})
editor.on('loaded', function () {})
```

**Comment by germanbisurgi** [comment]
The feature is now implemented. [Readme](https://github.com/json-editor/json-editor#schema-loader-events)

**Comment by djdance** [comment]
it works! it works! 👌
