### ISSUE TITLE
Question: Is it possible to bulk edit an array table?

### ISSUE THREAD

**Issue by samuel-bentley** [json-editor/json-editor#1419]
Hi, is it possible to bulk edit when the `type="array"` and `format="table"`? E.g. In the screenshot below, is it possible to set "modality" for all modality values, without having to set each value individually? The use case is sometimes we will have hundreds, maybe thousands of rows to edit.
<img width="1040" alt="Screenshot 2023-11-02 at 16 02 17" src="https://github.com/json-editor/json-editor/assets/136350237/dc353a36-12ce-4b59-8262-a40b5104a917">

**Comment by germanbisurgi** [comment]
The feature hasn't been implemented
