### ISSUE TITLE
Option use_default_values: `false` deletes valid values while `true` sets invalid default values

### ISSUE THREAD

**Issue by moonrail** [json-editor/json-editor#1422]
### General information

- json-editor version: 2.11.0

### Expected behavior
1. `use_default_values: true` should set defaults adhering to given constraints, such as minimum & maximum on integers
2. `use_default_values: false` should not set any default other than defined in the schema and use a given value via `startval` or `setValue()`

### Actual behavior
1. `use_default_values: true` always sets the same default value, e.g. `0` on integers, not respecting minimum & maximum
2. `use_default_values: false` causes valid values of `startval` or `setValue()` to be ignored, if the schema has no explicit default value

#### behaviour with true
See [here for an interactive example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIeYYUiUATgIYQgA04eAVgKYZQD62VAnmAK5RCAcwowAJvRCIMACxYBbKqlBQeEFoTDM2QhhRYBHfjAOSUAbRAHDUmxwDuMKLI7iWAMyr9sQgLoMEBSQLBSwLMho1kYqIGoahDDwUCzCoVIKSTAK/AqoAIwMSgAe2bkFAAwAvgyQQlHxmiggSSlpFBlZOXkohSAlZT351fpGjs6u7l4+9arqTS3JqekMU96+qACsRV3lvUVUpd2VNeDQ4y5unuuzcfOJS+1SazNbO/CDBQdHe8NV/wxELIwA4OKFghRIosUtR2HB4FIXIoFsRSORqBBNnYjCYzBw8DwrtMNigvNhECxVjBEBBuISbLiWOIODgeKgyRTAcDQXUOEl2VRyZSQPAwBwqOJxM54YKOEEQmEYBEBUKGFQmIcVZyQFLEFQ8NgWGCpZwmIgEFrhbr9YaOFhsNwIBTLVS9QajfKNIrlaTBdrre7xRRqISJeYOVbqTajVRg7wOAYwBR3B1faqdVHA7GQ1dDSkXSAWPBo0Gc1gIGy09rs/GsMlguSOFBIAWA7aa4T3HmYw6EyDIhHXSWO7mWCkuFRyH2HJb/kA===)

#### behaviour with false
I am unable to provide a reproducible URL, as the option `use_default_values` is hardcoded to `true` in https://json-editor.github.io/json-editor

The example above for `true` can be reused, but with `use_default_values` set to `false`.
Using the following `startval` data should showcase the issue:
```json
{
  "req": 5,
  "opt": 5
}
```
The editor now shows empty inputs with no values for properties `req` & `opt` even though we've provided valid values.
When using `editor.getValue()` the properties `req` & `opt` are missing.
As can be seen, the properties `req_with_default` & `opt_with_default` are handled correctly - as they have defaults defined in their schema.

So in a simple workflow of "loading data into the editor, then modifiying and saving it" we would loose data.

Parts of this issue are also mentioned in #1343

**Comment by moonrail** [comment]
@schmunk42 Please reopen this issue - there are 2 parts of it, not only the one you've described.
The behaviour of `true` is not really important to me, so if this is how it works, thats fine by me.

As a matter of fact I do not want to use this option at all, as it sets values the users should decide themselves about.

But I am currently not able to disable it, due to the described behaviour with `false`, which does look like a bug and not as intended.

**Comment by moonrail** [comment]
Here is a modified version of your example mit startval data: [click](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY4AnVARwFcBLOgE0ygG0qZs76FXtWACA%2BgHdm8ABZi2qAGYBDRgBsywXgF1K0bMho40NeM1QBnTuH0iB14XzhI0nOMwjxUAc1Q0htk7AALYezMGMwZwAjHp8QcHKAB7hkTEADI4AvnFBxppYNvEiLujAWO6ePn4BxdihEKlR5VCxjiKJKRHNWNGZgTmOtAyS0nIKKuoFUEXFzihlFcAeXr7%2BwLnxcBOqGpwArJsJYd0xRx3JTRnZR3D5o7LySrvTs1sIC27LVWu1c8A7KYHc71E5pFptQIXLrg3r9eJZXiIiBZYBAA%3D%3D&value=ETI%3D&code=EQKwpgJghgLlB0BXAzmA%2BhMAzKiA2MaAblHomMgLw56oDcAOgHbjRzzJwBOMJelAb2YACYQ2BcwAR3EAuYQFYANCLHAA9gAcYcxSqajxkqWgDuASxgALDNlwFdARn2GN2s5ZuYc%2BHcHmOzAC%2BzAD0ocIAKlZgwljqeHjqFkwA5sJ45kwUwlCSwgC2UExs6lwAnrklwpJQEOpMeOXwwgCa6ojCAMbFuRAQ3Sgw6gXd6pi5AEbqRLHFA5NgSabwzOZYwgAUIKgQlmXCWZzFXWDqGyn1KwBSAMoA8gByAKJ7w1wAlMI7kPtc8JhOFx1OVNh9GCxdn9hJRhNlTMJLsl4Hcnq8%2Fpt6l1EAUwEwYPApOQKrclmAuu9NuIAMQ7BoAWl%2B73p8S4BXEHyU30gsCg4OAQA&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0).

**Comment by germanbisurgi** [comment]
Fixed in #1422
