### ISSUE TITLE
Bug Migrating from v2.11 to v2.12

### ISSUE THREAD

**Issue by matihaber** [json-editor/json-editor#1429]
### General information

- json-editor version: 2.12.0
- We are facing a javascirpt error with a json that should be working (the same json works in prev version without any problems).

### Expected behavior

Backward compatibility with version 2.11.0

### Actual behavior

Throws a javascript error: "jsoneditor.min.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'value')"

### Steps to reproduce the behavior

Use the following JSON with the given schema from the direct link

```Json to Update from:
{
  "main-menu": {
    "links": [
      {
        "type": 2
      },
      {
        "type": 1,
        "link": "/p/como_comprar_supercatalogo",
        "text": "Como Comprar"
      }
    ]
  }
}
```

Direct link: 

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIBRRLGxhkbKIIi6U7LjwW8HjqVQCOImM4AmqANogsxlK8EFIwslKCIAC6bCGQVFKwNBogsjDwALQM8CIp5paEYJzc4mYw2lYgALJUOQAEAAqh8BgwEHIKcZaJMMlo/mCBvHgA5nkWlYbNY2wkMmTi1gHSClo6hADCg9J1nlR1AGIInmAKe0RkItiLIADEAMyPTyAAvmzLQVBUAB6LmhOEKbpGbEaSyG4fVbldbWLaBXZUbB1AAqPygpzY50u10ItyI+IJr3e9BCNEQvAQvCUUkG8n6+UqeDAgyoZHgCjm4MIKm4AGsmd8oRVCAB5DBXchSOritknOqIfZ7RAQAQALzIdWUZFaGrIeDIHAxICxEtQUCkIiobxAuHgvOQ9IB1jIUikQg5YIWhHIeHWZWF1gAMul7QoRPAYG4qABJL50B3my1scpqB3/ArWIq2UogNaVWNqBSQWAINPGmCIPU6XgBAQQBVmi1UTEVqtUXhUTzlXgcWjslCJ5vlyu+9tdBJJBNN60IKgioi+TTQyrBu2rJ02Eoe+Y3EahbyxGndSfjDPpyrpL4jBIKWoiOi+ACMMXA0DgSBSyhgnj2/cHL2tW1eTyZdCFXYCzA3IF4BBE0cWsAB6BQ6HSQNahGKBlFQR9rS+X4QIDEBkXKK4jQZQFzWBZDUPQzDsMxKgLlNaw6iJfxEHJDABA4vol0IjZuP2DYAGVhLqAAKSBWgQOQ6naN1dgrKgADJ4CMPYAG4wAASjOGgMFCN8EE2QTEDqESxIVeSyE8MgzIgHYaHaaSADp1wzEAvx/Wo9KY+CQGo+A0JguiUAAJgAthnDcDxO18XMATYIDVjRaI2BsrsS3gOQmniHo+gubAFTePiYSIsBbLM7jzIWKgRmkGA7OlegwDqcCzOEqhrJOUwEo8rMt0PPKT0dM8+ovNS6pvNg7wfFAfDCl9i3fMsvN/RtLQA61ovcLx4vIl8MvKd8cqPCdegdQripYUrKmRCqmuqjZavq0ImqwOhWuEkQ8ALeMETqGgvjakN3MqAa7CG48LtPKxz0IS8pqkW8cjmnx7iWoyP36NafIHadcNS+lQOsYioFIsGKOmQLgowrCUEfBi/JuVjIpAHbYu8ebxpS/DDp/Y6ZOwXLoYKuRrtusCQzqDUAFVspqq8Go1WpGhdWBxQEZHIP64pIdBHdCD3b9OjO/Ky3I0aJqvaaQFm3wABZMay1bv3W/HNutDAXukQReBN4nCOjAARAHnqVt7KesRHr211J0jCe9UAABiZ7FFmTwn8MDsqADl6DwZww59t6JKkk7sF0hjqTaLLCHzuhC/2OQvikbLYAAN1ahypUQGB5UVGhWTqT6phdOoBGlEvGoBsBzQ1TkyDcnXJkomCado+mcO21xdri7nyPeEu/ZN/nMorkXzrFoqrSiLatrYRBlDACgO1daQHRARG3R4d9VlUBghAmRzzHhAZgAEgA=

**Comment by schmunk42** [comment]
We're looking into that. Just one quick note:
``` 
                  "css_classes": {
                    "title": "Clase CSS (opcional para dise&ntilde;o)",
                    "description": "Clases CSS separadas por espacio.",
                    "type": "hidden",
                    "default": "",
                    "minLength": 2
                  }
```
There's no type `hidden` it should be `string`. 
Also a hidden input, with default `""` and minLength: `2` is problematic, unless you have some js-magic to set it.

**Comment by germanbisurgi** [comment]
I'll rephrase the GitHub issue response:

Attributed to @schmunk42, the usage of 'type: hidden' in JSONEditor isn't recognized and shouldn't have been functional in version 2.11.0. However, for string type editors, there exists a valid usage of "format": "hidden".

```json
"css_classes": {
  "title": "CSS Class (optional for design)",
  "description": "CSS classes separated by space.",
  "type": "string",
  "format": "hidden",
  "default": "",
  "minLength": 2
}
```
