### ISSUE TITLE
"required" prevents correct validation of numbers

### ISSUE THREAD

**Issue by Radouch** [json-editor/json-editor#143]
### Expected behavior
`minimum` and `maximum` values for types `number` and `integer` in JSON schema should be respected.

### Actual behavior
If another property is defined as `required`, validation for `minimum` and `maximum` does not work

### Steps to reproduce the behavior

1. Create JSON schema
```javascript
{
  "type": "object",
  "title": "Number validation does not work with required",
  "properties": {
    "name": {
      "type": "string"
    },
    "number": {
      "type": "integer",
      "minimum": 3
    }
  },
  "required": ["name"]
}
```

2. Load it to the editor, e.g. at https://json-editor.github.io/json-editor/

3. You can enter e.g. `0` or `1` at the field `number` and it does not cause validation error.

**Comment by Radouch** [comment]
There is workaround for problems (see also #130) with required:
Instead of
`required: ["name"]`
(see the example above)
you can use":
```
"properties": {
  "name": {
    "type": "string",
    "required": "true
  }
}
```
But I am afraid this workaround may work with this editor only.

**Comment by germanbisurgi** [comment]
Good catch. Fix coming soon. Thanx
