### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by FilippoLippi** [json-editor/json-editor#1431]
### General information
Markdown not working

- json-editor version: 2.12

### Expected behavior
JSON output: Markdown property has the correct value

### Actual behavior
JSON output: Markdown property is empty!

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsigGb4A22ANCBOWIdDlSyMw5XABMsLLHVTM2WTpnFD86FlBwA3VunqzWHEIXwAPHBOgALVAAZONMghyIopXITATUARk4BjfGxnLCQYWE1cbkgscigAT2D8cj9rJgMFEBg/BBZqVBBheFcAd3peLABWEE4wKgArLD8NFnw4sFp8+BFjFmqQRBSsY1RQWCgpfIAFGMQEPviILHzahqa+0QBHdBhRMVQAbRACYhAAXU4oxdiYPTQjoiW7hcf+ihh4AHM+4XJjKHzjOQANZiMDFeAgAC+0M4iEsYJwMR45AYmSKMXwTTgEM4UEsQxeVDAYCgLnI+AgVU4m22uwECQkzDU/zS8k4YhgiAgLQSNJ2WDEOBycX0bP68OKQv471Fhi6OHwYg5sAQrBwlxisFuFF0nHwdVMsoyHMQ+CoUkRypwdVmENZhhNZot2RYLQg2CN7M5TsiPCuWoYcgd3vNJHI5ISir29uNIYtSQjOFEIgk5E9IEdoYV4da5kk0keQYyIR92cT2QgIpjepzCWyRR4bBwUEg6cz8dreakdAVrqTYMD6S9pqzCdzEm7uBaLn7xSNkNh+aaAoAMtQGIdEDA+FJCF5ziB0Egl3QxGuqBuQJjcAKwiI+ikwFk9LC/LeW2nF1ImgAmPrYb9YAALyWThGBaKAICyIFP36GAPgIKB0FEdVFT6P5LBtB8pHwCIsNOSEgA==

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string",
      "format": "markdown"
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Fixed in #1433
