### ISSUE TITLE
Absolute dependencies not used in new array items

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1435]
When defining a dependency inside an object inside an array item, the dependencies will be ignored and the fields will be displayed always.

Triggering the dependency value will apply the dependencies in the array items.

Sample sandbox: https://is.gd/fLfA7P

Steps to reproduce: 
1.-Load the form. Dependencies work upon loading in field below "subform" section.
2.-Change the "tipo" select menu ("Show dates" should hide textarea fields and show date fields instead). Dependencies work.
3.-Add an item to the "Type-1 objects" array
4.-**ERROR**: Will show all fields, including both date and textarea, regardless of what is selected and ignoring dependencies.
5.-Changing the popup menu will apply the dependencies properly in the array items.

**Comment by germanbisurgi** [comment]
fixed in #1547
