### ISSUE TITLE
type must not be "button" for button to work

### ISSUE THREAD

**Issue by totszwai** [json-editor/json-editor#1439]
### General information

- json-editor version: 2.12.0

### Expected behavior

JSON Editor should not need to check for the `type` in order to know whether it is a button or not. The general logic should be that, it checks for `options.button` if it exist, then it shall render a button. The value of `type` attribute should be left as-is according to JSON schema specification.

In addition, the `title` should be taken from the `options.button.title` instead of the `title` directly from the field.

I can have a field named `helloworld`, with title "Hello World" but I want to have a button with different text than "Hello World".

### Actual behavior

- The `type` required to be changed to "button" for the button to work.
- The title of the button is taken from the field's `title`

### Steps to reproduce the behavior

As we could see here, "button" is not a valid JSON schema value, also we would lose the actual indented definition of the field too. In my example, that field is supposed to be of type "string", I was going to use JavaScript to generate the string accordingly when pressing the button.

![image](https://github.com/json-editor/json-editor/assets/4440365/094a0c7b-daa3-40aa-81a8-152104174636)

**Comment by totszwai** [comment]
> Could you add an example schema, please.

Straight from json-editor's own README.md
https://github.com/json-editor/json-editor#button-editor

```
{
  "type": "button", // <==== THIS
  "title": "Search",
  "options": {
    "button": {
      "icon": "search",
      "action": "myAction",
      "validated": true
    }
  }
}
```

Example:

```
{
      "example": {
        "type": "object",
        "properties": {
          "something": {
            "type": "string", // <== I want something to be a string, but I want to click a button to get the value
          }
      },
```

Currently, I'd have to change the `type` to `button` which cause the JSON schema itself to lose the original information of the field. I wanted to use the JSON schema to document my API structure.

**Comment by schmunk42** [comment]
Here's a quick and dirty modification of `/tests/pages/button-callbacks.html`:
https://gist.github.com/schmunk42/83c422a05e5f79c158121fb9ed847540

I think the README is wrong, since there's no `type: button` just a format.
CC: @germanbisurgi

**Comment by totszwai** [comment]
> Here's a quick and dirty modification of `/tests/pages/button-callbacks.html`: https://gist.github.com/schmunk42/83c422a05e5f79c158121fb9ed847540
> 
> I think the README is wrong, since there's no `type: button` just a format. CC: @germanbisurgi

`format` should not be button either.
https://cswr.github.io/JsonSchema/spec/basic_types/

The point is that, if we have a JSON schema, and the developer decided to stopped using json-editor, the schema file itself should work. Right now, json-editor is requiring user to modify the schema file to make it work with the editor.

`options` field is there, is a universal blob, json-editor should most probably just use that instead.
