### ISSUE TITLE
How to validate enum values on user selection ?

### ISSUE THREAD

**Issue by gmmoliveros** [json-editor/json-editor#1443]
### General information
very outdated version
- json-editor version: v0.7.28

### Expected behavior
validate schema if user selected any of the choices on the `enum` array
### Actual behavior
currently it always returns valid even there is no selection yet, gonna be honest that i don't know where should i look for possible solution

### this is how it looks like
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2GG8EcWpUEEF4JwB3ei4sAFYQNjAqACssbzVxfGiwWhz4IQNxCpBERKwDVFBYKEkcukdu0PJEOHgcjwA6SwAmbpiILByq2vrusV7KaFmcgBUzLAACcahu8I2omHpBkAJiZ8FyAxuUHok6m7SdEIDFAgXQhFQAG0QNcPGt6FBVmxrgBmEAAXWR0Q2OUclHgAHMQABfLE4n7xchNbroeAwACOzAAkkDdCksMTOWxEGYwAUcJFONMcjB8pF8PVjsjzm8flQwGAoHj8BAACwk4lAA

```javascript
{
    "title": "test",
    "version": "1.02",
    "type": "object",
    "description": "The test",
    "properties": {
        "name": {
            "format": "select",
            "items": {
                "enum": [
                    "test1",
                    "test2",
                    "test3"
                ],
                "type": "string"
            },
            "type": "array",
            "uniqueItems": true
        }
    }
}
```

Currently lost on this one, if anyone can point me on the right path here on how will i be able to validate it using the schema and not relying on JS. Thanks a lot!

**Comment by schmunk42** [comment]
Use `"minItems": 1` for your array (`name`).

[Example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2GG8EcWpUEEF4JwB3ei4sAFYQNjAqACssbzVxfGiwWhz4IQNxCpBERKwDVFBYKEkcukdu0PJEOHgcjwA6SwAmbpiILByq2vrusV7KaFmcgBUzLAACcahu8I2omHpBkAJiZ8FyAxuUHok6m7SdEIDFAgXQhFQAG0QNcPGt6FBVmxrgBmEAAXWR0Q2OUclHgAHMQABffQweAASSBDC8MOxmx+8XITW66HgMAAjswqf1dCksMTBWxEGYwAUcJFONMcuS6Mz6sdkec3j8qGAwFA8fgIAAWEnEoA==)
