### ISSUE TITLE
Dependency (dependant fields) are not created after JSON update at change of the controlling field

### ISSUE THREAD

**Issue by cygro** [json-editor/json-editor#1452]
### General information
I have a schema that incorporates dependencies, such as the example "Dependencies" on the interactive playground: https://pmk65.github.io/jedemov2/dist/demo.html
When the editor is initially loaded, the controlling field ("Category") can be changed, the dependent field ("Subcategory") is updated as it should.
After loading an existing configuration (just clicking the "Update Form" button is enough), the (new) dependent field is not created and the json is not updated anymore when changing the controlling field.

- json-editor version: Current 
It can be reproduced on the demo using the shema from the example mentioned above: 
https://json-editor.github.io/json-editor/

### Expected behavior
The dependent field is created in the UI and the node in the JSON is generated

### Actual behavior
The dependent field is not created in the UI and the node in the JSON is not generated.
If changing the controlling field back to the value at the time of loading the JSON, the field is shown in the UI and the JSON node added. 

### Steps to reproduce the behavior
1. Open the Interactive Playground: https://pmk65.github.io/jedemov2/dist/demo.html
1.1 Click the button "Load Example" in the action bar on the top.
1.2 Choose "General Examples" > "Dependencies"
1.3 Switch to the tab "Schema"
1.4 Copy the Schema

2. Open the editor example: https://json-editor.github.io/json-editor/
2.1 Paste the copied schema from 1.4 to the textarea "Schema"
2.2 Click "Update Schema"

3. Change the field "Category"
=> The field "Subcategory" and the JSON is changed

4. Click "Update Form" to the right of the editor

5. Change the field "Category" again
=> The field "Subcategory" disappears, the property is removed from the JSON

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "Dependencies",
  "type": "object",
  "format": "grid",
  "properties": {
    "_text1": {
      "title": "Dependencies Example",
      "type": "string",
      "format": "hidden",
      "description": "<p>This example shows the use of the <strong>dependencies</strong> option, where you can have a field depend on the value of another field.</p><p>This works by creating all dependant element and then hide/show the selected one. So this feature works best if fields are placed vertically.</p>",
      "options": {
        "grid_columns": 12
      }
    },
    "category": {
      "title": "Category",
      "type": "string",
      "enum": [
        "Chocolates",
        "Vegetables",
        "Icecreams"
      ]
    },
    "subcategory1": {
      "title": "Subcategory",
      "type": "string",
      "enum": [
        "Dark chocolate",
        "Milk chocolate",
        "White chocolate",
        "Gianduja chocolate"
      ],
      "options": {
        "dependencies": {
          "category": "Chocolates"
        },
        "grid_columns": 12
      }
    },
    "subcategory2": {
      "title": "Subcategory",
      "type": "string",
      "enum": [
        "Broccoli",
        "Cabbage",
        "Carrot",
        "Tomato"
      ],
      "options": {
        "dependencies": {
          "category": "Vegetables"
        },
        "grid_columns": 12
      }
    },
    "subcategory3": {
      "title": "Subcategory",
      "type": "string",
      "enum": [
        "Frozen yogurt",
        "Booza",
        "Ice milk"
      ],
      "options": {
        "dependencies": {
          "category": "Icecreams"
        },
        "grid_columns": 12
      }
    },
    "_text2": {
      "title": "Using Checkbox",
      "type": "string",
      "format": "hidden",
      "description": "<p>You can also use boolean checkbox with dependencies.</p>",
      "options": {
        "grid_columns": 12
      }
    },
    "billing": {
      "title": "Billing address same as shipping address",
      "type": "boolean",
      "format": "checkbox",
      "default": true,
      "options": {
        "grid_columns": 12
      }
    },
    "billingaddress": {
      "title": "Billing address",
      "type": "string",
      "options": {
        "dependencies": {
          "billing": false
        },
        "grid_columns": 12
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Fixed in #1452
