### ISSUE TITLE
Buttons in array editor are not setup correctly if there exists another enum-typed property for which the default value does not equal the first value

### ISSUE THREAD

**Issue by ThomasKiesel** [json-editor/json-editor#1461]
### General information

- json-editor version: 1.13.1

### Expected behavior

When the settings are 
```
disable_array_delete_last_row: true,
disable_array_delete_all_rows: true
```
the buttons "delete last item" and "delete all" are not visible as the settings demand it.

### Actual behavior

When the scheme contains an enum typed property whose default value does not equal to the first enum value, the buttons are shown.

### Steps to reproduce the behavior

Direct link to example: 

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsigGb4A22ANCBOWIdDlSyMw5XABMsLLHVTM2WTpnFD86FlBwA3VunqzWHEIXwAPHBOgALVAAZONMghyIopXITATUARk4BjfGxnLCQYWE1cbkgscigAT2D8cj9rJgMFEBg/BBZqVBBheFcAd3peLABWEE4wKgArLD8NFnw4sFp8+BFjFmqQRBSsY1RQeIgsfNqGpr6o8diYPTQQEPRCAAUeefiRkDGJlH6KGHgAcz6JZjUofOxs+DEANR0JzlXCVABtAphyF2eWLo+ncEE8XiAALoAX04SXIrU20VicV2+3ycNafTCQwYozi40m9UaN04cxisCWoFIxwcBzxBMOLkoZxAULZ7M4iEsYGKOBiPD++ROdHhTTg8D6UEsQwOICoYDAUCZ+AgABY+qIAI7oX5YMQCBKXVTqfTyThiGCICAtBJanWifU5FFpM39bm8yAaE6mwxdHD4MQW2AIVg4MkLJZyQz4OqmH0ZC2IfBUKR8oM4OqIBDx82W5Op7IsFoQbA5kCJ/ORLbkxYMKMJvMpkjkeEJANiMsVpv+lutHCiEQScidxupjGGyTSA71t4EbvjnDZCDOmcgBf3ChgNg4KCQEdJ+e9idSOj+ov9nkMCi6XMHsdH8yT08tFwX4qoa9YNlAA

```javascript
{
  "type": "object",
  "properties": {
    "enumProperty": {
      "type": "string",
      "default": "secondValue",
      "enum": [
        "firstValue",
        "secondValue"
      ]
    },
    "arrayProperty": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "attribute": {
            "type": "string"
          }
        }
      }
    }
  }
}
```
Settings:
```
disable_array_delete_last_row: true,
disable_array_delete_all_rows: true
```

**Comment by germanbisurgi** [comment]
Fixed in #1462
