### ISSUE TITLE
const validates objects and arrays incorrectly

### ISSUE THREAD

**Issue by germanbisurgi** [json-editor/json-editor#1463]
### Expected behavior

`"const": {}` and `"const": []` should not display errors with empty objects and arrays

### Steps to reproduce the behavior

[Example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2GG8EcWpUEEF4JwB3ei4sAFYQNjAqACssbzVxfGiwWhz4IQNxCpBERKwDVFBYKEkcjKQobpiILByq2vru8JmomHpB8Bq6ybQQadmUTYXJnwRHQYBfC7Z48iaN/Zzb+9OJ1ABtAF0r656zMAKOEinHIDBAMHykXw9Tg8CmZn6BxAVDAYCgjjuEAALCArkA)

```javascript
{
  "title": "const",
  "type": "object",
  "properties": {
    "object": {
      "type": "object",
      "const": {}
    },
    "array": {
      "type": "array",
      "const": []
    }
  }
}
```

**Comment by schmunk42** [comment]
@germanbisurgi Can we close this?

**Comment by germanbisurgi** [comment]
Yes
