### ISSUE TITLE
Memory leak in empty method of array editor 

### ISSUE THREAD

**Issue by ThomasKiesel** [json-editor/json-editor#1466]
### General information

- json-editor version: 2.13.1

### Expected behavior

If the `empty`-method of the `array`-editor is called with parameter `hard=true`, the rows which are only present in the `row_cache` should be destroyed as all other rows.

### Actual behavior

The rows in the `row_cache` remain in memory.

### Steps to reproduce the behavior

Direct link to example: 
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2GG8EcWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFpG+CEDcR7ERKwDVFAYiCxGsH7BqB7wtaiYemWQeNLo49X1lBPyM57gxYYV6LWNrfLdzn3YI7QQRA6AAUvpEYhcXld/hQigBzEAAX0RSLYUDMi0hVDAYCgjlKEAALAj4UA=

Add three object-typed items: `Item 1`, `Item 2`, `Item 3`
If `Item 2` is deleted, the row remains in `this.row_cache`. If now the `empty`-method is called, the `JsonEditor` instance as well as the `ObjectEditor` instance of the cached row remain in memory.

**Comment by germanbisurgi** [comment]
Fixed in #1467
