### ISSUE TITLE
Removing labels from buttons and only using icons

### ISSUE THREAD

**Issue by dom-devel** [json-editor/json-editor#148]
I'm wondering if it's possible to display only the icons as and not the text as specified in the [original icon issue](https://github.com/jdorn/json-editor/issues/65), for creating and removing object and array entries.

Currently the JSON below will generate the following buttons:

![image](https://user-images.githubusercontent.com/8628008/43108436-b6aa3fe4-8ed9-11e8-81f6-0ee57e6d4e5f.png)

I can either get:
- The name of the category
- Blank for add, but not delete by setting category to " "
- "item" used for the category if I don't specify anything.

There is no specific wrapper on the text so I can't hide just that and setting the `font-size: 0` will also kill the font awesome icon.

Am I missing a basic configuration option here, any ideas how to best go about doing this?

```
{
      disable_properties: true,
      disable_collapse: true,
      disable_edit_json: true,
      theme: "bootstrap3",
      iconlib: "fontawesome4",
      schema: {
        type: "array",
        title: "categories",
        items: {
          type: "object",
          title: "category level 1",
          properties: {
            "Category 1": {
              type: "string",
              enum: ["Fill me"]
            },
            category2: {
              type: "array",
              // title: "category 2",
              items: {
                type: "object",
                title: " ",
                properties: {
                  "Category 2": {
                    type: "string",
                    enum: ["Fill me"]
                  },
                  "Category 3": {
                    type: "array",
                    title: "Category 3",
                    items: {
                      "Category 2": {
                        type: "string",
                        enum: ["Fill me"]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  );
});
```

**Comment by schmunk42** [comment]
We have the same requirement and we're working on that.

**Comment by dom-devel** [comment]
Thanks for the update, I will continue with some questionable workarounds or manage to convince my designer that we might have to compromise. Thanks for the excellent library!

**Comment by germanbisurgi** [comment]
Hi dom. I am working on it. My specification list so far:

- an option to display / hide button labels like -> `display_button_labels`
- hide "+ item" label. Displays only "+" icon
- hide "x item". display only "x"
- place buttons (add remove last, remove all) at the top to avoid moving it  when adding items

Open questions:
- remove last and remove all use the same icon. Should i leave this labels on?
- what else need to be hidden?

**Comment by dom-devel** [comment]
`remove all` could possibly work as a bin icon? I think I would possibly switch that to a bin and leave the rest as crosses?

Personal preference, but I actually don't like `remove last`. To my mind it just duplicated and clutters considering there is already an inline delete button, so I just hid it and rely on the other buttons.

![image](https://user-images.githubusercontent.com/8628008/43316174-468a12f2-9190-11e8-806d-405e3b0c3ce4.png)

I would also be tempted to:
- Let a user hide remove last and or inline removal.

**Comment by pmk65** [comment]
A dirty hack would be to override the setButtonText function in themes and skip adding the textNode. Like this:

````javascript
JSONEditor.AbstractTheme.prototype.setButtonText = function(button, text, icon, title) {
  button.innerHTML = '';
  if(icon) {
    button.appendChild(icon);
    button.innerHTML += ' ';
  }
  //button.appendChild(document.createTextNode(text));
  if(title) button.setAttribute('title',title);
}
````

**Comment by pmk65** [comment]
What's the status on this? Has it already been fixed/implemented but never documented like #10, or is it still unresolved?

**Comment by schmunk42** [comment]
It's unresolved. We're currently in holidays, so it might take another few days until we're able to start working on that, but I have put high priority on this.

**Comment by pmk65** [comment]
I have been looking a bit on this and got a couple of questions too:

There are 3 "states" of buttons: "text + icon", "text" and "icon".
1) Should a global config option set that for ALL buttons, or are there some that always should use the "text + icon" state.? And if so, which buttons?
2) Or should there be local config options for each object, so you can change only some of them when/if needed?

It's very easy to implement the 1st solution. the 2nd is a bit more complex.

**Comment by schmunk42** [comment]
I'd be fine with a global option and/or a solution where tweaks could be done via CSS.

**Comment by pmk65** [comment]
A pure CSS solution could be made by just wrapping the button text in a span tag, similar to the icon is styled using an I tag.

Currntly a button looks like this (Bootstrap Theme):

````html
<button type="button" title="Object Properties" class="btn btn-default json-editor-btn-edit">
  <i class="fa fa-pencil"></i>
   Properties
</button>
````

And with a span tag.

````html
<button type="button" title="Object Properties" class="btn btn-default json-editor-btn-edit">
  <i class="fa fa-pencil"></i>
  <span> Properties</span>
</button>
````

Hide the icon on "Object Properties" button only:
````css
.json-editor-btn-edit i {
  display: none;
}
````

Hide the text on "Object Properties" button only:
````css
.json-editor-btn-edit span {
  display: none;
}
````

Hide the text on ALL buttons (Bootstrap Theme):
````css
.btn span {
  display: none;
}
````

**Comment by schmunk42** [comment]
I'd like the solution with a `<span>`, any downsides?

**Comment by pmk65** [comment]
Only one I can think of is that the HTML is always created for both icon and label, so the output will be a little bit larger due to the span tags.

The 3rd example will only work on Bootstrap themes, so we might want to intruduce 1 or more extra "json-editor-btn-*" classnames (Must be set regardless of theme). That way we can group buttons of same "type".

**Comment by pmk65** [comment]
Made a patch with span tags and it seems to be working perfectly. 😃 
But the `json-editor-btn-` class is based on the iconlib key, so it might not be specific enough to style individual buttons. 
Especially the Array/Table "Delete" and "Delete All" buttons, which have the same icon/class name. 
There's probably more, so if you got any ideas/suggestions let me know. I'll then add some custom class names to those buttons.

**Comment by pmk65** [comment]
Here's a list of the various Buttons generated. And it looks like there are only 3 files that have to be modified (There are buttons in upload.js and datetime.js too, but they don't need a class)

The buttons in table,js,object.js and array.js 3 are very similar, so I think they should just share the same class names if the functionality is "identical"

| **array.js**  |                          |                   |
|-----------|--------------------------|-------------------|
| Line      | Icon                     | Desc              |
| 506       | delete                   |                   |
| 552       | copy                     |                   |
| 578       | moveup                   |                   |
| 605       | movedown                 |                   |
| 637       | collapse |                   | collapse/expand 
| 699       | delete                   | Delete Last       |
| 728       | delete                   | Delete All        |
| **object.js** |                          |                   |
| Line      | Icon                     | Desc              |
| 520       | save                     |                   |
| 526       | cancel                   |                   |
| 546       | add                      |                   |
| 660       | collapse                 | collapse/expand   |
| 691       | edit                     | Edit JSON         |
| 709       | edit                     | Object Properties |
| **table.js**  |                          |                   |
| Line      | Icon                     | Desc              |
| 326       | delete                   | Delete Row        |
| 354       | moveup                   |                   |
| 375       | movedown                 |                   |

**Comment by pmk65** [comment]
> 
> 
> Maybe we could change
> 
> ```
> 728 | delete | Delete All
> 709 | edit | Object Properties
> ```
> 
> to make it visible, that those are different buttons.
> 
> Obj Properties could be `cog`, delete all ... `trash`?

That shouldn't be hard. we just need to find the appropriate icons in the various iconlibs and insert it in iconlibs/*.js

Here's a list of the classes Im going to add. Let me know if you have any objections or changes.

| array.js  |          |                   |                                |
|-----------|----------|-------------------|--------------------------------|
| 506       | delete   | Delete            | json-editor-btntype-delete     |
| 552       | copy     | Copy              | json-editor-btntype-copy       |
| 578       | moveup   | Move Up           | json-editor-btntype-move       |
| 605       | movedown | Move Down         | json-editor-btntype-move       |
| 637       | collapse | Collapse/Expand   | json-editor-btntype-collapse   |
| 699       | delete   | Delete Last       | json-editor-btntype-deletelast |
| 728       | delete   | Delete All        | json-editor-btntype-deleteall  |
| object.js |          |                   |                                |
| 520       | save     | Save              | json-editor-btntype-save       |
| 526       | cancel   | Cancel            | json-editor-btntype-cancel     |
| 546       | add      | Add Row           | json-editor-btntype-add        |
| 660       | collapse | Collapse/Expand   | json-editor-btntype-collapse   |
| 691       | edit     | Edit JSON         | json-editor-btntype-editjson   |
| 709       | edit     | Object Properties | json-editor-btntype-properties |
| tablse.js |          |                   |                                |
| 326       | delete   | Delete Row        | json-editor-btntype-delete     |
| 354       | moveup   | Move Up           | json-editor-btntype-move       |
| 375       | movedown | Move Down         | json-editor-btntype-move       |
| 400       | collapse | Collapse/Expand   | json-editor-btntype-collapse   |
| 434       | add      | Add Row           | json-editor-btntype-add        |
| 446       | delete   | Delete Last       | json-editor-btntype-deletelast |
| 462       | delete   | Delete All        | json-editor-btntype-deleteall  |

**Comment by schmunk42** [comment]
LGTM!
