### ISSUE TITLE
"rating" format value isn't submitted

### ISSUE THREAD

**Issue by thibgl** [json-editor/json-editor#1486]
### General information

- json-editor version: 2.14

### Expected behavior

The rating value should print to the console when submitted.

### Actual behavior

The rating value is "undefined".

### Steps to reproduce the behavior

Set a rating ("safety" starts rating) value in https://json-editor.github.io/json-editor/basic.html and submit.

Schema from https://github.com/json-editor/json-editor/blob/master/docs/basic.html

```
safety: {
  type: "integer",
  format: "rating",
  maximum: "5",
  exclusiveMaximum: false,
  readonly: false
}
```

**Comment by germanbisurgi** [comment]
Fixed in #1543 (will be available from version 2.14.2)
