### ISSUE TITLE
How to install / use?

### ISSUE THREAD

**Issue by kaesesahnetorte** [json-editor/json-editor#1504]
From the readme, I cannot tell what my options are on using this.

So my understanding is this is a browser-based-editor that I can run locally?

For usage I need to create an html file and run it via browser?

Is my assumption correct that I can do ONE OF THESE OPTIONS?
- install JS library via npm
- use the CDN link in the html document
- install by build from source (this github repo), add some locations to $PATH variable or idk

Sorry for this noob question

**Comment by kaesesahnetorte** [comment]
I somewhat got it to work for me locally.

My suggestion: Add to readme that
- this is a javascript library
- the functionality is inserting a json editor into your html document (or css framework instead of html?)
- be more clear about ways to install the JS library. Is it one step by step guide or multiple options?

**Comment by schmunk42** [comment]
PRs welcome :)
