### ISSUE TITLE
New array items ignore dependencies

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#1505]
### General information

- json-editor version: All versions

### Expected behavior 

When adding a new row, dependencies should always be taken into account to display fields

### Actual behavior

Dependencies are ignored until explicitly triggered again.

### Steps to reproduce the behavior

Create an enum field.

Create an array. Have one property depend on a value on the enum and another property on the other.

Render the form and add a new item to the array. Both properties will show, rather than the one whose condition is med.

If the condition is re-triggered (by changing the enum in this case) the dependencies will go into effect and work for the existing array items.

Direct link to example: https://is.gd/6hZdn8

```javascript
{
    "title":"Dependency-triggering selector",
    "type":"object",
  "properties": {
    "selector": {
      "type":"string",
      "enum":["X","0","1"],
      "options": {
        "enum_titles":["Select one…","Zero","One"]
      }
    },
    "rows": {
      "title":"Entries go here",
      "type":"array",
      "minItems2":1,
      "items": {
          "title":"Single Entry",
          "type":"object",
          "properties": {
            "field1": {
              "title":"Shows on X or one",
              "type":"string",
              "options": {
                "dependencies": {
                  "root.selector":["X","1"]
                }
              }
            },
            "field2": {
              "title":"Shows on zero",
              "type":"string",
              "options": {
                "dependencies": {
                  "root.selector":["0"]
                }
              }
            }
          }
      }
    }
  }
}
```
Possibly important note: If rows are created initially using minItems > 0, those rows will have their dependencies properly applied. This bug is only for new rows whose items have dependencies outside the array.

Edit: I just noticed I'd logged a similar issue in #1435 . Let me know if I should delete either one.

**Comment by germanbisurgi** [comment]
fixed in #1547
