### ISSUE TITLE
How to Add a Visibility Button to the Password Field

### ISSUE THREAD

**Issue by alfian444** [json-editor/json-editor#1507]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: [link example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2GG8EcWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFpG+CEDcR7ERKwDVFBYKElGgAVIxEq2GIgsRrB+wage4QBHdBhhEVQAbRACYh78AHNDthFnHv58dSEwVwtXEQh6H3gYnIPVBvgq8B6BygyAAumxwgcojB6MsnkRDmgQPsCSBHJR4G8emJ5pRoHAESgQAAxG6OAAE+EhbIAMn4oGznp8QIQitzAm8oEkACxfJQqM6MgBSkUW0TZABEhAiAL5sd4ElbRA6NIp0D7Q2V/eWoABMnX0RRghHQhE8AA59EYnS7UABOX26pr/QF0HAgsGE4mNMlFSlsQTkAwKkDhi1E4LrRl/AGUOhs1NUuWqRoAYn4f06lksIEDEKhuKjjJjFJ6gR9KEeMyF/EWWiFYElkRAKMD32kkaNJObcaa01IjTH/bpCAYoH4IygEBqAGtoWhtQe2LDSPSG5Ojidyj1VpmQNywHDT+jOJjYDjCd5gtEz8amxRY4WVrFoyADKnJskypTwJ+8xgDWaROOOhq/qS/4tpayjASAADCACC8Epl+jg/BOKHToWNIwMuDIgAAKmYMCIGyjFshCkTOCIHK0FwJ6+OI4hqvwnCEGyg5shwWDqHAmCiZkYBsvw2LiCIyB7IsEAbiSwDAJ+MSHmy2nEXQB49JkpCJLiunfoyx7wgAdFZcyISStn0nZRmHAeh7sFIq5EuejLxKU37xnOyZOFQ6x7BmJJbMiPToPAMBXFgACSdCELoKRyECmU/iSxwDFe0VrLFUiIi+kRvn5jbIVOaEzm2rodim85fGAM5UDcdxsMIdJReAg7QmiIBiEByYiB1BGCvl0YNTW3ljZhCr3HVC5TWwM2MgA6loJQ1iO3mDi8jJUGAA5kvgEBSgtQA==)
```javascript
{
  "title": "RTSP",
  "type": "object",
  "required": [
    "port_stream",
    "username_stream",
    "password_stream",
    "list_profile"
  ],
  "properties": {
    "port_stream": {
      "title": "Port Streaming",
      "type": "integer",
      "default": 554
    },
    "username_stream": {
      "title": "Username RTSP",
      "type": "string"
    },
    "password_stream": {
      "title": "Password RTSP",
      "type": "string",
      "format": "password",
      "options": {
        "inputAttributes": {
          "placeholder": "your password here...",
          "class": "myclass form-control"
        },
        "containerAttributes": {
          "data-container": "my-container",
          "class": "my-container-class"
        }
      }
    },
    "list_profile": {
      "type": "array",
      "format": "table",
      "title": "List Profile",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Profile",
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "value": {
            "title": "value",
            "type": "string"
          }
        }
      },
      "default": [
        {
          "name": "",
          "value": ""
        }
      ]
    },
    "default_profile": {
      "title": "Default Profile",
      "type": "string",
      "watch": {
        "profile": "list_profile"
      },
      "enumSource": [
        {
          "source": "profile",
          "value": "{{item.name}}"
        }
      ]
    }
  }
}
```

I created a password field like the following image
![image](https://github.com/json-editor/json-editor/assets/56497185/46901eec-ccfc-41f1-a0a3-e50361fbaee5)

Is there a way to add a button so that the password can be hidden or shown like this picture
![image](https://github.com/json-editor/json-editor/assets/56497185/be81bc65-e227-479d-a469-10cecf460b00)

**Comment by eduo** [comment]
Depending on the browser, you might get the widget to make the password visible automatically.

I just tried [this schema](https://is.gd/XVQNCl) and I got this in ·Edge:

<img width="532" alt="image" src="https://github.com/json-editor/json-editor/assets/154630/05760ab1-4707-4355-b38f-3150e96f72b0">


<img width="532" alt="image" src="https://github.com/json-editor/json-editor/assets/154630/49c6f71c-7a4e-49c8-9bad-cbdfd2e51ab3">

Alternatively, you can set a watcher for password fields where if length > 0 an icon is added to the input, and to that icon add an event listener for click to switch icons and to change the type from password to text and viceversa.

Alternatively, you could scan all your password fields and append a toggable eye when there isn't one already.

You can put this in your change event for the editor:

```
	editor.on('change', function() { 
		document.querySelectorAll("[type=password]").forEach((thisField,eid) => {
			if(!thisField.parentElement.querySelectorAll('i.eyetoggle').length>0){
				thisIcon=document.createElement('i');
				thisIcon.addEventListener('click',function(){ if(thisField.type === "password") {
					thisField.type = "text";
					this.classList.add("fa-eye-slash");
					this.classList.remove("fa-eye");
				}
				else {
					thisField.type = "password";
					this.classList.add("fa-eye");
					this.classList.remove("fa-eye-slash");
				}});thisIcon.classList.add('eyetoggle');thisIcon.classList.add('fa');thisIcon.classList.add('fa-eye');thisField.parentElement.append(thisIcon)
			}
		})
}


```

(of course, you should modify the style to work for you, and perhaps put a timer in the click event so it automatically turns back to password field).

**Comment by alfian444** [comment]
> Depending on the browser, you might get the widget to make the password visible automatically.
> 
> I just tried [this schema](https://is.gd/XVQNCl) and I got this in ·Edge:
> 
> <img alt="image" width="532" src="https://private-user-images.githubusercontent.com/154630/316086313-05760ab1-4707-4355-b38f-3150e96f72b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDExMDUsIm5iZiI6MTcxMTM0MDgwNSwicGF0aCI6Ii8xNTQ2MzAvMzE2MDg2MzEzLTA1NzYwYWIxLTQ3MDctNDM1NS1iMzhmLTMxNTBlOTZmNzJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNDI2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmUxZjhjY2NlMzkzZGY2NzM1OWYwZmUyZjgzNjI5Y2QzYTU4NGUyZjM3NDMyM2ZkNTA2NmNhOTM1OGE4ZDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sGFtOiaQd1qYkKAUHTJPFOSCanNK2OLA7sriEbPDAMk"> <img alt="image" width="532" src="https://private-user-images.githubusercontent.com/154630/316086514-49c6f71c-7a4e-49c8-9bad-cbdfd2e51ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDExMDUsIm5iZiI6MTcxMTM0MDgwNSwicGF0aCI6Ii8xNTQ2MzAvMzE2MDg2NTE0LTQ5YzZmNzFjLTdhNGUtNDljOC05YmFkLWNiZGZkMmU1MWFiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQwNDI2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTJlODUzNWUyNDE0M2JlNmNkMDViYjliMmJlODA5NDNhNDNhYzViYTA2OTIwODNiMTUxYmUxYzRlOGZiYTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U_XFF6ajPb8arxHPejMOAoc5xPadULi3WYGh93_f2LE">
> Alternatively, you can set a watcher for password fields where if length > 0 an icon is added to the input, and to that icon add an event listener for click to switch icons and to change the type from password to text and viceversa.
> 
> Alternatively, you could scan all your password fields and append a toggable eye when there isn't one already.
> 
> You can put this in your change event for the editor:
> 
> ```
> editor.on('change', function() { 
> document.querySelectorAll("[type=password]").forEach((thisField,eid) => {
> 	if(!thisField.parentElement.querySelectorAll('i.eyetoggle').length>0) {
> 		thisIcon=document.createElement('i');
> 		thisIcon.addEventListener('click',function(){ 
> 			if(thisField.type === "password") {
> 				thisField.type = "text";
> 				this.classList.add("fa-eye-slash");
> 				this.classList.remove("fa-eye");
> 			} else {
> 				thisField.type = "password";
> 				this.classList.add("fa-eye");
> 				this.classList.remove("fa-eye-slash");
> 			}});
> 			thisField.style.display='inline-block';
> 			thisField.style.width='90%'
> 			thisIcon.style.zIndex=2
> 			thisIcon.classList.add('eyetoggle');
> 			thisIcon.classList.add('fa');
> 			thisIcon.classList.add('fa-eye');
> 			thisField.parentElement.append(thisIcon)
> 		}
> 	}
> )
> }
> ```
> 
> (of course, you should modify the style to work for you, and perhaps put a timer in the click event so it automatically turns back to password field).
> 
> Edit: Some formatting, since I wrote this in a rush in the developer tools console :D Edit2: Modified input field to be inline block and 90% width to accomodate the icon after it, but you can do your own styling.

Thank you for the answer, this really helped me :D
