### ISSUE TITLE
How to Add Info With Icons

### ISSUE THREAD

**Issue by alfian444** [json-editor/json-editor#1513]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: [link example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAFwJZIDYFNEC4HACsBnAeziIGMALTAWwENZMAPe2gBy0QBpIZ5ESAJ7tswPIhIAjApgpIefOPnYQSoiKkxFcscFGUDgLNpzF59%2FeNcEjz%2BIkggpoAc0UHrN4ABNtFZ3ZUMl1EABUqFCJYKNh6OBMOLFhKGgYAOg8rL0Q%2FADN6AFd0BXF8AAUseiJMJh80WFpMTOAlLwBfNthOg3bgIA%3D%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgKrMGTnEsphATsAchloejxYS%2B2ESRxxrAukgG9wQ4h2zu6vQGQ3YIxQY3cAEE0JNgABtZjsAAOsDKSPIJBIGDYDAAuhthKsYuQbnY7MxoFgSAAxLCmBibWBYBhJMoAPnAn1%2BP2YNjsAEIKVTafThOjqD0YuCuj1%2BoNhqNxmxoSgrlhhLB2LBWHg8ODLglhOD8BS2QAGL7cizMa1CkgASRkAjK%2FxlvRkvGYsClsDdaoNhRwR2ttspDqdOGEfAYMUMPQAMlSvVVWtciDIANaPZ6vXkfb5Wm1Fvl2kUoBjCREo8plCpTdGY7GUBgbTmFkNF0t08uV5HwOvAL0ADxtwEDwaLHbtwhkKAxJETqijilhCHIiy18xIc5I0A244gHanYZnO4XSeE1BoBlgq%2FXmtg%2B%2FbRYAvuBTM420HD5PO2GyxWVb9j8wANliOJTAePJHsw06zvOi69NGd4bo%2BwAHN%2B0G%2FnBZ6IZevo3ihD5bjue7oVBMEvi%2BGETsewrdhWqjsOCGRUkic7sGUly4EQVTzDo6CZpcFHYf%2BDHCExLHYAwFJcQAnGaACklzPqGVKOgIEmIixABe9qMLAQ5lAATKpsFhhpkbwZieHIZcD46nqDw0T%2BdHhpp1nnkudlrgGZl2pZp4IRePn3lqfmYTBXaiuKgI%2Bm6UZIiijDkhZEYJM%2BL6FtR3LUcAQA%3D%3D&style=ETI%3D&theme=bootstrap3&iconlib=fontawesome4&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```
I tried to add a description to the json schema, and the description appeared just below the field like the example image below
![image](https://github.com/json-editor/json-editor/assets/56497185/03e670f3-8436-4f82-b8b0-6034cdcb5f1f)

How do I do it if I want to add a description that appears when the info icon is hovered like the image below
![image](https://github.com/json-editor/json-editor/assets/56497185/a0ef55ee-8111-4a71-b42f-a734c11ac1b0)

**Comment by simontaurus** [comment]
This can be achieved with `infoText` (see [ReadMe](https://github.com/json-editor/json-editor?tab=readme-ov-file#infotext) )
```json
      "options": {
        "infoText": "Displayed in popup tooltip"
      }
```
e.g.  [playground](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAFwJZIDYFNEC4HACsBnAeziIGMALTAWwENZMAPe2gBy0QBpIZ5ESAJ7tswPIhIAjApgpIefOPnYQSoiKkxFcscFGUDgLNpzF59%2FeNcEjz%2BIkggpoAc0UHrN4ABNtFZ3ZUMl1EABUqFCJYKNh6OBMOLFhKGgYAOg8rL0Q%2FADN6AFd0BXF8AAUseiJMJh80WFpMTOBeTy98dWDoHTLLQw7EFzySMJZSiWAAESjOeiFMHxi4dnVC9lgkEhISlHZEJQ7YAF9D61P2i5hj4CA%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgKrMGTnEsphATsAchloejxYS%2B2ESRxxrAukgG9wQ4h2zu6vQGQ3YIxQY3cAEE0JNgABtZjsAAOsDKSPIJBIGDYDAAuhthKsYuQbnY7MxoFgSAAxLCmBibWBYBhJMoAPnAn1%2BP2YNjsAEIKVTafThOjqD0YuCuj1%2BoNhqNxmxoSgrlhhLB2LBWHg8ODLglhOD8BS2QAGL7cizMa1CkgASRkAjK%2FxlvRkvGYsClsDdaoNhRwR2ttspDqdOGEfAYMUMPQAMlSvVVWtciDIANaPZ6vXkfb5Wm1Fvl2kUoBjCREo8plCpTdGY7GUBgbTmFkNF0t08uV5HwOvAL0ADxtwEDwaLHbtwhkKAxJETqijilhCHIiy18xIc5I0A244gHanYZnO4XSeE1BoBlgq%2FXmtg%2B%2FbRYAvuBTM420HD5PO2GyxWVb9j8wANliOJTAePJHsw06zvOi69NGd4bo%2BwAHN%2B0G%2FnBZ6IZevo3ihD5bjue7oVBMEvi%2BGETsewrdhWqjsOCGRUkic7sGUly4EQVTzDo6CZpcFHYf%2BDHCExLHYAwFJcQAnGaACklzPqGVKOgIEmIixABe9qMLAQ5lAATKpsFhhpkbwZieHIZcD46nqDw0T%2BdHhpp1nnkudlrgGZl2pZp4IRePn3lqfmYTBXaiuKgI%2Bm6UZIiijDkhZEYJM%2BL6FtR3LUcAQA%3D%3D&style=ETI%3D&theme=bootstrap3&iconlib=fontawesome4&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)
```json
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me.",
      "options": {
        "infoText": "Displayed in popup tooltip"
      }
    }
  }
}
```

**Comment by eduo** [comment]
Keep in mind that infoText kind of works but complains in the console when using bootstrap 5 ( #1108 ), doesn't work in arrays formatted as tables ( #1509 )

**Comment by alfian444** [comment]
> [ReadMe](https://github.com/json-editor/json-editor?tab=readme-ov-file#infotext)

thanks for the answer, I missed it while reading the ReadMe 😄

**Comment by alfian444** [comment]
> Keep in mind that infoText kind of works but complains in the console when using bootstrap 5 ( #1108 ), doesn't work in arrays formatted as tables ( #1509 )

Thank you for the info, this really helps me
