### ISSUE TITLE
Cannot use more than one class in "class" option for links

### ISSUE THREAD

**Issue by jameslao** [json-editor/json-editor#1514]
### General information

- json-editor version: 2.14.1

### Expected behavior

You can add multiple classes to the link, as described in [https://github.com/json-editor/json-editor?tab=readme-ov-file#hyper-schema-links](https://github.com/json-editor/json-editor?tab=readme-ov-file#hyper-schema-links)

### Actual behavior

If you add more than one classes, it faces error 

`jsoneditor.min.js:8 Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('btn btn-primary') contains HTML space characters, which are not valid in token`

**Comment by schmunk42** [comment]
Example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2GG8EcWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFpG+CEDcR7ERKwDVFBYKElGgCFxMABzAAIABTBHPYBJER6YiCxGorodyJ76+ABrBgBtUGFZlBBawmIxWQbDMwn4jQA9BBjlBEBDgMBsOJ+ABfFEQ/6A2EQnreEaIAqYwJQAC0zxeewi8BJRRJrhEWj2HBgBnI0RJdEMUBAKIAuii2FAzIsbr8qGAwLCKPgIAAWHkooA

**Comment by germanbisurgi** [comment]
fixed in #1529
