### ISSUE TITLE
How to link enum sources located in different root files?

### ISSUE THREAD

**Issue by Forlk4** [json-editor/json-editor#1516]
### General information
- json-editor version:

### Expected behavior
when the ai label option is filled then the source enum in the detect object also displays the same source enum

### Steps to reproduce the behavior

Direct link to example: [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY5kAnHNW%2BAS1QGdMpxoZs8BDNumBZuvXnCRpOcfEVIUq47HQaomrDiK5Ll2fswD6AG355UxzmL0SEzeMeFY4AQQCSUADJmLinjewpJ31aWn5EPwDqYAAzHFoAW34ybTghR1IAJkiouABXCGYARzzUN3hUBK0seFpSyn8bOHtK6p1GgMkUYLTa5ggAcxyo7FQIPITOAG1dEZV1NhwIYbm4PGZiRGJHFZG4Yn5aOFmAgF0T5QBfBr3gABNUGP484xSsGY6m4EZF5eAb1bAdabbbCAG3A5HYAXcTnT4wS4XRGNa6zOAPCqkQxyEhvdp6ST2HapYAAEVQmPgUAA8oRcbtAt0ZMA2H1Bgy4HFEslmelcdl%2Fhc4AB3ZLEAAWVhh%2BmYpnMlhJBhMPgVSPBtjGEwAyjg8rRiMEptYCSzdfqesADHLfNDPpc4eJkQjIJdgEA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgKrcHBG2JLKDNgEckkUZhJhOTQdchkAazIKgG9Do%2FApnUkzFYOCm4AAXOBvjhfr8pgxKOQMAAtASwUEQhCSHDjLACezFFrbWBJKEwmHkFBDZh2ADkACFAcDwPDETSEj8YQBfDngbnQ3k%2FH4E9zCAS03gMdg07aY7HMXE4PKQnnC9IYFgyaDipBIXrkLAAfRQulM0sQWJxYpJ4DA4AAsrA6D1ruAAA5DSTPaDyVzMinkdT6o0mlA8mH6KjgFzlZLOM7CPCwZjNCY07K64RB40mFBswr8sngCMeDqUag9A1ZkMxlwJpMANQpgzy%2BcLR2LiBkMdV50TybO2t1eZtEAdjHIrpYr3kS1KWOYkle4CQOgcsCX6eYVjDv1tY7wAZ0WBQlWP%2BqjOE6fsoWAohuzph37cj3U6BojKEGH3AEVXY16rywOwJB2KW5bMJW94hgcBZkh2r40Aa8rMJS36%2Fmu4zCB%2BX6gZIZbdBBVY5jBT4jva3R4J65DQG62TupQ8rMkm%2F4GiuGFbrBMIIDIoo3nguAUgaJCao65DCK6dFUlgpAXMwLFsf%2BwgITWl6IdhpCtm23HCMJcB0OJkkMdJ9xaHJ4ysX%2BmHKRUCHvk2GmkdpbBYPxOCCbpokGUg9HyjJpnyZZvTefKAjfqSbYwrZyGoRCUVuKhpGcpphbaR5%2BkSd5Ul%2Bcx5kKZhwUKmFpGRapSHxaQsWldFpCJfmpF7o69HPJQki3swAaume0KzpQjk8dQCDUCQ0CNp%2BsAtjynIwVN%2BTAEAA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=1&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)

code for JSON
```javascript
{
  "type": "object",
  "properties": {
    "base": {
      "type": "object",
      "properties": {
        "ai_label": {
          "title": "AI Label",
          "type": "array",
          "format": "select2",
          "uniqueItems": true,
          "items": {
            "type": "string",
            "enum": [
              "person",
              "bicycle",
              "car"
            ]
          },
          "default": [
            "person",
            "bicycle",
            "car"
          ]
        }
      }
    },
    "detect_object": {
      "title": "Detect Object",
      "type": "string",
      "format": "select2",
      "watch": {
        "ailabel": "ai_label"
      },
      "enumSource": [{
        "source": "ailabel"
      }]
    }
  }
}
```

code for JS
```javascript
jseditor.on('ready', function() {
    jseditor.watch('root.ai_label', function() { // Memantau perubahan di dalam ai_label
        var ed = jseditor.getEditor('root.ai_label');
        var current_ai_label = ed.getValue();
        var fc = jseditor.getEditor('root'); // Mendapatkan editor untuk objek root

        // Mengambil nilai enum dari ai_label
        var enum_values = Object.keys(current_ai_label);
        var enum_titles = Object.values(current_ai_label);

        // Mengubah properti detect_object
        fc.original_schema.properties.detect_object.enum = enum_values;
        fc.schema.properties.detect_object.enum = enum_values;
        fc.original_schema.properties.detect_object.options = {
            enum_titles: enum_titles
        };
        fc.schema.properties.detect_object.options = {
            enum_titles: enum_titles
        };

        // Memperbarui tampilan editor
        fc.refreshValue();
    });
});
```

when I try the above method on the detect object, it does not display the selected data from the ai label.

![image](https://github.com/json-editor/json-editor/assets/100834919/b1b70397-d5e4-4600-b484-7761890ac40f)

**Comment by germanbisurgi** [comment]
By giving the full path to the editor:

```json
"watch": {
  "ailabel": "root.base.ai_label"
},
"enumSource": [{
  "source": "ailabel"
}]
```

**Comment by Forlk4** [comment]
> By giving the full path to the editor:
> 
> ```json
> "watch": {
>   "ailabel": "root.base.ai_label"
> },
> "enumSource": [{
>   "source": "ailabel"
> }]
> ```

thankyou
