### ISSUE TITLE
Can I Do Dependencies Only On the Default Value And Enum?

### ISSUE THREAD

**Issue by alfian444** [json-editor/json-editor#1524]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: [link example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AETQA5oQAmxAxomgM5wA0kMc8AnkVjgPYBGAVmuXj1GOAGacATgFsAhkODY4AcwmISw6DgITORCUhodwmpgjYYFUYzBs4kqC4rPtgDEzebmOcavFUQlDVtTYgBXKQ4AbRFguwkZCGoCSXk3WNM9ak4IOBibAF08gF80j2AZRAB9FBluNBQjPNN7dG9gAEEASSgAGVr6oODPFycZCXiWQds4cWk5NpU1KbLQiEQAR1C0Tvg0KVpLPy3S6eBkPYPsa3Thxxxff0DgJqgSl7hdJGzLqxfTck4KBqBGoaHUhwkxz%2BOEQEHEABU0AAPeROHj8QRQcg1aiIUSIchyRDZKAEGQkGRQKScMgoKAsBJKKAkRBQPwVHLPdwwN7cnBkUQyUIoVFQaJ8jJoCRZTknIbAbgEljYixy06EiTLU7U%2BCScjK1quaFwCoSAg1CCq40K0IHNVldmwrUOyHkADWztM3E48yNEriMlE%2BPIUBQiCUAAtUtb8RI0FAIywSPEINH%2FT5dQQoLilLLrWSJG7YUypGhdpq%2FekcHUIOQI57q4gJOD7f9fa3%2BZwnh24BHJKCGz4I2hCIPgACAO5j%2BqECMJNNVuB1MZjgBeaG48THSibgdEVvTCpk7rJ7rH4U39RqY7npG4Mm71oMY%2BooWQhIHlZuwFEqmodQPRdgGoIs7WtagIE4CdvTGFtwOSfRqCge8gTHItdjHe9QRQul7wXb8sI3GQgSgJQUE4AA3QDvxAuQNx9ZsX1CCRRBgxiv1iZhiDWJD4ndMtMM4eAHDHCdYXjMiZGoMDD3IUICDHWYPQ4%2BU3TWfcX2SbJBInBoVNOe8IASGQxxkAhzWozjgISEgxLrMdJEZSz5U3ThyABMMxw1HR8Ksvt4GZLsxwIRBV1XEz9LKEhslCXz5UJN1nPVOcmy8zhQnsyKMiE3YSFJC04oMsExxZNYAjZWpDR7BBOEQdBCodCix2BTMx2pW0krKOMdU60xEpYNi4Nkq9ST7S02oJHQJxkKiHKovND11KTyxfWFlOquNf3DKU5EkQTOHW61sTcw7DwoqTevuShpP7MdcpIFhkLQFcspwFKJGZVQpTuzghIjTdbXrLlYkKdxeVOMhdkESp0QEUVrlOFo7jgfAoYCgB5Pg4edW42jGCYceAT5iUSRpD1hBFkVFOAw18ZkxlZWHMQZcqZDdBJmVZSHseB4Jwflc59jJoDWBGGFUzQJRvte5hkENJxMYxBrTGm%2BBMquaFTAqGo6j00Yqh1gZedifmrLCKQAGV0okcg7kiBGaOt228bq%2Fo9OhIpQZN%2B04AFIURSwSIAAYvZsU2cHhITiOF%2BUkbaSP4GjyLccsOBYV2KWKx94A%2FeFUUAEYg%2BKSARCKSAimAIA%3D%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=grid&template=default&show_errors=always&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

```javascript
{
  "title": "Dependencies",
  "type": "object",
  "format": "grid",
  "properties": {
    "type": {
      "title": "type",
      "type": "string",
      "enum": [
        "transport",
        "person"
      ]
    },
    "ai_label": {
      "title": "AI Label",
      "type": "array",
      "format": "grid",
      "uniqueItems": true,
      "items": {
        "type": "string"
      },
      "options": {
        "collapsed": true,
        "infoText": "object clasification pada model yang di train"
      },
      "default": [
        "person",
        "bicycle",
        "car"
      ]
    },
    "detect_object": {
      "title": "Detect Object",
      "type": "array",
      "options": {
        "infoText": "list dari object yang akan di detect"
      },
      "items": {
        "type": "integer",
        "title": "Object",
        "watch": {
          "ailabel": "ai_label"
        },
        "enumSource": [{
          "source": "ailabel"
        }]
      },
      "default":[0]
    },
    "Total": {
      "title": "Total",
      "type": "integer",
      "default": 10
    }

  }
}
```
in the "type" properties when the selected value is "transport", then the "ai_label" properties have a default value of [ "bicycle","car"] and the "Total" properties have a default value of 5. Is there a way for cases like this? and I don't want to add properties with other names

**Comment by germanbisurgi** [comment]
Hello, I've noticed an issue where items are typed as integers but they're expecting strings in their enumSource. This mismatch will cause problems.

To address your question, the Json editor doesn't handle arithmetic operations. To adjust the total value and likely the ai_label value, you'll need to include additional JavaScript.

Feel free to reopen the issue
