### ISSUE TITLE
[bug]select2 setValue report a error and not select it

### ISSUE THREAD

**Issue by RelicOfTesla** [json-editor/json-editor#1525]
### General information

- json-editor version: 2.14.1

### Expected behavior
select it

### Actual behavior
```
this.input.appendChild(...).trigger is not a function
    at Select2Editor.addNewOption (jsoneditor.js:9902:82)
    at Select2Editor.updateValue (jsoneditor.js:9877:28)
    at Select2Editor.setValue (jsoneditor.js:9835:30)
```

### Steps to reproduce the behavior

```javascript
{
	"type": "object",
	"properties": {
		"example": {
			"type": "string",
			"format": "select2",
			"enum": ["aa", "bb","cc"],
			"options": {
				"select2": {
					"tags": true
				}
			
			}
		}
	}
}
```
```javascript
jseditor.getEditor('root.example').setValue('dddddd')
```

**Comment by schmunk42** [comment]
Here's a select2 example:
- Demo: https://json-editor.github.io/json-editor/select2.html
- Source: https://github.com/json-editor/json-editor/blob/master/docs/select2.html

If you use `tags`-style you need `type: array`, I think ... [simple example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2GG8EcWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFpG+CEDcR7ERKwDVFBYKElGgAVIxEq2GIgsRrB+wage8IOomHplkCcAcwYV6IPG+NLonsFyAzOUEGwknKACYeuh4DAAI7MACSdEIuhScmCiyedxeh3+jko8HuPUC6EIqAA2iAqGBxCIesEtDU5jNxL4IMgALoAXw5bL2ZkWmLJYDAUGx+AgABYQFyARJTlgRAAZagMUmA06gllscEq8qyhVUJUgMq4WXBIQ9RJgGo3NLeY1QU1pGDcSSEdxpaXlGAAL0ObH4IygEBqAGtyHMYPcCFB0MIcBB8FT9KQzH1kD5JPhQimQOygA)

**Comment by RelicOfTesla** [comment]
don't multi choose option result( ["xx",...] ) by "array" type, must dynamic single string result ( "xx" ).  @schmunk42

**Comment by schmunk42** [comment]
It shows the error you mentioned if you use a non-exisiting value, but with an existing value it looks good to me:
![Bildschirmfoto vom 2024-04-04 15-14-54](https://github.com/json-editor/json-editor/assets/649031/4ce4d7fa-feb0-4d3f-81a9-c56db535086a)

**Comment by RelicOfTesla** [comment]
I know there's no problem using existing values... I was reporting an BUG when setvalue a not exist value on select2...

**Comment by schmunk42** [comment]
Funny thing is, in the example you can enter a custom value, click twice ... first click show the error, second click adds the value.

However, a validation error is still triggered because the value is not contained in the enumeration list.

I think you'd need a custom editor which saves the values as comma-separated string.

**Comment by RelicOfTesla** [comment]
not quote $ the .trigger(xx)...

https://github.com/json-editor/json-editor/blob/98f85cd716b7ce27537858fc4b4b5203eee2c680/src/editors/select2.js#L77

https://github.com/json-editor/json-editor/blob/98f85cd716b7ce27537858fc4b4b5203eee2c680/src/editors/array/select2.js#L82

fix to
```js
// this.input.appendChild(new Option(sanitized, sanitized, false, false)).trigger('change') 
 $(this.input.appendChild(new Option(sanitized, sanitized, false, false))).trigger('change') 
```

**Comment by schmunk42** [comment]
@germanbisurgi Please have a look and reopen if it's a bug.
