### ISSUE TITLE
Can Do a "WACTH" To Another Root "JSON Editor".

### ISSUE THREAD

**Issue by alfian444** [json-editor/json-editor#1530]
if I have 2 jsoneditor for example jsoneditor "A" and "B", how do I get jsoneditor "B" to do a "watch" to jsoneditor "A"

**Comment by germanbisurgi** [comment]
I woukd say, using the `change` event.

**Comment by alfian444** [comment]
> I woukd say, using the `change` event.
> 
> ```js
> editorA.on('change',() => {
>   const valueA = editorA.getValue()
>   // Do something on B
> });
> 
> editorB.on('change',() => {
>   const valueA = editorB.getValue()
>   // Do something on A
> });
> ```

can I use the watch function like this?
`
{
  "type": "object",
  "id":"editorB",
  "properties": {
    "primary_color": {
      "primary_color": {
        "type": "string",
        "watch": {
          "colors": "editorA.possible_colors"
        },
        "enumSource": [{
          "source": "colors",
          "value": "{{item.text}}"
        }]
      }
    }
  }
}
`

**Comment by germanbisurgi** [comment]
No thats not possible, but you could try listening  for changes from editorA `possible_colors`. When it changes you can grab the value of  editorA `possible_colors` and set the editorB `possible_colors` values with the grabbed value and use editorB `possible_colors` as enum source.

**Comment by alfian444** [comment]
> Sadly, thats not possible, but you could try listening for changes from editorA `possible_colors`. When it changes you can grab the value of editorA `possible_colors` and set the editorB `possible_colors` values with the grabbed value and use editorB `possible_colors` as enum source.

thanks for the explanation, that means I have to use the onchange event
