### ISSUE TITLE
Auto generate schema for simple cases

### ISSUE THREAD

**Issue by cdtut** [json-editor/json-editor#1531]
An option to auto generate the schema would work for simple cases. If you just have a json object you want to edit using json-editor you shouldn't need to create a schema, just pass the object and a form is generated where you can edit it. Every item will be the original type such as numbers in the json object create number inputs in json-editor.

**Comment by schmunk42** [comment]
You can edit any JSON without a schema with `json-editor`.

There are also tools which can generate schemas from data, see https://json-schema.org/implementations - but that's out-of-scope for this project.

**Comment by cdtut** [comment]
> You can edit any JSON without a schema with json-editor.

How to call `JSONEditor` function that way?

**Comment by schmunk42** [comment]
I don't really understand the question?! You need to initialize an editor anyway.

**Comment by cdtut** [comment]
You said you can edit any JSON without a schema with json-editor. But I tried calling with `startval` and no `schema` and got error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$ref')
    at t.value (jsoneditor.min.js:8:382148)
    at t.<anonymous> (jsoneditor.min.js:8:383712)
    at u (jsoneditor.min.js:8:370346)
    at Generator.<anonymous> (jsoneditor.min.js:8:371702)
    at Generator.next (jsoneditor.min.js:8:370709)
    at Zn (jsoneditor.min.js:8:376356)
    at a (jsoneditor.min.js:8:376560)
    at jsoneditor.min.js:8:376621
    at new Promise (<anonymous>)
    at t.<anonymous> (jsoneditor.min.js:8:376500)
```

**Comment by schmunk42** [comment]
Please provide a complete example here: https://pmk65.github.io/jedemov2/dist/demo.html
