### ISSUE TITLE
 Dependent field does not update when watched field changes

### ISSUE THREAD

**Issue by DCkQ6** [json-editor/json-editor#1538]
### General information

- json-editor version: master

We have identified an issue where a field that depends on another field which watches a third field, does not update when the watched field changes. 

### Expected behavior
`dependent_field` should update whenever `field_that_watch` changes, reflecting the new state of `field_that_watch` which depends on `watched_field`.

### Actual behavior

When `watched_field` is updated and `field_that_watch` consequently changes, `dependent_field` remains unchanged, failing to reflect the updated state of `field_that_watch`.

### Steps to reproduce the behavior
+ Define three fields:
  - `watched_field`: a basic variable.
  - `field_that_watch`: set up to watch changes in `watched_field` (i.e., `field_that_watch` updates whenever `watched_field` changes).
  - `dependent_field`: dependent on `field_that_watch` (i.e., should theoretically update whenever `field_that_watch` changes).
+ Change the value of `watched_field`.
+ Observe that `field_that_watch` updates in response to `watched_field`.
+ Notice that `dependent_field` does not update in response to the change in `field_that_watch`.

```javascript
{
    'title': 'Dependency chain support',
    'type': 'object',
    'properties': {
      'watched_field': {
        'type': 'boolean',
        'format': 'checkbox',
        'default': false
      },
      'field_that_watch': {
        'type': 'string',
        'template': '{{content}}',
        'watch': {
          'content': 'root.watched_field',
        }
      },
      'dependent_field': {
        'type': 'boolean',
        'format': 'checkbox',
        'options': {
          'dependencies': {
            'field_that_watch': 'true'
          }
        }
      },
    }
  }
```

**Comment by germanbisurgi** [comment]
fixed in https://github.com/json-editor/json-editor/pull/1547
