### ISSUE TITLE
Fields not autopopulating from previous fields when using exact index.html from json-editor/docs/index.html

### ISSUE THREAD

**Issue by brendalynharper34** [json-editor/json-editor#154]
### Expected behavior
(Working mainly in Django) Ok so strange thing or maybe I'm implementing it wrong but I wanted to see if I can easily incorporate the exact index.html page into my own site. I simply copied the entire json-editor's index.html (json-editor/docs/index.html) and pasted it into an empty index.html file in my site's template directory. I was expecting it to behave similar to the http://jeremydorn.com/json-editor/ page, specifically speaking on the the fields whose values are suppose to be generated from previous fields and the object properties displaying by default. 

This is a screenshot of the current working example from the http://jeremydorn.com/json-editor/ site

![workingjson](https://user-images.githubusercontent.com/1851002/43340395-30fbfb5c-91aa-11e8-92c2-a5f606b0237f.png)

### Actual behavior
When I run index.html from my server, the citystate field is not automatically populated despite the city and state field containing values. In fact, the location properties were not displaying and I had to click their checkboxes to get them to display.  

The following two screenshots are from my implementation of the index.html that was copied into my project's template directory with no changes to the code.  

This shows how the location properties were not displaying.
![notworkingjson_first](https://user-images.githubusercontent.com/1851002/43341578-f1eb954a-91ad-11e8-851b-0dccf701bf4b.png)

This shows how the citystate field was not populated despite the previous two fields being populated.
![notworkingjson_second](https://user-images.githubusercontent.com/1851002/43341604-06b10848-91ae-11e8-95a6-ffcb878e98ea.png)

### Steps to reproduce the behavior
I used the DJangoGirls blog site tutorial mostly for my site. 
 
1. Create empty django project. Be sure to edit your project's urls.py to include the path/url to your index.html page. Create a template folder to for the html pages and add a function to your views.py file to render up the html page.
3. Copy and paste the entire index.html (json-editor/docs/index.html) into an empty html file in your template folder. 
4. Start up your project's server and navigate to your server's address
5. Check if the citystate field is populated with the values from the previous fields. 

Please let me know if I even used the index.html code correctly. If not, what is the right way to use this json-editor in my Django site? 

```javascript

```

**Comment by germanbisurgi** [comment]
Add the "object properties required by default" option

**Comment by brendalynharper34** [comment]
Ok that takes care of the properties displaying but the schema is still missing the template attribute for the fields that are to be populated based on previous fields. Please correct me if I'm wrong but once the page opens, the default schema object is passed through the new JSONEditor object but if I have an attribute with template tags( ex: ```{{city}}, {{state}}```), the template will not stringify (``` ",",``` ). 

This is the location property object portion of the schema object code straight from index.html
```
location: {
  type: "object",
  title: "Location",
  properties: {
     city: {
          type: "string",
          default: "San Francisco"
     },
    state: {
          type: "string",
          default: "CA"
     },
     citystate: {
         type: "string",
         description: "This is generated automatically from the previous two fields",
         template: "{{city}}, {{state}}",  <----------- Specified template here 
         watch: {
              city: 'location.city',
              state: 'location.state'
          }
     }
}
```

This is the console.log of $schema.value
```
{
  "title": "Person",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    },
    "age": {
      "type": "integer",
      "default": 25,
      "minimum": 18,
      "maximum": 99
    },
    "favorite_color": {
      "type": "string",
      "format": "color",
      "title": "favorite color",
      "default": "#ffa500"
    },
    "gender": {
      "type": "string",
      "enum": [
        "male",
        "female"
      ]
    },
    "location": {
      "type": "object",
      "title": "Location",
      "properties": {
        "city": {
          "type": "string",
          "default": "San Francisco"
        },
        "state": {
          "type": "string",
          "default": "CA"
        },
        "citystate": {
          "type": "string",
          "description": "This is generated automatically from the previous two fields",
          "template": ", ", <------- Missing template tags!!
          "watch": {
            "city": "location.city",
            "state": "location.state"
          }
        }
      }
    },
    "pets": {
      "type": "array",
      "format": "table",
      "title": "Pets",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "cat",
              "dog",
              "bird",
              "reptile",
              "other"
            ],
            "default": "dog"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "default": [
        {
          "type": "dog",
          "name": "Walter"
        }
      ]
    }
  }
}
```
Now the workaround I've been using is manually updating schema via the schema textarea after the page loads. After I update it, the ``` {{city}}, {{state}}``` template began to work correctly and the fields were being populated by the previous fields. I would much rather have the same functionality as the http://jeremydorn.com/json-editor/ example without having to manually update the schema first. 

Even after reading the readme, I am still unsure as to why the index,html code didnt have the same exact functionality running locally on my server. I even included all of the required CDNs and the template engines but I have had absolutely no luck recreating the http://jeremydorn.com/json-editor/ example. 

Am I missing a script or what because the readme doesn't go into details about how to structure the schema object to use the different templating engines. Like if I want to set the default template engine to mustache, I still get the same results: missing template tags.. 

What am I missing?

**Comment by pmk65** [comment]
The double curly braces are part of [Django Template Language](https://docs.djangoproject.com/en/2.1/ref/templates/language/), so most likely there's a conflict there.
Maybe you can escape the template markers?
