### ISSUE TITLE
Required fields within array of object

### ISSUE THREAD

**Issue by rwattogl** [json-editor/json-editor#155]
### Expected behavior
Required fields should validate within an array 'items' object.

### Actual behavior
Validation does not occur

### Steps to reproduce the behavior
Schema as shown;
```javascript
{
    "type": "array",
    "format": "tabs",
    "title": "Cronjobs",
    "items": {
        "type": "object",
        "title": "Job",
        "format": "grid",
        "headerTemplate": "{{ self.title }}",
        "additionalProperties" : false,
        "required": [
            "title",
            "job",
            "minute",
            "hour",
            "day",
            "month",
            "year"
        ],
        "properties": {
            "title": {
                "title": "Title",
                "type": "string"
            },
            "job": {
                "title": "Job",
                "type": "string"
            },
            "minute": {
                "title": "Minute",
                "type": "string",
                "default": "*"
            },
            "hour": {
                "title": "Hour",
                "type": "string",
                "default": "*"
            },
            "day": {
                "title": "Day",
                "type": "string",
                "default": "*"
            },
            "month": {
                "title": "Month",
                "type": "string",
                "default": "*"
            },
            "year": {
                "title": "Year",
                "type": "string",
                "default": "*"
            },
            "active": {
                "title": "Active",
                "type": "boolean",
                "format": "checkbox",
                "default": true
            }
        }
    }
}
```

All fields for each item should be required, however they can be blank and validation reports no issues. The above schema validates array items correctly at https://www.jsonschemavalidator.net/ so there should be no issues with the schema itself.

**Comment by germanbisurgi** [comment]
In the json-schema world required does not mean that some value must be set. It means that the value must be present (valid also if its empty).

What you need is "minLength", probably.

https://json-schema.org/understanding-json-schema/reference/object.html#required-properties

**Comment by pmk65** [comment]
The keyword "required" is a bit misleading IMHO. As it's not the "required" you (and most others) want, which is setting the "required" attribute on the fields.
Currently, there's no way to set the "required" field attribute directly from the schema, so you will have to do it from JavaScript.

Example:
```javascript
var` editor = new JSONEditor(element, schema);

editor.getEditor('root.title').input.setAttribute("required", true);
editor.getEditor('root.job').input.setAttribute("required", true);
editor.getEditor('root.minute').input.setAttribute("required", true);
editor.getEditor('root.hour').input.setAttribute("required", true);
editor.getEditor('root.day').input.setAttribute("required", true);
editor.getEditor('root.month').input.setAttribute("required", true);
editor.getEditor('root.year').input.setAttribute("required", true);
editor.getEditor('root.active').input.setAttribute("required", true);
```

**Comment by schmunk42** [comment]
I am going to close this, please let us know if there's still an issue.

**Comment by pmk65** [comment]
Is there a reason why it's currently not possible to set the "required" attribute on input fields from within the schema?

**Comment by schmunk42** [comment]
@pmk65 What do you mean exactly, can you provide an example?

**Comment by pmk65** [comment]
@schmunk42 

All HTML input elements (input, textarea & select) supports various attributes, such as the "readonly" and "placeholder" attribute. (See #171) 
So if "readonly" is set on the input field, it's not possible to submit the form until the field have been filled out.

### Expected behavior
`<input readonly="true" name="root[ronly]" type="text" required placeholder="Placeholder text">`

### Actual behavior
`<input readonly="true" name="root[ronly]" type="text">`

### Steps to reproduce the behavior

```javascript
{
  "title": "Test",
  "id": "test",
  "type": "object",
  "properties": {
    "ronly": {
      "type": "string",
      "title": "Readonly test",
      "readonly": true, // works
      "required": true, // doesn't work
      "options": {
        "required": true, // doesn't work
        "placeholder": "Placeholder text" // doesn't work
      }
    }
  }
}
```

**Comment by schmunk42** [comment]
You can set the `required` property for a property, but this is connected to json-schema's `required`, which means that the key exists in the JSON.

@germanbisurgi Could you have a look at the part for the atttributes `required placeholder="Placeholder text"` - pleas open a new issue, if needed.
