### ISSUE TITLE
nested $ref definition can't be recognized

### ISSUE THREAD

**Issue by zhaozhao** [json-editor/json-editor#156]
### Expected behavior
nested JSON-pointer(`#/definitions/joke/Basic`) should behave as normal one-level pointer(`#/definitions/Basic`) , this should be valid json-schema ref(verifyed by https://www.jsonschemavalidator.net/ , [json-schema nested ref specification](http://json-schema.org/latest/relative-json-pointer.html))
### Actual behavior
![_cf58a2e2-b604-48eb-a14b-bd7b030beb9f](https://user-images.githubusercontent.com/3445700/43762559-d2839a62-9a5a-11e8-8194-86a6a7ee828e.png)

### Steps to reproduce the behavior
[Demo page](http://jeremydorn.com/json-editor/?schema=N4IgJATgpgZiBcIDEB6AJrAlgO0wF0wHtsBnFAK0IGsoUAhAQxMwGMQAaEAvAGygRCNmbThhg58RUglCUaMwU1YK8ATwAO/RIQBG5KCzwcQ6iIU0QCUEiutH4oNZoEk8EHAHMQAX19+gAA==&value=HYVwNmQA&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)
init JSON-editor with the following schema
```javascript
{
  "$ref": "#/definitions/joke/Basic",
  "title": "Basic",
  "definitions": {
    "joke": {
      "Basic": {
        "type": "object",
        "properties": {
          "test": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
for technical reasons, definitions are always located under an object call definitions.

you can do it like this

`{
  "$ref": "#/definitions/joke/definitions/Basic",
  "title": "Basic",
  "definitions": {
    "joke": {
"definitions": {
      "Basic": {
        "type": "object",
        "properties": {
          "test": {
            "type": "string"
          }
        }
      }
    }
  }
  }
}`

**Comment by amitlevy21** [comment]
I might have the same problem, I am not sure how to address this.

Given the following schema:
```json
{
  "definitions": {
    "r1": {
      "type": "array",
      "title": "r1 array",
      "items": {
        "type": "object",
        "title": "r1"
      }
    },
    "r2": {
      "type": "array",
      "title": "r2 array",
      "items": {
        "type": "object",
        "title": "r2"
      }
    },
    "r3": {
      "type": "array",
      "title": "r3 array",
      "items": {
        "type": "object",
        "title": "r3"
      }
    },
    "r_all": {
      "type": "object",
      "title": "r_all object",
      "properties": {
        "r1_1": {
          "$ref": "#/definitions/r1"
        },
        "r2_2": {
          "$ref": "#/definitions/r2"
        },
        "r3_3": {
          "$ref": "#/definitions/r3"
        }
      },
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://yourdomain.com/schemas/myschema.json",
  "type": "object",
  "title": "root",
  "properties": {
    "wrapper": {
      "type": "object",
      "$id": "#/properties/wrapper",
      "title": "wrapper",
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/r_all"
        }
      }
    },
    "w2": {
      "type": "array",
      "$id": "/properties/w2",
      "items": {
        "type": "string",
        "$id": "#/properties/w2/items",
        "title": "w2",
        "default": ""
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "wrapper",
    "w2"
  ]
}
```
Then I get the following form:
![image](https://user-images.githubusercontent.com/28672915/63834308-b538bc00-c97d-11e9-8811-09fd5726f116.png)

My problem is that there is nothing under the wrapper (r_all, r1, r2, r3) (sorry about the weird names, had to change them from the original schema).

I know that draft 6 isn't supported, however, when I use a schema that does not have $ref, it works perfectly.
I'm using Vue if that matters.

@germanbisurgi @pmk65 Can you please have a look?

**Comment by amitlevy21** [comment]
Interesting, replacing patternProperties with properties shows the desired UI, it seems that my problem is not $ref related:
![image](https://user-images.githubusercontent.com/28672915/63836195-c7b4f480-c981-11e9-99b2-66868ab72564.png)
