### ISSUE TITLE
Cannot set (programmatically) value for "enum" string

### ISSUE THREAD

**Issue by DrNeuroSurg** [json-editor/json-editor#1563]
### General information

- json-editor version:

### Expected behavior
editor.setValue("propertyName":"Value" should show the new value

### Actual behavior
Instead the editor-field is empty (but the console shows the right - new - value)

### Steps to reproduce the behavior

Open this example
[Direct link to example: https://json-editor.github.io/json-editor/](https://json-editor.github.io/json-editor/)

Change the value of "**gender**" (right pane) to "**female**" and press "**Update Form**" the Gender dropdown in editor-pane (left) is empty.
The same behavior is on populating a json-string and do editor.setvalue(jasonData);

Example:

https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgFEIBXAWygBVUAZzLBK0bMgBOONJLpDMUcOOrAAbgENJtDRHiDFymMexI0iuMO0QA5hSonsqLt0UBtB4%2BwBBeysdwAEJ%2BXqoAwiGhcAAikV7scQHAAGJwnsYAuukAvg65ENnAQA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgKrIucSymEBOwByXgZ2C%2B2ESRxxrHOkgG9DnHBwMHAAYV4zHgOkkzDUXCUXiGzE8MPICCBHmYcB4SCQMLgfCGVm%2B%2Bio4BoACFQawvhVii1hNl0cI8LBmMSwecLiNmAA1cgoQbgVjgQl3cAXAUXACSMgE4AigluW0%2B3xBTJwAH1oKgtB5ycdKdTesjYF1afSABKwLGURmko1qoZ5Qo4HHgBWklXW07kAAO7u6DD%2B0CwKAYdiJJIEB3tX2SWvcVLRvUx6uE7qo3WYUU0sGEUMoDNgq1gdidAhdAaG2wp0Z1wnjQ2EVQAHswwlgdER8GG5QSLQJhHwGDFDD0ADJYVTdG0XGREGQAawFznZnMGADE2DEcJ17pznO2cABfHdgJcRABK4DCMUg4BiUQAqgBZKx4jxzRh7crgD4R740dhrzoALnAKZCSmKxdztOUHieZgXi%2BecOS5WAV0oP8aDyD8HR%2BCAAHF6QoHhcyGbpfB5JB8JwdNajcP0vj1cAljYB1xRwVRwCfLB6GYMhNQY046WYZoJiuWNhHYziSAuMNvgdX4AAN%2BMEthZKotACOYSRKC%2BddVJsHkUSTZFPDIXA8SIBgHV0uwxJ6Eh3kwtiqA4mzhHgxd82AjY7W%2Bb5mJIVAM3QPArMc8TDQXRC8ik8BdxxXdgCAA&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1

**The same behavior is on radio-buttons ... :-(**

**Comment by snmishra** [comment]
If it helps, adding option `has_placeholder_option: true`  does the right thing. I think there is a bug in the `SelectEditor.setValue` method.

**Comment by germanbisurgi** [comment]
Fixed in #1565
