### ISSUE TITLE
Incorrect default value from schema property

### ISSUE THREAD

**Issue by danyaridiger** [json-editor/json-editor#1566]
### General information

- json-editor version: 2.15.1

### Expected behavior 
The value is substituted into the select from the "property" field

### Actual behavior 
The value is substituted into the select unclear where from

### Steps to reproduce the behavior 
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOAAVIohKmwYnMTmAni8oPdhABHdAwYQDFAAbRAbUCYnIIAAutVOHMojBFmhCogAPLwLBgkBIjkoEBUMBgST4eAgAC+bFJ8HJnO5J0clHa90C6EIqGJ/w5bH4IK0mvAnUiVNF4vYtPm0U5MFZ7JkKTkkulvLABopxsRfWIJ35zvl+AgABYxaKgA=

If there are default values in "property" field, it should substitute select value. But now select uses first value from enum.

**Comment by schmunk42** [comment]
`property` is AFAIK not part of JSON schema, see also the validation message:

```
[
  {
    "instancePath": "",
    "schemaPath": "#/unevaluatedProperties",
    "keyword": "unevaluatedProperties",
    "params": {
      "unevaluatedProperty": "property"
    },
    "message": "must NOT have unevaluated properties"
  }
]
```
