### ISSUE TITLE
Typescript Error - 'default.a is not a constructor'.

### ISSUE THREAD

**Issue by Marshall-George** [json-editor/json-editor#157]
I am trying to get the json-editor alive and running with a simple Aurelia project.  I can get the project to run successfully, but when initializing the json-editor I'm getting:

" _json_editor_json_editor__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor"

Nothing really out of the ordinary with the code from what I can see.

import JSONEditor from "@json-editor/json-editor";

export class App {
   editor:  JSONEditor<any>;
   editorcontainer:  any;    // This is set as the ref= attribute in the corresponding div in app.html

  public attached(): void {
  }

  public initeditor(): void {
    const schema : any = {
      "title": "Example Schema",
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "gender": {
          "enum": ["male", "female"]
        },
        "age": {
          "description": "Age in years",
          "type": "integer",
          "minimum": 0
        },
        "job": {
          "$ref": "job"
        }
      },
      "required": ["firstName", "lastName"]
    };

    const job : any = {
      "title": "Job description",
      "type": "object",
      "properties": {
        "company": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      }
    };

    this.editor = new JSONEditor(this.editorcontainer, {
      schema: schema,
      refs: {"job": job}
    });
}

When I get to the 'new JSONEditor' call is when I am getting the error.

**Comment by marc7000** [comment]
I don't know if its a TypeScript problem but maybe this can help https://github.com/json-editor/json-editor/issues/127#issuecomment-403033432
