### ISSUE TITLE
Format tab is not supported for type object

### ISSUE THREAD

**Issue by shashankMath** [json-editor/json-editor#1570]
### General information

- json-editor version: latest version

### Expected behavior
Tabs format for type object should be supported
### Actual behavior
Tabs format for type object is not supported
### Steps to reproduce the behavior

using this schema 
{
                "$schema": "https://json-schema.org/draft/2019-09/schema",
                "type": "object",
                "additionalProperties": true,
                "additionalItems": true,
                "properties": {
                    "property1": {
                        "type": "string",
                        "default": "atgImplementationConfigurations.json"
                    },
                    "property2": {
                        "type": "object",
			**"format":"tabs",**
                        "additionalProperties": {
                            "type": "object",
                            "properties": {
                               // some properties
                            },
                            "format": "grid-strict"
                        }
                    }
                }
            }

We are working around creating UI for property2 which will have values in type dictionary. UI is printing perfectly fine with dictionary values, but we are facing problem in getting it as tab layout, not getting delete button for each item. What is best work around for our scenario?

**Comment by germanbisurgi** [comment]
At the moment JSONEditor has not support for `"format": "tabs"`. There is a `"format": "categories"`. More [here](https://github.com/json-editor/json-editor?tab=readme-ov-file#objects). Maybe that could help with you scenario.
