### ISSUE TITLE
Ability to not show root element and array labels

### ISSUE THREAD

**Issue by rayzorben** [json-editor/json-editor#1580]
I want to hide all array labels such as "item 0" "item 1" etc. and I can't figure out a clean way to do that even with CSS as the format for nested children seems to change. I would also like to hide the root element completely if possible.

![image](https://github.com/json-editor/json-editor/assets/7737834/30333e9d-8bc3-4cc5-90da-a28b0e4b3ce6)

**Comment by mortenscheel** [comment]
This seems to work for me
```css
span.h3>span:first-of-type {
    display: none;
}
```

**Comment by rayzorben** [comment]
That only gets rid of top level item labels, and doesn't remove the root.

![image](https://github.com/json-editor/json-editor/assets/7737834/52c1a6d9-67f9-4529-b16f-fae1a5f17bd3)

**Comment by Kl0099** [comment]
@rayzorben  , hii

I'd like to contribute to solving this issue or contribute to this repo  but need some guidance on the code structure. Can you help me understand where to start?

thanks

**Comment by germanbisurgi** [comment]
You can use `titleHidden` option for that.

Feel free to reopen this issue if needed.
