### ISSUE TITLE
starrating adds invalid path in name attribute

### ISSUE THREAD

**Issue by mortenscheel** [json-editor/json-editor#1581]
### General information
When submitting a native html form with a starrating in the editor, the path in the radio input's name attribute contains an extra "level" which makes it fail schema validation.

- json-editor version: 2.15.1

### Expected behavior
The radio inputs for the star ratings should have `name="root[rating]"`

### Actual behavior
They actually have `name="root[rating][starrating]"`
### Steps to reproduce the behavior
Open the example link and inspect the `<input type="radio">` elements used by the star rating.

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOACVSEU2gACLCGIgQKFsGJzE5gJ4vKD3WbzGCLNAgUqwdpgkCYrAnRyUSlsNYGfEoECOeLk+H3CFQtkAZSc5C5jJAgXQhFQAG0QAAhLBtIrwSL3fkAaxg4kkAzYAFFDHNKIFvP17gBBESaeAmnUgfWG/EAXTYkAqSCpbUoIhwm20hHdKAATABfUPBjF9YgnKhgMBQen4CAAFhAoaAA=

```javascript
{
  "title": "Rating example",
  "type": "object",
  "properties": {
    "rating": {
      "type": "string",
      "format": "starrating",
      "title": "Starrating",
      "enum": [
        "Beginner",
        "Skilled",
        "Experienced",
        "Advanced",
        "Expert"
      ],
      "options": {
        "grid_columns": 2
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Hi, @mortenscheel,

may i ask how do you perform the schema validation?

I also think were no reason to add the extra `[starrating]` level in the input name but removing it would mean a breaking change for people that are already relying on those names.

On the other side, the JSONEditor could but it was not meant to be used like a regular form (because there are no arrays or objects on those). It is recommended to send the whole json in one payload parameter like "json" and parsing/validating on the backend with a json validator.

**Comment by mortenscheel** [comment]
Hi @germanbisurgi 
I validate the submitted data in the backend (Laravel) using https://github.com/opis/json-schema.

Yeah I found that it was much easier to just submit the entire object as a JSON string. Regular forms submit all values as strings, and it was a major hassle getting the validator to automatically cast those strings into integers, floats and booleans as required. It _is_ possible by adding f.ex. `"$pragma": {"cast": "integer"}` to integer properties. Like I said - a major hassle 😄 

Actually besides all the values being strings, I find that JSONEditor works pretty well when used as a regular form. I'm not sure what you mean by forms not having arrays/objects? I suppose it depends on how the backend parses the request, but I received arrays and objects (associative arrays) just fine in Laravel.

**Comment by germanbisurgi** [comment]
Laravel uses a naming convention for that. I use a similar framework (Yii2) that does the same using a helper that does magic behind the scenes for me.

Can we close this?

**Comment by mortenscheel** [comment]
@germanbisurgi yeah I'll close it, but maybe consider changing it in the next major release?
