### ISSUE TITLE
array element of type boolean with false value is defaulting to null when loading json into the editor via the setValue() method

### ISSUE THREAD

**Issue by theBull** [json-editor/json-editor#159]
### Expected behavior
When I specify a property of `"type": "array"` in my schema, the editor correctly renders HTML controls to add items to that array. If my array allows various types (boolean, number, string, null), a `type` selection dropdown appears adjacent to the input field of each element in my array. If I want to create an array of booleans, I select `boolean` from the rendered type selection dropdown of each added element, and a select dropdown (enum) of possible values I am able to select from are rendered as ` `, `true`, and `false`. If I choose `false` and save the value of the editor JSON (say, to localStorage), upon refreshing the page or reloading the editor, the editor should correctly select the `boolean` type and `false` value that I specified in my JSON. **In particuar**, loading the saved JSON back into the editor after page reload via the `editor.setValue(savedJson)` method should render the controls correctly, such that a `boolean` array element in my JSON with a value of `false`, should render as such in the editor HTML. **Note** that this functionality occurs as expected if the value I specify is `true`.

### Actual behavior
When reloading the JSON via `editor.setValue(...)`, the rendered type dropdown for the element in my array that *should be* `boolean` instead renders as `null`, and instead of displaying an enum drop down for ` `, `true`, and `false`, no value selection box appears (this appears to be the intended functionality when type is `null`, but in this case, the type should be `boolean`). As mentioned, the functionality renders the controls correctly when my boolean value is `true`, however, the seemingly incorrect behavior happens when I specify a boolean value of `false`. It also appears that selecting the empty value from the boolean dropdown list defaults to a value of `true` after reloading the editor.

*What I am selecting in the editor:*
![image](https://user-images.githubusercontent.com/3451643/44056944-a3c645b4-9efe-11e8-808e-b613d12747af.png)

*What the json looks like before refresh:*
`{"values": [true,false]}`
(JSON correctly includes `false` entry in my array)

*What the editor displays after reloading the page/editor:*
![image](https://user-images.githubusercontent.com/3451643/44056983-ba749f90-9efe-11e8-8e12-c7d5aa4b7411.png)

*What the json looks like after the save:*
`{"values": [true, null]}`
(JSON **incorrectly** includes a `null` entry in my array instead of `false`)

### Steps to reproduce the behavior
**NOTE:** My schema makes extensive use of the `$ref` property to separate various nested schemas into their own files, for sanity purposes. The schema I have provided here is a subset of my overall schema; I can't see this being a cause of this issue, but I could be wrong; if I need to provide more of my schema, LMK.
* Create a simple schema of type `object` and specify an entry in the `properties` map a property of type `array`, where `type` is one of a possible list of types.
* In the editor, add an element to this array via the UI controls
* select `boolean` from the rendered type select dropdown
* select `false` from the value input dropdown (should be an enum list of ` `, `true`, or `false`)
* store the json programmatically somehow (such as in localStorage) - if you repro with localStorage, you'll need to stringify the JSON.
* refresh the page
* set the value of the editor programmatically `editor.setValue(json)` after page refresh. If you repro with localStorage, you'll need to parse the stringified JSON before passing it to this method.

```javascript
{  
  "title": "Output",
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "values": {
      "type": "array",
      "items": {
        "type": ["boolean", "string", "null", "number"]
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
Hi theBull. 
 
I  tested your scenario and you are right. The json-editor dont recognizes the type of the values very well when not explicitly specified. Its a feature that we could add or fix (i don know at the moment).

But i think i find a hack for this. Use the "setValue" 2 times. Try it and Tell me if that fixes the problem for you (at least temp)

**Comment by theBull** [comment]
Hey @germanbisurgi that worked! Thanks for your help. It's an odd one. I crawled through some of the (dist) code yesterday and it was tricky to debug, however, it appeared to be related to the `getDefault` method, where a default value for the editor (HTML) input element is determined. First it checks to see if the `default` property is present in the schema. If not, it chooses a default value based on the type of the JSON value given for that editor input element. It appeared as if the type was `undefined` for a value of `false`. I know debugging the dist version if the code is not ideal, but that's unfortunately all the time I had for debugging yesterday :/. Hopefully that helps somewhat. Thanks for the workaround!!

**Comment by pmk65** [comment]
@theBull I think I might have figured out what's wrong. Try changing the **getDefault** in array.js, to this:
````javascript
  getDefault: function() {
    return this.schema.hasOwnProperty('default') ? this.schema.default : [];
  },
````
This should allow **boolean** values, **0** and **empty string** to be accepted values. (Let me know if it works)

**Comment by pmk65** [comment]
You can also do it by overriding the function (that way you don't have to modify dist or create new build)

````javascript
  JSONEditor.defaults.editors.array.prototype.getDefault =  function() {
    return this.schema.hasOwnProperty('default') ? this.schema.default : [];
  }
````

**Comment by pmk65** [comment]
@theBull Can you test this please?

**Comment by stultusstudio** [comment]
I'm running into a similar issue where if I enter this JSON, the "0" in the mojiPromotionBannerMojiIndex array turns into null. I've tried your fix @pmk65 but it doesn't appear to work. I haven't had too much time to look into it but if you change `return null` in the getDefault() function [here](https://github.com/json-editor/json-editor/blob/b14f4d8a83c9c4a8191ef811a44e9d1d957c18fc/src/editor.js), then that directly controls what the field is populated by.

`
{  
   "IsForwardMojiFromContextualMenuEnabled":true,
   "PickerContentUpdate.enabled":true,
   "SendMojiOnLongPressInRoster.enabled":true,
   "ShowMojiTitleInRosterGroupingInt":2,
   "exp_expressionStoreEnabled":true,
   "exp_socialShareButtonEnabled":true,
   "exp_socialShareMenuEnabled":true,
   "exp_thumbnailBlackListCopyright":[  
      "Universal"
   ],
   "expressionStoreEnabled":{  
      "enabled":true
   },
   "mediaBarPersonalExpressionEntryPointEnabled":true,
   "mojiForwardButtonEnabled":true,
   "mojiPromotionBannerMojiIndex":[  
      2,
      0,
      1
   ],
   "mojiQuickSendButtonOnSideEnabled":false,
   "mojiQuickSendFromRosterPreviewEnabled":true,
   "mojiReplayFromPreviewEnabled":true,
   "mojiTitlesInPickerEnabled":true,
   "searchButtonEnabled":true,
   "showMojiPromotionBanner":true,
   "testNest":{  
      "nestedProp":{  
         "test":"hello World"
      }
   }
}
`

**Comment by pmk65** [comment]
I did some debugging on the editor.js getDefault() function. And it runs through it 4 times for each field, except for boolean false where it only runs through the function 3 times.
So the error is not in the getDefault() function but somewhere where it mutates the schema.

**Comment by theBull** [comment]
Hey everyone. I did a little more digging and couldn't pinpoint the issue either. The workaround mentioned above worked to get me unblocked, so for what it's worth, if anyone stumbles across this while the cause is being investigated, give that a shot.
