### ISSUE TITLE
How do I show errors on submit?

### ISSUE THREAD

**Issue by MartinDavi** [json-editor/json-editor#1591]
### General information

- json-editor version: 2.15.1

If I have `show_errors: 'always'` , the form shows the errors. But what I would like is to call some method on the editor in my form's onSubmit method.

I have poured over the documentation and examples and can't find anything. I see an undocumented method called `showValidationErrors` that is certainly named as though it might do what I need, but it is not a function on the editor.

Sorry to ask a stackoverflow type question.

**Comment by germanbisurgi** [comment]
Legit question :)

I made a pull request to simplify this but in the meantime you could use this snippet:



```javascript
const errors = jsoneditor.validate() // All errors

Object.values(jsoneditor.editors).forEach(editor => {
  editor.is_dirty = true // If not dirty the editor will not display errors
  editor.showValidationErrors(errors) // every editor filters errors by path
})
```

**Comment by MartinDavi** [comment]
Aaah, thank you. I would never have gotten there on my own. I am just getting started with this library and will have more questions, if there is a better place for them please let me know!

**Comment by henrychoy** [comment]
Hi @MartinDavi, thanks for the code snippet above.  It works for me, however, it doesn't catch any missing required field errors?  i.e. fields that are listed in the required property array?  Let me know if you want me to create a new issue.
