### ISSUE TITLE
Installation Still Unclear

### ISSUE THREAD

**Issue by Kreakdude** [json-editor/json-editor#1606]
I was unable to install based on the readme section. I'm on Windows. I run the ndm command and it's not found. I don't know what to do with that CDN script xml looking blurb. Following that, there are three links. One is for older releases which is not what I'm looking for. One for a production page which seems like what I want, but it just takes me to a wall of text displayed. I don't know what to do with that. The third link is for dev releases which I do not what but at least clicking it takes me to a page but there's a lot of info on it and I don't know what to do once I'm there.

I don't even know what to expect from an installation. I read that all I need is a browser. Will it run in the browser after installation? That's weird. I'm used to having an executable to run after an installation and it opens in its own window. Then how do I open a schema and json that goes with it?

The documentation is assuming a lot and I'd really appreciate some actual steps I can follow to install and begin using. Thanks.

**Comment by schmunk42** [comment]
I'd recommend to download to ZIP file and start with the `docs` folder, eg. https://github.com/json-editor/json-editor/blob/master/docs/basic.html (that's using the CDN scripts)

Or the `tests` https://github.com/json-editor/json-editor/blob/master/tests/pages/anyof.html which are using locally built script files.

Although it's not really in the scope of this issue tracker, but ... in which kind of project (vanillaJS, React, Vue, ...) are you installing it?

**Comment by Kreakdude** [comment]
I don't really have a project I just have a json file I'd like to allow someone to edit with a GUI. Is having a project necessary for this?

**Comment by schmunk42** [comment]
> What do you mean by "start" with it?

To *begin* looking at the examples in `docs` and pick what you need.

**Comment by Kreakdude** [comment]
> To _begin_ looking at the examples in `docs` and pick what you need.

I need to install it. How is an html file going to help me install it on Windows?

**Comment by schmunk42** [comment]
Sorry, but this is out-of-scope, since it's just a JavaScript library.

You might wanna look into https://www.electronjs.org/ or something similar.

**Comment by Kreakdude** [comment]
Oh it's just a library? Why don't you distribute this as a standalone application. What would it take to make that happen? I'd even take a docker compose so I can easily put it into portainer or something and host it myself so I don't have to worry about putting my json data on someone else's website (especially if I want to use it for work stuff).

**Comment by schmunk42** [comment]
Some Docker stuff is here: https://github.com/json-editor/json-editor/tree/master/tests
