### ISSUE TITLE
Is it possible to have an element that is not automatically included in the json

### ISSUE THREAD

**Issue by Irishde** [json-editor/json-editor#1607]
Hi

Is it possible to have a string or array option that is not automatically added to the validated json?
For example from your demos you have a string city, state and citystate (which is templated from {state, city}), so is there an option to include in the json only the citystate value but not the city or the state?
The other 2 are temp fields to build the citystate

Example here: 
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOAAVIohKmwYnMTmAni8oPdhABHdAwYQDFAAbRABGI93wbSw9xEznuQ3UQmCGzA4iE90p8DE5HurN8FXg9zmUGQAF1qpw5lEYIs0CSiFTZUiFSBHJR2tT6N5KNA4AKUCAAGJ4xwAAnwnJNABkGibSVT9EVLYEOkkACxsMRDFQY/UAKUiIOiJoAIkIBQBfNgUhXg6LI/WqoptDVe1QnABMd0jp3wDMojU2rO5irjysT6rYawMPpAhbZiOCUP19MZdBNde5HqU3pOAGJ+EMbpZLCBsxyuWCQEqTuXk2xAuhCKhif97acQVo12BOpEQCLs9G7ZPpwmKEmNUDtfyTgAVMwwRAmh8mjmRZwiM20LikfZacRB/hOEIE0dxNDgsHUOBMBAzIwBNfhpXEERkEREEIHeaR9WAYA7XDSMTWw6M8PuTJSESScj31I8o0pE5o1HbMaUw2N4xVM8K1OP5SBOJitx1LZJ34DCIH2ABrYtgDw7NeR/SoS1Y1FnnKe4ISbEBLTAPldUFCV5mlBhQG8YJomPUsZ3YucQE9ZQ031ABlc0TQNUp4CMoEwFHNInGYqczNPNVLOsnt9QAYQAQU82tjMcWl5LLCyLy1GB+L1EA72fZ9X1KOgP2UKBv1gXxxH/eCgJAvowOESCvkfKBYPgxDkJUtCMOVbCjJiPCWAI4AYroYi2FIqByNlDqTP1GT+QAOjGwFvOVSbdSmvqqSk7MhQM3zWPiUoTMrLiaycKgoQbSFlVhYV7nQeAYBxLAAEk6EIXQUj2J7NpPB4lIxU61Iu+4YAJdgpB0iIpRlFiYy2+KAvuBclyJWtuI9MBLKoPEBlGLAdRO8Ad25MUrO7WyrNRyLKMh8zYYPG7/lM1jZ0Sq9tP1dLH0ywI3xyz98urX9ioAsrQPA6roLquCEIkJrUO4VqTmwoUptw/CFakKalQGkAhpG0BFc+vWzOqNXKOBqAlflBiuqJ1MfUJSn9REMm2BNgB1LQSlHfcrZ3Ml9SoMBt1VfAIFdBigA===

Also as per the example above is it possible to use templates in arrays? How would you reference the properties to include in the template within the array items?

Thanks!

**Comment by schmunk42** [comment]
> The other 2 are temp fields to build the citystate

How would you display loaded data if you only have `citystate`?

> Also as per the example above is it possible to use templates in arrays? How would you reference the properties to include in the template within the array items?

By array `ìd`, see https://github.com/json-editor/json-editor?tab=readme-ov-file#dependencies (last example)

[updated example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOAAVIohKmwYnMTmAni8oPdhABHdAwYQDFAAbRABGI93wbSw9xEznuQ3UQmCGzA4iE90p8DE5HurN8FXg9zmUGQAF1qpw5lEYIs0CSiFTZUiFSBHJR2tT6N5KNA4AKUCAAGJ4xwAAnwnJNABkGibSVT9EVLYEOkkACxsMRDFQY/UAKUiIOiJoAIkIBQBfNgUhXg6LI/WqoptDVe1QnABMd0jp3wDMojU2rO5irjysT6rYawMPpAhbZiOCUP19MZdBNde5HqU3pOAGJ+EMbpZLCBsxyuWCQEqTuXk2xAuhCKhif97acQVo12BOpEQCLs9G7ZPpwmKEmNUDtfyTgAVMwwRAmh8mjmRZwiM20LikfZacRB/hOEIE0dxNDgsHUOBMBAzIwBNfhpXEERkEREEIHeaR9WAYA7XDSMTWw6M8PuTJSESScj31I8o0pE5o1HbMaUw2N4xVM8K1OP5SBOJitx1LZJ34DCIH2ABrYtgDw7NeR/SoS1Y1FnnKe4ISbEBLTAPldUFCV5mlBhQG8YJomPUsZ3YucQE9ZQ031ABlc0TQNUp4CMoEwFHNInGYqczNPNVLOsnt9QAYQAQU82tjMcWl5LLCyLy1GB+L1EA72fZ9X1KOgP2UKBv1gXxxH/eCgJAvowOESCvkfKBYPgxDkJUtCMOVbCjJiPCWAI4AYroYi2FIqByNlDqTP1GT+QAOjGwFvOVSbdSmvqqSk7MhQM3zWPiUoTMrLiaycKgoQbSFlVhYV7nQeAYBxLAAEk6EIXQUj2J7NpPB4lIxU61Iu+4YAJdgpB0iIpRlFiYy2+KAvuBclyJWtuI9MBLKoPEBlGLAdRO8Ad25MUrO7WyrNRyLKMh8zYYPG7/lM1jZ0Sq9tP1dLH0ywI3xyz98urX9ioAsrQPA6roLquCEIkJrUO4VqTmw3D8OwpUBpAIaRsp/UhSm6c2Eo4GoCmo81q7VMfUJTXScs/WAHUtBKUd9y6qc+jJfUqDAbdVXwCBXQYoA===)

**Comment by Irishde** [comment]
Thanks @schmunk42 

You are right. Didn't think about the implication of loading data in such scenario.  Makes all sense.

Thank you for the corrected example of arrays templates. 👍
