### ISSUE TITLE
External ref does not contain a valid schema

### ISSUE THREAD

**Issue by dima-starosud** [json-editor/json-editor#162]
In short the issue is that lib doesn't expect `true`/`false` as a result of resolving `$ref`.
### Expected behavior
`$ref` is resolved correctly;
### Actual behavior
jsoneditor.js:624 Uncaught External ref does not contain a valid schema
### Steps to reproduce the behavior
```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "$ref": "http_returning_json_value_true"
    }
  }
}
```

**Comment by pmadril** [comment]
Please @dima-starosud, describe what "http_returning_json_value_true" is expected to return. 
It must be a valid schema. The minimum valid schema that I can think is:

{"default":true}

like in:

{
  "title": "json schema example",
"definitions":{
"http_returning_json_value_true":{"default":true}
},
  "type": "object",
  "properties": {
    "test":{"type":"string"},
    "example": {
      "$ref": "#/definitions/http_returning_json_value_true"
    }
  }
}

**Comment by dima-starosud** [comment]
@pmadril That returns just `true`. According to [doc](https://json-schema.org/latest/json-schema-core.html#rfc.section.4.3.1) `true` and `false` are both valid JSON schemas.

**Comment by pmk65** [comment]
@dima-starosud So patching core.js with something like this should return the desired result?
```javascript
    if (typeof this.schema == 'boolean') {
      this.schema = this.schema ? {} : {"not":{}};
    }
```

**Comment by dima-starosud** [comment]
@pmk65 I am not sure. Exception is thrown from [here](https://github.com/json-editor/json-editor/blob/348f4dd63c87c50bc4603de0698c439cf90a2870/src/core.js#L407). So that check should be extended:

`if(!response || (typeof response !== "object" && typeof response !== "boolean")) throw "External ref does not contain a valid schema - "+fetchUrl;`

**Comment by pmk65** [comment]
That would still throw error on boolean `false`. I think this would be better:
````javascript
if (!(typeof response === "boolean" || typeof response === "object") || response === null) throw "External ref does not contain a valid schema - "+fetchUrl;
````
This will allow `object` and `boolean` types to pass. Not sure about `null` as it validates as object. So I added an extra check for that.
Can you try and see if it works for you?

**Comment by dima-starosud** [comment]
This is equivalent to what I wrote since:
`(typeof response !== "object" && typeof response !== "boolean")` is the same as
`!(typeof response === "boolean" || typeof response === "object")`,
and `response === null` is covered by `!response`.

I'll be able to test this other day, will let you know if required.

**Comment by pmk65** [comment]
> 
> 
> This is equivalent to what I wrote since:
> `(typeof response !== "object" && typeof response !== "boolean")` is the same as
> `!(typeof response === "boolean" || typeof response === "object")`,
> and `response === null` is covered by `!response`.
> 

No. Using your `if statement`, the false value will be tagged as invalid.
See this [test](https://jsfiddle.net/hyLq98sx/). (Test1 is your` if statement`, Test2 is mine)

But both of our `if statements` also let the `array` type pass as it's detected as an object. So there's a need to check for that too.

**Comment by dima-starosud** [comment]
@pmk65 Ah, I see, you're right. Sorry.
Solution proposed by you should work.

**Comment by pmk65** [comment]
@dima-starosud No problem. Typecasting in JavaScript is a real pain. And my 1st attempt didn't work either. 😉 
I'm pretty sure that the problem occurs in other places too. Issue #159 looks very similar.
I'll make a PR with my last solution.
