### ISSUE TITLE
how to aggregate fields as a group?

### ISSUE THREAD

**Issue by lincf-tx** [json-editor/json-editor#1627]
i have the json like this :
{
  "name":"123",
  "age":1,
  "nickName":"123",
  "city":"a",
  "province":"b"
}

i want ui show like that

name
---divider---
  age
  nickName
---divider---
  city
  province

It looks too cluttered if all the fields in same level，i need virtual group to organize them。 hope your reply , thanks!

**Comment by schmunk42** [comment]
Should be feasible with `containerAttributes`:
https://github.com/json-editor/json-editor?tab=readme-ov-file#string-editors-input-attributes
