### ISSUE TITLE
Default properties are not visible for a json files without them.

### ISSUE THREAD

**Issue by daniel-dia** [json-editor/json-editor#163]
### Expected behavior
Show default properties when load a data to the json-editor

### Actual behavior
Default properties are not shown when loading a JSON File, only for empty jsons.

### Steps to reproduce the behavior

I'm using JSON Editor to allow my users to edit an JSON. 

Some properties are not required. but I wish to show this properties to the user.

for instance the fallowing schema:

```
    {"type":"object",
        "properties":{
             "name":{"type":"string"},
             "age":{"type":"integer"}
         },
         "required":["name"],
         "defaultProperties": ["name", "age"],
     }
```

when I load the fallowing JSON into Json-editor:

` {"name":"daniel"}`

the JSON-Editor does not shows the "age" property by default. I wish the user to see this property even if will let it 'blank'

**Comment by schmunk42** [comment]
Should be required then, see also https://github.com/json-editor/json-editor/issues/208#issuecomment-436724763
