### ISSUE TITLE
Mandatory boolean always showing false

### ISSUE THREAD

**Issue by vsudigali** [json-editor/json-editor#1630]
HI,

I have a mandatory boolean property. If I did not select any value, it should show the required validation. But its not happening. Also if I did not select any, then false is set. I dont want false to set unless user select false value.Can you please help me to achieve that

**Comment by schmunk42** [comment]
The hacky way (not recommended) You can set `"default": "undefined"` in the schema, see [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5SDUinEyYETapVBBErG8AayowQyrCzfhxagvBYvxM+i4sAFYnmAqAAra5qcT4aJgWgXeBCAziJ6IK4GVCgWBQSQXAAKkUQlTYMTmF2BYPKT1m8xgizQIBEYGC6JAxKwF3uYEk+HgTzEKMo0DgPJQIG5IgA/LylCooKh4CpxABfZVEvrEdlgMBQRylCAAFiewgAjugYMIRLxYmIhjKdiN6TBEBBIbFjabzTgEOJona5Oksp6eEVfWx4Th8CIRMEhVocFSojSGFN7fgQUYQw7EPgqJIclG1CCCcLk3Io1mcxtOZCINgM2Xs7n4wsk8s2PWK+HyKVYhGBigS23HQ2SF2od0sEIxOQ60OO/FuyYJFI2f3WyBAsPOwvNhAfavdmx52OXhROYgcFBIDPy7mj1al40tOJulkWwfM5u74vJI1IY4X5kvrKkAA)

The more correct [way](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5SDUinEyYETapVBBErG8AayowQyrCzfhxagvBYvxM+i4sAFYnmAqAAra5qcT4aJgWgXeBCAziJ6IK4GVCgWBQSQXAAKkUQlTYMTmF2BYPKT1m8xgizQIBEYGC6JAxKwF3uYEk+HgTzEKMo0DgPJQIG5IgA/LylCooDIUlgAL5Kol9YjssBgKCOUoQAAsT2EAEd0DBhCJeLExEMZTsRvSYIgIJDYkaTWacAhxNFbXJ0lkPTwinLUiB4Th8CIRMEhVocFSojSGFM7fgQUYfWwo4h8FRJDko2oQQThcm5Fmc3nNuJIRBsBn7dnc2FOHME7TS5mHRWSORSrEIwMUB2G93w72od0sEIxOR6+Wm2O+yYJFI2UPlmxAqP4kvNhBvevdmwdxOXhROYgcFBIHOuwuT5aV40tOJulkkxuR/fx4/JI1IY4b6ZD6SpAA=) (with show_opt_in)

**Comment by schmunk42** [comment]
CC: @germanbisurgi can `show_opt_in` be used in schema options for an editor?

**Comment by vsudigali** [comment]
HI,

Below is my schema.

	{
  "title": "Person",
  "type": "object",
  "properties": {
    "doit": {
      "type": "boolean",
      "description": "and?",
      "default": "undefined"
    }
  },
  
}

These are editor options


 // Initialize the editor
    var editor = new JSONEditor(document.getElementById('editor_holder'), {
      // Enable fetching schemas via ajax
      ajax: true,
      no_additional_properties: false,
      // The schema for the editor
      schema: person,
        disable_edit_json: true,
      disable_properties: true,
      disable_array_reorder: true,
      disable_array_delete_last_row: true,
      disable_array_delete_all_rows: true,
      collapsed: true,
      use_default_values: false,
      use_name_attributes: true,
      array_controls_top: true,
      display_required_only: false,
      show_opt_in: true,
	  show_errors: 'interaction',
	  remove_empty_properties :false,
	  display_required_only:false,
	  has_placeholder_option:true,

      // Seed the form with a starting value
      startval: starting_value
    });

**Comment by schmunk42** [comment]
You can specify it in options:

```
{
  "title": "Person",
  "type": "object",
  "options": {
    "show_opt_in": true
  },
  "properties": {
    "doit": {
      "type": "boolean",
      "description": "and?",
      "default": true
    }
  }
}
```

**Comment by vsudigali** [comment]
Hi,

Its not helpful. Below is my schema. Why mandatory property value is always setting to false even if I did not specify.
Its working fine for optional props.

Below is my schema.

{
  "title": "Person",
  "type": "object",
  "options": {
	  "show_opt_in" : true
	  },
  "properties": {
    "doit": {
      "type": "boolean",
      "description": "and?"
	  
    }
  },"required":["doit"]
}

**Comment by schmunk42** [comment]
> Why mandatory property value is always setting to false even if I did not specify.

A boolean value is either `true` or `false` it can not be empty.

**Comment by vsudigali** [comment]
OK. My requirement is little different. If I did not select either true or false, it should throw error. But I think that is not possible right ?

Thanks,
Vijay

**Comment by schmunk42** [comment]
Not with a boolean I think.
You could use a `string` type with an enum with 3 values and a pattern.

**Comment by vsudigali** [comment]
Hi,

Thank you so much. It worked.

Thanks,
Vijay
