### ISSUE TITLE
Can not remove dynamic properties when new JSONEditor(required_by_default)

### ISSUE THREAD

**Issue by RelicOfTesla** [json-editor/json-editor#1637]
### General information

- json-editor version: 2.15.1

### Expected behavior
Can delete object property

### Actual behavior
Disable

### Steps to reproduce the behavior

Direct link to example: https://is.gd/nuaXY6

```javascript
new JSONEditor(element, {
   required_by_default : true,
});

{

  "type":"object",
  "properties":{
    "dynamicObj":{
      "options":{
        //  "required_by_default":false // can not reset false....
      },
      "type":"object"
    }
  }
}
```

![ddd](https://github.com/user-attachments/assets/bc410c33-25cb-480e-82fa-763210f7ba5b)

![fff](https://github.com/user-attachments/assets/2dc0ef8a-8ee7-4993-a4bb-9fd14e31a2c2)

**Comment by schmunk42** [comment]
`required_by_default` is a native (sub-)editor option; doesn't go into `option`, see https://is.gd/eWqB4r for a working example.

```
{

  "type":"object",
  "properties": {
    "dynamicObj": {
      "required_by_default":false,
      "required": ["xx"],
      "type":"object",
      "properties": {
        "xx": {
          "type": "string"
        }
      }
    }
  }
}
```
