### ISSUE TITLE
Support show a multi line description

### ISSUE THREAD

**Issue by RelicOfTesla** [json-editor/json-editor#1638]
### General information

- json-editor version: 2.15.1

### Actual behavior
not support

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{

  "type":"object",
  "properties": {
    "aaaa": {
      "description":"aaaa\r\n\r\nbbbbb<br/>ccccc<p>dddd</p><p>eeee</e>"
    }
  }
}
```

source: theme.js
```javascript
  getDescription (text) {
    const el = document.createElement('p')
    if (window.DOMPurify) el.innerHTML = window.DOMPurify.sanitize(text)
    else el.textContent = this.cleanText(text)
    return el
  }
```
We can see that the source code is clean text... Line breaks are not supported. Can we replace it with some special symbol words to support it?

**Comment by schmunk42** [comment]
You need to load DOMPurify manually, which is not supported in the demo.

See playground for an [example](https://is.gd/7ty52W).
