### ISSUE TITLE
Version number is missing from dist files

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#179]
According to CONTRIBUTING.md, there should be a version number in the dist file after an update.
> The following is done when a pull request is accepted. There is no need to do any of these steps yourself.
> Increment version number in src/intro.js and bower.json. Set date in src/intro.js.

### Expected behavior
```javascript
/**
 * @name JSON Editor
 * @description JSON Schema Based Editor
 * Deprecation notice
 * This repo is no longer maintained (see also https://github.com/jdorn/json-editor/issues/800)
 * Development is continued at https://github.com/json-editor/json-editor
 * For details please visit https://github.com/json-editor/json-editor/issues/5
 * @version 1.2.3
 * @author Jeremy Dorn
 * @see https://github.com/jdorn/json-editor/
 * @see https://github.com/json-editor/json-editor
 * @license MIT
 * @example see README.md and docs/ for requirements, examples and usage info
 */
```
### Actual behavior
```javascript
/**
 * @name JSON Editor
 * @description JSON Schema Based Editor
 * Deprecation notice
 * This repo is no longer maintained (see also https://github.com/jdorn/json-editor/issues/800)
 * Development is continued at https://github.com/json-editor/json-editor
 * For details please visit https://github.com/json-editor/json-editor/issues/5
 * @version {{ VERSION }}
 * @author Jeremy Dorn
 * @see https://github.com/jdorn/json-editor/
 * @see https://github.com/json-editor/json-editor
 * @license MIT
 * @example see README.md and docs/ for requirements, examples and usage info
 */
```
### Steps to reproduce the behavior

```javascript
Look at the header on the link to the production version or the development version on the main repro page.
```

**Comment by pmk65** [comment]
Shouldn't the "{{ VERSION }}" marker be substituted with current version during the build process?

**Comment by marc7000** [comment]
Yes, it should. 
When i test this task it works, but when i run "npm version 1.2.0", which then executes the "preversion", "version" (do the string replace) & "postversion" script in "packages.json", it doesn't work. 
I will fix it as soon as possible.

**Comment by pmk65** [comment]
@schmunk42 @marc7000 The version number is still missing from the dist files at cdn.jsdelivr.net, but it's included when you build the dist locally using grunt. 
https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.min.js
https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.js

Doesn't look like the files on cdn.jsdelivr.net are the newest build either. (The latest PRs are missing) So the version updating might be working, but new files not pushed to cdn.

**Comment by schmunk42** [comment]
We had no release in the meantime. 

@marc7000 do we have docs for developers how to create the release?

**Comment by marc7000** [comment]
We have fixed the version bump task and published a new release.

**Comment by pmk65** [comment]
@marc7000 @schmunk42 Getting closer, but there still seems to be a problem with cdn.jsdelivr.net.
Try checking the link to the production version on the readme.md. It points to: https://cdn.jsdelivr.net/npm/@json-editor/json-editor/dist/jsoneditor.min.js

If you view the source you'll notice that it's still missing version number.
removing the filename puts you on the landing page., which says it's 1.3.2. (but it still returns an older file)

Clicking on the "Looking for a nice landing page for your package?" link on that page takes you to another landing page, where the version number says it's 1.2.1
https://www.jsdelivr.com/package/npm/@json-editor/json-editor

**Comment by pmk65** [comment]
Try searching for "cleave" in the source. If you get no hits, it's not 1.3.x but the old 1.2.1 version.

**Comment by pmk65** [comment]
There's also a 2nd "json-editor" on jsdeliv.net, pointing to this github page. (dunno if that poses a problem?)
https://www.jsdelivr.com/?query=author%3A%20json-editor

**Comment by marc7000** [comment]
I've installed it in a new Project, in both sources the version string is correct and found "cleave" in the source...
![bildschirmfoto 2019-01-08 um 16 33 00](https://user-images.githubusercontent.com/1118837/50840816-a60bec00-1363-11e9-8e9b-571e010739ed.png)

**Comment by schmunk42** [comment]
I'll leave it up to @pmk65 to close this :smile:

**Comment by schmunk42** [comment]
Just found this on Google

- https://github.com/video-dev/hls.js/issues/1664

So these seem to work correctly...

- https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js
- https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js

**Comment by pmk65** [comment]
BTW. Is there any reason why all files are put on CDN? Is that something we have control over?
It's only the DIST/ folder that needs to be available at CDN.
See the list of files at https://www.jsdelivr.com/package/npm/@json-editor/json-editor

**Comment by schmunk42** [comment]
> BTW. Is there any reason why all files are put on CDN? Is that something we have control over?
It's only the DIST/ folder that needs to be available at CDN.

Yes, it should be like that.

**Comment by pmk65** [comment]
I created a PR #264 that updates the links in docs and readme.md
