### ISSUE TITLE
Setting option "compact" to true on array type, results in JavaScript error: "TypeError: this.title_controls is undefined" 

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#185]
### Expected behavior

Show array type with less info (label/header, description)

Note:The demo page won't allow me to save a direct link when "compact" is set to true. So I had to set it to false in order to create this [direct link](http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC4QBMCGZaQLawAS2SgHsAnfAD1SwAc4BnEAGhAmUXFjrCfAE9r4SIgCMAVrADG3ZgDNSWdOwDmJVjyLVIRAHYMEoQnVTC4AfQJRToujsQzU0OrGaHjZ6iQ2wSkTnYdOAL7MHl4+EH76IE4kAG4QEoKgYPyCICLiUjyQMGkAyt7xiTxyJArcSCpqIZ4C4ZGgEuiwSqS8AMJEyEl8AuxcqtpKIMHgEDhcVNSIyans2gCuWMLeI8wxRQ1juewAMhBcuEQyuAVxCX7MKX1IqCQkqLzqmhA6eo1ENKhZCPaOsKMoLAsO9emkMpJpNs4Ow8hAhnBToULiV5IpKqo2DUwr5QaFkAspABxTwLaZRa5pAbw4ajDwoilzJCLZarUYSBb3WDaCRPRk3aJgQa0wKisWBIAAAA==&value=N4IgzgpgTgbglgYwiAXKBBDALhA5geygE8BhfAE2RRBABoQs4BbCMLDJgB1QAZ7JYiVqgDaAXQC+EoAA&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction).

So **remember** to change "compact" option to true.

### Actual behavior

JavaScript error: "TypeError: this.title_controls is undefined"
and no array element is displayed.

### Steps to reproduce the behavior

```javascript
{
  "title": "datetime editor examples",
  "id": "test",
  "type": "object",
  "format": "grid",
  "options": {
    "disable_edit_json": false,
    "disable_properties": false
  },
  "properties": {
    "service": {
      "type": "object",
      "title": "Service",
      "format": "grid",
      "properties": {
        "categoryCode": {
          "type": "string"
        },
        "timestamp": {
          "type": "number"
        },
        "services": {
          "title": "List of Services",
          "type": "array",
          "options": {
            "compact": true
          },
          "items": {
            "type": "object",
            "title": "Single Service",
            "format": "grid",
            "properties": {
              "productGroup": {
                "type": "string"
              },
              "price": {
                "type": "number"
              },
              "currency": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by pmk65** [comment]
The issue can be closed.

**Comment by marc7000** [comment]
Fixed in https://github.com/json-editor/json-editor/pull/186
