### ISSUE TITLE
How to differnitate error ands warning in errors arrays

### ISSUE THREAD

**Issue by MahendraBalu** [json-editor/json-editor#188]
### Expected behavior
we have error as type "error" and "warning". if error is type "error" then display in "red" if error type is "warning" then display in "blue"

### Actual behavior
all errors are display in "red"

### Steps to reproduce the behavior

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by pmk65** [comment]
@MahendraBalu All errors are displayed in the same way. There's no error/warning difference.
Which errors do you classify as errors and which as warnings?

A "quick'n'dirty" way to do it, would be to modify the language variables. So that the ones you want to be displayed in blue, is wrapped in a custom class.  But then you will have to modify the theme you use, so that it uses **innerHTML** instead of **textContent**.

Example of overriding the bootstrap3 theme:

````javascript
JSONEditor.defaults.languages.en.error_minLength = '<span style="color: blue">Value must be at least {{0}} characters long</span>';   

var editor = new JSONEditor(element, schema);
editor.theme.addInputError = function(input,text) {
  if(!input.controlgroup) {
      this.queuedInputErrorText = text;
      return;
  }
  input.controlgroup.className = input.controlgroup.className.replace(/\s?has-error/g,'');
  input.controlgroup.className += ' has-error';
  if(!input.errmsg) {
    input.errmsg = document.createElement('p');
    input.errmsg.className = 'help-block errormsg';
    input.controlgroup.appendChild(input.errmsg);
  }
  else {
    input.errmsg.style.display = '';
  }

  //input.errmsg.textContent = text;
  input.errmsg.innerHTML = text;
}
````

**Comment by MahendraBalu** [comment]
We have some errors and warnings in server side business validation. We are storing in json as follows
"messages": [
      {
        "text": "The efast value has been copied to the etast value.",
        "type": "WARNING",       
        "location": "maintenanceAction.maintActionDetails.emaSegment[0].zonSegment[0]"
      },
      {
        "text": "Reporting Station Code REP is invalid.",
        "type": "ERROR",       
        "location": "aevSegment.rep"
      }
]

I have created custom validation function to extract errors and warning from messages array as shown below

 // Custom validators to push the errors from messages
    JsonEditor.defaults.custom_validators.push(function (schema, value, path) {
      var errors = [];      
      if (schema && path === 'root.messages') {
      
        value.forEach(function (message) {              
          /* path format : root.maintenanceAction.maintAction.emaSegment.0.zonSegment.0.evbln */
          errors.push({ path: 'root.' +message.location.replace(/[[]/g, '.').replace(/[\]]/g, ''), message: message.text, property:message.type });
        });
        console.log( errors);
      }
      
      return errors;
    });

I would like to display error in "Red" and warnings in "Blue". Please let me know if it is possible.

**Comment by pmk65** [comment]
You could either use the method I outlined previously, or you can look at the "showValidationErrors" function in the editors. (That's the function that passes the error messages to the "theme.addInputError" function. Which is the one that displays the error message. )

**Comment by MahendraBalu** [comment]
Thank you for your help...
is there any way to display  no. of errors count besides each parent node?
example :  
errors object have following entry
1) path : "root.aevSegment.rep" text:"Invalid Reporting Station"
2) path : "root.evcSegment.ars"  text:"Invalid Code"

I would like to display following on UI
root (No. of errors = 2)
aevSegment (No. of Errors = 1)
evcSegment (No. of Errors = 2)

Let me know if it is possible

**Comment by pmk65** [comment]
@MahendraBalu Currently only the message text is passed to the "theme.addInputError" function.
So you will have to modify the "showValidationErrors" function of each editor if you want the error count passed on too.

**Comment by MahendraBalu** [comment]
Can you please provide some sample how to modify "showValidationErrors" method?

**Comment by pmk65** [comment]
@MahendraBalu Take a look at "src/editors/string.js". You'll find the "showValidationErrors" function there.
This function filters the errors based on the field path. So the resulting "message" array contains all the errors for the current field. Then it calls the theme function "addInputError" to display the error on screen.
You will have to modify those 2 functions to suit your needs.
