### ISSUE TITLE
Cannot build master branch

### ISSUE THREAD

**Issue by nikolay-turpitko** [json-editor/json-editor#19]
Hi guys,
Thank you for supporting this project.
I'm trying to build master branch from your fork and have an issue.

    src/editors/object.js
     713 |  },
             ^ Expected an identifier and instead saw ','.

Apparently, curved bracket get lost somewhere during one of the huge recent merges, could you please check? I've just added one right at this line and it's built. But I'm not sure if this a right fix.

**Comment by nikolay-turpitko** [comment]
Obviously, some part of the code also lost with the curved bracket, 'cause my code (client of the lib), stopped to work when I updated lib from manual build.

**Comment by schmunk42** [comment]
Yepp, we noticed that also, please see https://github.com/json-editor/json-editor/commit/b63fe416ebbfcbb50b94c0f7b72437eabb4b4d98#diff-9ecab8c8676df653092228b56dd73dc1

Could you try building from [`feature/testing`](https://github.com/json-editor/json-editor/tree/feature/testing) to verify it's working.

**Comment by nikolay-turpitko** [comment]
@schmunk42 Yes, I was able to build "feature/testing" without errors.

**Comment by pmadril** [comment]
Hi,
This fix is wrong. Return statement must be after the curved bracket, before the last bracket closing the function, so it also returns the result of:
var result = this._super();

**Comment by schmunk42** [comment]
@pmadril Could you link the line and commit in question?

**Comment by pmadril** [comment]
Hi, I hope this helps:
 [https://github.com/pmadril/json-editor/commit/6e77ac3465f7bbeeec83cf36d662d42c6d8049fc](Fix missing bracket )

**Comment by pmadril** [comment]
Sorry, 
[Fix missing bracket](https://github.com/pmadril/json-editor/commit/6e77ac3465f7bbeeec83cf36d662d42c6d8049fc)
