### ISSUE TITLE
Use htmlClass on Section

### ISSUE THREAD

**Issue by beedjees** [json-editor/json-editor#195]
### Expected behavior
Generate "div" section with specific class name, like this :
```html
<div class="col-sm-6">...</div>
```

### Actual behavior
```html
<div>...</div>
```

### Steps to reproduce the behavior

```javascript
"form": [{
    "type": "section",
    "htmlClass": "col-sm-6",
    "items": [ ... ]
}]
```

**Comment by punit-kulal** [comment]
So is there a way to set the class attribute of any field

**Comment by pmk65** [comment]
You can write a custom theme which sets custom classes on fields, or just use the "data-schemapath", like described in the wiki. [How to restyle form using CSS when there is no individual classes](https://github.com/json-editor/json-editor/wiki/How-to-restyle-form-using-CSS-when-there-is-no-individual-classes)

**Comment by osmanraifgunes** [comment]
"data-schemapath" will not work for arrays. For example I have five elements under array, and schemepath will be dynamic : 

data-schemapath="root.0"
data-schemapath="root.1"
.
.
.
data-schemapath="root.n"

**Comment by germanbisurgi** [comment]
Set a background color on all  elements that have a attribute data-schemapath value that begins with "root.":

```css
[data-schemapath^="root."] {
  background: #ffff00;
}
```
