### ISSUE TITLE
Find the interesting forks and invite them to contribute

### ISSUE THREAD

**Issue by xvaara** [json-editor/json-editor#2]
For example:

https://github.com/niebert/json-editor @niebert

https://github.com/mehmetb/json-editor @mehmetb

https://github.com/dmstr-forks/jdorn-json-editor @dmstr-forks @Kanabanarama

https://github.com/Syzygy24/y-jsoneditor @Syzygy24

https://github.com/AppWorkshop/json-editor @laurenthuron

https://github.com/TJKoury/json-editor/tree/dev @TJKoury

**Comment by loganvolkers** [comment]
I have invited @Syzygy24, the other repos don't have issues or necessarily other ways of contacting the authors.

Closing this issue, but feel free to do your own outreach campaigns :)
