### ISSUE TITLE
State of branches "docs" and "v1.0.0"

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#20]
@loganvolkers What's the state of the branches "docs" and "v1.0.0"?

Could I merge them into master, along with updated testing from https://github.com/json-editor/json-editor/tree/feature/testing

I also think it would be good to remove `dist` from `master`/`develop` since it requires running `grunt` all the time.

Let me know if there are any objections from your side.

**Comment by loganvolkers** [comment]
> @loganvolkers What's the state of the branches "docs" and "v1.0.0"?
> Could I merge them into master, along with updated testing from https://github.com/json-editor/json-editor/tree/feature/testing

Sure, I was just trying to separate the previous version (`7.2.8`) from current work, but in reality it looks like all development is happening on the master branch.

There is still some work to be done on those branches, but they definitely aren't in a bad start.

> I also think it would be good to remove dist from master/develop since it requires running grunt all the time.

That's fine with me.

> Let me know if there are any objections from your side.

Go for it!

**Comment by schmunk42** [comment]
Thank you for your feedback, I am happy to see we're moving forward :smile:
