### ISSUE TITLE
Restructuring files

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#203]
Restructuring the editor files. 
I added a [Contributing Use-cases](https://github.com/json-editor/json-editor/wiki/Restructuring-files---Making-it-easier-to-do-custom-builds)

**Comment by schmunk42** [comment]
Yeah, I think this would be nice. There should also be better formatting and following conventions of https://standardjs.com/

PS: Shouldn't actually the wiki page be the description of this issue?

**Comment by pmk65** [comment]
> 
> 
> Yeah, I think this would be nice. There should also be better formatting and following conventions of https://standardjs.com/

Sounds like a great idea.

> 
> PS: Shouldn't actually the wiki page be the description of this issue?

Probably, but there was no reference /example I could use, so I was not sure how to approach this. :)
I have now added some text outlining how to build a custom dist. And what needs to be changed/modified from the current setup. (Add change it if you think it's wrong or you got some better ideas)

**Comment by schmunk42** [comment]
Ping @marc7000 @germanbisurgi

**Comment by germanbisurgi** [comment]
we could use (ESLint)[https://eslint.org/] and define our conventions in a .json file

`{
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "env": {
    "browser": true
  },
  "rules": {
    "array-bracket-spacing": ["error", "never"],
    "block-spacing": [ "error", "always" ],
    "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
    "camelcase": ["error", { "properties": "never" }],
    "comma-dangle": [ "error", "never" ],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "comma-style": [ "error", "last" ],
    "computed-property-spacing": [ "error", "never" ],
    "consistent-this": [ "error", "self" ],
    "curly": "error",
    "dot-location": ["error", "property"],
    "eol-last": [ "error" ],
    "eqeqeq": ["error", "smart"],
    "func-call-spacing": [ "error", "never" ],
    "indent": [2, 2, {"SwitchCase": 1}],
    "key-spacing": ["error", { "mode": "minimum" }],
    "keyword-spacing": ["error", { "before": true }],
    "linebreak-style": [ "off" ],
    "lines-around-comment": [ "error", { "beforeBlockComment": true, "afterBlockComment": false, "beforeLineComment": false, "afterLineComment": false, "allowBlockStart": true, "allowBlockEnd": false, "allowObjectStart": true, "allowArrayStart": true }],
    "new-parens": "error",
    "no-alert": "error",
    "no-caller": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-eval": "error",
    "no-fallthrough": "error",
    "no-floating-decimal": "error",
    "no-func-assign": "error",
    "no-invalid-this": "error",
    "no-lonely-if": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-multi-str": "error",
    "no-multiple-empty-lines": ["error", { "max": 1 }],
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-plusplus": "off",
    "no-redeclare": "error",
    "no-self-assign": "error",
    "no-self-compare": "error",
    "no-sparse-arrays": "error",
    "no-trailing-spaces": [ "error" ],
    "no-underscore-dangle": "off",
    "no-unneeded-ternary": "error",
    "no-unreachable": "error",
    "no-whitespace-before-property": "error",
    "one-var": ["error", "never"],
    "operator-linebreak": ["error", "after"],
    "quote-props": [ "error", "as-needed" ],
    "yoda": ["error", "never"],
    "quotes": ["error", "single"],
    "semi": ["error", "always"],
    "semi-spacing": [ "error", { "before": false, "after": true } ],
    "space-before-blocks": "error",
    "space-before-function-paren": "error",
    "space-in-parens": [ "error",  "never" ],
    "space-infix-ops": [ "error", { "int32Hint": true } ],
    "space-unary-ops": "error",
    "spaced-comment": [ "error", "always", { "block": { "balanced": true, "exceptions": ["*", "!"] }} ],
    "wrap-regex": "error"
  }
}`

**Comment by schmunk42** [comment]
According to https://eslint.org/docs/user-guide/configuring - ecmaVersion: 5 is the current default - which one to pick here?

**Comment by pmk65** [comment]
Another thing that annoys me, is the use of "element.className", which is prone to errors. (Specially when using regex to test/remove classnames)
We should refactor that, and use ["element.classList"](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList), which has methods for adding, removing and toggling separate class names.

Some examples from the current code:

````
this.container.className += ' compact';
input.controlgroup.className = input.controlgroup.className.replace(/\s?error/g,'');
row.container.className = row.container.className.replace(/\s?active/g,'');
````
Using "element.classList", this would look like:

````
this.container.classList.add('compact');
input.controlgroup.classList.remove('error');
row.container.classList.toggle('active');
````

**Comment by schmunk42** [comment]
Also we should think about merging the open PRs before https://github.com/json-editor/json-editor/pulls - if they are ready.

**Comment by pmk65** [comment]
> 
> 
> According to https://eslint.org/docs/user-guide/configuring - ecmaVersion: 5 is the current default - which one to pick here?

5 matches the current code syntax, so that should be ok.

**Comment by pmk65** [comment]
@marc7000 Is it possible to change the Gruntfile.js setup, so that the individual editors is not referenced by name, but just by the folder path?
That would help to make it easier to build custom versions. (See my proposal for new file layout in the [Wiki](https://github.com/json-editor/json-editor/wiki/Restructuring-files---Making-it-easier-to-do-custom-builds#building-a-custom-version))

**Comment by pmk65** [comment]
I think "src/ie9.js" should be excluded from the build, as it can be included separately if needed. 
IE9 is currently used by 1.62% according to [Browser Statistics](https://www.stetic.com/market-share/browser/)

**Comment by marc7000** [comment]
@pmk65 Yes that can be done, as long as everything works as before and we can build a production release ;)
