### ISSUE TITLE
Support for CKEditor

### ISSUE THREAD

**Issue by mlutken** [json-editor/json-editor#204]
Thanks a lot for this json editor.
We are using it a lot and it really helps us.

This a request to either implement support for the CKEditor or directions how to do it.

**Comment by pmk65** [comment]
There's already support for another WYSIWYG editor [SCEditor](https://www.sceditor.com/). So you probably will have to create a CKEditor implementation yourself.
Try looking at how SCEditor is implemented in src/strings.js. Also look at the wiki on how to extend/create JSON-Editor editors.

**Comment by schmunk42** [comment]
Here's an example how we're using CKEditor in Yii2 widgets:
https://github.com/dmstr/yii2-widgets2-module/blob/release/2.x/src/assets/web/widgets-init.js
