### ISSUE TITLE
Materialize Theme Glitches with Default Values & Range

### ISSUE THREAD

**Issue by Digicrat** [json-editor/json-editor#205]
### Expected behavior
Labels should not overlap form elements.

### Actual behavior
If a default value is specified for any type that evaluates to a text input (string, number, etc.), the label overlaps the input field when using the Materialize theme.  

This also applies when using the 'range' number format, even without a default value being specified.

### Analysis / Workaround
The 'active' class needs to be applied to the label any time a default value is specified, or if the format is specified as range.

As a workaround, executing M.updateTextFields() in the editor.on('ready') handler resolves the case when default values are specified.

And for the range elements (if using jquery):
  $('.input-field:has(.range-output) label').addClass('active')

The default behavior of the plugin should be fixed to handle these cases, though I'm not familiar enough with this plugin to figure out how to do so myself.

**Comment by pmk65** [comment]
@Digicrat The rendering of Materialize components is handled by the "JSONEditor.defaults.themes.materialize" class. (Located in the file "src/themes/materialize.js")
Inside this (and other [themes](https://github.com/json-editor/json-editor/wiki#theme-srcthemejs)), you'll find various functions for creating the components.

You can try modifying this, and see if you can fix it (I don't use materialize myself).
The 2nd problem should be fixable in the theme, but the 1st one might need some core/editor adjustments.

**Comment by lukzas** [comment]
@pmk65 I'm able to fix the range label issue easily. However, I've noticed that the radio is also affected, but it's broken for 2.x branch completely. For 1.x code, I'm struggling to access it inside `getFormControl` theme function. When I try to dump input.type none of them is "radio", on the other hand, "range" is found with no problem. Any clues?

Regarding text input default issue it seems to be broken on newly created array items with default value set, oneOf, $refs or other dynamically set sections. I'm able to fix layout in materialize.js, but I struggle to check the value of the field from a theme level as input.value is empty. Is editor accessible from there?

PS providing [LINK](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgBkBDRHAV3inioAzv2IchwilWwAnVAEcetOQBNMUANrTqCYfADC4ycGkBdStGzIZONDLrGs4SzsEjDEoeucxf2JGjqcCIytBAA5lIuvjT0TEHAACp6UB7MFn46qBA8ALbqWtF%2BwfAcECocMipiEgCMUZkxwCJlFVU1qABMDY3YlTJcHfXAGb1w%2FYNG3SPameMyA4gdAMw9jfOLHQAsa3O4hCTwQ7vF%2B0SkHdOj62eHKydN%2BOdHRjsmRVDmszq2dDgQXhYUB8Y2A2TyAH06IxHJpvnsAMqlcqVFRQABitFQDBUgOuoKRrVRGKxOKEUAA7gA6KC%2FWj%2FKDEHC5ZAcUhYeAyHjpeGnACCCy4D35gsQlJpADMcDJchx4ByOHg8bymgLFuKoFKZXKFUqALTwWzC1WijVa2XygSK%2BIzD6nADyB1Ixp0jueZulFqwYkE4WlWOVdqabsOHu1lvCoTUtt6wad%2FGpms9OqgkdoKj1IVozvesdM8IAvrMC%2FiaHo0t54TQUMxWLcc%2FidOa5Qk09HG%2F44rXsMkRKkjA84AALVAcFSoGTJFkMOXduAgEDQpgFgvAxflowrwe4ZB%2FAGVoNwJkstlkIGc7kdnQqWhCa2oCHWWwThyAjlc1BX7A3u94JgQ1Ab3gCECCEf51AvT8VTgH97whJkGBnZAJAgj9Cw7OAKTlYghwPWMy3cAcgQIgwjEBdCq2ABgwgAazfOEgxBfDgDkBgEnHIRiFCPBAIAIUQF1sCHOQJQSABiAB6ccJTCeh6QBCSFzcUiJC3XNeiLD582iTSYBLaQYNQGSIDk%2F56KY7AWhRdojGGJxKKfOxXzw0FBAADzoCBkD4OzgRVVwawSLMIkE2IYQSZIPKgMJvP4GTsTRCl6CHKAOK42hd3kqBWmiiApUi%2FgAApgvCABKULgDS0JMvA4iklQKKYr4TVSUS5LUuEdKaugHKwnyhr4BpYrOTCMqKrpMyXNjHQ%2BpwAqIqHW8WoS6LyXCbIJ1nNE8DFIQZGICTAPoaUhAkkqqVAwSdDbeCcAYPJ9yBAA2fyoF0jSvzLDymvgWpfIsm4AjnYAclyHiZAqpdgYK3LYuWnFKXaqqMr3bLyly%2FqosK0HwfKmNpsMzjqr3CKBth5r4oRpL4BS5HurRtFZoKoacYnPGvx%2BbrzNema8rmgaFqWynGbWjaBkEbbdv2w6gJOiTWZkC7A2mpoboQh76JeoM9JVfTD10b6vJ86Z7O1%2FxArqsJfQnSGu1Jxqjbi1rEZpjqiZRrLer5mHCqt1B1pkdnXsJrqSbqmGfvhtrXbp1GvcxwaoF9iBrcD8auamgngCZgXw8W8lhdW1Mxa2qAdqgPaDqOw0ZFOv2A6Vq7sDVu6NfULWVfexo9eY9zPNi1YgQBvYgYSeubfx5jmzPOsBgiHkzbCm06wAJTKdbyadlbqdpzric99Gc48irY%2FkhI1%2Fnzeo5d3f3fp%2BP%2BY8ql073bmzd5hPBYL52lvWiBNolmXKWVdZa1wkuPRWl1J5ZxbvdXIj0sAd2ml3TIPdXIDR%2BibPyi8EAWzrCVCq08Eh90qKOW24Vw4DVIRwK%2Bhcd5u1DgfRm3tc4c2%2FHvD2tU6wFWobQ529DT4MgfszF%2B8k34qw%2Fo%2FGePZ87X1%2FiXQB5dK4y2OmA86UC2HXSjLdOBCCoC1G6GbFBfg0E3BwiQGieAcBuR%2Bv9YOuDAh1SsXdUcEBCHJmkUeEcxBLHWPIcvbA%2BhvG%2BLcnw7eSMOH30PiwrGzimBlCDjgwRbi6pBIsVY0Jkc6ERLvnHaJCchpxNcYklWhkJQcB4AwaRkE2FwAmno4eNwj6eKSLIwu8j%2F7i0AkAiu0tq5y3MT4jJjdoHMVgW3Z6r1jG%2BFMXsCQTBSC2MzoDPBlkRohVGSPO2dUETYlDFk%2FhOTGFCPyVIk%2BkSw51l2Qs%2FgBzwkxwuUwjGUjn6bNOOCfIQJCgSOwMMTR2Arg82wIPV6XwcH1PERIuAHyoRdnot8n52BMS1zPP8nQuymTlCbjoRIi0qhwCBWCn5cBmlfzkaLTppclF9NAadeZhwRn%2FLgOM%2BBmspm60%2BixMc9IllD3saPOqBC3lNCIXVAYN4cD%2BOBmvCVYSqZHP3ic5hn9hXXkeVw7AMr6RyujrfY5PVTnzVVdgD5BQgVwBXoBJucAADichsjWuALxe6zBQW1J3K%2FZZoJSV5yFj%2FClADunUpAao064r6SMvNcAFleikGxmmXpTluRKl0HpYsx2dicECrrBMASxq4CivwXshs9ieAmUUKgAAkoIXI9Ean8u2XWAAsim28xbbmO2vgI9VBrlVSKgHqJM4YsBptRfY5JCQW1VLbTcnVN8GGKt7c85mA6h1egru2iq9BUC1q9Ssxx%2BD1mRGNVkUGZr35NCsTibF2B6AcGosQG9wRZSITEMhAlF7tKd3dRCvdewfXcLaf64ulLFHAJUTXU6ybp2jsjRe5l2j1asvbuyoMszTjQdTe2zBf6AoHr6KKdx4YEiDJCRVMttAK3Vp3XWj87qoaTtbaOud3bclPOaau6e3pgkZPOWxjVcAp1YdnXc%2BVDz%2BNLuaTSQdXHGQ8b8fm7ONbIWlIccDIVTKwRnq%2BUCnQV72y6dvaUB9T7mgvoYG%2B8in6pk%2Fozny%2BD2cYktNxX6laHTA2S16SGyDElMMzoZRoqNMa2VGN1oWYspZmjIjaNUKYXq4CORfAGP9X1%2B4%2BVw%2BbfDJRQgbPo42nsZNRO6oXZwyTTm%2BP6vth2uG2TxP6oZsugarzbOevs8SxzKruGFc7bVvVi6GtScdceVkOZ3zclQ%2FGzlfccNtaztmtZOXj3usLf4KhcgOBSqq7wor87kkDfK4pidlCPLbZ64cur%2FXhFNdEZNWbqmAMFZO%2BtljCrSv7YKUN5kI3qloVC2hqbGDHaD1Nqp%2BbJKU7%2BwnstjxCQ57rU23VC%2BG8dusfq1d4%2Bh2e3n3XqgF7F23vo8GjdhpUaHsWpx3jvrBPDXXZPdgYbp5ULjb%2B5N6CwBSMZN5SDubqzsujSIxaEj8m3II7rGkoZ1jKclaiX2o17qjti%2BF1LvbhPmv2N%2FXdrOZPgDi5Ccrnt72XmfZPKNgQv3O4crZ6Orn2DQe86i4t0X2Brn7LO%2FcqnMvGsY%2Fl1jnZ7b9cScNyIxTpqdMOb%2BVGwFDmQVmyJVnDX3PVMwqhvCwzcBkUiFMxi%2F4BmL04rxdGQlmntcu9IAHtHNOn7G%2B%2B0z9ALOPps789bjNGXqxZeALmgXLZBWbsUxRqjyna95Yoc2pj%2FuUevc9xxmTHiR2959xJxjMHx9u7Ex7vJsumucdnxum5W7B%2Ba97vbjTUbQ9YARe1%2FTpm70mbpzoIQ5nLMfp%2BV%2B5BLWxEZckUa0fy%2BROr%2BKyrpXonDPsOrvocNXozueObsgpbvrE3tho7Fgo0k0GDh3oRopitl4ukgpu6v3tyNRrulAZeA2iPtgEJv5mXhPvjlPk5tvqARzjgeOr7j%2FsJq7jVuduvuxk5tJmuimAwSLoptuoQYnjzu3ifg5mfgxIitgFfnfkZvetmKZg%2FvehZhwO%2BupCrK%2FqzuCnZiIcxNruQcxlQZwUql7sAbwZaPwRAabpBBNg3vrOGjgLYhtofiPMfkel3i0o4U7uTrKsYdLhvmYRVoutjn4f%2FrtgboThVJIRflnJarnu1naqgA6nTnAM6uNhob0HHsxAnrblCh1mcojtyjgOXpdkAdYT9szhbmhuFjpJFrmscK4QljYE5Mlq4a4HoJmnbu3p3opgxqkndCdOcuUimueu1vEY6kkSkZpuka6rHu6kISpqIeph4Zkd3GFh8CgrMhsJMBIEgQ5C0UlrCMgSRF0csQkL0dDsRnVKUEqD4TroMbXMMRUlUmMfkRMakcAFMSkjMS6s%2FtNNkd6gfnoa5O4Y7msaghsesXUbMDsUsEYMDnkacIlvYG0SCR0SIGcUfj0egVcYLjcYqEIAaEaH0flnAPoI8crFnNJC8dIrEcxB8Zpt8Y6rMf8XmAscCUiecYKqsXYdCfyTMvUaKNsPFsACic5O0atpia3mphcbifYpgQgPePcRSQwEMZjiMa8WHuMVap8cyZ8ayRCX4ICU0pycgacKgUKnyZCZsRFrCfWC8HUKKeKWiVyRaZ0TKagU8OAaSaQXACGCWjgi6ccVGspFifkZabyReuhugiIPsXnplsDArGyW%2FqGXoIieaW4e3hAimfGtaSYrUSYpFt6RcHFk0WKYcaiSGfrGGZ6fbiWWOjgoqT6P7P6MYMPgEv6fGGGOui2X6KEO2erroW6aCLBH%2BA%2BAhEhChEQVBA5mOf%2BNXCBGBCkmNrOe1vOQ%2BMGbRlUamUGZWRKeiXsD6OGd0cDA2aZv0WLrOP2WKBHgmXUsOZmTcBuTolOd2PWgmdeLeHBIuaBBqh%2BdIV%2Bb%2BP%2BFuUPoZjoAzjYdAT8jGcxKBZKcxEKoeaeUFFGYBW9IZgmqgppj6PGdIW3mefGBeWSTrtedKGKFHvhR6h%2FghaOd%2BeOa%2BWodOauWik0C%2Bb%2BcuWBZ%2Bd%2BPRSBfua6bYQmbBaCPBchaCMmbRdiUmXkODLmRIlhQKd%2BlGj6BmWnrKXVOeXIUvMDIYL6ORVAIPKxc0c%2BFWUse1jmZJaCdmRDgHHJdUdIQpTMvmU5baTCdEHUvGPcOWaJSORib9HWe3ppXid3nWG2PcQGQmJKDvmFYpj5U%2BVKf5ZZXhiseCUCsJe6XGZ%2FigfbhJWlZpspKpfeepXWBZWlc5TrK5UWfaQ2SKd5fxdWb3B6bRQRQkEFQqTDnVG2JmCNIGaDiRRFT2SmF1VmL1VnHFWmdKUlYmaheCUZdRbdmJTcMFuoFsKxVoumBCHgOtjRLXphXlRNfAHhYii1XVBJXNbkfFacMtUCIYg5ftQ5gVVlclWPDZVDmpRdeBc3Ihq3MhjdXtdGeVRhZVS5RVQWMAEAA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=materialize&iconlib=materialicons&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1) to example presenting issues mentioned by @Digicrat

**Comment by lukzas** [comment]
Update regarding "radio" - it looks like input.type is undefined as when dumped along with label.innerHTML the result is `undefined radioinput1a`, so the second part of the condition `if (type && (type === 'checkbox' || type === 'radio'))` in `getFormControl` function will never hold (radio type check wasn't there in 1.x branch)

**Comment by lukzas** [comment]
Dirty fix for radio and range labels:
```
getFormControl: function(label, input, description, infoText) {

      var ctrl,
      type = input.type;

      if(!type){ // Workaround for radio (and possibly others) wrapped in div
        if(input.querySelector("input[type='radio']")){
          if(label){
            label.classList.add('active'); // Fix overlapping label
          }
        }
      }

      if (type && (type === 'range')) {
        if(label){
          label.classList.add('active'); // Fix overlapping label
        }
      }

     [...]
}
```

**Comment by pmk65** [comment]
@lukzas In the 2.x branch I have added additional functions for rendering radio and range elements. (In 1.x this is hardcoded) I think your problem is that you are not using/or applying your changes in those functions.

`getFormRadio()` -Gets the radio input field
`getFormRadioLabel()` - Gets the radio input label
`getFormRadioControl()` - Wraps up the radio input and the label

`getRangeInput()` - Get the range input field
`getRangeOutput()` - Get range output element
`getRangeControl()` - Wraps up the range input and the output element

The input parameter in `getFormControl()` is normally the input field (as there's only one), but in the radio and range editor it's a wrapper. (that's why you can't get any type result)

So try and see if it helps if you add the type check in `getFormRadioControl()` and `getRangeControl()`instead.

Your workaround seems to be a OK solution. Another way, is to add a "type" parameter to the wrapper element. Not sure which approach is the best.

**Comment by lukzas** [comment]
@pmk65 thanks for pointing that out, I'll check and try to implement proper solution :)

**Comment by lukzas** [comment]
Seems that getFormRadio() and getFormRadioLabel() returns single radio element and corresponding label - not interested in these. getFormRadioControl() returns single radio with label wrapped as follows:
```
<div>
  <label for="root[radioinput1a][0]">
    <input type="radio" name="root[radioinput1a]" id="root[radioinput1a][0]" value="Red" style="display: inline-block; width: auto;">&nbsp;Red
  </label>
</div>

```
However, what we need is label for parent of that element:
```
<label class="required">radioinput1a</label> // we need this
<div name="root[radioinput1a]">
  <div>
    <div> // we get this
      <label for="root[radioinput1a][0]">
        <input type="radio" name="root[radioinput1a]" id="root[radioinput1a][0]" value="Red" style="display: inline-block; width: auto;">&nbsp;Red
      </label>
    </div>
</div>
```
So either its accessible as parent sibling from radio control element or as in dirty solution as child of form control.

**Comment by lukzas** [comment]
Regarding range, I could use getRangeControl() if it takes the label as param, as currently it returns following:
```
<div style="text-align: center;">
  <output>0
  </output>
  <input type="range" min="0" max="100" step="1" data-schemaformat="range" name="root[range]">
</div>
```
without label sibling `<label class="required">range</label>`

**Comment by pmk65** [comment]
> 
> 
> Seems that getFormRadio() and getFormRadioLabel() returns single radio element and corresponding label - not interested in these. getFormRadioControl() returns single radio with label wrapped as follows:
> 
> ```
> <div>
>   <label for="root[radioinput1a][0]">
>     <input type="radio" name="root[radioinput1a]" id="root[radioinput1a][0]" value="Red" style="display: inline-block; width: auto;">&nbsp;Red
>   </label>
> </div>
> ```
> However, what we need is label for parent of that element:

The getFormRadioControl() function only returns a single radio element (wrapped in label) to the the Radio editor (src/editors/radio,js), which then supplies the header, description etc. and wraps it all up in the final element. So you should end up with a final output similar to this (Taken from the Spectre theme output)

````html
<div class="form-group">
  <label class="required je-label form-label">Radio input field with description and infoText</label>
  <div name="root[testcase][radio]">
    <div>
      <label class="form-radio" for="root[testcase][radio][0]"><input type="radio" name="root[testcase][radio]" id="root[testcase][radio][0]" value="Red"><i class="form-icon"></i> Red</label>
      <label class="form-radio" for="root[testcase][radio][1]"><input type="radio" name="root[testcase][radio]" id="root[testcase][radio][1]" value="Green"><i class="form-icon"></i> Green</label>
      <label class="form-radio" for="root[testcase][radio][2]"><input type="radio" name="root[testcase][radio]" id="root[testcase][radio][2]" value="Blue"><i class="form-icon"></i> Blue</label>
    </div>
  </div>
  <p class="je-desc hide-sm">Radio input field with description and infoText</p>
</div>
````

> 
> Regarding range, I could use getRangeControl() if it takes the label as param,...

Again the label is supplied/added by the editor itself, you should just return a single input element (or in the case of radio and range, a wrapper) to the editor. 
The radio and range wrapping is something I introduced in 2.x since both elements where hardcoded before. The wrapper method worked for me when I made the Spectre theme, but it might not be the optimal solution.
So it good to have your input regarding a different theme/framework. That really helps making it more usable. 👍 

I did notice a bug in the Radio editor. If you don't have "required by default" set, it will add a radio element with no label. (I'm going to fix this later today.)
Try the Playground schema I uploaded in #439. I have removed DescribedBy editor as it prevented my JavaScript from recreating the editor. And also cleaned up the schema so it uses definitions.

**Comment by lukzas** [comment]
@pmk65 I've created PR #456 for radio and range. Regarding ther inputs, I've come up with the following solution (had to check if the default value is set, maybe there's a better way?): 
```javascript
// editor\string.js
[...]
if(this.schema.default){
      input.dataset.defaultValue = this.schema.default;
}
this.control = this.theme.getFormControl(this.label, input, this.description, this.infoButton);
[...]
```
```javascript
// themes\materialize.js
getFormControl: function(label, input, description, infoText) {
      [...]
      if (input.dataset.defaultValue && label) {
          label.classList.add('active'); 
      }
      [...]
}
```

**Comment by pmk65** [comment]
@lukzas I have been digging into the themes code lately, and I think the correct procedure is to use the Theme `afterInputReady` function for things like this..

This function runs AFTER ALL other field operations is finished. So the default value should be have been set at this point.  In the `afterInputReady` function you have access to the input element, so you can  test if `input.value` is set or not.

In the Spectre theme, I used the `afterInputReady` code from the Bootstrap4 Theme. Without it, the error messages would not display in some cases. (I can see that there's currently no `afterInputReady` code in the Materialize Theme.

**Comment by lukzas** [comment]
@pmk65 I've considered this function, but the label is not accessible from inside. I would need to pass it to `afterInputReady` along with input as param. The reason behind my implementation was to fix it without BC to other themes, not improve theming in general 😃. While I agree that we should discuss theming enhancements in #439, this change was directly related to the current issue.

**Comment by pmk65** [comment]
For the 2.x version, we should try to address all problematic cases, (like the one you got with the label) 
And see if code change is needed to help solve it. But in this case I think the `afterInputReady` is the best solution. (See my explanation and example in #439)

**Comment by lukzas** [comment]
What about:
```javascript
afterInputReady: function(input) {
      var label = input.previousSibling;
      if(input.value && label && label.localName === 'label'){
        label.classList.add('active'); 
      }
    }
```

**Comment by pmk65** [comment]
That looks perfect. And you can add additional checks/adjustments for other element types if needed.

**Comment by lukzas** [comment]
I was able to fix `range` in the same manner, but not `radio`. I've tried adding `afterInputReady` to `radio.js`, however, it's not fired - maybe because it's broken for 2.x as mentioned earlier.
```javascript
afterInputReady: function(input) {
      var label = input.previousSibling;

      if(input.type && input.type === 'range'){
        label = input.parentElement.previousSibling;
      }

      if(input.value && label && label.localName === 'label'){
        label.classList.add('active'); 
      }
    },
```

**Comment by pmk65** [comment]
@lukzas I have added the missing `afterInputReady` call to `src/editors/radio.js` now.
But in the case of radio, the "input" is a wrapper and not the actual input element. (This was something I made when converting the hardcoded radio rendering into theme functions, as it's not a single element.)
Maybe some class or data attribute on the wrapper would help identify it? (Currently there's just the path/name data attribute)

**Comment by lukzas** [comment]
@pmk65 I'm aware it's a wrapper that's why I replied in PR that I'm not sure about dropping data attribute 😉. Alternatively, we could try to traverse children and check for radios, but I think attribute is a cleaner approach.

What about leaving the current data attribute? We can move it to `afterInputReady`. Then the code would be as follows:
```javascript
// radio.js
afterInputReady: function() {
    var self = this;
    self.input.dataset.containerFor = 'radio';
    self.theme.afterInputReady(self.input);
  }
// materialize.js
afterInputReady: function(input) {
      var label = input.previousSibling;

      if(input.type && input.type === 'range'){
        label = input.parentElement.previousSibling;
      }

      if(input.value || (input.dataset.containerFor && input.dataset.containerFor === 'radio')){
        if(label && label.localName === 'label'){
          label.classList.add('active'); 
        }
      } 
    }
```
We can also get rid of checks in `getFormControl()` then. Let me know if you're satisfied with above and I'll commit it.

Regarding further refactoring, we need to check why material radio is broken compared to 1.x

**Comment by pmk65** [comment]
> 
> 
> Regarding further refactoring, we need to check why material radio is broken compared to 1.x

in 1.x the radio editor extended string class, so there was not full enum support. I changed it to extend select class (Which makes more sense). Also the output was hardcoded in 1.x, so I added the theme functions for rendering radio output (including the wrapper).

**Comment by pmk65** [comment]
Looks fine. I think this is a good solution.
