### ISSUE TITLE
proper way to send editors values via ajax

### ISSUE THREAD

**Issue by andreasbourges** [json-editor/json-editor#207]
Hi,

...is there any example on how to properly send the values from the editor via ajax to a backend server? I would like to send a serialized json structure, but in the end what is sent is:

Devices[0][IP]: 1.1.1.1
Devices[0][name]: test-1
Devices[0][description]: vla
Devices[1][IP]: 1.1.1.2
Devices[1][name]: test-2
Devices[1][description]: bla

instead of 

{
    "Devices": [
        {
          "name": "test-1",
           "IP:"  "1.1.1.1",
           "description:"  "vla"
        },
        {
          "name": "test-2",
           "IP:"  "1.1.1.2",
           "description:"  "bla"
        }
}

This is my current code:

$.ajax({
                type: "POST",
                async: true,
                url: "/web-inventory/save",
                dataType: 'json',
                data: editor.getValue(),
                success: function(response) {
                        console.log("saved successfully");
                },
                error: function (error) {
                    console.log("ERROR", error);
                }
            });

Tried my luck with JSON.stringify() as well, but this results in a strange behaviour:

// replace the following line in the above example:
    data: JSON.stringify(editor.getValue()),

{"Devices":[{"IP":"1.1.1.1","name":"test-1","description":"vla"},{"IP":"1.1.1.2","name":"test-2","description":"bla"}],"Dynamic Groups":[{"Group-Name":"BGP","Device-Attribute":"name","Regex":".*sd.*"}],"VRFs":[{"route-target":1100,"name":"TEST-VRF","description":"a test vrf"}],"VLANs":[{"id":100,"name":"vlan-100-test","description":"a test vlan"}]}: 

--> notice that the whole key-value-content is used as a key for the dictionary and the value is empty (note the ":" at the end?!).

When parsing this in the backend, I it resulst in one key with empty value :(

Any hints on how to send the editors content via ajax?

Thanks,

Andreas

**Comment by andreasbourges** [comment]
oh my god - I got a backend decoding issue here. Sorry for the noise...

**Comment by PydPiper** [comment]
@andreasbourges sorry what was your solution for this? I have been searching for the past few hours and nothing seem to be working. I am getting the exact same thing on my django backend and i find it crazy that there is not a simple deserialize for this
