### ISSUE TITLE
How to judge the end and start times

### ISSUE THREAD

**Issue by lsc9** [json-editor/json-editor#209]
### Expected behavior
"minimum":"{{start}}" don't invoke Start_time .
### Steps to reproduce the behavior

                 "Start_time":{
                    "type": "integer",
                    "format": "datetime-local",
                    "options": {
                        "grid_columns": 6,
                        "flatpickr": {
                            "wrap": true,
                            "time_24hr": true,
                            "allowInput": true
                        }
                    }
                },
                "End_time":{
                    "type": "integer",
                    "format": "datetime-local",
                    "options": {
                        "grid_columns": 6,
                        "flatpickr": {
                            "wrap": true,
                            "time_24hr": true,
                            "allowInput": true
                        }
                    },
                    "watch":{
                        "start":"root.Start_time"
                    },
                    "minimum":"{{start}}"
                }
```

**Comment by pmk65** [comment]
@lsc9 I don't think you can use a watched field like that, as the "minimum" is part of the schema, and not based on your input value.
Instead, try watching the field from JavaScript using the onwatch function. Using that, you can manipulate the various fields much better. i.e.
1) Watch for changes in "End_time"
2) If change is detected, get the value from "Start_time" and compare it with "End_time"
3) If End is less than Start, fire a custom error.

**Comment by pmk65** [comment]
@lsc9  The "minimum" option just sets the "min" attribute on the input field. Currently, there's no way to modify that dynamically based on another field. (Unless you do it by JavaScript as I explained previously.)
 
But there are some [plugins](https://flatpickr.js.org/plugins/) available for Flatpickr, which can improve range inputs. Maybe installing one of those will solve your problem.
