### ISSUE TITLE
bootstrap select integration fails

### ISSUE THREAD

**Issue by punit-kulal** [json-editor/json-editor#211]
### Expected behavior
when a selector is changed, the value should be relfected in the jsoneditor.getValue();

### Actual behavior
The on change event is not triggered, jsoneditor.getValue() does not update the values of the selector value selected

### Steps to reproduce the behavior
add selectpicker class to all select tag in the json editor via jquery
try changing the value of select tag, and use developer console debugger. 
The onChange event is not triggered.

The jsoneditor.getValue is not updated when we trigger the on change callback by changing any other  editor input

```javascript
$('select').addClass('selectpicker').data('live-search','true');
```

**Comment by pmk65** [comment]
@punit-kulal  You can't expect 3rd-party plugin integrates without problems. Take a look at the src/editors/select.js and src/editors/selectize.js files and see how the onchange is handled there.
Basically, you need to call "onInputChange" after you change something.

**Comment by germanbisurgi** [comment]
You could trigger manually that change event:

```javascript
var input = document.querySelector('[name="root[name]"]');
var event = document.createEvent("HTMLEvents");
event.initEvent('change', false, true);
input.dispatchEvent(event);
```
