### ISSUE TITLE
Set initial value of readonly field?

### ISSUE THREAD

**Issue by taschmidt** [json-editor/json-editor#212]
I have a field with `readonly: true` because it shouldn't be editable once initially set.  The problem is, when setting `readonly` to `true`, it won't even let me set it when creating a new item.  Is there a way to accomplish this?

**Comment by taschmidt** [comment]
Anyone?

**Comment by schmunk42** [comment]
Sorry, had the same issue already, but found no solution yet.

**Comment by pmk65** [comment]
@taschmidt can you provide a direct link to an example schema using the [interactive demo](https://rawgit.com/json-editor/json-editor/master/docs/demo.html)?

**Comment by taschmidt** [comment]
Yeah, I guess the easiest way to adapt the demo to my situation would be to assume that you can't change a pet type once it's initially set.  But adding `"readonly": true` to the pet type makes it so you can never set it.  See it here:

https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iBwBDALbxCQgObiQ3IWBkAzIQDcsaKLAD6dLNHVNpObuib668iLiZkwGEAF1CJNFjJpIsewlDCxiUDBSchAMMA0cSSYTDDoNEkhrJAAxLjCAAiFjdIAZIQy/GREIHBzYSLAAC0QAFkITZXZoRiQAKXRYESJ0gBF1PABfCWkA4jJEEBKFaTRo2EbmxAAmAFZCYpwIEXYRRABGAA51oQAPLZ3EAE5LoZBlNQ0FHT0DHzGQsIiowkV1EXkJrp9LNCJAYCF7upNOkgQZ6vMhE0WiAAMSKZQrAAMmJAtyMJlmbyC4yQnxK3xA5QuCAE/zgTEUnSE9IctzkClGxI+4XJDL+AKQ7JkbkSOG8oEU0HkJAgdAA1oTgANlYRzJYkoFghMqLQGEwwfSkDksBZRTZXO5POKQHQoEROVrSTzInMFsiAMpZdLJNBZW2xLC4whheTkTUk0LOikNRGLJAAYQAgkGbXaQxyiY7I185rF4makAAVSoQDDpUvpIzoUPcTLsMBYf6QCzQaDdRSuETpKqwdIuWAqKzsMtgADuWHSiggsGg3HsoM6JClGZAwGAtqCKvSa/TsGVTFH8jo1TeG/tSDVooAdGemLuJperDgr/flSqQLZrVyJkI0L77T8/LImAQiUPSoJQIaKCwHYTDsJsHCwAAkgoIjeOE7CwIQmhoQ6EY6vQjAQeCEyoERH4WugVp4WG7wTGSLqEFSuw0jaAL1FgFKUFwvCECwCQQOBIBYD2sxOLICJIhM3CcUwLBCDJOBtogGF7oQhQ0fRUa4u+MZSTS4YhDJFIaUgADqzIKLMAyssqQA==&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxgAXzIAHGJwDOCANqhOmW6KX4K8yLFEA6hrcqCAWALoWQA&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by schmunk42** [comment]
What would happen if you mis-clicked the initial value?

I think you should "lock" the items with some custom code, I can't see how this fits into a JSON schema spec.

**Comment by pmk65** [comment]
I think the problem is that the pet field is not set to "readonly" (even if that is what's specified in the schema), but set to "disabled".
The difference between "disabled" and "readonly," is that the value from a disabled field is normally not submitted. 
Json-editor extracts the result as a json object and doesn't submit in a regular way (at least not the examples) And just changing "disabled" to "readonly" unfortunately doesn't fix the problem as "disabled" state seems to be mixed up with "readonly" several places.

**Comment by pmk65** [comment]
You might be able to create a workaround by watching the pet field, and then turn on the **readonly** mode when it is changed.

**Comment by taschmidt** [comment]
Sorry for the confusion, in my scenario at work it's not a select, just a regular textbox. That select was just the easiest to demonstrate on the demo form. I suppose maybe a good analogy would be a textbox that becomes the key column in a db? We just don't want it to be changed after it's initially set. But it sounds like you're right, that I'll have to handle it with business logic.

**Comment by joshpcausey** [comment]
My solution to this is kind of hacky, but for our internal tool it will work fine.

I wanted a field to be editable only on create, the route for create looked like `https://site.com/stuff/new` while a route for viewing something I don't want to be editable looks like `https://site.com/stuff/id-for-thing`

So I made a variable `const isNew = this.window.pathname.endsWith('/new')` then set readonly based on that.

**Comment by levh** [comment]
> Yeah, I guess the easiest way to adapt the demo to my situation would be to assume that you can't change a pet type once it's initially set. But adding `"readonly": true` to the pet type makes it so you can never set it. See it here:
> 
> https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iBwBDALbxCQgObiQ3IWBkAzIQDcsaKLAD6dLNHVNpObuib668iLiZkwGEAF1CJNFjJpIsewlDCxiUDBSchAMMA0cSSYTDDoNEkhrJAAxLjCAAiFjdIAZIQy/GREIHBzYSLAAC0QAFkITZXZoRiQAKXRYESJ0gBF1PABfCWkA4jJEEBKFaTRo2EbmxAAmAFZCYpwIEXYRRABGAA51oQAPLZ3EAE5LoZBlNQ0FHT0DHzGQsIiowkV1EXkJrp9LNCJAYCF7upNOkgQZ6vMhE0WiAAMSKZQrAAMmJAtyMJlmbyC4yQnxK3xA5QuCAE/zgTEUnSE9IctzkClGxI+4XJDL+AKQ7JkbkSOG8oEU0HkJAgdAA1oTgANlYRzJYkoFghMqLQGEwwfSkDksBZRTZXO5POKQHQoEROVrSTzInMFsiAMpZdLJNBZW2xLC4whheTkTUk0LOikNRGLJAAYQAgkGbXaQxyiY7I185rF4makAAVSoQDDpUvpIzoUPcTLsMBYf6QCzQaDdRSuETpKqwdIuWAqKzsMtgADuWHSiggsGg3HsoM6JClGZAwGAtqCKvSa/TsGVTFH8jo1TeG/tSDVooAdGemLuJperDgr/flSqQLZrVyJkI0L77T8/LImAQiUPSoJQIaKCwHYTDsJsHCwAAkgoIjeOE7CwIQmhoQ6EY6vQjAQeCEyoERH4WugVp4WG7wTGSLqEFSuw0jaAL1FgFKUFwvCECwCQQOBIBYD2sxOLICJIhM3CcUwLBCDJOBtogGF7oQhQ0fRUa4u+MZSTS4YhDJFIaUgADqzIKLMAyssqQA==&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxgAXzIAHGJwDOCANqhOmW6KX4K8yLFEA6hrcqCAWALoWQA&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction
> 
> My desired behavior would be to allow setting the value on a new item until it's saved, then it should be read only.

getting 404 while trying to see the example :|
