### ISSUE TITLE
How to implement Exapnd All and Collapase All

### ISSUE THREAD

**Issue by MahendraBalu** [json-editor/json-editor#215]
I would like to implement Expand All and Collapse All functionalities for UI. So that User does not need to go to individual section to collapse and/or expand.

**Comment by MahendraBalu** [comment]
Thank you.
How can I loop through entire editor form?
Can you please provide sample code to implement?

**Comment by pmk65** [comment]
@MahendraBalu The JSONEditor object contains info about every editor/field in your form.
Try doing a `console.log(editor)` to see what the object contains.

You can loop through the various editor/fields like this:
````javascript
var editor = new JSONEditor(element, options);

editor.on('ready',function() {

  for (var key in editor.editors) {
    if (editor.editors.hasOwnProperty(key)) {
      var ed = editor.editors[key];
      if (['array', 'object'].indexOf(ed.schema.type) !== -1) {
        // your code here
      }
    }
  }

}
````

**Comment by MahendraBalu** [comment]
Thank you for complete implementation.
I am getting following error:
**ed.editor_holder is undefined**

I believe editor_holder  is not defined.

**Comment by pmk65** [comment]
@MahendraBalu I updated the Wiki example. Now it also checks if **ed.editor_holder** exists.

**Comment by MahendraBalu** [comment]
Thank you...it is working fine.
