### ISSUE TITLE
Question: best way to make input field with suggestions 

### ISSUE THREAD

**Issue by tripower** [json-editor/json-editor#219]
Hello

I have now tried to use "watch" but the problem is,
that the field is "readOnly" and if I remove the attribute the "onChange" event
will be fired. So I cannot write a free text in this field
so, is it possible to delete the "onChange" at the input field or
is there a better solution instead of "watch"

thanks in advance 

regards
Klaus

**Comment by pmk65** [comment]
@tripower Have you looked at the Wiki example: [Adding AJAX autocomplete using Typeahead & Bloodhound](https://github.com/json-editor/json-editor/wiki/Adding-AJAX-autocomplete-using-Typeahead-&-Bloodhound) ?

**Comment by tripower** [comment]
hello

thx. I haven not seen this page before
but I found an other solution for me
and solved it by using jquery and autocomplete

regards
klaus
