### ISSUE TITLE
Status and version number?

### ISSUE THREAD

**Issue by roypardi** [json-editor/json-editor#22]
Hi – nice to see this project getting some attention.

I'm confused about the version numbers: the jdorn most recent version is 7.28 - same as the version in the dist folder here. Was this an oversight or am I looking at the wrong branch (or something)?

**Comment by schmunk42** [comment]
Latest version of jdorn is 0.7.28, btw.

I had some issues with PRs and builds in the dist folder, see also https://github.com/json-editor/json-editor/pull/17#issuecomment-370784379

I'd suggest to remove it and only add it for releases.

You might give `develop` a try, but you need to run `npm run build` to create the files in `dist`.

**Comment by loganvolkers** [comment]
We should probably provide some docs in the readme or elsewhere to indicate the state of the various github repositories and npm packages.

Personally I'd like to see this fork release a new version in the `1.0.0` range once it's ready.

**Comment by Syzygy24** [comment]
What's the new npm name gonna be?

**Comment by schmunk42** [comment]
Will be https://www.npmjs.com/org/json-editor/json-editor.
I think we'll start with a bunch of alpha releases, I actually would not incorporate too many changes for 1.0.0
