### ISSUE TITLE
Use 'Selectize' with multiselect array with emuns

### ISSUE THREAD

**Issue by PazzaVlad** [json-editor/json-editor#222]
Is it possible to use Selectize with array with predefined values (enum), something like this: 

```javascript
             tags: {
                type: "array",
                format: "select",
                uniqueItems: true,
                items: {
                  type: "string",
                  enum: ["bold","italic","smallcaps"]
                }
              },
```
Using code above with Selectize, json-editor renders default browser's select box, not Selectize box.

but when i remove:

```js
enum: ["bold","italic","smallcaps"]
```
 json-editor renders Selectize element, as expected.

So it there ability to use Selectize with array with predefined values? 

Thanks for such a great lib!

**Comment by pmk65** [comment]
@PazzaVlad Could you provide a direct link to a live example on [https://json-editor.github.io/json-editor/](https://json-editor.github.io/json-editor/) ?

**Comment by PazzaVlad** [comment]
@pmk65 as far as I can see I can't use Selectize in https://json-editor.github.io/json-editor/ , so l provide example in https://codepen.io/pazzavlad/pen/mQzPaw?editors=1000

**Comment by pmk65** [comment]
@PazzaVlad You are correct. It just displays a regular multi select box.

So the correct display would be a dropdown handled/styled by Selectize?
Like the 2nd example **Single Item Select** on https://selectize.github.io/selectize.js/

There's also another way of setting enum lists, that isn't very well documented in the docs. See this example: https://github.com/json-editor/json-editor/issues/182

**Comment by PazzaVlad** [comment]
> So the correct display would be a dropdown handled/styled by Selectize?
Like the 2nd example Single Item Select on https://selectize.github.io/selectize.js/ 

Year, imho that would expected behavior

> There's also another way of setting enum lists, that isn't very well documented in the docs. See this example: #182
thanks. I tried use enumSource, but seems like selectize ignores this object and doesn't show enums at all...

**Comment by pmk65** [comment]
@PazzaVlad 
> 
> 
> > So the correct display would be a dropdown handled/styled by Selectize?
> > Like the 2nd example Single Item Select on https://selectize.github.io/selectize.js/
> 
> Year, imho that would expected behavior

Im not so sure after all. I think It should be like this one, this makes more sence, and you can multiselect. https://codepen.io/i_cant_rap/pen/qNdXyj 
(I can't see a way to do that on the dropdown example)

> > There's also another way of setting enum lists, that isn't very well documented in the docs. See this example: #182
> 
> thanks. I tried use enumSource, but seems like selectize ignores this object and doesn't show enums at all...

Seems like they both triggers the selectize engine, so the bug is the same no matter which option you use.

**Comment by pmk65** [comment]
I did some more debugging and with your codepen example, the 1st field uses "multiselect" editor and the 2nd field uses the "arraySelectize" editor.
From what I can see, the "multiselect" editor currently doesn't contain any code for the "selectize" plugin, only for the "select2" plugin.

**Comment by pmk65** [comment]
@mneofit You seem to be using `Selectize` and have a good grasp on how JSON-Editor works, so maybe this is something you could take a look at? (If you got the time 😁)

**Comment by mneofit** [comment]
It does not documented, as a workaround you could move `enum` property into parent object as following:
```
             tags: {
                type: "array",
                format: "select",
                uniqueItems: true,
                enum: ["bold","italic","smallcaps"],
                items: {
                  type: "string"
                }
              },
```
It would be rendered with `selectize` and treated `enum` as `default`. 
Anyway, according to docs `enum` property should be in `items` and when enabling selectize it is expected to render all select control with `selectize`. I will take a closer look.
