### ISSUE TITLE
Support conditionals (if, then, else)

### ISSUE THREAD

**Issue by danielreus** [json-editor/json-editor#224]
In the draft for version 7 of the JSON schema specification (https://json-schema.org/draft-07/json-schema-validation.html#rfc.section.6.6), keywords for implementing conditionals are introduced. Is it planned to implement this any time soon? Or does it seem feasible that I (experienced developer, unfamiliar with the json-editor codebase) would implement this?

My use-case is simple (and I'd expect quite common): I need some sort of 'typing' in my JSON data. Meaning that the schema of some elements is basically dependent on the value of some field (like 'type' or 'class'). Are there any other suggestions to implement this?

**Comment by schmunk42** [comment]
PRs are highly welcome, tests would also be good for the feature you describing. I also thought about supporting newer versions of JSON schema, which would be pretty cool.

In fact, most of the current maintainers are not fully familiar with the code-base, since we just took over the project :wink: at least I consider myself more a steward than a developer.

CC: @pmk65

**Comment by pmk65** [comment]
@danielreus The Wiki is a good place to start. It describes the relation/function of the various classes.

**Comment by danielreus** [comment]
I got my use-case working using the existing oneOf functionality, as demonstrated in the [Advanced usage example](http://rawgithub.com/json-editor/json-editor/master/docs/advanced.html). For me this takes away the direct need for conditionals. Guess I should have read the docs more thoroughly. Expect to be opening PR's and issues for some other nice little enhancements though :)

**Comment by jfbrennan** [comment]
So there is a desire to update to json schema 7, but no current plans to do so? Is that correct?

**Comment by schmunk42** [comment]
@jfbrennan Yes.

**Comment by pmk65** [comment]
@jfbrennan We could use some extra maintainers, So if it's something you are interested in adding, feel free to create a PR. 😃

**Comment by coderofsalvation** [comment]
> NOTE: the oneOf seems to allow conditional rendering.
However, I've noticed custom validators to act funny: `editor.validate()` will result in 0 errors even when custom validators return an error. I guess its due to the nested nature.
