### ISSUE TITLE
How to control Form-UI based on Schema

### ISSUE THREAD

**Issue by MahendraBalu** [json-editor/json-editor#225]
How to set/control the no. of fields to be display in each row for 'object' type schema. Schema have various 'object' type schema and need to display different no. of fields in each section differently.

currently, editor is displaying randomly 2 or 3 fields on each row. 

```

**Comment by pmk65** [comment]
@MahendraBalu I suggest you read the documentation more closely (Try searching for grid and grid_columns) and/or dig into the codebase. There are also several examples in the "docs/" folder.
You are also welcome to make a PR and update the documentation if you find it inadequate. 😉

**Comment by schmunk42** [comment]
Grid and grid columns were buggy when I tried to use them the last time AFAIR.
But it would be great to have a test-case.

**Comment by MahendraBalu** [comment]
I am able to figure out by setting Grid_Columns options for each property under object. Editor is creating 4 columns per rows by setting grid_columns =2 for each properties of object.

However, grid_columns=2 does not work at editor options level to display 4 columns split per rowvat Schema level.

**Comment by pmk65** [comment]
> 
> 
> Grid and grid columns were buggy when I tried to use them the last time AFAIR.

Probably related to #214 As there would be a lot of nested grid rows.

**Comment by pmk65** [comment]
> 
> 
> I am able to figure out by setting Grid_Columns options for each property under object. Editor is creating 4 columns per rows by setting grid_columns =2 for each properties of object.
> 
> However, grid_columns=2 does not work at editor options level to display 4 columns split per rowvat Schema level.

grid_columns=12 = full width
grid_columns=6 = half width
grid_columns=3 = quarter width

**Comment by schmunk42** [comment]
I recently played around with this, also. What I found weird is that certain column width definitions seem to change the order of the fields, it looked like "some algorithm" was optimizing the layout.
