### ISSUE TITLE
Date is not getting display on UI

### ISSUE THREAD

**Issue by MahendraBalu** [json-editor/json-editor#227]
API is sending date in the following format "YYYY-MM-DDTHH:MM:SSZ" (Example :"2017-12-01T00:00:00Z")
Display Format Date on UI is MM/DD/YYY (e.g. 12/01/2017). 

I am using flatpickr so that user can select the date. Value is not per-populated to UI.

Schema 
"dob": {
                    "$id": "#/properties/dob",
                    "type": "string",
                    "title": "Date of Birth",
                    "default": "",
                    "examples": [
                        "10/08/1979"
                    ],
                    "format": "date",            
                    "options": {
                        "grid_columns": 2,
                        "flatpickr": {
                            "inlineHideInput": true,
                            "wrap": true,
                            "allowInput": true
                          }           
                    }
                }

**Comment by pmk65** [comment]
If you use a different date/time format, you need to [configure Flatpickr](https://flatpickr.js.org/examples/#human-friendly-dates) to use that format.

**Comment by MahendraBalu** [comment]
I tried..But it did not work for me. 
It would be great if you can share an example for the same.

**Comment by MahendraBalu** [comment]
I was looking the code for datetime.js. I notice that setValue function is not setting the value if  schema type = "string" for date.

can you  pls let me know if I am missing anything?

setValue: function(value, initial, from_template) {
    if (this.schema.type == 'string') {
      this._super(value, initial, from_template);
    }
    else {
      var dateValue, dateObj = new Date(value * 1000),
          year = dateObj.getFullYear(),
          month = this.zeroPad(dateObj.getMonth() + 1),
          day = this.zeroPad(dateObj.getDate()),
          hour = this.zeroPad(dateObj.getHours()),
          min = this.zeroPad(dateObj.getMinutes()),
          sec = this.zeroPad(dateObj.getSeconds()),
          date = [year, month, day].join('-'),
          time = [hour, min, sec].join(':');

      if (this.schema.format == 'date') dateValue = date;
      else if (this.schema.format == 'time') dateValue = time;
      else dateValue = date + ' ' + time;

      this.input.value = dateValue;
    }
},

**Comment by MahendraBalu** [comment]
I tried to pr-load the date in the startval uisng https://json-editor.github.io/json-editor/. Demolink also did not pre-populate the date.
can you please provide your insight.

**Comment by pmk65** [comment]
> 
> 
> I was looking the code for datetime.js. I notice that setValue function is not setting the value if schema type = "string" for date.
> 
> can you pls let me know if I am missing anything?
> 
> setValue: function(value, initial, from_template) {
> if (this.schema.type == 'string') {
> this._super(value, initial, from_template);
> }

The datetime editor extends the string editor, and by calling this.super() it will call the code from the strings editor. So that's why you don't see any code setting the value there.

You can set the default values in the schema like this:
````javascript
        "fsdate": {
          "type": "string",
          "format": "date",
          "title": "Date (String)",
          "description": "Standard date field with flatpickr",
          "default": "2018-12-19",
          "options": {
            "grid_columns": 4,
            "placeholder": "Enter date",
            "flatpickr": {
              "wrap": true,
              "allowInput": true
            }
          }
        },
        "fidate": {
          "type": "integer",
          "format": "date",
          "title": "Date (Integer)",
          "description": "Integer date field with flatpickr",
          "default": 1545091200,
          "options": {
            "grid_columns": 4,
            "placeholder": "Enter date",
            "flatpickr": {
              "wrap": true,
              "allowInput": true
            }
          }
        }
````

Or from JavaScript like this:
````javascript
  var element = document.getElementById('form');
  var editor = new JSONEditor(element, options);

  // Set value on stringdate field
 var ed = editor.getEditor("root.fsdate");
 ed.setValue("2018-12-19");

  // Set value on integer date field
  var edi = editor.getEditor("root.fidate");
  edi.setValue(1545091200);
````

**Comment by pmk65** [comment]
> 
> 
> I tried to pr-load the date in the startval uisng https://json-editor.github.io/json-editor/. Demolink also did not pre-populate the date.
> can you please provide your insight.

Demo editor is missing the external libraries like Flatpickr. i have opened an issue (#228) for that problem.
