### ISSUE TITLE
Add external libs to Interactive Demo

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#228]
Currently, it's not possible to test editors like Flatpickr, SCEditor etc. due to the external library is not present at the interactive demo at https://json-editor.github.io/json-editor/

I think we need to include ALL the external libraries on the demo page, so that all possible scenarios can be created/tested.

But I'm not sure if I have write access to the file myself (or where the file is located 😁)
 
Maybe the Interactive Demo source could be moved to the docs/ folder?

```

**Comment by schmunk42** [comment]
@germanbisurgi Can you have a look?

**Comment by pmk65** [comment]
Since there wasn't any response from @germanbisurgi I took the liberty of updating it myself in #238. 😜
