### ISSUE TITLE
json editor  uisng Angular 4 or 5

### ISSUE THREAD

**Issue by MahendraBalu** [json-editor/json-editor#230]
I would like to know what are the thinks needs to be consider  to use editor using angular 4 or 5

please share an example using angular if anyone has it

**Comment by pmk65** [comment]
Have you looked at the Angular issues https://github.com/json-editor/json-editor/issues?utf8=%E2%9C%93&q=angular
I know the examples are for Angular 2, but maybe it's similar in newer versions? (I have no Angular experience myself, so I can't help you.)

**Comment by martin-g** [comment]
The example in https://github.com/json-editor/json-editor/issues/127 works fine for Angular 8.
