### ISSUE TITLE
EpicEditor or SimpleMDE?

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#233]
@schmunk42 The documentation refers to **EpicEditor** as the editor for editing Markdown code. But the source has no reference to **EpicEditor** and examples use **SimpleMDE** for Markdown editing.

So is the **EpicEditor** references some leftovers from the original version? 
And should it be replaced with **SimpleMDE** info?

**Comment by schmunk42** [comment]
> So is the EpicEditor references some leftovers from the original version?

I think so.

> And should it be replaced with SimpleMDE info?

Yes, from what you've written.

Don't some "plugins" just replace/use the existing DOM-code? Can EpicEditor be used without any additional configuration?

**Comment by pmk65** [comment]
I just compared the original code with the current version. And the original has code for setting up EpicEditor, which has been removed in the current version. (Makes sense as there's no need to have 2 Markup editors)
With SimpleMDE you just include the lib and Markdown is available. So we should update the documentation.

**Comment by pmk65** [comment]
Fixed in #238
