### ISSUE TITLE
Editor silently accepts invalid input

### ISSUE THREAD

**Issue by dreusel** [json-editor/json-editor#239]
### Expected behavior
When I editor.setValue() a JSON document that does not validate according to the current schema (and for which editor.validate() also actually returns errors), I expect the editor to display the validation errors.

### Actual behavior
For many classes of 'invalid' in put, the editor just accepts the input without displaying (or returning) any validation errors. For other classes of validation errors, it does correctly display the errors on loading the data.

#### Not working: Trivial object schema (object with no properties declared), no_additional_properties set to true, setValue({"a": "x"}):
```javascript
{
  "type": "object",
  "properties": {}
}
```
https://rawgit.com/json-editor/json-editor/master/docs/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCwAvnUAAA=&value=N4XyAA==&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&no_additional_properties

```javascript
jsoneditor.setValue({x: 'y'})
> ...
jsoneditor.validation_results
> []
jsoneditor.validate({x: 'y'})
> [
  {
    "path": "root",
    "property": "additionalProperties",
    "message": "No additional properties allowed, but property x is set"
  }
]
```
#### Not-working: not matching simple enum that is required
```javascript
{
	"type": "object",
	"properties": {
		"x": {"type": "string", "enum": ["a"]}
	},
	"required": ["x"]
}
```
https://rawgit.com/json-editor/json-editor/master/docs/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoAHreNHIlWIeQHYDmeIMnAK4BbBAG0QAQxABdAL5z8hGAEdB5ZQBNxIBvKAAA&value=N4IgHiBcIIYgvkAA&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&no_additional_properties

```javascript
jsoneditor.setValue({x: 'y'})
> ...
jsoneditor.validation_results
> []
jsoneditor.validate({x: 'y'})
> [
  {
    "path": "root.x",
    "property": "enum",
    "message": "Value must be one of the enumerated values"
  }
]
```

#### Working: not-matching simple enum that is not required
However, when the property is not required, a validation error is correctly displayed:
```javascript
{
	"type": "object",
	"properties": {
		"x": {"type": "string", "enum": ["a"]}
	}
}
```
https://rawgit.com/json-editor/json-editor/master/docs/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoAHreNHIlWIeQHYDmeIMnAK4BbBAG0QAQxABdAL4KgA==&value=N4IgHiBcIK4HYBMCmAzAlnJCQF8gAA==&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&no_additional_properties

**Comment by danielreus** [comment]
The combination of these things sometimes causes the wrong 'oneOf' option to be selected:
https://rawgit.com/json-editor/json-editor/master/docs/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaZAdjAPIBmCA2qGAJZgA2ciAhniFAE5Kwe0wDOCUAA8h4aExD8wHGgQDmbGAQCuAW0ohWAXQC+u/BxgBHFTSMATTaO35IsBMnRYcB6nUaOUbTtxi8aATFReGoJR2lZBSVVDXgKEG89AxAjU3MYK3iQGztwxFQMbBBdPSA&value=N4IgHiBcIIYgvkAA&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&no_additional_properties
Validation silently fails for both options because of the extra un-allowed property 'y', causing the default/first 'oneOf' option to be selected, which also invalidates the enum, but still no validation error is displayed

**Comment by pmk65** [comment]
> 
> When I editor.setValue() a JSON document that does not validate according to the current schema (and for which editor.validate() also actually returns errors), I expect the editor to display the validation errors.

@dreusel How and if the editor displays errors are controlled by the `show_errors` property. in your live example links it is set to "interaction", which means it only triggers the error messages when you enter something into the form manually. Try changing it to "always" and see if that doesn't help.

**Comment by schmunk42** [comment]
no further feedback -> closing
