### ISSUE TITLE
Use CSS instead of hardcoded styles 

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#240]
Any reason why this [PR](https://github.com/jdorn/json-editor/pull/346/files) from the original repo, hasn't been included in the current release?
Seems like a good idea to get rid of inline CSS. And it would make it easier for people to restyle the form elements.

I don't like the use of uppercase in selector names, and there are a couple of minor issues in the PR, like changing the "row" classname. But that shouldn't be that hard to clean up.

**Comment by schmunk42** [comment]
I can't remember a particular reason why not, feel free to proceed with this - I totally support such a change. Maybe even texts and icons should be added via CSS (LESS/SASS).

**Comment by pmk65** [comment]
@zwerdlds Looks good. But I think we should prefix the JSON-Editor classnames with something like "**jse-**". That way you know it's a specific JSON-Editor style. (Note: Some classes, like "**row**" must not have prefixes, as it is used by frameworks)

1) I totally agree. The H* tags should not be used for the GUI.

Note: classList.add() accepts multiple arguments, so something like this:

````javascript
  tooltip.classList.add('tooltip');
  tooltip.classList.add('info');
  tooltip.classList.add('disabled');
````
Can be cut down to:

````javascript
  tooltip.classList.add('tooltip', 'info', 'disabled');
````

**Comment by zwerdlds** [comment]
pmk - agreed on all points.  thanks for the classlist tip.  I hope to get to this today.

**Comment by zwerdlds** [comment]
I have submitted pr #253 in support of a fix for this issue.  @pmk65 - I'm not aware of which classes are used by the frameworks, so that is not yet resolved.

**Comment by pmk65** [comment]
New 2.x themes now uses Style Rules
