### ISSUE TITLE
Mustache / JsonEditor not rendering HTML in template

### ISSUE THREAD

**Issue by theBull** [json-editor/json-editor#244]
### Expected behavior
When specifying Mustache as the template engine, it is possible to specify a `template` or `headerTemplate` with HTML that Mustache will render if the variable is specified with [triple curly brackets](https://github.com/janl/mustache.js#variables). Mustache should return the HTML string as a non-escaped HTML string that can then be injected into the page and rendered properly as HTML, with the appropriate CSS applied to it.

### Actual behavior
Mustache seems to be doing its part in returning the correct HTML string `<i class='glyphicon glyphicon-transfer'></i>`, but the JSONEditor is rendering it as an actual literal string **`<i class='glyphicon glyphicon-transfer'></i>`** rather than rendering it as an icon with the proper CSS applied. Inspecting Element, I can see the that HTML is injected as a String, not as HTML.

### Steps to reproduce the behavior
1. Define JSONEditor and specify a template engine to use for it.
2. Define a template view to be used by Mustache when it renders variables.
3. Specify a schema that specifies a triple-curly brace Mustache variable in the `headerTemplate` property.
```
// define a template view to give to the template engine so that mustache will render {{{icon_html}}} as the HTML defined here
var _TEMPLATE_VIEW = {
    "icon_html": "<i class='glyphicon glyphicon-transfer'></i>"
  };

// define a template engine which uses Mustache to render the template as defined above
var _TEMPLATE_ENGINE = {
    compile: function(template) {
      // Compile should return a render function
      return function(vars) {
        // hook into the mustache rendering engine
        Object.assign(_TEMPLATE_VIEW, vars);
        return Mustache.render(template, _TEMPLATE_VIEW);
      }
    }
  };

// Specifies options for the JSONEditor
  var _EDITOR_OPTIONS = {
    theme: 'bootstrap3',
    iconlib: 'bootstrap3',
    template: _TEMPLATE_ENGINE,
    display_required_only: true,
    ajax: true,
    keep_oneof_values: false,
    show_errors: "always",
    schema: {
      $ref: CONFIG.getEditorSchema()
    }
  };

var _EDITOR = new JSONEditor($editor[0], _EDITOR_OPTIONS); 

// schema
{  
  "title": "Output",
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "headerTemplate": "{{#self.destination.overwrite}}{{{icon_html}}} {{/self.destination.overwrite}} {{self.destination.id}}.{{self.destination.field}}",
  "required": ["destination"],
  "properties": {
    "source": {
      "type": "string",
      "format": "text",
      "propertyOrder": 1
    },
    "values": {
      "type": "array",
      "propertyOrder": 10,
      "items": {
        "oneOf": [
          {"type": "boolean"},
          {"type": "string"},
          {"type": "null"},
          {"type": "number"}
        ]
      }
    },
    "destination": {
      "propertyOrder": 20,
      "$ref": "./destination.json"
    }
  }
}
```

**Comment by pmk65** [comment]
@theBull You will probably have to override the **updateHeaderText()** function, as it only inserts textnode values.

**Comment by theBull** [comment]
Thanks @pmk65

**Comment by taschmidt** [comment]
@theBull Did you ever get this working? I'm running into the same thing and overriding an internal function doesn't seem like the safest thing.

**Comment by pmk65** [comment]
> 
> 
> @theBull Did you ever get this working? I'm running into the same thing and overriding an internal function doesn't seem like the safest thing.

@taschmidt There's no problem with overriding the existing functions. It's pretty much the same as creating a custom build, except you don't have to create a new build every time the main script is updated.

Here's an example of overriding the sanitize() function for integers.
https://github.com/json-editor/json-editor/issues/133

And as the **updateHeaderText()** function, inserts the data using **textContent**, you WILL have to modify that if you want to be able to insert HTML.

You are welcome to create a PR if you get it to work with both text and HTML 😉

**Comment by taschmidt** [comment]
@pmk65 Thanks for the response! It works, kind of. At the top level, I have an array of objects. The array format is set to 'tabs' and it's the header of those array tabs that I'm trying to set.  I tried overriding array and object but neither seem to be called in my scenario. Any ideas?

**Comment by pmk65** [comment]
@taschmidt I think it is some functions in objects.js you will have to modify.
Try opening up src/objects.js and search for "getHeaderText" and see if the content is applied using "textContent". If they do, try changing it to innerHTML as in the above example.

**Comment by taschmidt** [comment]
So, it looks like for the array tabs, I had to override `JSONEditor.defaults.editors.array.prototype.refreshTabs` but that didn't fix the title shown on the editor when clicking on an array item (which is a complex object).  After a while debugging, it looks like it gets set in `JSONEditor.AbstractEditor.prototype.updateHeaderText`. But simply changing [this  line](https://github.com/json-editor/json-editor/blob/b14f4d8a83c9c4a8191ef811a44e9d1d957c18fc/src/editor.js#L374) from textContent to innerHTML causes my header to be blank. I've kind of decided this isn't worth the effort and given up.

**Comment by theBull** [comment]
Hey guys - sorry my activity on this (and other) issues has been limited. @taschmidt I did not get it working and just put some plain text in instead. Overriding the method sounds like a perfectly reasonable approach, I personally wouldn't be too worried about it...just be careful when pulling in the latest version of json editor at a minimum.

**Comment by pmk65** [comment]
With current release you can now use HTML tags in header&title and description if DOMPurify library is loaded.
