### ISSUE TITLE
Suggestions for format of fields?

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#247]
There's currently changes to update output so it is easier to style and include things like placeholders.

Something else that might be useful is a way to define and format information.

I'm not sure the base JSON Schema specification goes into this but it becomes a necessity of presenting forms.

What's a suggestion for doing formatting of input fields? I'm thinking things like decimals, thousand separators, currency indicators, percentages, credit-card formats, date fields (like the MM/YY of a credit card), etc.

**Comment by pmk65** [comment]
@eduo The easiest way would be to use a 3rd-party library, like [Cleave.js](https://nosir.github.io/cleave.js/) 
Shouldn't be that hard to implement directly into JSON-Editor, so you can configure it through "options".
(Take a look at how the [datetime editor](https://github.com/json-editor/json-editor/blob/master/src/editors/datetime.js) includes the 3rd-party library [Flatpickr](https://flatpickr.js.org/) and how the options are passed)

Feel free to make a PR if you want.

**Comment by schmunk42** [comment]
Closing, since cleave support is merged.
