### ISSUE TITLE
UMD default export

### ISSUE THREAD

**Issue by loganvolkers** [json-editor/json-editor#25]
This library is currently exported using:
```
 window.JSONEditor = JSONEditor;
```

This makes it incompatible with build systems like Webpack and Rollup.

Instead the library should be exported as a UMD module, so that it can be properly released to NPM.

Note: UMD modules should mostly maintain backwards compatibility with export a global object on the window, but it may break some things. Because of this, if we include this change, it should result in a version bump to keep our releases in line with Semver.

**Comment by SyedWasiHaider** [comment]
For anyone else who had issues with this:

```npm install  @json-editor/json-editor ```

then in your file

```
require ('@json-editor/json-editor') 
bla = new window.JSONEditor(bla, bla)
```
