### ISSUE TITLE
Remove item in array by editing JSON directly doesn't trigger change event

### ISSUE THREAD

**Issue by ittus** [json-editor/json-editor#262]
### Expected behavior
Remove item in an array by editing JSON directly should trigger `change` event

### Actual behavior
`change` event is not triggered

### Steps to reproduce the behavior

1. Go to demo page (https://rawgit.com/json-editor/json-editor/master/docs/demo.html)
1. Add 1 pet by clicking on Add button, `JSON Output` on the right side will be updated respectively 
1. Clicking on `JSON` button to edit json directly, delete new adding item
1. JSON form is updated correctly, but `JSON Output` is not updated

Screenshot
![on_change](https://user-images.githubusercontent.com/5120965/50803973-63302100-132f-11e9-9c7e-c25a8dbd4106.gif)

**Comment by pmk65** [comment]
@ittus I don't think it's possible. As when you delete the item, it's no longer present in the list of editors and can't trigger the onchange event.

**Comment by schmunk42** [comment]
Shouldn't the whole data be updated, when clicking `Save`?

**Comment by ittus** [comment]
@pmk65 I think whole data should be immutable and trigger `change` when anything updated.

**Comment by pmk65** [comment]
@ittus I think I found the problem. I'll submit a PR that should fix it.

**Comment by schmunk42** [comment]
Should be fixed in #274
