### ISSUE TITLE
A way to load large JSON array

### ISSUE THREAD

**Issue by Fluf22** [json-editor/json-editor#263]
### Expected behavior

JSONEditor to load quickly

### Actual behavior

JSONEditor can take up to three minutes to load a 10000 lines JSON file with nested arrays

### Steps to reproduce the behavior

Use an abnormally large JSON file with a lot of arrays

I did a fix to make JSON Editor load this kind of file quickly. I just display the first item of the array (if you use `format: "tabs"` or `format: "tabs-top"`). Not using formatting results in using the old way of loading array.
The big downside of this fix is the inability to use the `watch` keyword, since all the data are cached, and not really loaded...

Ideas and improvments are welcome !

Thanks,
Thomas

**Comment by pmk65** [comment]
Duplicate of #252
Maybe you can team up with @j2jensen and come up with a good solution.

**Comment by schmunk42** [comment]
Closing as duplicate
