### ISSUE TITLE
Include a custom icon font

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#265]
It is possible to create a custom iconset, containing only the icons needed for the buttons using [fontello](http://fontello.com/)
We could create such a fontset and include it into the dist (Then it can be accessed through CDN)

With Fontello you can combine icons from several fontsets and include your own designs too.
And it is possible to rearrange/rededesign the fontsets again if needed.

**Comment by yanyeAbbr** [comment]
Now bootstrap4 has no icon, what to do

**Comment by pmk65** [comment]
@yanyeAbbr Hard to say, judging from the information you provided.
You need to be more elaborate on the problem and/or post an example.
