### ISSUE TITLE
Add dist files to cdnjs

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#268]
Right now there is only the old [jdorn](https://cdnjs.com/libraries/json-editor) 0.7.28 version available.

[cdnjs](https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url%28optional%29%3A**%20%0A**License%28s%29%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20README.md%20and%20CONTRIBUTING.md%20document%20first.%0A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!)

**Comment by schmunk42** [comment]
I am against this, we should not apply to even more CDNs actively.
It causes too many problems we can't foresee.

**Comment by pmk65** [comment]
> 
> 
> I am against this, we should not apply to even more CDNs actively.
> It causes too many problems we can't foresee.


What kind of problems?

If you use a site like https://jsfiddle.net/ or https://codepen.io for creating an example, they have an option to select libraries from CDN (but ONLY from CDNJS).
So if you do that, you end up with the old jdorn release. (To use a library from a different CDN, you'll have to manually enter the full url.)
So CDNJS seems to be more widely used than other CDN services.

**Comment by schmunk42** [comment]
> What kind of problems?

This:

> We are probably going to change the URLs on the readme.MD page soon, due to rawgit closing down in less than a year. See https://rawgit.com/
So we would also need to create a Github page soon. See: https://pages.github.com/

For example :)

**Comment by pmk65** [comment]
That's not exactly a cdn problem, but more a problem of hosting/showing non-dist files like the HTML examples/demo. And this would be solved by creating a Github page. 
Currently, we only use rawgit for linking to the HTML examples and interactive demo and not for CDN use.

**Comment by schmunk42** [comment]
`gh-pages` would be a good option I think.

**Comment by schmunk42** [comment]
Files are taken from the docs folder

![bildschirmfoto von 2019-01-13 17-35-44](https://user-images.githubusercontent.com/649031/51087921-c370f980-1759-11e9-8b5b-31141eda06dd.png)

I always thought they'd taken from a `gh-pages` branch

**Comment by pmk65** [comment]
Great then we can build a index page with access to the various demos and examples,

**Comment by schmunk42** [comment]
While thinking about it...
I'd recommend a separate repo for that ... We'd bloat this repo with dist versions over and over - we're actually doing this on the release branch already.

Now that I am writing about it ... is that really something that we need? Or shouldn't we simply keep things just as they are.

**Comment by pmk65** [comment]
We will need it if we want the readme.md to link to the examples and interactive demo. As rawgit is closing down.

**Comment by schmunk42** [comment]
What's about moving these to jsdelivr.com? 
Sure, also external, but would it work?

I just double checked it, there are no dist files in the releases, they are only uploaded to npm.

**Comment by pmk65** [comment]
> 
> 
> What's about moving these to jsdelivr.com?
> Sure, also external, but would it work?
> 

That should work too I guess since all files from the repo are pushed to jsdelivr.com.
The only difference is that updating or adding new demos/examples would require a release. 
Using the github page we would be able to do it without a release as it links directly to the files on the repo.

**Comment by schmunk42** [comment]
> Using the github page we would be able to do it without a release as it links directly to the files on the repo.

But then we'd have to have dist files for every commit in the repo. Please NOT :)
If you really need master, you have to be able to figure out how to use it.

Using `@latest` from jsdelivr looks good to me.

**Comment by skewty** [comment]
API level (not sales level) docs are tightly coupled to code and in the team I work in at least, should be stored together to ensure there is as little friction as possible keeping them both in sync.  Just my 2c.

**Comment by schmunk42** [comment]
I am closing this, please reopen or drop a note if there's still an issue.

**Comment by schmunk42** [comment]
@pmk65 I just noticed that this URL https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js - still delivers 1.3.2 - any idea why?

**Comment by pmk65** [comment]
@schmunk42 Try refreshing the link. That worked for me. I see 1.3.3.
And this version it's correctly minified too. (1.3.2 had a lot of comments still present in the minified version)
