### ISSUE TITLE
integer type enum in JSON Editor always returns 1

### ISSUE THREAD

**Issue by ShuminY** [json-editor/json-editor#270]
I expected the dropdown list will give the value which was selected.

but it always gives value "1".

I put below in the json file schema  "editor.json" 
"platformType": {
            "type": "integer",
            "title": "platform",
            "enumSource": [
                {
                    "source": [
                        {
                            "value": 1,
                            "title": "ele"
                        },
                        {
                            "value": 2,
                            "title": "mt"
                        }
                    ],
                    "title": "{{item.title}}",
                    "value": "{{item.value}}"
                }
            ]
        },
 
and in the html page, I init an editor instance with this json file
var editor = new JSONEditor(...){
    schema: {
                        $ref: "editor.json",
    ...
    }
}

and then try to get the value by the editor:
editor.getValue();

The integer enum one defined above always give value 1 no matter which one I select from the dropdown list.

Any idea how to resolve this issue? Many thanks!

```

**Comment by pmk65** [comment]
@ShuminY It's clearly a bug as there are no problems if the format is "string".

I think I have found the problem. (enum_values are stored as string values, so the indexOf() function won't match the integer values with those. And as a result, it returns the 1st enum_value)

Try adding this before initializing the editor. This will override the default onInputChange function. (Changes the indexOf() lookup value to always be in string format)

If it works for you, let me know and I'll make a PR.

````javascript
JSONEditor.defaults.editors.select.prototype.onInputChange = function() {
    var val = this.typecast(this.input.value);

    var new_val;
    // Invalid option, use first option instead
    if(this.enum_values.indexOf(String(val)) === -1) {
      new_val = this.enum_values[0];
    }
    else {
      new_val = this.enum_values[this.enum_values.indexOf(String(val))];
    }

    // If valid hasn't changed
    if(new_val === this.value) return;

    this.is_dirty = true;

    // Store new value and propogate change event
    this.value = new_val;
    this.onChange(true);
  }
``

**Comment by pmk65** [comment]
The fix seems to work, but the Travis tests fail. So maybe it has to be fixed at a higher level?
