### ISSUE TITLE
Time value set when editor is instantiated is not updated in flatpickr editor

### ISSUE THREAD

**Issue by 13BTurbo** [json-editor/json-editor#276]
### Expected behavior
Instantiate an editor using a setvalue field in the options object.
Initial values are populated into the input fields and everything looks correct.
Click the input and the flatpickr time editor appears and allows one to adjust the time from the existing value.

### Actual behavior
Click the input and the flatpickr time editor appears and the time jumps to 12:00.

### Steps to reproduce the behavior
https://jsfiddle.net/8a7g4w91/4/

**Comment by pmk65** [comment]
@13BTurbo You can set it using "defaultHour" and "defaultMinute".
I'll see if it's possible to set those by default if startval" is set.

**Comment by 13BTurbo** [comment]
Thanks, this fixed the issue for me.
