### ISSUE TITLE
Submit JSON as a string instead of a property array

### ISSUE THREAD

**Issue by DODMax** [json-editor/json-editor#281]
### Expected behavior
When submitting the form in which the editor is included, I would like to receive the JSON object as a string.
### Actual behavior
I receive an object in the form root[person][name].

Thanks for the help!

**Comment by pmk65** [comment]
Just pass the result through the [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) function.

**Comment by DODMax** [comment]
Thanks, I ended up using a hidden field to store the string value
```
editor.on('change', function() {
    var json = editor.getValue();
    var form = document.getElementById("form_id");
    form.hidden_field.value = JSON.stringify(json);
});
```
