### ISSUE TITLE
Newer versions fail to transpile with Babel/Webpack/Vue

### ISSUE THREAD

**Issue by Dids** [json-editor/json-editor#283]
### Expected behavior

Should transpile just fine in a Babel/Webpack/Vue project, with production enabled.

### Actual behavior

Fails to transpile in production with the following error:  
```
js/chunk-7db5f12b.8d6e7ccc.js from Terser
Unexpected token: name (protected) [./node_modules/@json-editor/json-editor/dist/jsoneditor.js:2041,0][js/chunk-7db5f12b.8d6e7ccc.js:15619,31]
```

### Steps to reproduce the behavior

Create a new Vue.js project with `vue-cli`, in my case I'm also using TypeScript, then add `@json-editor/json-editor` as a direct dependency, finally build the project in production with `vue-cli-service build --mode production`.

### Notes

Building/transpiling works fine if the environment is anything other than production. Additionally, version `<=1.2.1` of `json-editor` also works perfectly fine.  
This issue only seems to occur starting at version `1.3.0`, all the way up to the latest version (`1.3.2`).

I'm not sure if this is an issue with the `json-editor` per se, but I've been unable to find a workaround, other than downgrading. Also, from what I could find on Google, it _seems_ to be an issue related to UglifyJS and >ES5 code, as UglifyJS expects ES5 and not above.

**Comment by pmk65** [comment]
This was fixed in #266, but a new release (1.3.3) hasn't been made yet.

**Comment by marc7000** [comment]
New release (1.3.3) is available...

**Comment by Dids** [comment]
Version 1.3.3 fixes this, thank you!
