### ISSUE TITLE
0 in an array is parsed into null

### ISSUE THREAD

**Issue by stultusstudio** [json-editor/json-editor#285]
### Expected behavior

I'm running into a crucial issue where if I enter this JSON, the "0" in the array turns into null. The expected behavior is that it should remain a "0" and be of type number, as opposed to type null. This appears to be related to #159.

### Actual behavior

What actually happens is the the "0" gets turned into a null.

### Steps to reproduce the behavior

Simply go to the demo here: https://rawgit.com/json-editor/json-editor/master/docs/demo.html

Paste in the JSON below, and click update form. You'll find that the 0 has been parsed into null.

```javascript
{ "array": [ 2, 0, 1 ] }
```

**Comment by schmunk42** [comment]
Example: https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iAC2WahGRoswyLgBCAQxw50AWREQAkjm6wAHiAC6hEhLJpIsDIlDDR4yVmk55ilWs3a9CUGFLkQctDQ5IiYoWEFLL2IyfhAcdkFKdAMAXzSUoA==&value=N4Igtg9gVglgCgJwpALjCA7AQgQwxgUwQFloYBJDAEwIA8QAuAbQCYAaDAVwBtu2BGALoBfIA===&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by pmk65** [comment]
Try calling `setValue()` a 2nd time. that seems to set the correct types/values.

**Comment by stultusstudio** [comment]
This workaround works for me.

**Comment by stultusstudio** [comment]
However, if we use a more complex JSON object that has this array nested inside, then the work around has no effect.

```javascript

{   "IsForwardMojiFromContextualMenuEnabled": true,   "PickerContentUpdate.enabled": true,   "SendMojiOnLongPressInRoster.enabled": true,   "ShowMojiTitleInRosterGroupingInt": 2,   "exp_expressionStoreEnabled": true,   "exp_socialShareButtonEnabled": true,   "exp_socialShareMenuEnabled": true,   "exp_thumbnailBlackListCopyright": [     "Universal"   ],   "expressionStoreEnabled": {     "enabled": true   },   "mediaBarPersonalExpressionEntryPointEnabled": true,   "mojiForwardButtonEnabled": true,   "mojiPromotionBannerMojiIndex": [     2,     0,     1   ],   "mojiQuickSendButtonOnSideEnabled": false,   "mojiQuickSendFromRosterPreviewEnabled": true,   "mojiReplayFromPreviewEnabled": true,   "mojiTitlesInPickerEnabled": true,   "searchButtonEnabled": true,   "showMojiPromotionBanner": true,   "testNest": {     "nestedProp": {       "test": "hello World"     }   } }
--



```

**Comment by pmk65** [comment]
@schmunk42 @germanbisurgi Should we a a "Known Bugs" section to the Readme.md (or a separate file)?
I have seen the "solution" with calling setValue() twice, posted in questions by me or @germanbisurgi so it might be a good idea to compile a list of bugs/weird behaviors and how you can work around them. (At least until someone solves the actual problem)

**Comment by schmunk42** [comment]
I like the idea. Either in the README and/or the wiki (a link to the wiki may be enough).
