### ISSUE TITLE
Is there a way to hide all elements not defined in a schema?

### ISSUE THREAD

**Issue by sriks316** [json-editor/json-editor#287]
I have a situation where I can get a bunch of random additional json attributes in the jsonInput. 

These attributes are eventually ignored by the end system.
However, this causes the GUI to look bad, because we see bunch of "string" items displayed in the GUI.

Instead of having me to add each and every item in the  schema as a hidden property, is it possible to just hide them by default if it not defined in the schema?

**Comment by schmunk42** [comment]
Have a look at `display_required_only` - https://github.com/json-editor/json-editor#options

**Comment by sriks316** [comment]
@schmunk42  thank you. However, this doesn't solve my issue. Not all json attributes in my schema are required. Some of them are valid, but they may or may not show up in the jsoninput. Hence they are not required, but they are still defined in the schema. What about the ones not defined in the schema?

**Comment by schmunk42** [comment]
Can you provide an example?

**Comment by pmk65** [comment]
The simplest solution would be to create some custom logic that filters out the non-required properties from the schema before applying it to jsoneditor.

**Comment by germanbisurgi** [comment]
`no_additional_properties` should do the trick the trick
