### ISSUE TITLE
hidden property attribute is not hiding form element in UI

### ISSUE THREAD

**Issue by bittu** [json-editor/json-editor#289]
### Expected behavior
When a property in schema has `"hidden"` attribute defined true then the UI element should be hidden.

### Actual behavior
UI element is still visible

### Steps to reproduce the behavior
Please look into below link for example
where name property has `"hidden": true`
[JsonEditor Interactive sample](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeITOEApKeAhSvrAAvoR8ssLEZJoyYLC5aIqwPv6BAEwArIR2OBACvgKIAIwAHA18AB7NrYgAnENZID4AbjFQsAD6dFjQMTz54pLSckxeMQJ8gSALS2WEkDDik9PF+ofLnhV+AZoAxF4+tQAM7yBjucboK6ICkh1jJ5IRHIMEABtEC7OBbMJ8eEAXTGCj2eUBaykoK2Oz2mnRxSYbHUOG4CFAXmgexIEDoAGsypSMqzCEs6HsIBpKatNFRaAwmKd4UhTFhOWSmCw2OhOBTQHQoEQAWJNCDNndKo8kABlIz6LRoIxKjALb6ESQY1VAiQ4zUgbwPfYAYQAghaDsqrcTeVj1fawY7lKopUgACoJDD6CDR37oDEmPxgLC7SCc6DQCJeVgCfQuWD6FiwCbc3zRsAAdyw+i8EFg0AU3BOYRINN9IGAwCVojZ+i7PsyGSYlb2dFcvJ7KqQHK5uAAdFOmIPNLOyfOV6y2cxYGAFXykHw0MaVYRtmg05owHxKPCTlBRShd82QL4mgBHdIASWKAgpaVgQgZj/G1xAFehGHvM5NFQSDmFYdh5VA5DgUDJgITaaEDgJTwsCDShdAUJg0FgNQIDvEAsALMpkS1Z1CTwz1rExNVUI2eQtzoqpEChERWMdRjCGYzQAHUkWKMoMlRVkgA===&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxQfLplEBlCGGwAxVPcsBnAfLedd1EAGEAQXlLTkxvX1t7JxcwdwESbCCQAF8yAAcYTjcEAG1QMMzRJXwKeUhYUQB1DW5UVIBdFKA==&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me.",
      "hidden": true
    }
  }
}
```

**Comment by pmk65** [comment]
There's no option named "hidden" AFIK.
You need to set the `format` to "hidden" if you want to hide the field.

**Comment by bittu** [comment]
Even `"format": "hidden"` is not hiding the whole UI element. It is just hiding the input element.

[Sample](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeIReMQJ8gSDOEApKeAC+hHyywsRkmjJgsPloirA+/oEATACshHY4EAK+AogAjAAcTXwAHq3tiACcIzkgPgBuMVCwAPp0WNAxPIXiktJyTAloSSlLKxWEkDDi07Ol+oernlV+AZoAxF4+9QAM7yAT+cboa6IikhNjJ5IRHMMEABtEBJOA7MJ8eEAXQmCmSBUBGykoJ2iWSmnRpSYbHUOG4CFAXmgyRIEDoAGsKpSsqzCCs6MkIBpKetNFRaAwmKd4UhTFhOWSmCw2OhOBTQHQoEQAWJNCDtndqo8kABlIz6LRoIxKjBLb6ESQY1VAiQ4zUgbwPFIAYQAghaQErRFbibyser7WDHcpVFKkAAVNIYfQQGO/dAYkx+MBYfb0pHQCJeVgCfQuWD6FiwKbc3wxsAAdyw+i8EFg0AU3BOYRINL9IGAwG9RDZ+i7vtgrKYleSdFcvJ7mg5XNwADop5awNakDOyXPB99WRMyGAFXykHw0MaVfF8Sll5R4ScoKKULA90xfC0AI6+WAASVKAgpUnfhDmH8bXEAV6EYG8zk0VBwOYVh2HlYDEOBIMmAhDpoS9AlPCwYNKF0BQmDQWA1Aga8QCwAsKmRLVnUJHDPWsTE1WQrZ5G3GiakQKERGYx16MIRjNAAdSRUoKiyVFWSAA==&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxQfLplEBlCGGwAxVPcsBnAfLedd1EAGEAQXlLTkxvX1t7JxcwdwESbCCQAF8yAAcYTjcEAG1QMMzRJXwKeUhYUQB1DW5UVIBdFKA==&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by pmk65** [comment]
@bittu Looks like the `hidden` editor isn't used after all, but it's set directly in the `string` editor. So the "compact" option should be working.

Try this (and don't set "description" as the "compact" option doesn't hide that)
````json
    "name": {
      "type": "string",
      "format": "hidden",
      "minLength": 4,
      "default": "Jeremy Dorn",
      "options": {
        "compact": true
      }
    },
````

**Comment by bittu** [comment]
After parsing the code found setting 
```
"options": {
    "hidden": true
}
```
It is hiding the whole element.

[Example](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeIRs6jjcCKDOEApKeAhSvrAAvnmEfLLCxGSaMmCwJWiKsD7+gQBMAKyEdjgQAr4CiACMABztfAAeXT2IAJyThSA+AG4xULAA+nRY0DE8ZeKS0nJMXjECfIEg65u1hJAw4gtLVfoXW571fgGaAMRePi0ADH8QLMSsZ0NtROUkHsZPJCI4JggANogE5wQ5hPhogC6swUp1KEN2Uhhh2Op00eKqTASEFwyVAXmgpxIEDoAGtaikCrNNnRTrSsiIxJoqLQGEwbmikKYsHzEkwWGx0Jx6ecoERwcKocSDq8Gh8kABlIz6LRoIx0CAYdZAwiSfGayESHWwkDed5nADCAEFbWrRPaqSkdppobq3cpVPKkAAVNIYfRW/Qg9D4kx+MBYE6QPnQaARLysAT6FywfQsWDzWm+BNgADuWH0XggsGgCm41zCJCZQZAwGAltEBXw+n7gfyeSYddOdFcwcHGqQvP5uAAdAumOPNMvEqut9zZmQwKrCZo+GhzRrCEc0NnNGA+JQ0dcoFKULBj0xfJ0AI65ACSVQCMkOSwIQyzAY64iivQjAvrcmioHBzCsOwKpQRh2r7K68K9Ei5zkp4WCupQugKEwaCwGoEDPiAWClrUWJ6h6FLEX61gElqzrYUCw4RvqgSIkKToKGxhAcZoADqmJVLUeQ4gUQA===&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8ATAKxkBmEAboQJYAuMA+gMb4ANoQQgAxI2Z0ADNNIgqYACZpRUCILhklEbqPnC+u9vmLxQfLplEBlCGGwAxVPcsBnAfLedd1EAGEAQXlLTkxvX1t7JxcwdwESbCCQAF8yAAcYTjcEAG1QMMzRJXwKeUhYUQB1DW5UVIBdFKA==&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)
