### ISSUE TITLE
docs vs. examples

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#29]
@loganvolkers I thought about keeping `examples` instead of `docs` for the .html files. They are examples, aren't they?

If we have a docs folder, I'd rather use markdown in there and maybe move some stuff from the README over there.

WDYT?

**Comment by schmunk42** [comment]
related https://github.com/json-editor/json-editor/commit/cdc7d68fe575ba2e124949b4dcdf89e760987a14#commitcomment-28011249

**Comment by loganvolkers** [comment]
IMHO `examples` feel like a kind of docs.... but the main reason for moving the folder around was for easy hosting on github pages -- they're restrictive in terms of providing only a few places they let you serve static html pages from.

As for docs in general, I'd be happy to see most of the readme make it's way into this repo's wiki section and just use markdown.

Feel free to make the call though, I'm not picky.

**Comment by schmunk42** [comment]
Ah, I never used github-pages before :)

So, I think that's fine.
