### ISSUE TITLE
Problem with SimpleMDE (format=markdown) in arrays

### ISSUE THREAD

**Issue by jmandreoli** [json-editor/json-editor#290]
### Expected behavior
My test type is an array of objects, each having a property 'bio' of type 'string' and format 'markdown'. When creating one item in the array, the SimpleMDE textarea appears, together with the text fields for the other properties. When deleting the item just created, both the text fields and the SimpleMDE textarea should disappear.

### Actual behavior
The text fields do disappear, but the SimpleMDE textarea remains. The item is not removed from the value. I get the error message "this.SimpleMDE.destroy is not a function".

### Steps to reproduce the behavior

```javascript
testType = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      web: { type: 'string', format: 'url' },
      mail: { type: 'string', format: 'email' },
      bio: { type:'string', format:'markdown' }
    }
  }
}
// and somewhere in my html page
var editor = new JSONEditor(document.getElementById('editor_holder'),{schema:testType})
```

**Comment by schmunk42** [comment]
@pmk65 @marc7000 Is there a way to easily convert the provided JSON (without ") to JSON which can be used on the example page?

**Comment by pmk65** [comment]
@schmunk42 I use this one to  reformat JSON https://www.freeformatter.com/json-formatter.html
It will add the missing double quotes and clean up the JSON.

**Comment by pmk65** [comment]
I can confirm the problem.

**Comment by schmunk42** [comment]
@pmk65 This issue would be a nice use-case for https://pmk65.github.io/jedemov2/dist/demo.html

**Comment by pmk65** [comment]
> 
> 
> @pmk65 This issue would be a nice use-case for https://pmk65.github.io/jedemov2/dist/demo.html

I have added the schema to the examples as "SimpleMDE". But unfortunately the "prototype" override method doesn't work on functions with calls to `this._super()` so it wan't possible to test the fix using the Interactive playground.
