### ISSUE TITLE
Disable Header for Object

### ISSUE THREAD

**Issue by VadimTikhonyuk** [json-editor/json-editor#294]
It is possible to disable header at all and leave only content?

### Expected behavior
![image](https://user-images.githubusercontent.com/13260375/52562658-deda2d80-2e07-11e9-9e18-0bb4884eaad8.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/13260375/52562633-c8cc6d00-2e07-11e9-88df-d3d0ffbd62bc.png)

**Comment by schmunk42** [comment]
You should be able to do that with CSS.

**Comment by VadimTikhonyuk** [comment]
> You should be able to do that with CSS.

CSS can't remove header, here I just leave it " "

**Comment by schmunk42** [comment]
Could you provide an example schema link?

**Comment by VadimTikhonyuk** [comment]
> Could you provide an example schema link?
`{
	"definitions": {
		"application": {
			"type": "object",
			"defaultProperties": [
				"type",
				"title",
				"images"
			],
			"format": "categories",
			"properties": {
				"type": {
					"title": "Type",
					"type": "string",
					"minLength": 2
				},
				"title": {
					"title": "Title",
					"type": "string",
					"minLength": 4
				},
				"images": {
					"title": "Image",
					"type": "array",
					"items": {
						"title": "Image",
						"type": "object",
						"properties": {
							"resourceId": {
								"title": "ResourceId",
								"type": "string",
								"enumSource": [
									{
										"source": "imageResourcesPtr",
										"title": "{{item.name}}",
										"value": "{{item.id}}"
									}
								],
								"watch": {
									"imageResourcesPtr": "root.resources.images"
								}
							}
						}
					}
				},
				"childrens": {
					"title": "Children",
					"type": "array",
					"items": {
						"title": "Children",
						"$ref": "#/definitions/application"
					}
				},
				"scriptId": {
					"title": "ScriptId",
					"type": "string",
					"enumSource": [
						{
							"source": "scriptResourcesPtr",
							"title": "{{item.name}}",
							"value": "{{item.id}}"
						}
					],
					"watch": {
						"scriptResourcesPtr": "root.scripts"
					}
				}
			}
		}
	},
	"title": "Cinema Application",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"application",
		"scripts",
		"objects",
		"resources"
	],
	"format": "categories",
	"properties": {
		"application": {
			"title": "Application Part",
			"$ref": "#/definitions/application",
			"options": {
				"disable_properties": true,
				"disable_edit_json": true,
				"disable_collapse": true,
				"compact": true
			}
		}
	}
}`

**Comment by schmunk42** [comment]
The schema is not working for me, several parts are missing.

```
Object is missing the required property 'scripts'

Object is missing the required property 'objects'

Object is missing the required property 'resources'
```

You can create an example here: https://json-editor.github.io/json-editor/ - Link is a the top right.

**Comment by pmk65** [comment]
Try making a more simplified schema to illustrate the problem.

**Comment by VadimTikhonyuk** [comment]
[Updated Schema](https://json-editor.github.io/json-editor/?schema=N4IgJgpgZglgdjALjA9nAziAXKAhgB3wBsYBjXZNbURAT3wmxBQCMArCUxEAGnGlwBXIogAKAJxQNxyCJiwBtEHQa9lSIoz4wAtrgDmckAF0+UFOL3csIcogj6LMI33yTps+TXqMc6xJpMACo+aiq+IOiI4vD6ajrwADIQcPqIABbYAEwAvnzIAb40GhFBJWGhNlExqfFJKWmZWAAseSC6BkZ+BYE2AJJ6hhWqNrji4ri0akgQOl7+vSADncMRrBxcam5SEDLO8+JyKILipBB9YNQLEQBKRydnF6tM1bFqKYI6AMrHp74KoHQvzOTA6hjuQIeclE0TC5RswGAMx0ADo4LgdBAcjk1AA3XBEQQRRHIlEwMDYkA5UwgADuFFITVAYIgEOB0NhNkkKEQKMOkL+6DJgyM2LFYvy8JAAGF4LNcAACACChBIdlQcGeNnWnG4fFwYDASA1BIkOz2XSgBPQEDMFisTDsDicLhA2w8+yuBGIZAoGquPQiKp96rQCtEYz1IHSEANuyCs2IFAiCrUABJDlAmABiAD0kFgCEoGFz3rVfqofCkxfmRvQuBYmgA+u7dp5sNEiXw6w3mxAjYgm2wgZqsJ3beAYPXGxAm6QUEQiAQbR3xF3bCgdPhcJsx2usWKgA&value=N4IghgDhA2CWDGYAusD2A7EAuUSCeEAptiCADQgpLTFakWwC2YA5oQM7YDaAugL58gA=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by schmunk42** [comment]
> > You should be able to do that with CSS.
> 
> CSS can't remove header, here I just leave it " "

Why does

```
.tab-pane h3 {
    display: none;
}
```

not work for you?

**Comment by VadimTikhonyuk** [comment]
> > > You should be able to do that with CSS.
> > 
> > 
> > CSS can't remove header, here I just leave it " "
> 
> Why does
> 
> ```
> .tab-pane h3 {
>     display: none;
> }
> ```
> not work for you?

Where I should use this?
From my PoV I can get access to it through JS by having id of element, but header doesn't have id or classname
![image](https://user-images.githubusercontent.com/13260375/52636120-61c8ba00-2ed4-11e9-8528-742b6ba2efbf.png)

**Comment by VadimTikhonyuk** [comment]
> > > You should be able to do that with CSS.
> > 
> > 
> > CSS can't remove header, here I just leave it " "
> 
> Why does
> 
> ```
> .tab-pane h3 {
>     display: none;
> }
> ```
> not work for you?

Where I should use this?

**Comment by pmk65** [comment]
> 
> 
> So questing is how to get access to it through js or where to apply your css code?

Just put the CSS into your own CSS file/styles.
Or if you really want to do it from JavaScript, you can do something like: `document.querySelector('div[role="tabpanel"] > div > div > h3').style.display = 'none'; `

**Comment by abhi-wd** [comment]
In my case span class is created with class h3 card-title level-1 je-object__title and style = "display: inline-block" having button with text Collapse

One other span class is created with buttons Edit JSON and Object Properities

How to hide this span
