### ISSUE TITLE
When loading existing document into editor, hide some populated fields by default

### ISSUE THREAD

**Issue by jdelfino** [json-editor/json-editor#298]
This is more of a question/feature request: I'd like to be able to load a document with a number of fields on it, but initially hide many of them, because they aren't commonly edited/exported. I'd like editors to be able to add these fields back via the `Object Properties` menu when needed. 

It seems that both `required` and `defaultProperties` don't work for this - if you load a document with populated fields, all of the populated fields are shown by default. 

Is there any way to control the initial set of fields that are shown for a loaded document, ignoring which fields are actually filled in on the document?

**Comment by pmk65** [comment]
There's no option like that AFIK, but you can do it with some JavaScript, like this:
````javascript
jseditor.on('ready', function() {

  var hideThese = ['root.prefix', 'root.blocks'];
  for (var ed in jseditor.editors) {
    if (jseditor.editors.hasOwnProperty(ed) && hideThese.indexOf(ed) > -1) {
      jseditor.getEditor('root').removeObjectProperty(jseditor.editors[ed].key);
    }
  }

});
````
See live example [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AYXQIYBuaAdAFYDOUaAJsgPYBONAHgQLYAO6lcANJBhxEtLDnhpK8AUIkBPLhmDY4DAEbk0AYxnBB0HADNmHAntXAA5k1GzDarkgYQ+KqOEPDg9SgXXoAPp0yIFULuJGBCiUaAYw3r7+QVxMDEpMSFKR0bFyAL7xOKnpaJmI2e6eCTiBABZoBLRl4tU1CkricNK2EFb27cam5l3AdaLNEAPtcM2U2rZOiBHucAA8dQDMAHwAouzc6FCUdQwA7oh9UKdnUPAMUACusVD4jSQU1PdQJkxm8FB5AxHiwAGQoeAAbkuXEe8AA9KCrFCoNoXJIIACzg1oEDHlACEw0HdFJcrKQ1vCtts1lxtgAxZhQWgMbSPDhoTHmZbQFx3BqvQgfKhQdLOVz8KAoBgMADWBIBawI1yJRgAvGBNWN4PAuJRMPD4VZkHVHupSGiOPCIAxKIgmPDtEKyFRNXA7oSrGh4BqtYEAgQILK3cA7sh0L64G9iC7qABxE1mkPbaPCyiUgjbKAJ+Cm9RQLgEL2kKAATWBqMDBJiDyMl1oBKlDABDCMbE4PCkUEu/MQ1CVKrQ6pDdR1eoN8KoddotHQpAg3uttvt8IIABkIHVaEZNgAveEhj1ML0+kP+lCB4NasOoNCRvDOz5QABSAGV6RN0Mm3x+Z+gM1mhbFpSdLTDUjjim42BtIMcCWoWujiPATCPHEciwdYti0IEaIoOyrjiAAjAATOhCT5GRhRkXBRL0PA2iEmIVRkd48CKMolg9GSYEJHASC3qMuC0cgryMTxiRSAsiBLCslg4EU4HAGKPJQR4LG8Zhog4QweEcAR7gAGwKTMwAwnCACCOq2OocKVNB6mKTwBDaGgpwoM0TCjJykgsAsIQAgxTANhA7LqC0wAOVAVFeCZTrvBxakxRhfl0bgYnuMhqHGRhLhCf5aVBQAKuxuB1IGXpMZYKXIAVtDFUopXlXQAASgazuFkUUUlUWUcZcBcKcC6tOpfHsaMXF9OJEjhglcAAAqDcSIUcGFnn6CNPiSYs4qjAtLhLaFZQ/MMOpklAAAUtCBn2dQAJRQAA1AWqqIKwU0QSpw3dd4Nhabh+GqUZkVwc6X2DI5i1IShaHfRpA37QASmgxq5QwzSjLQwbrbD3ipEOr2jA9AAsACs8mRd4NoAJIcBy9DmGgc0vW97hRDEGCw11gxc+RfXAHjdYs/Z3WjZ0qzABN/TYxh/FfuLTP4yz2U4HMUkyVM8vM+9Snq6pMEmb92H/XpgPK94cUxmD4O41r4vPrsAC0cCdepPMwNFikBKysp6xtbFi5xyHcdLJmy7NwCvmUiDRFAy2rdrqvbTyowAELStoPuSo8XAZAxLy/P8SCTSHinKS4vuw3Ahvabp+nYEDlemRAsLwJZQc2ZIFfW7jF4uW5HmjLsmJHbEtgx3HHWc2bOAWyQVvW3AXsZ6pADaFMJJs081CTW8JCT68ALq73A2e5wQeQZdDx+bSgiAcMg4WWE7Jfg7MaC3/fPlrgQu7yK+NxQ1Qi7bqbseqGC6vkYAQA&value=EQbwOgdgBFbA+gCwKYEMAmyBOcBctg4AaSGOAYy2XQEsAXc1LdPA40ggB0QHsJlWcdtC5UAZjQAeg4CgA2cnsLLAARovIBrAM4z06MUIgBfYEA==&code=EQehAIGEBsFMEMButwHsB2kBOsAmBLAF0ni1wBUBPAB1kgAt50BzPcR9XOLAHXUVLgAxjgLFSFGnQ6tcACSZdYWcAF5wAMwCu6IYXwYAFISkBKcAG8+4cAJWxoa8IXr4AzgDoHsALax0hB7osAAehADK+ABG0PgsANzW4Pga4IYO5g4eccFYcuQAsgAyTgDkJGTOUgBc4AA8boRYGMwAfKXgANRVtF3gpXUgjc0s7YnoAL7jfGDg4UgoQlpYOAFzQvS+8OCKc4SkhALQfHbgbhtbTgBWbnhEqFge55s+8OOnjQdH17diDx6sQgANXg0C0sEMpmm6FmAAV4IQNmcLq80NR9Bg3DtODtcLgoHAFmhMKIiBVJLQGExZJodHoDOg+M8th5qM1aFh9LBPCI7oiJB5UOiGTzCchBSS+eSqJSZGx1LyxNKpFSWHgFJxuNDZgAlWCsXIIlAuFAaB4+PgpNI3PkPcw2v6PXDcpqoSiQ8YO+4qdTBADu4D9cVwqD9HgAUuEAPIAOQAoo7DCGln4Ah4AI7grCUcLePQPQw8YAAYhuGAAtLasOWzVgLcBTAAaSxJZmvWpt+DNz6co4d/a90F8CZQvh8L2Ef5GUo4eC4SilZvaXQY9CQluM9A2U6uZ3kTa3JwAbRnqFQgTZsA0+BCi/6zXPHhiqCEAGs3KUALrjGy1tKnNg4nACd/irNxzCsLcbGSVJDBAx4wI8Rg3CjP10FhdllBMdJcHMAAyPD2HwPcD1gbJOFCKMNBw8xWnAcsAEYIKSaDgN+b0AVgQgE29QxT3PUpTA8HAfFQZAoyiK5YD0DChSw914K8R03CPPBPw8V9YEoUcoJsCYkn0zcR3iYAgA==&style=ETI=&theme=bootstrap3&iconlib=bootstrap3&object_layout=grid&template=default&show_errors=interaction&lib_cleavejs=1).

**Comment by sriks316** [comment]
> There's no option like that AFIK, but you can do it with some JavaScript, like this:
> 
> ```js
> jseditor.on('ready', function() {
> 
>   var hideThese = ['root.prefix', 'root.blocks'];
>   for (var ed in jseditor.editors) {
>     if (jseditor.editors.hasOwnProperty(ed) && hideThese.indexOf(ed) > -1) {
>       jseditor.getEditor('root').removeObjectProperty(jseditor.editors[ed].key);
>     }
>   }
> 
> });
> ```
> 
> See live example [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AYXQIYBuaAdAFYDOUaAJsgPYBONAHgQLYAO6lcANJBhxEtLDnhpK8AUIkBPLhmDY4DAEbk0AYxnBB0HADNmHAntXAA5k1GzDarkgYQ+KqOEPDg9SgXXoAPp0yIFULuJGBCiUaAYw3r7+QVxMDEpMSFKR0bFyAL7xOKnpaJmI2e6eCTiBABZoBLRl4tU1CkricNK2EFb27cam5l3AdaLNEAPtcM2U2rZOiBHucAA8dQDMAHwAouzc6FCUdQwA7oh9UKdnUPAMUACusVD4jSQU1PdQJkxm8FB5AxHiwAGQoeAAbkuXEe8AA9KCrFCoNoXJIIACzg1oEDHlACEw0HdFJcrKQ1vCtts1lxtgAxZhQWgMbSPDhoTHmZbQFx3BqvQgfKhQdLOVz8KAoBgMADWBIBawI1yJRgAvGBNWN4PAuJRMPD4VZkHVHupSGiOPCIAxKIgmPDtEKyFRNXA7oSrGh4BqtYEAgQILK3cA7sh0L64G9iC7qABxE1mkPbaPCyiUgjbKAJ+Cm9RQLgEL2kKAATWBqMDBJiDyMl1oBKlDABDCMbE4PCkUEu/MQ1CVKrQ6pDdR1eoN8KoddotHQpAg3uttvt8IIABkIHVaEZNgAveEhj1ML0+kP+lCB4NasOoNCRvDOz5QABSAGV6RN0Mm3x+Z+gM1mhbFpSdLTDUjjim42BtIMcCWoWujiPATCPHEciwdYti0IEaIoOyrjiAAjAATOhCT5GRhRkXBRL0PA2iEmIVRkd48CKMolg9GSYEJHASC3qMuC0cgryMTxiRSAsiBLCslg4EU4HAGKPJQR4LG8Zhog4QweEcAR7gAGwKTMwAwnCACCOq2OocKVNB6mKTwBDaGgpwoM0TCjJykgsAsIQAgxTANhA7LqC0wAOVAVFeCZTrvBxakxRhfl0bgYnuMhqHGRhLhCf5aVBQAKuxuB1IGXpMZYKXIAVtDFUopXlXQAASgazuFkUUUlUWUcZcBcKcC6tOpfHsaMXF9OJEjhglcAAAqDcSIUcGFnn6CNPiSYs4qjAtLhLaFZQ/MMOpklAAAUtCBn2dQAJRQAA1AWqqIKwU0QSpw3dd4Nhabh+GqUZkVwc6X2DI5i1IShaHfRpA37QASmgxq5QwzSjLQwbrbD3ipEOr2jA9AAsACs8mRd4NoAJIcBy9DmGgc0vW97hRDEGCw11gxc+RfXAHjdYs/Z3WjZ0qzABN/TYxh/FfuLTP4yz2U4HMUkyVM8vM+9Snq6pMEmb92H/XpgPK94cUxmD4O41r4vPrsAC0cCdepPMwNFikBKysp6xtbFi5xyHcdLJmy7NwCvmUiDRFAy2rdrqvbTyowAELStoPuSo8XAZAxLy/P8SCTSHinKS4vuw3Ahvabp+nYEDlemRAsLwJZQc2ZIFfW7jF4uW5HmjLsmJHbEtgx3HHWc2bOAWyQVvW3AXsZ6pADaFMJJs081CTW8JCT68ALq73A2e5wQeQZdDx+bSgiAcMg4WWE7Jfg7MaC3/fPlrgQu7yK+NxQ1Qi7bqbseqGC6vkYAQA&value=EQbwOgdgBFbA+gCwKYEMAmyBOcBctg4AaSGOAYy2XQEsAXc1LdPA40ggB0QHsJlWcdtC5UAZjQAeg4CgA2cnsLLAARovIBrAM4z06MUIgBfYEA==&code=EQehAIGEBsFMEMButwHsB2kBOsAmBLAF0ni1wBUBPAB1kgAt50BzPcR9XOLAHXUVLgAxjgLFSFGnQ6tcACSZdYWcAF5wAMwCu6IYXwYAFISkBKcAG8+4cAJWxoa8IXr4AzgDoHsALax0hB7osAAehADK+ABG0PgsANzW4Pga4IYO5g4eccFYcuQAsgAyTgDkJGTOUgBc4AA8boRYGMwAfKXgANRVtF3gpXUgjc0s7YnoAL7jfGDg4UgoQlpYOAFzQvS+8OCKc4SkhALQfHbgbhtbTgBWbnhEqFge55s+8OOnjQdH17diDx6sQgANXg0C0sEMpmm6FmAAV4IQNmcLq80NR9Bg3DtODtcLgoHAFmhMKIiBVJLQGExZJodHoDOg+M8th5qM1aFh9LBPCI7oiJB5UOiGTzCchBSS+eSqJSZGx1LyxNKpFSWHgFJxuNDZgAlWCsXIIlAuFAaB4+PgpNI3PkPcw2v6PXDcpqoSiQ8YO+4qdTBADu4D9cVwqD9HgAUuEAPIAOQAoo7DCGln4Ah4AI7grCUcLePQPQw8YAAYhuGAAtLasOWzVgLcBTAAaSxJZmvWpt+DNz6co4d/a90F8CZQvh8L2Ef5GUo4eC4SilZvaXQY9CQluM9A2U6uZ3kTa3JwAbRnqFQgTZsA0+BCi/6zXPHhiqCEAGs3KUALrjGy1tKnNg4nACd/irNxzCsLcbGSVJDBAx4wI8Rg3CjP10FhdllBMdJcHMAAyPD2HwPcD1gbJOFCKMNBw8xWnAcsAEYIKSaDgN+b0AVgQgE29QxT3PUpTA8HAfFQZAoyiK5YD0DChSw914K8R03CPPBPw8V9YEoUcoJsCYkn0zcR3iYAgA==&style=ETI=&theme=bootstrap3&iconlib=bootstrap3&object_layout=grid&template=default&show_errors=interaction&lib_cleavejs=1).

thanks pmk65. But I kind of dont know what to hide. I may be getting a key / value that is not defined in the schema. I want to keep it in the JSON output(not remove it altogether) but hide from the GUI.

**Comment by pmk65** [comment]
I guess you could use the same logic, but instead of calling "removeObjectProperty" set the field(s) to hidden.
