### ISSUE TITLE
JSON Editor meta-schema

### ISSUE THREAD

**Issue by IanMayo** [json-editor/json-editor#299]
This issue was addressed without success previously #52 

The JSON-Editor uses a schema to structure the editor.

The schema adheres to the JSON Meta-Schema [1]

The JSON Editor adds some properties the JSON Meta-Schema (such as `format` attribute).  I suspect it _may_ not reflect some JSON Meta-Schema properties.

Also, when the schema element of the JSON-editor is populated with the JSON Meta-Schema, the editor control is empty, and unusable.  This would be fixed by having a default object, with a default name.

I'd propose that this new document be called the JSON-Editor Meta-Schema

The presence of a JSON-Editor Meta-Schema would mean that power users would be able to create schemas for new document types without having to understand JSON.

As an example of the refinements, Ideally the JSON-Editor Meta-Schema would use $ref keywords to ensure that the list of  `required` properties were actually present in the document.  It would also make use of `grid` and `table` format attributes to display the data in a compact manner.

Has anybody addressed this issue?

[1]. http://json-schema.org/draft-07/schema

**Comment by schmunk42** [comment]
AFAIK not more than described in the issue, but any help with this would be greatly appreciated.

**Comment by IanMayo** [comment]
I had a play with it myself over the weekend, just to "prove the concept".  But, it's a fairly hefty piece of work so if it hasn't been done before I'll be offering it to freelancers, with the intention of submitting it to this repo on completion.

**Comment by IanMayo** [comment]
BTW, @schmunk42 - I just went to your profile page, to see if your email address was listed. I was going to invite you to apply to take on the task. I couldn't find one.

I _think_ you, or anyone else associated with JSON-Editor can view/apply for the job posting here: https://www.upwork.com/ab/applicants/1096060693219868672/job-details

**Comment by IanMayo** [comment]
Aah, @schmunk42 - do you contributors have a Slack channel or private mailing list where you discuss dev issues.  If you do, I'd appreciate you sharing this issue in there, please.  I'm happy to sponsor the development of this valuable feature, that I'll be contributing back to JSON-Editor.

So, to get it right first time, I'd appreciate the support/guidance of the community.

**Comment by pmk65** [comment]
> 
> 
> The schema adheres to the JSON Meta-Schema [1]
> 
> [1]. http://json-schema.org/draft-07/schema

JSON-Editor currently only supports JSON Schema version 3 and 4, so the above schema might give unexpected results.

**Comment by IanMayo** [comment]
Yes, thanks @pmk65 .

But, it's not very effective in JSON-Editor, since it lacks the layout hints that JSON-Editor supports - so the resulting editor is quite verbose and inefficient.  So this task is to refine the schema to include "format":"table", and include $ref constraints, etc.

**Comment by pmk65** [comment]
@IanMayo Im currently working on creating a new "Interactive Demo" for JSON-Editor, which allows for more complex testing setups than the current one. You can try it [here](https://pmk65.github.io/jedemov2/dist/demo.html)
It's not as restrictive as the current one, as it will generate schemas without starting values. And it includes several example schemas and setups.

**Comment by IanMayo** [comment]
Hmm, maybe there's already a suitably annotated meta-schema in the repo.

Does anyone know the background to this file?
https://github.com/json-editor/json-editor/blob/master/docs/meta_schema.json

**Comment by schmunk42** [comment]
> BTW, @schmunk42 - I just went to your profile page, to see if your email address was listed. I was going to invite you to apply to take on the task. I couldn't find one.

I've just enabled one ;)

**Comment by pmk65** [comment]
Looks like @Franciman Is working on something like this now. See #300

**Comment by IanMayo** [comment]
@pmk65 - that's not a coincidence :-)

**Comment by schmunk42** [comment]
@IanMayo Did you send me an e-mail, haven't seen one yet?

**Comment by pmk65** [comment]
I guess this was solved in #300, so I'm closing this issue.
