### ISSUE TITLE
Move Add Button

### ISSUE THREAD

**Issue by RichPitul** [json-editor/json-editor#30]
When using the array format the Add Button appears at the bottom of the list of current items, how do I go about moving it to the top. The list of items in my list is going to get long and I would like to make it so that I don't have to scroll all the way down to the button..

**Comment by schmunk42** [comment]
Instead of moving I'd introduce an option for the button position.

**Comment by pmk65** [comment]
The issue can be closed.

**Comment by marc7000** [comment]
Fixed in https://github.com/json-editor/json-editor/pull/186
