### ISSUE TITLE
New example editor - Schema Editor (with preview)

### ISSUE THREAD

**Issue by IanMayo** [json-editor/json-editor#302]
Use of the JSON Meta-Schema in the repo [1] allows the JSON-Editor to be used to edit schemas.

One of the core features of JSON-Editor is to dynamically generate a form-based editor based upon a schema.   We could use another JSON-Editor instance on the page to act as _Preview_ of an editor based on that schema.

So, it would start with a JSON-Editor that is based on the JSON-MetaSchema.  This editor is being used to design a schema.

That "living" schema could then be used as the schema for another instance of JSON-Editor, a _preview_ of what a form based on the schema being edited would look like.

This will involve a lot of screen components, so it may be worth rationalising some of the UI config selections present on the normal example screen.

There again, if the point is to visualise what the editor _could_ look like, then maybe the options are relevant for the second, _preview_ editor.

[1] https://github.com/json-editor/json-editor/blob/master/docs/meta_schema.json

**Comment by pmk65** [comment]
There's a couple creator tools available for JSON-Editor.
https://niebert.github.io/JSON2Schema
http://json.bootsphp.com/jsonSchemaCreator/

Dunno if it's something like that you are talking about?

Also, I'm currently working on a replacement for the /docs/demo.html with a lot more options and nicer layout. See: https://github.com/pmk65/jedemov2

**Comment by IanMayo** [comment]
Yes, they're both examples of what I was describing, though it took me a few minutes to recognise this is what the first one was doing.

The second one is very close to what I pictured. How about having something like it in the repo examples?

**Comment by pmk65** [comment]
That would be a cool addition.
There's also this one. (Not based on JSON-Editor) https://www.jsonschema.net/

**Comment by IanMayo** [comment]
@pmk65  - @Franciman & are going to work on an alternative example of a schema editor here:

**Comment by pmk65** [comment]
@IanMayo I'm looking forward to see how you progress.

**Comment by pmk65** [comment]
@IanMayo @Franciman Are you still working on this, or is the project at a standstill?

**Comment by IanMayo** [comment]
Hello @pmk65 - we've implemented sufficient features to make it usable.

Most of our work was in reducing the json meta-schema to allow more productive/focussed use of the json-editor (reducing the number of options)

A demonstration of the reduced schema was merged here:
https://github.com/json-editor/json-editor/pull/300

So, I guess this issue is closed.
