### ISSUE TITLE
Grid layout doesn't work with Foundation6 new XY Grid system

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#305]
Latest version of Foundation6 no longer works with JSON-Editor Grid layout.
See: https://foundation.zurb.com/sites/docs/grid.html

Only the legacy CSS (foundation-float.css) works with JSON-Editor.

**Comment by germanbisurgi** [comment]
grid-strict fix this bug

[interactive-demo](https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIBOAhgHYDmc+AZkuQLaU6K3kEAmAtAGcwPbHhBRySWOTAEYghKEpLCJMiBX5IsBCGE8646XKTVF8UNz4B9TEmIBXVuYQBGAL4f8KVXPV6vtrQGgYERvgmBGYWVjy8dg7OrvAATF74mH5EpHpZwbqIYRHIUKYpcbb2Ti4WAMwZILzZAYjNBaEi4bTGZdEVINYJ1ckWACyNZKD+uYgM4CF6xT2RfTGqQ4k1KQCsjYwtsyAHHUtdJVHrloPxW6MIAGyNPdczGisLhfrnH5cDmyNaggAOyNAAWhw0ENORR+vXKsRuVSSQPgAA5GgRIXosTDvoZfmt/rdASkAJyNNDYxBUvHLeH9REAlEpNwABkaAGtqSBuXS4asERsSSyLG5PN4QMQedL+QSGVdKsNRe5UvhNihyDBKNz4CJHDBGqweca5d0FcTbJrtbr9TB1SLtmLGtQea6zRciUzbtadQg7Q7kU73IGEkhGIxBDBOBLIjykOIdJ15YLGcKrVq/XryAbQ3dUW48+HI9GEOlJVAeZWPYShdcNZnbTn7UjlcH4IXWzZi1HOA1JQBHHlDmsW70Zm3+5t50liosR3sICaS8g81ej1OKru+pu5ruzkNdnul+B7SWIt5LROLWEp0p1pU2HdTvfM9udzbHzhPSWcaY5DQcA3e803rH1GxfFs33uDt5xLThQUlRweWQ4C/nHBJn2zV9HRgj9bi/BAMUlAA3HkyLQr100wiDsKg3CCzgxd4ApSUAHceQ4yiH23WiA33FVYKPBcT3ZRoAA8eUk7jQMfA8hM/ESYwlLwgA&value=N4IghiBcIgNCAjKN4GNlxAEw/ApriAGaEDmhAFoQJaEBWhA1oQDaEC2hAdoQPaEAHQgEdCAJ0IBnQgBdCAV0IA3QgHdCADwwBfIA&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=foundation6&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default)
