### ISSUE TITLE
JSON modification

### ISSUE THREAD

**Issue by KamilGPSEA** [json-editor/json-editor#307]
Hello, 
I was wondering where the JSON file is to modify once the information is entered in the Form.

**Comment by pmk65** [comment]
You get the form result by calling `editor.getValue()`

**Comment by KamilGPSEA** [comment]
And can I store all the results in a single JSON file?

**Comment by pmk65** [comment]
You can do whatever you want with the result. You could pass it through [JSON.stringify()](url) and then store it in a hidden field before submitting to server. Or you could create some JavaScript code to save it directly as a file if you want to.

**Comment by KamilGPSEA** [comment]
Merci beaucoup

**Comment by pmk65** [comment]
Here's a pure JavaScript `SaveAsFile` solution (Editor must be available in the variable `jseditor` : 
````javascript
var button = document.createElement('button');
button.appendChild(document.createTextNode('Save Result'));
//document.body.appendChild(button);
jseditor.root.header.parentNode.insertBefore(button, jseditor.root.header.nextSibling)

button.addEventListener('click', function(e) {
  e.preventDefault();
  var example = jseditor.getValue(),
  filename = 'example.json',
  blob = new Blob([JSON.stringify(example, null, 2)], {
    type: "application/json;charset=utf-8"
  });

  if (window.navigator && window.navigator.msSaveOrOpenBlob) {
    window.navigator.msSaveOrOpenBlob(blob, filename);
  } else {
    var a = document.createElement('a');
    a.download = filename;
    a.href = URL.createObjectURL(blob);
    a.dataset.downloadurl = ['text/plain', a.download, a.href].join(':');
    a.dispatchEvent(new MouseEvent('click', {
      'view': window,
      'bubbles': true,
      'cancelable': false
    }));
  }
}, false);
````

**Comment by schmunk42** [comment]
@pmk65 That's nice! How about a "pure JavaScript `SaveAsFile` solution" page in the wiki?

**Comment by KamilGPSEA** [comment]
+1

**Comment by pmk65** [comment]
> 
> 
> @pmk65 That's nice! How about a "pure JavaScript `SaveAsFile` solution" page in the wiki?

Done! https://github.com/json-editor/json-editor/wiki/Adding-a-SaveAsFile-button

**Comment by schmunk42** [comment]
Can we close this?
