### ISSUE TITLE
Does anyone got a working ACE Editor example

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#308]
I'm trying to setup an ACE Editor field, but I keep getting errors like these when using CDN lib "https://cdn.jsdelivr.net/npm/ace-builds@latest/src-noconflict/ace.min.js":

> misspelled option "enableBasicAutocompletion" ace.js:4017:8
> misspelled option "enableLiveAutocompletion" ace.js:4017:8
> misspelled option "enableSnippets" ace.js:4017:8
> Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver ace.js:4206:8
> Loading failed for the <script> with source “https://github.com/pmk65/jedemov2/dist/mode-sql.js”.

Example: https://is.gd/maGoYz

So if anyone got a working setup (Not just the schema), please post a link.

**Comment by schmunk42** [comment]
@eluhr You had one right?

**Comment by pmk65** [comment]
I think I got it figured out with the help of Google translate and a Russian site 😁 

If you are using the CDN lib: "https://cdn.jsdelivr.net/npm/ace-builds@latest/src-noconflict/ace.min.js", then you must set the ACE "basePath" to the same path as the lib:
````javascript
var url = "https://cdn.jsdelivr.net/npm/ace-builds@latest/src-noconflict/";
ace.config.set("basePath", url);
````
Or a more "fancy" approach: (Live example: https://is.gd/AD6UdE)
````javascript
var aceScript = document.querySelector('script[src*="ace-builds"]');
if (aceScript.src && window.ace) {
  window.ace.config.set('basePath', aceScript.src.replace(/(.*\/)[^\/]+$/g, "$1"));
}
````
But the "misspelled option" still occurs when using the options listed in JSON-Editor's readme.md.
I did get it to work with other options though. So maybe it's options for an older version of ACE Editor?

**Comment by eluhr** [comment]
> @eluhr You had one right?

Yes, but not in combination with the JSON Editor.

**Comment by pmk65** [comment]
I'll make a stand-alone ACE-Editor example for the docs/ folder. 
I also noticed some annoying "features" of ACE Editor while working on my Playground project, and I'm pretty sure the also occurs when using it inside JSON-Editor.
1) After setting the value in ACE Editor using `setValue()`, all the content is selected.
2) If a ACE Editor field is hidden when you update the value, the value is not visible when you make the field visible. It first updates when you put focus to the editor.
Both is very easy to fix.
