### ISSUE TITLE
XML Parsing Error: not well-formed in Firefox when used locally

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#309]
When used locally (file://), Firefox throws an error when loading $refs through AJAX.

`XML Parsing Error: not well-formed ...`

This is due to the XHR request. When the MIME type isn't set by the server, Firefox believe that the file requested is in XML format. See: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/overrideMimeType#Example

**Comment by schmunk42** [comment]
@pmk65 One minor thing, GitHub can close issues automatically using predefined keywords ;) https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by pmk65** [comment]
Thanks for the info. I didn't know that. 😄
