### ISSUE TITLE
When is JSONEditor value updated?

### ISSUE THREAD

**Issue by eduo** [json-editor/json-editor#31]
I've just noticed it's possible to trigger the submit event skipping the change event.

The editor's value seems to only be updated on change event (and to bubble the change event).

What's the easiest way to have the editor update its value on change -as it happens- ?

**Comment by schmunk42** [comment]
Are you referring to standard inputs or some special ones like WYSIWYG editors or Select2?
Did you trigger changes and/or submit via JavaScript or user input?

**Comment by eduo** [comment]
I'm talking about simple text fields. The "change" doesn't trigger when text is being changed.

In some cases pressing enter will submit the form without having the editor value updated. I assume the change event is either not being triggered or there's a race condition when the submit is happening before it's updated.

I could add a delay on submit but it doesn't look clean to me. I wonder what's the easiest way to attach events to field change (for text and textareas, I believe, at the very least)

**Comment by schmunk42** [comment]
> In some cases pressing enter will submit the form without having the editor value updated.
> ...
> I could add a delay on submit but it doesn't look clean to me.

I never noticed that, but I also never looked specifically after this.
Does it work all the time for you when you enter some text, then wait for a second and then hit enter?


CC: @marc7000

**Comment by eduo** [comment]
I solved it. I was mixing up things.

The editor value *is* updated but there is a hidden field where I was storing the JSON (it's an old form and I'm forced to reuse the old freetext textarea field, so I've hidden it and I update it as the form changes).

So, as you type in text fields the editor value *does not* get updated but when you submit and/or you change fields it does (this might be a problem if you need to do things like character counts on a field unless you attach a listener to the field).

The problem was on my side. I was updating the hidden field with the editor value, but the submit action was running before this got into effect.

When I added a delay it worked, because the hidden field managed to get overwritten by the change event.

What I've done is attach the update of the field to the submit event itself, so the final value is always updated prior to submission. No need for delay.

Thanks :D
