### ISSUE TITLE
Uncaught TypeError: Cannot read property 'flatpickr' of undefined

### ISSUE THREAD

**Issue by MF0124** [json-editor/json-editor#312]
we are getting folowing exception 
Uncaught TypeError: Cannot read property 'flatpickr' of undefined

while using rawgit demo site https://rawgit.com/json-editor/json-editor/master/docs/demo.html as well as in our application while using oneof schema with date. This error we get when using option 'Update form' with input json. Please find json schema and input json

Schema:
{
  "type": "array",
  "title": "Test",
  "items": {
    "type": "object",
    "headerTemplate": "{{self.item}}",
    "required": [
      "INV_STATUS"
    ],
    "properties": {
      "INV_STATUS": {
        "title": "Details Name",
        "options": {
          "keep_oneof_values": false
        },
        "oneOf": [
          {
            "title": "Option 1",
            "type": "object",
            "required": [
              "F1",
              "F2"
            ],
            "properties": {
              "F1": {
                "type": "string",
                "options": {
                  "hidden": "true"
                },
                "default": "F1"
              },
              "F2": {
                "title": "F2",
                "type": "string",
                "format": "date"
              }
            }
          },
          {
            "title": "Option 2",
            "type": "object",
            "properties": {
              "F1": {
                "type": "string",
                "options": {
                  "hidden": "true"
                },
                "default": "F2"
              },
              "F2": {
                "title": "F2",
                "type": "string",
                "format": "date"
              }
            }
          }
        ]
      }
    }
  }
}

Input:
[
  {
    "INV_STATUS": {
      "F1": "F1",
      "F2": "2019-02-20"
    }
  }
]

**Comment by pmk65** [comment]
I pasted your schema and value into the [demo](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcICGAnFSIgDTgJZgBs5EAVGAZzGxHxgFtyFRJYEQB7AIwCsYBjKjgAWMJABMYKMnSgEkYYiGDByMAgDMAdLToBfXdRQwAjgFdcRsQgDaIAJIA5AGoB9AMokAgiQCqbkAC6OFAo7LAoYLgUTPbO7l6+/vDM+ERsACIwYEi4BOQABA5IdHA4YZHsAHaMySAA1jAwUC5VMOzqLgBuSASm0fDqPaq6ZZUwAPLqNimEiuNQFZX5AIzULIpcvAKGJuaWNiAAYqs4hwBMgcGh4ZH9oMcx62yUKLiVAObU5bhVNaBCuDEEkqbDAKD6IBGIAkg1MBCoiAeUPOj1SihROCeiBeb0+OHU7BQdHkbDE8jg+jKCx+1RiDSaLTG7S6PT6NUGeRgUJCYUkkHGKAkKAQywADOKRjM0oh5ot8hdMdANjx+IIQDyblE/kdVrUsSAcR8vtTfjEAUCYCDEGCIVCYUg4QijhdkRc9Wi2BjwErnmDcdQCUSSYgyQpIVDvqbavTmq1md1ev0OcMrryIhABUKReLRboAvp9EA==&value=NobwRAkgcgag+gZQCoEEkFUFgFzgGICMOYhYANCQEzGUAMBAnALS2VMEDMYAvtwLpA==&lib_switcher=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) 
But I don't see the error you are referring to. Instead I see this error in console.
`TypeError: v is undefined  jsoneditor.js:1411:10 `

The odd thing is that line 1411 looks like this, and there's no reference to a "v" variable.
`var dateFormat = ed.flatpickr ? ed.flatpickr.config.dateFormat : format[ed.format];`

So it looks like there's some problem with date fields if flatpickr is not loaded.

**Comment by MF0124** [comment]
Just before this(var dateFormat = ed.flatpickr ? ed.flatpickr.config.dateFormat : format[ed.format];) line

Getting error on "var ed = this.jsoneditor.getEditor(path);"

we are using v1.3.4
also getting same even if we select flatpicker option in the libraries of rawgit

**Comment by pmk65** [comment]
Thanks. That helped me pinpoint the problem.
The `path` variable in your test case is either `root.F1` or `root.F2`, but the editor it's trying to lookup got the keys `root.0.INV_STATUS.F1` and `root.0.INV_STATUS.F2`

I think it's due to the validation picks the `date` validation before `oneOf` validation. 
As i put in some `console.log()` in the `onOf` and `date` validation functions, and only the one in the `date` validation showed. But if I disable the `date` validation, the debug in `onOf` validation is shown.
I'll see if I can "shuffle" them around so `onOf` has higher priority..

**Comment by pmk65** [comment]
@schmunk42 @germanbisurgi Doesn't look like it's possible to get the full path to a field in the validation process. Specially if field is in an array. Do you know of any ways to access the full path in the validators?
Otherwise I'll remove the date/time validation, as it relies on getting the `options` from the schema field definitions.

**Comment by schmunk42** [comment]
> Otherwise I'll remove the date/time validation, as it relies on getting the options from the schema field definitions.

Shouldn't we rather fix the full path access, than removing the validation?

**Comment by pmk65** [comment]
That's what I have been trying to do without success. 
Remove the validation is the last resort, so that the editor doesn't break when using date fields inside arrays.

**Comment by schmunk42** [comment]
Could a custom validator be a workaround?

**Comment by pmk65** [comment]
The datetime validator is already a custom validator.
