### ISSUE TITLE
Description text is repeated inline in tables

### ISSUE THREAD

**Issue by algr** [json-editor/json-editor#313]
### Expected behavior

When using the 'table' format, we would like a tabular display of the data, like an HTML table or spreadsheet. Where the schema has descriptions for the data items (i.e. columns in the table), they might be visible on a mouseover, or in column headings etc.

### Actual behavior

The default table rendering of arrays, where there are descriptions in the schema, repeats the descriptive text inline in the table, in each cell, under the edit field. This leads to lots of duplicate text and wasted space. Also the combination of edit field and description are vertically centred in the overall table cell. Where the descriptions are of different lengths this breaks vertical alignment of the edit fields.

### Steps to reproduce the behavior

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "array",
      "format": "table",
      "items": {
        "title": "item",
        "type": "object",
        "properties": {
          "code": {
            "description": "unique item code",
             "type": "integer"
          },
          "name": {
            "description": "name of the item, this might be a very long description, that spans multiple lines",
            "type": "string"
          }
        }
      }
    }
  }
}
```

then some data that has multiple items:

```javascript
{
  "example": [
    { "code": 1, "name": "first item" },
    { "code": 2, "name": "second item" }
  ]
}
```

**Comment by schmunk42** [comment]
Since the help text is already wrapped in a `<p>` tag with a class I think you can implement this on your own.

**Comment by algr** [comment]
There's no class, the help text is wrapped in a <p> tag with inline style:

```
<p style="font-size: 0.8em; margin: 0px; display: inline-block; font-style: italic;">Description of the item</p>
```

**Comment by schmunk42** [comment]
Which version are you using?

```
<p class="help-inline">name of the item, this might be a very long description, that spans multiple lines</p>
```

https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QCsDOB7AdgAlQYwAtYBbAQ21gA9TiAHOEAGnAE9b4l0AjZWPMJiFoAndO2GRYqRKCo16HUGDYcQpYcNItBAM3TCyApGFJcGzKCWkIlUBkkvFBy9ohDde/QSLGwJEKRkQPHQAE0UQcPxhCFpILDcAV0wIAEdE2GxHbBDw5xU3CEwwWABzPxAAX2ZMGgiovBi4iASkWuJM9B1sMCIskuJGHoIIVGxiCFKCMGwuTPIANz8WbGgsUuwGpvjMId7SGdRaUkwx4kToSAVVosDmF1VUMBjMUqrKj4+gA&value=N4IgpgHghgtgDgGzCAXAbVAYwPYBNkoAMANCAHawEggC+AujUAA=&prompt_before_delete&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by algr** [comment]
I'm using latest/dist/jsoneditor.min.js from cdn.jsdelivr.net as suggested in the docs, with no specific CSS for the json-editor elements.

As a workaround, I was able to hide the help text with
```
.form-control p {
  display: none !important;
}
```
but the table layout is still bad as the fields are generally too wide and the "move up" / "move down" buttons are stacked on top of each other at the end of each row. It needs to be more compact to be useful.

**Comment by pmk65** [comment]
@schmunk42 It's odd. In *all* the editors there's a check in the `build()` function to see if `this.options.compact` is not `true`. And only when it's `false` the description is generated. But I can't get it o work with your test case. No matter where I put the options object.
````json
"options": {
  "compact": true
},
````

**Comment by pmk65** [comment]
> but the table layout is still bad as the fields are generally too wide and the "move up" / "move down" buttons are stacked on top of each other at the end of each row. It needs to be more compact to be useful.

You are more than welcome to submit a PR if you can improve the layout.

**Comment by schmunk42** [comment]
> You are more than welcome to submit a PR if you can improve the layout.

Definitely, but we need to make sure it works for all layouts (table, tabs, ...)
