### ISSUE TITLE
Sphinx+ReadTheDocs integration

### ISSUE THREAD

**Issue by paulmeems-waterwatchfoundation** [json-editor/json-editor#314]
### Expected behavior
Use the validator with Sphinx on ReadTheDocs

### Actual behavior
No documentation, so not sure how to do this.

### Question
We've made a JSON Schema and have documented it with Sphinx on ReadTheDocs: https://global-coffee-data-standard.readthedocs.io

We would like to add your json-editor/validator on one of our rst pages but we're not sure how to do this.
Is this been done before or is a tutorial or some documentation available?

**Comment by pmk65** [comment]
I have zero experience with Sphinx, but I did a quick googling around and found this page:
http://www.sphinx-doc.org/en/stable/templating.html#script_files
So it should be possible to include custom scripts on a page.
