### ISSUE TITLE
Need help with selectors from array

### ISSUE THREAD

**Issue by dzg** [json-editor/json-editor#319]
I have all my data in an object. I have 3 dropdowns, and I each dropdown to populate based on the selection of the previous one.

For example:

```js
data = {
  "campaign1": {
    "name": "Campaign 1",
    "projects": {
      "job A": [
        "proj 1"
      ],
      "job B": [
        "proj 2",
        "proj 3"
      ]
    }
  },
  "campaign2": {
    "name": "Campaign 2",
    "projects": {
      "job C": [
        "proj 4",
        "proj 5",
        "proj 6"
      ],
      "job D": [
        "proj 7",
        "proj 8",
        "proj 9"
      ]
    }
  }
}
```

The idea is that first you choose a "Campaign", then 2nd dropdown shows "Jobs" for that campaign, then 3rd shows "Projects" for that job.

This is what I've tried for the first 2 items, but I'm not understanding how `watch`, `enumSource`, and `template` work together:

```js
var editor = new JSONEditor(document.getElementById("editor"), {
...
  schema: {
    type: "object",
    properties: {
      campaign: {
        id: "campaign",
        type: "string",
        enumSource: [{
          source: Object.entries(data),
          value: "{{item.0}}",
          title: "{{item.1.name}}"
        }],
      },
      project: {
        type: "string",
        watch: { "c": "campaign" },
        enumSource: [{
          source: Object.entries(data),
          title: "{{item[c].projects}}"
        }]
        ....

```

The first item shows the campaigns correctly, but how do I then use that selection to populate the 2nd dropdown?

Thanks!

**Comment by pmk65** [comment]
Watching a field from within the schema is rather limited, compared to watching the field from JavaScript.
If you watch the field(s) from JavaScript, you can manipulate the fields better. 
Take a look at this example: https://github.com/json-editor/json-editor/wiki/Adding-autoprefilling-based-on-value-in-another-field-using-Bloodhound

**Comment by dzg** [comment]
@pmk65 thanks! Looks promising.
I just discovered Alpaca, seems more robust, maybe I should be using that?

**Comment by pmk65** [comment]
@dzg I originally used Alpaca myself, before switching to JSON-Editor. I found Alpaca too bloated and the documentation didn't match the current codebase.

**Comment by schmunk42** [comment]
btw, I just ran `cloc` against Alpaca's `src`

```
 schmunk@xps-15  ~/Workspace/_tmp/alpaca-master  
> cloc src            
     176 text files.
     163 unique files.                                          
      16 files ignored.

github.com/AlDanial/cloc v 1.80  T=0.11 s (1426.0 files/s, 339515.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      90           4696           8489          22655
HTML                            67            342             21           1120
CSS                              5            281            139            828
-------------------------------------------------------------------------------
SUM:                           162           5319           8649          24603
-------------------------------------------------------------------------------
``` 

and `json-editor`

```
 schmunk@xps-15  ~/Workspace/json-editor/json-editor   master  
> cloc src          
      59 text files.
      59 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.80  T=0.04 s (1441.0 files/s, 263157.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                      58           1089            933           8710
CSS                              1              0              0             43
-------------------------------------------------------------------------------
SUM:                            59           1089            933           8753
-------------------------------------------------------------------------------
```

**Comment by dzg** [comment]
@pmk65 I looked more closely at that example, and the problem is that I don't need to `setValue` for the other fields ... I need to `setEnum` or something, which I don't see as a method.

@schmunk42 Also in the colors example, the 2nd field is taking values from an array in 1st field, but my 1st field is not an array, it's 1 selection from enum list.

I'm fine using `onchange` but how do I change the enum list in another field?

Thanks!

**Comment by pmk65** [comment]
@dzg I recently made an example of modifying enum using JavaScript. https://is.gd/E8Ha7e
A combination of this and the other example might do wat you are looking for.

**Comment by pmk65** [comment]
@dzg Take a look at this. https://is.gd/VDL0Wv
Needs some more work, but should be good as a base.
Note: I rewrote the data format to make lookup more simple.

**Comment by dzg** [comment]
@pmk65 Thanks, I tried that, and I can modify the schema ... but the destroy/recreate function redraws the whole screen and renders really ugly with no styling.

Is there a way to 'rebuild' a single field? Or redraw the form in place?

**Comment by dzg** [comment]
Can the source of an `enumSource` be a function which takes the value of another field as an argument? Or something like alpaca's `subscribe` function? I was able to get that to work in alpaca ... but everything else was a nightmare.

**Comment by dzg** [comment]
UPDATE: I figured out that to redraw properly I had to pass the old options into the new editor
👍

**Comment by dzg** [comment]
Actually it's not working, see https://github.com/json-editor/json-editor/issues/320

**Comment by pmk65** [comment]
I fine-tuned my example: https://is.gd/amdw1Q 
So it should be working 100% and now unselecting works too. The "water -> fish" has 3 steps, while the others 2.

In the "watch" function, I update the "startval" array with the current value. (I too noticed the problem with the value in "watch" getValue() didn't contain the current value)
````javascript
  startval = jseditor.getValue();
  startval[key] = val;
````

**Comment by pmk65** [comment]
There's also the `dependencies` option available (Is present in current release but was missing from the documentation) And there's also the new **DescribedBy** editor available in the current git version.
