### ISSUE TITLE
Issues with `.watch`

### ISSUE THREAD

**Issue by dzg** [json-editor/json-editor#320]
Starting from [this](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AeQK7wAOhcANJDHPAJ5EbDZwD2ARgFZoDG85lO8ABZoAtgybBWzZvADO8AE4BDIgBY%2B0HArQBHfIm0ATLFADa%2FKgjTyAjBpiX413sH4BdCprhEFzegqRrE3BNR2c7RigQhwdqZHQTOABlRUQIAHMoJ3koADNENBRjYE8YxzpxHHkFNPT7MrhDNFylfBQXCQAJQpRmKAB1ZgUiuAsoAF9S2Kt5YLHHeMrk1IyoNAh8ETyCkZL5gQrE4Gra%2Bpi4dc2Tc1CGyRQlLgBrM7uAd0FkBn23MfH%2Bf4QcbAIA%3D%3D&value=ETI%3D&code=EQKwzgpgJglgLgewE4DoEDsAUByJECGUAntgDQAEAZgK7oDGcMGmAlOQN4A66355A9P3IBlfADcI5OAAtJUCJXzUANnHIBRdNQC25MfmXUIYXnvxJyyAOaad5ALzlw0eMhRg6s7fhQAHJAi%2BEEiMxihwxnAoEFraANzcpoLkAMJ4%2BBHkAEbUcIg86Hz6FlAO5FAIdDoxcBRZZVAodOkR6soQ2jU4OXkY2CwUlMi6jo0AjkZIRMIQ7QzIOADE4BgAtC6ISKtDSNr9CYXZKPi%2BQehQKdIwylCYjc0EEQAqEAAecAByCPI4TwhWVnaGli5AAagYjGB%2BiwDnwdto%2FOYal95CgYOhICEAEIKZAQTBZQbDFDoN5wYQwLLKdFWGGmLLHKBQdQSdBwAAyMDAEVJSBwdGpdAA1mQqLQGEwsGwuAU%2BHwZFyUFAMvhIFFEACgY4FWAlSq1eF%2FoDJPZHNgAIzYcgAfnI2AADFaAFx2y0HUx8ZIAcQgaiqSDwbJEng6%2BHI%2BHOIjg5jg%2BmUHrMFg8XjDjmcsE27hD3lhcuK5G5MbjZXTrlQVl94MM%2BLpsrlyQAst8YJQiFJZAXs2GYnY45CE8nQ34AkEQjAwhFudEQY5MDq9dGDRrjQ4zZa2LaANq4aBkbBWPAxPdUozYAC65Bd1ls8USh09QgAShAK7yMpIZJJ4QmW%2BRMKXNjYAC3HkbkAiIVhcz4YCLEcUkAHdyHg9EKnglAAClhAAeQ%2BdQMwWeFyFIdhB28F1SPwChCxCONyOjGiDAAX1rOVyATZJnwmGA8FKHZyGoXxlUYdArHIAAFZR8CIA8EFoUosNyXxcnIJ58HqMB0ToSQNmQcguXKSJwOgPSMRgeRyAgVk4ATGC0CwbBPAjCtRQEoSIAUuAlLgWtTGY910D84AgA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction) example, I tried changing the schema when a certain field changes.

But:
1. `destroy`ing the form and then creating a new one means the `.watch` listener is no longer active, so it doesn't catch additional changes.
2. The change event seems to fire before 'recording' the changed value. `getValue()` returns the value of the changed field BEFORE it was changed!

Is there a way to redraw without destroying?

**Comment by dzg** [comment]
Also, this:
```js
            jseditor.on('change', function () {
                console.log('.on change',this.getValue())
            });
```
returns the changed value of the changed field.

But this:
```js
            jseditor.watch('root.test1', function () {
                console.log("watch", jseditor.getValue())
```
returns the value of the changed field **before** it was changed.

**Comment by pmk65** [comment]
> 
> 
> Starting from [this](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AeQK7wAOhcANJDHPAJ5EbDZwD2ARgFZoDG85lO8ABZoAtgybBWzZvADO8AE4BDIgBY%2B0HArQBHfIm0ATLFADa%2FKgjTyAjBpiX413sH4BdCprhEFzegqRrE3BNR2c7RigQhwdqZHQTOABlRUQIAHMoJ3koADNENBRjYE8YxzpxHHkFNPT7MrhDNFylfBQXCQAJQpRmKAB1ZgUiuAsoAF9S2Kt5YLHHeMrk1IyoNAh8ETyCkZL5gQrE4Gra%2Bpi4dc2Tc1CGyRQlLgBrM7uAd0FkBn23MfH%2Bf4QcbAIA%3D%3D&value=ETI%3D&code=EQKwzgpgJglgLgewE4DoEDsAUByJECGUAntgDQAEAZgK7oDGcMGmAlOQN4A66355A9P3IBlfADcI5OAAtJUCJXzUANnHIBRdNQC25MfmXUIYXnvxJyyAOaad5ALzlw0eMhRg6s7fhQAHJAi%2BEEiMxihwxnAoEFraANzcpoLkAMJ4%2BBHkAEbUcIg86Hz6FlAO5FAIdDoxcBRZZVAodOkR6soQ2jU4OXkY2CwUlMi6jo0AjkZIRMIQ7QzIOADE4BgAtC6ISKtDSNr9CYXZKPi%2BQehQKdIwylCYjc0EEQAqEAAecAByCPI4TwhWVnaGli5AAagYjGB%2BiwDnwdto%2FOYal95CgYOhICEAEIKZAQTBZQbDFDoN5wYQwLLKdFWGGmLLHKBQdQSdBwAAyMDAEVJSBwdGpdAA1mQqLQGEwsGwuAU%2BHwZFyUFAMvhIFFEACgY4FWAlSq1eF%2FoDJPZHNgAIzYcgAfnI2AADFaAFx2y0HUx8ZIAcQgaiqSDwbJEng6%2BHI%2BHOIjg5jg%2BmUHrMFg8XjDjmcsE27hD3lhcuK5G5MbjZXTrlQVl94MM%2BLpsrlyQAst8YJQiFJZAXs2GYnY45CE8nQ34AkEQjAwhFudEQY5MDq9dGDRrjQ4zZa2LaANq4aBkbBWPAxPdUozYAC65Bd1ls8USh09QgAShAK7yMpIZJJ4QmW%2BRMKXNjYAC3HkbkAiIVhcz4YCLEcUkAHdyHg9EKnglAAClhAAeQ%2BdQMwWeFyFIdhB28F1SPwChCxCONyOjGiDAAX1rOVyATZJnwmGA8FKHZyGoXxlUYdArHIAAFZR8CIA8EFoUosNyXxcnIJ58HqMB0ToSQNmQcguXKSJwOgPSMRgeRyAgVk4ATGC0CwbBPAjCtRQEoSIAUuAlLgWtTGY910D84AgA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction) example, I tried changing the schema when a certain field changes.
> 
> But:
> 
>     1. `destroy`ing the form and then creating a new one means the `.watch` listener is no longer active, so it doesn't catch additional changes.
> 
>     2. The change event seems to fire before 'recording' the changed value. `getValue()` returns the value of the changed field BEFORE it was changed!
> 
> 
> Is there a way to redraw without destroying?

I haven't tried it, but it should be possible to add or remove fields
There's an example on the old repo: https://github.com/jdorn/json-editor/issues/387

**Comment by dzg** [comment]
@pmk65 ok, I'll try that!
What about the second issue?
Do you know why I getValue isn't getting the changed value?

**Comment by pmk65** [comment]
I converted the example from the old repo to a non jQuery version, and this method seems to be working well. https://is.gd/nJBCW5

Inside the "watch", you can explicit call getValue for the selected editor. that will give you the correct value. I read somewhere (can't remember where) that if you can `jseditor.getValue()` twice in a row, the 2nd time the value is updated.

**Comment by pmk65** [comment]
@dzg I went through the source and discovered a couple of "hidden features".
The `dependencies` option can be used to create enum fields depending on value from other field.
Also the new "DescribedBy" editor I submitted recently, can do some similar thing.
