### ISSUE TITLE
SCEditor 2.x doesn't work

### ISSUE THREAD

**Issue by freiguy1** [json-editor/json-editor#322]
### General information

- json-editor version: 1.3.5
- SCEditor version: 2.1.3

### Expected behavior

SCEditor shows up as my string editor

### Actual behavior

It is just a plain text area

### Steps to reproduce the behavior

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sceditor/2.1.3/themes/default.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/sceditor/2.1.3/sceditor.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sceditor/2.1.3/formats/xhtml.js"></script>
```

This is in my index.html. It appears SCEditor is no long dependent on jQuery which is nice for page footprint. Below is an example of my schema.

```javascript
{
    "genetics": {
        "format": "html",
        "options": {
            "wysiwyg": true
       },
       "title": "Genetics",
       "type": "string"
    }
}
```

**Comment by pmk65** [comment]
I had problems getting SCEditor to work in my JSON-Editor Playground too.
But with the right libraries (You'll need the jQuery version), it does work. See this example: https://is.gd/DkuS3B

The files I include:

>    https://cdn.jsdelivr.net/npm/sceditor@latest/minified/themes/default.min.css
>    https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
>    https://cdn.jsdelivr.net/npm/sceditor@latest/minified/jquery.sceditor.min.js
>    https://cdn.jsdelivr.net/npm/sceditor@latest/minified/formats/bbcode.js
>    https://cdn.jsdelivr.net/npm/sceditor@latest/minified/formats/xhtml.js

**Comment by freiguy1** [comment]
That did work for me, thanks! I guess this is closed then.

**Comment by schwemmer** [comment]
I couldn't get SCEditor to work either. And the suggested fix did not work for me nor does the demo (see above: https://is.gd/DkuS3B) seem to be working in any browser. I ended up integrating Jodit manually.

**Comment by pmk65** [comment]
The Playground examples have been updated to work with the develop/2.x branch (Which also includes a Jodit based editor) As I have refactored several of the editors and separated editors like SCEditor from the string editor.
The develop/.2.x branch has several new editors and features.

**Comment by schwemmer** [comment]
Thanks! Is there a way to install the develop/2.x branch via npm or when will it be released?

**Comment by pmk65** [comment]
@schwemmer I don't think it's available at npm yet, but you can clone the develop/2.x branch and create a custom build. https://github.com/json-editor/json-editor/tree/develop/2.x

Here's a list of some of the changes introduced in the 2.x version: https://github.com/json-editor/json-editor/issues/450

And here's a Playground page that uses a 2.x version of the library (not the latest) so you can see some of the new editors. (If you try the SCEditor, you need to change the format from `html` to `xhtml`, then it will work) https://pmk65.github.io/20test/dist/demo.html

**Comment by schwemmer** [comment]
Thanks @pmk65 (for all your work! json-editor is super useful!). I might try the 2.x branch, although I now got it working fine with the latest 1.4.x release and attaching Jodit manually based on a class.

The demo/playground does not work for me in Brave, Chrome, Firefox or Safari unless I am missing something. Shouldn't I see a form?

**Comment by schwemmer** [comment]
Sorry, I did not load an example... It works. Maybe make it default to one of the examples?

**Comment by pmk65** [comment]
> 
> 
> Sorry, I did not load an example... It works. Maybe make it default to one of the examples?

It remembers the last schema/setup you used. So if you close the page and reopen it later it will use your previous schema/setup. (Unless you use a direct link)

**Comment by schwemmer** [comment]
I see. SCEditor does not work in the playground (unless I am missing something again), Jodit works.

**Comment by pmk65** [comment]
> 
> 
> I see. SCEditor does not work in the playground (unless I am missing something again), Jodit works.

Change the schema format from `html` to `xhtml` in the SCEditor example.

**Comment by schwemmer** [comment]
> Change the schema format from html to xhtml in the SCEditor example.
Um, yes, indeed, and you told me so before – this is embarrassing. Sorry for that. I changed the format in the schema to `xhtml` and clicked on "Generate Form" and it worked.
