### ISSUE TITLE
Input format - oneOf error

### ISSUE THREAD

**Issue by y25ean** [json-editor/json-editor#323]
### General information
When using oneOf to select a date or datetime input, an uncaught type error occurs.

- json-editor version: 1.3.5

### Expected behavior
Enable user to select between date and datetime formatted inputs.

### Actual behavior
Uncaught TypeError

### Steps to reproduce the behavior

Direct link to example: The direct link did not work with this error.

```javascript
{
  "title": "Test",
  "oneOf": [
    {
      "title": "Test1",
      "type": "string",
      "format": "date"
    },
    {
      "title": "Test2",
      "type": "string"
    }
  ]
}
```

**Comment by pmk65** [comment]
Probably related to #312
