### ISSUE TITLE
setValue() for integer datetime-local not working

### ISSUE THREAD

**Issue by lucas-lotr** [json-editor/json-editor#324]
### General information
setValue() for integers formatted as datetime-local does not work.
- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcICWA7MMDmMBOIA0IAZgPbYC2AhmAiACZUxhJkwC0ANsQMYXsgC+QA=&value=&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

- Create any schema with an integer formatted as datetime-local (like in the demo link above;
- Manually set the date through the browser's default datepicker;
- Change the value in the JSON output;
- Click "Update Form";

```javascript
{
  "type": "integer",
  "format": "datetime-local"
}
```

P.S.: I checked the code and found the problem, however I am new to GitHub and have not yet found a way to create a pull request with the suggested fix.

**Comment by pmk65** [comment]
> 
> ### General information
> 
> setValue() for integers formatted as datetime-local does not work.
> 
>     * json-editor version:
> 
> 
> ### Steps to reproduce the behavior
> 
> Direct link to example: [https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcICWA7MMDmMBOIA0IAZgPbYC2AhmAiACZUxhJkwC0ANsQMYXsgC+QA=&value=&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction](https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcICWA7MMDmMBOIA0IAZgPbYC2AhmAiACZUxhJkwC0ANsQMYXsgC+QA=&value=&lib_switcher=&prompt_before_delete&upload=function(a,b,c)%7Bconsole.log(%22Upload%20handler%20required%20for%20upload%20editor%22)%7D&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)
> 
>     * Create any schema with an integer formatted as datetime-local (like in the demo link above;
> 
>     * Manually set the date through the browser's default datepicker;
> 
>     * Change the value in the JSON output;
> 
>     * Click "Update Form";
> 
> 
> ```js
> {
>   "type": "integer",
>   "format": "datetime-local"
> }
> ```
> 
> P.S.: I checked the code and found the problem, however I am new to GitHub and have not yet found a way to create a pull request with the suggested fix.

@lucas-lotr Please post a code snippet of the fix you made.

**Comment by lucas-lotr** [comment]
> > P.S.: I checked the code and found the problem, however I am new to GitHub and have not yet found a way to create a pull request with the suggested fix.
> 
> @lucas-lotr Please post a code snippet of the fix you made.

Over at datetime.js the setvalue function should be:
`setValue: function(value, initial, from_template) {
    if (this.schema.type == 'string') {
      this._super(value, initial, from_template);
      if (this.flatpickr) this.flatpickr.setDate(value);
    }
    else if (value > 0) {
      var dateObj = new Date(value * 1000),
          year = dateObj.getFullYear(),
          month = this.zeroPad(dateObj.getMonth() + 1),
          day = this.zeroPad(dateObj.getDate()),
          hour = this.zeroPad(dateObj.getHours()),
          min = this.zeroPad(dateObj.getMinutes()),
          sec = this.zeroPad(dateObj.getSeconds()),
          date = [year, month, day].join('-'),
          time = [hour, min, sec].join(':'),
          dateValue = date + 'T' + time;

      if (this.schema.format == 'date') dateValue = date;
      else if (this.schema.format == 'time') dateValue = time;

      this.input.value = dateValue;
      if (this.flatpickr) this.flatpickr.setDate(dateValue);
    }
  },`
The only difference is in the construction of dateValue, it should have a 'T' in between.

**Comment by lucas-lotr** [comment]
The setvalue function on datetime.js should be:
```
setValue: function(value, initial, from_template) {
    if (this.schema.type == 'string') {
      this._super(value, initial, from_template);
      if (this.flatpickr) this.flatpickr.setDate(value);
    }
    else if (value > 0) {
      var dateObj = new Date(value * 1000),
          year = dateObj.getFullYear(),
          month = this.zeroPad(dateObj.getMonth() + 1),
          day = this.zeroPad(dateObj.getDate()),
          hour = this.zeroPad(dateObj.getHours()),
          min = this.zeroPad(dateObj.getMinutes()),
          sec = this.zeroPad(dateObj.getSeconds()),
          date = [year, month, day].join('-'),
          time = [hour, min, sec].join(':'),
          dateValue = date + 'T' + time;

      if (this.schema.format == 'date') dateValue = date;
      else if (this.schema.format == 'time') dateValue = time;

      this.input.value = dateValue;
      if (this.flatpickr) this.flatpickr.setDate(dateValue);
    }
  },
```
The only difference is in the constructuon of dateValue, it should have a 'T' in between.

**Comment by lucas-lotr** [comment]
On a related issue: when using strings formatted as datetime-local valid inputs trigger an error display:
"Datetime must be in the format "YYYY-MM-DD HH:MM"."
To fix that the regexp to validate datetime formats in validator.js should be:
```
 var validator = {
          'date': /^(\d{4}\D\d{2}\D\d{2})?$/,
          'time': /^(\d{2}:\d{2}(?::\d{2})?)?$/,
          'datetime-local': /^(\d{4}\D\d{2}\D\d{2}[ T]\d{2}:\d{2}(?::\d{2})?)?$/
      };
```

**Comment by pmk65** [comment]
The problem doesn't occur in Firefox (which has no datetime-local datapicker). But I was able to trigger the error in Chrome.
