### ISSUE TITLE
Range format has undefined value by default

### ISSUE THREAD

**Issue by Franciman** [json-editor/json-editor#326]
### General information
Hi, I find a strange behavior when using the `range` format for integers.
The value at which the slider starts, when generating the editor is `undefined`,
while if I use the `number` format or no format at all, the value of the field is set to 0 by default.

- json-editor version: latest

### Expected behavior
I think the expected behavior should be equal to that of `number` format.

### Actual behavior
The actual behavior is that even if the property value is set to 0 by default in the JSON (the JSON you see by pressing on `JSON` button), in the JSON Editor interface I see `undefined` as slider's value.

### Steps to reproduce the behavior

Here is a JSON Schema I tried:

```javascript
{
  "type": "object",
  "required": ["grade"],
  "properties": {
    "grade": {
      "type": "integer",
      "format": "range",
      "maximum": 10,
      "minimum": 0
    }
  },
  "title": "Student"
}
```

**Comment by germanbisurgi** [comment]
Hi franciman, and thanks for your posting the bug. I will fix this ASAP. You can use the 'default' property as a temporary solution like this: 

```
{
  "type": "object",
  "required": ["grade"],
  "properties": {
    "grade": {
      "type": "integer",
      "format": "range",
      "maximum": 10,
      "minimum": 0,
      "default": 0
    }
  },
  "title": "Student"
}
```

@pmk65 I think i will use the minimum value as a default in case the "default" prop is not defined.

**Comment by pmk65** [comment]
@germanbisurgi If the minimum value is used when no default value is supplied, the slider will be in wrong position.
I think it's better to set it to zero which is where the slider position will be. (I'll submit a PR)
