### ISSUE TITLE
Inconsistency between theme rendering 

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#329]
There's an inconsistency between how theme render the Description option. 
@schmunk42 This should be identical for all themes, so which one is (should be) the "correct" rendering?

Example using a Boootstrap Theme renders the `description` as HTML: https://is.gd/i8xfEc

Example using a Foundation Theme renders the `description` as TEXT: https://is.gd/hyGmII

(Both examples are identical except for the selected Theme.)

**Comment by pmk65** [comment]
@schmunk42 If there's no objection, I will make all themes accept *limited* HTML data in the description.
Currently you can inject JavaScript by using HTML description, but if it's parsed through some sanitizing function first, it should be safe.
````javascript
// Removes script, style, embed and object tags from HTML data before displaying
var sanitizeHTML = function(data) {
  var disallowed = ['script', 'style', 'embed', 'object'],
      container = document.createElement('div');

  container.innerHTML = data;
  disallowed.forEach(function(tag) {
    var el = container.querySelectorAll(tag);
    for (var i in el) {
      if (el.hasOwnProperty(i)) {
       el[i].parentNode.removeChild(el[i]);
      }
    }
  });

  return container.innerHTML;
};
````

**Comment by schmunk42** [comment]
Hmmm, shouldn't we rather whitelist the tags or go with TEXT.

I was just reminded to https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454 :)

What would be the use-case to allow HTML?

**Comment by pmk65** [comment]
> 
> 
> Hmmm, shouldn't we rather whitelist the tags or go with TEXT.
> 
That would require a larger list of tags to check for, and you will have to build a new DOM element, which would slow down the process. Blocking `script`, `style`, `link`, `embed` and `object` tags should be enough to prevent any form of JavaScript injection.

> I was just reminded to https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454 :)
> 
> What would be the use-case to allow HTML?

Using RegEx to filter HTML is almost impossible, as you can create create tags in so many different variations.
 In my example function I create a DIV element (not attached to the DOM) and add the HTML content. (This doesn't execute scripts etc.). Then I filter out all the `disallowed` tags (and their content) before returning the cleaned HTML back.
This also ensures that the HTML code is not missing any closing tags.

**Comment by schmunk42** [comment]
> Using TEXT would not allow you to put any formatted text in the description. So you are stuck with 1 line of text without linefeed.

Actually I'd be fine with that for a *description*, while links or bold tags would be nice, I see too many potential problems coming up, especially that you can break the editor with weird stuff in the descriptions.

How about using TEXT as a default and make HTML usage optional?

**Comment by pmk65** [comment]
> 
> 
> > Using TEXT would not allow you to put any formatted text in the description. So you are stuck with 1 line of text without linefeed.
> 
> Actually I'd be fine with that for a _description_, while links or bold tags would be nice, I see too many potential problems coming up, especially that you can break the editor with weird stuff in the descriptions.
> 

That's what the sanitizing function removes or cleans up. 
I made a JSfiddle to illustrate it: https://jsfiddle.net/uqc2gon1/

HTML content in 1st textarea is sanitized when you click the button, and the result is placed in the 2nd textarea.

Notice that the `SCRIPT` and `FORM` elements have been removed AND that the invalid HTML (the `DIV` and `A` tags missing the closing tags) have been fixed.



> How about using TEXT as a default and make HTML usage optional?

I would rather avoid having to add additional options.

**Comment by schmunk42** [comment]
```
<IMG SRC=javascript:alert(&quot;XSS&quot;)>
```
..goes through.

via https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Basic_XSS_Test_Without_Filter_Evasion

**Comment by pmk65** [comment]
> 
> ```
> ..goes through.

You are right. And that one is hard to check for as you can't rely on it starting with plain "javascript:".

But I got an idea that might solve it, and support both TEXT and HTML which doesn't require any additional config options. (You just have to load a 3rd-party sanitizing library if you want to use the HTML feature.)

1) As default it inserts the data content as TEXT.
2) But if [DOMPurify](https://github.com/cure53/DOMPurify) library is loaded, then sanitized content is inserted as HTML.

**Comment by schmunk42** [comment]
> But if DOMPurify library is loaded, then sanitized content is inserted as HTML.

Regarding the above and

> I would rather avoid having to add additional options.

why don't you like one more option? Yes, we have plenty of them, but I rather like to see an option than some auto-detection if a certain lib is loaded or not. That lib could also be loaded from another piece of code, how would you turn that off then?

How about `enable_html_descriptions` (or similar) here https://github.com/json-editor/json-editor#options?

**Comment by pmk65** [comment]
There would be no need to turn it off. 
If lib is NOT loaded, content is rendered as TEXT (including any HTML tags)
if lib is loaded, content is rendered as HTML. (If the content is plain text, it will render in the same way as if no lib is loaded.)

**Comment by schmunk42** [comment]
I meant for use-cases where you have the lib loaded, ie. from another lib, but you still want to make sure that descriptions are rendered as TEXT, to avoid any risk.
