### ISSUE TITLE
input_width of options is invalid when I set parent's array type to table if CSS Framework is HTML

### ISSUE THREAD

**Issue by Xiaoleng123** [json-editor/json-editor#330]
### General information

- json-editor version: 1.3.5

### Expected behavior
I expect the width of input to be the width I set.

### Actual behavior
The width of the parent <td> is the width I set, but the width of input is the default.

### Steps to reproduce the behavior
step 1. Set CSS Framework to HTML;
step 2. Set array type to table;
step 3. Set input_width of input options to a valid CSS width string(e.g. "300px");
step 4. Click the "Update Schema".

Direct link to example: https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iBwBDALbxCZMBhABdCWixk0kWNIShhYxKDClyIDGDQQcAcyaLIuNaBMl2YAPoB3CNzAALRCADMABj8SAA8QAF9CERMAGVgzT0QAFkJuWAAzIXZoRiQAWSIAAld3D3yIDHz/QJDwkEkbYjJvITQ0ISImVKw0ESFs8CFKOCZIGH1UKSZ2HAgOWABJMFgRNSN2WEIoJfrdRooaekZCEaGkcaYSBSUVbb1tBv1DYzMmWPYRfhA6XqZuLHNCShcXiEFgkSBDQhYTzoWTJNIZLLeX7mGqacg6W5IR4mf4gSwQax3OwOFxueJISrBMKhGlw9KZbJ8DG7EDIpho7x5QpkkplfI4KEVAJU0IyGmhIA===&value=N4IgdghgtgpiBcICyBPABAdwJYBMAuAFmlgM5oDMADJQA4AeIANCDTHiQgNqh4qsIgcAewDmTcNDiJUmXIWJkwQvBWr0QAXwC6GoA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=html&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "name",
    "pets"
  ],
  "properties": {
    "name": {
      "type": "string",
      "options": {
        "input_width": "300px"
      },
      "minLength": 4,
      "default": "My width is 300px"
    },
    "pets": {
      "type": "array",
      "format": "table",
      "title": "Pets",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "title": "Pet",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "cat",
              "dog",
              "bird",
              "reptile",
              "other"
            ],
            "default": "dog"
          },
          "name": {
            "type": "string",
            "options": {
              "input_width": "300px"
            }
          }
        }
      },
      "default": [
        {
          "type": "dog",
          "name": "My width is not 300px"
        }
      ]
    }
  }
}
```

**Comment by pmk65** [comment]
IIt works if you use a different Theme (Bootstrap etc.), as they set the width of the input to 100%, so the parent is used to control the size.
But you can use the `inputAttributes` option instead. This will allow you to set specific styles/classnames etc. on the actual input field. Example: https://is.gd/ygN3aw

**Comment by Xiaoleng123** [comment]
> @Xiaoleng123 It works if you use a different Theme (Bootstrap etc.), as they set the width of the input to 100%, so the parent is used to control the size.
> But you can use the `inputAttributes` option instead. This will allow you to set specific styles/classnames etc. on the actual input field. Example: https://is.gd/ygN3aw

Fine, thanks for your advise, I will use the `inputAttributes` instead. The reason I ask the question is that it makes me confused, but this may not be a issue.😄
