### ISSUE TITLE
Checkbox Input elements are inside the Label elements

### ISSUE THREAD

**Issue by tolgaparlan** [json-editor/json-editor#336]
### General information
Checkbox Input elements (both with schema elements and when choosing Properties) are generated inside the Label elements, and not after/before them as it's normally done. This is bad semantics and produces problems when your styling relies on this fact.

- json-editor version:1.3.5

### Expected behavior
Normally a label and its input element are placed next to each other as it can be seen here: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox). 

### Actual behavior
This is what ends up getting generated in for example [https://json-editor.github.io/json-editor/](https://json-editor.github.io/json-editor/):
`<label class="checkbox" style="display: inline-block; font-weight: normal;">
age
    <input type="checkbox" disabled="" style="width: auto; display: inline-block;">
</label>`

### Steps to reproduce the behavior
Just check the HTML code produced.

**Comment by schmunk42** [comment]
Could you provide a demo link?

**Comment by tolgaparlan** [comment]
I suppose [this](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGiodAFvQDWlLAA8exMohAiscAIZ5CAMyxoAtvMZJ+QkeMKQY5ENnWwABLrrCxIAL6OgA===&value=N4IgxgFgpmDWBGB7AHiAXAFwE4FcoF8g&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) would demonstrate. If you inspect the HTML in the checkbox section, you can see that the checkbox input is nested under the label tag, instead of next to it:

`<label class="checkbox" style="display: inline-block; font-weight: normal;">some checkbox<input type="checkbox" name="root[checkbox]" style="width: auto; display: inline-block;"></label>`

**Comment by pmk65** [comment]
From [w3](http://www.w3.org/TR/html401/interact/forms.html#edef-LABEL): The label itself may be positioned `before`, `after` or `around` the associated control. Either one is valid.
Wrapping the `label` tag around the `input` tag allows you to skip the `for` attribute,

**Comment by germanbisurgi** [comment]
and its used for bootstrap checkboxes too
<img width="974" alt="Bildschirmfoto 2019-04-26 um 14 48 30" src="https://user-images.githubusercontent.com/13135260/56808728-77daeb00-6832-11e9-8b6e-ce0abf6c8bac.png">

**Comment by schmunk42** [comment]
>  produces problems when your styling relies on this fact

I think it also produces problems when your styling relies on the fact that it is before or after.
I don't think it's *bad* semantics, I agree with @pmk65 that it is valid.

There could be an option to specify whether you want inline, before or after for checkbox labels, but I also think this might be a bit overkill.

Are there other CSS frameworks which require the label before or after?
Should/could the theme handle it?

**Comment by pmk65** [comment]
> 
> 
> Are there other CSS frameworks which require the label before or after?
> Should/could the theme handle it?

The Materialize Theme set the `for` attribute on the `label` tag in the function `getFormControl `
But it still wraps the `input` tag inside the `label` tag, which is correct according to the Materialize [documentation](https://materializecss.com/checkboxes.html),

**Comment by germanbisurgi** [comment]
Also label wrapping the input will make the label clickable, for example when using checkboxes clicking on the label will tic/detic the checkbox
