### ISSUE TITLE
How to programatically delete array elements and refresh tabs

### ISSUE THREAD

**Issue by plueschpruem** [json-editor/json-editor#338]
I am really stuck.

I have a schema that gets filled via JSON and renders just as I need it to.
It's 2 layers of arrays - products and product attributes.
So I have tabs to the left and in there are general product info on top and another array with tab bar for the attributes.
Just like the examples basically.

Then I added my own buttons to each product and attribute connect to an API I am talking to - basic stuff like save changes, make new attribute, delete attribute.
Saving - no worries. Reloading the answer from the API is also working.
New attribute works fine and is also updated into the JSON once the server returns the dataset.
Delete works API wise, but then I need to clear out the deleted item from my editor.
Using
```
var partRemove = editor.getEditor(dataPath);
partRemove.destroy();
```
Removes the part, but not the tab itself and the tab button.
Also after that I get errors when changing tabs
```
Uncaught TypeError: Cannot read property 'classList' of null
```
So what is the proper way to remove stuff from the array and update my tabs and tab navis?
Using a JS fake click on the editor provided (and in my case hidden) buttons cannot be the right way…
I also need my own buttons because there are extra forms to display for editing and new attributes.

**Comment by pmk65** [comment]
@plueschpruem Could you provide an working example, using this: https://pmk65.github.io/jedemov2/dist/demo.html
There's a function in editors/object.js called `removeObjectProperty`. I think it's that one you need to call in order to remove the entire row.

**Comment by pmk65** [comment]
Closing issue due to lack of feedback.
