### ISSUE TITLE
Any tips on how to implement Bootstrap3 date picker?

### ISSUE THREAD

**Issue by roypardi** [json-editor/json-editor#34]
I'm no JS hero but I want to take a stab at using this [Bootstrap3 date picker](https://eonasdan.github.io/bootstrap-datetimepicker/) instead of the HTML5 date picker.

Has anyone already done this or can suggest where to start? I've been looking through the old [issues from the jdorn site](https://github.com/jdorn/json-editor/issues/654) and seen a few hints but I thought I would ask here.

**Comment by marc7000** [comment]
Create a "datepicker.js" editor class, look at the "[editors](https://github.com/json-editor/json-editor/tree/master/src/editors)" section, e.g. "[checkbox.js](https://github.com/json-editor/json-editor/blob/master/src/editors/checkbox.js)".
The template or the "theme" for the datepicker plugin could be added in the "[bootstrap3.js](https://github.com/json-editor/json-editor/blob/master/src/themes/bootstrap3.js)" theme or append it directly in "datepicker.js" editor class.

**Comment by roypardi** [comment]
I found this implementation of spectrum at the old jdorn site. Seems to work.
https://github.com/hellobugme/json-editor.zh-CN/tree/master/plugin/spectrum-editor
