### ISSUE TITLE
"oneOf" with "$ref" don't work,

### ISSUE THREAD

**Issue by lovelyserafima** [json-editor/json-editor#340]
Hi, I want to do one of two fields required: "A" or "B". But I got an error in console: Uncaught TypeError: Cannot read property '$ref' of undefined.

Some piece of code:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "additionalProperties": false,
  "title": "File",
  "oneOf": [
    {
      "required": [
        "A"
      ]
    },
    {
      "required": [
        "B"
      ]
    }
  ],
  "properties": {
    "A": {
      "$ref": "#/definitions/A|B"
    },
    "B": {
      "$ref": "#/definitions/A|B"
    }
   }
}
```

[edit @schmunk42] added formatting

What can I do with it?

Thanks.

**Comment by schmunk42** [comment]
When trying the schema https://is.gd/BAz2Wf

I get

```
[
  {
    "path": "root",
    "property": "oneOf",
    "message": "Value must validate against exactly one of the provided schemas. It currently validates against 2 of the schemas."
  }
]
```

**Comment by lovelyserafima** [comment]
Okay, sorry for misunderstanding.
So, what is wrong? Why I can't write in this way?

**Comment by schmunk42** [comment]
First of all, I don't know if this is JSON-schema v7 specific, we're currently only supporting up to version 4.

Moreover I don't understand how the `required` definition in `oneOf` should work in your schema, maybe you can create a more concrete example.

Lastly, do you have a definition under `#/definitions/A|B` available? Is the `|` pipe just in the filename or does it have a special meaning?
