### ISSUE TITLE
How can I auto-complete the field of an array element?

### ISSUE THREAD

**Issue by pauldamian** [json-editor/json-editor#341]
### General information

I followed [this wiki](https://github.com/json-editor/json-editor/wiki/Adding-AJAX-autocomplete-using-Typeahead-&-Bloodhound) to get auto-complete working on a simple object field at the top of my schema.

Now I'm trying to do the same for a field of an array object and I cannot get it working.
Also, I couldn't find any solutions online.

- json-editor version: 1.3.5

Imagine the following schema:

```javascript
{
  "title": "Store",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "products": {
      "type": "array",
      "items": { 
        "type": "object",
        "properties": {
          "name": {"type": "string"},
          "price": {"type": "number"}
        }
      }
    }
  }
}
```

I am able to autocomplete the store name, but I don't know how to proceed with the product name.

Do you have an example?

**Comment by schmunk42** [comment]
This might be related to delayed initialization of the auto-complete input, since it's in an array.
Do you see any errors in console log?

CC: @pmk65

**Comment by pauldamian** [comment]
There are no errors in the console log.
I was able to _almost_ achieve it using this js code

```javascript
    var element_pattern = new RegExp("^root.products.\\d$");
    var watcherCallback = function(path) {
        var product_code = editor.getEditor(path);
        if (product_code) {
            $(product_code.input).typeahead({
              hint: true,
              highlight: true,
              minLength: 2
            },
            {
              name: 'product_codes',
              source: substringMatcher(Array.from(Object.keys(catalog)))
            });

            // Change parent (wrapper) display from inline-block to block
            $(product_code.input).parent().css("display", "block");
        }
    }
    editor.on('change', function() {
        for (var key in editor.editors) {
          if (editor.editors.hasOwnProperty(key) && element_pattern.test(key) && !watched_elements.includes(key)) {
            editor.watch(key, watcherCallback.bind(editor, key + ".name"));
            watched_elements.push(key);
          }
        }
    });
```

Basically, I'm tracking all changes and if a new product gets added, I'll _watch_ its _name_ field.
_catalog_ is a list of products and and use watched_elements as a cache in order to avoid duplicate watching.

However, with the exception of the first product (which works as expected), all other product name fields offer suggestion after I provide some text and move focus to a different field.

**Comment by pmk65** [comment]
I would do it like this: https://is.gd/Vg65xR
The "ready" event is used for attaching the handler to the static fields and the "change" handler loops through the editors and attach the handler to the dynamic array elements.

**Comment by pauldamian** [comment]
Thanks @pmk65, that did the trick :)

**Comment by pmk65** [comment]
@pauldamian I added a new example to the [Playground](https://pmk65.github.io/jedemov2/dist/demo.html) page, where the Typeahead autocomplete is integrated as a custom editor. That will make it much simpler to use with arrays and different lookup engines.

**Comment by pauldamian** [comment]
Thanks, @pmk65, really appreciate it!
