### ISSUE TITLE
remove_empty_parameters causing fields to disappear when editing the json value manually

### ISSUE THREAD

**Issue by nvrnight** [json-editor/json-editor#343]
### General information

- json-editor version: 1.3.5

### Expected behavior
When remove_empty_properties is enabled and you edit/save the json value. The original editor fields should still be displayed.

### Actual behavior
The fields which don't exist in the json value disappear after clicking save.

### Steps to reproduce the behavior
initialize the editor with remove_empty_parameters set to true and a schema with at least a field that with an empty value.
click Edit Json
click Save

**Comment by nvrnight** [comment]
setValue seems to do the same thing.

if I assign a schema with a property, and don't include that property in the initial value, that field won't be shown.

**Comment by nvrnight** [comment]
Setting required_by_default seems to fix the issue.

**Comment by schmunk42** [comment]
Is this issue solved for you?

You might also want to look at the screenshots at the bottom here https://github.com/json-editor/json-editor/pull/337#issuecomment-491220389 - it's another approach to the problem with non-required fields.

**Comment by nvrnight** [comment]
The issue is still there, I've just worked around it by setting required_by_default. A field being required or not shouldn't make the field disappear when a value for that field is not provided.

**Comment by schmunk42** [comment]
Does this only apply for `string` fields or also others? An example link would be helpful (https://json-editor.github.io/json-editor/)

**Comment by pmk65** [comment]
@nvrnight Please post a live example of the problem using https://json-editor.github.io/json-editor/ Or https://pmk65.github.io/jedemov2/dist/demo.html
Without example or schema it's pretty hard to pinpoint the problem.

**Comment by germanbisurgi** [comment]
This is a perfect scenario for `show_opt_in`. It will make non required properties "optable", so if you don´t want them in the final value you can uncheck the checkbox near the editor´s title. And it will not dissapear.

**Comment by majkinetor** [comment]
This is still present, please reopen.

If I set `remove_empty_properties: 1` then this shows.  

To reproduce it:

1. load [Json-Editor Proof](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAJAZwMYAsCmBbAhnAXLMKgC7EAOeA9JQFaID2EAtChjgHT0BOA5pQCZdsAM2JMADABZKrLNgDEcADSQYcfumEBLCFuJbGifFHDQYhYugAexY6fPm4xAJ5l0xuImJcdPZaodCYW4cW2ACJ2tibC50XGAVMwc4WOx%2BRgAbZ2NhbAzEdETAwkwdABl0CB5iVGMAJiLAuHoyfUM7AOK4Hh9%2BAH1kegyAV0wII3CoADZGruAdMmHiPowtHhIPYABGAFZYzDhO8wBfI%2BPZwh1gjqTHYBc3Tav6f1u1YBa28Zvi956tfqDEZjCYEGZHZLAf79ABGqQA1sZvMN3G8oKdbucjnAAI5MSw2H5NYDBLihTbQljeLTIMIXd5kLgtdBcfToUEmCF3BZLIm%2FQifAzfSb2fl3QaYMjYWlIrgorkOLFoyHwWLCTbyASaHR6IWISgEukKu6M5ms5wAeS4Gi4xi24mNSv5cGefN%2BcFVmg1Wu0ui%2B%2BtdCWNDKZbnNVptdvEDuV6K5GMVASdFj0GXckzgAGZ2FBAPgggD4QQAsIIAGEEAYiCADhAoPmoIBBEEAQiCAARBi3XAKwggAkQQBcIPnABogUAbLcA3CAtwBMIMXALwgdbH%2BfrlfLhZb3ZbUA7xcA%2FCDluvFgdTwDMIFBVw2ey2O5vXu8HumIh8YTR0DKg2Y4KTyRmob0qT5741mq09W71FoiDYDCaZ9Og%2FB6H0dCMMYMYwMmKToDiwxaLE%2FDGAA2ti2xnncdSHGYAC637AKaYZshyorvFsbrvJ66qvpqGi%2BrqhiUHihq4ZC%2BjEGmmzZlsUCALggxbDi2hYbkuK5dlAgDaIEuB5HiudZQOWNaroAwiBjhulYVoAmiAjku5aAOwgwlluW%2BZjluu59sWxnDj2NmrgO47FkoVaFlONZTlAVkVpZ1lLvWTatju5aLlxJqhiyFG0dyEDXCKwaEBoKA%2BL%2BMGvgAPFoAB8WVkLlub9oWA75nuimLiexZQI2LaAIwgNUlvu%2BYroAbCBLs18m1kFikORJdaVhpqkTi2%2FY1sNq75nVjVQMeln5oAPCA1l2e6VjW%2BYVt21nlbZ9k9jVVm%2BeZAXbktqkDpWZUrmdi2%2BeWDkaTmgAoIA2bWiWOCn5pdg0di27krtWbZ1tWfkWVZ26Vk2%2B3dtp%2B4uWO7kzU1NX1RphbDVZYnzp9VbDvO7mLg2UCLi1M0%2Bfm9XQ2VbU6cuxYyd1lXHs2UCFvmB7lp9g1QIAWiDloAoiD5g5d3TnWo4Ng9xa809WWUIVBVFYeVWs4t%2BYdap6kabzonNutxZqyT4njlA%2BktT95YrhdlZqxr5aLXrUDGTVZtqZpOujrzS5ifJe5UwdpvlgZo45oACCAyaTIO1gOGmAOIgxbdu5Najh2Nv5k2bOo%2BjS5Y%2BJLZjuwcsK5QeUEfyCaBBX8EXHA%2BFJWiHpqt6zE6v67H4lEkXnqml6ENmdRQIAGCCLc5LaLfnm5bTVwu7cz1VsxzktebOWse9Lw2U6JLbO6ppnj4ASiBacWh6eYLUAaTuM8Z%2BtU3QxpDtQIABCAtpp9WXX9UCAIQgDb1eFLZ4F3QgZEYpaHZHFd4gYCBUXdMAVKyB0pfE2DlfKhURJiRnJnKAl0eqqRHkOceE5zLdnOnPTcmt3a627BvRqYljJGT3i2Q%2BVkT7aQFufS%2BDlr61lvnZe%2BNVn6v3fkub%2Bv9Fw5kAHgg64ayO2ktWbq9tR4EMnuFGqpCaoaUGqWR2R03ba11l7KsNDt41RMlAA%2BR8WHlQABSCwAJTsKviY7h6deEOxzEXFBuU0EtgwcnJcF8r5GWcXfceqlDFbzocuHs9sapM2VizFS7NObc3LIXeWnjADEIB2EKMkOZqUds1bBv9z41iHBJIcLVSniXLKWfxXZ37VhrApeJylfJLn7FuEyGlSaVkGqE3GujcbmOYUWbSd0AmcPOuWbB6kXHGXvudDRw4Gz73zkuTetClwCI0m%2FS2wif5%2FwkfVba3k6bDS7HdQ8HZhpNKrLHY83TJrTjKTUoJXZtpGz5oLYWNVobjybGk4updgCOnjGcJMkBjjACAA%3D%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=EQbQJghgLhC0DOBjAFgUwLYQA7WQKgF4AdYTAJwGsSBdAAgG9aAjCRCgczIHsBXAOzAAuWgGIAZgHZUANhkBuWuXYBLPrChcswgIwYFOMGFXt1mwbABMGWgF9gQA&theme=spectre&iconlib=spectre&object_layout=grid&template=default&show_errors=&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=1&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=1&disable_array_delete=0&enable_array_copy=0&array_controls_top=1&disable_array_delete_all_rows=1&disable_array_delete_last_row=1&prompt_before_delete=0&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=1&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)
2. set single value using json, then other input will dissapear. 

This doesn't happen with `remove_empty_properties: 0`.

![pimis bug](https://user-images.githubusercontent.com/85767/98169437-8789c400-1eec-11eb-8664-e824d832f81e.gif)
