### ISSUE TITLE
change properties programmatically?

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [json-editor/json-editor#344]
This is a question and might be a feature request:

Is it possible to programmatically change the `properties` of a schema element after initialisation?

I have a lot of properties that depend on each other. Like let’s say following example:
```
var editor = new JSONEditor(document.getElementById("editor_holder"), {
    schema: {
      type: "object",
      title: "vehicle",
      properties: {
        make: {
          type: "string",
          enum: ["car", "bicycle", "monocycle"]
        },
        wheels: {
          type: "string",
          enum: [1, 2, 3, 4]
        }
      }
    }
  });
```

I would like to be able to change the enum options of "wheels" based on the value of "make".

Let’s assume I want to match the weels enum choices to the number of wheels the selected vehicle type has like so:
```
make === car => wheels.enum = [1,2,3,4]
make === bicycle => wheels.enum = [1,2]
make === monocycle => wheels.enum = [1]
```

I would have to programatically check the make change and based on that change the wheels schema.

The documentation is not really clear, I tried:
```
make = editor.getEditor('root.make');
wheels = editor.getEditor('root.wheels');
editor.watch('root.make', e => {
  if(make.getValue() === "bicycle") {
    wheels.schema.enum = [1,2];
    wheels.container.innerHTML = ""
    wheels.preBuid();
    wheels.build();
    wheels.postBuild();
  }
});
``` 

This works but is unfortunate.
There should be something like `wheels.setSchema({
          type: "string",
          enum: [1, 2]
        });`.
That replaces the old schema and re-renders the HTML.

I tried to find a better way to do this in the documentation but could not.
What do you think, is there a better way already or not?

**Comment by schmunk42** [comment]
You could use `oneOf`, see example https://github.com/json-editor/json-editor/blob/master/docs/advanced.html

**Comment by ThibaultJanBeyer** [comment]
Hey @schmunk42 and thanks a lot for the fast answer!

Hmm, I’ve played around with the tool and it seems that what I want to achieve is impossible or extremely difficult (The above was just a try to simplify the problem which failed), maybe you can help me:

I have such data set similar to this:
```
{
  locations: {
    "united states": "us",
    "germany": "de",
    ...user should be able to add more locations...
  },
  information: {
    "us": {
       "users": 9,
       "beers": 10
    },
    "de": {
       "users": 2,
       "beers": 3
    },
    ...user should be able to add car model/price information based on the locations...
  }
}
```

For example, if a user adds a new `location` ("france": "fr") then, I would like to help the user by adapting the `infromation` part. In the just added france example, it should then look like this:

```
{
  locations: {
    "united states": "us",
    "germany": "de",
    "france":"fr"
  },
  information: {
    "us": {
       "users": 9,
       "beers": 10
    },
    "de": {
       "users": 2,
       "beers": 3
    },
    "fr": {
       "users": ...to be filled...,
       "beers": ...to be filled...
    },
  }
}
```

I face two issues:

1. How can I add an input field for the user to set a `key`:`value` pair of an object? 
2. How can I modify another input based on the first input. That seems to be something for [Dependencies](https://github.com/json-editor/json-editor#dependencies). But I don’t manage to do such a modification by just using the watch property. So I thought that a direct event listener that replaces the properties of an element might be useful.

What do you think? Thank you!

**Comment by schmunk42** [comment]
Hmm, I can't come up with a quick solution. 
If you can modify your data structure the locations data in the advanced example is pretty close to what you need.
In general I'd avoid modifying the schema, since it should be immutable, IMHO.

**Comment by pmk65** [comment]
@ThibaultJanBeyer I recently added some "onOf" examples to my playground page.
Also made a dynamic enum example a while ago. See https://is.gd/amdw1Q

**Comment by pmk65** [comment]
There's also the `dependencies` option available (Is present in current release but was missing from the documentation) And there's also the new **DescribedBy** editor available in the current git version.

**Comment by ThibaultJanBeyer** [comment]
That might work, thank you!
