### ISSUE TITLE
[req] Support for OptGroup in Select

### ISSUE THREAD

**Issue by dekimsey** [json-editor/json-editor#345]
### General information

- json-editor version: (v0.7.20, embedded in jenkin's [extended-choice-parameter](https://plugins.jenkins.io/extended-choice-parameter) plugin)

### Expected behavior

I'd like to be able to create `OptGroup` [elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) as part of defining a `Select`.

### Actual behavior

There appears to be no support for this behavior

### Steps to reproduce the behavior

Maybe an example implementation:

```javascript
{
  "title": "Dinosaur",
  "type": "string",
   "enum": [
      "Theropods": ["tyran", "velo", "deino"],
      "Sauropods": ["diplo", "salt", "apat"]
   ]
   "options": {
      enum_titles: {
          "Theropods": ["Tyrannosaurus", "Velociraptor", "Deinonychus"],
          "Sauropods": ["Diplodocus", "Saltasaurus", "Apatosaurus"]
      }
   }
}
```

**Comment by schmunk42** [comment]
AFAIK an `enum` has to be a flat list, see also https://github.com/guillotinaweb/ngx-schema-form/issues/118

How can this be covered by json-schema?

**Comment by pmk65** [comment]
You could probably modify the select list output in the "ready" event. 
Then if you add some pseudo values to the enum list you could check for those in the  "ready" event and modify the list accordingly. 

````javascript
"enum": [
 ">>>Theropods", "tyran", "velo", "deino", "Theropods<<<",
 ">>>Sauropods", "diplo", "salt", "apat", "Sauropods<<<"  
]
````

1) Test if value starts with ">>>", then find same value that ends with "<<<"
2) Create optgroup element, set label to value and insert it in list. 
3) Move "children" into optgroup.

**Comment by dekimsey** [comment]
I don't quite grasp the relationship of json schema and json-editor, so I apologize if this suggestion is out of whack. But alternatively, perhaps it could be handled the similarly to how Labels are handled. An option specifying which element the individual entries are an OptGroup of:

```
"enum": [
 "tyran", "velo", "deino",
 "diplo", "salt", "apat",
],
properties: {
  enum_groups: ["Theropods", "Sauropods"],
  enum_group_indexes: [1, 1, 1, 2, 2, 2],
  enum_titles: ["Tyrannosaurus", ...]
}
```

**Comment by schmunk42** [comment]
> I don't quite grasp the relationship of json schema and json-editor

You define a json-schema and json-editor creates a form and JSON output, see the first image in the README :wink:

**Comment by pmk65** [comment]
@dekimsey Here's an example of what I suggested earlier (Turns out you don't have to move any elements, just insert `optgroup` tags) https://is.gd/FfIbJm

**Comment by schmunk42** [comment]
Much nicer without the ending delimiters!

**Comment by pmk65** [comment]
I added a more generic version to the list of examples on the Playground.
This version doesn't require a know field key, but works on all available editors.
