### ISSUE TITLE
Draft-04 date-time format (relates to datetime-local format)

### ISSUE THREAD

**Issue by jramstedt** [json-editor/json-editor#347]
Draft-04 has date-time format for validation that is not currently supported.
https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-7.3.1

datetime-local validation is not working on Chrome 74.0.3729.169.
Input[type="datetime-local"] uses ISO 8601 style date values without timezone.

### General information

- json-editor version: 1.3.5

### Expected behavior
datetime-local should work and use ISO 8601 dates without timezone.
date-time both should work and use ISO 8601 dates.

### Actual behavior
date-time does nothing.
datetime-local validationdoesn't work on Chrome 74.0.3729.169.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "format": "datetime-local",
      "description": "This is an example schema.",
      "default": "2018-06-14T00:00"
    }
  }
}
```

**Comment by pmk65** [comment]
@jramstedt Could you try this https://github.com/pmk65/json-editor/tree/datefix and see if it solves the `datetime-local `problem?
