### ISSUE TITLE
Is there a way to extend json-editor fields?

### ISSUE THREAD

**Issue by OgAstorga** [json-editor/json-editor#354]
I'm working in a special field for a very specific application
(you can think of it as an HSL color picker rendered in SVG by d3.js)

I love how you handle your dynamic forms and I want to use your library in top of my project.

Is there a way I can generate a custom plugin to render mi input and handle all your form interactions (multiple inputs, changing order, collapsing a block, saving data, setting a default value, etcetera...)

Thank you very much for your time & for this library.

**Comment by pmk65** [comment]
You can create [custom editors](https://github.com/json-editor/json-editor#custom-editor-interfaces) (Also see the [wiki](https://github.com/json-editor/json-editor/wiki)) 
These can either be included directly in the library (PR's are welcome. 😄) or as a standalone extension. 
(I got some old examples on my [Codepen page](https://codepen.io/pmk/pen/RYEgde))

**Comment by pmk65** [comment]
@OgAstorga I just added some examples of creating custom editors, at the [Playground page](https://pmk65.github.io/jedemov2/dist/demo.html)
