### ISSUE TITLE
Hyper-Link DescribedBy Editor (Feature from old jdorn repo)

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#356]
There's an interesting PR at the old Jdorn Repo. "**Full support for the describedBy hyper-link standard to allow dynamically to extend schemas**" https://github.com/jdorn/json-editor/pull/322 
Basically it allows you to use variable inside ref parameters so you can switch between rendering based on previous values.

Live example: https://rawcdn.githack.com/gpetrov/json-editor/7e9dcbfa31bb13c9f499ad56c0fd57a56a486812/examples/describedby.html

I tried merging it with our branch (weeding out various merge errors), but it didn't work.
from what i can see, there's a problem with the ref lookup in the file: editors/describedby.js inside the `buildChildEditor()` function.

So something must have changed between our version and the old one. I haven't played around with refs much, so I could use some help here. 😃

**Comment by pmk65** [comment]
Turned out to be extremely easy to fix once I took a closer look at `refs` 😁 
I'll make a PR once I clean up the code..

**Comment by pmk65** [comment]
@schmunk42 @germanbisurgi @marc7000 This branch also makes some modifications to the file/folder structure of the src/ folder which we should implement.

1) New folder named **validators**. This folder contains custom validator code for each editor (So you don't have to merge it into the existing validator code in `validators.js`)
2) New folder named **resolvers**. This folder contains the code for activating each editor (so you don't have to merge code into `defaults.js`)

This allows you to remove editors you don't need before making a custom build. (Currently you will have to locate and cut out code from `validators.js` and `defaults.js`) As you just remove the editor files you don't need.

**Comment by thorstenfreitag** [comment]
This feature would be great. Thanks for merging. 
I just tried the example: https://github.com/json-editor/json-editor/blob/master/docs/describedby.html
But it doesn't seem to work yet. It seems as if it is not picking up the links in the schema properly.
Am I missing something or is it still WiP?

**Comment by pmk65** [comment]
@thorstenfreitag You will have to create  a custom build, as we haven't build a release yet. (CDN)

**Comment by thorstenfreitag** [comment]
Great, thanks.
Just tried and works like a charm!
