### ISSUE TITLE
Is there plan to support draft-06 or draft-07 schema?

### ISSUE THREAD

**Issue by happywisepaul** [json-editor/json-editor#359]
More and more tools now support only draft-6 and above schema, like https://jsonschema.net/.  Is there any plan to update Json-editor to support draft-6 and later, and if so what's the priority or approximate ETA?

**Comment by pmk65** [comment]
The development of JSON-Editor depends on people submitting PR with new features and bug fixes.
Most people like myself, focus on the features they need themselves.
So Draft6/7 support would probably be something added when one of the contributes need the features. 
PRs are welcome if you want to take the task?

**Comment by happywisepaul** [comment]
Thanks for the clarification of how this project moves forward.  As I am still in the early stage of adopting it at this point I'm happy with how the editor implements the draft-04 core and validation portions, which is what I need.  Probably my coping mechanism is to translate schema draft-06/7 generated by other tools into draft-04, or find a tool that generates draft-04 schema.  Some day if I feel I cannot live without draft-06/7 feature I'll do what you suggest (submit PR).
