### ISSUE TITLE
Enable/Disable editor

### ISSUE THREAD

**Issue by calpirro** [json-editor/json-editor#36]
Hi

is this functionality working in this version?

> `// Disable entire form
> editor.disable();
> 
> // Disable part of the form
> editor.getEditor('root.location').disable();
> 
> // Enable entire form
> editor.enable();
> 
> // Enable part of the form
> editor.getEditor('root.location').enable();
> 
> // Check if form is currently enabled
> if(editor.isEnabled()) alert("It's editable!");`

I'm getting this error: **Uncaught TypeError: Cannot read property 'disable' of undefined at f.disable (jsoneditor.min.js:95)** 

Thanks

**Comment by agladysh** [comment]
Same here.

**Comment by agladysh** [comment]
For me this didn't work because I used `ajax: true` and tried to call `disable()` before `ready` event was fired. This fixed the problem for me:

```
editor.on('ready', function() {
      editor.disable();
});
```

**Comment by germanbisurgi** [comment]
Hi calpirro,

There are three things i need to know from you in order to help.

1 Expected behavior
2 Actual behavior
3 Steps to reproduce the behavior

**Comment by schmunk42** [comment]
I think this is solved in the comment from @agladysh - also in the tests and examples there's an option to disable the editor.
