### ISSUE TITLE
New type, Dict / Associative Array?

### ISSUE THREAD

**Issue by mikey-b** [json-editor/json-editor#360]
### General information

I would like support for a Dict type - which uses the object notation with the object's properties being unique id's.

I would like to treat these like they they are arrays, but with a "key" value.

```javascript
{
  "1": {"name": "object 1"},
  "2": {"name": "object 2"}
}
```

Could someone briefly describe what this would involve to do?

**Comment by pmk65** [comment]
@mikey-b The format you listed above is not an array, but an object. 
You can display it using a schema like this:
````json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    }
  }
}
````
Live example: https://is.gd/tzIIg4

If you want to use Array format, you will have to leave out the id. 
Live example: https://is.gd/uzQnh5

If the format is fixed, could create a custom editor type and then display the data as you see fit.
