### ISSUE TITLE
Horizontal dependencies in grid mode doesn't work well

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#365]
When using **dependencies** option, the dependent field wrapper is shown/hidden depending on value.
In grid mode this hides the wrong element `this.control` but should hide `this.container`
Example: https://is.gd/996Azq

Currently the checkDependency defines the wrapper like this:
````javascript
  checkDependency: function(path, choices) {
    var wrapper = this.control || this.container;
````
@germanbisurgi Do you think it would be ok to swap `this.control` and  `this.container`

Example with the two swapped: https://is.gd/zQz3xE

Still not the optimal solution, as it still fails using Foundation themes. (try selecting Ice creams)
This is because Foundations forces `float:right` on the last element.

**Comment by germanbisurgi** [comment]
Right. But for what i saw all editors have (and should have a container). This to generalize features and in this case to prevent empty columns in grids, or just empty divs in the forms.
