### ISSUE TITLE
Array has residual values from previous value

### ISSUE THREAD

**Issue by cgunadi2018** [json-editor/json-editor#37]
When an array has a previous value of let's say 2 items, then I setValue(new value), where new value is an array of shorter length (one item), I saw the array editor correctly display the new value of only one item.

But when I hit the "Add Row" button to add another item, the old value from the old 2-item array is shown again. What I expect is that the new item will be blank.

Where could I have gone wrong?

Thank you so much.

**Comment by pmk65** [comment]
@cgunadi2018 Do you have a schema example you can post?

**Comment by pmk65** [comment]
Closed due to lack of feedback
