### ISSUE TITLE
Get a reference to editor using DOM without jQuery?

### ISSUE THREAD

**Issue by pm64** [json-editor/json-editor#377]
I have been using the deprecated jQuery-style initialization method, because this allows me to get a reference to the editor later using the DOM: $('#myDiv').data('jsoneditor')

Is there a way to get a reference to the editor using the DOM with the "standard" initialization method?
var element = document.getElementById('myDiv');
var editor = new JSONEditor(element, options);

Thanks!

**Comment by pmk65** [comment]
@pm64 Your variable `editor` will contains reference to the editor you created on `#myDiv`.
Try `console.log('editor', editor);`

**Comment by pm64** [comment]
Right, but my requirement is to get the reference using only the DOM -- for example, after "editor" is out of scope.

**Comment by pmk65** [comment]
Maybe you could do something like this when creating the instance? (untested)
````javascript
var el = document.querySelector('#form');
var editor = new JSONEditor(el,schema);
el.setAttribute('jsoneditor', editor);
````
And then to get the reference back, something like this.
````javascript
var el = document.querySelector('#form');
var editor = el.getAttribute('jsoneditor')
console.log(editor);
````

**Comment by pm64** [comment]
Thanks @pmk65. I had considered stashing the reference myself, but wanted to make sure json-editor didn't provide an "official" way to obtain it. Will give this a shot.
