### ISSUE TITLE
feature/doc: plugin activation is always global

### ISSUE THREAD

**Issue by devkral** [json-editor/json-editor#380]
I want to use the selectize plugin just for one JSONEditor instance and not for the others.
But the plugin activation is always global.
Is there a way to activate plugins only for one instance? It would be really helpful to configure plugins on instantiation (e.g. in options argument).
Can you please document or integrate ways to do this?

**Comment by pmk65** [comment]
@devkral Currently it's not possible due to the way Selectize (and Select2) is integrated.
But you are welcome to create a PR if you can make it more configurable.

**Comment by schmunk42** [comment]
How would it be here? https://github.com/json-editor/json-editor/pull/396

**Comment by pmk65** [comment]
> 
> 
> How would it be here? #396

Selectize and Select2 integration has always been global due to their "plugin" nature.
I don't know if the Choices editor uses same approach, or controls the choices.js from within the editor/schema.
