### ISSUE TITLE
Idea for new editor (UUID with autogenerated ID)

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#381]
I recently needed to have a unique id on array elements, and came up with this small editor solution.

**Example of new editor format [uuid] for string type**
Value must be a valid RFC 4122 uuid (Universally Unique IDentifier). If field has initial no value (startval) then a random uuid will be autogenerated
https://is.gd/QMh6iI

@schmunk42 @germanbisurgi Would it be worth including it in the package?

**Comment by schmunk42** [comment]
Yes, I think it would be nice.

**Comment by germanbisurgi** [comment]
I am sure some will be glad to have this feature :)
