### ISSUE TITLE
Compact options is ignored for object

### ISSUE THREAD

**Issue by lucarota** [json-editor/json-editor#382]
### General information

When the compact options is defined true for an object then the title should be hidden.

- json-editor version: 1.4.0-beta.0 

### Expected behavior

The title (Car in the example below) should be hidden.

### Steps to reproduce the behavior

Direct link to example: [demo](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2AYQIYBOcANJDHAGYD2hAtvvFjgBaIAm7aEp5O1AByTUIAZ2bhoMHAGNqdAfhlNg2eIQCuGKQF8yUuPACeAjKv4AjAFZplvA8EJoAjhsRP2zANp8KwbgDmiBBm%2BtI4AO4saGgocHwAumE4AoSCaIRIaOLmkuFwgcFm2HnhOMamzHCi6sEB9mXlyOhV%2FhBBIQ1lcFyU%2BBooKthwABrxUjB6vpHRsRLTfhXFODWEdV35CM3LcFExccDJm739g60A8uPhOnw3EDrAQA&value=ETI%3D&code=EQehAIBUAsFNwFIGUDyA5AogEwJYBcB7AJ3BwDsBnPAQzIGN4cLxqA3anAG2oCNPGy4PHHDsiOXv3AAdYACsKsXISKzp9ApQL8AdJwIBzABQByBUvzETAGnPLiASgDcwIA%3D%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jquery=0&lib_dompurify=0)

```javascript
{
  "title": "Car",
  "format": "hidden",
  "options": {
    "compact": true
  },
  "type": "object",
  "required": [
    "engine",
    "wheel"
  ],
  "properties": {
    "engine": {
      "type": "string",
      "title": "engine",
      "default": "X"
    },
    "wheel": {
      "type": "string",
      "title": "wheel",
      "default": "O"
    }
  }
}
```

**Comment by pmk65** [comment]
@lucarota For objects, the header/title is in the same container as the Collapse, JSON and Properties buttons. So hiding the header/title is a little more complicated than in the other editors,
As a workaround, you can hide it using CSS. See https://github.com/json-editor/json-editor/issues/294#issuecomment-462349328

**Comment by enniosousa** [comment]
I'm waiting for the release with this bug fix.

**Comment by pmk65** [comment]
@enniosousa you can clone the develop/2.x branch and build a custom version.

**Comment by enniosousa** [comment]
Thanks for the tip

**Comment by pmk65** [comment]
You can see a list of some of the major changes in #450
