### ISSUE TITLE
Combining string enums to build a object with one selection of a drop down or input value

### ISSUE THREAD

**Issue by creativeautomaton** [json-editor/json-editor#383]
### General information

- json-editor version: latest

### Expected behavior 

Slect drop down to select one option

### Actual behavior
select option works fine, looking to have one selected option add an object{} to that property instead of a single string.

 
 

```javascript
{
  "title": "test",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "enum": [
       " { 'key': 'value',  'key': 'value' } ",
       " { 'key': 'value',  'key': 'value' } "
      ],
      "description": "This is an example schema.",
      "default": " "
    }
  }
}
```

**Comment by creativeautomaton** [comment]
Any help would be nice or really direction to point me in.

**Comment by pmk65** [comment]
The `enum` property has to be an array, not an object.
If you want to have different title/values, you'll need the `enum_titles` property or `enumSource`.
