### ISSUE TITLE
Remove "rating" editor from package

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#389]
Currently we got 2 rating editors, "rating" from the old repo and my "starrating".
I suggest we remove the old "rating" editor.
1) It only works with integer. "starrating" works with both integer and strings.
2) It has display issues (stars jump up and down when you hover or click)
3) Styling is hardcoded inline.
4) Doesn't respect enable/disable and other features.

@schmunk42 What is your opinion?

**Comment by germanbisurgi** [comment]
One that does more is better. We could resolve the old format into your new rating editor for fallback.
