### ISSUE TITLE
Start with entire form expanded?

### ISSUE THREAD

**Issue by tonebender** [json-editor/json-editor#39]
Hello,

This issue is a duplicate of the one I wrote on the original jdorn-json-editor repository.
It's a fairly basic problem that I haven't been able to solve:
When I create my form from my schema, adding the data from my data object, only the elements in the form that actually has data are shown (expanded). I need to click on Object Properties in the form and check the additional elements I want to show.

I was advised to use this call:
editor.root.setValue(data, true);

But I wasn't able to get it to work. Can anyone please help me out a bit more with how to use that?
I tried with:
editor.root.setValue(my_object_with_data, true);
... but not sure what I'm doing wrong.

Thanks in advance!

**Comment by fxi** [comment]
I think I've the same issue. 

The `initial` parameter in setValue set to `true` does not what I expect.

I can't open all editors by default when there is some missing values in `startval` data.

So, I found an ugly workaround to this issue : merging `startval` with the an output of `getValue()`:

```js

var statval = `<obj with missing values>`;
var schema = `<schema>`
var editor = new JSONEditor(`<element>`,{
    schema: schema,
    startval: startval
});

if(startVal){
    var baseVal = editor.getValue();
    var startVal2 = merge(baseVal, startVal);
    editor.setValue(startVal2);
}
```
For some `merge` function, you could use something in https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge

Please add a comment with a cleaner solution :)

**Comment by schmunk42** [comment]
Could you put together an example, ie. based on https://jsfiddle.net/tmunk/zxdk5qLd/

Would using `"require": true` make a difference?

**Comment by fxi** [comment]
`required` seems to do what I need, but it's not well documented : it's only mentioned in the editor defaults under `required_by_default`, unless I've missed something.

By the way, I've build a simple json-editor toy example in jsfiddle : 
https://jsfiddle.net/fxi/9gnL6t0p/1/

The version of json-editor is maybe not up to date, though.

So, all good for me.

Json-editor is a complex beast...  Thanks to maintain it  !
