### ISSUE TITLE
programmatically changing boolean does not stick

### ISSUE THREAD

**Issue by hungerburg** [json-editor/json-editor#392]
This is still with the old jdorn source, though no changes to current code. On a boolean editor of type checkbox try as below:

- call editor.getEditor(foo).setValue(bool),
- editor.getEditor(foo).getValue() shows value of `bool`,
- editor.getValue() does not reflect the change,
- call editor.getEditor(foo).onChange(`true`) to make it stick

Is the checkbox editor missing an argument (probably `value != initial`)?
 - https://github.com/json-editor/json-editor/blob/71968e2c087526b33013e260473b4a79e4f6d059/src/editors/checkbox.js#L5 -

**Comment by pmk65** [comment]
@hungerburg Try calling `setValue()` twice. (Known issue)

**Comment by schmunk42** [comment]
Would be great to have a test for programmatically changes. CC: @germanbisurgi

**Comment by hungerburg** [comment]
Stepping through with the debugger, `initial` seems not useful, probably just unconditionally let bubble?

**Comment by pmk65** [comment]
@hungerburg Can you make a live example? 

I think it's due to how the checkbox is toggled in combination wit the event type.

From checkbox.js/setValue:
````javascript
   this.input.checked = this.value;
````
This will not fire the change event on the checkbox element.
Instead you will have to do it like:
````javascript
  this.input.setAttribute('checked',this.value);
````
Then the change event is fired on the checkbox element.

**Comment by hungerburg** [comment]
Hello @pmk65 Reading up on DOM manipulation, nothing in any standard requires the difference in behaviour that you observe. I rather not base a fix on that.
The string-editor works for me, if the input is dirty, pass true to onChange…
https://github.com/json-editor/json-editor/blob/71968e2c087526b33013e260473b4a79e4f6d059/src/editors/string.js#L57

**Comment by pmk65** [comment]
@hungerburg I think this will do it: 
````javascript
  setValue: function(value,initial) {
    var changed = this.getValue() !== !!value;
    this.value = !!value;
    this.input.checked = this.value;
    this.onChange(changed);
  },
````
(`changed` var must be set before setting `this.value`, otherwise `getValue()` will return the new value)

**Comment by hungerburg** [comment]
@pmk65 That looks good to me

Just a user here, though, who wants to be useful. If that goes in, I can skip my workaround on next update…
