### ISSUE TITLE
Should I treat this as the primary fork?

### ISSUE THREAD

**Issue by jstnlef** [json-editor/json-editor#4]
I'm looking to write an Angular4/5 wrapper for this project and was wondering if I should use this as the starting point or the original jdorn one?

**Comment by loganvolkers** [comment]
The original project is not accepting pull requests and hasn't had contributions in awhile.

We are trying to contact the original author to officially move the project: https://github.com/jdorn/json-editor/issues/800

In the meantime, I would suggest that you build off this fork, but we have yet to publish to NPM (see #5)

**Comment by jstnlef** [comment]
Sounds good. Thanks

**Comment by schmunk42** [comment]
@danielo515 We merged over a dozen PRs from the original repo, please see https://github.com/json-editor/json-editor/commits/master - but it's time to create a real `CHANGELOG.md` now 😄

**Comment by loganvolkers** [comment]
Closing this issue. See #5 for progress on making this fork official.
