### ISSUE TITLE
React support?

### ISSUE THREAD

**Issue by narciero** [json-editor/json-editor#40]
Are there any plans to create a json-editor React.js component?

Thanks!

**Comment by photz** [comment]
I'm currently using the editor in a React-based project by wrapping it in a custom element:
https://github.com/photz/content-client/blob/master/json-editor.json
You can then use it like so from within React:
```<json-editor initial-value="..." schema="..."></json-editor>```
I wrote it in a rush and it's a bit messy, but it certainly does its job and works well enough.

**Comment by narciero** [comment]
The link you posted returns 404...but yea it would be great to have an 'official' react component as part of this lib, id be willing to help contribute.

**Comment by photz** [comment]
Thanks, I fixed the link!

**Comment by schmunk42** [comment]
@loganvolkers Is the Mozilla lib a full replacement for json-editor?

@narciero What would be needed to make this a react-component?

**Comment by s-a** [comment]
`import '@json-editor/json-editor'` resolves to object instead of function. I guess there is missing something like an AMD loader in there. Any news on this thread?

**Comment by marc7000** [comment]
Use `import JSONEditor from '@json-editor/json-editor'` works with Vue.js and Angular 2.

**Comment by s-a** [comment]
This does ironically work in react development but not in production build. I use `node node_modules/react-scripts/bin/react-scripts.js build` to build react app for production deplyoment.

**Comment by schmunk42** [comment]
@crisu83 Can you shed some light on this? (since you're working a lot with react)

**Comment by crisu83** [comment]
@schmunk42 looking at the code it seems that this editor uses jQuery and DOM manipulation, and usually React doesn’t play very nice with DOM manipulation, so I’m not sure.

**Comment by schmunk42** [comment]
@crisu83 Thank you for the feedback!

**Comment by Dids** [comment]
@marc7000 Can you confirm it's supposed to work with Vue? I can partially see editor elements, but it's throwing the following error: `TypeError: (new _json_editor_json_editor__WEBPACK_IMPORTED_MODULE_6___default.a(...)) is not a function`

**Comment by pmk65** [comment]
I don't understand why info like this isn't added to the documentation or wiki?
The same questions pop up again and again because there's no info in the documentation.
Same goes for new features that are not documented. 😞

**Comment by VadimTikhonyuk** [comment]
> @Dids yes i can, i had a sample project, but i already deleted it. when i have time, i check it again and add it to the documentation.

Hi, so where I can find, looks like Wiki page doesn't have article about this

**Comment by butters16** [comment]
I decided to use this in my react code
```javascript
const JSONEditor = require("@json-editor/json-editor").JSONEditor;
```

with my entire component looking like this (although it's rough and i'm likely to refactor it as i actually start to develop, but coding practices are not the point of this thread 😉)

```javascript
import React, {useEffect} from 'react';
import schema from "./schema.json"
import "@fortawesome/fontawesome-free/css/all.css"
const JSONEditor = require("@json-editor/json-editor").JSONEditor;

const BuildView = () => {
    useEffect(() => {
        const element = document.getElementById('editor_holder');
        const editor = new JSONEditor(element, {
            schema: schema,
            display_required_only: true, // circular references will blow up without this
            theme: 'bootstrap4',
            iconlib: 'fontawesome5'
        });
    }, []);

    return <div id='editor_holder'></div>
};

export default BuildView;
```
