### ISSUE TITLE
Suggestion: Replace SCEditor with a non-jQuery Editor

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#400]
@schmunk42 @germanbisurgi @marc7000 
SCEditor has some problems with JSON-Editor (See #79) and requires jQuery.
I suggest we replace it with another **standalone** WYSIWYG editor. (There's a good list here https://github.com/JefMari/awesome-wysiwyg#standalone)

I recently did an experiment on creating an WYSIWYG JSON-Editor editor using [Jodit](https://xdsoft.net/jodit/), which supports both `iframe` and `contenteditable` modes.
Live test link [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAJASwCZwFy2ACwC44A4DOaA9CQKYAeAhgLb4A25AdAMYD2tJ1ATj9QE9CzQqyzla1ZgCtC7CHAA0kGHHijxk9JlwFSJWfIC0GiVPY8A5iWT8AZjiMAGAOwlTkgMRKVmZOVEeRHwcRHltOABBKB5yfFjCcggcalD5KHY7KGoofHIeOQhFKA56aggBYotLcsQAL1SwooyeXIZqVnIfaEwcATyI4HYAI2lyVhxu1WB49jyeUIDtcB7p3n4BZd8Yab6B4Aw4dcEpnenEHAlCLdWz3v6ug8xCHCCIS1O7zDsLSUmnuAAdyEiGBH2AyluZzgczSEGuTxWX2hwGk7GQFxuyLucHEiEsuG0ACYnE5tsiAL7ks5UqFQWk0yEol6NVhYnHAPaPQ7AF5vcFMjk%2FHh%2FQbAwiggQC6mYWFNBEYJHIuBojH%2FRUylF4gnqqAAFlJguxcBwmm5fl4AGs4Jr6TKGTsHbSKcAgA&value=EQbwOgdgBFbAhgJ0fAnnAXFA2pGM54AHIgGwFM4AaPfOAexQgHNLhaBdG6WYAZwAu8AQEsAxpl4AJcqVL04kAL7AgA%3D%3D&code=EQehAIEsDsGMBsCuATApgYQMqYBQB1gALAF2IAcBnALjFmWgCsKA6BAexQDN4BDAJ1Ss2AWxA8GPAB4h4kAEYUQDNskjEQAZmYBGZgE4ATEpVrmwmKwoUCASjzQwUOEjQApXARLlqtek1bwHMjc%2FIKwImIS0rIKxqrqWrqGcabm0MxMtvb2jgBifCLgFHywIIjEkLIVqCxM4DwU4MSEkI2t4NBsxOCokmRsFKjI4ADmgXI88PAAnvYAbvzgACStZLwwbHIMqLDdALzgnIhwFWzQOOCbDOA24ADe9uBQnOA4xNNkqGwvV%2BAAhHsDgQrjtiARwAAfCGXLbMTpoAAqH1QkOhOF%2BAIO0EQU3AADI8TDroCDldmAB3GDINjkmy3B7QJ5PATERB8RmcSaDADcj3AAF8%2BZAXujYeFoBRiHxELs2Hx8YS%2FgB5Lag5hkArELrI5iEBpK8nQAAKBU%2BfHerEm8FFDCEEqlMq1fHVmu1nwANOACK0TV03aglZxbPS%2BczUKz2YcuaheYyBXyWWzGQ6Y%2FZ%2BbGchB8oViqVypU1JAahlGg0mi02o1Ot1ev1BsMxpsrbNoAt5UtesRUNBhgcjidIGccGhJTAeKdoCG422ihwSqhPZB3Rq2Gb3rGnpw5ThIHttNyoAAefgjRDCbvEFjwbsjZoHyAAagfU6Zs7ZsBRBxPZ4vFAA2pAAC6G5Mlu8o4Cua7TE4b7zi%2Br7PDgfwUHOH66vqhq%2BlBEGmqg5rTHS4DihU2KpnGr7CjgKHvqgf6QXh7yAQqyyrOsnSqrsVGobR9H4YBhEMghTKUX8I4keOg7pHqFAGsauH4Thq4MQRtxiWOE50fJjHgAcdzpqGCEdpIXY9sONTiRpvGMZ61HzppSl8TYIGvoK5FMqg8CDPcBmvmp0ASWc9lQUxBy2R%2BQXKcBPnxm5rlPHF4CJpGfkBdAsb6dAmbgAAcqg5LgOS0wUJAhUjD08RyuAiDFdAZWuCY3SHl4lA0CAkjIChnDEHC4YpOoAB8XrQO4SrZQAohVzpoJyOKXswQxqHKLCFcVpU6eAI3jZNzDTTws0sAtTosJKfAwCM83Gd2yA4IJRThgAapMiCoFQhzHLskk4AsSALjAhaTO6nAFMIAD6XbCGs46oPBTwzoM8AvAczStBmbmUcjLDg5DXbMX8QMiGDqAQ7wXYw0ySVpQZrkGZR33PTpgIdDi8Cok0yLfOAdOfozADkxzTTAQw87cXPrQQBDOT0nkouj7MvKLJJesAIK7LYnNPZ%2BG2YKNzAnWdwrTF9GtOQZHlebLnwc6LmJK3rtVqwrSsEA%2BXOoxRnBGz9DNIxWut4ZAkyQAAXkMtwU27TKOJgPDQIWIfq17cioGBKKDKQZ1QGCblwzHcdDOtGO67nFQh57z0m5laMe4XMBkOUzAK4zFDF8HofeW5YYRpTsXZG5NfQHX3WO83scl0MEdPI4ACqZDIFD5YogA6gAmpgACSK8AOI09XvvKPEIMwJKMcfrchf72oh%2F2ifghpxNi18I9P1US3IfIBXBkzrAeq1fnfbA4TYm88oTllaMwEYD0NY4FuDbV2vdXyFwEEDGohAn7PWgRPRCf0KiTDPr7VoINVD4XWpyaWkszYy13mApgZxDpymYKuCcx1CA0hBnhAofBGiKwIN%2FGOEC1Y1woIQyAxCkbSjIjvN4vseDIAYNVYgINCCoEgCMEgeCwEyLkZKRRyjVHECkWA2u5QP5uUcAAIUQHIOQ15QGNDTmglEWpwBkFCNAS8zwF4J3prw3%2ByADKFzOOgH%2BECcA%2BIge%2FEC%2FJ3R8jkIgSoyBXr9g%2BkOMmhcwLCHHOtHmXZjKhB4DzA8eQ5QfkOHKDJ3QYBOIIDk4geTxZ919iDCgiAzQYL5FEvkPAup4TXgPcoAAlVAMjpiJPehOaB7dXxww8ojWxnpGGSQoJg4Urw%2FiUh7DSZg9V4hk0nhAbZahwAxD4PwaC1YjlsBkUMGybBwBaO6FKIZDyKz1FLEUKUZ1orihQteZggQRg4B5uw%2BhdyGpHPkCcvgZyuj1AWJUHg1jBDC0lk8QuTSWl4TaR3RK4YkyS2pqYiAm9wyXDIEwz0yjmh4VGOMSYpKmGHGBkrTa98nQ7WTnteAc0FlnFqA1cEcoDKOBqmMFEVloI8olIynM38iY8CVpKvl8R6mvkVetIyJlrp6U9LdV8SiVEkFehoAADMaqmnoWXbV2vtBhZLFkZDBSA7VtjbVMIdfEVmekTEIL3g1K%2Bx84Ca2gHlAqVJNkHP0f3Qe8y7W8u9cJKhx1ZUZOYAIGRSpoAzFZoXCgyaeCpqGdSTN0EQE5rzcwLGJNoaTIQufP1R9amBr9sQQZ6bi1vHERXFy8CmR1oPg2m%2B805i%2FgYecHhwTUAEEBmMz6uy7oIwbhrda8NODusvgOptEDiCsrlA4rFQkV3MAIUQ94BdxEovnauwJE6O3l3xfGp4h6qXnmYF0rsfBemD1bcgQ2h6jHEC7QKaJcZuwIuvKMgcKSa1PBEoXSY5IeBFWEc3RF79oO9vwX07qqgUPXl7FGMh0UVkGKVeu6%2Bgb1GkYURutCadv0ZpmDgUhgxAM%2BrAei1prGYrxWA08HDYGXpvUg%2BceDiGhH8dQ2TYjomkMSbw5R198AEOydaAJ%2FDKZJZRvrnJv%2BTRz071eH2sjAbT4uovtR8jtHwz0fbSmLjaLmmtJk%2BJ1TknIm8fAGJAoIyhPJPOFJkURmLMmerUF%2F1ja0JecdPujD7HHOYsA65fkJjLUP3ZTNLlLABA%2FOHZw5gxwKAtC6kxmdQ5c1KIyfBYj5W5UVuRN7W2Hz7bAGYjVlN6TMncOACtEq0wRhqwpkrHrpUJZphMVlTetKWbik4Co%2Blkl7CpbZdazLrr7XmfWrdTwuiSAEFegAVlNR570QMeDnj2wRwYnpHBr1O%2BecAwgVAomkkUM7YqCiIuEKWOxH5JoFSUYyGRqhaodBDVZIs1hyInZOeeTA7xrwXc8MQYQ8A7gZL4CMGAr1jVkEkNyfkcgVDTDuC45AwORhUG0DjvHExYAAGsRgFH5lQKUMcKAuIEG47k4RAh8CoAAYlNca7kdZCxnCoAIEmkBh3ciDgAWipL0KgBhuTVTwnL%2BGoIqB7S1NydHmPoBUGp9yNguXuA0ioC0Mn3Z8eE5%2Fdr7pfA7jEQvFQPA7vgDu4lggIZfPCd3hw5DEZ1i2D08FJ76ABLHAIiUaUqYNIM6yGDaWAQD2Y5zydNBdPOKZFnBmMwcAy8OBERjvUMnRF5GFHCGgeohPh31B7OAJOgRyTMHsMRpgdD5Q0a%2BC8dZ1JW9LblLcTvVrzLeaxaPh%2B61g35X7%2BG7WW0H7DlDz%2BNxzAACOz0oWYA8qCbcBB%2Bc0OgHLrvcv0m2E9NsDPPAnLACAA&style=EQOgVg9gJglgLgfQGYFcA2aDOMBeBTAAgG8AdAOwIIFsBDAJwHMYyBaNPJOALgICYAGAA4APANzlKtRsxZ0YDABbcCQseQC%2BwIA%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jquery=0&lib_dompurify=0)

This didn't require any changes to the core or any other editors like `src/string.js` (Which is where the SCEditor, ACE and SimpleMDE code are currently placed) as it just extends `src/string.js` with the necessary code. So if Jodit lib is not present it will fallback to a standard string/textarea. And it can be configured using global config options and/or schema based options.

Using this method we also could move the ACE and SimpleMDE out of  `src/string.js` and place them in separate editors, making it possible to exclude them from build if needed.

**Comment by schmunk42** [comment]
> I suggest we replace it with another standalone WYSIWYG editor. (There's a good list here https://github.com/JefMari/awesome-wysiwyg#standalone)

I would not drop the support completely for 1.x releases, we can consider that for a 2.x along with a more generic way to add your own editors.

**Comment by pmk65** [comment]
> 
> 
> I would not drop the support completely for 1.x releases, we can consider that for a 2.x along with a more generic way to add your own editors.

Using the same method as in my Jodit example, we could create a SCEditor editor too, but not include it in the official build. (Then if people want it instead of the non-jQuery editor, they can create their own custom build)
If we split out support for special editors in `src/string.js` it will be much easier to add new editors that extends it. 
And then we could split up the editors in "**required**" (string, number, boolean, integer, object, array etc.) and "**optional**" (SCEditor, ACE, SimpleMDE , Starrating, SignaturePad etc.), making it easier to create custom builds.

**Comment by schmunk42** [comment]
Sounds great!

**Comment by pmk65** [comment]
Should we close this, as the changes is now available in https://github.com/json-editor/json-editor/tree/develop/2.x

**Comment by schmunk42** [comment]
Would be great if you could add some lines about the major changes to CHANGELOG.
