### ISSUE TITLE
Select2 performance issue for generating dropdown

### ISSUE THREAD

**Issue by MohnishKamble** [json-editor/json-editor#404]
1) JSON editor is very slow when using 'Select2' library for generating dropdowns when dealing with large amount of data. On contrary to this, 'Select' is very fast and it gives utmost performance. Is there any way in which performance of select2 can be increased for large amount of data?

2) Please refer to following direct URLs for checking performance for Select vs Select2 for my use case:
    i) When using Select : https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QGEAWBDAdgc1gAgEEATIgJ1gGcKQAacATwAd4kB7AIwCtYBjMWkOQCOAVwjkiiANogRjIujCwAYhFjQi1ALp1GpVs1KRKiUBTCLYAGQjnTDZohDpSpdPQEHIrTNQShUCBJYTEQwUhFYAF86KFgAWz9QMCYWEA5uPgE9A1gjNSTBE38HNPNSCBwQKJqYkB4oehs7EpTHJBc3DzovCB9CwODQhHDIurjE+za0jN5+XX1DY0LyQumncsrsatq6F1h0Zv5W1KdO909Gb197QaIQsIjo2KVJk/b0rjnsxbzl+1WAEYpqckJsqrU6nIFEpVOpNCCPrMsnRIDA0gBldRzPCYWAAdzw5ksNDwDRSeCwREp5HQAmEYgk0hAFGxfFgRAxFiUAlZcHZRGQjV5bKURAItJAOhAOSWBXsfLmHK5lkRZXCWwEADNWKR4ooNqKBGi4E4sfywLiCUTufA6PjFDxUArbX4WbajtU6CERPEMawRKQeCwpGYA0H1ZZqHQAG7oaCRJzAYATAB0AGtYPQasaoKakMm03GE9EotUtHVFQKhSk1RsNVU6Dq9QawUbUXnMaKrYTyd0QA6wE77OT5Ug+566j6/eHg9Iw4G5+OoPLY/HEwWU68M1mcx30UmtwlU8WxmWohW6FWxRKDnWwQ3tk3dfrjiz2+BO2bu3jCfs6fajrOiU/5uv+k7epgvr+ouIYLhGZy0tGICnmkhbbpm2Zlvu+YgOhx6oTmF6QlEQA==&value=N4IgrgDgJghgLgUwGIEsEBsoGcQC5RYYIDGiUAynPAniCADQiHolkDCKcAnrQ00aQRQAggCcEMXgF9GWKogAyKOXgDaoAG4x0YGrhABaA+QFwjfANYIe+kDNBWbIAAx8tOvSACyMKAAsuGAACAAVRXwQsPzt6B2taAEY3bV1aHz8YcKi4cJi4pwAmZI9aPz90zJhs3PsQR1oAZmLU/Tg4Cqy/HMla+v0AFmbPLCwOqq6a2Lr4/QBWIdoALzHqnqm+kAA2Bf0ADxWJtfzaAHYdkAB3A+686acADnOAR2vJ4/0ATnPRmAzOm96MxACVcjHcLTqryOd1oBSaYJSngAVlDbhsCoMESV9GBUYCnA15liIVw8esgf1MSBwZ4AEJk94gWbw6mI2hsBkwuZUmm0BCcjYJBos3n6KBQlBooFComs7EgABmUIuUqcCX6IrZ+gA5lDoYLKed6b9KqsALaqxKzHlakDGv7jboAe0t+gSsy+xLpersAF1GMROFwlCpcOouXQvbQjCYWKRzPjaAA6c7CKIAIzAogAdq6QEnnKC5RCkDBsxZ0Chs0EIJkLHmC85G+dswgLkEuE7RPXE/pGwWklH9Gm/Jmcw3CwPm0OQDAR2Pc7385PnAl+4XznOM1ns14J03V+vB8XPPOd3ul0f10UZ2ec3B91PV6ntzn9UCr4eN7fX9m2I+vzXZ8f1Hc8AKAm8T1oO9swAEXAgtNXlGDyAQ5wbWQ39UMvFcgIgl9QJzCAJ2PUUQBggB5Ejpyg4df2EajgNo8jfxoHD8JAhdaSonCDzwxCCIXSBiN4p8gIwiEYJE8knE/A8kMk38Lxk5MVwPIsyIAcRQv1GEyCQQwfMNGXOGNTATFS3XOWCnQubM4FsxdLJASCyJsuyHLs0Q8wUzx3PsxzYOUxkJL8xzPPsvNZTc8LHIUPNthnfyIoAUTzM4ktijy80eTKPMcgAVeKl09ZjksctKlxBaysuzBiqtI21yrsyrnISVymtq4q2t82hmt3VrGXVGr8pajQ83dEaApa9MJsSsrapS981QyhbRuzbqhtytbpuzJaJtKmL1s2iMCg0zr1pSnAlwKRr5X6rxxpujr7tqmBgtO3r9H6uBBtO0K+tq8g/vRaKLt2mAQaBAp5qO3aFShwpVrh1K8wKbaUcc4gvER2FDttAAlfqfPO+UCfIchiaXBo7ohInap8l66ap5zhXOcmWcZBoAf0en1p8sGyc5iMGlhwnKbenzkfF/rompjGZdquXWfxoXatmpd+lJ5m3oVPN+lpzwOfV7V9aZo3+vTU3Na+kBjfW4g9c1nm7Yl9aRn1wWdfd67nP6MW1fW8R9elwOIY9zWFbDiLxCgfXVYhYWNlmbWwv5pdZkNwH0+c2Zzez3aottpOgWtKaIqir208LjOA8ThmM9D+uc8ZWYo+bmvc4T6uK6XTZU4L3vnM2LPvob4f87HluI02Yvx8ZTYXZLpxNirwfHISuue43vum+3uyEvb/enIX7v14PpcTgHqfO8ZE5R5AZfTknx/54jE45+njYTiXt/v7Xm+Q875b3Pifd+e9QHpSPpAy+Z9AE72cvca+r8v5AnuA/J++h7gv0wSAe4n9b4RnuL/VBDwAEoMIRsD4yDcEfAwX/IEHwcEMKcB8W2BUJBmiCLQl2HCYBcNoeQ2CGAUAaAQKILg3CWG0A+CA+Bdkgh8ItCVCB8jqwwGWrCVRFCIpBA0Zo/Q6NvgjCkaQxo0D9DkDLFQbMYAggExgBYKInAfJwJ0Y5UxlCKQ0Nqp4oBEYDblw8bg/ozD1p+IQSFEhu0IkXz9nI9xCjcGzG0f1WJ1ZkkWMSRk3xyS3FgEzPZOxaTcH93OBcKsUBbJYHSekhKD8HECOkfoTYYSYnZidHASUfcCG6PQE6bUvsF7RN0UMme5CYDpmIHoqZMziCbyCQorwFECa4xaak3xVRYCH3OAAaVKW4rZdTL7IJ8KILpOSzH6HvpuKohA2jHOcicF+AApJ0hBHl31tlgKACpPnvxdmIXBJxyHaigMChJuynRmmBdohx2o/DAqyfs5pIAThuL5l4sh5xyCItRfcBJABNGAuD7jaOJVEUlWSHG0N6ZEiMHwsm0LcbgkEPirnAmcAk/qbE2rOA2RykETLfEAAknROjjlVZwLLcmooSNVPKMSSlyvlYssBgp2pqr0TUrZGifkTSFFql5BqRkeONQ1IRviXkfQ1dy3xwh/kaoFTEh1rKEjCvCRwlQDUZXhNdXKs6WrlWCtut8bA4aflBCgI66UMNzhmhgNM1lDR2UxIKsQOQkQHxVVFucCAnQY1qgaM63RfgkQIqRGWiaDRfVKrlYExVujWWhKDfWu14SzROnQBNfoJaPHZk4GACabdW2Co9KOrFiQykzjuQgOAhap30L9UEWkc02m6OEOmIIm65q2y8E6MRogF1ukXlqpAXZlFtVXlqs0CBO3qulJsBJVjwh+GPcCTY2ivAoGIBkDA76EibA9TErAVQqhzVraM8DVUr5avDRNG5jbglyueecBFAGP4Tv8YKH+WqFS/IQ5a8J1s2onHbTEyVpG+0KK4NwBDwHdH4YQ5Bjx+GnZtSQVq3lW0l0xKREiCa2CtUIsE3ShRTGqrEK1X4bUCoROSaIzEl5CBszZgMcCAlWrcWZATX6KQQA===&lib_switcher=&prompt_before_delete&upload=function%20(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

ii) When using Select2:
   https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QGEAWBDAdgc1gAgEEATIgJ1gGcKQAacATwAd4kB7AIwCtYBjMWkOQCOAVwjkiiANogRjIujCwAYhFjQi1ALp1GpVs1KRKiUBTCLYAGQjnTDZohDpSpdPQEHIrTNQShUCBJYTEQwUhFYAF86KFgAWz9QMCYWEA5uPgE9A1gjNSTBE38HNPNSCBwQKJqYkB4oehs7EpTHJBc3DzovCB9CwODQhHDIurjE+za0jN5+XX1DY0LyQumncsrsatq6F1h0Zv5W1KdO909Gb197QaIQsIjo2KVJk/b0rjnsxbzl+1WAEYpqckJsqrU6nIFEpVOpNCCPrMsnRIDA0gBldRzPCYWAAdzw5ksNDwDRSeCwREp5HQAmEYgk0hAFGxfFgRAxFiUAlZcHZRGQjV5bKURAItJAOhAOSWBXsfLmHK5lkRZXCWwEADNWKR4ooNqKBGi4E4sfywLiCUTufA6PjFDxUArbX4WbajtU6CERPEMawRKQeCwpGYA0H1ZZqHQAG7oaCRJzAYATAB0AGtYPQasaoKakMm03GE9EotUtHVFQKhSk1RsNVU6Dq9QawUbUXnMaKrYTyd0QA6wE77OT5Ug+566j6/eHg9Iw4G5+OoPLY/HEwWU68M1mcx30UmtwlU8WxmWohW6FWxRKDnWwQ3tk3dfrjiz2+BO2bu3jCfs6fajrOiU/5uv+k7epgvr+ouIYLhGZy0tGICnmkhbbpm2Zlvu+YgOhx6oTmF6QlEQA==&value=N4IgrgDgJghgLgUwGIEsEBsoGcQC5RYYIDGiUAynPAniCADQiHolkDCKcAnrQ00aQRQAggCcEMXgF9GWKogAyKOXgDaoAG4x0YGrhABaA+QFwjfANYIe+kDNBWbIAAx8tOvSACyMKAAsuGAACAAVRXwQsPzt6B2taAEY3bV1aHz8YcKi4cJi4pwAmZI9aPz90zJhs3PsQR1oAZmLU/Tg4Cqy/HMla+v0AFmbPLCwOqq6a2Lr4/QBWIdoALzHqnqm+kAA2Bf0ADxWJtfzaAHYdkAB3A+686acADnOAR2vJ4/0ATnPRmAzOm96MxACVcjHcLTqryOd1oBSaYJSngAVlDbhsCoMESV9GBUYCnA15liIVw8esgf1MSBwZ4AEJk94gWbw6mI2hsBkwuZUmm0BCcjYJBos3n6KBQlBooFComs7EgABmUIuUqcCX6IrZ+gA5lDoYLKed6b9KqsALaqxKzHlakDGv7jboAe0t+gSsy+xLpersAF1GMROFwlCpcOouXQvbQjCYWKRzPjaAA6c7CKIAIzAogAdq6QEnnKC5RCkDBsxZ0Chs0EIJkLHmC85G+dswgLkEuE7RPXE/pGwWklH9Gm/Jmcw3CwPm0OQDAR2Pc7385PnAl+4XznOM1ns14J03V+vB8XPPOd3ul0f10UZ2ec3B91PV6ntzn9UCr4eN7fX9m2I+vzXZ8f1Hc8AKAm8T1oO9swAEXAgtNXlGDyAQ5wbWQ39UMvFcgIgl9QJzCAJ2PUUQBggB5Ejpyg4df2EajgNo8jfxoHD8JAhdaSonCDzwxCCIXSBiN4p8gIwiEYJE8knE/A8kMk38Lxk5MVwPIsyIAcRQv1GEyCQQwfMNGXOGNTATFS3XOWCnQubM4FsxdLJASCyJsuyHLs0Q8wUzx3PsxzYOUxkJL8xzPPsvNZTc8LHIUPNthnfyIoAUTzM4ktijy80eTKPMcgAVeKl09ZjksctKlxBaysuzBiqtI21yrsyrnISVymtq4q2t82hmt3VrGXVGr8pajQ83dEaApa9MJsSsrapS981QyhbRuzbqhtytbpuzJaJtKmL1s2iMCg0zr1pSnAlwKRr5X6rxxpujr7tqmBgtO3r9H6uBBtO0K+tq8g/vRaKLt2mAQaBAp5qO3aFShwpVrh1K8wKbaUcc4gvER2FDttAAlfqfPO+UCfIchiaXBo7ohInap8l66ap5zhXOcmWcZBoAf0en1p8sGyc5iMGlhwnKbenzkfF/rompjGZdquXWfxoXatmpd+lJ5m3oVPN+lpzwOfV7V9aZo3+vTU3Na+kBjfW4g9c1nm7Yl9aRn1wWdfd67nP6MW1fW8R9elwOIY9zWFbDiLxCgfXVYhYWNlmbWwv5pdZkNwH0+c2Zzez3aottpOgWtKaIqir208LjOA8ThmM9D+uc8ZWYo+bmvc4T6uK6XTZU4L3vnM2LPvob4f87HluI02Yvx8ZTYXZLpxNirwfHISuue43vum+3uyEvb/enIX7v14PpcTgHqfO8ZE5R5AZfTknx/54jE45+njYTiXt/v7Xm+Q875b3Pifd+e9QHpSPpAy+Z9AE72cvca+r8v5AnuA/J++h7gv0wSAe4n9b4RnuL/VBDwAEoMIRsD4yDcEfAwX/IEHwcEMKcB8W2BUJBmiCLQl2HCYBcNoeQ2CGAUAaAQKILg3CWG0A+CA+Bdkgh8ItCVCB8jqwwGWrCVRFCIpBA0Zo/Q6NvgjCkaQxo0D9DkDLFQbMYAggExgBYKInAfJwJ0Y5UxlCKQ0Nqp4oBEYDblw8bg/ozD1p+IQSFEhu0IkXz9nI9xCjcGzG0f1WJ1ZkkWMSRk3xyS3FgEzPZOxaTcH93OBcKsUBbJYHSekhKD8HECOkfoTYYSYnZidHASUfcCG6PQE6bUvsF7RN0UMme5CYDpmIHoqZMziCbyCQorwFECa4xaak3xVRYCH3OAAaVKW4rZdTL7IJ8KILpOSzH6HvpuKohA2jHOcicF+AApJ0hBHl31tlgKACpPnvxdmIXBJxyHaigMChJuynRmmBdohx2o/DAqyfs5pIAThuL5l4sh5xyCItRfcBJABNGAuD7jaOJVEUlWSHG0N6ZEiMHwsm0LcbgkEPirnAmcAk/qbE2rOA2RykETLfEAAknROjjlVZwLLcmooSNVPKMSSlyvlYssBgp2pqr0TUrZGifkTSFFql5BqRkeONQ1IRviXkfQ1dy3xwh/kaoFTEh1rKEjCvCRwlQDUZXhNdXKs6WrlWCtut8bA4aflBCgI66UMNzhmhgNM1lDR2UxIKsQOQkQHxVVFucCAnQY1qgaM63RfgkQIqRGWiaDRfVKrlYExVujWWhKDfWu14SzROnQBNfoJaPHZk4GACabdW2Co9KOrFiQykzjuQgOAhap30L9UEWkc02m6OEOmIIm65q2y8E6MRogF1ukXlqpAXZlFtVXlqs0CBO3qulJsBJVjwh+GPcCTY2ivAoGIBkDA76EibA9TErAVQqhzVraM8DVUr5avDRNG5jbglyueecBFAGP4Tv8YKH+WqFS/IQ5a8J1s2onHbTEyVpG+0KK4NwBDwHdH4YQ5Bjx+GnZtSQVq3lW0l0xKREiCa2CtUIsE3ShRTGqrEK1X4bUCoROSaIzEl5CBszZgMcCAlWrcWZATX6KQQA===&lib_switcher=select2&prompt_before_delete&upload=function%20(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

3) Is there any way in which I can directly fire an ajax call from json schema's select2 field(dropdown field)?
   Description : In my json schema, the value of a key is actually a javascript function. This value is of type 'String', i.e. the function is actually a string
   from json's perspective.
   So, is there any way in which select2 can understand this as a function and not string?
   Please refer to the below schema so as to get an understanding:
   "selectedState": {
          "type": "string",
          "format": "select",
          "title": "Select new state",
          "watch": {
            "states": "stateList"
          },
          "enumSource": "function({
 ajax: {
    url: "https://api.github.com/search/xyzurl",
    dataType: 'json',
    delay: 250,
    data: function (params) {
      return {
        q: params.term, 
        page: params.page
      };
    }}
	})"

**Comment by schmunk42** [comment]
We'd need some in-depth information about this (JS Profiling, etc..) - I can't tell if this is related to json-editor or select2.

**Comment by pmk65** [comment]
@MohnishKamble The speed issues with Select2 have been fixed in the PR #401 I'm currently working on.
As it applies the Select2 code async so there's no wait before rendering next field.

3) I haven't tried it, but it might be possible if you can place the JavaScript function in a template helper.
I made a handlebars template example with helper function you might be able to use as reference. https://is.gd/5Rtkf3
