### ISSUE TITLE
categories string tabs

### ISSUE THREAD

**Issue by xlievo** [json-editor/json-editor#405]
How to display "name2" tabs correctly?

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "type": "object",
  "format": "categories",
  "basicCategoryTitle": "Main",
  "properties": {
    "name": { "type": "string" },
    "name2": { "type": "string" },
    "name3": { "type": "object" }
  }
}
```

**Comment by pmk65** [comment]
Categories only work with object or array types. All other types end up under a single Tab named "Basic" or `basicCategoryTitle` value. 
So you probably want something like this: https://is.gd/hq6yBg

**Comment by xlievo** [comment]
Thank you. I adjusted the style.
