### ISSUE TITLE
upload option not work

### ISSUE THREAD

**Issue by chen19890918** [json-editor/json-editor#408]
when i use the latest cdn, upload option doesn`t work.
even the example page below doesn`t work.
https://json-editor.github.io/json-editor/upload.html

**Comment by chen19890918** [comment]
is there any method to fix this bug？

**Comment by pmk65** [comment]
I have the same problem when I try to make an upload example for the Playground page.

**Comment by pmk65** [comment]
> 
> 
> is there any method to fix this bug？

Debug the code, find and fix the problem. Then submit a PR. 😁

**Comment by niebert** [comment]
@chen19890918 Open Console of browser and you will see, that there is `TypeError` preventing the json-editor to rendered in the holder (`upload.html` example). 

   TypeError: a.links[b].rel is undefined    jsoneditor.js:11476:48 - i.e. line:col in build of json-editor in `dist/`

For debugging check property `rel` with
```javascript 
 if (a.links[b].hasOwnProperty("rel")) {
} else {
   // do something if .rel atribtute does not exist
}
```
just a suggestion to start and create a Pull Request after forking the JSON editor as your repo.
