### ISSUE TITLE
Array's enum's empty default breaks if deleting an array element

### ISSUE THREAD

**Issue by gradinkov** [json-editor/json-editor#41]
If an array's enum's default is { }, and you delete any array element, you're unable to select the enum anymore.

Related: https://github.com/jdorn/json-editor/issues/813

**Comment by germanbisurgi** [comment]
Hi Gradinkov. I need your schema to understand, reproduce and maybe find a solution to your problem :)

**Comment by pmk65** [comment]
@gradinkov Please provide a sample schema or this issue will be closed.

**Comment by pmk65** [comment]
Closing issue due to lack of schema/feedback.
