### ISSUE TITLE
Question: Is it possible to use computed property names?

### ISSUE THREAD

**Issue by jordyno** [json-editor/json-editor#410]
Hi all,
I need a very basic multilanguage text editor.
The source JSON would be like  {"en":"English text","de":"German text", ...etc}.
I want to do this so that it is possible to select language directly by key, without array traversal in other parts of my code.
JSON-editor however, seems not to allow computed property names.
Is there a way around this?
Many thanks in a advance.

**Comment by pmk65** [comment]
@jordyno What do you mean by "computed property names" ?
Do you have a mock-up schema you can show?

**Comment by jordyno** [comment]
@pmk65 Something like this:
{
	"type": "array",
	"title": "Multilang Text",
	"format": "tabs",
	"items": {
		"headerTemplate": "{{self.lang}}",
		"properties": {
			$languageShort: {
				"type": "string",
				"format": "textarea",
				"title": $languageName
			}
		}
	}
}

Where $languageShort would be a two-letter short for one of the languages available (PHP array) and $languageName would be the name of the language, e.g. English, German, French...
I would like to have tabs with languages and showing just respective textareas.
The point is to be able to easily refer to multilanguage content, that is, to have two letter language representation as key of the localized content. 
The input data would then look like as mentioned above: 
 {"en":"English text","de":"German text", ...etc}

**Comment by pmk65** [comment]
If the language selector is separate from the main form, couldn't you just pre-process your schema and replace the variables before rendering the main form?

Another way you could do it (language selector will still have to be separate from main form), is by modifying/hacking the `getTitle()` function. Then you could have a language array and return the appropriate translation based on the key and language selected.

Something like this:
````javascript
window.JSONEditor.defaults.myCurrentLanguage = 'en'; // This is the language selected
// The translation list. In this example it will match a property with the name "text" 
// and set the title to the value.
window.JSONEditor.defaults.myTranslationtable = {
  "en": {
    "text": "English"
  },
  "de": {
    "text": "Deutsch"
  },
  "dk": {
    "text": "Dansk"
  }
};

// Override the current getTitle() function
JSONEditor.AbstractEditor.prototype.getTitle = function() {
  var lang = window.JSONEditor.defaults.myCurrentLanguage;
  var tt = window.JSONEditor.defaults.myTranslationtable;
  if (tt[lang] && tt[lang][this.key]) {
    this.schema.title = tt[lang][this.key];
  }
  return this.schema.title || this.key;
};
````

**Comment by jordyno** [comment]
@pmk65 Thank you for this! I checked it out and it's close, but not there yet. The problem is, that I need to feed the actual value in multiple languages and the title is specified only in schema. In your example I am getting same `text` for any chosen language.

I guess I will have to stick with PHP generated language portion of the schema, because number of available languages may change. It's not the best solution, but I think that's all I can do without rewriting JSON values on each access/write.
