### ISSUE TITLE
Two columns

### ISSUE THREAD

**Issue by mirannda** [json-editor/json-editor#413]
How can I make a configuration with two columns for example?

![image](https://user-images.githubusercontent.com/22716715/61065204-997f5380-a3d9-11e9-8da1-7f5cf7b7f911.png)

**Comment by pmk65** [comment]
You can use `grid` or `grid_strict` layout. https://github.com/json-editor/json-editor#objects
Example: https://is.gd/ivD6ut

**Comment by mirannda** [comment]
@pmk65  Thank you very much, exactly what I need!
