### ISSUE TITLE
Array and anyOf/oneOf items cause problems when deleted

### ISSUE THREAD

**Issue by rossleonardy** [json-editor/json-editor#415]
### General information
When you delete a row, it looks like the array editor sets itself to a value sans the row you're deleting: 
https://github.com/json-editor/json-editor/blob/master/src/editors/array.js#L554
This has an unusual interaction with anyOf/oneOf multiple style schemas, it looks like with   remove_empty_properties: true, it will set all existing items to the first schema available, and without it will get into a weird state showing a type toggle and the wrong schema in the switcher.

- json-editor version: latest 
 1.4.0-beta.0

### Expected behavior
After deleting a row the UI retains the appropriate state 

### Actual behavior
After deleting a row the switcher for the multiple editor is set incorrectly because state isnt retained

### Steps to reproduce the behavior

Direct link to example: https://codepen.io/anon/pen/jjjxrx

```javascript
var element = document.getElementById('editor_holder');

var editor = new JSONEditor(element, {
  no_additional_properties: false,
  disable_edit_json: true,
  disable_properties: true,
  disable_collapse: true,
  keep_oneof_values: false,
  schema: {
    title: "test schema",
    properties: {
      test_list: {
        type: "array",
        items: {
          oneOf: [
            {title: "test1", properties: {cost: {type: "number"}}},
            {title: "test2", properties: {name: {type: "string"}}},
            {title: "test3", properties: {date: {type: "string"}}}
          ]
        }
      }
    }
  }
});
```

**Comment by schmunk42** [comment]
@rossleonardy Did you try `latest` of this repo? 
We are at [1.4.0-beta.0](https://github.com/json-editor/json-editor/releases/tag/1.4.0-beta.0) atm.

**Comment by rossleonardy** [comment]
@schmunk42 yes, sorry; got confused looking at the git tags. The codepen shows it on 1.4.0-beta.0

**Comment by mattsta** [comment]
I reworked the example to show the error easier: https://codepen.io/anon/pen/dxygMo

Steps to reproduce:
- visit https://codepen.io/anon/pen/dxygMo
- click "Add Item"
- switch type between "test1" to "test2" and "test3" multiple times
  - each type only has one item (`cost`, `name`, **or** `date`), but switching types retains them all in the interface with bonus broken input modalities

See how the form strangely keeps fields from not-the-current-object but with an odd dropdown to select the type of the input element (which doesn't exist on the selected object):

<img width="270" alt="Screen Shot 2019-07-18 at 11 29 36" src="https://user-images.githubusercontent.com/15594/61470580-60059580-a94f-11e9-96bc-d129fea4ea43.png">

**Comment by pmk65** [comment]
@mattsta Try setting `no_additional_properties` to **true**. 
Example: https://is.gd/yS2W4r
