### ISSUE TITLE
dont support ts ?

### ISSUE THREAD

**Issue by zhuyunhe** [json-editor/json-editor#417]
### General information
i use 'npm i @json-editor/json-editor' to install it，i want to use it in my ts project, but i get error when i import it
```
import JSONEditor from '@json-editor/json-editor'
```

**Comment by pmk65** [comment]
Take a look at #127 and see if the solution posted there works for you.

**Comment by sirockin** [comment]
@zhuyunhe this project doesn't currently include typings so you need to import in the same way as you would import any other non-typescript module:
```typescript
import * as JSONEditor from '@json-editor/json-editor';
```
If you're using Angular, then the template @pmk65 mentioned in #127 should get you started.
