### ISSUE TITLE
Custom classes are not applied when format is radio

### ISSUE THREAD

**Issue by victoroliveira** [json-editor/json-editor#420]
### General information

- json-editor version: 1.4.0-beta.0

### Expected behavior
Should apply class to element.
### Actual behavior
Class is not applied to radio buttons.
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoA5jAHYAmMht45YANnIgyzZ5w0PiCphC5RnWEAzJIQC2AQxyJCK5uSTCmAVyUIA2iFW95Mc3AC6+EhSSMa8UNKj6wAQTCTyKT2oOTG4VKhczCABaELCaAF9ExKA==&value=N4Ig5gpgdgJhBOIBcIC2BDANhEBfIA==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap3&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "type": "object",
  "properties": {
    "gender": {
      "title": "gender",
      "type": "string",
      "format": "radio",
      "enum": [
        "male",
        "female"
      ],
      "options": {
        "inputAttributes": {
          "class": "my-class"
        }
      }
    }
  }
}
```

**Comment by pmk65** [comment]
@victoroliveira `inputAttributes` sets the attribute on `this.input`, which usually is the input element. But in the radio editor `this.input` is the wrapper element. (I guess that's one of the reasons why the `inputAttributes` function is not applied.) 
But it does add it's own class names to input (**radio__field**), label (**radio**), label span (**radio__label**) and icon (**radio_icon**). You should be able to use those for custom styling.

**Comment by pmk65** [comment]
If we add `inputAttributes` support to radio editor, which element should the attribute then be applied to? Radio element, Label or Wrapper?

**Comment by victoroliveira** [comment]
I think the class should be applied to wrapper element, and this class should be responsible to manage styles for radio element and label.

Regarding this, I notice that enumSource and options.enum_titles are not working when format is radio. Is this working as expected or is a know issue?

**Comment by pmk65** [comment]
> 
> 
> I think the class should be applied to wrapper element, and this class should be responsible to manage styles for radio element and label.
> 

Ok. (I think the same "problem" is also present in the checkbox editor.)

> Regarding this, I notice that enumSource and options.enum_titles are not working when format is radio. Is this working as expected or is a know issue?

You are correct. There's no `enum_titles` or `enumSource` support present in the radio editor, so that's something that should be added.
The radio editor is a fairly new addition to the library #346, created by @florina-chesaru Maybe she got an update/fix for this?

**Comment by pmk65** [comment]
@victoroliveira You can try the #437 PR I just submitted. It should contain fixes for all the above issues.

**Comment by pmk65** [comment]
@victoroliveira I'm refactoring the radio and checkbox editors and want to know how people want the checkbox/radio elements rendered. See #446 
So if you got any ideas/suggestions, please let me know.
