### ISSUE TITLE
Inherited fields not generated for more than one level of "allOf" inheritance

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#422]
### General information

Schemas using `allOf` inheritance do not generate form fields for more than one level of inheritance.

- json-editor version:1.4.0-beta.0

### Expected behavior

Should generate form fields for all required fields in inheritance hierarchy.

### Actual behavior

Does not generate grandparent field. Online editor behaves inconsistently thereafter.

### Steps to reproduce the behavior

1. Open (https://json-editor.github.io/json-editor/) paste sample schema (below) into Schema text box and click `Update Schema`. fields declared directly in the child object schema are correctly generated, as are those in the parent, but not those in the grandparent. A validation error is shown for the missing grandparent field.
2. Provide a value for the missing field by updating the JSON output. The validation error disappears, and the field appears in the form but with a type selector.
3. If the field is then removed from the JSON output, the form field disappears but the validation error does not reappear.
4. Repeat step 1 and click "Direct Link". The grandparent field still does not appear but neither does the validation error. Also the parentField (`numLegs`) now has a type selector.
5. Remove the numLegs field from the JSON output. The form field disappears but there is no validation error.

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "animal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number"
                }
            },
            "required": [
                "id"
            ]
        },
        "landAnimal": {
            "allOf": [
                {
                    "$ref": "#/definitions/animal"
                }
            ],
            "type": "object",
            "title": "Land Animal",
            "properties": {
                "numLegs": {
                    "type": "integer"
                }
            },
            "required": [
                "numLegs"
            ]
        }
    },
    "allOf": [
        {
            "$ref": "#/definitions/landAnimal"
        }
    ],
    "type": "object",
    "title": "Cat",
    "properties":{
        "breed":{"type":"string"}
    },
    "required":["breed"]
}
```

**Comment by pmk65** [comment]
@sirockin Judging from the various bug reports, there's a lot of unresolved issues with `oneOf`, `allOf` and `anyOf`
Personally I don't have much experience with those 3, since I never use them myself. (This is also why I have never attempted to try fixing bugs in `src/editors/multiple.js` which is the class used for those types.)

You are welcome to create a PR if you are able to fix it. 😃

**Comment by sirockin** [comment]
Sure I can have a look at that particular use case anyway. This is definitely an area where I think unit tests would be useful.
