### ISSUE TITLE
Form is autopopulated with Enum values when default value for enum in POJO is NULL

### ISSUE THREAD

**Issue by faraazbh** [json-editor/json-editor#427]
### General information
Form is autopopulated with Enum values when default value for enum in POJO is NULL

- json-editor version:

### Expected behavior
Drop down values for ENUM shoudn't be populated by default. It should be BLANK
### Actual behavior
Drop down values for ENUM are populated by default
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "name",
    "gender"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    },
    "gender": {
      "type": "string",
      "enum": [
        "male",
        "female"
      ],
"default": ""
    }
}
}
```

**Comment by pmk65** [comment]
@faraazbh That's the correct behavior when you have the "gender" property as "required".
If you remove "gender" from the "required" list, it will work as you expected.
Another way is to add a blank string as the first entry in the enum list.

**Comment by faraazbh** [comment]
By blank I meant, after I have loaded the schema , the form and the output JSON should be reflected as follows:

![image](https://user-images.githubusercontent.com/13655599/61683861-bbab9680-ad34-11e9-84c4-12692b4387a7.png)

**Comment by pmk65** [comment]
> 
> 
> By blank I meant, after I have loaded the schema , the form and the output JSON should be reflected as follows:
> 
Then do as I described before. Remove "gender" from the "required" list. Example: https://is.gd/wJn4X6
