### ISSUE TITLE
Editor value is not refreshed with nested DescribedBy property

### ISSUE THREAD

**Issue by lukzas** [json-editor/json-editor#429]
### General information

- json-editor version: 1.4.0-beta.0

### Expected behavior

Everytime propertyType is selected, editor.getValue() function / UI JSON edit should reflect actual value of propertyTypeOptions depending on selection

### Actual behavior

Editor value is not refreshed or holds previous value before selection. Without nesting as in original describedBy example seem to work ok

### Steps to reproduce the behavior

Direct link [LINK](https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIAKATkrJZAAQBmSl9AygIal4hTW1gCMAM4JQfGjDoQAchwC2ZUJFgIQwsJQIA7AOY9BJMiCqTp9OYp4ATEZi1RBSbWoAqACxj1tCr0kb0YJ70EgIQ9CgwOrr0wkjE1iAAvvihUpCu0ErgWWoaWnoGRNwU/Onhmar4MNoArvIIANogPO5ItcJw+JgclDwQHJjuOAC6KSAAws6MBPrwyrmIqBjYPGl0QqLzvGXSlTAA8o4EzlsLqkvoWDj4hiUg9DwA7hxgQ2I7ZhmLn2H7yfgaE5tGcQNYCMIOChSAB9daCEQITS1GD4cGQ6EwGEwcFgGFoOIueDI1FgiFQ2GYeLEDhQTpIygo8bEHQAay2jTG40oMAAjrUCDzEvBmvCIPsjsDRFz8Dz+YKcU1fuVLF1lXtcvgptoZvoRmiYDNtEQTiCPm0Otl4ZsPhxrNYecJQSpjPlokUjGoAIL2x2iblIJDyZ0/HRgGC6KQe+4yeqRVgHAIAJUDweSSXGPT622tiO2KEoHG0wvOrs07tuxWMACFC8WeDV6kqvbVwTxqwBZADqPAmngAbtRSDcQEcYMQeB2iMJaigIe4CCAxt14iwPi68uXCpXPYgpsQ1/hmJR5K81FSD31xhAYL11z83dvCLuQNWBQl6ABNW9XjP4AZDDgOa7AioI+FY2wbogj76DuMa+ACIDyEgtgTpBD5brBz73B2KHjohN53uhFwgGGEZRnBxjfne16DMMAAyNS6EE94kWRkZ9JRaiMXoLEZvxQA===&value=N4IgDgTg9mCmEBcCeA5AhgW1iAXCEANONHIkgCpJy75EDCUAdgGYCWA5rqJDPMpXADyYBKyYBnLgF8ZQA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

```javascript
{
	"type": "object",
	"title": "Property for Sale",
	"properties": {
		"propertyName": {
			"type": "string",
			"title": "Property Name",
			"description": "The name of the property being sold"
		},
		"propertyType": {
			"type": "string",
			"title": "Property Type",
			"enum": [
				"",
				"house",
				"car",
				"yacht"
			]
		},
		"Config": {
			"type": "object",
			"properties": {
				"propertyTypeOptions": {
					"type": "object",
					"title": " ",
					"watch": {
						"propertyType": "propertyType"
					},
					"options": {
						"disable_properties": true,
						"disable_edit_json": true,
						"disable_collapse": true
					},
					"links": [{
						"rel": "describedBy",
						"href": "#/definitions/{{propertyType}}"
					}]
				}
			},
			"required": ["propertyTypeOptions"]
		}
	},
	"required": [
		"propertyName",
		"propertyType",
		"Config"
	],
	"definitions": {
		"house": {
			"properties": {
				"address": {
					"type": "string",
					"title": "Address"
				},
				"rooms": {
					"type": "integer",
					"title": "Number Of Rooms"
				}
			}
		},
		"car": {
			"properties": {
				"brand": {
					"type": "string",
					"title": "Brand",
					"enum": [
						"Audi",
						"BMW",
						"Chevrolet",
						"Opel",
						"Mitsubishi"
					]
				},
				"color": {
					"type": "string",
					"title": "Color",
					"format": "color"
				},
				"year": {
					"type": "string",
					"title": "Build Year"
				}
			}
		},
		"yacht": {
			"properties": {
				"name": {
					"type": "string",
					"title": "Name"
				},
				"model": {
					"type": "string",
					"title": "Model"
				},
				"year": {
					"type": "integer",
					"title": "Year"
				},
				"yachtLength": {
					"type": "integer",
					"title": "Length"
				}
			}
		}
	}
}
```
### Workaround

Watch field programmatically and trigger setValue/onChange

**Comment by pmk65** [comment]
Fix added in #401 PR.

**Comment by lukzas** [comment]
Tested commit outside PR and it works, thanks!

**Comment by pmk65** [comment]
@lukzas I think I have spotted another issue with the DescribedBy editor. 
When you destroy the editor and then recreate it, the "subschemas" of the DescribedBy editor won't be displayed. Maybe you can confirm it?

I think the problem might be is in the register/unregister functions,

**Comment by lukzas** [comment]
@pmk65 I'll try to test that somewhere soon, but I recently removed DescribedBy from my project at all. Could you provide JS code used to destroy and recreate in #443, so that I can better understand what's the case here?

Meanwhile, I think we can close this ticket as it was fixed in 2.x

**Comment by pmk65** [comment]
I have posted a separate bugreport #443 with a test example. (I tried fixing it, but I just can't pinpoint where it goes wrong.)
