### ISSUE TITLE
Can I format checkbox for one item per line? 

### ISSUE THREAD

**Issue by djy0215** [json-editor/json-editor#431]
A simple checkbox schema:
``` 
{
  "type": "array",
  "format": "checkbox",
  "uniqueItems": true,
  "items": {
    "type": "string",
    "enum": ["value1","value2"]
   }
}
```
The page will display `value1` and `value2` in the same line. Is there a way to modify the schema to let one item one line? 

FYI, I am using this JSON EDITOR for  Jenkins [Extended choice plugin](https://wiki.jenkins.io/display/JENKINS/Extended+Choice+Parameter+plugin).

Thanks:)

**Comment by pmk65** [comment]
@djy0215 You can break it so it displays 1 item per line using CSS.
````css
.checkbox {display:block !important;}
````

**Comment by djy0215** [comment]
@pmk65 Thanks for reply. But I am wondering are there any ways to achieve this in schema field. It's a Groovy file not a JS file.

**Comment by schmunk42** [comment]
> @pmk65 Thanks for reply. But I am wondering are there any ways to achieve this in schema field. It's a Groovy file not a JS file.

While we have some options regarding layout settings, I don't think this one would belong there. 
CSS should do the job.

**Comment by pmk65** [comment]
Another way is to override the `getMultiCheckboxHolder` function, as the "inline-block" style is hardcoded in here. 
````javascript
window.JSONEditor.AbstractTheme.prototype.getMultiCheckboxHolder = function(controls,label,description, infoText) {
    var el = document.createElement('div');
    el.classList.add('control-group');

    if(label) {
      label.style.display = 'block';
      el.appendChild(label);
      if(infoText) label.appendChild(infoText);
    }

    for(var i in controls) {
      if(!controls.hasOwnProperty(i)) continue;
      //controls[i].style.display = 'inline-block';
      controls[i].style.display = 'block';
      controls[i].style.marginRight = '20px';
      el.appendChild(controls[i]);
    }

    if(description) el.appendChild(description);

    return el;
  }
````

**Comment by schmunk42** [comment]
We could rewrite that so that no `!important` ist needed.

**Comment by pmk65** [comment]
> 
> 
> We could rewrite that so that no `!important` ist needed.

That would require that the inline CSS is placed in external file. As inline CSS has the highest priority.

**Comment by schmunk42** [comment]
Inline styles should be avoided in general. although I admit I haven't looked in detail into this specific issue.

**Comment by pmk65** [comment]
@schmunk42 The most logical place to add the inline CSS would be in the Themes and not in the editor.
As there seems to be a overlap in some editors. (that's one of the things I want to clean up in #401. (But I have put further work on hold until the current changes have been reviewed/accepted.)

**Comment by pmk65** [comment]
@djy0215 I just looked at the Groovy plugin and it's using the old jdorn version of JSON-Editor.
You should get the author of the plugin to update his code as the version here contains several bugfixes and new features. 😉

**Comment by djy0215** [comment]
@pmk65 Thanks:) 
I just found that [Groovy plugin](https://wiki.jenkins.io/display/JENKINS/Extended+Choice+Parameter+plugin) allows you to combine with a Javascript file and I could rewrite the css style in Javascript. :blush:

**Comment by pmk65** [comment]
@djy0215 I'm refactoring the radio and checkbox editors and want to know how people want the checkbox/radio elements rendered. See #446
So if you got any ideas/suggestions, please let me know.
