### ISSUE TITLE
Accessing field schema at theme level

### ISSUE THREAD

**Issue by wsantos** [json-editor/json-editor#432]
### General information

How can I get the input schema at the label/input theme functions to proper apply a css class if a field is required, e.g: set label bold if field is required, what is the correct approach for accomplishing this ?

- json-editor version: all

**Comment by pmk65** [comment]
@wsantos If you install the [DOMPurify](https://github.com/cure53/DOMPurify) library, you can use HTML tags in the title and description properties.

**Comment by wsantos** [comment]
@pmk65 I can add it using my custom theme (using `JSONEditor.AbstractTheme`), but I need to know if the field is required or not, and I need that info at the theme class level, probably on `getFormInputLabel`, I'll give a try on your link, but I'd prefer to have more control/data at the "theming" level.

**Comment by pmk65** [comment]
@wsantos There is a function called `isRequired()` in the editor class, but themes don't have direct access to the field info and is limited to the parameters passed from the editors.
It would require changes in all the editors, so that the `isRequired()` parameter is passed along to the theme label function(s).
I think this could be a useful enhancement.

**Comment by pmk65** [comment]
@wsantos You can try the #433 PR I submitted. It will give you access to the required flag inside the theme label functions.

**Comment by wsantos** [comment]
Sure I'll give it a try, thank you !

**Comment by pmk65** [comment]
@wsantos Is it a new theme you are working on or a custom version of one of the existing themes?

As I'm working on creating a new theme from scratch myself (Using [Spectre CSS framework](https://picturepan2.github.io/spectre/index.html)) and I'm going to add some more theme functions or features if I find it necessary. 
So I could use the insight of someone else other working on themes. 😄 

Maybe @mirannda, the author of the Tailwind CSS theme have some ideas too?

**Comment by mirannda** [comment]
I find it nice to have flexibility to manipulate any element, having conditions to perform by configurations is always much more appropriate.

Following is the implementation I made of the required.

```
    getFormInputLabel: function(text, req) {
      var el = this._super(text, req);
      var rq = document.createElement("span");
      rq.style.fontWeight = 'bold';
      rq.style.color = "red";
      rq.innerHTML = "*";
      el.appendChild(rq);
      return el;
    },
```

**Comment by pmk65** [comment]
> 
> 
> @pmk65, Following is the implementation I made of the required. @wsantos
> 

With the _Inline Style Rules_ enhancement I want to implement, this could be simplified to:
````javascript
  rules {
    '.je-required:before': 'content:" *";font-weight:bold;color:red;'
  },
  getFormInputLabel: function(text, req) {
    var el = this._super(text, req);
    if (req) el.classList.add('je-required');
    return el;
  },
````
And the styles of `.je-required:before` can be modified from a normal external stylesheet too, without problems.
