### ISSUE TITLE
Material theme input fields are broken with custom format validation

### ISSUE THREAD

**Issue by lukzas** [json-editor/json-editor#435]
### General information

- json-editor version: 1.4.0-beta.0
- materialize/1.0.0/css/materialize.min.css
- materialize/1.0.0/js/materialize.min.js

### Expected behavior

Input fields (string) are rendered as without format or built-in validation (e.g. minLength)

### Actual behavior

Input fields are broken, Select generated from enums seems ok

### Steps to reproduce the behavior

Attach custom validator with JS and use Material theme

Direct [LINK](https://is.gd/T8tU9W)

```javascript
{
  "type": "object",
  "title": "Car",
  "properties": {
    "make": {
      "type": "string",
      "enum": [
        "Toyota",
        "BMW"
      ],
      "format": "connectionString"
    },
    "model_custom": {
      "type": "string",
      "format": "connectionString"
    },
    "model": {
      "type": "string",
      "minLength": 1
    }
  }
}
```

```javascript
JSONEditor.defaults.custom_validators.push(function (schema, value, path) {
  var errors = [];
  if (schema.format === "connectionString") {
    if (!/^([^=;]+=[^=;]+)(;[^=;]+=[^=]+)*$/.test(value)) {
      errors.push({
        path: path,
        property: 'format',
        message: 'Connection string must be in the format "Server={value};Database={value};Trusted_Connection=yes;"'
      });
    }
  }
  return errors;
});

var editor = new JSONEditor(element, {
  [...]
  "theme": "materialize",
  [...]
}
```

**Comment by pmk65** [comment]
@lukzas Materialize Theme currently has some issues. See also #205 & #214 
We need someone who is using Materialize to take a look at those issues.  (I don't use materialize myself, so that excludes me).

The rendering of Materialize components is handled by the "JSONEditor.defaults.themes.materialize" class. (Located in the file "src/themes/materialize.js")
Inside this (and other themes), you'll find various functions for creating the components.

It would be really helpful if you can see if you can fix the issues and then submit a PR.

**Comment by lukzas** [comment]
I've tried to look into it briefly before submitting an issue. I need to dive more into code to understand how elements are created and hope that I'll be able to fix afterwards :)

**Comment by pmk65** [comment]
@lukzas The "**JSONEditor.defaults.themes.materialize**" class **(src/themes/materialize.js**) extends the "**JSONEditor.AbstractTheme**" class (**src/theme.js**)
So if a function is not present in the materialize class, it will use/fallback to the function from the parent class.
Inside the material class functions, you can call the parent function using `this._super()` so you don't have to repeat the code if you just need minor changes.

Also take a look at some of the other Themes, like the Bootstrap4 which is working well.

And if you got any questions, feel free to ask 😉

**Comment by pmk65** [comment]
@lukzas I'm currently working on creating a theme based on the [Spectre CSS framework](https://picturepan2.github.io/spectre/index.html) 
This theme is build from the base theme, and I have only modified the functions that is needed for the Spectre framework. 
While working on it, I noticed a lot of the other themes is missing several features. 
So i started on making a schema for displaying the various fields in different situations. You can see a version of it here (only the 2 first items in the select box works so far) https://is.gd/p0z4f7
Maybe it will be of use if you want to have a go at fixing the Materialize Theme.

**Comment by lukzas** [comment]
@pmk65 Thx, I'll look into it :)

**Comment by pmk65** [comment]
I also noticed that the Materialize theme failed with JavaScript errors in some cases.
I have updated the testing schema to cover Array and Object output too Try it [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgBkBDRHAV3inioAzv2IchwilWwAnVAEcetOQBNMUANo1h8AMLjJwALqVo2ZDJxoZdQ1nBnqCHfolD1DmF%2BxI06uCIytBAA5lKOXjT0TP7AACo6UK7Mpt5OqBA8ALbqWhHeAfAcECocMipiEgCM4WmRwCLFpeWVqABMtXXYZTJcrTXAqV1wPX0GHYPSdSMyvYitAMyd08Cj8wYALMtpcPhEpP3bBbiEJPCtE0Mre2eLR%2FU3B5twU14mr05WdDgQ7ixQnmGwAy2QA%2BnRGHZNB8dsAAMpFEplFRQABitFQDBUfyuQIRTWRaIxWKEUAA7gA6KBfWg%2FKDEHBZZAcUhYeAyHgpGHHACCsy4915%2FMQ5KpADMcDIshx4GyOHgcdz6ny5qKoBKpTK5QqALTwKyC5XCtUa6WygTymKTfKwgDyp1Ihqc9v2%2FEp6slZqwYkEIUlGMVNuOLrOJs9WqgISCamtXXqIdIYc15qjtBUOsCtEdwCVRhhAF9XvncdoRMkPDCaChmKwTq77lFIbEEiIkgYG8AABaoDgqVAyBJMhgymvYEAgCFMfP5gETlwGacdmk%2FP72JVwBlMllkf7szm444qWhCS2oUEWKz92yrgQc1AH%2BpHk94Jig1BH%2BCgghCH7qPf39dgCfU9QQZBhh2QCQ%2FzvAsHzgMkZWITsKyDHx5yg%2F5Sz0Aw%2FlgytgAYYIAGsbw0QEVjkBhYj7IRiCCPB3wAIUQQ04E7OQxViABiAB6PsxWCehaV%2BHjx0EMsF0LHMbXzPMIkLMxi2kOB%2BME75fhQ45GiRFoDAGNcbTgC9rGvTSgUEAAPOgIGQPh9IBJUnF8UdCiCUInR8aIXPiVArKgYJbP4ATMRRMl6E7KAaLo2hkHUqAmn8iAJQSKyPJU4Roti4Tm18%2FgAr4dViVC8LIoyoIsrpBLgmS3KKTS3AKo0%2F5yLjbBqpwFKd1rTrEsCwqQvJEqovKuKqqSjrapeVCYAUuMlNQjdu2IIi8BwCz8vgeyWpWZzYkzdzY1auBTRlWIkJIFa1vqydvN0JbLos3qCuCrFBvgCLhpi0aSkSmrUsOuN0tokbssw4A7ou1bHo2%2FrXrC97SuBr7hPin72s6uqAaBZcmoM1r6nR3LYgh5aoaeoKirej6yuRyq0fGjGpvx2aunmwGGkxM4Nq2xyfGrPb2WCMIsZ2rzYjhTnExhl7ioRz7GtRlFCf%2Bh9DxpxrxclvKbOeyn4eppGFbGv74Ex1X6hBHJ%2FjyfGnAGc3jkuXmnCWaT8feabsBxm9tqBS3wS80jnfqdEZBEDzjglhkSgj%2Bo4k7ZQY2Dj3bbahmibBiWmClnWKYG%2FXEcy76lfTqzMd5lm6jZoEsh4Bg6AkbPrMCnnParPwwbWeqTq67BG7OeqeAgWhFFQABJQQshvf8Hc8pswYAWTrhutfJ2HZYNouUeNia%2FJ1D1kywfvs1noGt9%2FRfl%2BPVfpb1ob1eL37d9NqB957o%2Btfq%2BhUCnsz8fb7y%2B1haz3SJkK2WAbap2wKtLEscnD0A4IRYgcC%2B7SnAmISCTNbZyWZqfBq6kfbBzgMrXucAl712vk3NeMsqaFxBnTEuJsqRv3DOaY%2BO4K5KmrisWuFD2EbQmHjI6CB%2Bad2FN3VhZ17pQ0HsPUeE8f7TzvHgm6sRyEryobffO99DaPxIa%2FA%2BXp6TSKuiLWE8t1JqKvuw6hd85YP23vTJhBj37GMhqYvB39f7NSISIjutYgGxzgJbXIwcnAwJjCAgmRQkEoICGghgGDcKexgDg1q3DsaNUISktOJsrF8JvrndetCLGOMYc%2FZhhiIznVJqYzhqEMnHF6EeHA3M%2F7mVEQEwWB08E91iM02k10xZgwAEq9lpLY7R9jdFlKfp1eqpSL61jGS0yZcMdHn2gDveZZjjghOtr4kZ74gnAAAOJyAyCcxiDBORYLjCnYR3t2nsxIbEFZEytHrOmZsxWcyM71LmgWIsJYGiImaBUcYzzzCWBMgGKFTlcptJ8W3PxgDunAN5o2K03VcprI3nQ2mWynHPwWQ4pZ2AeqfPxYsol5TGa7IeFk%2BFsJXlg0pUUmhBcaW%2FJIWbXxm5mTZjZDBT2lc0iNPqDUh6SKhHs12mDQJDKnB9LBlKmRSq57YuwCTB6eKSlktpX8lWmKgIGuJiY6GHK7Gb3oYa3l9UnnItTsQ0upDwYWr1Vyg1PLXV8pyRuRkgre7%2FgBazc2AQtYyocii%2BVXS3IYpjcM2sWdQxUv1TMhhRqdx4JpZrTRVqpk2sJT6ph9V9kQN8fbXxTt%2FXAFdrzB57NHWyuEf7G6QcclOFDuHDVkcSA%2FEiWEilCdyh3Nao24RrLk2FL6pyjZtqS0VJOQK7c0Fbmiq4aYQCvCNFc1zq3f%2BqLYhdw1cdSRCrP6nuAEPEenIFHeOFfuE1qjL4FPzbO61BKjbEp6iww%2BUB2GkozRAfJu6c4fsLV%2BvRvqXGsI%2Fk3L%2Bk9snOqPQq9FJzy3Qk7dAnAsDe3RMQVmOJDQElJLHfciueDm3RpQ1O7A6jKGpoLV8ot366W1Vg%2F%2BwD%2BGA1biFbeddzNN3busZG3OgiaPCNjd0cRV6VW1jVR4k1N75FIbXQBRN89awMZsWmr1wHF2%2FqqeaRTFkgObNA4x8DutIPcu2Rxv9RjTOIcUcy440nXJCww2A0J2G4AROIwg2J%2BGnBCFIxwTBbtsGUZNdR32Kw6NkNE%2B%2BmzLGoOzN5ZxpzFrl2BtXbuEVQmGnhuAAM1p%2B6OBub5v4vu6G5PntrGVoZWnsDvJwJ6%2Bdxb7PGpRbm0Z4z2t6c62xrNZafMHNrUcwdtbzmoEuTx4A1zblRfuVRplTrbYuryf11ZQ3vkLu69m%2FleX%2BMho3Q0oF8kQVrEOBt44xkrxwru7CcSm0qsAOPbJlRSbtW4clIGQ9%2FEODL1CcAKbFBsCzfm%2BQbAS3mAToS2p57crOm1fjeR8VXDLveAyTMOYFwoVGRhY9qE8W0IiAPVJ1HeOBT1eTLEIoCpmtargLoP7YdSVimB%2FXUH4PBiQ4uSB%2FncA4dwARyypHLaUc1c8wdUNVdsdeFx6sYUdxkfQsvDYJ7Uv6ivcp9L7yJ7ekNZ8PKIQeoDRXpfbWNnDB%2Fuc%2B573LQYPjnC7OYLiHIubnw88ZLyTh6POgvRyt1mWOZLAteDT9YEgtjq6J5r0y6uEUU%2Fe6h2sRuTXydNy%2BLkmmWfg3ZwD4RQOQcHJd5EgXc2hcw698t8XxwvHIc22ntHXmQ8K4u%2BHq7ke6y3D0oT4AD2tek8Anr1PgfHhHbz95BMU%2FD1D8TzrnaOh9fN8D4q4OErl8iAk2Tna1PgBgIYjIDHVcolYVdkvjpMvgDBF9P2U%2FmPzuAq7zjkFk%2BCdx8H8T4fTft9vaT11wP0nwkXp1VRHD9CCEMG%2BxazgFnyTCcwgP9GgNi3Wyv0PGPBAjAgggwkfQ0xQ2AhzzfA%2FC%2FB%2FCFzwPPyAkwKIIX21wE3QFFTwVoJH1rR9FXwD2AIdDnygSxVuiQJkBFCrT83wWEj%2Fx4KoOfFfGwIi1wPoKiQwMkLPHfHoFIPJRniHScEINfGYKUSfWwycBXVO0KygS3yBB0KqxWEVXQKpxvw330KgDFSK1TlMOOB9F3yHQ%2BzBhAJC01T4N9ElBFBrSgS9jQP93EK0LPGkMglHHUPsJUmoNfGUM%2FG%2FDUOUQ0OwAiPPB%2F0X3oKHRcNhHMMAPZiPwfyKJsO8hKJP3b1tkcPSU30oJ9EvzCI4Jv28PkN8OJn4JFFdnaPj1hRYOCPgQgHvyqOsIN1iDv1QBCFKPSNqJf2cMgHlyfw7zfx7w%2FwMCaN9j6JJzEPcxX3H04PrDpzNFiFTGmwDx%2BzgK4IQIjDOPqkKLGPJwAMeKcgPzsOcMoNe3cOEMD0qMf1WNrVe02I8JbxdRGP%2BKVyWJx0Vxmnfy4NaFjx122N%2F2ZSwnYJe0OIHmONOjBjOIzEFhPmfUuOAHgPdFcTxMzEJJRQeOaPMn2LKPczeLq16JEJXAsNhDONAlw2yFxigA2HaKcE5LwDkA4CInUzyPqN8S%2BPZNeJvz%2BJ8N2FCL3yBE5LAh5JvA6GwzmPFU%2BJ0GBJ%2BIP0mOmKqJZLi3SLgFVO5KyF5M1OCO1OhOf1D1f0hMUkgHzGACAA%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0).

**Comment by lukzas** [comment]
@pmk65 I've found out that it's due to input type attribute being change from "text" to the validator name, in my case "ConnectionString". I'm not sure whether it's used by validation engine at all as it seems to work fine with the type being set to "text".

My first guess was to add `getFormInputField: function(type) {}` in materialize.js and set type explicitly for fields other than text, but with so many different input types it's not feasible. To implement a smart solution I would need to recognize field type and reset type or check if it's in the custom validators collection. After that, I started to wonder if it's a theme issue at all and shouldn't be fixed in the validator (assuming there is no need to change type).

**Comment by pmk65** [comment]
I think I have spotted the problem. In src/editors.string.js, the type is defined like this: 

````javascript
    // Specific format
    if(this.format) {
      // Text Area
      if(this.format === 'textarea') {
        this.input_type = 'textarea';
        this.input = this.theme.getTextareaInput();
      }
      // Range Input
      else if(this.format === 'range') {
        this.input_type = 'range';
        var min = this.schema.minimum || 0;
        var max = this.schema.maximum || Math.max(100,min+1);
        var step = 1;
        if(this.schema.multipleOf) {
          if(min%this.schema.multipleOf) min = Math.ceil(min/this.schema.multipleOf)*this.schema.multipleOf;
          if(max%this.schema.multipleOf) max = Math.floor(max/this.schema.multipleOf)*this.schema.multipleOf;
          step = this.schema.multipleOf;
        }

        this.input = this.theme.getRangeInput(min,max,step);
      }
      // HTML5 Input type
      else {
        this.input_type = this.format;
        this.input = this.theme.getFormInputField(this.input_type);
      }
    }
    // Normal text input
    else {
      this.input_type = 'text';
      this.input = this.theme.getFormInputField(this.input_type);
    }
````
And the "HTML5 Input type" sets the type to the format. There should probably be a check for valid HTML5 input types here and a fallback to "text" type.

**Comment by pmk65** [comment]
@lukzas Did the update I committed, solve your problem?

**Comment by lukzas** [comment]
@pmk65 just checked 8ba5b8bb52dfce47d32b28ce8eb2f356bab5da88 in my project and it works well :)
