### ISSUE TITLE
A lot of blank lines between objects

### ISSUE THREAD

**Issue by elham123456** [json-editor/json-editor#436]
I have a json file which contains multiple properties. The problem is there is too much spacing (multiple blank lines)between the properties. I have tried the different themes that you provide but that does not really make a difference in the spacing. 

Is this something I  would have to change in the bootstrap css file or the jsoneditor.min.js?  And Could you tell me what I would have to change?

I have already tried overriding the margins and paddings of div, span, tr, table, row.

**Comment by pmk65** [comment]
@elham123456 You got a few options.
1) Use the Barebone or HTML Theme (Example https://is.gd/xNihq3) and then create [custom styles](https://github.com/json-editor/json-editor/wiki/How-to-restyle-form-using-CSS-when-there-is-no-individual-classes) for everything. 
2) Modify one of the existing framework Themes (Please submit a PR if you make any useful improvements)
3) Build a new custom Theme.
 
What Theme are you currently using?

**Comment by elham123456** [comment]
I'm using bootstrap3. And the other themes have the same problem exept html.
I prefer not using the html theme because I want to take advantage of the grid format option. 
So I would think that in another css file, I would have to override the margin of the rows since the objects are placed into rows and theses rows are too far away from each other. But that has not worked.

**Comment by elham123456** [comment]
okay so changing the margin-bottom and top of h1,h2,h3 helps a lot!! But I haven't gotten rid of them completely.

**Comment by pmk65** [comment]
There are also options like "**compact**" that can reduce some of the white-space.
Try posting an example of your schema/setup using the [Playground page](https://pmk65.github.io/jedemov2/dist/demo.html).

**Comment by pmk65** [comment]
Take a look at some screenshots of the new 2.x **Spectre theme** I posted here: https://github.com/json-editor/json-editor/issues/439#issuecomment-518002094
It is very compact and easy to restyle from CSS or using the available theme config options.

**Comment by elham123456** [comment]
Hey! thanks a lot!
 I tried it out but the properties were all stacked under each other. The bootstrap3.js(with the grid format) uses the space much better than spectre.js.

**Comment by pmk65** [comment]
The Spectre theme got grid layout too (and so does most of the Themes) and takes up less space (both horizontal and vertical) on the screen compared to other themes.. 
All themes uses no grid mode as default, so you will have to enable that in your schema.
