### ISSUE TITLE
Is there a way to combine 'checkbox' and 'object' together? 

### ISSUE THREAD

**Issue by djy0215** [json-editor/json-editor#440]
I saw `For arrays of enumerated strings, you can also use the select or checkbox format`. I am wondering if it is possible for `checkbox` format each item in it is an object. 

For example, every item lists in checkbox are the following format. 
```
{
  "type": "object",
   "properties": {
      "name": {
        "type": "string"
      },
      "address": {
         "type": "string"
      }
    }
}
```

**Comment by pmk65** [comment]
No. Currently objects support the following formats: `grid`, `grid-strict` and `categories`
You can see a test schema with various formats [here](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgBkBDRHAV3inioAzv2IchwilWwAnVAEcetOQBNMUANo1h8AMLjJwALqVo2ZDJxoZdQ1nBnqCHfolD1DmF%2BxI06uCIytBAA5lKOXjT0TP7AACo6UK7Mpt5OqBA8ALbqWhHeAfAcECocMipiEgCM4WmRwCLFpeWVqABMtXXYZTJcrTXAqV1wPX0GHYPSdSMyvYitAMyd08Cj8wYALMtpcPhEpP3bBbiEJPCtE0Mre2eLR%2FU3B5twU14mr05WdDgQ7ixQnmGwAy2QA%2BnRGHZNB8dsAAMpFEplFRQABitFQDBUfyuQIRTWRaIxWKEUAA7gA6KBfWg%2FKDEHBZZAcUhYeAyHgpGHHACCsy4915%2FMQ5KpADMcDIshx4GyOHgcdz6ny5qKoBKpTK5QqALTwKyC5XCtUa6WygTymKTfKwgDyp1Ihqc9v2%2FEp6slZqwYkEIUlGMVNuOLrOJs9WqgISCamtXXqIdIYc15qjtBUOsCtEdwCVRhhAF9XvncdoRMkPDCaChmKwTq77lFIbEEiIkgYG8AABaoDgqVAyBJMhgymvYEAgCFMfP5gETlwGacdmk%2FP72JVwBlMllkf7szm444qWhCS2oUEWKz92yrgQc1AH%2BpHk94Jig1BH%2BCgghCH7qPf39dgCfU9QQZBhh2QCQ%2FzvAsHzgMkZWITsKyDHx5yg%2F5Sz0Aw%2FlgytgAYYIAGsbw0QEVjkBhYj7IRiCCPB3wAIUQQ04E7OQxViABiAB6PsxWCehaV%2BHjx0EMsF0LHMbXzPMIkLMxi2kOB%2BME75fhQ45GiRFoDAGNcbTgC9rGvTSgUEAAPOgIGQPh9IBJUnF8UdCiCUInR8aIXPiVArKgYJbP4ATMRRMl6E7KAaLo2hkHUqAmn8iAJQSKyPJU4Roti4Tm18%2FgAr4dViVC8LIoyoIsrpBLgmS3KKTS3AKo0%2F5yLjbBqpwFKd1rTrEsCwqQvJEqovKuKqqSjrapeVCYAUuMlNQjdu2IIi8BwCz8vgeyWpWZzYkzdzY1auBTRlWIkJIFa1vqydvN0JbLos3qCuCrFBvgCLhpi0aSkSmrUsOuN0tokbssw4A7ou1bHo2%2FrXrC97SuBr7hPin72s6uqAaBZcmoM1r6nR3LYgh5aoaeoKirej6yuRyq0fGjGpvx2aunmwGGkxM4Nq2xyfGrPb2WCMIsZ2rzYjhTnExhl7ioRz7GtRlFCf%2Bh9DxpxrxclvKbOeyn4eppGFbGv74Ex1X6hBHJ%2FjyfGnAGc3jkuXmnCWaT8feabsBxm9tqBS3wS80jnfqdEZBEDzjglhkSgj%2Bo4k7ZQY2Dj3bbahmibBiWmClnWKYG%2FXEcy76lfTqzMd5lm6jZoEsh4Bg6AkbPrMCnnParPwwbWeqTq67BG7OeqeAgWhFFQABJQQshvf8Hc8pswYAWTrhutfJ2HZYNouUeNia%2FJ1D1kywfvs1noGt9%2FRfl%2BPVfpb1ob1eL37d9NqB957o%2Btfq%2BhUCnsz8fb7y%2B1haz3SJkK2WAbap2wKtLEscnD0A4IRYgcC%2B7SnAmISCTNbZyWZqfBq6kfbBzgMrXucAl712vk3NeMsqaFxBnTEuJsqRv3DOaY%2BO4K5KmrisWuFD2EbQmHjI6CB%2Bad2FN3VhZ17pQ0HsPUeE8f7TzvHgm6sRyEryobffO99DaPxIa%2FA%2BXp6TSKuiLWE8t1JqKvuw6hd85YP23vTJhBj37GMhqYvB39f7NSISIjutYgGxzgJbXIwcnAwJjCAgmRQkEoICGghgGDcKexgDg1q3DsaNUISktOJsrF8JvrndetCLGOMYc%2FZhhiIznVJqYzhqEMnHF6EeHA3M%2F7mVEQEwWB08E91iM02k10xZgwAEq9lpLY7R9jdFlKfp1eqpSL61jGS0yZcMdHn2gDveZZjjghOtr4kZ74gnAAAOJyAyCcxiDBORYLjCnYR3t2nsxIbEFZEytHrOmZsxWcyM71LmgWIsJYGiImaBUcYzzzCWBMgGKFTlcptJ8W3PxgDunAN5o2K03VcprI3nQ2mWynHPwWQ4pZ2AeqfPxYsol5TGa7IeFk%2BFsJXlg0pUUmhBcaW%2FJIWbXxm5mTZjZDBT2lc0iNPqDUh6SKhHs12mDQJDKnB9LBlKmRSq57YuwCTB6eKSlktpX8lWmKgIGuJiY6GHK7Gb3oYa3l9UnnItTsQ0upDwYWr1Vyg1PLXV8pyRuRkgre7%2FgBazc2AQtYyocii%2BVXS3IYpjcM2sWdQxUv1TMhhRqdx4JpZrTRVqpk2sJT6ph9V9kQN8fbXxTt%2FXAFdrzB57NHWyuEf7G6QcclOFDuHDVkcSA%2FEiWEilCdyh3Nao24RrLk2FL6pyjZtqS0VJOQK7c0Fbmiq4aYQCvCNFc1zq3f%2BqLYhdw1cdSRCrP6nuAEPEenIFHeOFfuE1qjL4FPzbO61BKjbEp6iww%2BUB2GkozRAfJu6c4fsLV%2BvRvqXGsI%2Fk3L%2Bk9snOqPQq9FJzy3Qk7dAnAsDe3RMQVmOJDQElJLHfciueDm3RpQ1O7A6jKGpoLV8ot366W1Vg%2F%2BwD%2BGA1biFbeddzNN3busZG3OgiaPCNjd0cRV6VW1jVR4k1N75FIbXQBRN89awMZsWmr1wHF2%2FqqeaRTFkgObNA4x8DutIPcu2Rxv9RjTOIcUcy440nXJCww2A0J2G4AROIwg2J%2BGnBCFIxwTBbtsGUZNdR32Kw6NkNE%2B%2BmzLGoOzN5ZxpzFrl2BtXbuEVQmGnhuAAM1p%2B6OBub5v4vu6G5PntrGVoZWnsDvJwJ6%2Bdxb7PGpRbm0Z4z2t6c62xrNZafMHNrUcwdtbzmoEuTx4A1zblRfuVRplTrbYuryf11ZQ3vkLu69m%2FleX%2BMho3Q0oF8kQVrEOBt44xkrxwru7CcSm0qsAOPbJlRSbtW4clIGQ9%2FEODL1CcAKbFBsCzfm%2BQbAS3mAToS2p57crOm1fjeR8VXDLveAyTMOYFwoVGRhY9qE8W0IiAPVJ1HeOBT1eTLEIoCpmtargLoP7YdSVimB%2FXUH4PBiQ4uSB%2FncA4dwARyypHLaUc1c8wdUNVdsdeFx6sYUdxkfQsvDYJ7Uv6ivcp9L7yJ7ekNZ8PKIQeoDRXpfbWNnDB%2Fuc%2B573LQYPjnC7OYLiHIubnw88ZLyTh6POgvRyt1mWOZLAteDT9YEgtjq6J5r0y6uEUU%2Fe6h2sRuTXydNy%2BLkmmWfg3ZwD4RQOQcHJd5EgXc2hcw698t8XxwvHIc22ntHXmQ8K4u%2BHq7ke6y3D0oT4AD2tek8Anr1PgfHhHbz95BMU%2FD1D8TzrnaOh9fN8D4q4OErl8iAk2Tna1PgBgIYjIDHVcolYVdkvjpMvgDBF9P2U%2FmPzuAq7zjkFk%2BCdx8H8T4fTft9vaT11wP0nwkXp1VRHD9CCEMG%2BxazgFnyTCcwgP9GgNi3Wyv0PGPBAjAgggwkfQ0xQ2AhzzfA%2FC%2FB%2FCFzwPPyAkwKIIX21wE3QFFTwVoJH1rR9FXwD2AIdDnygSxVuiQJkBFCrT83wWEj%2Fx4KoOfFfGwIi1wPoKiQwMkLPHfHoFIPJRniHScEINfGYKUSfWwycBXVO0KygS3yBB0KqxWEVXQKpxvw330KgDFSK1TlMOOB9F3yHQ%2BzBhAJC01T4N9ElBFBrSgS9jQP93EK0LPGkMglHHUPsJUmoNfGUM%2FG%2FDUOUQ0OwAiPPB%2F0X3oKHRcNhHMMAPZiPwfyKJsO8hKJP3b1tkcPSU30oJ9EvzCI4Jv28PkN8OJn4JFFdnaPj1hRYOCPgQgHvyqOsIN1iDv1QBCFKPSNqJf2cMgHlyfw7zfx7w%2FwMCaN9j6JJzEPcxX3H04PrDpzNFiFTGmwDx%2BzgK4IQIjDOPqkKLGPJwAMeKcgPzsOcMoNe3cOEMD0qMf1WNrVe02I8JbxdRGP%2BKVyWJx0Vxmnfy4NaFjx122N%2F2ZSwnYJe0OIHmONOjBjOIzEFhPmfUuOAHgPdFcTxMzEJJRQeOaPMn2LKPczeLq16JEJXAsNhDONAlw2yFxigA2HaKcE5LwDkA4CInUzyPqN8S%2BPZNeJvz%2BJ8N2FCL3yBE5LAh5JvA6GwzmPFU%2BJ0GBJ%2BIP0mOmKqJZLi3SLgFVO5KyF5M1OCO1OhOf1D1f0hMUkgHzGACAA%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0).

**Comment by djy0215** [comment]
Thanks. 
Is it means that if I need the format to be `checkbox` and items in it must be enumerated strings?

**Comment by pmk65** [comment]
> 
> 
> Thanks.
> Is it means that if I need the format to be `checkbox` and items in it must be enumerated strings?

Yes, (Unless you create single checkbox elements. These don't need enum lists)

You can also create a custom editor to handle this specific format. You can see an example of a custom editor (autocomplete) here: https://is.gd/WihSGg

**Comment by djy0215** [comment]
@pmk65 Thanks for replay. Could u provide me some example of `create single checkbox elements`? 
Thanks so much:)

**Comment by pmk65** [comment]
Look at the 1st link I posted. the "checkboxinput1" is such a field.
