### ISSUE TITLE
Nested meta schema validates with unexpected errors (no additional properties allowed)

### ISSUE THREAD

**Issue by machinaeXlasse** [json-editor/json-editor#441]
Dear json-editors,

#### Expected Behaviour
I try implementing the meta schema into my project as part of the user interface. In this case, the meta schema is nested in another schema.

To be able to reference the definitions as a mayor part of the meta schema from the original json-editor files, I moved the definitions to the schemas top.

#### Actual Behaviour

For reasons I don't understand the validation fails for most properties with the "no additional properties allowed" error.

Maybe you have an idea what exactly changes once the definitions are not on the same level as the meta schema property.

#### Steps to reproduce the behavior

I got rid of all the rest of the my schema and the problem persists. Here is the most basic example validating with the above error:

[Direct link to example](https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIAiMAbgZjAM54hQBOSsLYBDCoAJtVowA+vUwALGAFsAhr0IkyIATToACMZNlMAJCxgAzBCADEAegEGCAOyIEk1+mc3S5+VuxidujeP0M2dg6+oJCwxqgY2ExQMmBgXtYACmwcXDx+IAB0AFTyeobG5paBXMHOEq4gAL61dfgltmWO8i6yAIIsLDIQ8mFKMl09TFI2AJIJUr4AjPhE0iEgBUaIxQFN9o4VWm4KpMZtcrX41gCuxMTyHmk+fdBkoDBnUggA2iBnFyAAutX4T6cXpl5lM7uFEJ9LsdlIYZOccJl+sZITFUl5IAB5FgCFgIaYABnqIBQSCQpBk1iuaO8GVC93kAKB7xJZJgFJ+fxAjPkIMWSMQLPJlOhBiQLFkCLp4JA9DALBsAHMmNz4O96DBSNF8JVMABrEkADw5DVh8LBSkFbMp7mpmOxXjxhOhsvl1iVmWu6NumXYzUWnppixsUFOYGEAHcCHwwOJzQc5YqanNrCGw5ICArxJLwPTEC7E5yYAbYtY+MJ05ns/ziaShUmQOGIPQCI33VKLbWrTURWKJXG8wm3ajPJwIFicQgAEz4/7PN4gTBksVMPhxOANNdcKTr5SbgjbgC0xCQmBkl3+sgI55AUgcMaYzxQDvw3TdO4S14SBpw+C/YEGbJMFuO6nCw17hjAMC6kwMjYJsYjylAP7EnEEhWPs2pMJgADU2FYVAUBYUgBgGJBWH0OIgzIZg9CMBunArmgFIKkgypoHRXJgcxTAscQ3H4AqbBIFQvT4JRpakCggwcZR9C6hq16UQaO5ZlI16BEwTECJpMhULsTF6QhBBIZp9AOEwpC0RZBD0IR+DEKcuyyPJ6E7rILC6nwSDhtaN5xHxKAjE2ACO16RFgXBUFgMQyGIZ4xF415QAq9ChTE4h2cwEAxuZL5MCwpwoKJMqxRxcV8UwYhWfg9DuZAlVpTVkAOWVVBKr+kbtSAVAoEZJn4AaalMBAMhDb8+CjNYAAyTwKveiK5iANgJAqz43oEUiAggM7MLaY72ri8CTgArJysgGjNbrze2xjLTAq24hNG1bfAO0BnaE7wAAzIS7hxAkLCUgt0r5kO+CiuKcTGPoq1GjaI4fQ632nb+uaPHOqoyoOSrjVyGOgLy/ZY66SrQpYcLEFWi2g11737Z9BJnTAfAEHIwNKOFWogDIfAs80Z4pAj3oGGe6rwzctI5uCN0DiT3acpMUB8QkRM0/LJyAk+h2gO93qgL68FUkLkvBqGEZRtdUtKGrnKm2mMAZlmqvY/WRYlmWFZO+zxiWuyRL8ujL3vI+Dq4yqBOTHyi0h7iZOmpTRMx/Wk37i9MsfJra10+OSMnWdMgGqnQLp0n4vovTSM/Wd8LGaQGIrCXmePbtCMV4dX2ndCd0PUbEuLAbwS916JspmbkbRrG3uywWyapuWDuVs7cuFsWFIewvXvp77wpxyLZpT0t1grQ6Z3PcXVvIk3w5pG3U4o35hebef1aly3N85+3v03jXSswPXidXzLqOD+CAO4KzRnjIOh9j64jDvjJakcibdxPkSTm2ZybwkFn3ecuseDfCAekfuSFDYeltHrBcZI+JQHVHwIm296ws3oDIFApBhCLguDIahDwL4Ck7H7BoNlmGsOZkQYQ7FzIH3oZyRhQiRC4KjtKKRL5pDCRENIJCEBhDyLoXw4U9kehIFDEvRMs4oGCSjByaEAdIFMmQOgCKxoYR7wTgfNB9ZtGuPsVzWI8REhYOHosXI+R9ArFMBYdYQQtiHHVswf6fiyGS2rG4v6vjAb+MDPIIJmRlhFHCVYDY5RolEh5nzTYAsEkKI7KyfhIB9DBVOAQfQtCD6DG6MVU4th6kwAmAsBAcpTgwHBr2KGiB/wsJ3ITA+atfxEH2IgOm3YhmQypiDF2pjbHmNob8aErThiZAwZTdJhD5yE3wW/AJ8gB4tFIcbRY7CqE0J0dUvRyhBHjOELszRJSnl1mkW81hnzhACFICrSRuiGH/JEIC4FMAEgfIuMINg4ZKk+3BX8ph7zoUalhSIPispEXeR+V2dFsiPlDE0foMUn0t5ooERi1h9zOHqiJX7KxECVTvE+Y4g5KyBjkqYBDPsozZH1kmfrawf8VivFADk1YZhFwdIBmYAAbEmdOXL8CyrCQqo+XgzAAHYBXDIROAZhjBqi4w6QQLpPTQRguecncYiCD7IObinJ+2184GltSixArqRhn09fgEpkSzw+uCYUOVjRIlOCKUsoV6dpk2PnBq014ygJmozb1A8YB2BYUkHqQ0lVsVc1PCtMUtxtmckOAAIVitwpJXjkI8qOd6d4XBFBAXpGcupDSmnziRGcjxMsdZ7RAfAWYPDiYmOQMQwemRxBRgEEDfpMAu7NMTWskAgqRkgFAgQesOholTK3Tuk1+76wdrmZuuWBDb5HWkQwTAiFmjGLBuc4BB0EAABZCzwOrKmya4aJ34CtTa51q673juOjtM9xgxn7D/YCAAyoYlgdBLkSv/qqUIsylDIf3L/NQqHQIYdRqs5euBcOdsQAAYSQFIX+BpiNobI1O1NcHhW9QDdYYDk6xXICw1K6jcyQD0ccP+I+agABqZ4BkcQA/y+Nu6EMgU6QM4DkGEG9JPcvP4In8OsffItZJ3NeahuIK2jIItiBi1qTAepjTmbzjMqRuAZyW0VJc0Zn4BDyGufQ9whwkq3gGeMAAdVQpIPgagABi3BiC0PI9bF2+m9hKHE7KCkYAZNyZ4Ml4wHHjXwZFU9Xjzr+POrC4gPSDljPSlMyG/mlmvPwBs3Z4d3U8tvtJjMmjN6Cx1FxvQYgQgiZFeWSV9NZXgOTgmgXWbcwqtTv9SKK8AMeuXrw5tzktWBk7dqNs3GsqBtDk5MF7DMqQm5OjX6bYrhOhtPrBSMcDcljXajREu7hxHvDE5GeYgl33uRrCbd+C92Oj8s5NYJA2YtVrHyTGiHRwoNfoPq/Hljp8Rf1G9YXUvruZKe3cVrjGFtN2vTqZq9ShcfQWDeZ5rVnfDtcGR+45mR9CXF0zPEA4gPuna6pxvdYF6yYDxQTm2DRvLWGPDzTDIWcNTqUQLmouNtwsxkAAFQgdWG2RJwxRaJqZnxANkitdAFklXRJJA8y8Jr9RysG3U1S/gK5BPTNu/kPJGAUBhDBeIsIPb1nRZrpNM4yUj7w9M94JyTrjJhDU4J6msDGmIMFVZ0L1TTABO663VwSmShqeLJAJsthZJATXPTv6sPFMESTvdS9evBci54knJyRdvMngsped733/uDCB7ywTqRdRq2VG0Nkj7oOvvg9rfWpgnvMi979xKgPQfmch8j7Xo3Tb6wXeE+l4wGJd/09KQ4cptyEAs81VP8wOqlXTG/Wqw/iBfvFSa2Ulrl+2sh5vyDu/hiuqLAZg0wx0z+ReiAyGW6H+5+X+2CP+tmrO8O8qgBD+qqaWEBIAAAcoAmZmftYBfvAdfsDqEgAYqnqtMIahgdtogGMLqj3KfhZtHggXZsgffhQQABzgE0EgA1rgqMGM6tbEFsGoEUEACc3BNG2B5w14MBBBcBFyLBSBt+KB5BwB04qudQQAA==&value=N4IgJgpgbglgxhA+gZzgCwgWwIYgFygAuMhANhPiCADQiECeADhXiAPYBGAVhHITSEYAnNsyHEIyfMAC+coA&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

this is how the meta schema was modified in short:

```javascript
{
  "type": "object",
  "title": "Devices",
  "properties": {
    "device_schema": {
      "title": "Device Schema",
      "$ref": "#/definitions/schema",
      "properties": {
        "definitions": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "$ref": "#/definitions/schema"
            }
          }
        }
      }
    }
  },
  "definitions": { ... } // all the definitions see json-editor meta schema
}
```
I use the meta_schema.json from the docs folder in json-editor version: 1.3.5

**Comment by pmk65** [comment]
You got an `oneOf` error in your schema, which is not displayed inline. 
Look in the Validation output of your example and you'll see the complete list of errors..

**Comment by machinaeXlasse** [comment]
Thanks for the quick reply!

I came accross the update which included: [Move additionalProperties: false from schemaBase to each branch of schema.oneOf](https://github.com/json-editor/json-editor/pull/300/commits/d6482c0a3e6eeaebea66038fb026c58d094485c4)

Now when I undo these changes the [schema validates](https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIAiMAbgZjAM54hQBOSsLYBDCoAJtVowA+vUwALGAFsAhr0IkyIATToACMZNlMAJCxgAzBCADEAegEGCAOyIEk1+mc3S5+VuxidujeP0M2dg6+oJCwxqgY2ExQMmBgXtYACmwcXDx+IAB0AFTyeobG5paBXMHOEq4gAL61dfgltmWO8i6yAIIsLDIQ8mFKMl09TFI2AJIJUr4AjPhE0iEgBUaIxQFN9o4VWm4KpMZtcrX41gCuxMTyHmk+fdBkoDBnUggA2iBnFyAAutX4T6cXpl5lM7uFEJ9LsdlIYZOccJl+sZITFUl5IAB5FgCFgIaYABnqIBQSCQpBk1iuaO8GVC93kAKB7xJZJgFJ+fxAjPkIMWSMQLPJlOhBiQLFkCLp4JA9DALBsAHMmNz4O96DBSNF8JVMABrEkADw5DVh8LBSkFbMp7mpmOxXjxhOhsvl1iVmWu6NumXYzUWnppixsUFOYGEAHcCHwwOJzQc5YqanNrCGw5ICArxJLwPTEC7E5yYAbYtY+MJ05ns/ziaShUmQOGIPQCI33VKLbWrTURWKJXG8wm3ajPJwIFicQgAEz4/7PN4gTBksVMPhxOANNdcKTr5SbgjbgC0xCQmBkl3+sgI55AUgcMaYzxQDvw3TdO4S14SBpw+C/YEGbJMFuO6nCw17hjAMC6kwMjYJsYjylAP7EnEEhWPs2pMJgADU2FYVAUBYUgBgGJBWH0OIgzIZg9CMBunArmgFIKkgypoHRXJgcxTAscQ3H4AqbBIFQvT4JRpakCggwcZR9C6hq16UQaO5ZlI16BEwTECJpMhULsTF6QhBBIZp9AOEwpC0RZBD0IR+DEKcuyyPJ6E7rILC6nwSDhtaN5xHxKAjE2ACO16RFgXBUFgMQyGIZ4xF415QAq9ChTE4h2cwEAxuZL5MCwpwoKJMqxRxcV8UwYhWfg9DuZAlVpTVkAOWVVBKr+kbtSAVAoEZJn4AaalMBAMhDb8+CjNYAAyTwKveiK5iANgJAqz43oEUiAggM7MLaY72ri8CTgArJysgGjNbrze2xjLTAq24hNG1bfAO0BnaE7wAAzIS7hxAkLCUgt0r5kO+CiuKcTGPoq1GjaI4fQ632nb+uaPHOqoyoOSrjVyGOgLy/ZY66SrQpYcLEFWi2g11737Z9BJnTAfAEHIwNKOFWogDIfAs80Z4pAj3oGGe6rwzctI5uCN0DiT3acpMUB8QkRM0/LJyAk+h2gO93qgL68FUkLkvBqGEZRtdUtKGrnKm2mMAZlmqvY/WRYlmWFZO+zxiWuyRL8ujL3vI+Dq4yqBOTHyi0h7iZOmpTRMx/Wk37i9MsfJra10+OSMnWdMgGqnQLp0n4vovTSM/Wd8LGaQGIrCXmePbtCMV4dX2ndCd0PUbEuLAbwS916JspmbkbRrG3uywWyapuWDuVs7cuFsWFIewvXvp77wpxyLZpT0t1grQ6Z3PcXVvIk3w5pG3U4o35hebef1aly3N85+3v03jXSswPXidXzLqOD+CAO4KzRnjIOh9j64jDvjJakcibdxPkSTm2ZybwkFn3ecuseDfCAekfuSFDYeltHrBcZI+JQHVHwIm296ws3oDIFApBhCLguDIahDwL4Ck7H7BoNlmGsOZkQYQ7FzIH3oZyRhQiRC4KjtKKRL5pDCRENIJCEBhDyLoXw4U9kehIFDEvRMs4oGCSjByaEAdIFMmQOgCKxoYR7wTgfNB9ZtGuPsVzWI8REhYOHosXI+R9ArFMBYdYQQtiHHVswf6fiyGS2rG4v6vjAb+MDPIIJmRlhFHCVYDY5RolEh5nzTYAsEkKI7KyfhIB9DBVOAQfQtCD6DG6MVU4th6kwAmAsBAcpTgwHBr2KGiB/wsJ3ITA+atfxEH2IgOm3YhmQypiDF2pjbHmNob8aErThiZAwZTdJhD5yE3wW/AJ8gB4tFIcbRY7CqE0J0dUvRyhBHjOELszRJSnl1mkW81hnzhACFICrSRuiGH/JEIC4FMAEgfIuMINg4ZKk+3BX8ph7zoUalhSIPispEXeR+V2dFsiPlDE0foMUn0t5ooERi1h9zOHqiJX7KxECVTvE+Y4g5KyBjkqYBDPsozZH1kmfrawf8VivFADk1YZhFwdIBmYAAbEmdOXL8CyrCQqo+XgzAAHYBXDIROAZhjBqi4w6QQLpPTQRguecncYiCD7IObinJ+2184GltSixArqRhn09fgEpkSzw+uCYUOVjRIlOCKUsoV6dpk2PnBq014ygJmozb1A8YB2BYUkHqQ0lVsVc1PCtMUtxtmckOAAIVitwpJXjkIhv5sQI5wtRaDKcRTMA7aMjvC4IoIC9Izl1IaU0+cSIzkeJljrPaID4CzB4cTExyBiGD0yOIKMAggb9JgF3Zpia1kgEFSMkAoECD1h0NEqZx7T0movfWQdcyj1ywIbfI60iGCYEQs0YxYNznAIOggAALIWeB1ZU2TXDYu/AVqbXOr3e+hdx0dr3uMGM/Y4HAQAGVDEsDoJciV/9VShFmUoHD+5f5qDw6BQjqNVnL1wGRodiAADCSApC/wNDR/D9Hl2pvQ8K3qAbrAwaXWK5AxGpUsbmSADjjh/xHzUAANTPAMjikH+XxrPZhkCnSBkwaQwg3pt7l5/FkxRvj75FrJO5rzUNbaKkIBFsQMWtSYD1MaczecZk6NwDOTyvtvg1TWZ+AQ8hfmCPcIcJKt4lnjAAHVUKSD4GoAAYtwYgtCGPWxdhZvYSgFOygpGAVT6meC5eMIJ41GGRVPTE86iTzqEuID0g5Gz0o7MtrKU525LnO0Rclu1gZ/7SYzNY6+gsdRcb0GIEIImNXll1fTQ1mDk4JoF3W3MFry7/UiivADMbT7yPHc5CNht1N8u1G2bjWVU2hycliyRmVITcnRr9NsVwnQ2n1gpGOBuSw3tRoiZ9w4P3hicjPMQF7QPI1hI+/BL7HR+WcmsEgbMWq1j5Jjcjo4yHgMH1fjyx0+Iv7zesLqX13NtMntq8JjCJm7Xpzs8+pQFPoLBoc624LA23NdpnR5y4ZmZ4gHEMDh7XUhPnrAvWTAeLqc2waN5awx4eZEbi6R5dSjJc1FxtuFmMgAAqEDqw2yJOGFLRM7M+IBskZzmQsm66JJIHmXgjfqOVpdxjournU7s37+Q8kYBQGELF4iwgLu+Fc+qL9zjJRx57bzvwnJBeMmEGz6nqb4OGcQwVLt0u9NMEk2b49XBKZKDZ4skAmy2FkkBNc9O/qTTx7xA1oubeH4d8XZOTkW7eZPBZS84Pofw8GEjxV6nUi6jVsqNobJwOEeg6R7W+tTBA+ZBH2HiVEeo989jy3nt1um31mezJwrxgMQn81Yv8wOqlXTBA2qi/iAIfFSx/KwxuqWBmGmMdZ/VeiAOGx6H+9+eq0wqqBWgBIAAAcoAnDqEnfl/g/oalAadogGMLqj3DfvDkgYquAQABwAHoEgA1rgo4GIGf74E/7TAACcxBrGsB5w14oByBeq04eudQQAA==&value=N4IgJgpgbglgxhA+gZzgCwgWwIYgFygAuMhANhPiALICeABAConkgA0IhNADhXiMoQBOMAHYBzEAF9JQA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction).

I would of course like to reference the most recent meta schema file and avoid creating a modified version.

Is there a better way to embed the meta schema I'm missing out on?

**Comment by pmk65** [comment]
Sorry. I haven't used meta schema much myself, so I hope @Franciman might be able to explain the changes.

**Comment by Franciman** [comment]
Hi, it's been a bit of time, I'll review the schema and will try to help

**Comment by Franciman** [comment]
Hi, sorry for the huge delay,
I saw one thing I don't quite understand:
In the schema you used for the json editor there is:
```json```
{
  "type": "object",
  "title": "Devices",
  "properties": {
    "device_schema": {
      "title": "device schema",
      "$ref": "#/definitions/schema",
      "properties": {
        "definitions": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "$ref": "#/definitions/schema"
            }
          }
        }
      }
    }
  },
}
```
why did you put this fragment of schema before the metaschema?
If I remove it, and then fill the json-editor with the json you used, it validates correctly

**Comment by machinaeXlasse** [comment]
Hey! Thanks for having a look into this. Now its me being late, sorry.

I want to allow using the editor to create a schema for (inside) each "device" instance, that's why I nested the meta schema into an object type. 

Maybe in the end that's not practical anyhow from a user point of view and creating the schema should be its own editor. 

The way I did it just seemed more straightforward.
