### ISSUE TITLE
Is it possible to use checkbox/select with multiple checkboxes with enumSource?

### ISSUE THREAD

**Issue by lukzas** [json-editor/json-editor#442]
Is it possible to use checkbox/select with multiple checkboxes with enumSource? It works fine with using $ref to fetch values, but my case needs to allow modification of values in checkbox during runtime. 

```javascript
{
  "type": "array",
  "format": "select",
  "uniqueItems": true,
  "items": {
    "type": "string",
    //"enum": ["value1","value2"]
    "watch": {
      "values": "possible_values"
    },
    "enumSource": "values"
  }
}
```

**Comment by pmk65** [comment]
I don't think so. The rendering of checkbox elements is  a bit wiird IMO.
1) A field with type "boolean" and format "checkbox" is rendered using the `src/checkbox.js` (valid)
But any type other than boolean will render it using the `src/string.js` (invalid)
2) Select and Checkbox in multiselect mode are triggered by `"uniqueItems": true` and both rendered using `src/multiselect.js` 

I made a Select test case on the Playground page you can try. https://is.gd/OLELuk 
(If you improve it, please upload a copy the new test case to the Github repo. 😄 ) 

I'm currently working on a new Theme, and in the process I'm cleaning up various render issues in the different editors. And the multiselect editor renders things differently from the other editors.
See this [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgBkBDRHAV3inioAzv2IchwilWwAnVAEcetOQBNMUANrTqCYfADC4ycGkBdStGzIZONDLrGs4SzsEjDEoeucxf2JGjqcCIytBAA5lIuvjT0TEHAACp6UB7MFn46qBA8ALbqWtF%2BwfAcECocMipiEgCMUZkxwCJlFVU1qABMDY3YlTJcHfXAGb1w%2FYNG3SPameMyA4gdAMw9jfOLHQAsa3O4hCTwQ7vF%2B0SkHdOj62eHKydN%2BOdHRjsmRVDmszq2dDgQXhYUB8Y2A2TyAH06IxHJpvnsAMqlcqVFRQABitFQDBUgOuoKRrVRGKxOKEUAA7gA6KC%2FWj%2FKDEHC5ZAcUhYeAyHjpeGnACCCy4D35gsQlJpADMcDJchx4ByOHg8bymgLFuKoFKZXKFUqALTwWzC1WijVa2XygSK%2BIzD6nADyB1Ixp0jueZulFqwYkE4WlWOVdqabsOHu1lvCoTUtt6wad%2FGpms9OqgkdoKj1IVozvesdM8IAvrMC%2FiaHo0t54TQUMxWLcc%2FidOa5Qk09HG%2F44rXsMkRKkjA84AALVAcFSoGTJFkMOXduAgEDQpgFgvAxflowrwe4ZB%2FAGVoNwJkstlkIGc7kdnQqWhCa2oCHWWwThyAjlc1BX7A3u94JgQ1Ab3gCECCEf51AvT8VTgH97whJkGBnZAJAgj9Cw7OAKTlYghwPWMy3cAcgQIgwjEBdCq2ABgwgAazfOEgxBfDgDkBgEnHIRiFCPBAIAIUQF1sCHOQJQSABiAB6ccJTCeh6QBCSFzcUiJC3XNeiLD582iTSYBLaQYNQGSIDk%2F56KY7AWhRdojGGJxKKfOxXzw0FBAADzoCBkD4OzgRVVwawSLMIkE2IYQSZIPKgMJvP4GTsTRCl6CHKAOK42hd3kqBWmiiApUi%2FgAApgvCABKULgDS0JMvA4iklQKKYr4TVSUS5LUuEdKaugHKwnyhr4BpYrOTCMqKrpMyXNjHQ%2BpwAqIqHW8WoS6LyXCbIJ1nNE8DFIQZGICTAPoaUhAkkqqVAwSdDbeCcAYPJ9yBAA2fyoF0jSvzLDymvgWpfIsm4AjnYAclyHiZAqpdgYK3LYuWnFKXaqqMr3bLyly%2FqosK0HwfKmNpsMzjqr3CKBth5r4oRpL4BS5HurRtFZoKoacYnPGvx%2BbrzNema8rmgaFqWynGbWjaBkEbbdv2w6gJOiTWZkC7A2mpoboQh76JeoM9JVfTD10b6vJ86Z7O1%2FxArqsJfQnSGu1Jxqjbi1rEZpjqiZRrLer5mHCqt1B1pkdnXsJrqSbqmGfvhtrXbp1GvcxwaoF9iBrcD8auamgngCZgXw8W8lhdW1Mxa2qAdqgPaDqOw0ZFOv2A6Vq7sDVu6NfULWVfexo9eY9zPNi1YgQBvYgYSeubfx5jmzPOsBgiHkzbCm06wAJTKdbyadlbqdpzric99Gc48irY%2FkhI1%2Fnzeo5d3f3fp%2BP%2BY8ql073bmzd5hPBYL52lvWiBNolmXKWVdZa1wkuPRWl1J5ZxbvdXIj0sAd2ml3TIPdXIDR%2BibPyi8EAWzrCVCq08Eh90qKOW24Vw4DVIRwK%2Bhcd5u1DgfRm3tc4c2%2FHvD2tU6wFWobQ529DT4MgfszF%2B8k34qw%2Fo%2FGePZ87X1%2FiXQB5dK4y2OmA86UC2HXSjLdOBCCoC1G6GbFBfg0E3BwiQGieAcBuR%2Bv9YOuDAh1SsXdUcEBCHJmkUeEcxBLHWPIcvbA%2BhvG%2BLcnw7eSMOH30PiwrGzimBlCDjgwRbi6pBIsVY0Jkc6ERLvnHaJCchpxNcYklWhkJQcB4AwaRkE2FwAmno4eNwj6eKSLIwu8j%2F7i0AkAiu0tq5y3MT4jJjdoHMVgW3Z6r1jG%2BFMXsCQTBSC2MzoDPBlkRohVGSPO2dUETYlDFk%2FhOTGFCPyVIk%2BkSw51l2Qs%2FgBzwkxwuUwjGUjn6bNOOCfIQJCgSOwMMTR2Arg82wIPV6XwcH1PERIuAHyoRdnot8n52BMS1zPP8nQuymTlCbjoRIi0qhwCBWCn5cBmlfzkaLTppclF9NAadeZhwRn%2FLgOM%2BBmspm60%2BixMc9IllD3saPOqBC3lNCIXVAYN4cD%2BOBmvCVYSqZHP3ic5hn9hXXkeVw7AMr6RyujrfY5PVTnzVVdgD5BQgVwBXoBJucAADichsjWuALxe6zBQW1J3K%2FZZoJSV5yFj%2FClADunUpAao064r6SMvNcAFleikGxmmXpTluRKl0HpYsx2dicECrrBMASxq4CivwXshs9ieAmUUKgAAkoIXI9Ean8u2XWAAsim28xbbmO2vgI9VBrlVSKgHqJM4YsBptRfY5JCQW1VLbTcnVN8GGKt7c85mA6h1egru2iq9BUC1q9Ssxx%2BD1mRGNVkUGZr35NCsTibF2B6AcGosQG9wRZSITEMhAlF7tKd3dRCvdewfXcLaf64ulLFHAJUTXU6ybp2jsjRe5l2j1asvbuyoMszTjQdTe2zBf6AoHr6KKdx4YEiDJCRVMttAK3Vp3XWj87qoaTtbaOud3bclPOaau6e3pgkZPOWxjVcAp1YdnXc%2BVDz%2BNLuaTSQdXHGQ8b8fm7ONbIWlIccDIVTKwRnq%2BUCnQV72y6dvaUB9T7mgvoYG%2B8in6pk%2Fozny%2BD2cYktNxX6laHTA2S16SGyDElMMzoZRoqNMa2VGN1oWYspZmjIjaNUKYXq4CORfAGP9X1%2B4%2BVw%2BbfDJRQgbPo42nsZNRO6oXZwyTTm%2BP6vth2uG2TxP6oZsugarzbOevs8SxzKruGFc7bVvVi6GtScdceVkOZ3zclQ%2FGzlfccNtaztmtZOXj3usLf4KhcgOBSqq7wor87kkDfK4pidlCPLbZ64cur%2FXhFNdEZNWbqmAMFZO%2BtljCrSv7YKUN5kI3qloVC2hqbGDHaD1Nqp%2BbJKU7%2BwnstjxCQ57rU23VC%2BG8dusfq1d4%2Bh2e3n3XqgF7F23vo8GjdhpUaHsWpx3jvrBPDXXZPdgYbp5ULjb%2B5N6CwBSMZN5SDubqzsujSIxaEj8m3II7rGkoZ1jKclaiX2o17qjti%2BF1LvbhPmv2N%2FXdrOZPgDi5Ccrnt72XmfZPKNgQv3O4crZ6Orn2DQe86i4t0X2Brn7LO%2FcqnMvGsY%2Fl1jnZ7b9cScNyIxTpqdMOb%2BVGwFDmQVmyJVnDX3PVMwqhvCwzcBkUiFMxi%2F4BmL04rxdGQlmntcu9IAHtHNOn7G%2B%2B0z9ALOPps789bjNGXqxZeALmgXLZBWbsUxRqjyna95Yoc2pj%2FuUevc9xxmTHiR2959xJxjMHx9u7Ex7vJsumucdnxum5W7B%2Ba97vbjTUbQ9YARe1%2FTpm70mbpzoIQ5nLMfp%2BV%2B5BLWxEZckUa0fy%2BROr%2BKyrpXonDPsOrvocNXozueObsgpbvrE3tho7Fgo0k0GDh3oRopitl4ukgpu6v3tyNRrulAZeA2iPtgEJv5mXhPvjlPk5tvqARzjgeOr7j%2FsJq7jVuduvuxk5tJmuimAwSLoptuoQYnjzu3ifg5mfgxIitgFfnfkZvetmKZg%2FvehZhwO%2BupCrK%2FqzuCnZiIcxNruQcxlQZwUql7sAbwZaPwRAabpBBNg3vrOGjgLYhtofiPMfkel3i0o4U7uTrKsYdLhvmYRVoutjn4f%2FrtgboThVJIRflnJarnu1naqgA6nTnAM6uNhob0HHsxAnrblCh1mcojtyjgOXpdkAdYT9szhbmhuFjpJFrmscK4QljYE5Mlq4a4HoJmnbu3p3opgxqkndCdOcuUimueu1vEY6kkSkZpuka6rHu6kISpqIeph4Zkd3GFh8CgrMhsJMBIEgQ5C0UlrCMgSRF0csQkL0dDsRnVKUEqD4TroMbXMMRUlUmMfkRMakcAFMSkjMS6s%2FtNNkd6gfnoa5O4Y7msaghsesXUbMDsUsEYMDnkacIlvYG0SCR0SIGcUfj0egVcYLjcYqEIAaEaH0flnAPoI8crFnNJC8dIrEcxB8Zpt8Y6rMf8XmAscCUiecYKqsXYdCfyTMvUaKNsPFsACic5O0atpia3mphcbifYpgQgPePcRSQwEMZjiMa8WHuMVap8cyZ8ayRCX4ICU0pycgacKgUKnyZCZsRFrCfWC8HUKKeKWiVyRaZ0TKagU8OAaSaQXACGCWjgi6ccVGspFifkZabyReuhugiIPsXnplsDArGyW%2FqGXoIieaW4e3hAimfGtaSYrUSYpFt6RcHFk0WKYcaiSGfrGGZ6fbiWWOjgoqT6P7P6MYMPgEv6fGGGOui2X6KEO2erroW6aCLBH%2BA%2BAhEhChEQVBA5mOf%2BNXCBGBCkmNrOe1vOQ%2BMGbRlUamUGZWRKeiXsD6OGd0cDA2aZv0WLrOP2WKBHgmXUsOZmTcBuTolOd2PWgmdeLeHBIuaBBqh%2BdIV%2Bb%2BP%2BFuUPoZjoAzjYdAT8jGcxKBZKcxEKoeaeUFFGYBW9IZgmqgppj6PGdIW3mefGBeWSTrtedKGKFHvhR6h%2FghaOd%2BeOa%2BWodOauWik0C%2Bb%2BcuWBZ%2Bd%2BPRSBfua6bYQmbBaCPBchaCMmbRdiUmXkODLmRIlhQKd%2BlGj6BmWnrKXVOeXIUvMDIYL6ORVAIPKxc0c%2BFWUse1jmZJaCdmRDgHHJdUdIQpTMvmU5baTCdEHUvGPcOWaJSORib9HWe3ppXid3nWG2PcQGQmJKDvmFYpj5U%2BVKf5ZZXhiseCUCsJe6XGZ%2FigfbhJWlZpspKpfeepXWBZWlc5TrK5UWfaQ2SKd5fxdWb3B6bRQRQkEFQqTDnVG2JmCNIGaDiRRFT2SmF1VmL1VnHFWmdKUlYmaheCUZdRbdmJTcMFuoFsKxVoumBCHgOtjRLXphXlRNfAHhYii1XVBJXNbkfFacMtUCIYg5ftQ5gVVlclWPDZVDmpRdeBc3Ihq3MhjdXtdGeVRhZVS5RVQWMAEAA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1), and notice that there are no infoText buttons on the 2 multiselect elements (There are other differences, that are harder to spot too.)

**Comment by pmk65** [comment]
Have you tried any of the extended Select addons? (Select2, Selectize or Choices)
The have an additional features, like tagging/pills. (Have different names in each plugin).

In the 2.x branch I have modified the multiselet editors, so it is now possible to add additional items to the enum lists. Either from user input or from `setValue()` (Optional feature)

**Comment by lukzas** [comment]
This is what I've thought :stuck_out_tongue_winking_eye:. I've seen playground Select TCs example before posting the question. I have two ideas on how to tackle this:

1. Watch source property with JS and update enum from code
2. Use plugin for select that works with Materialize e.g. choices (not sure whether passing data differently than with schema defined enum is supported when used inside the editor?)

BTW I'm using the playground every time I need to check idea or searching for example - it saves a lot of time and is convenient to use :smiley:

**Comment by pmk65** [comment]
The changes I made in the 2.x branch, updates the schema enum list dynamically if needed, so new values will validate correctly. (I have updated Select2 and Selectize editors too, so they now are separate editors instead on nested into `select.js` and `multiselect.js`)

**Comment by pmk65** [comment]
In the 2.x branch I have also introduces some changes to the Theme format. So it now can use Style Rules instead of hardcode Inline Styles. (This makes it so much easier to restyle from CSS)
And you can add configurable options to the Theme, to have different layouts.

So if you are going to update the Materialize theme, it might be a good idea to use the 2.x branch. 😉

**Comment by lukzas** [comment]
I've checked 2.x branch with following config [LINK](https://is.gd/pA4aE7) and it's rendered differently than on 1.x code. On 1.x it is rendered as multi-select (checkboxes in the dropdown with Materialize), while on 2.x there are pills (checkboxes mixed with pills with Materialize). Seems that latest choice.js demo page is in line with how new branch works, as there are pills too.

**Comment by pmk65** [comment]
I kinda destroyed the Choices editor during my 2.x update. As I assumed it worked similar to Select2 and Selectize with a Select box. But then I discovered that the tags/pills no longer worked. 😢 
This is because Choices needs a textinput field and not a select box (And I have modified the editors to extend the select/multiselect). I plan to fix this later on if @itsoli doesn't beat me to it.

In the 2.x branch, you have to specify the format as ""select2", "selectize" or "choices" if you want to use those (In the 1.x branch you had to enable it for ALL elements, which I didn't like.) So it is now possible to have select2, selectize and choices fields on the same form.

**Comment by lukzas** [comment]
@pmk65 Ok, I'll use the workaround until it's sorted out 😃

**Comment by marcc-orange** [comment]
@pmk65, JSON Editor beginner here, would you mind sharing your workaround ?

Based on your previous [test](https://is.gd/pA4aE7), I tried multi-selection with an array of strings updated by an enumSource from an array of objects, but I'm failing to make it work: https://is.gd/KHoGiF.

**Comment by lukzas** [comment]
@marcc-orange Actually my example doesn't present a workaround as it serves as issue description. You'd need to modify enum from JS as in playground example [LINK](https://is.gd/i0iNCU). In my case I use it with `watch()` hook. Hope that helps :smiley:
