### ISSUE TITLE
DescribedBy editor stops working if you destroy the editor

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#443]
### General information
DescribedBy editor stops working if you destroy the editor.

- json-editor version: 1.4.0-beta.0

### Expected behavior
That form look the same as before destroying.

### Actual behavior
The subitems of the DescribedBy editor is no longer present, just some empty div tags.

### Steps to reproduce the behavior
The example below destroys the editor when the ready event is triggered (See the JavaScript/CSS Tab). Then it recreate the form with exact same schema.

Direct link to example: https://is.gd/i4l8cz

**Comment by schmunk42** [comment]
@pmk65 It would also be nice, if we could create real tests from an example like the above.
Those tests can be marked a `optional`, so they don't stop the build process immediately.

**Comment by pmk65** [comment]
@schmunk42 Do you know this one? https://houndci.com
I came across this on another repo where I posted a PR. It performs various tests and auto review the PR. Then it write a comment if something is not accepted.

**Comment by schmunk42** [comment]
We've worked with https://scrutinizer-ci.com/

While this is also useful, my main concern is that, if we have a known issue, it should be rather easy to create a simple test case for it - even before it is fixed, actually classic TDD.

**Comment by pmk65** [comment]
Fixed in #559
