### ISSUE TITLE
How should Radio/Checkbox layout look/work in 2.x?     

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#446]
Currently the multicheckbox editor shows the checkboxes in "horizontal" style (all on the same line). But in some cases you might want the layout to be "vertical" (each checkbox on own line).

In the Radio editor I made it so it is possible to style it in both layouts. (I changed hardcoded output to theme functions)
And in the Spectre Theme the layout is "vertical", but if you turn on "compact" mode, it changes to "horizontal". But I'm not sure if this is the best approach (since the header/title is not visible in compact mode)

So here's some ideas.

1) Use the "compact" mode to change layout, like the current 2.x Radio editor. (With no visible header)
2) Add a config option to change layout (will only be useful for checkbox and radio properties)
3) add a new editor format. like "format":"checkbox" for default layout format (horizontal), and "checkboxV" for vertical layout.

As the output is based on the theme, Number 2 and 3 might not have any effect if the theme doesn't support the feature. Which might lead to confusion.
Personally I prefer 1 or maybe a combo of 1 and 2.

**Comment by mirannda** [comment]
@pmk65 I find an option like grid_columns ...
check_horizontal, check_vertical ..

If only when using compact greatly restricts the usability of the feature.

**Comment by pmk65** [comment]
I have just committed an update of the Radio editor to the 2.x/develop branch.
Now you can set the option `"layout": "h"` for horizontal layout (compact mode also triggers horizontal mode)

**Comment by mirannda** [comment]
This way you are restricting the possibilities, because it will be configured globally, I refer to the schema options, so it will be possible to have more punctual control, I felt the absence of a getRadiosHolder (), similar to CheckBox, this allows a better control, in my opinion.

![Screenshot_12](https://user-images.githubusercontent.com/22716715/62565738-da924880-b85d-11e9-9a52-10c808fce816.png)

**Comment by pmk65** [comment]
No. It's not global. You can set the option for the individual radio properties in schema.
````json
        "radio": {
          "type": "string",
          "format": "radio",
          "title": "Radio input field with description and infoText",
          "description": "Radio input field with description and infoText",
          "enum": [
            "Red",
            "Green",
            "Blue"
          ],
          "options": {
            "infoText": "This field is generated by src/editors/radio.js",
            "grid_columns": 6,
            "layout": "h"
          }
        },
````

And in theme you use the `getFormRadioControl` function to wrap up the radio input and label and to change the style to `inline` (horizontal layout)
````javascript
  getFormRadioControl: function(label, input, compact) {
    label.insertBefore(input, label.firstChild); // Move input into label element
    if (compact) label.classList.add('form-inline');
    return label;
  },
````

**Comment by schmunk42** [comment]
I'd prefer the long form:

```
"layout": "horizontal"
```

**Comment by pmk65** [comment]
> 
> 
> I'd prefer the long form:
> 
> ```
> "layout": "horizontal"
> ```

Ok. I have changed it to "horizontal" now. 😄
