### ISSUE TITLE
Drag & Drop for Array Table 

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#448]
Currently the table layout has a lot of buttons for sorting rows (move up/down one step at the time) and is not very user-friendly.
We could add (optional) row drag&drop using a 3rd-party library, which should improve the usability.

I found 2 (Non-jQuery) libraries that looks useful. If you know of others, let me know.
https://github.com/arteyazilim/rowsorter (Last commit 2-Jan-2016 - 9 issues - 1 PR)
https://github.com/sindu12jun/table-dragger (Last commit 2-Dec-2018 - 13 issues, - 4 PR)

Which one does do you prefer?

1st one seems to be the fastest, specially on large tables. The 2nd has a nicer drag effect.

**Comment by schmunk42** [comment]
CC: @germanbisurgi @marc7000

**Comment by schmunk42** [comment]
from the two above: https://github.com/sindu12jun/table-dragger

**Comment by pmk65** [comment]
Another one: 
https://sortablejs.github.io/Sortable/  - Would take some more time to implement. As the table rendering needs to be changed, since this one works with UL/LI.

**Comment by schmunk42** [comment]
Or we create a new rendering format for UL/LIs

**Comment by pmk65** [comment]
This one looks **really nice**, but has a LOT of extra features we might not need. Like dragging content inside table cells.  https://github.com/dbunic/REDIPS_drag

**Comment by schmunk42** [comment]
> Another one:
> https://sortablejs.github.io/Sortable/ - Would take some more time to implement. As the table rendering needs to be changed, since this one works with UL/LI.

Examples do not work at all for me!?

**Comment by pmk65** [comment]
Works fine for me in both Chrome and Firefox.

**Comment by schmunk42** [comment]
Works for me too, now. I dunno what was wrong the first time...

**Comment by pmk65** [comment]
> 
> 
> from the two above: https://github.com/sindu12jun/table-dragger

I just did a test, and it was very easy to get dragging working, but I discovered that it had a lot of limitations. Like you'll have to destroy and recreate the dragger every time you add a new row,

The [Redips](https://www.redips.net/my/preview/REDIPS_drag/example15/) lib seems like the best choice, and it has a lot of callbacks needed for updating the JSON-Editor values,

**Comment by skyshore2001** [comment]
any progress? i expect this feature, thanks!

**Comment by schmunk42** [comment]
No progress from our side.

Would you consider working on it?

**Comment by josuema2002** [comment]
You can use this example code, it is in js and does not use libraries.
[Code](https://github.com/josuema2002/DragAndDrop-Array-Table)

**Comment by skyshore2001** [comment]
I implement the feature and create PR#1526 :

Drag and drop for array item is supported. 
For array editor with format=`tabs` or `tabs-top`, dragging the tab header is enabled by default.
But for the default editor or format=`table`, dragging is enabled once by double click on the array item panel. This design avoid side-effect of draggable panel.

**Comment by germanbisurgi** [comment]
Support coming in #1602
