### ISSUE TITLE
> Add Support for new table row  and Add button on top

### ISSUE THREAD

**Issue by ppbntl19** [json-editor/json-editor#451]
> 
> 
> This option doesn't work for arrays with a "table" format. First off, unless I'm missing something, the docs don't make that obvious which should probably be remedied. Second, would it be possible to add this? I have a pretty big array and it's a pain to scroll all the way to the bottom to add a new item.

@taschmidt This should be easy to fix. As the `table` editor extends the `array` editor. So all that is needed is to take the changes I made to the `array` editor and apply them to the `table` editor. (in the `build `function)

_Originally posted by @pmk65 in https://github.com/json-editor/json-editor/pull/186#issuecomment-495197713_

**Comment by ppbntl19** [comment]
https://github.com/json-editor/json-editor/pull/452

**Comment by pmk65** [comment]
@ppbntl19 There's a problem with your changes. The items get displayed in reverse order, so the move buttons points the wrong way.
