### ISSUE TITLE
Radio button doesn't work with `enum_values`

### ISSUE THREAD

**Issue by debnet** [json-editor/json-editor#453]
### General information

- json-editor version: 1.4.0-beta0

### Expected behavior

When using `format: "radio"` with enums, the radio labels must be taken from `enum_values` instead of `enum` if provided in options.

### Actual behavior

Radio buttons are displayed with values instead of labels.

Extra issue for Bootstrap 4 theme: the radio buttons are wrongly displayed inline.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2uFgZGAXUIk0WMmkhDEoMEMYJQEqejBEA8mm7pEAZkKQY5EAGUwAQzDsMTPRjpoIJSLkQgmAWwg4AMrA4AOZgABaIAIyEvjgQ3uzeUcakZsIuIUwAZlho3jaeaFbcEFhMQYn8IJFMAExMBiBiIFLuOPYqIBXeAPomcB0CWgDSTMNaTAAiuADkYAAEwzhYAO5NAL6ELBxcsLwIYGjssOunQA==&value=N4IgLgpgzmIFwgIwgL5A&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "test"
  ],
  "properties": {
"test": {
  "propertyOrder": 3,
  "title": "Status",
  "description": "",
  "minLength": 1,
  "minimum": 1,
  "type": "string",
  "format": "radio",
  "enum": [
    "1",
    "2",
    "3"
  ],
  "options": {
    "enum_titles": [
      "OK",
      "KO",
      "Don't Know"
    ]
  },
  "required": true
}
}
}
```

**Comment by pmk65** [comment]
I have fixed the radio editor issues in the develop/2.x branch
As for the Bootstrap4 issues, then we need someone to step up an take on updating the theme.
