### ISSUE TITLE
creating new format with specific enum values

### ISSUE THREAD

**Issue by elham123456** [json-editor/json-editor#454]
I want to create a new format with special values. Where in the code would that have to be added in?

**Comment by pmk65** [comment]
Create a custom editor in `src/editors/` If you need enum support, then extend the select class. 
Take a look at the Radio editor, as this is extending the select class.

Once you have created your new editor, add a resolver code for your format in `src/defaults.js` (Look at the bottom of the file) You also need to add it to the list of editors in `Gruntfile.js`

Then you can create a custom build with your new editor,

Also take a look at the documentation and the [Wiki](https://github.com/json-editor/json-editor/wiki#editor-srceditorjs)

**Comment by elham123456** [comment]
Thanks!
I created it without adding it to the Gruntfile.js nor the defaults.js. I did so by making a new editor which has a new type similar to the boolean type in the select.js editor only with different enum_options.
