### ISSUE TITLE
Applying regular expression rules on string

### ISSUE THREAD

**Issue by Vafa-Andalibi** [json-editor/json-editor#457]
Is it possible to have a string with regex rules? 

EDIT: Something like custom validation but individualized for a string property

**Comment by Vafa-Andalibi** [comment]
Sorry just saw the Custom Validation in the doc.

**Comment by pmk65** [comment]
You can use the schema `pattern` property to apply your own regex validation rules.

**Comment by Vafa-Andalibi** [comment]
Thank you very much, I used the schema pattern as you suggested and it's working great.
