### ISSUE TITLE
Idea for improving schema field "watch"

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#458]
Currently the "watch" functionality is rather limited when used from within schema options. (Using the on('watch') from JavaScript offers much more flexibility) and the field watching is always readonly.

In the develop/2.x branch I introduced a `callback list` for including JavaScript function callbacks in schema options. (Originally created for 3rd-party plugins that uses callback functions as options)

The same `callback list` functionality could be used for "watch" fields. ~~So instead of setting a "template" parameter, you set a "watchfunc"~~ So if the "template" parameter matches a callback function in the `callback list` it will use the callback function as "template".  The callback function receives the values of the watched field (similar to templates) but can manipulate the data much more freely. 

#### Test case:
- Field1 is a textinput for entering firstname
- Field2 is a radio input with 2 options (male and female) and is watching for changes in Field1

When Field1 loses focus, the watch event is triggered in Field2. this passes the value of Field1 to the "watchfunc", which then does an API lookup at https://api.genderize.io, and sets the Field2 value based on the result. And as the field is not readonly, the user can change it manually too.

The changes needed for this to work, is _very minimal_ since the `callback list` code is already present in develop/2.x

#### Current code in editors/string.js
````javascript
    // Compile and store the template
    if(this.schema.template) {
      this.template = this.jsoneditor.compileTemplate(this.schema.template, this.template_engine);
      this.refreshValue();
    }
    else {
      this.refreshValue();
    }
````

#### After patching code in editors/string.js
````javascript
    // Compile and store the template
    if(this.schema.template) {
      var callback = this.expandCallbacks('watch', {template: this.schema.template});
      if (typeof callback.template === 'function') this.template = callback.template;
      else this.template = this.jsoneditor.compileTemplate(this.schema.template, this.template_engine);
      this.refreshValue();
    }
    else {
      this.refreshValue();
    }
````

And a callback watch function would be defined like this (callback is named "hello")
````javascript
window.JSONEditor.defaults.callbacks.watch = {
  "hello": function(jseditor,e) {
    var watched = e.colors;
    return watched ? 'The color is ' + watched : '';
  }
};
````

@schmunk42 @germanbisurgi @lukzas @mirannda What do you think of this idea?

**Comment by pmk65** [comment]
A live [example](https://pmk65.github.io/20test/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY5kAnHNW%2BAS1QGdMpxoZsAzZrTbwIAQwC26YFm69ecJGk5xhtZhADmcKrwC%2BlHtQSpxyADaj4UmTrkKU17KvVbgBuUYDul4gAtOsh5GYpLKwAJCIhJStnruHgom5paOcCAgIai6utqGUPqxcBqoEAAmqLQBsUaKqcDOmhTV2N7wflV5dsCZYRHCPcDNBZ3YVqYWVmHFZRVmODgA1gCuyLlyORA6G7rAQA%3D%3D%3D&value=ETI%3D&code=EQKQyg8gcgogJgSwC4HsBOA6OBTAZgQwFcAbJAZw20VTQrKTQQDsBzDABzRVSQE93sGAEaEExOAAIAvBNyEmAYyQIUTABQBKCQG8AOkwkSAbvjQSy2YrmkSkACwRkANBIQBufYYS41AQnuOGCjsyqoUCigAtuz4SloBFHbY%2BDhmMgkYxPhCljYZ9tiRgizYSABi6JEAkkzshEgAMtmWahklSAAqyMTYmi4ZjgBK2ACOomhUmhoeBq4%2BGWQKSZH4WNiLjCEqTPEOFDgbCFuqeXsYBUUY7RVo1bX1ACLrCpuh6gtLhasHL0dv0545q0zsE3hRmLgUB1sAAPJC7QIQlAAIXqqAM6TOF2KpRqkNRSHRwMCoO24KYkOhcIBTEBGUht3wSFOgUWy1WDJWSBmXh8%2FjOnKZEgAZMLbGc2V8MEVEPgRWKPuzpVQEKs%2BAItHpZoZ6ZUhZjWZ8VsrZed%2BIIJuwsgpegB6NQAPTU%2BHYVoQCiZ2wAPkhYfDdLp7TCALQaAD8akOIQDGHDGi9amDZBQhDQNoAJBpbSwnAByXM0wwAX0B3j8usZzNF4pJxyY%2BzwRFIAH1BfCdICdQK9cyDRRSWE1gQSEhWz2eRIS7MyxkB%2FWMG3NZ2axQ2yz%2B3XV%2BPAVPAbbbRIwAIFN53bIe6X5t3K0vtRJ9xIqcyAIITfDLmfXrnSKQyXO%2BuFTGSAsOzvLtEXuUd1WwGx%2Fz9ID8FzCdDHA8k6l7FdzmWHFOngt8anQzRkMnZcH0GfBWBggj6mXSwLCBCtv1%2FP80AokoQK1FCUIGSDm2g2DWMopDl0MEwzEiZh1wwSVjQkpgEEiQhIgkL0vQkAAGYjRNMCQVhhKSZNWPSFKUlS1IAWSZOxpXwGE1AARnU9SnDkgBqezCy44wdPobB2BseytIYiUjSMkcjh6CBcFvLyULLOSAFJFSlRTSAi7Aoq0OSbEs%2BwMBtMQ1Dk21ktk8KrQy6KACpSrCtKKqioLeSK2ykpCpVUuUBrot02ycqshdiBQdAWphEr2pS8rIuq2rpSmyqmvMX1%2FL7aTQrm%2BrpqC3cwMw5h0Kk7ErlKcjKOopAiuYFzbKcXz2E84tSIPAAJDpzIaABWCRztsc1aOIejOK8nj0L481YIApBhN27wJDUABtXMREJVRcxcXNPgUABrIQUBhNGJAxlAhrQAnczgJlsDJinfWUIpgyGj1iDJr4xDJ3AxCp9GHDgHAmDJhT8HY9HIlUewyaYJSclJ9GYjIMgAHd0DgMnWMQFBVfWUoyYsUwlh1wghAkqH0d9ZnTb9Mm6a5wnU3NwmFewbAsdzABdDBmBwGEouJLcbwkAA%2BCRgw80DYtQj3eP41a222kS9sgw7sOO8pKnOsoEEsOBfcj0HoIekjZinQwHygPViFsP1XEgwE6JgoGI%2F2%2BowYECHLeIkH6iTwocJuO50IzrOc6bqDzU8naS4POSGmwVh7BcPSZ7nuwXAoyQYkJbA0Fpad5nNFBrFmxfZ5YewJF8X8JF0YB5BwDmmCoa%2BETQ%2BppNKZ9CUYZHelzPSemXtGR9bJL1PnYTyM596HwmsaDevpt7n0vtfW%2BeBmCP2AM%2FXOr8LBIA%2FgwBA381C5lgVvfmThZrEO3p5OuDFIGYUMtKZgICz4XxkEgpgd9UFwCfgndCb8cGf3wfUH%2BFDSG5gwNoXMrkj6MJPvYVyaMiwFhmJeHOc5whRBiHEMO3EzgRCYEgfAqDMAKCyPLBojgkAYBSNnIm0RYhQ3HrXAG9cPxXlrGCTBo4FYIDgPYDBI9pJ8B6Bgbxvi7BSTUZ45soT7ATgnsFQ0So3xwAgEwYgvAzJ0PWsk1Q6TMmzV9NELIvoYo6MCPgYgCt8C8DIM2RAZBsg9EkOkNAhBsAdzOAE7BuCv5CMITktJvAratKpo4nek9DylAkAoQg9AogSCZHg7%2BZAJAnBHhISwPd9EYAkAABVMPgIocDXArNMKxDJB8JCcG4NgJQVAJBY2wDUnZMBoh8AWWgc5cwJBMFUIIOkEpcSQR6YI30ZAEa%2F1sv%2FUBZMRGaxSLkoZItmBkz0jrZabsaQAoguhZcVjeYwCMLPRoFjZ5b0IUsNiXM5CKDeGobAmpw5X12oITg2AiX6KeMOUgRF46CDmewXZXAYgsE9KoXlu144PgeKjZkFShoK2mXYNizAWDfISLITO4gTkLMrkUym8cywWCsGtJUhSrSU1KbFDIJhiBtJsMa3AGBbVtMWhMJAqYmBx3GV5MS3kK6rRde0%2BOUqDwNPksoAAXjBIN8c%2FXhuQAgaNzTzCWCdQmqNvRbUF2arahBMgM1JqoFa4GZwg0Oooom5N3r46Oo9rUxAaB3ktNdfoWtaaMATFwBMMgdgABqFS2kStinW1QABhZVlFWgjILkWLFu9VGbiiUkBALA7Dtk7pY%2BgvBgkrrXRhWcS6R7Nj3euicn53FkkoDCGI7CT3YFXeuktGQUgACtZmjlPRhGlShtj0uICW5qvhLBaHdZ6oKfqEAuCWFISwQRcC4Gwc9B9%2B6goPh%2BqgFA5g7DoCQIanwcGD6IdKMhx9zIAA8GziBrS4MQYgpH92AbilITS8dDAKwcD0f98HiNIAY%2BuiQlG4MbGJvRlD67XIAGYmNcTLAgAOjl1JaCEG%2BLGi0vCuVcuppVmntPCaCYIL9NgljyPYPjRaxcvKWa4tQhuXkEAscWhxzm3GiNIfE8yAOMhhMvFE%2FxpAUmZNxR8PJxTynVPaYQLptjKEljBmDHp6j27d0eeM3YUz5mYvWa8vpndhnUsyDUCZjyGXoaxWy0WZRd5N34rgIS4l5jfIPzQIQx5vBCDsDRj%2BulDLtFcTrW%2Bj996yO%2B1nQXGr1j6v6Ma76ZrFLJ3C263%2B3rdnDADbgO%2B%2Bgw392jeInOjp5SNtDa%2FcOwuKjGJMn8ZBPhIKCHkyZPgJMoU2yAK%2FJdqr2kzDrNWiPc9bi%2FZMUvrmQS7ES3fcwkddop0ShjrFrR4ekF%2BhYmTlDqlEB6iEU3UjxJUo75NmZKpCQuVrJ6RzvQuSJllKE%2BchpDQdO4lttmBkPRDBibd0uNcSosP9Hw4yFkHIxAXAj2xw2KMbwReR3xGiVQnlmdi0Mc1qxrpZ5wAnWIbOcuefE3nRM58TAMlkGPKqCubZlCsHFEKB%2BVAVmoAkMq5XBh8C4GOQUauB1HALN5vc23ru4BREBN49hKAFadtGG0%2BgevBZvDKKxIoaglvipLQ%2BMAWMjjV2mfgeirv1ke8Rbq816BTAZJVDQJwT1VkFDQN4iwQuDCu49PRS5FEFk2mbCX9A0y3zi%2FL8gCQ3i6MSBKM1ymCyDBby4GYBgvBVW2Cwy6AQ7DXDMh90kXSjgyAz5iBMfRZccCuMjB2gJW%2FiW796wN53W9zrDBSLwU7zV1ubc%2FR5rQD%2FjseYPyake48df3gPLD6InMo%2BkgcyEw4oME5qxS2A520CaohQFqJSfW3kZgTMxAQgsQWMUksIt6qu8qaB2M4KuYVSSA%2BsLg2gEBlMAAXFkmanAZAftq4nDNBJcigXgVjOcLQSPsxITAnvzBguQb6MZrgegewfqr6MRNQvkBwQIatK%2BsmA%2FNQOgPlBopzNCKIb0AUlIdgBLvwdgG3qwKguNmcF2j2v2oOr0GMoYLZsuBkMYesKYXauYQzkwJVozvoIHn7iHuANAPAMgIoXjiOOEEIfgSEkyEsDYEDNfEPqkENCgFjB1tfFQTwWoLIe3mgE4CtgwfShgEwIcjBFwfmKBqUOBsuH6j2jYJLHRi4DCCgEIK%2BuUdgIqgABrvTPSEjsDDBjDrAXQFzVG1FBAL6EIADiMAHQZM66SA7AZAFB%2B4LoCAx07CW8RaHsKAtoYYORRQUguYEgrkGy2RuR%2FQM6xEvRr6QQTAySNSBivolKlENgSRTGsMagxxoeN%2BYAlxeRMgAALEFg8U8fQEyLMj%2BITAAExOQgRlEyBeFQAcCmAWCPE1EnE9rsBhDYBPgaDzGpCLQpEKGYDloyBYm%2BGYABK4kSBlEsI%2FIkAVxhgknrASBUG5jIJwJyRUBlbhz7j4k0B8IDoOFqA9o5ooRskWDYmnETpUrTptJ8kVZHHwlvzsJqAVEAZOEuE7wPgdCr6Qh0bB4z7ECoKnKgErDsJMjoAZJrzUkIqDI7IACaKYGejuvM0yH68yEQOACyuMRKQBEgAuweGA%2BgDx7JHezAfxig2Aly7hXpkJPhNAWgfpmABwrOt%2BNI0Z9RiqoZnhkAsA2JagfuMyRQ2ynRaAvAYAmySgI018AAxLIaoMGKkcGJyE%2FC4K%2BlQA9tMMAEAA%3D&style=ETI%3D&theme=spectre&iconlib=fontawesome5&object_layout=grid&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0). (Enter a firstname in the 1st field and then remove focus)

The callback function is defined under the JavaScript/CSS Tab.

**Comment by lukzas** [comment]
@pmk65 I'd use such feature instantly in my project as I was missing something similar. I've seen the demo and wonder if we could still use the template and have another property for callback? This would allow concatenating values directly in the template as it is now.
```
"gender": {
	"type": "string",
	"watch": {
		"name": "firstname"
	},
	"callback": {
		"gender": "genderlookup"
	},
	"template": "I'm a {{gender}}"
}
```

**Comment by pmk65** [comment]
@lukzas I thought at something like that at first, but there are cases (like the Gender example) where it isn't possible. (The "watch" expects the template to return a value, but in the case of the "gender" example, the value is first ready when the AJAX lookup call is finished, so it doesn't return a value but inject it once it's ready)
Also the `compileTemplate` and `expandCallbacks` functions both do the same thing. (compileTemplate converts a template into a function, where expandCallbacks converts a keyword into a function) So the endresult is almost the same.

In both return functions, you have access to all variables defined inside the "watch" property + `self` (content of field)
In the function returned by expandCallbacks you also have access to the editor class.
And you can make same concatenating of values in the callback function.

**Comment by pmk65** [comment]
If there's no objections to this change, I will implement it in the develop/2.x branch
There's only 2 editors with watch/template support. `string.js` (plus all that extends` string.js`) and `hidden.js` so it's a really minor change.

**Comment by pmk65** [comment]
Functionality added to develop/2.x branch
