### ISSUE TITLE
errors not work in anyOf

### ISSUE THREAD

**Issue by wclssdn** [json-editor/json-editor#459]
### General information

- json-editor version: 1.4 & 2.0 /* all */

### Expected behavior

when error occur the editor can show error message.

### Actual behavior

It doesn't show error message in anyOf array.

### Steps to reproduce the behavior

Direct link to example: https://is.gd/FM9u4L

`labelComponent` doesn't work.

```javascript
{
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9_]+$",
      "minLength": 1,
      "maxLength": 50
    },
    "children": {
      "items": {
        "type": "object",
        "anyOf": [
          {
            "$ref": "#/definitions/labelComponent"
          }
        ]
      },
      "type": "array"
    }
  },
  "type": "object",
  "defaultProperties": [
    "id",
    "children"
  ],
  "definitions": {
    "labelComponent": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9_]+$",
          "minLength": 1,
          "maxLength": 50
        }
      },
      "defaultProperties": [
        "id"
      ]
    }
  }
}
```

**Comment by pmk65** [comment]
I noticed a similar problem in the `src/editors/multiselect.js` editor, where the errors wasn't displayed on form.
This is because the error for child elements have a number added to the end of the path. I.e. `root.children.1`
````json
[
  {
    "path": "root.children.1",
    "property": "anyOf",
    "message": "Value must validate against at least one of the provided schemas"
  }
]
````
In the `src/editors/multiselect.js` editor, I solved that by creating a regex to match against the path (which allows the additional child number on the path) instead of a direct comparison. Like this:
````javascript
  showValidationErrors: function(errors) {
    var regexPath = new RegExp('^' + this.escapeRegExp(this.path) + '(\\.\\d+)?$'),
        messages = [];

    $each(errors, function(i,error) {
      if (error.path.match(regexPath)) {
        messages.push(error.message);
      }
    });

    if (messages.length) {
      this.theme.addInputError(this.input || this.inputs, messages.join('. ') + '.');
    }
    else {
      this.theme.removeInputError(this.input || this.inputs);
    }
  }
````

**Comment by wclssdn** [comment]
@pmk65 With debug, i saw some mistakes.
In file [`src/editors/multiple.js#L310`](https://github.com/json-editor/json-editor/blob/0ca9b61cf02a4fc4ba55327c5e02bca58771341a/src/editors/multiple.js#L310)
The logic in `if` is similar with the problem that you said. 

So i cancel the `else`, let it always run. it can show error message on the page.

But, it's not totally correct, the error message is `Value must validate against at least one of the provided schemas` and display below the item title. 

I expect it display at the revelant field. and message like `Value must match the pattern ^[a-zA-Z0-9_]+$.`.

**Comment by pmk65** [comment]
@wclssdn The multiselect editor uses the array type to create the element. So there's only 1 element and only 1 title to display the error under. So this might be a special case.

On the Playground page, the "Output" tab shows all the errors (also those not displayed at the form)
Is the `Value must match the pattern ^[a-zA-Z0-9_]+$.` error message available there?
 
Also I have noticed that some Themes is not displaying the error messages for some elements (specially Bootstrap2). So try using the new develop/2.x Spectre theme for testing. As this is currently the theme most up-to-date.

**Comment by wclssdn** [comment]
@pmk65 It's only one error message. 
```
[
  {
    "path": "root.children.0",
    "property": "anyOf",
    "message": "Value must validate against at least one of the provided schemas"
  }
]
```

The error message is discard at [`src/validator.js#L90`](https://github.com/json-editor/json-editor/blob/master/src/validator.js#L90). 

In debug, i can see that error message like `Value must match the pattern ^[a-zA-Z0-9_]+$.` and path like `root.children.0.id`.

I have no idea to resolve this problem.

**Comment by pmk65** [comment]
@wclssdn The `check` variable in `src/editors/multiple.js`, line 297 expands to **root.children.0.anyOf[0]**
But `error.path` is **root.children.0**,  so they will never match.

Changing the if statement from;
`if(error.path.substr(0,check.length)===check) {`
To:
`if(error.path === check.substr(0,error.path.length)) {`

Will match **root.children.0** against **root.children.0**, so the match is valid.

BUT the fields data-schemapath is **root.children.0.id**, so the error is not placed under the field, but at the top. (So we need to figure out how to append the property name (in this case **id**, to the error path)

**Comment by pmk65** [comment]
I think the if statement changes are correct, and the position above the field is also correct.
As the error is:
````javascript
  {
    "path": "root.children.0",
    "property": "anyOf",
    "message": "Value must validate against at least one of the provided schemas"
  }
````
So it makes sense that it is place **above** the fields. (at the **root.children.0** block)

we might need 2 loops. one for the **root.children.0** and one for the **children root.children.0.id**

**Comment by pmk65** [comment]
I have added the switched if statement to the develop/2.x branch.

**Comment by wclssdn** [comment]
> I think the if statement changes are correct, and the position above the field is also correct.
> As the error is:
> 
> ```js
>   {
>     "path": "root.children.0",
>     "property": "anyOf",
>     "message": "Value must validate against at least one of the provided schemas"
>   }
> ```
> 
> So it makes sense that it is place **above** the fields. (at the **root.children.0** block)
> 
> we might need 2 loops. one for the **root.children.0** and one for the children **root.children.0.id**

The errors of `anyOf` is already checked in [`src/validator.js#L90]`(https://github.com/json-editor/json-editor/blob/master/src/validator.js#L90). So the second loop is not necessary.

**Comment by pmk65** [comment]
Great. So the problem is solved?

**Comment by pmk65** [comment]
I have added this to the `_validateSchema`  in `src/validators.js` to remove any duplicate error messages. (Any error object with same `path`, `message `and `property` will be filtered out.)
````javascript
    // Filter out duplicate error messages
    errors = errors.filter(function (value, i, self) {
        return self.findIndex(function (test) {
            return test.path === value.path && test.message === value.message && test.property === value.property;
        }) === i;
    });
````

**Comment by wclssdn** [comment]
Do you plan to fix this bug, when an array's item is a `anyOf`? 
I'm sorry for can't help.

**Comment by pmk65** [comment]
@wclssdn Have you tried the latest develop/2.x version?
Your PR and mine should have been included, so it might have been solved. (If not, I'll take a second go at it.)

**Comment by wclssdn** [comment]
@pmk65 Thank you. I checkout current `develop/2.x` branch and build it. 

The error message doesn't show, but the input box border is change to red. 👍 

<img width="1247" alt="2019-08-23 00 36 55" src="https://user-images.githubusercontent.com/1057693/63533084-ac3f8900-c53e-11e9-8acd-1cb8e30a4de2.png">

But seems that doesn't contains my PR for choose the right `anyOf`.

<img width="1257" alt="2019-08-23 00 41 51" src="https://user-images.githubusercontent.com/1057693/63533347-2cfe8500-c53f-11e9-9d0a-6312e5d60ae9.png">

You can edit the `docs/index.html` file, change the default schema to this below, and check if you resolve this problem.

```
{
  "title": "anyof badcase",
  "description": "when value has errors with validators. e.g. the id property.",
  "type": "object",
  "properties": {
    "items": {
      "title": "title",
      "type": "array",
      "format": "tabs",
      "items": {
        "title": "item",
        "headerTemplate": "{{self.handler}}",
        "options": {
          "keep_oneof_values": false
        },
        "anyOf": [
          {
            "$ref": "#/definitions/a"
          },
          {
            "$ref": "#/definitions/b"
          },
          {
            "$ref": "#/definitions/c"
          }
        ]
      }
    }
  },
  "defaultProperties": [
    "items"
  ],
  "definitions": {
    "a": {
      "title": "item a",
      "type": "object",
      "properties": {
        "handler": {
          "type": "string",
          "default": "aaa"
        },
        "id": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9_]+$",
          "maxLength": 50
        },
        "___a": {
          "title": "___",
          "type": "string"
        }
      }
    },
    "b": {
      "title": "item b",
      "type": "object",
      "properties": {
        "handler": {
          "default": "bbb"
        },
        "id": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9_]+$",
          "maxLength": 50
        },
        "___b": {
          "title": "___",
          "type": "string"
        }
      }
    },
    "c": {
      "title": "item c",
      "type": "object",
      "properties": {
        "params": {
          "properties": {
            "items": {
              "title": "sub items",
              "type": "array",
              "format": "tabs",
              "items": {
                "options": {
                  "keep_oneof_values": false
                },
                "title": "sub item",
                "headerTemplate": "{{self.handler}}",
                "anyOf": [
                  {
                    "$ref": "#/definitions/a"
                  },
                  {
                    "$ref": "#/definitions/b"
                  }
                ]
              }
            }
          }
        },
        "handler": {
          "default": "ccc"
        },
        "___c": {
          "title": "___",
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by pmk65** [comment]
@wclssdn Sorry, It looks like your #445 PR have only been merged into the master branch. I have asked @schmunk42 to add it to the develop/2.x branch too.

**Comment by pmk65** [comment]
@wclssdn is there any chance you can resubmit the PR in the develop/2.x branch?

**Comment by wclssdn** [comment]
@pmk65 ok.

**Comment by wclssdn** [comment]
@pmk65  I have checked the code, it's already merged. And it's working well.

I don't know why i got that result yesterday.

<img width="1231" alt="2019-08-23 14 02 09" src="https://user-images.githubusercontent.com/1057693/63570279-2576c480-c5af-11e9-8a8d-953665784f16.png">

**Comment by pmk65** [comment]
Ok. But there's still problems I can see.

**Comment by pmk65** [comment]
@wclssdn Can you post the schema and startval you are using in the screenshots?

**Comment by wclssdn** [comment]
@pmk65 Schema is [pasted before](https://github.com/json-editor/json-editor/issues/459#issuecomment-523986066).
Value is generated by editor. Simply add some items. 

1. Edit the file `docs/index.html` change the schema
2. Open the editor by run the file `docs/index.html`
3. Add some items(you would be manual show the property)
4. change some item's type(like `item b`)
5. Click `Update Form` button
6. See what's happened

**Comment by schmunk42** [comment]
It would be great if someone could create a page in `tests/pages` with the schema.

**Comment by wclssdn** [comment]
@schmunk42 Hi, I run the tests on develop/2.x, there are some errors. So, if i add a new file, i can't merge to the branch.

```
-- FAILURES:

  1) string
       editor value and String editor should have coerent values @optional:
     Unable to locate frame: undefined
  
  Scenario Steps:
  
  - I.switchTo(0) at Test.Scenario (editors/string_test.js:37:5)
  - I.see("item 1") at Test.Scenario (editors/string_test.js:34:5)
  - I.click("Add item") at Test.Scenario (editors/string_test.js:33:5)
  - I.amOnPage("string-sceditor.html") at Test.Scenario (editors/string_test.js:32:5)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace

  2) string
       Should work correctly in arrays @optional:
     Unable to locate frame: undefined
  
  Scenario Steps:
  
  - I.switchTo(0) at Test.Scenario (editors/string_test.js:55:5)
  - I.see("item 2") at Test.Scenario (editors/string_test.js:52:5)
  - I.see("item 1") at Test.Scenario (editors/string_test.js:51:5)
  - I.click("Add item") at Test.Scenario (editors/string_test.js:50:5)
  - I.click("Add item") at Test.Scenario (editors/string_test.js:49:5)
  - I.amOnPage("string-sceditor.html") at Test.Scenario (editors/string_test.js:48:5)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace

  3) Validations
       test validations in validation.html:
     element (#output div:nth-child(131)) still not present on page after 10 sec
  
  Scenario Steps:
  
  - I.waitForElement("#output div:nth-child(131)", 10) at Test.Scenario (editors/validation_test.js:8:7)
  - I.amOnPage("validation.html") at Test.Scenario (editors/validation_test.js:6:7)
  
  
  
  Run with --verbose flag to see NodeJS stacktrace


  FAIL  | 52 passed, 3 failed   // 4m
```

**Comment by pmk65** [comment]
@wclssdn Can we close this issue now?

**Comment by wclssdn** [comment]
@pmk65 Yes i think so.

**Comment by Radouch** [comment]
I am probably missing something. If I open the original link https://is.gd/FM9u4L , it still does not work as expected: there is only "high-level" error "_Value must validate against at least one of the provided schemas_", but no errors inside anyOf are displayed. The same behavior is in my local installation of this editor (by npm).

How can errors inside anyOf options be displayed?

**Comment by schmunk42** [comment]
> I am probably missing something. If I open the original link https://is.gd/FM9u4L , it still does not work as expected: there is only "high-level" error "_Value must validate against at least one of the provided schemas_", but no errors inside anyOf are displayed. The same behavior is in my local installation of this editor (by npm).
> 
> How can errors inside anyOf options be displayed?

Is this the follow up? https://github.com/json-editor/json-editor/issues/825
