### ISSUE TITLE
Memory Leak in Object.js Editor

### ISSUE THREAD

**Issue by corykon** [json-editor/json-editor#460]
### General information
Believe I've identified the source of memory leak. 

We noticed that after visiting a page in our angular app with a json-editor (and a VERY large schema), and then leaving, the app felt sluggish. Digging around in Chrome dev tools confirmed that memory usage climbs significantly after visiting the page and never drops back down.

I'm no expert in memory leaks, but some further digging led me to line 647 in [objects.js](https://github.com/json-editor/json-editor/blob/0ca9b61cf02a4fc4ba55327c5e02bca58771341a/src/editors/object.js#L647), where there's an event listener added directly to the document. I tweaked that code to attach a named function instead of an anonymous function, and then detached the listener in [`destroy()`](https://github.com/json-editor/json-editor/blob/0ca9b61cf02a4fc4ba55327c5e02bca58771341a/src/editors/object.js#L1048), and that seemed to prevent the leak.

### json-editor version
1.4.0-beta.0

### Expected behavior
Memory usage return to previous level after destroying the editor.

### Actual behavior
Memory stays bloated.
![memoryLeakHeapSnapshot](https://user-images.githubusercontent.com/12416432/62902383-a8309180-bd1c-11e9-8cbd-634eaf10bad2.png)

### Steps to reproduce the behavior
1) Go to the [Interactive playground](https://pmk65.github.io/jedemov2/dist/demo.html)
2) Upload the json setup from below. You'll notice in the Javascript section I added a couple buttons to destroy and rebuild the editor.
2) Force garbage collection (in chrome dev tools memory tab) and then take a heap snapshot.
3) Load in the sample JSON (also below).
4) Click the "Destroy Form" button
5) Force GC and take another heap snapshot. You'll see that memory is still much higher than before. There are a bunch of leftover objects, arrays, detached DOM nodes, etc.

PS. I'm working on the same application as the submitter of #252, @j2jensen.

For now we'll likely fork and implement the fix in our own application, but would love to submit a PR if the maintainers are supportive.

Has the setup for the interactive demo & json data:
[memoryLeak.zip](https://github.com/json-editor/json-editor/files/3497617/memoryLeak.zip)

**Comment by pmk65** [comment]
@corykon That sounds very plausible. And there's a LOT of anonymous event listeners in other editors too. I have already converted a couple of them to named functions in some editors (like multiselect, select2 and Selectize), in the develop/2.x branch. But I didn't add any code to remove the eventlisteners.

Could you try the develop/2.x branch and see if the problem is still present?
In the develop/2.x branch, several issues have been fixed and should be faster, specially if using 3rd-party based editors. See #450 

BTW: It's possible to upload the ".json" file from the playground, directly in the GitHub comments. You just have to add ".txt" to the field name. (GitHub doesn't like the ".json" file extension) and then drag'n'drop it into the comment field.

**Comment by corykon** [comment]
@pmk65 Thank you! Good to know. I'll give the 2.x branch a look.

**Comment by corykon** [comment]
Memory leak causing us problems was still there in the 2.x branch. Submitted a small PR to fix. #468

**Comment by istvan-arany** [comment]
Hello everyone!
I was fiddling around with some editors, and bumped into a problem.
Even if I set collapsed to true, the child editors doesn't load up collapsed.
If I set collapsed globally, then all the editors main tabs are collapsed too, so I cannot see anything. How could this be solved?

**Comment by pmk65** [comment]
@istvan-arany You probably should open up a new issue and not comment on a closed issue that have no relation to your question. 😉

**Comment by istvan-arany** [comment]
Yea :) I solved it in a different way since then though :)
