### ISSUE TITLE
Collapsing a nested array of objects makes it unexpandable

### ISSUE THREAD

**Issue by wowczarek** [json-editor/json-editor#461]
### General information

- json-editor version: 1.4.0-beta.0

### Expected behavior

Array of objects where one property is also an array of objects. Collapsing the property and expanding it back should be possible.

### Actual behavior

Once "collapse" is clicked for an "array of objects" property within the array editor, the panel which contains both the content and the collapse button, becomes hidden, making it impossible to expand it again

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC5wAsIDsDmBnEAacAngA7xICGAThWQXiAGYD2FAtmWIuGQEZx1SwWOBKDDFSIRtwBWsAMYd8kGBLIACMKkx0iFRiQqRYw0ahOESnLGAroMdZXyQAVMyAC+S5O0SjxVmzsHKCcQVx9PEDJoLEYAfU0IczFLcioaYJVOAEE0ABM1aNiNN3wBIV8LCSlZBUzQgDljMFgCxO18XX1YQwhjSvaMOLIB/yRrWw7wEIlXJJKgyMG47lHUkAmgpRnOcLAF7Xcj4/cgA&value=NobwRALgFglgzmAXGeACAhq6MB2BzMAGkinQiRTgxwHtoBTAJy1nyLHQBs4aB9bBIlAlceXugpooTeu2z5eAI0lUGjWQF8AutqA=&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "title": "Things",
  "type": "array",
  "format": "table",
  "items": {
    "type": "object",
    "title": "a thing",
    "properties": {
      "this": {
        "type": "string",
        "title": "This"
      },
      "that": {
        "type": "string",
        "title": "That"
      },
      "also_this": {
        "type": "array",
        "title": "And also this",
        "items": {
          "type": "object",
          "title": "Nested thing",
          "properties": {
            "thing_a": {
              "type": "string",
              "title": "This thing"
            },
            "thing_b": {
              "type": "string",
              "title": "That thing"
            }
          }
        }
      }
    }
  }
}
```

Try collapsing root.0.also_this.

### Cause / fix / workaround

https://github.com/json-editor/json-editor/blob/0ca9b61cf02a4fc4ba55327c5e02bca58771341a/src/editors/array.js#L689

Unable to tell if doing so carries any adverse consequences, but removing the above line that hides self.panel in the array editor, fixes the issue for me. Row holder becomes hidden, but panel stays, along with the expand button.

**Comment by pmk65** [comment]
I think the problem is that "compact" mode is set as default for this type of array so there's no individual titles.
Normally the Collapse button (`this.title_controls` ) is inserted into `this.title`, which is separated from `this.panel`

In line 162 of `src/editors/array.js,` `this.title_controls` is created and inserted directly into `this.panel`. So clicking the collapse button hides **both  `this.panel` and the child `this.title_controls`.

**Comment by wowczarek** [comment]
@pmk65 sounds about right. `title_controls` should  live outside the panel.

**Comment by pmk65** [comment]
I have fixed this in the develop/2.x branch by adding a empty title element.
