### ISSUE TITLE
fix validation

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#462]
### General information

- json-editor version: 2.0-dev
- I [fixed a few](https://github.com/json-editor/json-editor/compare/develop/2.x...develop/2.x-fix-tests) other tests before (minor errors), but the validations for certain objects are not working correctly.
- Fixing this is a high priority to me, since validations are very important

https://travis-ci.org/json-editor/json-editor/jobs/571279410

### Expected behavior

`validation_test.js` should pass.

### Actual behavior

It doesn't.

### Steps to reproduce the behavior

Run tests from `develop/2.x-fix-tests`.

```
 codeceptjs run editors/validation_test.js 
```

The output with the failures:

```javascript
required4 [test valid 0]: success
required4 [test invalid 0]: fail. Expected: errors, Actual: []
required4 [test invalid 1]: success
required4 [test invalid 2]: success
required4_merge [test valid 0]: success
required4_merge [test invalid 0]: fail. Expected: errors, Actual: []
required4_merge [test invalid 1]: fail. Expected: errors, Actual: []
```

The corresponding test data:

```javascript
required4: {
            schema: {
                type: "object",
                properties: {
                    required: {}
                },
                required: ["required"],
                additionalProperties: true
            },
            valid: [
                {required: true, test: 1}
            ],
            invalid: [
                {},
                "a string",
                [1,2,3]
            ]
        },
        required4_merge: {
            schema: {
                type: "object",
                properties: {
                    orig: {},
                    other: {}
                },
                required: ["orig"],
                oneOf: [
                    {
                        required: ["other"]
                    }
                ]
            },
            valid: [
                {
                    orig: true,
                    other: true
                }
            ],
            invalid: [
                {
                    orig: true
                },
                {
                    other: true
                }
            ]
        },
```

So an empty object `{}` is now accepted, but it should trigger an error.

And `oneOf` seems not to be correctly evaluated, since only an object with `orig` AND `other` should be valid.

CC: @pmk65 @wclssdn Can you shed some light and/or fix this?

**Comment by pmk65** [comment]
@schmunk42 I spent the last 2 hours trying to get Codeceptjs to work on Windows, as the installer kept failing when installing `acorn` and `acorn-dynamic-import` modules.
Finally got it working by adding `"acorn": "^6.0.5",` to package.json

But now I'm stuck at the `codeceptjs init` phase, as I'm not sure what to enter at these prompts:

- Where are your tests located?
- What helpers do you want to use?
- Where should logs, screenshots, and reports to be stored?
- Would you like to extend the "I" object with custom steps?
- Where would you like to place custom steps?
- Do you want to choose localization for tests?

**Comment by schmunk42** [comment]
@pmk65 Did you try testing with Docker?

**Comment by schmunk42** [comment]
For the broken test mentioned above, you can "simply" open `tests/pages/validation.html`

For Docker I'd recommend:
- https://docs.docker.com/docker-for-windows/
- https://docs.docker.com/docker-for-mac/

**Comment by pmk65** [comment]
I hcan't install Docker on my Windows 10 Home, It says "Docker Desktop requires Windows 10 Pro or Enterprise version 15063 to run."
It should be possible to run it if the [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) is installed, but I keep getting the same error message after installing it.

**Comment by schmunk42** [comment]
Oh no :disappointed: 

Do you have something like Virtualbox to create a VM?

**Comment by pmk65** [comment]
According to the Docker documentation, it needs Hyper-V support, which isn't available in Windows Home edition (according to the documentation). But if I look at my System Information, this is displayed:
**Hyper-V Requirements:      
VM Monitor Mode Extensions: Yes
 Virtualization Enabled In Firmware: Yes
Second Level Address Translation: Yes
Data Execution Prevention Available: Yes** 

I also tried installing the Docker Toolbox with all options checked. But Docker still refuses to install. 😢

**Comment by schmunk42** [comment]
Hmm, so sorry I can't really help you here other than googling.

But, as said, my issue does not require to use Docker, rather "just" open `tests/pages/validation.html` to see the problem.

**Comment by pmk65** [comment]
I tried removing the changes introduced in #445 by @wclssdn, but the validation still fails at the same tests. (And the 2nd commit just added a 2nd parameter to the `this.theme.getFormInputLabel` function, so that shouldn't have any effect on the validation results either.)

Does the same tests pass on the 1.4.0-beta.0 version?

This is a list of the last commits to `src/editors/multiple.js` so the errors is not caused by any of the recent changes (The 3rd commit if from 2017). 

> git log --follow src/editors/multiple.js
commit 03d1a31207430bc371747e8fd86c6c890816576d
Author: Nemo <ssdn@vip.qq.com>
Date:   Sun Aug 4 23:34:48 2019 +0800

    choose the best fix schema in the oneOf

commit c0d0f5e53de173e7d9ab5b8e0f97c56ecae909e4 (origin/themereq, themereq)
Author: Peter Klein <pmk@io.dk>
Date:   Thu Jul 25 21:31:21 2019 +0200

    Pass isReady() value to Theme label functions

commit aa611a8b6e7c76039fbff50071448df714cc46ef
Author: Kana <kanabanarama@googlemail.com>
Date:   Wed Jul 26 18:12:52 2017 +0200

    Update multiple.js (#21)

**Comment by pmk65** [comment]
@schmunk42 I found the culprit. It was the code I added for Button and Info editors in `src/validator.js`. 
I'll make a fix ASAP.

**Comment by pmk65** [comment]
Maybe we should update CONTRIBUTING.md with info about `tests/pages/validation.html` ?
It might be a good idea if people ran that before submitting a PR.

**Comment by schmunk42** [comment]
Yes, we can do that, but on the other hand we're running this test always in the CI.
