### ISSUE TITLE
child watches parent = infinite recursion

### ISSUE THREAD

**Issue by wowczarek** [json-editor/json-editor#467]
### General information

- json-editor version: 1.4.0-beta.0

Schema has an array of objects. I want one field in those objects to be an enum list of all values of another field in the same array.

Example of a valid use case: an array of objects describing software releases. A release has a "version" field and a "replaced by" field, where "replaced by" should be an enum of all existing versions.

### Expected behavior:

It should be possible for a property to watch its parent.

### Actual behavior

Nesting a watch like this causes infinite recursion. When you touch the parent array, it notifies the watching child property, which then bubbles up onChange(), which when it reaches the parent, notifies the child, which...

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoYAFuQHYDmN8d0ciAhoYTwh4Q5MDAC27TrATJ0WHPiIkYZSlILEoARlrgusqmELMWIAL5KtAJj2QZiIydbCA7jzCZ6d0+xDEkMAA6Bl8LfBgmAFdxAGUkKMJMbgBtUCoEpO5wMPwANx4AGyjs4GBRCSDlHXNzCwBdWqbzIA==&value=N4IgLgFglgdg5gZxALgNoF0C+Q==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

Add an item to the array and you get `Maximum call stack size exceeded`.

```javascript
{
  "type": "object",
  "properties": {
    "things": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "prop1": {
            "type": "string"
          },
          "prop2": {
            "type": "string",
            "watch": {
              "tings": "root.things"
            },
            "enumSource": [
              {
                "source": "tings",
                "value": "{{item.prop1}}"
              }
            ]
          }
        }
      }
    }
  }
}
```

Looks like we need a smart way to break the loop. I started to tackle this by flagging the watch as "looped" when setting up watches if `watcher.path.startsWith(watched.path)` and then trying to break the event cascade.

**Comment by pmk65** [comment]
Looks very similar to this #306

**Comment by wowczarek** [comment]
Same thing indeed... I also think this can / should be solved. So far I managed to get to a point where it doesn't crash, but enums only get properly updated on array add/remove, and then it starts to interfere with detecting changes in the whole document. I *think* the solution lurks along the lines of "distinguish triggered changes from actual changes". Like I said, there is a valid use case for this kind of construct.

**Comment by pmk65** [comment]
@wowczarek Maybe we could test if the property watching (`prop2`) is a child of the property being watched (`things`). And if so, cancel the bubbling? 

In src/editor.js there's these 3 functions that triggers/controls the `onChange`.
````javascript
  onChildEditorChange: function(editor) {
    this.onChange(true);
  },
  notify: function() {
    if(this.path) this.jsoneditor.notifyWatchers(this.path);
  },
  change: function() {
    if(this.parent) this.parent.onChildEditorChange(this);
    else if(this.jsoneditor) this.jsoneditor.onChange();
  },
  onChange: function(bubble) {
    this.notify();
    if(this.watch_listener) this.watch_listener();
    if(bubble) this.change();
  },
````

**Comment by wowczarek** [comment]
@pmk65 yes, I've been looking at these functions at this block ad nauseam. But first:

`setupWatchListeners`:

```javascript
 if(this.schema.hasOwnProperty('watch')) {
      var path,path_parts,first,root,adjusted_path,my_path;

      for(var name in this.schema.watch) {
        if(!this.schema.watch.hasOwnProperty(name)) continue;
        path = this.schema.watch[name];

        my_path = self.container.getAttribute('data-schemapath');

        if(Array.isArray(path)) {
          if(path.length<2) continue;
          path_parts = [path[0]].concat(path[1].split('.'));
        }
        else {
          path_parts = path.split('.');
          if(!self.theme.closest(self.container,'[data-schemaid="'+path_parts[0]+'"]')) path_parts.unshift('#');
        }
        first = path_parts.shift();

        if(first === '#') first = self.jsoneditor.schema.id || 'root';

        // Find the root node for this template variable
        root = self.theme.closest(self.container,'[data-schemaid="'+first+'"]');
        if(!root) throw "Could not find ancestor node with id "+first;

        // Keep track of the root node and path for use when rendering the template
        adjusted_path = root.getAttribute('data-schemapath') + '.' + path_parts.join('.');

        if(my_path.startsWith(adjusted_path)) {
          self.jsoneditor.watchLoop = true;
        }

        self.jsoneditor.watch(adjusted_path,self.watch_listener);

        self.watched[name] = adjusted_path;
      }
    }
```

So then something like:
```javascript
onChildEditorChange: function(editor) {
    this.onChange(!this.watchLoop);
  }
```

**Comment by wowczarek** [comment]
The recursion starts here: https://github.com/json-editor/json-editor/blob/0ca9b61cf02a4fc4ba55327c5e02bca58771341a/src/editors/select.js#L350

With the above change to `setupWatchListeners()` (just setting `watchLoop`), I can stop the bubbling right there: 

```javascript
      if(this.parent && !this.jsoneditor.watchLoop) this.parent.onChildEditorChange(this);
      else this.jsoneditor.onChange();
```
With this change, things seem to work OK, selects are being dynamically populated across all array members without issues and editor's global onChange() I am using, seems to stay intact.  Maybe this needs some clever logic to still bubble, but sending some termination condition / flag / message / loop counter up the loop so that this happens only once, however right now, for me my problem is fixed.

...but don't blame me if it turns out later that this accidentally summons Cthulhu into someone's pond.

**Comment by pmk65** [comment]
@wowczarek Please create and submit a PR with the changes. This will trigger the tests so we can see if something would fail.

**Comment by wowczarek** [comment]
@pmk65 will do

**Comment by pmk65** [comment]
@wowczarek While adding JavaScript callback support for enumSource https://github.com/json-editor/json-editor/pull/476/commits/7c26fe77b989daa6c7fa7900dbc4dc765b52df9b, I noticed that in the `filter` callback the watched property is available. So it might be possible to filter out the parent somehow. (If you return an empty string, the item will be ignored/filtered)

**Example data available in the filter template:**
````json
{
  "i": 1,
  "item": {
    "text": "Green"
  },
  "watched": {
    "colors": [
      {
        "text": "Red"
      },
      {
        "text": "Green"
      }
    ],
    "self": ""
  }
}
````
