### ISSUE TITLE
How to track what data changes with "on change" event.

### ISSUE THREAD

**Issue by chrislebaron** [json-editor/json-editor#47]
Is there a way to track what has actually been updated with the on change event handler? I tried something like this, but the event comes back undefined:

`editor.on('change',function(event) {
            console.log(event)
 });`

I would like to be able to track incremental changes rather than submitting a full json object.

**Comment by pmk65** [comment]
Not event data, but you could modify the "change" and "onChange" functions of the editor to something like this:

```javascript
  change: function(path) {
    this._super();
  },
  onChange: function(bubble) {
    this.notify();
    if(this.watch_listener) this.watch_listener();
    if(bubble) this.change(this.path);
  },
 ```
Then you have access the the path of the field changed inside the "change" function.
And then you can access the field using "this.jsoneditor.getEditor(path);"

**Comment by pmk65** [comment]
You could use the "watch" handler to watch all fields, like this:

```javascript
var element = document.getElementById('form');
var editor = new JSONEditor(element, options);
var watcherCallback = function(path) {
  console.log("field with path: [" + path + "] changed to [" + editor.getEditor(path).getValue() + "]");
}
for (var key in editor.editors) {
  if (editor.editors.hasOwnProperty(key) && key !== 'root') {
    editor.watch(key, watcherCallback.bind(this, key));
  }
}
 ```

**Comment by germanbisurgi** [comment]
There is no event wich says wich editor changed. But single editors can be watched. pmk65 described a good solution for that

**Comment by pmk65** [comment]
This issue can be closed. I have added the above JavaScript snippet to the docs in a previous commit.
