### ISSUE TITLE
Constant enumSource value specified as array of strings causes a template compilation error

### ISSUE THREAD

**Issue by wowczarek** [json-editor/json-editor#470]
### General information

- json-editor version: 1.4.0-beta.0 + swig templates enabled

### Expected behavior

A constant enumSource value using the shorter syntax (array, without supplying the source object), as described in readme.md, should add the value to the select, with title same as value.

### Actual behavior

An error while attempting to compile the filter template is thrown.

### Steps to reproduce the behavior

Schema:
```javascript
{
  "type": "object",
  "title": "thing",
  "properties": {
    "something": {
      "title": "something",
      "type": "string",
      "enumSource": [
         ["none"],
         ["tba"]
      ]
    }
  }
}
```
### Fix:

https://github.com/json-editor/json-editor/blob/f261e3ab1b40833c6d6ab1b2d0d2308f9d37fd10/src/editors/select.js#L157

Change to:

```javascript
        if(this.enumSource[i].filter && !(Array.isArray(this.enumSource[i]))) {

```
Looks like the same code exists also in `editors/selectize.js` and `editors/choices.js`

**Comment by pmk65** [comment]
@wowczarek Is there any reason why you use Swig template engine? Does it actually work?
I tried the [example](https://github.com/json-editor/json-editor#enum-values) from the Readme.md, but it fails. The only template engine I could get to work was Handlebars. Example: https://is.gd/qGg3Ww

BTW: In the develop/2.x branch, I added support for using JavaScript callback functions in addition to templating. Currently it's only implemented in string based editors, but it might be useful for `enumSource` as well (Not quite sure where to implement it as `enumSource` has multiple sub-properties. `source`, `slice`, `filter` etc.)

**Comment by wowczarek** [comment]
Well I couldn't get any `enumSource` values to format without a template engine loaded (`item.prop` didn't work for me with the barebones var replacement), so I picked Swig at semi random, for no specific reason. My use of templates is minimal, only some `headerTemplate` and the `enumSource.value` - but yes, it does work. But that issue with `["someconst"]` also happens with whatever is used in the github.io demo page.

I guess you should implement callbacks for all of `source`,`slice` and `filter`.

I picked Swig at random because I don't do web often, just every few years I have a problem that needs solved with a web app. So I catch up with what's changed in HTML, js, then quickly forget about what's changed in js because of Internet Explorer being used, and go for it. This time I had a complex document we maintain at work and couldn't stand keeping it as a wiki or Word doc and maintaining formatting, so this got me to JSON Schema and that in turn took me to json-editor + a node.js backend + jsrender/jsviews for viewing the data. 

Right now any issues I come across in json-editor are show-stoppers to me, but once I'm done with what I'm doing, I will likely not be touching json-editor for some time.

**Off-topic:**
1. Do you know if json-editor has a function that can return a cleaned up schema free of any json-editor extras? As in, pure JSON Schema? I think this would be useful.
2. Another feature good to have would be the ability to combine json-editor with a template engine and summon an editor on demand for the given field, as in: you are viewing formatted + templated JSON content and want to edit a specific field. Press "save" and the editor disappears. Essentially a WYSIWYG for the whole thing. I intend to do something like that. Press a button and little edit icons appear next to each field rendered by the template, press that icon and the editor is invoked and the specific editor is brought in place of the field with an "update" button next to it. Initially the edit icon will probably just take the user to the editor page, focusing on the given field.

**Comment by pmk65** [comment]
1) No. The schema is unfortunately not filtered in any way.

2) Not quite sure what you mean, but maybe something like:
[json-schema-editor](https://deepbluecltd.github.io/json-schema-editor/) - Dynamically generated, form-based editor based on the JSON Meta-Schema using the JSON-Editor.

**Comment by pmk65** [comment]
> Change to:
> 
> ```js
>         if(this.enumSource[i].filter && !(Array.isArray(this.enumSource[i]))) {
> ```
> 
> Looks like the same code exists also in `editors/selectize.js` and `editors/choices.js`

I have added a PR with your fix to the develop/2.x branch. In this branch the selectize.js and choices.js editors now extends the selcet.js class, so they don't need any additional fixing.
