### ISSUE TITLE
Unexpected behavior with watch and dependencies

### ISSUE THREAD

**Issue by pkej** [json-editor/json-editor#473]
### General information

- json-editor version:
https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/css/jsoneditor.min.css
https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js
https://cdn.jsdelivr.net/npm/bootstrap@3.4.0/dist/css/bootstrap.min.css
https://cdn.jsdelivr.net/npm/bootstrap@3.4.0/dist/js/bootstrap.min.js
https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js

### Expected behavior

Field "description1a" should show when field "useDescription1" is false.
Field "description1b" should show when field "useDescription1" is true.
Field "description2a" should show when field "useDescription2" is false.
Field "description2b" should show when field "useDescription2" is true.

### Actual behavior

Field "description1a" shows when field "useDescription1" is false.
Field "description1b" never shows up when field "useDescription1" is true.
Field "description2a" shows when field "useDescription2" is false.
Field "description2b" never shows up when field "useDescription2" is false.

### Steps to reproduce the behavior

Direct link to [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYA7DQ648AYkQAaSDHiIkAS0FES5Kilo0RAdy59tZDAFcARrZRYIaFmSzQyXNzhqUAayx6OUwFFBp8FA8IGgAbbWgArnluRhZVdTgSJAgsUX1ERSF8xOttFgiEpMyobMRBUuhyyv1wOvhNYGqAtqzOzsQyAE9KLELgJnt6LDQyWo0Bkl0JnoXsgcRKCCYxiDJtLBQ%2BjqWupywAESO0CG1KA5YARhPFs66RsYn7JiY4rDw0HW70GwEaojwtji82AxDIEFsWDUpxBQ2s%2Fwm13Q90e0CeAH5gSCSKJePgYcREGE0AEfgAPRD9d4AX2RbyWDRudweFTxBFhsHa7LOQ1G4wFiGid2gfCJqOABzIGIlwCxtxxvKe%2FLZG3eiHIODiAGE4ngUMcVaSIDgAHJ4HDinXEkjgyHQzFcjXPbVM%2BVmPBkTCvXXyzx4ezKyndRLJC5q7m4l7AJ3Oki2O6rGNcdPaRkolkp%2BW7XEW4hCkN6sFYMbQRrQNCHUuC32pxBxz08576CFxZwtkHM%2FtLQf5gasoddRroBOa%2BzB52ir4qqWJWXJiegxWRkjxr14ufr0cc0hkQ0ms1NxBW232x0byf5N0UncdxMHwuV%2F2BjDz1vAMMRuKUY9Nmzi7p2eJysSbYZiqIE5nmwrDh%2BIqTBBTblqmLrVp4dYNkcv5YW2YGvpq%2Bjwoi96dCOSFjhu45HucJHTnuABMhGVp8QEkD8fwAkCh60aCrpQs%2BPbOChx5btxiBqmxhKCRWmzANeAYTNStJMAywD0ZJD4sRBrH8mWVGLjJwArjKUGodJHoGbiRnWceBrGqa5oTNedoOk5ykie6KrgQ5PqMaCX5BgKmF%2FgB26IPBzHqoZPnHghcFZilVEMUJXTFryGFUQ%2BNZ4Y2HELsA7b2by7ECuJ4whXRdWwDRSmNXp2EVSwrEHiZDVmRMllrq1HzouZgWVe%2BpknmebmXipZJeXePVVhCol2QlDnjYtYU%2FhF%2BUkNF5lxVcpEdUlykpcBaWwRlg0kDlrQ7Q1BW4Z4%2BF5Y9oLlWtlXkQitVZdRGW6RuMFxCVUlin18KrqdJC2SqACqABKACSsAABTpnEACUMP6qerkXh5ZJIwAMrjKmHHEggABL4%2Be7kqoklC2BIdJ0qa%2FALf9WymmgWAYH8jRQCqhiUMYdDk35z540YJjk6p0tlRAoOKaVWB0valD%2FE2ADau0y2LJhmMbPjps4Vp8FgPhMH4OCJLMIjiJEaCsDgTCCCgXAzCsOkNQAuvRQ5NfVixNcywBAA%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0): 

```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/pkej/schemas/master/link.schema.json",
  "$ref": "#/definitions/link",
  "definitions": {
    "link": {
      "type": "object",
      "id": "link",
      "properties": {
        "useDescription1": {
          "type": "boolean",
          "default": true,
          "title": "Desciption1?",
          "format": "checkbox"
        },
        "description1a": {
          "type": "string",
          "title": "Description1a",
          "htmlClass": "formName",
          "default": "Description1a",
          "watch": {
            "enable": "link.useDescription1",
            "uri": "link.uri"
          },
          "options": {
            "dependencies": {
              "useDescription1": false
            }
          }
        },
        "description1b": {
          "type": "string",
          "title": "Description1b",
          "htmlClass": "formName",
          "default": "Description1b",
          "watch": {
            "enable": "link.useDescription1",
            "uri": "link.uri"
          },
          "options": {
            "dependencies": {
              "useDescription1": true
            }
          }
        },
        "useDescription2": {
          "type": "boolean",
          "default": false,
          "title": "Desciption2?",
          "format": "checkbox"
        },
        "description2a": {
          "type": "string",
          "title": "Description2a",
          "htmlClass": "formName",
          "default": "Description2a",
          "watch": {
            "enable": "link.useDescription2",
            "uri": "link.uri"
          },
          "options": {
            "dependencies": {
              "useDescription2": false
            }
          }
        },
        "description2b": {
          "type": "string",
          "title": "Description2b",
          "htmlClass": "formName",
          "default": "Description2b",
          "watch": {
            "enable": "link.useDescription2",
            "uri": "link.uri"
          },
          "options": {
            "dependencies": {
              "useDescription2": true
            }
          }
        },
        "url": {
          "type": "string",
          "title": "URI (url)",
          "htmlClass": "formURL",
          "fieldHtmlClass": "input-xxlarge",
          "placeholder": "https://",
          "default": "https://",
          "format": "url",
          "examples": [
            "https://www.curseforge.com/minecraft/mc-mods.jeid"
          ]
        }
      }
    }
  }
}

```

**Comment by pkej** [comment]
I'm sure it's just a misunderstanding on my part, but this drove me to frustration and lasted quite a while until I found out the logic.

**Comment by pmk65** [comment]
The dependencies functions uses the internal watch functions. So my guess is that it chokes when you use the same property with `dependencies` and `watch`. (But unfortunately not something easily fixed, due to the shared code.)

But maybe you can rearrange your schema so the property is inside an object, and then use the object property for the dependencies?

**Comment by pkej** [comment]
I made this example to describe how it performs. If I use only 1 dependency, the same behavior, in other words, I have to be very careful about how to set up the true/false.

However, it doesn't seem to be the case with some of the examples. I'll post my actually form here in a few, just fiddling with it first.

**Comment by pkej** [comment]
This example has three string fields. The first you see is the real description which will be a hidden field, because when using templates it remains uneditable even if I want it editable (looking forward to see that in the 2.x as mentioned in another issue).


The second field, the part of the UI, is supposed to be triggered by the checkbox.

The checkbox is only controlling the visibility of the UI-field, as well as going to be a part of the logic in the template of the real description field.

I've changed the checkbox title to an inclusive wording, which as you can see doesn't make the UI-field show up in either state.

Cont'd below the javascript code.


 [Direct link](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYA7DQ648AYkQAaSDHiIkAS0FES5Kilo0RAdy59tZDAFcARrZRYIaFmSzQyXNzhqUAayx6OUwFFBp8FA8IGgAbbWgArnluRhZVdTgSJAgsUX1ERSF8xOttFgiEpMyobMRBUuhyyv1wOvhNYGqAtqzOzsQyAE9KLELgJnt6LDQyWo0Bkl0JnoXsgcRKCCYxiDJtLBQ%2BjqWupywAESO0CG1KA4zgYnbFs66RsYn7JiY4rDw0HW70GwEaojwtji82esDIEFsWDUpxBQ2s%2FwmAFVnLBGug7g8KnBRIc4oIAPzAkEkUS8fAw4iIMJoAI%2FAAeiH67wAvsi3ksGjcCY8gc9Xht3kNRuNYYhondoHwqajgAcyBjZcAALIAQQA0gBRWBao0ACQAkpdLgaAHKwAAyOoAKgaAEoAQk97uVktVuEocTwHgmIBAtju3O5obxt3uIsjPrOiDMQcwJ35Ks8eHsGsZ3USyQu13xcaJid94e0qwLXEr5aTYKFpaeeZ6XBjwqJTv9nJRPK5Z15A4FjZLhJY3ZwlHTEobnxlefliSVwD5s5HatzJGLsfHorX1IMZBwcQAwoGUMdNbSIDgbXgcDKD9Tk6mMDPD10szmFyQ20Wmz3XsMyWIc%2BwbXYRSvF5hxVRoxmgRpoDQQ5oNgcVP1BACxxFfR4URWD%2B3A0DCPgMCQPOO4PxfVVpQmJdFXrUFN1%2FRBMVdc1YAACnDOIAEomK6cgT3PPBLwmG8cHY%2B1BJpUlBFNY8zwvNDEESShbAkNk2UDfgn1I0EAzwNAsAwP5GigTVDEoYw6FkxBJKDCY61XAyvzZB8AyOfQAG03NBazbJoMwQp8cNnBvPgsB8Jg%2FBwRJZhEcRIjQVgcCYQQUC4GYVmAfyAF0DO5Qjir7UrFnK6BuWAIA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)

Code:
```javascript
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/pkej/schemas/master/link.schema.json",
  "$ref": "#/definitions/link",
  "definitions": {
    "link": {
      "type": "object",
      "id": "link",
      "properties": {
        "useDescription": {
          "type": "boolean",
          "default": true,
          "title": "Use description field?",
          "format": "checkbox"
        },
        "description":{
          "type": "string",
          "title": "MAKE ME HIDDEN LATER!!!!",
          "template": "{{uri}}{{description}}",
          "watch": {
            "enable": "link.useDescription",
            "uri": "link.uri",
            "description": "link.descriptionTemp"
          }
        },
        "descriptionTemp": {
          "type": "string",
          "title": "Description",
          "htmlClass": "formName",
          "watch": {
            "enable": "link.useDescription"
          },
          "options": {
            "dependencies": {
              "useDescription": true
            }
          }
        },
        "uri": {
          "type": "string",
          "title": "URI (url)",
          "htmlClass": "formURL",
          "fieldHtmlClass": "input-xxlarge",
          "placeholder": "https://",
          "format": "uri",
          "examples": [
            "https://www.curseforge.com/minecraft/mc-mods.jeid"
          ]
        }
      }
    }
  }
}

```

In this code I have reversed the language and settings to the oppsite using excluding language, and now it works as expected.

[Direct link](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgTmB2AEtmAEgM4GMAWBTAtgQ0QC4FgMAXMgB0IHoaArFAe2gFp1t8A6JiAcxoATCHgBmZVgAYA7DQ648AYkQAaSDHiIkAS0FES5Kilo0RAdy59tZDAFcARrZRYIaFmSzQyXNzhqUAayx6OUwFFBp8FA8IGgAbbWgArnluRhZVdTgSJAgsUX1ERSF8xOttFgiEpMyobMRBUuhyyv1wOvhNYGqAtqzOzsQyAE9KLELgJnt6LDQyWo0Bkl0JnoXsgcRKCCYxiDJtLBQ%2BjqWupywAESO0CG1KA4zgYnbFs66RsYn7JiY4rDw0HW70GwEaojwtji82esAhcWcalOIKG1n%2BEwAErosLBGug7g8KnBRIc4oIAPzAkEkUS8fAw4iIMJoAI%2FAAeiH67wAvki3ksGjcCY8gc9Xht3kNRuNYYhondoHwqSjgAcyOjZcAALIAQQA0gBRWBao0YgCSl0uBoAcrAADI6gAqBoASgBCD1u5WS1W4ShxPAeCYgEC2O7c7khvG3e4iiPes6IMyBzAnfkqzx4ewaxndRLJC7XfGxokJn1h7SrfNcCtlxNgoUlp65npcaPComOv2c5E8rlnXn9gUN4uElhdnCUNMS%2BufGW5%2BWJJXAPkz4dqnMkIsxsei1fUgxkHBxADCAZQx01tIgOGteBwMv31KTKYw04PXUz2fnJFbhcbu49umSyDr29a7CKl4vEOKqNGM0CNNAaCHFBsDih%2BoL%2FqOIr6PCzgwX2YEgQR8CgcB5x3O%2Bz6qtKEyLoqdaghuP6IAAqi6ZqwAAFGGcQAJSMV05DHmeeAXhM144OxdqCTSpKCBiR6nueqGIIklC2BIbJsgG%2FCPiRoL%2BngaBYBgfyNFAmqGJQxh0LJiCSYGEy1iuBmfmy97%2Bkc%2BgANpuaC1m2TQZghT4YbONefBYD4TB%2BDgiSzCI4iRGgrA4EwggoFwMwrMA%2FkALoGdyBHFb2pWLOV0DcsAQA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=0)

Code:
```javascript

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/pkej/schemas/master/link.schema.json",
  "$ref": "#/definitions/link",
  "definitions": {
    "link": {
      "type": "object",
      "id": "link",
      "properties": {
        "useDescription": {
          "type": "boolean",
          "default": false,
          "title": "Hide description field?",
          "format": "checkbox"
        },
        "description":{
          "type": "string",
          "title": "MAKE ME HIDDEN LATER!!!!",
          "template": "{{uri}}{{description}}",
          "watch": {
            "enable": "link.useDescription",
            "uri": "link.uri",
            "description": "link.descriptionTemp"
          }
        },
        "descriptionTemp": {
          "type": "string",
          "title": "Description",
          "htmlClass": "formName",
          "watch": {
            "enable": "link.useDescription"
          },
          "options": {
            "dependencies": {
              "useDescription": false
            }
          }
        },
        "uri": {
          "type": "string",
          "title": "URI (url)",
          "htmlClass": "formURL",
          "fieldHtmlClass": "input-xxlarge",
          "placeholder": "https://",
          "format": "uri",
          "examples": [
            "https://www.curseforge.com/minecraft/mc-mods.jeid"
          ]
        }
      }
    }
  }
}

```

**Comment by pkej** [comment]
And thanks for the quick response :)
