### ISSUE TITLE
`npm test` script does not run and appears to be obsolete

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#485]
### General information

When I run `npm run test` from Windows powershell I get an error output. A closer look at the scripts suggest it is trying to call mocha tests but it seems that these don't exist. Is the script obsolete?

- json-editor version:
commit: commit 1bebfc1240cd30935e54607c8fd045b95bd80775

### Expected behavior
Should give me some useful output

### Actual behavior
```
npm run test

> @json-editor/json-editor@1.4.0-beta.0 test C:\flow\forks\json-editor-master
> grunt test

Running "run:mocha" (run) task
>> Error: spawn mocha ENOENT
Warning: non-zero exit code -4058 Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @json-editor/json-editor@1.4.0-beta.0 test: `grunt test`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the @json-editor/json-editor@1.4.0-beta.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sirockin\AppData\Roaming\npm-cache\_logs\2019-08-20T09_54_45_589Z-debug.log
PS C:\flow\forks\json-editor-master> 
```

**Comment by schmunk42** [comment]
Yeah, can be removed I think. It was added in fairly large merge-commit.

**Comment by sirockin** [comment]
Okay great - I've actually replaced the script in #486 (it now runs unit tests in watch mode)
