### ISSUE TITLE
Webpack - Should we have a uncompressed version available?

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#489]
I'm a newbie when it comes to Webpack, so bear over with me if this sounds stupid. 😁 

In the 1.4 version wh have a minified and an unminified version avaliable at jsdelivr CDN.
From what I can see, the Webpack system currently only build a minified version. (The old Grunt build, created both minified and an unminified versions)

On the Playground page, I use the unminified version so that code examples that overrides the existing functionality, matches the source. (Doing this on the minified version would first require that I unminify it, then find the function to override, and match all the truncated variables with the ones in source. ZZzz..)
 
@schmunk42 @germanbisurgi @sirockin

**Comment by sirockin** [comment]
@pmk65 don't worry, this is my first time playing with Webpack, other than using it as part of the  Angular infrastructure and obviously I'm new to collaborating on this project and still finding my way around it so forgive me if I ask any stupid questions.

The impression that I get is the workflow encouraged by Webpack is to only distribute the source code and sourcemap, and to carry out debugging using the sourcemap. If you want to debug a distribution (say on a CDN as in your case) I'm pretty sure it's possible to tell your debugger (eg Chrome Dev Tools) to point the source map back to the files on your machine.

I did try to get readable output by doing a development build but didn't get very far with it. I can try again though. I also wonder how that would work once (as I'm doing now for my webpack_optimization branch) we move to using ES2016 transpilation.  Can any Webpack experts out there advise on this? 

I'm not really clear on the structure and intended role of the playground - can you point me to any docs on it? Is it intended as a demo tool or a debugging tool? If the latter, would it be possible to incorporate it into this repo? That way those wishing to use it to debug could do so on the local machine, in which case sourcemaps should work out of the box.

**Comment by pmk65** [comment]
Here's a Playground example that adds custom editor https://is.gd/WihSGg 

The Playground is a place to test JSON-Editor setups, including more complex ones with additional JavaScript/CSS setups. You can also use it for debugging or development (That's what I do.)

I originally intended it as a replacement for the [interactive demo](https://json-editor.github.io/json-editor/) from the docs/ folder. But the project grew as I added more and more features. So I decided to keep it as a separate project instead of merging it into this repo. (But there's a link to the live version at the top of the README.md, and from there you can go to the repo.)

BTW:  Found this one. https://github.com/leftstick/unminified-webpack-plugin

**Comment by schmunk42** [comment]
Yes, we also need an unminified version.

**Comment by sirockin** [comment]
Okay I've thrown unminified-webpack-plugin into my current branch and it does seem to do what's required. Obviously the code's not simply a concatenation of the original files but it is readable. Let's leave this open until the PR goes in.

**Comment by sirockin** [comment]
I notice that the travis e2e test runs actually test against jsoneditor.js which was (and will again be) the unminified version. For completeness, shouldn't we make it test against both?

**Comment by schmunk42** [comment]
> I notice that the travis e2e test runs actually test against jsoneditor.js which was (and will again be) the unminified version. For completeness, shouldn't we make it test against both?

Hmm, yeah. Won't hurt in a Travis matrix.

**Comment by sirockin** [comment]
Would you have any objection to changing the naming convention so that output files have the same name but unminified goes to a separate directory (eg dist/unminified) - I think that will make it easier to set up test scripts to use the same html files from /tests/pages/ (I can just set up the test server to serve ./dist from another file).

**Comment by schmunk42** [comment]
> Would you have any objection to changing the naming convention so that output files have the same name but unminified goes to a separate directory (eg dist/unminified) - I think that will make it easier to set up test scripts to use the same html files from /tests/pages/ (I can just set up the test server to serve ./dist from another file).

Would be fine for 2.x

**Comment by sirockin** [comment]
Okay so I'm building:
production (minified): dist/jsoneditor.js
development (non-minified): dist/dev/jsoneditor.js

**Comment by schmunk42** [comment]
CC: @marc7000

**Comment by marc7000** [comment]
That already exists it is done with grunt task.
Currently it builds the following files:

- dist/jsoneditor.min.js.map
- dist/jsoneditor.min.js
- dist/jsoneditor.js.map
- dist/jsoneditor.js

https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js
https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

**Comment by sirockin** [comment]
Grunt is dead. Long live Webpack! ;-) I'm on it, don't worry.

**Comment by marc7000** [comment]
... Have fun ;-)
