### ISSUE TITLE
Webpack - Included CSS files are not minified

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#490]
@sirockin I noticed that in the `jsoneditor.js` build by Webpack, the CSS is now included. But this seems to be unminified, so comments are included. See below:

>typeof s&&(s=[[t.i,s,""]]);var n={insert:"head",singleton:!1};i(15)(s,n);s.locals&&(t.exports=s.locals)},function(t,e,i){(t.exports=i(14)(!1)).push([t.i,".starrating {\n  direction: rtl;\n  display: inline-block;\n  white-space:nowrap;\n}\n.starrating > input {\n  display: none;\n}  /* Remove radio buttons */\n.starrating > label:before {\n  content: '\\2606'; /* Empty Star */\n  margin: 1px;\n  font-size: 18px;\n  font-style:normal;\n  font-weight:400;\n  line-height:1;\n  font-family: 'Arial';\n  display: inline-block;\n}\n.starrating > label {\n  color: #888; /* Start color when not clicked */\n  cursor: pointer;\n  margin: 0;\n  margin: 8px 0 2px 0;\n}\n.starrating > label.starrating-display-enabled {\n  margin: 1px 0 0 0;\n}\n.starrating > input:checked ~ label,\n.starrating:not(.readonly) > input:hover ~ label {\n  color: #ffca08; /* Set yellow color when star checked/hover */\n}\n.starrating > input:checked ~ label:before,\n.starrating:not(.readonly) > input:hover ~ label:before {\n  content: '\\2605'; /* Filled Star when star checked/hover */\n  text-shadow: 0 0 1px rgba(0,20,20,1);\n}\n.starrating .starrating-display {\n  position: relative;\n  direction: rtl;     \n  text-align: center;\n  font-size: 10px;\n  line-height: 0px;\n}\n",""])}]);

**Comment by sirockin** [comment]
hmmm. Okay will look into it.

**Comment by sirockin** [comment]
Have tried minimizing using optimize-css-assets-webpack-plugin but no dice with comments.

Someone else has opened an issue on this so I'll keep an eye on it:

 https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/93

**Comment by pmk65** [comment]
It's not just the comments (But that's what caught my attention) It is isn't minified at all.
If it was minified, the "\n" and spacing would have been removed.

**Comment by sirockin** [comment]
The above plugin does seem to remove spacing but for some reason not the '`n'.

**Comment by pmk65** [comment]
Bus should something like `(.readonly) > input:hover ~ label:before` be concatenated into `(.readonly)>input:hover~label:before`  ? (spaces removed)

**Comment by sirockin** [comment]
No that doesn't appear to be happening - I'll look into finding a clean way - someone else must have solved this - before resorting to dirty.

**Comment by pmk65** [comment]
2 Webpack 4 plugins for minifying CSS:
https://github.com/NMFR/optimize-css-assets-webpack-plugin
https://webpack.js.org/plugins/mini-css-extract-plugin/

**Comment by sirockin** [comment]
Thanks - I'm already using them.

**Comment by pmk65** [comment]
Maybe useful: https://github.com/marharyta/webpack-boilerplate

**Comment by germanbisurgi** [comment]
fixed in #647
