### ISSUE TITLE
allOf inheritance doesn't work consistently

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#500]
### General information

I know there are a few open issues on `allOf` but wanted to log this which is related to my own use-case. I think it's going to be easier to work on now that (in develop/2.x) we have a reasonably usable unit-testing framework.

- json-editor version:
current master, develop/2.x

### Expected behavior
A schema inheriting properites via allOf should produce the same behaviour as its equivalent flattened hierarchy.

### Actual behavior

There are several key differences including:

1. Field is not generated for inherited required property 
2. No options is given to add inherited non-required property
3. Inherited fields with option `"hidden":true` are displayed

### Steps to reproduce the behavior

The following example links show the different behaviours for:

1. [Inherited hierarchy](https://json-editor.github.io/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEGzhcAluXmZ5FCGlBIlyADYaQmAJ444aEKQBGROFExSQORqROMVcdalDy2+oybPkAK4IFnCMIAC+0lryugByFABKcACOgfKMcD6eBsam6BCYjIrMkdHaSDoAEt6y5L55ZoXF5KXSzipq+jC1cPWoRYFwESPSmWkZWWgA2iDeIAC6USA6WmwAghV6OZU6APJcM6BgmYfoYvhQpIHkmGH4AIyRC9J++eZWNnavyjrvADJrAAEm1ilXsjmcYTcHlAQQQ/zgzFhuX86EUd2YYUiy3G6Uy2Vm8MRyMWoxAuwOR3ApzMFyuNzujHwACZnq9GuhLNZbPYVJg/mYAMJIb4OJwuGH6CyZKY5N5NIolHFjVL4uWzGVwKZLIA&value=N4IgRgTgplAmIC4QgDQgHYFcC2AZKA5gM6IAMaAFgJayxTqIgVQA2LA9iAL5A===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

2. [Flattened equivalent](https://json-editor.github.io/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEJgCeOOGhCkARkThRMUmQEtMAG0XoAwki3ScjUgsaYdcCGlA62TmfKMhyAVwQq4jCAAvtJI5DrI+gByFABKcACO3jqMcK6ooHIKShCYjDrkzMGh4ZEAEi5scORuWZ65+YXa1nYUjhkYldVoed5wQSFevgAycMztmR5KBZhjAcUgKqlptVPoDQVFA9KpSSkrqADaIC7aPgij49pLcCsAukFAA==&value=N4IglgJiBcAMA0IB2BXAtgGQKYHMDOMCIARgE5ZZTQgiICGSYadANgBKQRZIwgAWWFiwD2IAL5A=&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default)

**Comment by sirockin** [comment]
I'm going to close this as I think I've already fixed it in #430  :-D

I think my confusion was because the interactive JSON Editor hasn't been updated with the fix.

**Comment by pmk65** [comment]
The Interactive JSON Editor is not 100% reliable. Specially when you start switching on/off options and external libraries. That's why I wrote the Playground page. This renders the form in a separate iframe and redraws the frame when options change.

**Comment by sirockin** [comment]
Is the Playground documentation - or a link to it - somewhere in this repo?

If we're not using in interactive editor, can we remove it from the bugfix template?

**Comment by pmk65** [comment]
At the top of the README.md there's a link to both the Interactive demo and the Playground.

**Comment by sirockin** [comment]
Hah, sorry, didn't spot it! :-D. 

I think there should definitely be a warning for the interactive editor and get it removed from the bugfix template.
