### ISSUE TITLE
Suggestions for new data format with replacement config for the old JSONEditor.defaults

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#502]
**Suggestions for new data format with replacement config for the old JSONEditor.defaults**

````json


{
   "schema": {},
   "startval": {},
   "config": {
      "options": {
         "theme": "spectre",
         "object_layout": "grid"
      },
      "callbacks": {
         "button": {},
         "ace": {}
      }
   }
}
````
@schmunk42 @sirockin What are your comments on this solution?
Personally I never liked the way you modified the global instance of `JSONEditor.defaults`, so I would prefer something like this.

_Originally posted by @pmk65 in https://github.com/json-editor/json-editor/issues/494#issuecomment-524573963_

**Comment by sirockin** [comment]
Is the old format documented somewhere (for comparison)?

>  I never liked the way you modified... 

I'm not sure of the meaning of the above - I didn't modify anything in the JSONEditor.defaults, I just removed the circular dependencies between editors and JSONEditor by injecting JSONEditor.defaults as a parameter to the editor.

**Comment by pmk65** [comment]
> 
> 
> Is the old format documented somewhere (for comparison)?
> 
> > I never liked the way you modified...
> 
> I'm not sure of the meaning of the above - I didn't modify anything in the JSONEditor.defaults, I just removed the circular dependencies between editors and JSONEditor by injecting JSONEditor.defaults as a parameter to the editor.

I'm referring to how the original script worked, by modifying the object directly for setting the defaults instead of passing them as parameters when you create the instance.

**Comment by sirockin** [comment]
Ah sorry, yes I understand now. I agree having a global defaults object is potentially messy and can cause problems, especially if you're creating and tearing down instances of the editor.

I also don't really like the schema being part of the options object - it's not really an option but an essential parameter so I think it should be passed as such.

**Comment by pmk65** [comment]
> 
> I also don't really like the schema being part of the options object - it's not really an option but an essential parameter so I think it should be passed as such.

The same goes for the `startval` property. But if we change `schema` and `startval` to separate parameters, we might have a problem. As the startval is optional and can be any value (including null) so we can't just use a null value for no startval.

**Comment by sirockin** [comment]
I think you've just explained why `startval` should stay as an option - it's optional! :-D

Schema on the other hand, is compulsory, and shouldn't changed for the lifetime of the editor.

**Comment by pmk65** [comment]
Schema and startval are tied together. So I would be odd IMO, if one of them is a separate parameter while the 2nd is part of the options array.

**Comment by germanbisurgi** [comment]
i am closing this :)
