### ISSUE TITLE
Clarify and document function of `no_additional_properties` 

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#509]
### General information

I would like a way to tell the json-editor to ignore any properties found in the json but not defined in the schema. 

So for example [here](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIasAjgK4QsAmiA2iBwBDALbwAuoRJosZNJFgZEoYWOXEyiEBjBoIOAOZNuiunpKRcWgGJcdAAiE5u9gDJCHq+IRH7XsQzAAC0QAFkITADMhdmhGJAApdFgRInsAESw0PABfPKA=&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCADQgQDmc8AzACwC+QA=&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction), only the name field should be displayed, not age.

Does such an option already exist? If not how about adding one?

**Comment by pmk65** [comment]
`"no_additional_properties": true` - Example. https://is.gd/1IxWu8

**Comment by sirockin** [comment]
Thanks! I just tried something similar in the interactive editor and it worked there. But not in my current build for some reason.

**Comment by sirockin** [comment]
Okay so it does seem to work to an extent, but there is a problem (at least for my use case). It doesn't just ignore the property, it deletes it from the output JSON altogether. I essentially want it to leave any additional properties untouched - as if they are defined in the schema but with `options.hide:true`

**Comment by sirockin** [comment]
Looking at the code (in validator.js and object.js) and also at previous issues including #130, it seems there is some confusion over what the correct function of `no_additional_properties` should be.

Should it

1. Satisfy my use case - simply not display any additional properties but leave them untouched in the JSON

2. Essentially replicate the `additonalProperties:false` option in the schema itself - prevent additional properties from being added and raise validation errors if additional properties are present

Clearly I can see a use case for 1 since that's why I raised this issue in the first place :-D

I find it harder to see the use case for 2, since it's just repeating something which can (and IMO should) be set in the schema in the first place.

Either way, for clarity, perhaps the options should be renamed:

Use Case 1: `hide_additional_properties` (defaults to false)

Use Case 2: `additional_properties` (defaults to schema `additonalProperties` value

Comments from @json-editor/maintainers please?

**Comment by sefaYavuz** [comment]
So I would like this, but the other way around. 

If I don't have an property in my object that is present in the schema. Show the property anyways, now it just removes the property.

**Comment by pmk65** [comment]
So what you want is the undefined data to be placed in hidden fields so it can't be edited, but still a part of the form result?

Couldn't you just filter out the undefined values based on the schema properties, before rendering form. And then merge the form result with the original result before submitting?

**Comment by sirockin** [comment]
> So what you want is the undefined data to be placed in hidden fields so it can't be edited, but still a part of the form result?

Yes

> Couldn't you just filter out the undefined values based on the schema properties, before rendering form. And then merge the form result with the original result before submitting?

Well I *could* *just* do that. But I was hoping not to have to :-). It would be nice if that was one of the options in the editor.

So is your understanding of `additional_properties` option that is simply overrides the schema `additionalProperties` value?

**Comment by sirockin** [comment]
> Couldn't you just filter out the undefined values based on the schema properties, before rendering form. And then merge the form result with the original result before submitting?

@pmk65 I've raised this enhancement as a separate issue #523.
