### ISSUE TITLE
Boolean as combobox with custom `enum` (ie. for nullable boolean) doesn't work

### ISSUE THREAD

**Issue by debnet** [json-editor/json-editor#516]
### General information

- json-editor version: 1.3.5

### Expected behavior

Boolean as a combobox should trigger the model update.

### Actual behavior

Boolean as a combobox doesn't work, no model update event is triggered and the field stay constantly at the first enumerated value.

### Steps to reproduce the behavior

https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIwAeYATgIZ4hTVKzVgEwDOCoYXO8UExYw2EAPLUAJqIQBGfOxJkQAFX4ACGRpRIkxAJcwAdgxmdM1AlHZJTiBgFsCxgDImA5mAAW8/M+MCRwBXRz9waBVdfRhaU3wTUIQAbRpgmFwAM1piThgAXXwWW2NuQRBExwB9JVIy5JAATS4GADkkEHyAX3xqGABHYII+qQQ0mB7wfgAmHkZmVkhJGWpw2pV1TjAtAHIDY1CDOhKzLktrE4d/F3djL194BRAAoKTHxUiEEC2rO4ZMpDURy0AQHYjEBIHMLwBpyBizfAAZk6RRsBDsZVAlRqRDqKRAACFaKN8ABBABuoloHjg+AA4npRt1egMhiMxtR0l1uUA===&value=N4IgLgpgzmIFxgE4FcIBpzTAJniAjCAL5A==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "type": "object",
  "title": "extra",
  "properties": {
    "test": {
      "propertyOrder": 1,
      "title": "Test de booléen",
      "description": "",
      "minLength": 1,
      "minimum": 1,
      "type": "boolean",
      "enum": [
        true,
        false
      ],
      "options": {
        "enum_titles": [
          "Yes",
          "No"
        ]
      },
      "required": true
    },
    "test2": {
      "propertyOrder": 1,
      "title": "Test d'énumération",
      "description": "",
      "minLength": 1,
      "minimum": 1,
      "type": "string",
      "format": null,
      "enum": [
        "1",
        "2",
        "3"
      ],
      "options": {
        "enum_titles": [
          "Bad",
          "Average",
          "Good"
        ]
      },
      "required": true
    }
  }
}
```

**Comment by debnet** [comment]
By the way, I know it works by removing the `enum` property. But sometimes I want to change the order of the elements and often I would like to create a kind of null-boolean field.

https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAacAlmADZyIwAeYATgIZ4hTVKzVgEwDOCoYXO8UExYw2EAPLUAJqIQBGfOxJkQAISRJStAHYACPpxz4ZnTNQJR2SbQhAMAtgW0AZGNoDmYABbz8j7QT2AK72vuDQKigaWjb4biEIANraQcTEuDRBMLgAZrTEnDAAuvgsVtrcgiDx9gD6SqSViSAAqtoA1tpIAO6xIACaXAwAckggRQC++NQwAI5BBDNSCJkwU+D8AEw8jMyskJIy1GENKgCiKfaitOX6/AwmZhbltg5Orh7eYf6BCfAK4VgtkM5g8DBySGo9huCBSaTilySIDkDG2+AAzONSpYCNZKqAavUiI0kapaMt8ABBABu13ccHwAHENMtJtM5gslitqFkJnygA==&value=N4IgLgpgzmIFwDMCGAbKEA05pgEzxAEYQBfIA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
  "type": "object",
  "title": "extra",
  "properties": {
    "test": {
      "propertyOrder": 1,
      "title": "Boolean test",
      "description": "",
      "minLength": 1,
      "minimum": 1,
      "type": "boolean",
      "enum": [
          null,
          true,
          false
      ],
      "options": {
        "enum_titles": [
          "Unknown",
          "Yes",
          "No"
        ]
      },
      "required": true
    },
    "test2": {
      "propertyOrder": 1,
      "title": "Enumeration test",
      "description": "",
      "minLength": 1,
      "minimum": 1,
      "type": "string",
      "format": null,
      "enum": [
        "1",
        "2",
        "3"
      ],
      "options": {
        "enum_titles": [
          "Bad",
          "Average",
          "Good"
        ]
      },
      "required": true
    }
  }
}```

**Comment by pmk65** [comment]
A boolean checkbox/select is only rendered correctly when there's NO `enum` present. (and only allows values `true` or `false`)

````javascript
    "billing": {
      "title": "Billing address same as shipping address",
      "type": "boolean",
      "format": "checkbox",
      "default": true
    },
````

**Comment by debnet** [comment]
How can I achieve to have nullable boolean then?

**Comment by debnet** [comment]
And changing the order of choices?

**Comment by pmk65** [comment]
You will probably need to create a custom build with a modified `src/editors/select.js` that renders the Boolean type as you want.

This is how a Boolean selectbox is rendered currently.
````javascript
    // Boolean
    else if(this.schema.type === "boolean") {
      self.enum_display = this.schema.options && this.schema.options.enum_titles || ['true','false'];
      self.enum_options = ['1',''];
      self.enum_values = [true,false];

      if(!this.isRequired()){
        self.enum_display.unshift(' ');
        self.enum_options.unshift('undefined');
        self.enum_values.unshift(undefined);
      }

    }
````

**Comment by pmk65** [comment]
@debnet If you don't set `required` for the boolean field, you get an blank start entry in the selectlist with the value of "undefined". The order is fixed, but you can set the labels of the `true/false` values.
Example: https://is.gd/aat1LP

**Comment by petrolep** [comment]
@pmk65 I am also trying to get a "nullable boolean" selector - ideally with return values null/true/false.
However the first option from the select with the "undefined" HTML value returns "true" as its JSON value.

So from the three options "undefined/true/false" you get values "true/true/false".

Is this by design or a bug?

Seems to be because of `!!"undefined":`
https://github.com/json-editor/json-editor/blob/master/src/editors/select.js#L49

Thank you.

**Comment by pmk65** [comment]
@petrolep It looks like a bug to me. As "undefined" should not evaluate to "true"
Changing it to
 `if (this.schema.type === "boolean") return value === 'undefined' || value == undefined ? undefined : !!value;` 
will allow the undefined value to pass through. (The property value is not set if value is undefined)
