### ISSUE TITLE
How to write a Schema to describe the json Schema self of json-editor?

### ISSUE THREAD

**Issue by metled** [json-editor/json-editor#52]
I'd like to have an editor letting users design the json schema, which could be used to produce the json-editor as the project.
i.e.  the super json schema -> editor for json schema -> editor for json

**Comment by metled** [comment]
```json
{
  "title": "json schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "description": "title for json",
    },
    "type": {
      "type": "string",
      "enum": ["object", "array", ...]
      ...
    },
    "properties": {
        "type": "array"
        ...
    }
  }
}
```

is it possible?

**Comment by marc7000** [comment]
Did you see the basic json-editor demo?
https://json-editor.github.io/json-editor/

There is a schema text-area below the editor where you can edit the schema and update the editor.

**Comment by schmunk42** [comment]
@metled That should be possible and I'd really like to see an example for this. Actually the way you showed in the example looks good to me.

I googled for some existing "json-schema for json-schema", but haven't found a matching piece.

Work on this would be very appreciated.

**Comment by schmunk42** [comment]
Another starting point is feeding ie. http://json-schema.org/draft-04/schema# into the editor, which at least shows a working form... [Example](https://json-editor.github.io/json-editor/?schema=N4IglgJiBcIBYBcEAdoHo0CsDOB7AdgLTYDGcApgLYCGAdLgE4DmaED1AZgoQAwAsaUhRoBiEABoQAEiFVqMeElQYcBYmTn1mrdl14DZoiSAjlSDMMgRgCCgMKNyAAkPUnlcgmrrh8yaY4wfDBrAmwYUFcAQQZ2AE8IkAQ45HIFaljqBMlKIIBJBCpw6ABGSRCixKkGcg4FMQBfBslkXGwQsAA3cjz8QqZyBkTk1IUg/sHjXODKAFdKGB5mkFb2627eiYYAEVrqWYAbBB5E6gODgHk66ABtUGra+tZaoI6wtFWOjb7yAaHm0ABfZHRYNAC6y3alGQB3IABUUmZEuR8PMYDcQBl4sYAEa4XCw6j4YzjX6TSSo87GVGUHHkkC4HGYcgkBDGbAICz4JggCGSDlcpgxbHQUAjNKwLFZEmFSjFMWIhQCoI85bTAqVUqSWbBACOsx6suKnINTUk4oUjOZrOMyAYuFSDGsSNF4CgrotsGV3JAyxkGhow0VXs5Kt95pCsKDoxDgvDJjMJAsVhsxI9wZA3tV/j2hzZorVecssKu0YlIBpdKGOVecwW0B4knIAA8SAdZu1ugBZWto6Am8hq6jNsB1ssKSuTZYttsdrrkLvD0d9hUxkB4gnkInGIF5mAcM7YQc1mYrpIZyf/Jut9udhe9+ur8sbwnEnMHvfQA8HI9D5sAGRRJgEDgKoamuEARGeQJglCfBsA+Novh6H4/njaZAO5ECwMeWAoICV44IQz51hQrZdg/I4TmWZBqCQQY0yfJVQx9SQOEYGh8xAGoBmbeNqAgCA3nwM4NTlU58DiUtbiY2AXy3YkAXBd9gXzYAzXAI0JKk647gBc81ylbIQHVLStU0zV7nA+pfWUhNKLUjSaGbMT5Wkay8OgwjU2IpDSM2MkrxM/IzKs3DIK82CfMQtZ5wCv4KNU6jtT1A1XPHOT8VfHdcxBL9D2PEzhwABXtR1nTch4IPwl4oveEi4tQqcT1Kh1BgqnDqsi4TfNi75yNy454xqfUwBqd0wq6gi6vgwQWKFTIEmWAShLgs5WvKsAXVAIkdPRWT1yyhTw3UsEVM/dTlmmnqMoZJkWTZSQVuE9ayvarbKo8yD413PLLpaN6nQ+26rQe4xnrWg4Nve7b3PCxpzr+jTaPohh8GhoHYc9O7rUezFBJeqHAY610qpsq7BoiDTTFSfBTHwEhgfTNdQZtJ6CchjGSZ2yTpLuOHqpOgWnmuoi5sFYVpXBDSUTPbGjKmELNTKEAdTAfVDU1Adlk9Hm9pkkBZfrDEFckeTt3KJrqwrQ4DmpeYq2MVm8azXl9PlxaZUs4XPNF6KoRheFEXCNUlfE8y1Y19L+wYU0+RAdiGE427XeW85pMmkXap6wQA2oSWlqe3nrkz33s7F6JPeWAhyAzn2Ir995K+xZZ8FwNT68aCnafpxnYZnW950XEcx1uIqR7RM7DZvOduwfdFgtPBZ49+xyGiAAAA=&value=N4IglgJiBcIQhgZwYkAaEASRBjAFgKYC28MI6IALmJQDYFkTJIUQG4BOYADtQPYA7RkhRQMbAGbwArrUowBs2hiKzq3egHkJMAAwr4ADzCqiejAUM5a0xGABuBALJGT0s9Cm1EBFWAFuHvoglta2Ds7+gTBePgaGADIEAgDmlHjmIET+SanpCkoY3PCUlAQcQrAU8BAQNGCC8LQAkmVEqNDAAL4YNMQd3fGt/ZnZAsPtmdIBAI7SBBMdsb5ZRgAKHHzc5dTso/4bWztge9CKtMogHARzYNdQ0ADa5AC6GDV1/AJNh9scuwMenACBIol9AUVNn8ATBBiBiqVygJfsdTnC2NsBGwBDgThCQooPM8QG8QBI+BwSPIqu8LtoYMTSfABABPelPV4YQQEdmMjACPjU860LpAAA&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by wclssdn** [comment]
Are you looking for this? http://json.bootsphp.com/jsonSchemaCreator/

**Comment by schmunk42** [comment]
@wclssdn Wow, this looks neat!

**Comment by niebert** [comment]
You can also start from a JSON of your choice and create a JSON Schema for the JSON Editor by https://niebert.github.io/JSON2Schema . The `JSON2Schema` Tool used the JSON Editor developed by Jeremy Dorn to create the JSON Schema and finally you see the look of the JSON Editor in https://niebert.github.io/JSON2Schema . Because a JSON Schema is JSON too you might find the workflow from JSON to a JSON Schema useful.

**Comment by pmk65** [comment]
Added info to Wiki.

**Comment by IanMayo** [comment]
Hi all, I've created a new issue relating to this one #299 

The schema the original poster was referring to was the JSON Meta-Schema.  It exists, and can be used in JSON-Editor to create/edit a schema.  But, the editor has sub-optimal formatting, since the JSON Meta-Schema doesn't contain the fancy JSON-Editor specific formatting hints.
