### ISSUE TITLE
Tidy up import paths for amd build

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#522]
### General information

In #521 I created a separate amd build for use by `import`/`require` statements.

The output path is a bit horrible though, requiring the following statement:
```
import { JSONEditor } from '@json-editor/json-editor/dist/jsoneditor.amd.js
```

I'll aim to tidy this up before merging onto main branch.

**Comment by schmunk42** [comment]
What would be the plan? 

`@json-editor/json-editor` is the "namespace", rest looks also OK.

**Comment by sirockin** [comment]
Yes I think I'd just remove the `dist` bit from the path like so:
```
'@json-editor/json-editor/jsoneditor.amd.js
```
It's a really minor fix and I should have put it in the original PR - just wanted to record it here so I don't forget to do it, and so others are aware of it.

**Comment by joshuaryoung** [comment]
Still getting the ```TypeError: window.JSONEditor is not a constructor``` error. Any updates on this?

**Comment by marc7000** [comment]
@joshuaryoung:

If the JSON editor library is used via import it cannot be accessed via global window instance. 
It should work as described here: https://github.com/json-editor/json-editor/issues/782

If it is included via script tag the global window instance can be accessed, like in the interactive demo:
https://json-editor.github.io/json-editor/

**Comment by KES777** [comment]
@joshuaryoung 
In my case I did next:
```
import { JSONEditor } from '@json-editor/json-editor'
window.JSONEditor =  JSONEditor;
```

**Comment by germanbisurgi** [comment]
I believe we can close this but please fell free to reopen
