### ISSUE TITLE
Is it possible to rename object properties or to delete them ?

### ISSUE THREAD

**Issue by k2s** [json-editor/json-editor#524]
### General information

It is possible to add properties to object dynamically, but I can't find a way how to edit them or to remove them.

### Expected behavior

Clicking on property name or on some action element should make it possible to modify the property name text or to delete it from object.

### Actual behavior

I can't find editor control to do that.

### Steps to reproduce the behavior

I have created [an example](https://json-editor.github.io/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIUAGhCYAlpgA2cNCACCbNjKkUksgAQ5GpHHEbS4EbXAAeSBDnkgJmAJ6HFpAEZE4UTPZBJV6pqyAAr6hsZSpmhcWhBwEmxwMQCuspihBkYmEGgA2iBsjuTWUlAA8h5ePgC6EnqZEVGooIXFCKUVnt5ooNJyCugAIkUlUNruXT4SYIxJigDE7ElS5IHkEOwj7VAgAL67Ccur0hQ5zQVbpT2SzgMgE1W+OEjYRuQZ4dnXdABU104udAPbp1MJZSJnXqWHznAF3CCYRgrZh7fZo3ZAA==&value=N4IgJgngdghgtgSwMYHkBGArApkgLiALlAHcYpcACXAewqwCdY4srb6smtDRcsAPfARC4AFjErFqAVwA2YCmhYBzduJABfTUA===&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap3&iconlib=fontawesome5&object_layout=grid&show_errors=interaction) 

I would like to modify the property `want to ername to rename` which was added dynamically on level of `Dynamic object` properties and I made a mistake in the text.

**Comment by pmk65** [comment]
@k2s You can remove properties using JavaScript. Take a look at some of the JavaScript examples at the Playground page. https://is.gd/2MmcaA
