### ISSUE TITLE
Theme Error Message Displayed

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#528]
### General information

Using the 2.x branch I currently see the following error message for `html` and `bootstrap4` themes (I haven 't tried any others).

![image](https://user-images.githubusercontent.com/7776773/64515586-20bf4980-d2ed-11e9-9652-e052e1b9b0e8.png)

Is this by design? If so, what do we need to do to resolve it?

- json-editor version:
develop/2.x

**Comment by pmk65** [comment]
> Is this by design? 
Yes. It is something I have added to all Themes that are not updated to 2.x.

Currently the Spectre and Tailwind Themes are the only ones in 2.x format.

>If so, what do we need to do to resolve it?

Someone who is willing to do the update of the themes. I'm going to update the HTML and Barebones themes, but someone using the Bootstrap and Foundation themes will have to update those. (There haven't been any volunteers yet, but maybe after we release a 2.x beta, someone might step up. 😁 )

**Comment by pmk65** [comment]
I have updated the HTML and Barebones Themes now.

**Comment by pmk65** [comment]
@schmunk42 @sirockin To reduce overall file size, we could exclude the 1.x themes from the 2.x alpha release, but still keep them in the repo for custom builds.

IMO we should only include themes the latest framework versions (i.e. Bootstrap4 and Foundation6) and skip all the previous versions (Bootstrap2, Bootstrap3 etc.)

**Comment by sirockin** [comment]
That works for me although ultimately I'd like to try to get all the themes available - if we can get lazy-loading working as per #488.

**Comment by pmk65** [comment]
> 
> 
> That works for me although ultimately I'd like to try to get all the themes available - if we can get lazy-loading working as per #488.

True. but currently we got a lot of themes that doesn't work correctly. If we stick to supporting the latest framework versions (Unless someone creates a working theme for an older version), we have less code to maintain and we can focus on getting those themes to work correctly.

**Comment by pmk65** [comment]
@sirockin @schmunk42 @germanbisurgi @marc7000 What are your view on this. Should we include all the faulty themes in the 2.x release or just include the ones that actually works?

**Comment by germanbisurgi** [comment]
I would:
- have a barebones interface that can be extended or overwritten.
- retain the two last versions of the most used css frameworks and leave the really old versions like Bootstrap 2 and Fundation 3 out.

**Comment by schmunk42** [comment]
> Bootstrap3, Bootstrap4, Foundation3, Foundation4 and Materialize themes doesn't work correctly with either 1.4.x or 2.x

All should be fixed for 1.4.x
For 2.x we should at least fix BS 4

**Comment by sirockin** [comment]
I think I'm with @germanbisurgi. Better to keep most of the older themes for the time being and document any issues with them - perhaps keep an open issue on each faulty theme. They don't really fatten the code very much do they?

**Comment by pmk65** [comment]
> 
> 
> > Bootstrap3, Bootstrap4, Foundation3, Foundation4 and Materialize themes doesn't work correctly with either 1.4.x or 2.x
> 
> All should be fixed for 1.4.x
> For 2.x we should at least fix BS 4

By whom? There's been no interest in fixing them earlier. (I have raised this issue before.) 

I have already updated/created the Spectre, HTML & Barebone themes and is not going to do any more.

**Comment by schmunk42** [comment]
@pmk65 Can you link to the issue raised before?

If they were working in 1.3 we can't just drop them in a 1.4 stable.

@amk0 could you take a look at this?

**Comment by pmk65** [comment]
> 
> 
> I think I'm with @germanbisurgi. Better to keep most of the older themes for the time being and document any issues with them - perhaps keep an open issue on each faulty theme. They don't really fatten the code very much do they?

Again, _who_ is going to document/test all the problems in the faulty themes?

**Comment by schmunk42** [comment]
> who is going to document/test all the problems in the faulty themes?

-> @amk0

@pmk65 When did it break?

**Comment by pmk65** [comment]
> 
> 
> @pmk65 Can you link to the issue raised before?

#329 Then there's several others like #111 #277, #435 

> 
> If they were working in 1.3 we can't just drop them in a 1.4 stable.
> 

They didn't work correctly in 1.3 either (or any older versions), but no-one have been interested in fixing them.

**Comment by schmunk42** [comment]
> They didn't work correctly in 1.3 either (or any older versions), but no-one have been interested in fixing them.

Ah OK, thank you.

So keep broken versions with notice for 1.4 - and drop them for 2.x - we'll fix BS4

**Comment by pmk65** [comment]
I made a test schema to display all the various form types and options at the Playground, similar to [this](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgGU1SAnVKAFQAWqALa8AMgENEOAK7x%2BqAM7yAwhMXNK0bMi440XOksxRw26sGLrUtCADMcJszBfYHXYRLItsthxSpXbDpGZlZgSWk5KHgleSsNRQDzFzgAEyViLlpkOhwIEzhBWkUYuITeAHd1KE8MmJwoIQZkKCzUL14cLigZZDTOmKFRUvcoACk2AHkAOQBaAFE0%2Bm6oACYAOgAPKAA3VC5FWnyNqABJeUUBHErS%2BCEoCV2JWgYJPCYoZQkIAa40qCoJiiCDwUqVegCR4MBhQZaKZBvRDvT76PIQUqoCAo1BpchfGTEKE1DKKLI5dGPX5QPw4PioLbwU6CXh4OTwfKKAD0GiYpEe8nuvA5rRwdiGvHcwi%2B11uTRuDQaAHMlZ9ntlZHdhrwESRaHZaMQoGjjhiNgAePBcAB8lptMxwsSwZ3FUV6GiGJSgEPuEqgAEZtnsDkd8vjFDhRMbxUKoAagWlSsJaEqBPIII6oHhePDEVJcW1ujxSAxEBs4IEYABfLSuODfX4Sf4Vf1OSupBAoMLYfBEUjJILYAAkPDshWAAGIuRkDRB6KbuQ2%2FmkWxWUjX2%2FX4D9lxU1m2UhYkGhx72SN5a0E4CPUGOfHApzPbPPOTzt43m9Z98B2xuUnAmy4KQKgPQcaC7U9CHPAcr2AG873CR9b2fdFuUA4DrDXVw%2FzrYB0MQCptzwJIfGcWDj27OAz37YBL1w%2BDxyQ2cXwxLl8MI94SN%2FOjsHY6wiOUfRQPIiD71wKCaJ4iwGLEpiUIXNiuCAgj%2BM4kUsJcHCOz4jQiKYYTcIoyC%2BwvdtpNHRjp2QudUMU5SOI%2BZhuM3cSTJA0izOCUTwmo0zD2HCzZKs5jbN89znP%2FVzzwqJVsjSAyOyMsTfJg%2BjAsQ4L5NfMLrFi2h4p%2FdceKoiT4BiuLlGyGisDIwzvJ7UrUo7GSMqfGyFJyjQ8sTeAqu8CLcM6khOiVbpaGMDz%2FPAk9ksa2jPOvdLsDk9rstKiorFiUbsgm39Ai09JrJYkiapcpcmxXaxW0msCEHofSxLOCBkGieMGETb1IThTJslyU0qQBWl6UZQFsUctJy3mqbgF0fQDiME7TE8ixKtsJVbBe7xTv8uqZvCVGICVJrbpCB7wjYXq0ZpZ7XvG97Pt9UlyT%2B%2FIAephxgb8wdcKZ370XHCnskJ6nMbjOmAR9KFeYpf6d3ZukGSZYnYJNTkEu53x7AVxlx2KUZxZpUolSxA5OgBPBEC%2BLhiC5XEVkON8haVDYCBIqTubgbqAH1iBwBgZGEDETAANnd26MbkABBeBKbZWJEdqjWOzzYhUGud6DnHLFYh6CQyh1wqk805Hi5xqAtNuiAA%2BzIXMfVkS8ewKvhBr5XDPuyjgBmauDhF2mEwZqWfpl1m5aBxW247aWWYKMTu5b3uI%2FkN6Ja%2B6fKTHrXOchsOO1VoObqLzWOYnsS9bFgevWNiBTdic3LcUa3beWDkHebmuXbdkvcO933%2FcDxGodv4diXtHWOcgJrYyPsnN4qd04ZC4FnUEvc87v0zoXI%2BVZgFYLLhXWCtgtoHCXvXXGncCGoGNogqGRcaAd3HE9QhPQl4X3ppLb6ZI%2Bay2pOPAuu8LDr1NLrRWfdl4GzYQI0e3Ct6Kx3sAqiM8E7AIsDwrG2Bz4r0NlAa%2Bt8CwWytjbO2r9uTkMoZ%2FSeP84o%2Bz9gHA%2BWAgFl1wqAmO2Q46QKRg42CKc05%2BwQUgnOjxqaMKgGgqhSjy7YJLng3CQFCY2BpqoxOJN6pwBMegvhbhuieFUXAGJxtzHBDoWJAASj8Y2IiWGr0ZsPGebMVFQAABQMIoQcAAlPkw6HCR6z3CCU2J5SNHiOqRvKRJ9GSnEacgyhbTqFJ3kahEh%2BDpEF3COog2V8TZATvlmB%2BT9DHdGMZMg4ZiZk0OAL%2FaxACQ4RNwbvGgismwdGIYfDW01O4EyJicj2wApReHHLERkDyJDtLuqEIRAKeB52YQMteQyuGAyWVzWZwAJHdLUfciF%2FSxEws6TUzeoylafNuvvRRHjlEIt1gIL0Gj1k302bonZBiX77MdmjY56SLDnP%2FrYgMax2Wa0xmAlxECSXQIsF4%2BB6DwjZxQfnfqpLwkeJwRrKJHY8A4D9h0CARISAAGs1VbAWUeZJwA1Uap%2BMCn52TLBCGIHqnABrCXkUKeEAAQuqpgPw2g2rtTsKFWKqk4uGfC%2FFwKUXjjdWa6A2rbX6sxQPQZga4Xy23qG28EgZAMFUb1GQqB0lzIXIakB5Kz6Uv1pfI2GyzbbP0c%2Fe23Jo0%2BrZWEz2li%2F42MAdc5VtzgC8mgs8r5SV8aU0JsC0mnc2BAnPHG1h2LmZBuTafPNyLYX5AFpO%2Fkfr42zs4ZI4N2sCVLqxAHEwABtZtwBrp8rgN%2BK9wAADMGkNYAF0l3EsLRYI9wgvZjsRme%2BVFgABitBDiIugewEg%2BQCp8osMUf4j6k4vvPSoilVK1kVtpVWvRj9GV1p5Oupkrt8kctbRc7lwdO3cxVRYICyxHD9qSY3LcTsLWZN%2BWJGjxxR3OuwCU2j07KlD0TbuhdvC5HLqE6iuAvHjj8cHuwudSbkOOtwp%2B0956im4iI9gAA4jwLEWm4Auv9k5DxiGPH5rVvRr5SmVmloqZo7RdL741r2Q7DjOAm3ypbflKxXKO2Ksid24QGa6C9uqu405g7eJKSkCxjwbH8b4eBTIOcABHHNFwRCI2zbmsTY7xwAFkQslHw7JhNCnhN1LmHGVj8AsBhdA18sNYkiuZpK3yeQm6Z0Boq9APF%2B7TjVctfVpLymQGxGECKo%2BrzxzvIM8AVTPg%2F2iuwGq96WnlHbgYIaDb2BFCeBhFYZAXF5VPuwa%2BhR77j77pQ2W%2BmNKdHOew7WoxXJgttYa55sDZySN%2BauQFm5Jc4DvdC%2Fhht%2BrC0zbEvhOLWTxzg%2FtcltLGWJvZa4Dmpd%2BWWvFYa2V7dXTakIqgEN2rWAEcOqXc18IrXQcdbxz1ndfWRkDeJzV%2BLdWvW6oh2NzbWWrtQ6HcxnnHZFtYGW6KuAa2oNhM2xIbbxBdv1gOwwI7J3oFncVRd%2BZVnw7Fts6h8tWjK1bKw7splDsQftfPF96bP2fNtsuT4cjAOu1A5NeyVdOuOyWvHHHDks9MfccMx7gPYmqfYBdSHuTKLCf4tkeZ3Al2veOL12ouz1L0OPerc91z3I%2FcnEI8L4j9vSP%2BaLkqyjnkK%2FVmKj298u4vz10WreSybVjpvh3BdVcjraGgsevEip4J8cz3xHUuWvthDIAkPyLEOIIbKzgLDAwCMFlMbRk8qBSK33J47BPqf4WcsUcHFRpuPda5yEh4n7Xm%2FTl7%2Bn1m9H6AXeUe7ak8%2FCSxPb5v0iu%2FB%2FH9H6CBPxyVKTiTrh3ws25USS%2BV%2FwfxzQAOwm7X%2BW3AhQ3wiy3yT2%2FxeUsEjH31gKf3L0Czd1NQ9S1W9W50wJVgwLQNvxwPvxMEP2f2P27Qa0vy%2F2oJ%2F1oL%2FzgMYMAO7Xc1YKoKgNuhgPoP%2Fx4IQLd0txYPAKvwLR3wsBEJ8AYIIMBzLmBxxzBzIMRxkLYKENgkUKwGUKTmr14KIJDwEOv3YKwIMJiDEJUOVSrwGm0hixUg0CbxBTJmwEjhcIXxhj0GX3Gim1unwnjg%2FwTyiwAh8OF1708LgBUD9n2VTTsHTUzTUy82AA02l3SN01QH0yLwj2M3g0HDM1OXoD53kK8kYzryF3gNLmPycIsB0lQAEncKx3CG8OUjk2GxiE4l8JamWkylWlYiaN8KX3hkCNXzwhcNCMvx9zEhaIwXqP8hMLwUiPslUmInUisxiM7g6KkC6NJx6OIjmC2PdmbwQgGLb1shGJ7z8LhkMAmK9zWKkBmJkLmPCAEhOKEkWMAMcKKhciaL0m7CgJ2PHD2MtjYW6KBL6KWgfEGPbxuLOLuICLcT0OeMQFeIoNwneOCBxCKLqN%2BP%2BMiiGlaKD2ACmDmiRLGIeNRLd18kxKsIbk7hSmiI8M7gpJMigCXy%2FgT2pJXwqLuWUGuixIHWNTmx%2BNd3SNCO%2FBFIY07hCXxKYPPVCIfQqKNSqLf0VMJPsMr2WIaIajclyjincP6LhKuI6nWkwluLaOwA5KnUqFOG6O6lGP8PGNpLUKilIAZL0IsBxO8wKkiT%2BIkOJMtK6gqkpnCxBLZPHDtP5AdLZyySwG6jmFRkkgWjglhMnHhNClDM0HTL5MeJFJKhMm9LEz9LtzSBTIjLlQcL1KJMGlzM2goTGndJJjJNjPkHjO6KbO2keKpNdJpKCJVlKlLPCONRZKXXLJ7JbJ5NOV0PPXhBxF8zeGO27By1vUXMci9kMS9ldk90MMfw3JKCXILLcXXPPRsKMMlNOVPKHOsK8GFMZKwIiM9Ma0izJLUC2m6EtkvRlx7EEL%2FP4WPK3L%2FhXLcKUMPMAuwE3KYG3Jfl3IjFRXPP%2FSnmAtgtvNEIxygrgEvLsNFRP1ugwrVI7HFNlKRRfPFKgpMJ1PL1vU2hlKfNFKqInL%2FNBLEk%2FObK4EthvVYtkMszItuhgtQGXIkFXMwtyxQqAsUCXJ3L3KQsgskugrQuEqIoPO4JWwIs8QHP5IEtggVOItIXHH0qor%2FOopfwvK8FVN0vVOZMpN4ptLiJGm%2FKgFVOgx0G0sLMYqwM1IMsSmNR8pMpQrMqWJou1LCurH2kgCrGACAA%3D&value=ETI%3D&code=EQehHcEsDsBMHtwDoBSBlA8gOQKK0gC7wBOSsApgGYCGArgDYEDOSBAFuQLbktMAO5AMYFi5JH2LwiBAJ4Ck8PgUjxoLfE2oAjeuQD67LvuIMeAAgC8ZkbXIBuADrQnTsGYAqHM5Xj16iGABzM3oYc2pRM05qOGoiYhkzGNgzUWoEaHoZJDMATXhaM0EYpNgUwVomIk4i%2BAokrXgAN3IkuDMtcn9kJ0hKMwAKACsmcnx4sxgqmMFyeH6oOERUTFxxkgBKMxGxwhIyHhF4GQGNx2gd9eJLM2hycDNFhGR0bDw94gGECu5oAiQAI62BJoLpCeIDBzAADEI1UAFpdvF4T5iJwoRsADTbMZxahnFzQJoRVLkdIyAASyV01yslFo0GEKmgpzMAG9CWYuWZidcUlZvrRfgRsVpaAQiNA9GxfBRadtRlckJIpKwONwkIFyAQKWS5QAhcWSimy8ifAnOaDcnkkwRpAjkQ0S1Q3emM5SqAYOgAeIqK1D8WmoggA1lsOVbrTbrmLnVarJcPsr4KqtQQnZKveRfdiAOS57E%2BggWqMdI2qJBVGS6JDRb0AdUgsHYN1zAHZRJxc%2BdS7HJdLTaRqHwBHAAMJsSD0WADPuqEtRudSmXTs2V2Q1jR8ejURJWXOUXTe7tOXvl6BIdKwHAtP4AGUgVXId0%2BucEoVDBf9geDIexNHoUYF2tRN4mTVUOHSNc%2BAiZ8CCwOoxCmM10yoEhyFnc8B1XYhsVA%2FYVX%2BSC5SQO5fTQSAdCCYCzAAXx7bleSKe1yFBXRhFdBkmU9RQPTUbFih%2FUNw1PKMmNGegbnw0hCLVIxNW1NjwQASWgPhxQGaAGHof8AyAhjrQkpB32oJgmAfKpLzKAZcwk8F4SYLtMVzWB4RgUI7gLXNOGIeEACYv28mR4QARlzGiuSMqsazrRtmzYVsOy4E9IxAxUk1kwwNVGAglOEDAlGZJgBgk7EMC0IZwSQYl6FsYreKKrEzHKyrhCQENyBkerCtUJgNgiswjKvG84Ish0XxswQ2BiLUv0E%2Bgg1DXTAPIAal2wkjh1HWAJynGcJIG6TwKIvVoNgv4EIoJBkOIVDUQw9aVzlPD0rA2TiLXMjcsojzAho%2BjRK5JjRDtMkHXeCY6S4vjWQjUs%2BkGaTJjUAgZjmBYYGeFY3iuLYjooKpJBOQ7XpIG47geJ5lleNYPi%2BeAfjgwFgRkPKIShWEmARJESBREh0WAJrKtgPESZ50hPVzNJYBkL83W4lkRNSqNpcpakzVOAzuVo%2F6tcB5iwdYsFhAGOGo1zVT1IIQbIAAL3IXMAC5bm0zF9a5XMELRAMnbMXNoH5n23eVj20GiPxfds8P6ALd2%2FbvCJZud3Md2IWb9do%2F9oeZAZVvZOOEdz1hE%2B1aqA1sLYqZeVYIf2CgaAYZg5O4XgBGEURxEkaQ5DEBreuutTxT0Jg7daKwxFRtPS5q2wta5EGWNr80tZ1859dBuJHXPGyE86ST9VlOXs89POzetKvsdpsD67oRgWCynhKzbkQxAkKQpB7hQerUJAdz3vRGjThuAAQgvjTJeBwG532bo%2Ffg4IO5v27vIPuP8%2F5dAAbKOepIN7gyuJrDOFp14sQzJLAAgqEQIVoD7Oict4Y%2BLJT5xzATXJUN9G733VLA5%2BCCu4f2Qd%2FFgAZICUIwTQkBzCcZJjYdAh%2Brd4Gv14bIfhfFBEUKlI0GhWCF6GyXvg5Wq99ZEMNiQlkuYWrgjMAfYgcoj7uhzowkOjxMbUxYVIqgt8m6yKfvIzu78lG9wEQoCq4IMHWLNOI5x1dJHX3cewmBcj24KL8Z%2FFBLB4DBOEKEuUWihCLzwf9GiRjN4mJsuYjiqkKB%2FFsQrXOStSwSKvnXWJMjOEJJfr4pBASVFBNagQPQmM4IRKWFExppBpGeNad4xJHS%2BFdKKj0kJAy%2Fg5JweQXRBS9bK1WSU3M7htC6EsSQGxWc7EnzqVGBpEDxkcKMG0nhyTlHzNRjofQjQwnylAZEy%2BVzmkTNuVM9piDZlf26c83QWSzQrLyXTDZhitnEO3rs%2FZrQABa5AtDEFMhuB2JyakOPqV88BrDfk3JbgC%2B5nSQVPORXoe2GKsXVjHmYT5wzvnEqgX8slcDplAv8VS%2FuYL9B0sxdFewcdtGb3WSvBcnIzBOABpaI6ktVbVJhkrNwpJyRUjgDSPRq9gBAA%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1), which helps find the bugs/problems. Switching between the various Themes, will give a quick indication of the differences,

There's also some test cases for Select2, Selectize etc.

**Comment by pmk65** [comment]
> 
> So keep broken versions with notice for 1.4 - and drop them for 2.x - we'll fix BS4

I would recommend building a new BS4 Theme from scratch or base it on the BS2 theme. As the current BS4 theme is very buggy.

**Comment by kunalraj89** [comment]
Can we not hide This Error Message in Old version?
