### ISSUE TITLE
Release 2.0-alpha-1

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#535]
Need to check the build process and files uploaded to npm

CC: @sirockin Any feedback from your side about this? 
Usually @marc7000 did the releases, but he might be unavailable until next week.

**Comment by sirockin** [comment]
Yes - I've just been playing about doing a private publish. I noticed that there is no "files" property in package.json which means everything in the repo will get published. Did it used to be there or is it intentionally left out?

I would be inclined to add:
```
"files":"dist"
```

**Comment by pmk65** [comment]
Currently the only Themes updated to 2.x format are: Spectre, Tailwind, Barebone and HTML
The others 1.x themes should be removed from the alpha build.

**Comment by pmk65** [comment]
**Bump**

**Comment by marc7000** [comment]
Done, but Travis CI build failed...
https://github.com/json-editor/json-editor/pull/565

**Comment by pmk65** [comment]
For the next release we should remove these from `core.js`:

- IE9 Polyfill (If people want to use it wit older browsers, they can get a polyfill from https://polyfill.io/v3/ or similar)
- jQuery wrapper. (If someone needs this, they can create their own. Library works with jQuery without it)
- References to the old obsolete plugin system.
- Themes not in 2.x format. Maybe keep the latest 1.x themes like Bootstrap4 etc. (We can just comment out the import lines for now and keep the old themes in src.)

**Comment by pmk65** [comment]
@schmunk42 If I create a PR with 1-3, should I just comment out the inclusion of IE9 Polyfill and jQuery wrapper and keep the files in src? Or remove them completely?
