### ISSUE TITLE
ipv4 format breaks editor when used in 'allOf' inheritance hierarchy

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#536]
### General information

When a schema uses `allOf` to inherit from a parent definition, and the parent contains a property with `type:"string"` and `format:"ipv4"`, the editor does not not display, and the browser console shows the following error:
```
Uncaught TypeError: Cannot read property 'ipAddress' of undefined
```

Commenting out the resolver assignment code for the ip editor (`defaults.js` lines 529-531) gets rid of the error (as well as the double error message from #534).

- json-editor version: develop/2.x

### Steps to reproduce the behavior

1. Create a new html page string-formats2.html in the tests folder (see below)
1. Run npm run debug
1. Navigate to http://localhost:8080/tests/pages/string-formats2.html

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>wysiwyg-sceditor</title>

  <!-- json editor -->
  <script src="../../dist/jsoneditor.js"></script>

  <!-- jquery -->
  <script src="./../../node_modules/jquery/dist/jquery.min.js"></script>

</head>
<body>

<textarea class="debug" cols="30" rows="10"></textarea>
<button class='get-value'>Get Value</button>
<div class='container'></div>

<script>
  var container = document.querySelector('.container');
  var debug = document.querySelector('.debug');
  var schema ={
    "definitions": {
        "parent": {
            "properties": {
                "ipAddress": {
                    "title": "IP Address",
                    "type": "string",
                    "format": "ipv4"
                }
            },
            "required": [
                "ipAddress"
            ]
        },
    },
    "type": "object",
    "allOf": [
        {
            "$ref": "#/definitions/parent"
        }
    ]
};
  
  var editor = new JSONEditor(container, {
    schema: schema
  });

  document.querySelector('.get-value').addEventListener('click', function () {
    debug.value = JSON.stringify(editor.getValue());
  });

</script>

</body>
</html>

```

**Comment by sirockin** [comment]
Whether we keep the ip editor or not (see #534) I'd like to understand what is causing this bug as it may be due to a lifecycle issue that I've contributed to in my earlier work on #430.

Also if we do decide to implement lazy loading and other asynchronous features, we (I at least) need a better understanding of the lifecycle for complex schemas.

**Comment by pmk65** [comment]
Your implementation adds a new validator, where mine uses the existing pattern validation by injecting a custom pattern into the validator from the editor.

**Comment by sirockin** [comment]
Ummm okay. But it's not my implementation breaking the editor (unless it's something I messed up while doing the webpack transfer).

**Comment by sirockin** [comment]
It may be useful for us to have a real-time chat about this. Would that work for you?

**Comment by pmk65** [comment]
I tried sending you an invite on Skype.

**Comment by sirockin** [comment]
Hmm it hasn't popped up for me but I was on do not disturb. Wanna try again?

**Comment by pmk65** [comment]
@sirockin try this: https://join.skype.com/invite/g22WWMEGWMJq

**Comment by pmk65** [comment]
@sirockin Can we close this?
