### ISSUE TITLE
is angular(typescript) version available ?

### ISSUE THREAD

**Issue by Rajkapoor1** [json-editor/json-editor#543]
Hi,
Thanks for sharing json-editor, I'm new in angular. This is the same I was looking for but this is in angular js, is there angular (typescript) version available of json-editor which provide similar functionality. or can someone suggest how to use this library in typescript/angular 6 projects?

Thanks in advance.

**Comment by schmunk42** [comment]
CC: @amk0

**Comment by sirockin** [comment]
Hi @Rajkapoor1 .

There isn't currently an angular wrapper (although I will be releasing one shortly) but it's very easy to create one. Look at #127.
