### ISSUE TITLE
How to get Select without multi select??

### ISSUE THREAD

**Issue by JorgeSivil** [json-editor/json-editor#545]
### General information

- json-editor version:
  "version": "0.7.28",

I've been trying for some time to get a Select dropdown with a list of values, but I keep getting multi-select dropdown or checkboxes.
I don't want this behavior... but couldn't find a way to disable it.

How can I do that?

**Comment by pmk65** [comment]
Try a newer version of JSON-Editor and see if that fixes your problem.
