### ISSUE TITLE
Update coding standards and decide which should be enforced by Eslint

### ISSUE THREAD

**Issue by sirockin** [json-editor/json-editor#546]
When I created the Webpack build, I transferred the linting mechanism from jshint to Eslint carrying over as best as I could the jshint rules from the old build. It wasn't clear to me whether or not the jshint rules had been enforced by the build (ie the build fails if a rule is broken) so I left the linting as advisory.

Can we discuss and agree which (if any) rules we want to enforce, which we want to appear as a warning, and whether we want to mention and justify these in `CONRIBUTING.md`?

I can then updated the Eslint rules as agreed.

**Comment by pmk65** [comment]
> 
>     1. Coding standards are IMO primarily about readability and that is helped by making code have a similar structure throughout - what rules are actually enforced are secondary to the fact that there ares some rules. It's like listening to someone speak - we can quickly get used to someone speaking with an unusual accent, but if they change their accent every few words, it's confusing. So my preference may not be yours but the most important thing is that we choose some rules and aim to stick to them.

True. But as there currently is no rules, we will have to refactor the entire codebase to match any rules we setup. 

> 
>     3. The main issues I have with single line `if` statements are readability:
>        
>        1. The action appears at the end of the line and is more likely to overflow the screen - so it makes it harder to see what the effect of the statement is

You can break IF statements with multiple comparisons at the dividers. (Same goes for ternary operators)
````javascript
if (a == 1 && b == 2 && c == 3 || d == 4) {

}
````
into
````javascript
if (a == 1 &&
    b == 2 &&
    c == 3 ||
    d == 4) {
}
````

>        2. If (as is often done) there are no braces to contain the action, the delimiter between the
>           condition and the action is a bracket - and there may be several of these on a line - this makes the distinction between the two parts of the statement less clear. (for this reason I would prefer all if and for statements to have their body surrounded by braces even if on a single line)

This will also increase the size of the library (At least the non-minified version.)

>     5. Ternary operators usually (IMO should) be fairly terse, and so even if placed on a single line, it will occupy less than the 80 characters often recommended for maximum line length

You can break those into multi lines as I explained before.

**Comment by germanbisurgi** [comment]
i recommend https://standardjs.com/ for eslint

**Comment by schmunk42** [comment]
I just wanted to post the same thing :) so let's go ahead with this, unless @sirockin vetoes.

**Comment by sirockin** [comment]
> I just wanted to post the same thing :) so let's go ahead with this, unless @sirockin vetoes.
I love standards which are already agreed and I hate wheel-reinventing so that's a +1 from me.

@pmk65 I was just answering your question and giving my reasons for what I had already said was a personal subjective view. It's certainly not a hill I would choose to die on :-D All I would say is I believe size of non-minified build is not something which should influence any coding standard.

So people, I'm happy to set this up in eslint but one remaining question - do you want these to be warnings or errors - IE should a rule failure break the build? (Bear in mind you can add exception comments where necessary).

**Comment by pmk65** [comment]
If we want to enforce the rules, it should break the build. Just like the e2e tests do.

**Comment by germanbisurgi** [comment]
yes, it should break the build

**Comment by sirockin** [comment]
I just ran eslint on the contents of `src` with the standardjs rules enforced. It returned 11875 errors.

Running eslint with --fix (automatically fixes errors where possible) still leaves 462 errors (see attached file). 
[eslint_out3.txt](https://github.com/json-editor/json-editor/files/3621660/eslint_out3.txt)

How would you like to proceed? I'd recommend busting some of those rules down to warnings, at least for the time being.

**Comment by schmunk42** [comment]
@sirockin @pmk65 I merged the open PRs and created a PR for the changes on master to develop/2.x here #549 

After that I'd do the `--fix` for develop/2.x (actually I'd be happy if @sirockin can take care of this :smiley: ) - after that it's very likely that we won't be able to (forward)-port changes from master. But that's OK IMHO. I'd even make (merge) `develop/2.x` the new master and create a branch of the current `master` named `release/1.x`.

**Comment by sirockin** [comment]
Hi @schmunk42 I'm happy to submit a PR with as requested but we'll still end up with quite a few broken rules (see eslint_out3.txt) above so I'll fix what I can and bust rules down to warnings on others such as `camelcase`.

**Comment by schmunk42** [comment]
I think having one round of (auto)fix is fine. Let's how the rest works out then.

We tried this before a few months ago, but it failed with some `ie9.js` AFAIR - but I think this file is gone now.

**Comment by sirockin** [comment]
Fair enough - I'll wait for #549 to merge then get to work on it.

**Comment by pmk65** [comment]
Something like this might be useful for getting the last errors fixed (Looks like a lot of them is camelcase errors) and do more advanced refactoring.
https://github.com/facebook/jscodeshift
https://padraig.io/automate-refactoring-jscodeshift/

**Comment by schmunk42** [comment]
> Fair enough - I'll wait for #549 to merge then get to work on it.

Checks have passed, one of you need to merge it...

**Comment by pmk65** [comment]
@sirockin @schmunk42 Is Bitwise operators then discouraged?
As I want to update the typecasting functions so they return correct values. 

Example:
````javascript
// Will return undefined if val is undefined or "undefined"
var booleanTypecast = function(val) {
  return String(val) === 'undefined' ? undefined : Boolean(val);
}

// Will return 0 if invalid or infinite number
var numberTypecast = function(val) {
  return isFinite(val) && Number(val) || 0;
}

// Will return 0 if invalid or infinite number
var integerTypecast = function(val) {
  return Math.floor(isFinite(val) && Number(val) || 0);
}

// Will return 0 if invalid or infinite number (Same as "integerTypecast" but with Bitwise Operator)
var integerTypecastAlt = function(val) {
  return (isFinite(val) && Number(val) || 0) >> 0;
}
````
I have used the JavaScript typecast functions combined with logical AND/OR when possible, 
But in the `integerTypecastAlt ` example, I use `Bitwise Shift Right` to trim off decimals. Is something like this "too complex" to understand?

**Comment by schmunk42** [comment]
>  Is something like this "too complex" to understand?

With comments it's fine.
