### ISSUE TITLE
Color picker with alpha

### ISSUE THREAD

**Issue by drmrbrewer** [json-editor/json-editor#55]
First of all, json-editor is a dream come true... thanks!

With my particular use-case (Android app, but with non-Android contexts too), colour strings are in the form `#aarrggbb` rather than `#rrggbb`. where `aa` is the hex alpha (transparency) value.

Does json-editor allow for this?  Something like the following (with a colour picker, including alpha, popping up in [this context](http://jeremydorn.com/json-editor/)):

    "favorite_color": {
      "type": "string",
      "format": "color",
      "title": "favorite color",
      "default": "#aaffa500"
    },

**Comment by loganvolkers** [comment]
This wouldn't be something that would be supported in the core project, but could easily be done thanks to the existing support for custom editors and custom plugins.

For an example of how you could build a custom color picker, check out the ratings editor here: https://github.com/json-editor/json-editor/blob/master/src/editors/rating.js
