### ISSUE TITLE
Tabs header value overlapped when header info too long

### ISSUE THREAD

**Issue by michellegx11** [json-editor/json-editor#552]
### General information

- json-editor version: 1.4.0-beta.0

### Expected behavior
Tab width changes dynamically based on the text length.

### Actual behavior
The tab columns size seems to be fixed. When the headerTemplate is set with very long text, the value is overwritten with each other
![issue](https://user-images.githubusercontent.com/55752347/65522246-c6c4a380-deea-11e9-95f7-8e0cc84f7a0a.png)

### Steps to reproduce the behavior
{
  "schema": {
    "uniqueItems": "true",
    "format": "tabs",
    "type": "array",
    "minItems": 1,
    "maxItems": 1,
    "title": "Title",
    "items": {
      "type": "object",
      "title": "Item",
      "id": "item",
      "headerTemplate": "{{self.name}}",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "title": "name",
          "readOnly": "True"
        },
      ....
     }
   }
 }
}

**Comment by pmk65** [comment]
@michellegx11 The example schema you posted is not valid.
But try using a [Template Engine](https://github.com/json-editor/json-editor#templates) to crop down the title or use [CSS to turn ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/).

**Comment by michellegx11** [comment]
Thanks, I will try updating the CSS then.
