### ISSUE TITLE
Select2 lose focus after change when using with enumSource

### ISSUE THREAD

**Issue by zazasa** [json-editor/json-editor#553]
It can be reproduced in the playground in the select2 example. 
If you tab through all the dropdowns until the "font" one, then select an element, the input will lose the focus and the tab restart from the beginning.

I found that a workaround replacing the `this.onChange()` at this point: https://github.com/json-editor/json-editor/blob/b13aa7b0b5d191ab96ef652182a9698388abf6fd/src/editors/select.js#L215
with :
```
this.notify();
this.change();
```
because the problem is caused by the `onWatchedFieldChange` function here:
https://github.com/json-editor/json-editor/blob/b13aa7b0b5d191ab96ef652182a9698388abf6fd/src/editors/select.js#L253

**Comment by pmk65** [comment]
@zazasa I can't reproduce the problem on the Playground using the new 2.x version. So I guess that have been fixed during my refactoring of the editors.
