### ISSUE TITLE
Dependencies fails for boolean value

### ISSUE THREAD

**Issue by websemantics** [json-editor/json-editor#554]
### General information

- json-editor version: @json-editor/json-editor@1.4.0-beta.0

### Expected behavior

From the example provided below, the `notification.body` ought to hide (display:none) when `config.hide` = true

### Actual behavior

It does not

### Steps to reproduce the behavior

Direct link to example: https://jsfiddle.net/websemantics/ocmjfub8/

```json
{
  "type": "object",
  "title": "Notification",
  "properties": {
    "body": {
      "title": "Body",
      "type": "object",
      "properties": {
        "title": {
          "title": "Title",
          "type": "string"
        },
        "content": {
          "title": "Content",
          "type": "string"
        }
      },
      "options": {
        "dependencies": {
          "config.hide": true
        }
      }
    },
    "config": {
      "type": "object",
      "title": "Config",
      "properties": {
        "hide": {
          "title": "Hide",
          "type": "boolean",
          "format": "checkbox"
        }
      }
    }
  }
}
```

### Solution

In `./src/editor.js` [Line 135](https://github.com/json-editor/json-editor/blob/71968e2c087526b33013e260473b4a79e4f6d059/src/editor.js#L135) should check if the `value` has `length` property before `value.length > 0`. This worked for me,

```javascript
this.dependenciesFulfilled = value && (value.length !== undefined ? value.length > 0 : true);
```

Finally, huge thank you for maintaining this project. Also, it's awesome that you've kept it dependency free.

**Comment by websemantics** [comment]
Quick note, in the [jsfiddle link](https://jsfiddle.net/websemantics/ocmjfub8/), if you change the deoendency condition to `false` it works, thought this might help.

```
            options: {
              dependencies: {
                'config.hide': false
              }
            }
```

**Comment by pmk65** [comment]
@websemantics This have been fixed in the `develop/2.x` branch See #384

**Comment by websemantics** [comment]
That's great, and thanks for your response.
