### ISSUE TITLE
Choices.js Demo is broken

### ISSUE THREAD

**Issue by stroebjo** [json-editor/json-editor#556]
### General information

- json-editor version:1.4.0-beta.0
- Choices.js version: v7.0.0

### Expected behavior

Integration should work.

### Actual behavior

Browser native `<select>` is shown. 

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/choices.html

**Comment by pmk65** [comment]
@stroebjo Try the develop/2.x branch and see if that version works better. (Note: It might work differently that the 1.4 implementation.)

@schmunk42 I have modified the Choices.js editor in the develop/2.x branch, but might have broken some of the functionality from the 1.4 implementation. I have asked @itsoli to take a look at it, but he never responded.

**Comment by pmk65** [comment]
@schmunk42 I'll update the demos once the 2.x version have been published to npm. (The demos all use the library from jsdelivr so that one have to be updated first.)
