### ISSUE TITLE
JSON Schema Editor - anyOf - Adding Title to another field?

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#558]
### General information

I have an array of anyOf, which I've added a title to make the drop down look nice / have info.  But I want this information to be sent to the output in a property... and I'm also hoping that when I load the same output into the editor later, it selects the proper item in the drop down.
I tried every combination of watch values I could think of (array is called items...  I tried items, items.title, title....  I can use this for all properties... but not on the object level attributes.

            "type": {
              "template": "{{thetitle}}",
              "watch": {
                "thetitle": "items.title"
              },
              "type": "string"
            }

Is there an ability to access the object level attributes (in this case, title) for a template?  

(sorry, this isn't really an issue.  this seemed like the best place to ask the question.)

**Comment by pmk65** [comment]
In the `develop/2.x` branch you can use JavaScript callback functions for `templates`.
The JavaScript callback function has full access to the current editor, so you can use that to access other fields/properties you don't have access to when using the regular templating.

**Comment by Lilwolf** [comment]
Will this work in selecting the proper object when passing in an existing json object?  
In other systems (non-js/schema... but similar) I've used, there was a key you could define i key that helped with the mapping when more then one was valid.   I'm trying not to make a super set of all definitions of each object...  But currently I'm always getting the first object defined in the anyof.  I hoped the watch would handle it.  But this seems to be going in one direction.

Thanks for your input!

**Comment by pmk65** [comment]
> 
> 
> Will this work in selecting the proper object when passing in an existing json object?

It should, if the value from the json object is stored in the same field.

> In other systems (non-js/schema... but similar) I've used, there was a key you could define i key that helped with the mapping when more then one was valid. I'm trying not to make a super set of all definitions of each object... But currently I'm always getting the first object defined in the anyof. I hoped the watch would handle it. But this seems to be going in one direction.
> 

I rarely use oneOf, anyOf or allOf myself, so I can't help you with that part.
