### ISSUE TITLE
show_opt_in: true is ignored after click on Object Properties 

### ISSUE THREAD

**Issue by dibericky** [json-editor/json-editor#561]
### General information

- json-editor version: 1.4.0-beta.0

### Expected behavior
When show_opt_in is enabled, property not required that are not checked are shown as disable.
If I click on Object Properties, not checked properties are keeped as disabled.

### Actual behavior
When show_opt_in is enabled, property not required that are not checked are shown as disable.
If I click on Object Properties, not checked properties are rendered as "enabled", although they are not checked
### Steps to reproduce the behavior
Fields "a" and "b" are not checked and they are correctly rendered as disabled input.
Click on "Object Properties" and do not change anything. Click outside the popup in order to close the Object Properties menu. Now the fields "a" and "b" are rendered as enabled input, although they are unchecked.

Direct link to example: https://codesandbox.io/embed/static-4rul6

```javascript
      const schemaToRender = {
        type: "object",
        properties: {
          a: {
            type: "string"
          },
          b: {
            type: "string"
          }
        },
        required: []
      };
      var editor = new JSONEditor(element, {
        schema: schemaToRender,
        form_name_root: "",
        show_opt_in: true,
        theme: "bootstrap4"
      });
```

**Comment by dibericky** [comment]
@pmk65 I think that could be connected to that bug, but the one I reported happens when you click on Object Properties, the one you linked doesn't seems to refer to it.

**Comment by germanbisurgi** [comment]
hi dibericky. this happens with json-editor@1.4.0-beta.0. With the master branch works perfectly and also with 2.0.0-alpha.0.

**Comment by germanbisurgi** [comment]
@ pmk65 do we still develop/apply patches to 1.x.x?

**Comment by pmk65** [comment]
> 
> 
> @pmk65 do we still develop/apply patches to 1.x.x?

I only work on the 2.x.x version.

**Comment by pmk65** [comment]
@germanbisurgi can we close this if 2.x.x fixes the problem?

**Comment by germanbisurgi** [comment]
this works in 2.x.x. For me it can be closed
