### ISSUE TITLE
`options.infoText` doesn't work when using Bootstrap 3 or 4 themes

### ISSUE THREAD

**Issue by skewty** [json-editor/json-editor#568]
### General information

- json-editor version: not sure as "json-editor.github.io/json-editor" doesn't seem to let me choose or show me the version it is using

### Expected behavior
(i) with the infoText is displayed

### Actual behavior

no (i) with infoText is display

### Steps to reproduce the behavior

Direct link to example: [link](https://json-editor.github.io/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYA7PhqIkAYhAAaEJgCWmADZw0IALKk2AVyUACAMIUus5lJkBPHMvSkARkThRMpnI1KXGcuBDSgoFcg5yFN6ooJgWViBIjJxmpnKKkQbkAY6yFDoKshBO0vKIIaBgjHBcKmLspbLk8unkEPjJqUHkAKLkmIxxAL690iUAjpqyJWxoANogfimBdd4AutJsVTUthSBNsxTtnXGhMvJKKptpFM6u7p7r0811APrhlj7mT+g5jNUm0nDkmggTIAAynAPkgFCcWqYAApIKAAazgmD0SBwmE0JQhdRA8260huW3Id3ISAQVjCERU70+pgQ1QAMj9mJgYGgAIy4kA4TQ2LIQGAPNyyKDPR6RKnkEwciDc6AfGxwAU4IUiilvTrUjl+Ep3d5wEl3BF7cmvEDiyV40gIO44JhOfaiynqiU0+mM5ls6RuNbPZaWcjLchQWReZ7406Eh3oYGg8H+AkgDnVLikAAqcAAHnaQK10yScEpUDoADpTS0AJhLOgyAHVqmxSAB3CA6fNITDJxgICCSYsgSoAN3w2DMAFVAQAhPiVjJQ0gQWTplsKNsdrsJjnIKB3JBsDhedaR01Or4gWnkBkS92oVkAVk9qLmPrgfoDQZD+zDLQeqpAMPhiORVF0TgTEzkTchkzTTMVBzPMCx0VlWVQMsy1QABmNDUAAFiw1AbxvVAADZCPXDlBmGUYAU/e4HQtGZwyJEllBxXogA=&value=N4Igxg9gdlCmYBcCW0DOIBcBtUkb2WgH0EBPAB1kxAGVYAnJAQwBsBhaORFKEAGnCcCPIlCYBbKhhAATAGZNU8pvxDkArgCMWSVAAsSEckjDVVqLajCNNsQ8dPTVkendQJXEogGtYpMwKQ4kTkEPQIZgC+ALqRQA&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=foundation3&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by pmk65** [comment]
No one have volunteered to update the Bootstrap themes, so currently the the 1.x themes are included.
Currently the only themes in 2.x format are the Spectre, Tailwind, HTML & Barebone themes.

Old themes will displays the text "This is an old JSON-Editor 1.x Theme and might not display elements correctly when used with the 2.x version" at the bottom of the form. See #450 and #439

**Comment by skewty** [comment]
and see #573

**Comment by odurbalau** [comment]
@skewty I will look into this as per our internal sprint task COM-369 as soon as I am able.

**Comment by pmk65** [comment]
I'm closing this as @stroebjo have updated the Bootstrap4 theme to 2.x format. See #588
