### ISSUE TITLE
Type definition file available?

### ISSUE THREAD

**Issue by shibasish** [json-editor/json-editor#569]
I am using Angular 8. Is the type definition file available for this lib?

Thanks.

**Comment by pmk65** [comment]
No, but you are welcome to create one and submit a PR. 😃

**Comment by schmunk42** [comment]
CC: @amk0

**Comment by shibasish** [comment]
> No, but you are welcome to create one and submit a PR.

I would love to do that. TBH, I am new to this TS and Angular world. Any suggestions on getting started? Googling is kind of making me confused about how to get started. Thanks.

BTW @schmunk42 great lib.
