### ISSUE TITLE
Error after update to version 2.0.0-alpha.0

### ISSUE THREAD

**Issue by victoroliveira** [json-editor/json-editor#570]
### General information
After update from version 1.4 to version 2.0.0, the error `Uncaught TypeError: Cannot set property 'disable_properties' of undefined` is shown during the initialization.

- json-editor version: 2.0.0-alpha.0

### Expected behavior

Expected to be compatible 

### Actual behavior
Uncaught TypeError: Cannot set property 'disable_properties' of undefined

**Comment by pmk65** [comment]
The 2.x has a lot of breaking changes, so don't expect it to be directly compatible with the 1.x version without manually changing options to match the new setup. See #450

**Comment by schmunk42** [comment]
@victoroliveira Additions to https://github.com/json-editor/json-editor/blob/master/UPGRADING.md welcome ;)
