### ISSUE TITLE
Looking for volunteers to help update the Materialize/Foundation themes to 2.x

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#573]
Currently only the themes: Spectre, Tailwind, Bootstrap4, HTML and Barebones have been updated to the new 2.x format.

So if JSON-Editor should continue supporting the older themes, we need someone to update the Foundation 6 and Materialize themes to the new 2.x format.

If you are interested in updating one of the old themes, let us know and I'll help you with the updating.

**Comment by stroebjo** [comment]
I probably could look over the Bootstrap 4 theme if you can guide a bit, where I have to look in the code base (`themes/bootstrap4.js` file?). Though I'm not quite sure how big of a task this is…

**Comment by pmk65** [comment]
@stroebjo 
1) The biggest difference is that themes now uses **Style Rules** instead of **Inline Styles**. So you define the selectors/classes in the Style Rules and uses those to style the various elements. See #439. A good start would be to convert all the Inline Styles to Style Rules.
2) Use the `Spectre` theme as reference as this is currently the best working theme and also uses another new feature where you can define custom display options for the Theme. (Also the Bootstrap2 theme seems to work better than Bootstrap4 theme)
3) On the Playground Page, I made a test [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgGU1SAnVKAFQAWqALa8AMgENEOAK7x%2BqAM7yAwhMXNK0bMi440XOksxRw26sGLrUtCADMcJszBfYkaE3FsOKVV2%2FomT2BJaTkoeCV5Kw1FX3MXOAATJWIuWmQ6HAhgwVpFCKiY3gB3dShhCRSInCghBmQoNNQJSKgcLigZZCTW3nghUQKHToApNgB5ADkAWgBRJPoOqAAmADoADygAN1QuRVpstagASXlFARwSgoHeCW2JWgYJPCYoZQkIXq4kqFQmUQQeAFEr0ARQCQMBhQRaKZDPRAvN76LIQAqoCBI1BJcjvGTEcHlFKKNIZVEQr5Qbw4PioDbwY6CXh4OTwbKKAD0GiYpAh8luNUaODsESEUBGwnel2udSuNRqAHMFW8HulZDdBrw4SRaHZaMR2plDmi1gAePBcAB85qtUxwkSwJxFYS6GlF%2BSgoIGot4AEZNjs9gdsrjFDhRO0RQK9f8kgVhLQFQJ5BB7VA8LxYfCpNimh0eKQGIg1nA%2FDAAL5aVxwD5fCQ%2FYq%2BpxlxIIFDMVi4QgkMjAKv%2BOAAEh4dmCAGIOSk9RB6MbObXvklG6WEpWWzX4J9F8UVs2EhZ3B3sPgiKR4v5sMPUKOWNgJ1PbLP2VzN3WG9Zd8AW2uEnB61wpGKPcLxodtghPHtzwHYArxvTt72vR9UU5f9AOsFdXB%2FatgFQxBik3PA4lvZxoMPcDuzPPsWwsWDx0nRCZ2QjlcPwl4iO%2FfsLBY6wCOUfRgNIsDbzgCDKM41taOE4AEOnJ80WYrgALwni2LZZAMJcLDW24jQCKCYjqLcITO1E3txJokc6IfRi5wUpTWNeZgOPXLtT3gICDP3IyPCk0yoOwyT4Po2SmNMjznN%2FVye2KBV0iSATsLI3yKLMwyh0sqSZKQ2ywusWLaHir9V3EkSUpiuLlHSSisBIxLjOPFL%2FIkjKgusuTOVyjR8rjeAqt7CLsM6kg%2BgVDpaGMTyQLbHyTMaqivPS68rIY9qOSGqxIlG9IJu%2FPwtOSFbkIS7AF3rJdrCbSbSMCI84BOCBkHCGMGDjT0wRhVJ0iNbIKV%2BalaXpP5MUcpIS3mqbdH0PYjCImrDIsSrbAVWxHt7OGvLqmaTt6pGmqmuhGFu4A2BxiAFSpB6nvGl63u9YlSW%2B6AtwphwAdSjHW3pr7UWCEn0jJinUfFanfi9cEubJY1fpZmk6QZPHoJROdjovCx%2Frl3IBA9Z6%2FoKBUMT2PpfjwRB3i4YgOWxJZ9hffmFTWAgiPM1W4G6gB9YgcAYGRhDREwADZnamlG5AAQXgHGWUiWHTHhl3gGzYhUEuF69mCDFIk6CRCnpDTVc0uOKzjrSpogH2M351GVcErG4DL4QK4VxKbuCKZy72QWqdjWnxc%2ByWfuZ9Xc%2FB%2FPsAlxnW%2FbzoQ%2FkHWe4%2Bklualwf7Fl%2BkwaD1slfZavg9XtnNe1kWqT1g2AMiY3TcUc3LcWNkbfriuHadwvW3dz3vd9mPA9ftXKfgcOkc5ATXRqPaCidk5exSFwdOQIO7Z0fmnIqYCi4c1QfnEu0FbCbT2DPXerYkqdmwagfWMCR75xoC3KS90cHT3%2FsLbuYsF4M3JCvVmGtyHx3HjzKSbNO6z2Pkw7hy9KRD3lpwqa28%2FZXTAV4feHDOx5GGMfD0%2BsICGwvumK%2BN8rb305MQ0hz8m7QXfl7H20isA%2FzQa2GegD0hRxAbHax2EIEp2gbAzOEIKa0KgIgshv8oDllfkEjmmDsIATJjYf%2B%2BCDz1TkbQ4xFgJStGCBE%2FWiSAiE2CAAJU%2BPrfhDCaZCL7ozaWYioAAAoaEkL2AASgyQdRe%2FcchSVyZEgpc9ilNNKWwteDJKnVNIfUiRitGYx1qqPOR7Dh6KK1so7uqiz5Gy0WbC2uiOj6LgYYx2GSLCmM%2FhYqA%2FtgnF03jQOW9YWh4JkfHQh2M7YNOAMktGbgLk8AkI8gm%2BlFFvJaB0wR71hED1EfI4em8LBApaT8%2Bklzs4z0KaLQFJTWEgumeI8Fx4xkxJsaCl5cAlEIpPlANRGjcwm1Wbfa285Sb2x2SMqa%2BzzEx19CsDFf9UZ2NoA48ZASLCuKgUgzsGd4E536s4wJJzQlnOAHgHAXsWgQAJCQAA1rKjY2LQK1xlXKpgnxHnPOCEq4gqqcDqvpQQqhnYABCOqFVNCEMatV%2FzGFIu6Siv6uLHmQuCDa%2BVnx7UqqdfCzprqWEiI9Wijer8Dp2AkDIBgLzeoyFQBikSWKbkUOAGIw%2B8yaaLPUefMl2i1l3w2RyI1JqNhGPNdhRlX8A6SowdK7kkEM01yJojMmnzLXYDYP8HszqimhqXsCiNfSvXIuNLzftvJg0ArppO0dMs2ZRusXADEPsTAAG0AlwEumy7An4D1wAAMx51VgAXVTbgdNoCUHrvrm7L5jid3iosAAMVoPsdmKDWx9s9l8XZrY8g%2FHPfnK9u6s2et4XMwl%2BbSWXwpesm2LbSDVuPcAOthzjnWJCU2uOcAAKLEcG2zGHaaX6o6JUPFwAiOHG7Vk1pVRDiDsRQut14bl0cOvd6pjxHWPz0hWU6D16N3CG3ZB7J2IgNwAAOI8AxDJ4AVrvZOWsRBtdN6jqkawdB2ZR8FmnwLcs8l18S1Uo5HRnA6HINYe%2Fo21WYTWzCHjXQVDLyJn4ziThRSUhKNcGo8EdzjyZAzgAI7JrOCIGOSaU3RoQD2uAABZVz%2BQZ3yDnS69jYal3lJmOKKjrQsDBZrWPRdULsApYTWlnkGX6EhuyyOpmqK%2BnHHy884r6XHn0Gi9i2JWrO0KiU2JiTb7sCypekBtWm4GD6imydSoUIrDIHYuKi9wTr1SJ5eKqZ46YMGbzUZhDKyzOUr0RyFz1X3M2Z25huKHszH1tvDhsBeHHPSsu259LFa1UaumkTXC%2FnAtSR%2B6akL4XIuRGEDFrgybr3PuCFVr7tWBNdJy81sdfD2uFfgFgUHZqePlcR6l9zqPh3NOE5GqA2OAtFYDY6sHpWvBQ%2B27%2BzV5GHmlYsCN28r7f0WAm4VA903IRza562RQi2GDLdW7%2B9buHNu3qcWzqDaKc1waO4WxDp3kOck%2BzVnsN2Vd2Ybbh05BGZWsmyH9u5cAo5shafDxLymreO%2Fi7x61rvBPlcp61x5W2%2BvYGzft3NutiVLM0aZnRpabb26OHSjDJvnsOYvG9zCA0Jevm3B%2Baui04J3mCtlZ8p13waH3WlBLjHOz3SFjrEE5PGa4nKczT2whkASF5BiLEoMFZwEhgYGG%2BCNx22uXezNAedPYVb%2B36qERYfoDN1Ki3fjR%2FK8mVp5Wk%2FWzT474m%2BfKf%2FBOb%2FrQ1fnnRnabH%2Bvnfs%2FYsH8wtKtJUSq5b7TRftfsjLDhhn3v5Nd%2FNLSsiBhXeVP3iwn0v0zWvx%2FwX1e3Nw5jt1tU%2BHxz%2BzAPfyvy%2F13xMFv0X3wzgOABK3APP03wIKmkgMwP32wPewtys2QKVzPxIPQJv3IJgKX1wP13wNQMkVoMg1INvCwOYJwMzTYO%2BwdUrRoLfzoOgh4KwD4NHjT0P2lTjwqwkIsBQOUO3wYKgL%2F3QUPwzy4l82Ug0Fz0r2%2BWwFDn0N7wTj0AH3GlZ3jlwmjg83i1tx8yUgYxMLgBUC9g2QnVjVc1GxVykyF0g3k1QEU3FzgBU1%2F2QVHg0w%2Fx62h0D3ZyCwo2iIwWLkMjkMwT%2FH0IclsObir1MP0Png6wiDYgsMCgLzaiYh0k0Ar372hhsKHxcKkAcL%2BwNSkl4jAwLi8kyJKmaIMNQF4jUiMIRykjMKUmKJx2kLYhmGGJGTz2WhClshqIsPqMMEaJ02yKUlaJfyeRx2CF4lmP4lSJ0J6N0OwBqL0iPDP0oQKLgHGKkEmNp1x1KMcnKJakqMOmWJyPQnmMsKhnWMcQkK2JaKiDaP2I6KxC6O0PT2KhciGhGOdwmDmmdj7ysIaKBIt1Mh2OIIIW8z8iZ2MKJmRLcigH7xfk0zWMHy3wPCiEulxK8wGxSICSP1IiiE%2FAZPbWCD8WhPkMgwcLPRpLxK1QMSQRZK0IlTOLhMiiGm6iMIqLgCyhsmfARL%2BNGM7BJIHRKGOBKLlL%2BKpI2NxNKjchxI4OgnaM7D1PSKlPv3hLKjygqhxlnxuKJOCE1N5G1IK2eKwG6hmERjEgrwVOkkL2VPklVNRP%2BOsMxNwOxLBN2ItOwF9P9LFTSJtP%2FztLcmKA2hITGmjPxiRJSk9B1KmKaBGlzIpIhnRMBLyMVhSlNLUKSOSjciBxSRBzLO2grPX1UMg1hCxAeyhAkBWyPFiww17Mcjdl0Tdkdmt14Pn1HPyD7INMcRHO4I0LIN%2FwV3iyXJrIgNaHpLNMzWcIJOF0yXcOADUE2g6FNnLzG1fyIIPPXzHKYH7OeCHPXLizGwhQXPHMnOnIqxXM%2FLHm%2FOfO3PfJPIsCkLnw3P50CRPLRIBOpM5KmkG0D0ZI51xhON%2FTkP4JQVZKn1aA5IfLQvImbPFwPGdwvJzK4FNiPV5UxXELoq%2FMUD7I%2FlfMMNnLh0YqAuYp%2FLvinLDH%2FLnK4uSGAtQDdlAo4ugP5zwvASrMQqIvjh5KFOIqkiUq4uwtkJZIww2kFKQuFKJmPLotuLPMoq2lNkFLgsjIxJ3PvSgwSWUq5KklFP8UAo0tTKwolI0syL2kgHLGACAA%3D%3D%3D&value=ETI%3D&code=EQehHcEsDsBMHtwDoBSBlA8gOQKK0gC7wBOSsApgGYCGArgDYEDOSBAFuQLbktMAO5AMYFi5JH2LwiBAJ4Ck8PgUjxoLfE2oAjeuQD67LvuIMeAAgC8ZkbXIBuADrQnTsGYAqHM5Xj16iGABzM3oYc2pRM05qOGoiYhkzGNgzUWoEaHoZJDMATXhaM0EYpNgUwVomIk4i%2BAokrXgAN3IkuDMtcn9kJ0hKMwAKACsmcnx4sxgqmMFyeH6oOERUTFxxkgBKMxGxwhIyHhF4GQGNx2gd9eJLM2hycDNFhGR0bDw94gGECu5oAiQAI62BJoLpCeIDBzAADEI1UAFpdvF4T5iJwoRsADTbMZxahnFzQJoRVLkdIyAASyV01yslFo0GEKmgpzMAG9CWYuWZidcUlZvrRfgRsVpaAQiNA9GxfBRadtRlckJIpKwONwkIFyAQKWS5QAhcWSimy8ifAnOaDcnkkwRpAjkQ0S1Q3emM5SqAYOgAeIqK1D8WmoggA1lsOVbrTbrmLnVarJcPsr4KqtQQnZKveRfdiAOS57E%2BggWqMdI2qJBVGS6JDRb0AdUgsHYN1zAHZRJxc%2BdS7HJdLTaRqHwBHAAMJsSD0WADPuqEtRudSmXTs2V2Q1jR8ejURJWXOUXTe7tOXvl6BIdKwHAtP4AGUgVXId0%2BucEoVDBf9geDIexNHoUYF2tRN4mTVUOHSNc%2BAiZ8CCwOoxCmM10yoEhyFnc8B1XYhsVA%2FYVX%2BSC5SQO5fTQSAdCCYCzAAXx7bleSKe1yFBXRhFdBkmU9RQPTUbFih%2FUNw1PKMmNGegbnw0hCLVIxNW1NjwQASWgPhxQGaAGHof8AyAhjrQkpB32oJgmAfKpLzKAZcwk8F4SYLtMVzWB4RgUI7gLXNOGIeEACYv28mR4QARlzGiuSMqsazrRtmzYVsOy4E9IxAxUk1kwwNVGAglOEDAlGZJgBgk7EMC0IZwSQYl6FsYreKKrEzHKyrhCQENyBkerCtUJgNgiswjKvG84Ish0XxswQ2BiLUv0E%2Bgg1DXTAPIAal2wkjh1HWAJynGcJIG6TwKIvVoNgv4EIoJBkOIVDUQw9aVzlPD0rA2TiLXMjcsojzAho%2BjRK5JjRDtMkHXeCY6S4vjWQjUs%2BkGaTJjUAgZjmBYYGeFY3iuLYjooKpJBOQ7XpIG47geJ5lleNYPi%2BeAfjgwFgRkPKIShWEmARJESBREh0WAJrKtgPESZ50hPVzNJYBkL83W4lkRNSqNpcpakzVOAzuVo%2F6tcB5iwdYsFhAGOGo1zVT1IIQbIAAL3IXMAC5bm0zF9a5XMELRAMnbMXNoH5n23eVj20GiPxfds8P6ALd2%2FbvCJZud3Md2IWb9do%2F9oeZAZVvZOOEdz1hE%2B1aqA1sLYqZeVYIf2CgaAYZg5O4XgBGEURxEkaQ5DEBreuutTxT0Jg7daKwxFRtPS5q2wta5EGWNr80tZ1859dBuJHXPGyE86ST9VlOXs89POzetKvsdpsD67oRgWCynhKzbkQxAkKQpB7hQerUJAdz3vRGjThuAAQgvjTJeBwG532bo%2Ffg4IO5v27vIPuP8%2F5dAAbKOepIN7gyuJrDOFp14sQzJLAAgqEQIVoD7Oict4Y%2BLJT5xzATXJUN9G733VLA5%2BCCu4f2Qd%2FFgAZICUIwTQkBzCcZJjYdAh%2Brd4Gv14bIfhfFBEUKlI0GhWCF6GyXvg5Wq99ZEMNiQlkuYWrgjMAfYgcoj7uhzowkOjxMbUxYVIqgt8m6yKfvIzu78lG9wEQoCq4IMHWLNOI5x1dJHX3cewmBcj24KL8Z%2FFBLB4DBOEKEuUWihCLzwf9GiRjN4mJsuYjiqkKB%2FFsQrXOStSwSKvnXWJMjOEJJfr4pBASVFBNagQPQmM4IRKWFExppBpGeNad4xJHS%2BFdKKj0kJAy%2Fg5JweQXRBS9bK1WSU3M7htC6EsSQGxWc7EnzqVGBpEDxkcKMG0nhyTlHzNRjofQjQwnylAZEy%2BVzmkTNuVM9piDZlf26c83QWSzQrLyXTDZhitnEO3rs%2FZrQABa5AtDEFMhuB2JyakOPqV88BrDfk3JbgC%2B5nSQVPORXoe2GKsXVjHmYT5wzvnEqgX8slcDplAv8VS%2FuYL9B0sxdFewcdtGb3WSvBcnIzBOABpaI6ktVbVJhuc1WVI4A0j0avYAQA%3D&style=ETI%3D&theme=spectre&iconlib=fontawesome5&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1) for the `Spectre` theme that displays all the available editors with various options enabled. You can use that to test the `Bootstrap 4` theme too,
4) Also the Playground examples for Selectize/Select2 is good for testing if those looks correct.

The Bootstrap 4 theme extends the default theme class (`AbstractTheme` in src/themes.js) So if you don't redefine a function in your theme, it will use the function from the `AbstractTheme` class.
Also you can call the function from the `AbstractTheme` class using `this._super()`

If you need more help, just ask. 😄

**Comment by stroebjo** [comment]
@pmk65 thanks for the tips! 

Can you also point me in some direction on how to set up a local dev environment (the information in `CONTRIBUTING.md` seems a bit out of date, there is no `npm start` in the current `package.json`?). 

I found the `npm server-test` but opening the `docs/index.html` seems to load all assets from a CDN. Can I produce the example page you linked locally?

**Comment by pmk65** [comment]
@stroebjo In the 2.x version we have switched from using Grunt to NPM scripts. And we really need to get various documentation up-to-date. 😁 

But you can type `npm run` to get a list of available scripts/commands. (Use `npm run <command>` to run a script/command)

`npm run watch` will monitor the `src` folder for changes and update the lib whenever a change is detected.
 
The Playground is in a different repo https://github.com/pmk65/jedemov2 Clone this locally and change `window.mappingOverride` in the top of `dist/demo.hml`, to point to your local version of `dist/nonmin/jsoneditor.js`. Then you can create custom setups/tests as you like.

**Comment by schmunk42** [comment]
@stroebjo We thought about taking on BS 4.x, with which one would you have started with? Just so, that we don't do double the work :smile:

**Comment by stroebjo** [comment]
I would look at Bootstrap 4. I don't use any of the the other versions/frameworks so I couldn't really help there.

**Comment by pmk65** [comment]
I have added a Bootstrap 4 Test Case to the Playground.

**Comment by stroebjo** [comment]
I started to look at the basic form fields. Cleaned up radios and checkoxes (code at my feature branch: https://github.com/stroebjo/json-editor/blob/feature/twbs4theme/src/themes/bootstrap4.js).

Bootstrap also provides options on [sizing](https://getbootstrap.com/docs/4.3/components/forms/#sizing) the inputs and has an option for "[custom forms](https://getbootstrap.com/docs/4.3/components/forms/#custom-forms)" (more fancy looking checkbox/option/...)

I think both could be made available as options in json-editor?


@schmunk42 did also start doing something, or can I just continue on my branch?

**Comment by schmunk42** [comment]
@stroebjo Please continue, thank you!

**Comment by pmk65** [comment]
> 
> Bootstrap also provides options on [sizing](https://getbootstrap.com/docs/4.3/components/forms/#sizing) the inputs and has an option for "[custom forms](https://getbootstrap.com/docs/4.3/components/forms/#custom-forms)" (more fancy looking checkbox/option/...)
> 
> I think both could be made available as options in json-editor?

Yes. Take a look at the `Spectre` theme and see how the options is used/implemented.

Also you can remove the default rule `div[data-schemaid="root"]:after` if you want to get rid of the red warning text message at the bottom of the form. 😉

**Comment by lukzas** [comment]
@pmk65 I could take `Materialize` as already contributed to it and actively using it in a project 😉

**Comment by mraheelkhan** [comment]
is there anything I can help with? 
would love to contribute

**Comment by schmunk42** [comment]
I am going to close this issue, since it's nothing which is really still open.

But PRs are always welcome, yet it looks like it wasn't used very frequently.
