### ISSUE TITLE
SimpleMDE on second tab only shows content after click/focus

### ISSUE THREAD

**Issue by michielpost** [json-editor/json-editor#574]
### General information
When I place a markdown property with a SimpleMDE editor on the second tab (using the categories format for tabbed layout) the content of the SimpleMDE editor is only shown after a click/focus. 
It does works when the editor is on the first tab.

- json-editor version: 2.x

### Expected behavior
Markdown content is visible when selecting the second tab.

### Actual behavior
Markdown content is not visible when selecting the second tab, only when selecting the Markdown field it becomes visible

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYA7PhqIkAYhAAaEJgCWmADZw0IAKIAPJAhxKpMgJ45l6UgCMicKJj1cmya+ihJMcZk1lwIe00giyoAMLOrkz6ACryuugAskiy5HqMcACOAK6ySWxoANoykcoAutI4jKRGjHKeaKByisY1hsYgEJiM8cx6tVEgES4KegjxADJw5MyYMGgAjAC+0sjx1Xl1KmFwANYtnY0qLW1jNnbOKsiM62ykAO4J0mVyFF6ooH7aSghs9c1GCgoB8FDrOCMNBcJAKCBwGZQ6SmUgAfSgFBc5AcDSMKjMFisnXyKgCSNG1mKpXKlUeoA+0DaOHuCSey26a02RIM6PQe3ah0Y9hOSDOF2uejusgeSxeOkQHzF31+/0BwNQoPBkKhqpmQA&value=N4IgLglmA2CmIC4QHsDWIA0IC2BDCAdouABYQDOABAO7IBOq5mIARsgPoDGyBYsviUABNY5TnQgAHSD2JgyVHtACelciWTUquAGZ86lXJU7QIndAF8LQA===&lib_switcher=simplemde&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

```javascript
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Example",
    "type": "object",
    "format": "categories",
    "basicCategoryTitle": "Main",
    "required": [
        "title"
    ],
    "properties": {
        "title": {
            "type": "string",
            "title": "Titel",
            "minLength": 1
        },
        "bo_content": {
            "type": "object",
            "title": "Content",
            "properties": {
                "description": {
                    "title": "Tekst",
                    "type": "string",
                    "format": "markdown",
                    "options": {
                        "simplemde": {
                            "spellChecker": false
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by schmunk42** [comment]
Likely an initialization issue with the editor CC: @germanbisurgi we had that with other editors too

**Comment by pmk65** [comment]
@michielpost Strange. In Firefox,the above test link works perfectly with editor in both Tabs.  But when using Chrome the error described is present.
Do you use Chrome? If yes can you try testing it in Firefox too and see if it works then.

**Comment by pmk65** [comment]
Looks like a persistent SimpleMDE bug. (The links below also has suggestions on how to work around it, but none looks to be 100%) 
https://github.com/sparksuite/simplemde-markdown-editor/issues/344
https://github.com/sparksuite/simplemde-markdown-editor/issues/596

**Comment by michielpost** [comment]
Thanks for looking into this. A colleague of mine also wrote some javascript to work around this issue:
```js
const markdownEditors = [];
function editorChange() {
    for (let x in editor.editors) {
        const e = editor.editors[x];
        if (e._fixed) continue;
        e._fixed = true;

        if (e.simplemde_instance)
            markdownEditors.push(e.simplemde_instance);
    }
}
addEventListener('DOMContentLoaded', () => {
    if (!window.editor) return;
    window.editor.on('change', editorChange);

    const tabs = document.querySelectorAll('[data-toggle="tab"]');
    for (let i = 0; i < tabs.length; i++) {
        tabs[i].addEventListener('click', () => {
            setTimeout(() => markdownEditors.forEach(e => e.cleanBlock()), 100)
        })
    }
});
```

**Comment by pmk65** [comment]
> 
> 
> Thanks for looking into this. A colleague of mine also wrote some javascript to work around this issue:
> 

Unfortunately that approach isn't 100% either, as tabs can be inside other tabs. And also the attribute might not be available in all themes.
There is a codemirror addon that could be used in these cases. http://codemirror.net/doc/manual.html#addon_autorefresh
But I don't know how to load in in combination with SimpleMDE other than creating a custom build.
(I could rip the code and implement it directly in the editor)

**Comment by pmk65** [comment]
@michielpost I have ported the code from the codemirror addon and created a PR #575 that should fix the problem.
To enable it, you need to set the SimpleMDE option `autorefresh` to true, for the property.

**Comment by michielpost** [comment]
Cool, thanks! I'll wait for that PR to merge and then use that.
