### ISSUE TITLE
"json-editor version" dropdown in interactive page

### ISSUE THREAD

**Issue by germanbisurgi** [json-editor/json-editor#579]
It would be great to have the possibility to switch between versions of the json-editor in the interactive table.

**Comment by pmk65** [comment]
There's one "problem" with doing that. Someone will have to (remember) to update it every time we create a new release.
In the Playground page I added a quick way to override the CDN libraries, where you just change the URL manually in the top of the  `dist/demo.html` file. So my local clone of the Playground uses the current local build of JSON-Editor.

**Comment by pmk65** [comment]
I looked at the network data at https://www.jsdelivr.com/package/npm/@json-editor/json-editor and we could "hack" into their API. As calling https://data.jsdelivr.com/v1/package/npm/@json-editor/json-editor will give back a JSON object, containing a list of all available versions on CDN.
