### ISSUE TITLE
I am trying to use other name instead of "root" for UI.

### ISSUE THREAD

**Issue by brij281** [json-editor/json-editor#58]
First  and first thanks a lot guys for such type work. 

I am trying to use other name instead of "root" for UI. Basically don't want to display "root" on UI. I tried following way, but  it not worked for me.
1. JSONEditor.defaults.options.form_name_root = "newUI";
2. jsonUI = new JSONEditor($editor, {
        schema: Schema,
        startval: initialData,
    form_name_root:"newUI"
});

I am suspecting issue in line#1434. it is not replacing the string.
    **if (this.jsoneditor.options.form_name_root) this.formname = this.formname.replace(/root^\[/,this.jsoneditor.options.form_name_root+'[');**

**Comment by marc7000** [comment]
Add a title attribute in the root element.
See the example below and compare the schemas:
[Without tittle attribute](https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoAdgIYC2c8oksCIVYh5dAczwgAJtUx8oFJHS4AxcoR4ACBnRHKAMgxWMWwpv00xBYABYIALPjEAzBgFcANjkQApGIRhMIygCJIhLIAvqFAA==&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCAL5AA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)
[With title attribute](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QAVYCcDOB7AdiANOAJ4AO8SWARgFawDGYBIJaWZaksGioOAhgFtyoMKXIgMYNBBwBzJgBMudaSUi5EIAGIRMYAAR8cC/QBk+k/fyFMBM07DlgAFogAshJQDM+AV2iMSABS6LACRPoAIlhoeAC+CUAAA==&value=N4IgdghgtgpiBcIBSMBOMoE8AEARA9qmCAL5AA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

**Comment by germanbisurgi** [comment]
@brij281 you were indeed right. I made a PR for this. Thanks for letting us know
