### ISSUE TITLE
DescribedBy Editor doesn't validate referenced properties (they are always valid)

### ISSUE THREAD

**Issue by skewty** [json-editor/json-editor#580]
Here is an example using your "Property for Sale" schema with a few validation requirements:

[Link to Json_Editor Interactive with issue](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgAUAnHNDpKAMxwcoAZQCGTClWzIuPOqgDOmKOGgwZc1L0QA5MQFtmWNRo00Ux7IvgdaEAOZT1ZmvUktsnbtr76jzmbUwAAmSsR2yHQ4ECpwACoAFqhQEIYpOPxQ8MlQsj46UHio9g5QijgMIYFBcAb2ADKojjkqAKzSMAC%2BlC6aBUjxliqmtQjDnnA2do41rgjuVuxahUNoc%2BbAzQCuBioA2p1jiTjbisy9QZvEYhwb84hixIlkwEcwALpHPUdw%2BfKINaoADyUVoMWUnlG8yQ60muEIJFelzGdEYS2A3gBUFB0QgkJR8wA7mJ4M8Ru9Nv9fICJqxgNSdEC4JSfn1ggx7ABrSFYQ7sjTQq7YDioBhxULhOzFEIAIUQ92Oov4EoAxAB6ML8ez0cH49UgECMwaWLpdFkC7qUr59c3qNnBUUAR22tFF1U8%2FPmxr06Q2fxWJrh0g%2BKLgWp1eN5ql%2BwBOZysQuCxtoSgpluwYhCIVFimjSdRdOstlKiphiwlAEFs7mCZT5vUIE0Wol2vWoA7hXAuDgDPn28FYRj7PBUA5tGXNmiPPTdLtisJgVkAEo4Xt1jPBRu0Ay7FQARnbdqux40neCNzuUMpAYGqf7GbgeA4YggHpMA%2BwQ4l01LwEJXYLOiEqyi%2Bb6TsEOx7J6n7BJW2whLQEGbLKACyADqyHBAAwskABuXBMMisHYKCYpYdgqH0Io2x4LQiiJEhbyblANrCh2AHzMQlRCOm7GDkWUwlrM%2F6fm4wHwthPFXpxYyCBwBikhK3EMLxzHseeYyIKgtx8fxFhwvSv4ibJ5YSfSsqulUUAAJo6VeR6st8AFwI8zyvB%2BAq3vI956VccBpAE14sQZGLGU4okhUBM7YP4zBHqZ2AGDgYTisF%2FFfoJwDhch4kxXAqEpeR6nCppDz2X5gHfvCI5jhOkUZXlGJ2bpJUnolrlPC8zYOK06X6eMhnYLV44yWJ0UYj1fWOQKp5WvakBdMAQA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=handlebars&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

**Comment by pmk65** [comment]
Fixed in #581
