### ISSUE TITLE
array and minItems/maxItems not being required

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#585]
### General information
setting minItems / maxItems on an array has no use.

                  "color": 
                  { "type": "array",
                    "items" : { "allOf": [
                      { "type": "array",
                        "minItems": 2,
  						"maxItems": 2,
                        "items": [ 
                          { "type": "number"}, 
                          { "format": "color", "type": "string" } 
                        ]   
                      }
                      ]}        
                  },

- json-editor version:
v0.7.28

### Expected behavior
When I press Add on Color, there is an array of a number and a color.  When I press add, I would expect two items to be added, a number and a color

### Actual behavior
When I press Add to Color, I then have to press add twice, once for number, once for color... I can also finish with only adding one of the two... or add a 3rd/4th ect... that are user defined.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript

```

**Comment by pmk65** [comment]
Try the current 2.x version and see if the problem is still present.
