### ISSUE TITLE
remove_empty_properties: true cause "TypeError"

### ISSUE THREAD

**Issue by pmadril** [json-editor/json-editor#589]
### General information
On the simpleExample shown below, if remove_empty_properties is set true on options, adding an item throws `TypeError: Cannot convert undefined or null to object` on console and ABoolean doesn't appear on form.
- json-editor version:2.0.0-alpha.0

This error was introduced in commit 496a89ec55fe4064f83bad05c84ae1b3e1fcc2e2 #550 
and is possible related to #131.

On line 1048 before commit:
if (typeof result[i] === 'undefined' || result[i] === '' || result[i] === Object(result[i]) && Object.keys(result[i]).length == 0 && result[i].constructor == Object) {

changed to 1038:
     if ((typeof result[i] === 'undefined' || result[i] === '' || result[i] === Object(result[i])) && Object.keys(result[i]).length === 0 && result[i].constructor === Object) {

New parenthesis change the result. The sequence A || B || C && D && E is changed to (A || B || C) && D && E which causes `TypeError: Cannot convert undefined or null to object` when result[i] is undefined. I suggest to change to A || B || (C && D && E).

### Expected behavior
No error on console and ABoolean shown on form.

### Actual behavior
`TypeError: Cannot convert undefined or null to object` thrown on console. ABoolean doesn't appear on form.

### Steps to reproduce the behavior
- Add an item to the array on the example, it throws error on console and ABoolean doesn't appear on form.
- Change remove_empty_properties to false on schema and press Update Schema button.
- Add an item and now everything is ok, no error and ABoolean appears on form.

Direct link to example: [simpleExample](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QCsDOB7AdgAlQYwAtYBbAQ1wmIAc4BRAD1OrhABpwBPK+JUgJz6kObEFBKpEoMFx4h0AI2Sw8YEVT7pufSLAkJQqSjVgMmxyZ26I5i5avabIWPaD4l0AN1gB9ElWne6pqw2hC6iGB8AK6wAL7sQVo6LiAAggByUcTyIRbSVkiYWTl8IPFpAELo6HCkmHky1vLVtfWx7R1AA==&value=NoXSA===&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction)

```javascript
{
  "title": "json schema simpleExample",
  "type": "array",
  "items": {
    "type":"object",
    "properties": {
      "simpleExample":{
        "type":"object",
        "options": {"remove_empty_properties":true},
        "properties":{
          "ANumber":{"type":"number"},
          "ABoolean":{"type": "boolean"}
        }
      }
    }
  }
}
```

**Comment by pmk65** [comment]
@pmadril I have added your parenthesis changes in #590

**Comment by pmadril** [comment]
Thank you very much.

**Comment by pmadril** [comment]
Sorry for the delay, I was in a travel all the past week, just read mails today. I apologize, I must have pay more attention.
