### ISSUE TITLE
Custom/alphabetical property sorting

### ISSUE THREAD

**Issue by rejemy** [json-editor/json-editor#59]
I am making an editor for a schema where there are a large number of additional properties with arbitrary names (a large database-like map of values), and I can't find a way to get them sorted. I can't use propertyOrder, since these are additional properties whose names are not known ahead of time.

I believe it would be solvable by adding an option for alphabetical property sorting, or a way to supply a custom sort function to use to sort object editors.

**Comment by schmunk42** [comment]
Could be an enhancement.

Is there some JSON-schema spec about it?

**Comment by rejemy** [comment]
I don't believe there's any way to enforce ordering in JSON-schema, I think an object is by definition unordered in JSON. This would have to be something purely for display convenience. I'm thinking of modifying the sort comparator function in editors/object.js to fall back to alphabetical sorting if propertyOrder is not set on both properties being compared. If you want I can submit that as a pull request, enabled by a new schema options flag, something like alphabetize_properties.

**Comment by rejemy** [comment]
I'm not creating a schema dynamically. I suppose I could load the json first, build a schema off of it and use that, but then I'd have to update the schema every time I added a new entry to the database, and I don't think you can switch out the schema on the fly.

My (simplified) schema looks like this:

{
	type: "object",
	options:
	{
		disable_collapse: true,
	},
	additionalProperties:
	{
		type: "object",
		options:
		{
			collapsed: true,
			disable_properties: true
		},
		additionalProperties: false,
		properties:
		{
			name: { type:"string", title: "Name" },
			cat: { type:"string", title: "Catagory" },
			img: { type:"string", title: "Image filename"},
			max: { type:"integer", title: "Max stack size" },
                         <.... many more properties>
		},
		format: "grid"
	}
}

The (simplified) database looks like this:

{
	"wood": {
		"name": "Wood",
		"cat": "goods",
		"img": "wood.png",
		"max": 100
	},
	"stone": {
		"name": "Stone",
		"cat": "goods",
		"img": "stone.png",
		"max": 100
	},
	"hay": {
		"name": "Hay",
		"cat": "goods",
		"img": "hay.png",
		"max": 100
	},
	"thatch": {
		"name": "Thatch",
		"cat": "goods",
		"img": "thatch.png",
		"max": 100
	},
	"peat": {
		"name": "Peat",
		"cat": "goods",
		"img": "peat.png",
		"max": 100
	},
        <100s more items...>
}

The items can be added and removed in the editor, and there are many of them, so it's nice to have them sorted to be able to find them when editing. There is no master list of all items, since admins are always adding more.

Anyway, I understand if this is a special use that's not broadly done. I've already made my own branch with the alphabetical sorting option, and I'm happy to just use that going forward if you'd rather not mess with it in the main branch.

**Comment by pmk65** [comment]
@rejemy Sounds like an interesting feature. Please submit a pull request.

**Comment by snipercup** [comment]
This is an interesting issue and I also support property sorting. What I would really like though is that the json Editor keeps the order the keys were in when they were loaded in. Currently, when json is provided to the json editor and the schema does not provide any property order, the editor decides on a new order by itself. In this case, I don't want to specify any order, just keep it as it was.

**Comment by rejemy** [comment]
Sorry I'd forgotten this issue was still open. My version of json-editor has diverged a bit by this point and I'm pretty happy with it, and it sounds like you'd rather keep the current ordering, so I'm going to close this.
