### ISSUE TITLE
DescribedBy doesn't work when "type": "array"

### ISSUE THREAD

**Issue by odurbalau** [json-editor/json-editor#593]
Here is a non working example using your "Property for Sale" schema:

[Link to Json_Editor Interactive with issue](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2ABQE4D2ADmvkmgM5QBmh%2BUAygIbpwA0kMc8AnqVhzN8%2BZrw5ccyNAFtKg8MAAk%2BNDUFwAxAHoAJmsQRkiQhErbiRYgDF6LNsAC%2BnaDn01Dx0%2FODZwr7mBLElt8ewxfKH8YGJw%2BAUi4QgAjACs0AGN4CQCYnmQHbDgCEjI%2BWnomVgiXWMDg0nJEKgVJOpwGst4AOWYZCL829rj%2BAZxKeHxDAHMc4byEArHiqy6oXv65%2BbcqDKniJFMNYAAVAAs0KAg%2By8IaKHgLqE7yXihktBmoSkIUXTghrFnICFi8%2BCdRq1cu0eJDEsAJlMILNgLVtvlUMs8KtXlAIQk0fM4GgIABXGSCADaIJhwDOhFJlBqNLqcAywi22xwvGYGTO2WALJgAF0WcDoaCceDRgB5A4mMxQrmwhJFYApdJZTnDDGFHAlRrlOWHRWooU4ADuzHgfKVXI6Ut4%2BKxYKdcPN4uVwBQhgA1j5sNSJe1ovbAqoUMd9JQ9ogProAELiM3BnV01TqeE6dyeE3mEAgV3OxyOAGpoHm0Wp0sSz2s4CqACOpMQqn%2BkSDRKCjo2zNTcCL7olVaBhJw9MZY1DsQHUuaAaiLLgzF0ulUlAX07T8SxiJm2tpSExxwAgqv1z4xWOZw3CIQ5HauzvjoZ4GhpmQD%2FWj3q4N1yR8DAyvcABKd4PoK1YgjWo5DGyHKRFu9Rzi0iFLsAySiBA7aDOWIyquMkz7imXo%2FliCZYe2171iS5JUuagQnqSuiIF%2BtIJgAsgA6mx9YAMIXAAbkQ6ACtRtJymgkYkfacAccglCkskiCUGcrGQVyI7DHWtIZL89CPtucJqnuyK8YEZHHHx%2Bn4OZOB0PgMjWscekoAZGnaeJ3JoAhuGkcZhFIiiXkWUsxwJi2fxQAAmj5tkee0MF1ElMA6dyvL8oZyGlE0qF%2BWm1ybGheEqruRFmTJT5hfCvZlvMaU3jIhD6NJ%2BVPgFcCmcF5q6liHHNVJdWeehvBxVl34dcAr7vp%2BlXbtVaqxQhV4jRl8AADIktMjzjTez7wtNH7xSFcQLTgm3IjtCXJdBQxJTWjjAEAA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=handlebars&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

**Comment by pmk65** [comment]
I think this have been fixed in current version. (Repo version, not CDN)

**Comment by skewty** [comment]
@odurbalau please try this out tomorrow morning when you arrive and send me a Mattermost message with the results.

**Comment by odurbalau** [comment]
In json-editor v.2.3.0, the additional properties for car, yacht and house don't appear. Also, there is a type error in the console on line 16789 of the non-minified jsoneditor.js file whenever I click the "Add Property for Sale" button.
[Link to Json_Editor Interactive with issue](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgS3gGwKZwFy2ABQE4D2ADmvkmgM5QBmh%2BUAygIbpwA0kMc8AnqVhzN8%2BZrw5ccyNAFtKg8MAAk%2BNDUFwAxAHoAJmsQRkiQhErbiRYgDF6LNsAC%2BnaDn01Dx0%2FODZwr7mBLElt8ewxfKH8YGJw%2BAUi4QgAjACs0AGN4CQCYnmQHbDgCEjI%2BWnomVgiXWMDg0nJEKgVJOpwGst4AOWYZCL829rj%2BAZxKeHxDAHMc4byEArHiqy6oXv65%2BbcqDKniJFMNYAAVAAs0KAg%2By8IaKHgLqE7yXihktBmoSkIUXTghrFnICFi8%2BCdRq1cu0eJDEsAJlMILNgLVtvlUMs8KtXlAIQk0fM4GgIABXGSCADaIJhwDOhFJlBqNLqcAywi22xwvGYGTO2WALJgAF0WcDoaCceDRgB5A4mMxQrmwhJFYApdJZTnDDGFHAlRrlOWHRWooU4ADuzHgfKVXI6Ut4%2BKxYKdcPN4uVwBQhgA1j5sNSJe1ovbAqoUMd9JQ9ogProAELiM3BnV01TqeE6dyeE3mEAgV3OxyOAGpoHm0Wp0sSz2s4CqACOpMQqn%2BkSDRKCjo2zNTcCL7olVaBhJw9MZY1DsQHUuaAaiLLgzF0ulUlAX07T8SxiJm2tpSExxwAgqv1z4xWOZw3CIQ5HauzvjoZ4GhpmQD%2FWj3q4N1yR8DAyvcABKd4PoK1YgjWo5DGyHKRFu9Rzi0iFLsAySiBA7aDOWIyquMkz7imXo%2FliCZYe2171iS5JUuagQnqSuiIF%2BtIJgAsgA6mx9YAMIXAAbkQ6ACtRtJymgkYkfacAccglCkskiCUGcrGQVyI7DHWtIZL89CPtucJqnuyK8YEZHHHx%2Bn4OZOB0PgMjWscekoAZGnaeJ3JoAhuGkcZhFIiiXkWUsxwJi2fxQAAmj5tkee0MF1ElMA6dyvL8oZyGlE0qF%2BWm1ybGheEqruRFmTJT5hfCvZlvMaU3jIhD6NJ%2BVPgFcCmcF5q6liHHNVJdWeehvBxVl34dcAr7vp%2BlXbtVaqxQhV4jRl8AADIktMjzjTez7wtNH7xSFcQLTgm3IjtCXJdBQxJTWjjAEAA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=handlebars&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=1&disable_collapse=1&disable_properties=1&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1)

**Comment by odurbalau** [comment]
This issue is a duplicate of https://github.com/json-editor/json-editor/issues/786
