### ISSUE TITLE
New 2.x tests

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#596]
@pmk65  @schmunk42 
I have time to write tests now. Since i went on vacation new features wer introduced. Could we make a list of features do you want me to tests? :)

_Originally posted by @germanbisurgi in https://github.com/json-editor/json-editor/pull/582#issuecomment-547396940_

**Comment by pmk65** [comment]
We should have some tests of the JavaScript callback functions using the `enumSource` property.
Here's an example of usage (primary_color property): https://is.gd/LCrQFN

**Comment by schmunk42** [comment]
This would be worth a look: https://codecept.io/plugins#puppeteercoverage - so we'd see what parts are not tested :)
