### ISSUE TITLE
multiple editor will create a link twice

### ISSUE THREAD

**Issue by hybtalented** [json-editor/json-editor#599]
### General information

- json-editor version: 2.x

### Expected behavior
there is one link `google` in the form.
### Actual behavior
the JSONEditor create same link twice in the form
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "test links",
  "type": ["number","string"],
  "links": [{
    "rel": "google",
    "href": "www.google.com"
  }]
}
```

**Comment by pmk65** [comment]
This is due to "`type": ["number","string"],`. Changing it to a single string value will just render 1 google link.
And as array is a valid `type` property, then this is a bug. https://json-schema.org/understanding-json-schema/reference/type.html
