### ISSUE TITLE
Refactor/rewrite upload.js

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#603]
### General information

The upload editor looks quite ugly in most themes due to the different browser layouts of `<input type="file">` 

The best solution would be to hide the file input and then trigger it using a standard button. Example: https://jsfiddle.net/78ozymLv/

## New feature
It would also be nice to be able to configure it to use Drag'n'Drop to create a Dropzone, like this: https://codepen.io/pmk/pen/gbZLbG

## Update features
- Options should not be in global property namespace but under it's own namespace.
- Upload handler should be a callback function similar to other editors. That way you can have different handlers if needed.
- Options should be documented. Right now there's a "hidden" option called "auto_upload" not documented anywhere.
- After clicking the "Upload" button, the button should change to a "Remove/Cancel" button.
- Output is to rigid. We could make this more customizable by taking advantage of the template engine support.
- It should be possible to restrict upload to specific (mime) types.

**Comment by schmunk42** [comment]
I'd stick with the default browser button by default. There's such much which can go wrong, eg. displaying filename/path on different OSes.

@marc7000 How did you use a custom uploader recently?

**Comment by pmk65** [comment]
1) You can't style the default upload element as it's rendered differently based on browser.
2) Some browsers shows just a button while others shows an input field + button or button + text.

Hiding it and then triggering it from another element (button) will give a uniform look in all browsers, like in the jsfiddle example I created. And the button/field styling will respect the Theme styling.

![image](https://user-images.githubusercontent.com/478711/67863231-c8a20800-fb23-11e9-96e8-94180019c5ff.png)

**Comment by marc7000** [comment]
@schmunk42 
https://github.com/json-editor/json-editor/issues/111#issuecomment-400331222

**Comment by pmk65** [comment]
@schmunk42 I'm talking about the code rendered by the editor, not the upload handler.

Spectre Theme:
![image](https://user-images.githubusercontent.com/478711/67944070-ddda6d80-fbdb-11e9-9b08-817d09129574.png)

Bootstrap 4 Theme;
![image](https://user-images.githubusercontent.com/478711/67944104-f5195b00-fbdb-11e9-931e-f67941c2d01d.png)

As you can see from the screenshots, buttons doesn't use theme styling and field looks very different in the 2 themes. (Screenshots taken on Firefox/Win 11)

**Comment by schmunk42** [comment]
IMO we should not change the style by default. It should be easy to apply the changes you mentioned.

My comment to Marc was about a drag&drop upload handler

**Comment by pmk65** [comment]
> 
> IMO we should not change the style by default. It should be easy to apply the changes you mentioned in your project.
> 

You can't style the default upload element, that's the point. So if you want a nice form with uniform styles, the only way is to use the Button editor and then create custom callbacks to handle the uploads. (Not sure how many people knows how to do that. And it would also require several additional fields in the schema properties.)

I just want to replace/hide the upload field and then use standard elements to display/trigger the upload. 
Functionality will be exactly the same as before as the click on the standard button element will pass the click to the upload element.

>
> My comment to Marc was about a drag&drop upload handler

The upload handler only handles the uploaded file(s), not how you upload them. Drag&Drop needs to be set up inside the editor itself.

**Comment by pmk65** [comment]
In #607 I have added custom buttons/display field + the ability to use Drag&Drop uploading.

Currently the element container is used as DropZone, but that can easily be changed. 
One idea is to use the "Info Editor" to insert a custom HTML element, and then in the "Upload Editor" config, set the dropzone to the HTML element. That would allow flexible layouts.

**Comment by pmk65** [comment]
Here's a list of options have added so far:

| Option             |  Description
| ------------- | ---
| title    | Title of the Browse button. (Default: **Browse**)
| auto_upload  | Trigger file upload button automatically (Default: **false**)
| hide_input    | Hide the Browse button and name display (Only works if 'enable_drag_drop' is true) (Default: **false**)
| enable_drag_drop   | Enable Drag&Drop uploading. (Default: **true**)
| drop_zone_text  | Text displayed in dropzone box (Default: **Drag & Drop file here**)
| alt_drop_zone_id   | Alternate DropZone ID (Can be created inside another property)  (Default: **none**)
| mime_type | If set, restrict upload to mime type(s). Can be either a string or an array. (Default: **none**)
| upload_handler | Callback function for handling uploads to server. (Default: **[Dummy Test handler]**)

There will be some minor breaking changes as the **upload_handler** is now an editor callback function and is set specifically for each property. Other than that it's compatible with the old version.

**Comment by pmk65** [comment]
**Elements in container:**

- Header
- Description
- Text input element - for holding base64 data. Hidden
- File input element - for file upload. Hidden
- Browse button - Trigger File input element. (Can be hidden in some setups)
- Name display - for displaying the name of file, emulating the File input element (Can be hidden in some setups)
- DropZone - for drag &drop uploading. (Can be hidden in some setups)
- Preview - Preview container with several elements. (Currently inserted into the description field)

**Elements in preview container:**
- File type/size info
- Image preview (If image upload)
- Upload button
- Progress bar
- Download link

IMO The "Name display" is useless and should instead be used as container for the preview container. then the name could be displayed alongside the file type/size info in the preview container.

Currently when clicking the "Upload" button, the upload to server starts and the "Upload" button is disabled. Then when upload is done it's enabled again. 
But wouldn't it make more sense to remove the button or replace it with a "Delete" button?

**Comment by pmk65** [comment]
Test example: https://is.gd/Yupe8V
