### ISSUE TITLE
Run headless and optional tests in separate Travis Jobs

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#605]
### General information

- json-editor version: 2.0.0-dev

### Expected behavior

Test results should be separated into browsers (4x), headless and optional.

### Actual behavior

headless run before browser tests.
optional after_script

### Steps to reproduce the behavior

see travis

**Comment by germanbisurgi** [comment]
Would be ok of we use stages?

stages:
  - unit
  - e2e (in parallel with matrix)
  - e2e-optional

**Comment by schmunk42** [comment]
The second part would be the right thing to do.

**Comment by germanbisurgi** [comment]
PR #614

**Comment by pmk65** [comment]
can we close this?

**Comment by germanbisurgi** [comment]
yes
