### ISSUE TITLE
remove theme error displayed?

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#608]
### General information
I'm trying to add a theme to an editor.  Is there a place / example of the new themes?  all the examples I'm seeing online are the old ones that show the "This is an old JSON-Editor 1.x Theme and might not display elements correctly when used with the 2.x version" at the bottom of the form output.
I am hoping to find a location for any theme that works with 2.x... or the ability to turn the error message off.  (the old themes seem to be working fine for me, at least for now... the error those isn't ok)

Thanks

- json-editor version: 2.0

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by pmk65** [comment]
See #450 and #573

**Comment by Lilwolf** [comment]
Thanks!
