### ISSUE TITLE
Using json-editor with angular and require

### ISSUE THREAD

**Issue by arvindkhadri** [json-editor/json-editor#61]
I have an angular app and want to use json-editor along with it. I am using require.js to load my dependencies, how can I do the same with json-editor? Is it possible to do this?

**Comment by mauryashashi** [comment]
You can use angular directive for embedding editor and in define function first load editor file.

**Comment by arvindkhadri** [comment]
@mauryashashi Thanks, that was helpful. But I am looking for help with loading the dependencies of json-editor.js, is there a bundled file that I should be using to load json-editor?

**Comment by mauryashashi** [comment]
Except css files, you can load all the JS dependencies in define argument. That will make sure that all dependencies would be available before initializing editor in custom directive. You can bundled them in one file but I think it would be not simple to bundle dependencies using require.

define(
['jsoneditor','other files path'], function () {
angular.module('directives').
directive('schemaeditor',
function () {
//embed, initialize editor here
}
)
}
)
