### ISSUE TITLE
Suggested theme error changes

### ISSUE THREAD

**Issue by adambrakhane** [json-editor/json-editor#611]
#608 #450

# Question
Are we sure this error is working as expected? The only thing I have included on my page is the script as detailed in the "Using a CDN" section: `<script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js"></script>` and I still get this error. Even the demo linked in the readme displays the error: https://json-editor.github.io/json-editor/

# Suggested Changes
I understand I can just hide it, but it seems weird to have to hide an error that probably shouldn't be there to begin with. I would also suggest writing to the console instead of printing it out on the page. That way you get developers' attention but leave users alone.

**Comment by adambrakhane** [comment]
Actually, how do you even hide it with CSS? What selector would I use? It looks like it's just appended at the end of the div that contains the whole editor. How do I select that text without adjusting the editor?

**Comment by pmk65** [comment]
@adambrakhane Reason for this is that the new 2.x version introduced a lot of changes See #450 . We plan to reduce the number of available themes to the ones that are updated to 2.x format. 
Currently only Spectre, Tailwind and Bootstrap4 themes have been updated. (We need volunteers for updating other themes. See #573 ) 

Just add this to your CSS setup.
````css
div[data-schemaid="root"]::after {
  content: "Set to empty value to hide" !important;
}
````

Note: Any errors/problems using the old 1.x themes will not be fixed.

**Comment by pmk65** [comment]
> 
> I understand I can just hide it, but it seems weird to have to hide an error that probably shouldn't be there to begin with. I would also suggest writing to the console instead of printing it out on the page. That way you get developers' attention but leave users alone.

It is only displayed if you use one of the themes that haven't been updated. 
Using one of the old themes affects both users and developers. 
And if you really want to use one of the older themes you can help out by updating it to 2.x format 😉

**Comment by adambrakhane** [comment]
Interesting. I'm using the bootstrap4 theme: `JSONEditor.defaults.options.theme = 'bootstrap4';`

**Comment by pmk65** [comment]
@adambrakhane It's only the Bootstrap4 theme in the current build that have been updated (updated by @stroebjo ). 
(Still work in progress.)
The CDN version is only updated when we create a release.
