### ISSUE TITLE
Is there a way to input previously generated json data and have the editor populate the fields? 

### ISSUE THREAD

**Issue by DineshBhudia** [json-editor/json-editor#616]
I would like to know if there is any way to directly input json data and have the editor populate the fields so that the user can edit existing json data.

**Comment by WilliamsJack** [comment]
There are a few ways to do this. You could set the data when you create the editor using the option `startval` like so:
```js
var editor = new JSONEditor(element,{
  schema: schema,
  startval: myJsonObject
});
```

Or you can set it after creation using `setValue()`:
```js
editor.setValue(myJsonObject);
```

`myJsonObject` should be valid against the editor's schema.

**Comment by DineshBhudia** [comment]
Thanks for this, but can I  just ask where would I get the start value from? Where would I paste the json data for it to be read by the editor?

**Comment by pmk65** [comment]
I suggest you take a look at some of the examples or read the documentation.

**Comment by DineshBhudia** [comment]
ok I have now managed to wire the up editor so it can read the json data but it throws an error for the array items. Which says "Array must have unique items"?

This is my schema:

{
    "id": "bullet",
    "properties": {
        "bullet": {
            "title": "Bullet",
            "oneOf": [
                {
                    "title": "bullet text",
                    "properties": {
                        "text": {
                            "title": "Bullet text",
                            "description": "Enter text",
                            "type": "string"
                        }
                    }
                },
                {
                    "$ref": "image.json",
                    "title": "bullet image"
                }
            ],
            "properties": {
                "popup": {
                    "title": "Popup",
                    "$ref": "popup.json"
                }
            }
        }
    }
}

**Comment by niebert** [comment]
You can also load a JSON from the local file system with [`LoadFile4DOM`](https://www.gitlab.com/niehausbert/loadfile4dom) apply a `my_json = JSON.parse(my_loaded_file.json)` with try-catch and  set edtior `editor.setValue(my_json);`. This allows that uses can populated a web front end with the `jsoneditor` with there own data. See [LoadFile4DOM-examples](https://niehausbert.gitlab.io/loadfile4dom)

**Comment by niebert** [comment]
With `FileSaver.js` you can save the content with 
```javascript
var my_json = editor.getValue();
var str = JSON.stringify(my_json,null,4);
```
and let the user save the file with `FileSaver.js` by Eli Grey to the local filesystem (see [AppLSAC](https://en.wikiversity.org/wiki/AppLSAC)

**Comment by DineshBhudia** [comment]
I've managed to get this working now but the only problem is that when I try to populate the editor's  UI it changes my original structure and produces something different?

**Comment by pmk65** [comment]
@DineshBhudia Please provide a live working example at the [Playground](https://pmk65.github.io/jedemov2/dist/demo.html) if you want help. Without that it's impossible debug.

**Comment by DineshBhudia** [comment]
Ok Ive added the JSON schema [Playground](https://pmk65.github.io/jedemov2/dist/demo.html) to the link but I can't seem to upload the 3 pages that are loaded via ajax?

**Comment by pmk65** [comment]
The Playground page unfortunately doesn't allow uploading of additional files. 😢 (It's a GitHub page).
But you can clone the [Playground repository](https://github.com/pmk65/jedemov2) to create your own Playground page and then add the additional files.

**Comment by DineshBhudia** [comment]
Ok I think I have found out what the problem is. Basically if you try to edit the JSON data via the JSON edit btn and the changes require the loading of additional schema files via ajax then these call won't happen so it won't be able to populate the UI on the editor. I've tried removing the ajax calls and it seems to work ok.

**Comment by pmk65** [comment]
Why don't you just read data into the editor like @WilliamsJack suggested? That's the proper way to do it.

**Comment by DineshBhudia** [comment]
I did try but as there are schema pages being loading in via ajax it wouldn't read the json data properly.

**Comment by pmk65** [comment]
Wait for the "ready" event to fire before you load data into the form using AJAX, then it should work.

**Comment by DineshBhudia** [comment]
I did wait for the ready event before setting the value but as a test I just pasted all the JSON data into the data variable directly just to see if that would work but it didn't'. So is the issue that I didn't load the data via AJAX?

**Comment by pmk65** [comment]
It sounds more like your data doesn't match the schema layout. (Data has to be in same format as the output format)
Here's a simple example: https://is.gd/B58vUm

**Comment by DineshBhudia** [comment]
No it definitely is matching as I literally copied and pasted the JSON generated by the editor. I still feel it's a schema page loading issue. As there are several schema pages being loaded via AJAX I believe the AJAX call are not happening so the schema is not complete and therefore can't read the JSON. When I just use one page for the schema and don't load any in via AJAX it all works fine.

**Comment by germanbisurgi** [comment]
I think this question was answered long ago
