### ISSUE TITLE
Is there a way for a field to depend on a something outside the parent editor.

### ISSUE THREAD

**Issue by VasiliDarozhkin** [json-editor/json-editor#617]
Hello!

Right now I am able to set a dependency based on another field inside one editor.
Is there a way to set a dependency based on 
 - global state (for example window.some_variable)
 - another editor state (for example `editor_2.someField = 'value'`)
?

Thank you!

**Comment by pmk65** [comment]
There's no functions for doing something like that. AFIK.
But you could create a 'hack' solution. If you In `editor1` you have a field that when changed should change something in `editor2`.

1) In `editor2` add a hidden field with dependencies.
2) Add a change event to the field in `editor1` that when triggered, call `editor2` setValue to update the hidden field.

**Comment by VasiliDarozhkin** [comment]
@pmk65 Hm, you're right, it might do the trick 👍 
Thank you!

Should I close the issue?

**Comment by pmk65** [comment]
I looked at the editor properties, and it looks like it's possible to inject stuff into the editor `watchlist` property.
See example here (Turn on console in browser): https://is.gd/fs27LC

The `watchlist` is an object with the field as key (ie. "root.billing" and an array object containing the function(s) to execute. In the example I just inject a 2nd function into an existing watch field (1st one is the `registerDependencies` but this might not be needed if it's a different form it have to trigger. ) and then when the field is triggered it shows a message in console (this should be the action in the 2nd form)

**Comment by VasiliDarozhkin** [comment]
Cool, @pmk65, thanks a lot!
I will try these solutions today, then will comment which worked and close the issue

**Comment by VasiliDarozhkin** [comment]
So, all in all, I was able to get what I wanted by combination of 
 - watch
 - getEditor(key)
 - setValue
methods.
Everything worked pretty well, I just followed the examples Peter Klein provided

Thank you!
