### ISSUE TITLE
Unable to load Form for $ref values

### ISSUE THREAD

**Issue by faraazbh** [json-editor/json-editor#622]
### General information

Form is not loading for below schema with $ref values

Consider below JSON Schema:
`{
  "type": "object",
  "id": "urn:jsonschema:swift:drivers:nms:traffic:tunnels:core:complexParams:BidirectionalELSPCosParams",
  "properties": {
        "mainAcosParamsELSP": {
      "type": "array",
      "items": {
        "type": "object",
        "id": "urn:jsonschema:swift:drivers:nms:traffic:tunnels:core:complexParams:ELSPCosParams",
        "properties": {
          "hasValues": {
            "type": "boolean"
          },
          "cos": {
            "type": "string",
            "enum": [
              "COS0",
              "COS1",
              "COS2",
              "COS3",
              "COS4",
              "COS5",
              "COS6",
              "COS7"
            ],
            "default": ""
          },
          "bw": {
            "type": "number"
          },
          "isAvailable": {
            "type": "boolean"
          },
          "color": {
            "type": "string",
            "enum": [
              "GREEN",
              "YELLOW",
              "GREEN_AND_YELLOW"
            ],
            "default": ""
          },
          "eirMode": {
            "type": "string",
            "enum": [
              "Auto",
              "Manual"
            ],
            "default": ""
          },
          "eir": {
            "type": "integer"
          },
          "eirWeight": {
            "type": "integer"
          },
          "valid": {
            "type": "boolean"
          },
          "available": {
            "type": "boolean"
          },
          "bwValid": {
            "type": "boolean"
          }
        }
      }
    },
    "mainZcosParamsELSP": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#urn:jsonschema:swift:drivers:nms:traffic:tunnels:core:complexParams:ELSPCosParams"
      }
    },
    "protectionAcosParamsELSP": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#urn:jsonschema:swift:drivers:nms:traffic:tunnels:core:complexParams:ELSPCosParams"
      }
    },
    "protectionZcosParamsELSP": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#urn:jsonschema:swift:drivers:nms:traffic:tunnels:core:complexParams:ELSPCosParams"
      }
    }
  }
}`
- json-editor version: **2.0.0-alpha.0**  as well as **1.3.5** 

### Actual behavior
Form NOT loaded with properties for mainZcosParamsELSP,protectionAcosParamsELSP & protectionZcosParamsELSP
### Steps to reproduce the behavior
Copy paste above posted schema and click generate form
Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY4BLAE02wFcAnCDAgZxwk%2BIAtUAWwCGGTgHcaAM3gY6LGgDdULThghD18FiOnSaxDPCYQIqADbriOFqgw2hyC6gAeABRG6tGAEL0aO1IaHhELAFEAGQBldwBhHE5Pb04KKmxkFhw0FngaVFTgLHBoGDLqYFEaCABBGySvES0o2MYS8oqkNEY4L11ENNLy2nhhQuL0juwu9CLsfCJSQamK%2Bh7gVnYuHj5BUXEpWXlFFTUNHx09AyMTM0trW3tHZzdkpvUW%2BMS3rWWVuEy2VUeQKbUm%2F2A%2FBEnAAamEmKC5u0VsMEChZlg4HgcDgXCIIHBwVMAL6UIYQ%2Bpg8kouAzdacHTVADmfxRFVQECYQkYAG0iWy4HEAPLRAAMrLZFWF0QAjBLJYKRQAmeUC4DSgDMqpp6pFABZtRDpQBWQ1TRXRABsZo6FoA7ITqSsALpkyUVOioaQiJgWMhzQnAfnlUnBspYiRU93TdHrTlCPCqR2S0NO1E0Tg1JQiGgWER4FxR9202MB4DY3GofHJtmphXAGwWWxF%2Bt0ssMxQQFnAN3F4Acrm8sPm4AAcQASuFwgA5G2ogCaUUiQoA6nPw2PJzOAPo1acAEW3i8iy7XQbTHVdw43nu9vv9mKD55TvZ1qECAFkcJ6W2q24%2BO2Zdc4AHbk5j5C8RxqJh4BwdcKg%2FfEmDCGtJSvSCby9H0%2FXWVCVjrNV3xYX8dX%2FbBqlGJkk2fWtXwhIiV3fJl%2BAfKBkVbUtHwo1AqOImiUQInVswsNYkWvTpOOwCs8QJfj8LokcRGzXN80LMSMIk7oy2kqtZOvQSITwCQ4REhh1OjEstMfHTqzkkkw2JflHPJAy4CqCAAC16h%2BThPhImMrOwPoRAGHt%2BRGMZ%2FM0jF5kIEh%2FQUjcABI7GkdYAGJNg4bheAEYQxEkGQ5AUZRVHUTRtF0fRDGMUxzCsBxHkapwXA8RofE%2BBIGhSPCYGckM6IBLJRmCHg6m%2BdrfJidx%2FMsmLehYfpVQi35zIhMi4AWeLDTgFKvQyrLtlyvYCsOYqTjK85KquGrbnqh47Gal42pSDBOomnq7Kgfqylc4BARGvIeC8j73j8tbUQ24BgtCxKVvGNiwzm9YtqWMKL121KDrYbKdjy%2FZCqOErTnKi4quuWq7gamxHueVqfLe6aup83rvvBH7nOJYAgA%3D%3D%3D&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgKrIucSymEBOwByXgZ2C%2B2ESRxxrHOkgG8rcGTjlozSZmyuQOOC%2BxRa5Uq1VquHqoUisRObSQHS6PX6g2Go3GbEmMzmOEWJxWbHWwC2OyYzH2hRwAF8CsAgA%3D%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=1&ajaxCredentials=1&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1

**Comment by pmk65** [comment]
@faraazbh Your direct link provided doesn't work. It just shows the main page of the shorturl service.
Also you haven't provided a version number which makes it hard to determine which version you are using and/or if the problem already have been solved.

**Comment by faraazbh** [comment]
@pmk65 I've updated the link. Also you can copy paste the schema i've provided, form isn't generated for all the properties. Problem is reproduced on version **2.0.0-alpha.0**  as well as **1.3.5**

**Comment by pmk65** [comment]
It might be related to #8

**Comment by faraazbh** [comment]
I went over those issues, it doesn't look related. I've seen problems with form generation when references are involved. Basically most of the time, the form doesn't generate at all when there are $ref attributes in a schema

**Comment by pmk65** [comment]
@faraazbh I think I know why as I ran into a similar problem a while ago.
The "id" property doesn't seem to work as described in the specs but is only used to set "data-schemaid" on the property.

You can get the `$ref` attribute to work if you restructure you schema a bit and use `definitions`.
This [example](https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY54BLeAG3WCzgGU1SAnVKAFQAWqALa8AMgENEOAK7x%2BqAM7yAwhMXNK0bMi440XOksxRw26sGLrUtCADMcJszBfYkaE3FsOKVV2%2FomT2BJaTkoeCV5Kw1FX3MXOAATJWIuWmQ6HAhgwVpFCKiY3gB3dShhCRSInCghBmQoNNQJSKgcLigZZCTW3nghUQKHToApNgB5ADkAWgBRJPoOqAAmADoADygAN1QuRVpstagASXlFARwSgoHeCW2JWgYJPCYoZQkIXq4kqFQmUQQeAFEr0ARQCQMBhQRaKZDPRAvN76LIQAqoCBI1BJcjvGTEcHlFKKNIZVEQr5Qbw4PioDbwY6CXh4OTwbKKAD0GiYpAh8luNUaODsESEUBGwnel2udSuNRqAHMFW8HulZDdBrw4SRaHZaMR2plDmi1gAePBcAB85qtUxwkSwJxFYS6GlF%2BSgoIGot4AEZNjs9gdsrjFDhRO0RQK9f8kgVhLQFQJ5BB7VA8LxYfCpNimh0eKQGIg1nA%2FDAAL5aVxwD5fCQ%2FYq%2BpxlxIIFDMVi4QgkMjAKv%2BOAAEh4dmCAGIOSk9RB6MbObXvklG6WEpWWzX4J9F8UVs2EhZ3B3sPgiKR4v5sMPUKOWNgJ1PbLP2VzN3WG9Zd8AW2uEnB61wpGKPcLxodtghPHtzwHYArxvTt72vR9UU5f9AOsFdXB%2FatgFQxBik3PA4lvZxoMPcDuzPPsWwsWDx0nRCZ2QjlcPwl4iO%2FfsLBY6wCOUfRgNIsDbzgCDKM41taOE4AEOnJ80WYrgALwni2LZZAMJcLDW24jQCKCYjqLcITO1E3txJokc6IfRi5wUpTWNeZgOPXLtT3gICDP3IyPCk0yoOwyT4Po2SmNMjznN%2FVye2KBV0iSATsLI3yKLMwyh0sqSZKQ2ywusWLaHir9V3EkSUpiuLlHSSisBIxLjOPFL%2FIkjKgusuTOVyjR8rjeAqt7CLsM6kg%2BgVDpaGMTyQLbHyTMaqivPS68rIY9qOSGqxIlG9IJu%2FPwtOSFbkIS7AF3rJdrCbSbSMCI84BOCBkHCGMGDjT0wRhVJ0iNbIKV%2BalaXpP5MUcpIS3mqbdH0PYjCImrDIsSrbAVWxHt7OGvLqmaTt6pGmqmuhGFu4A2BxiAFSpB6nvGl63u9YlSW%2B6AtwphwAdSjHW3pr7UWCEn0jJinUfFanfi9cEubJY1fpZmk6QZPHoJROdjovCx%2Frl3IBA9Z6%2FoKBUMT2PpfjwRB3i4YgOWxJZ9hffmFTWAgiPM1W4G6gB9YgcAYGRhDREwADZnamlG5AAQXgHGWUiWHTHhl3gGzYhUEuF69mCDFIk6CRCnpDTVc0uOKzjrSpogH2M351GVcErG4DL4QK4VxKbuCKZy72QWqdjWnxc%2ByWfuZ9Xc%2FB%2FPsAlxnW%2FbzoQ%2FkHWe4%2Bklualwf7Fl%2BkwaD1slfZavg9XtnNe1kWqT1g2AMiY3TcUc3LcWNkbfriuHadwvW3dz3vd9mPA9ftXKfgcOkc5ATXRqPaCidk5exSFwdOQIO7Z0fmnIqYCi4c1QfnEu0FbCbT2DPXerYkqdmwagfWMCR75xoC3KS90cHT3%2FsLbuYsF4M3JCvVmGtyHx3HjzKSbNO6z2Pkw7hy9KRD3lpwqa28%2FZXTAV4feHDOx5GGMfD0%2BsICGwvumK%2BN8rb305MQ0hz8m7QXfl7H20isA%2FzQa2GegD0hRxAbHax2EIEp2gbAzOEIKa0KgIgshv8oDllfkEjmmDsIATJjYf%2B%2BCDz1TkbQ4xFgJStGCBE%2FWiSAiE2CAAJU%2BPrfhDCaZCL7ozaWYioAAAoaEkL2AASgyQdRe%2FcchSVyZEgpc9ilNNKWwteDJKnVNIfUiRitGYx1qqPOR7Dh6KK1so7uqiz5Gy0WbC2uiOj6LgYYx2GSLCmM%2FhYqA%2FtgnF03jQOW9YWh4JkfHQh2M7YNOAMktGbgLk8AkI8gm%2BlFFvJaB0wR71hED1EfI4em8LBApaT8%2Bklzs4z0KaLQFJTWEgumeI8Fx4xkxJsaCl5cAlEIpPlANRGjcwm1Wbfa285Sb2x2SMqa%2BzzEx19CsDFf9UZ2NoA48ZASLCuKgUgzsGd4E536s4wJJzQlnOAHgHAXsWgQAJCQAA1rKjY2LQK1xlXKpgnxHnPOCEq4gqqcDqvpQQqhnYABCOqFVNCEMatV%2FzGFIu6Siv6uLHmQuCDa%2BVnx7UqqdfCzprqWEiI9Wijer8Dp2AkDIBgLzeoyFQBikSWKbkUOAGIw%2B8yaaLPUefMl2i1l3w2RyI1JqNhGPNdhRlX8A6SowdK7kkEM01yJojMmnzLXYDYP8HszqimhqXsCiNfSvXIuNLzftvJg0ArppO0dMs2ZRusXADEPsTAAG0AlwEumy7An4D1wAAMx51VgAXVTbgdNoCUHrvrm7L5jid3iosAAMVoPsdmKDWx9s9l8XZrY8g%2FHPfnK9u6s2et4XMwl%2BbSWXwpesm2LbSDVuPcAOthzjnWJCU2uOcAAKLEcG2zGHaaX6o6JUPFwAiOHG7Vk1pVRDiDsRQut14bl0cOvd6pjxHWPz0hWU6D16N3CG3ZB7J2IgNwAAOI8AxDJ4AVrvZOWsRBtdN6jqkawdB2ZR8FmnwLcs8l18S1Uo5HRnA6HINYe%2Fo21WYTWzCHjXQVDLyJn4ziThRSUhKNcGo8EdzjyZAzgAI7JrOCIGOSaU3RoQD2uAABZVz%2BQZ3yDnS69jYal3lJmOKKjrQsDBZrWPRdULsApYTWlnkGX6EhuyyOpmqK%2BnHHy884r6XHn0Gi9i2JWrO0KiU2JiTb7sCypekBtWm4GD6imydSoUIrDIHYuKi9wTr1SJ5eKqZ46YMGbzUZhDKyzOUr0RyFz1X3M2Z25huKHszH1tvDhsBeHHPSsu259LFa1UaumkTXC%2FnAtSR%2B6akL4XIuRGEDFrgybr3PuCFVr7tWBNdJy81sdfD2uFfgFgUHZqePlcR6l9zqPh3NOE5GqA2OAtFYDY6sHpWvBQ%2B27%2BzV5GHmlYsCN28r7f0WAm4VA903IRza562RQi2GDLdW7%2B9buHNu3qcWzqDaKc1waO4WxDp3kOck%2BzVnsN2Vd2Ybbh05BGZWsmyH9u5cAo5shafDxLymreO%2Fi7x61rvBPlcp61x5W2%2BvYGzft3NutiVLM0aZnRpabb26OHSjDJvnsOYvG9zCA0Jevm3B%2Baui04J3mCtlZ8p13waH3WlBLjHOz3SFjrEE5PGa4nKczT2whkASF5BiLEoMFZwEhgYGG%2BCNx22uXezNAedPYVb%2B36qERYfoDN1Ki3fjR%2FK8mVp5Wk%2FWzT474m%2BfKf%2FBOb%2FrQ1fnnRnabH%2Bvnfs%2FYsH8wtKtJUSq5b7TRftfsjLDhhn3v5Nd%2FNLSsiBhXeVP3iwn0v0zWvx%2FwX1e3Nw5jt1tU%2BHxz%2BzAPfyvy%2F13xMFv0X3wzgOABK3APP03wIKmkgMwP32wPewtys2QKVzPxIPQJv3IJgKX1wP13wNQMkVoMg1INvCwOYJwMzTYO%2BwdUrRoLfzoOgh4KwD4NHjT0P2lTjwqwkIsBQOUO3wYKgL%2F3QUPwzy4l82Ug0Fz0r2%2BWwFDn0N7wTj0AH3GlZ3jlwmjg83i1tx8yUgYxMLgBUC9g2QnVjVc1GxVykyF0g3k1QEU3FzgBU1%2F2QVHg0w%2Fx62h0D3ZyCwo2iIwWLkMjkMwT%2FH0IclsObir1MP0Png6wiDYgsMCgLzaiYh0k0Ar372hhsKHxcKkAcL%2BwNSkl4jAwLi8kyJKmaIMNQF4jUiMIRykjMKUmKJx2kLYhmGGJGTz2WhClshqIsPqMMEaJ02yKUlaJfyeRx2CF4lmP4lSJ0J6N0OwBqL0iPDP0oQKLgHGKkEmNp1x1KMcnKJakqMOmWJyPQnmMsKhnWMcQkK2JaKiDaP2I6KxC6O0PT2KhciGhGOdwmDmmdj7ysIaKBIt1Mh2OIIIW8z8iZ2MKJmRLcigH7xfk0zWMHy3wPCiEulxK8wGxSICSP1IiiE%2FAZPbWCD8WhPkMgwcLPRpLxK1QMSQRZK0IlTOLhMiiGm6iMIqLgCyhsmfARL%2BNGM7BJIHRKGOBKLlL%2BKpI2NxNKjchxI4OgnaM7D1PSKlPv3hLKjygqhxlnxuKJOCE1N5G1IK2eKwG6hmERjEgrwVOkkL2VPklVNRP%2BOsMxNwOxLBN2ItOwF9P9LFTSJtP%2FztLcmKA2hITGmjPxiRJSk9B1KmKaBGlzIpIhnRMBLyMVhSlNLUKSOSjciBxSRBzLO2grPX1UMg1hCxAeyhAkBWyPFiww17Mcjdl0Tdkdmt14Pn1HPyD7INMcRHO4I0LIN%2FwV3iyXJrIgNaHpLNMzWcIJOF0yXcOADUE2g6FNnLzG1fyIIPPXzHKYH7OeCHPXLizGwhQXPHMnOnIqxXM%2FLHm%2FOfO3PfJPIsCkLnw3P50CRPLRIBOpM5KmkG0D0ZI51xhON%2FTkP4JQVZKn1aA5IfLQvImbPFwPGdwvJzK4FNiPV5UxXELoq%2FMUD7I%2FlfMMNnLh0YqAuYp%2FLvinLDH%2FLnK4uSGAtQDdlAo4ugP5zwvASrMQqIvjh5KFOIqkiUq4uwtkJZIww2kFKQuFKJmPLotuLPMoq2lNkFLgsjIxJ3PvSgwSWUq5KklFP8UAo0tTKwolI0syL2kgHLGACAA%3D%3D%3D&value=ETI%3D&code=EQehHcEsDsBMHtwDoBSBlA8gOQKK0gC7wBOSsApgGYCGArgDYEDOSBAFuQLbktMAO5AMYFi5JH2LwiBAJ4Ck8PgUjxoLfE2oAjeuQD67LvuIMeAAgC8ZkbXIBuADrQnTsGYAqHM5Xj16iGABzM3oYc2pRM05qOGoiYhkzGNgzUWoEaHoZJDMATXhaM0EYpNgUwVomIk4i%2BAokrXgAN3IkuDMtcn9kJ0hKMwAKACsmcnx4sxgqmMFyeH6oOERUTFxxkgBKMxGxwhIyHhF4GQGNx2gd9eJLM2hycDNFhGR0bDw94gGECu5oAiQAI62BJoLpCeIDBzAADEI1UAFpdvF4T5iJwoRsADTbMZxahnFzQJoRVLkdIyAASyV01yslFo0GEKmgpzMAG9CWYuWZidcUlZvrRfgRsVpaAQiNA9GxfBRadtRlckJIpKwONwkIFyAQKWS5QAhcWSimy8ifAnOaDcnkkwRpAjkQ0S1Q3emM5SqAYOgAeIqK1D8WmoggA1lsOVbrTbrmLnVarJcPsr4KqtQQnZKveRfdiAOS57E%2BggWqMdI2qJBVGS6JDRb0AdUgsHYN1zAHZRJxc%2BdS7HJdLTaRqHwBHAAMJsSD0WADPuqEtRudSmXTs2V2Q1jR8ejURJWXOUXTe7tOXvl6BIdKwHAtP4AGUgVXId0%2BucEoVDBf9geDIexNHoUYF2tRN4mTVUOHSNc%2BAiZ8CCwOoxCmM10yoEhyFnc8B1XYhsVA%2FYVX%2BSC5SQO5fTQSAdCCYCzAAXx7bleSKe1yFBXRhFdBkmU9RQPTUbFih%2FUNw1PKMmNGegbnw0hCLVIxNW1NjwQASWgPhxQGaAGHof8AyAhjrQkpB32oJgmAfKpLzKAZcwk8F4SYLtMVzWB4RgUI7gLXNOGIeEACYv28mR4QARlzGiuSMqsazrRtmzYVsOy4E9IxAxUk1kwwNVGAglOEDAlGZJgBgk7EMC0IZwSQYl6FsYreKKrEzHKyrhCQENyBkerCtUJgNgiswjKvG84Ish0XxswQ2BiLUv0E%2Bgg1DXTAPIAal2wkjh1HWAJynGcJIG6TwKIvVoNgv4EIoJBkOIVDUQw9aVzlPD0rA2TiLXMjcsojzAho%2BjRK5JjRDtMkHXeCY6S4vjWQjUs%2BkGaTJjUAgZjmBYYGeFY3iuLYjooKpJBOQ7XpIG47geJ5lleNYPi%2BeAfjgwFgRkPKIShWEmARJESBREh0WAJrKtgPESZ50hPVzNJYBkL83W4lkRNSqNpcpakzVOAzuVo%2F6tcB5iwdYsFhAGOGo1zVT1IIQbIAAL3IXMAC5bm0zF9a5XMELRAMnbMXNoH5n23eVj20GiPxfds8P6ALd2%2FbvCJZud3Md2IWb9do%2F9oeZAZVvZOOEdz1hE%2B1aqA1sLYqZeVYIf2CgaAYZg5O4XgBGEURxEkaQ5DEBreuutTxT0Jg7daKwxFRtPS5q2wta5EGWNr80tZ1859dBuJHXPGyE86ST9VlOXs89POzetKvsdpsD67oRgWCynhKzbkQxAkKQpB7hQerUJAdz3vRGjThuAAQgvjTJeBwG532bo%2Ffg4IO5v27vIPuP8%2F5dAAbKOepIN7gyuJrDOFp14sQzJLAAgqEQIVoD7Oict4Y%2BLJT5xzATXJUN9G733VLA5%2BCCu4f2Qd%2FFgAZICUIwTQkBzCcZJjYdAh%2Brd4Gv14bIfhfFBEUKlI0GhWCF6GyXvg5Wq99ZEMNiQlkuYWrgjMAfYgcoj7uhzowkOjxMbUxYVIqgt8m6yKfvIzu78lG9wEQoCq4IMHWLNOI5x1dJHX3cewmBcj24KL8Z%2FFBLB4DBOEKEuUWihCLzwf9GiRjN4mJsuYjiqkKB%2FFsQrXOStSwSKvnXWJMjOEJJfr4pBASVFBNagQPQmM4IRKWFExppBpGeNad4xJHS%2BFdKKj0kJAy%2Fg5JweQXRBS9bK1WSU3M7htC6EsSQGxWc7EnzqVGBpEDxkcKMG0nhyTlHzNRjofQjQwnylAZEy%2BVzmkTNuVM9piDZlf26c83QWSzQrLyXTDZhitnEO3rs%2FZrQABa5AtDEFMhuB2JyakOPqV88BrDfk3JbgC%2B5nSQVPORXoe2GKsXVjHmYT5wzvnEqgX8slcDplAv8VS%2FuYL9B0sxdFewcdtGb3WSvBcnIzBOABpaI6ktVbVJhuc1WVI4A0j0avYAQA%3D&style=ETI%3D&theme=spectre&iconlib=fontawesome5&object_layout=normal&template=default&show_errors=interaction&required_by_default=0&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1) uses the `definitions` and `$ref` properties.

**Comment by faraazbh** [comment]
Currently, I'm using Jackson jars to automatically generate Schema from Java POJO directly. Need to see if changing the schema generation to include `definitions `  is possible or not

**Comment by pmk65** [comment]
What JSON Schema versions does your generator create?
JSON-Editor only supports v3 & v4.

**Comment by faraazbh** [comment]
v3

**Comment by robocoder** [comment]
#8 proposes to not ajax load anything that looks like a URN, i.e., starts with "urn:".

"id" changed to "$id" in v4. Since the README claims to fully support v3 and v4, the schema loader should handle both.

The spec says "$ref" is a URI -- so that includes both URLs and URNs. If the schema loader comes across a URN that it hasn't seen, it might be nice to support an optional callback to resolve it.

Note: in the above schema, the URI isn't a proper URN, i.e., it starts with "#urn:".

**Comment by robocoder** [comment]
Fixed by #933
