### ISSUE TITLE
sceditor-integration does not work (or docs outdated?)

### ISSUE THREAD

**Issue by coderofsalvation** [json-editor/json-editor#624]
### General information

- json-editor version: latest (2.0.0-alpha)

### Expected behavior

the README.md mentions sceditor-usage like so:

```
{
  "type":"string",
  "format":"html",
  "options":{
    "wysiwyg":true
  }
}
```

### Actual behavior

The default textarea appears.

### Steps to reproduce the behavior

Direct link to example: https://is.gd/iUU405

```javascript
{
  "type":"string",
  "format":"html",
  "options":{
    "wysiwyg":true
  }
}
```

**Comment by pmk65** [comment]
There have been some changes in how the editors are configured. Check UPGRADING.md and README_ADDON.md
You are also welcome to submit a PR to update the info in README.md.

**Comment by pmk65** [comment]
Fixed
