### ISSUE TITLE
this is an old json-editor 1.x theme and might not display elements correctly when used with 2.x version 

### ISSUE THREAD

**Issue by kunalraj89** [json-editor/json-editor#625]
### General information

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by pmk65** [comment]
See https://github.com/json-editor/json-editor/issues/611#issuecomment-549598478 on how to hide the notice. (Or use one of the 2.x themes)

Note: The 1.x themes will be probably be removed in next release if there's no volunteers to update them. Also we will/can not fix any bugs related to the 1.x themes,

**Comment by pmk65** [comment]
FYI: The 1.x themes WILL be removed in the 2.0.0-beta release since no one have showed interest in updating those.
