### ISSUE TITLE
Vanilla Picker - thumb nail shows rgb number, not the color

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#626]
### General information
Not sure if this is the only option.  Based on their website, there are some additional options...  But this seems to be controlled from json-editor.

But currently the color displays text "#000000" instead of showing the color square in black.

Is there an option to select the other?  

NOTE:  I'm using Spectre theme.  I believe that theme normally would display the colors if vanilla picker isn't used... but I'm working in JCEF which doesn't have a default color picker so I can't use it.

imports are

  <script src="jsoneditor.js"></script>
  <script src="vanilla-picker.min.js"></script>
  <link rel='stylesheet' href='spectre-exp.min.css'>
  <link rel='stylesheet' href='spectre-icons.min.css'>
  <link rel='stylesheet' href='spectre.min.css'>

Thanks - Adding image of what the vanilla picker looks like.   Wandering if we can get the default not to show #0000ff in this case, but the color box that the normal color chooser does.

![image](https://user-images.githubusercontent.com/8716166/70270404-55b72d00-1772-11ea-8c11-4a2540760c88.png)

- json-editor version: built 2 weeks ago from the latest branch.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "type": "object",
  "properties": {
              "test":              {
                            "format": "color",
                            "title": "Color",
                            "type": "string"
                          }
  }
}
```

**Comment by pmk65** [comment]
Provide either a link to a working example or paste in your schema code. The ones you posted doesn't make any sense regarding your question.

**Comment by Lilwolf** [comment]
I've updated the request.  Since the question wasn't really about json... but the optional vanilla color picker, it didn't seem as useful.

**Comment by pmk65** [comment]
I think the colored box is rendered by the browser if the input type="color", which is probably why you don't see it if JCEF  doesn't support that type.
But you could use the VanillaPicker colorCallback() function to render your own custom colored square next to the input field.

**Comment by Lilwolf** [comment]
This is new since 2.0 right?  Is there any examples of how to implement something like this?  (I'm pretty new to 2.0 stuff (was new to 1.x too... but... really new to 2.0).  I haven't found where the documentation / examples are for the new stuff.

**Comment by Lilwolf** [comment]
wait... type="color" isn't standard.  type="string" format="color" has been the default.  Has this changed???  Let me try and see!

**Comment by pmk65** [comment]
I looked at the colorpicker editor, and the `onChange` function is hardcoded, so it doesn't look like you can override it.

**Comment by Lilwolf** [comment]
Thanks!  I'll give it a try!

**Comment by germanbisurgi** [comment]
question answered
