### ISSUE TITLE
Nested arrays of objects with differents definitions

### ISSUE THREAD

**Issue by RenaudRabier** [json-editor/json-editor#627]
### General information

Hi there.

I've been trying to do it for some days now and I'm on the edge of giving up.

I try to add multiple items (object) with differents definitions in a array, but it seems that the describedBy function only works for the first item of the array.

Maybe I just don't understand how it's supposed to works.

- json-editor version: 
@version "2.0.0-alpha.0"

### Expected behavior

Let's say you have a first array of items : "PANELS", with an enum "PANEL1", "PANEL2", "PANEL3" etc...

Each panel is linked with a list of possibles OPTIONS.

Each OPTION is linked with a list of possible VALUES.

In the end I should be able to get an output like this:

```

{
    "PANELS": [
        {
            "panel": "PANEL_1",
            "values": [
                {
                    "name": "OPTION1",
                    "value": "OFF"
                },
                {
                    "name": "OPTION2",
                    "value": "OFF"
                }
            ]
        },
        {
            "panel": "PANEL_2",
            "values": [
                {
                    "name": "OPTION_3",
                    "value": "CLOSE"
                },
                {
                    "name": "OPTION_4",
                    "value": "LEFT"
                }
            ]
        }
    ]
}
```

### Actual behavior

Only the first item in array correctly load definitions and update form accordingly.

### Steps to reproduce the behavior

Direct link to example: 
http://tiny.cc/35pfhz

Add 1 Panel
You should have an enum list with "PANEL_1", "PANEL_2", ""PANEL_3". 
Add 1 Option
You should have 2 enum list:
One for the option name  (with "OPTION_1" selected)
One for the value corresponding the option  ("ON" selected)

And then 2 problems occurs:

1 - If you add a new option item, only the name enum is populated, the value field doesn't update with the associated enum list.

Only the first option item is working at this point.

2 - If you add a new Panel item, set it to "Panel_2", and then add a new Option item, the option item shows "null" instead of 2 enum list "name" and "value".

If it's not an Issue but just me that doesn't use the libs correctly, forget about it. 

But in this case I would really appreciate if anyone could explain me how (and if) I can do what I'm trying to do.

(I want to say that my original schema is using an "allOf" array of "if"/"else" to get correct auto-completion, and it's working nicely).

Thanks for your job and your time.

**Comment by pmk65** [comment]
There have been some fixes for the `DescribedBy` editor lately. Try creating a custom library using the current Github branch.
Your schema is working for me using current Github branch.

**Comment by RenaudRabier** [comment]
It works with current rev, thanks you!

However, the validation (uniqueItems / minLength / required ...)  doesn't works correctly on nested items.

For example I want to be sure that a value is defined (from an enum) for any added option (required) but the select still have an empty option.

Maybe i can remove this line with a watcher, I will try.

But I can deal with it anyway, it's not a big problem, just saying.

Thank you again for your help.
