### ISSUE TITLE
How to use in Create-React-App Project?

### ISSUE THREAD

**Issue by bishoymelek-zz** [json-editor/json-editor#628]
Any docs about how to use the package in Create-React-App?

I am getting an error that JSONEditor is not a constructor.

Thank you

**Comment by pmk65** [comment]
Maybe related to #578

**Comment by germanbisurgi** [comment]
import JSONEditor and use it like normally

```
import { JSONEditor } from '@json-editor/json-editor/dist/jsoneditor.js'

new JSONEditor(containerElement, {
    ...options
})
```
