### ISSUE TITLE
Can default error messages be changed in JSON Schema?

### ISSUE THREAD

**Issue by mattferderer** [json-editor/json-editor#631]
I'm wondering if it's possible to use a custom error message specified in the schema instead of a default JSON Editor message.

My specific example is that I have a list of states in an array being used on a select list. 

Instead of saying "Value must be one of the enumerated values." I would rather it say "Please select a state."

**Comment by pmk65** [comment]
A while ago I added support for custom error messages. But I think it was only for regex based messages.

**Comment by schmunk42** [comment]
I splitted some of the opt-in tests to see which part triggers the problem https://github.com/json-editor/json-editor/tree/feature/hardening-tests-191211

Locally it works, so it might be some weird timing issue.

@pmk65 Does it also work with puppeteer? Also this commit https://github.com/json-editor/json-editor/pull/623 passed in PR state but fails now on master.

**Comment by pmk65** [comment]
You can override the messages **globally**, but not for a single schema property.
````javascript
JSONEditor.defaults.languages.en.error_enum = "Please select a state."
````

**Comment by mattferderer** [comment]
Thanks @pmk65. I did notice the global setting but that would cause confusing for select lists that don't deal with states. I also think our end users would squint in confusion at the phrase "enumerated values".

**Comment by pmk65** [comment]
@mattferderer I'm not a fan of the current error messages either. So if you have some better text for the messages, feel free to create a PR.
The problem is that a property can trigger several different error/messages. So it's not just a single error message you can override.

**Comment by mattferderer** [comment]
Just an update FYI.

I happen to be using this with .NET & already have their jQuery Unobtrusive validation included.

For my specific situation, I'm just adding the following to my schema:

```json
          "options": {
            "inputAttributes": {
              "data-rule-required": "true",
              "data-msg-required": "Name is required.",
              "data-rule-maxlength": "80",
              "data-msg-maxlength": "Max of 80 characters."
            }
          }
```

Then I append an element like this after each input:

```js
    function CreateUnobtrusiveValidationElement(name) {
        var element = document.createElement('span');
        element.classList.add('text-danger');
        element.classList.add('field-validation-valid');
        element.setAttribute('data-valmsg-for', name);
        element.setAttribute('data-valmsg-replace', "true");
        return element;
    }
```

So far, with limited testing, this seems to work well with JSON Editor. I've turned JSON Editor errors off & just rely on this for validation.
