### ISSUE TITLE
Optimal display of nested array

### ISSUE THREAD

**Issue by snipercup** [json-editor/json-editor#634]
### General information
- json-editor version: latest

### Expected behavior
I'm trying to find the optimal display of a nested array where all the items have a definition. 
Ideally I would like to use grid so it shows body part and amount next to eachother on one line.

### Actual behavior
With this example a lot of whitespace is generated. I'd use tabs instead of table, but I would like to display the first item as the header otherwise it's just body parts 1, body parts 2 etc.

### Steps to reproduce the behavior
Here's the example:
https://is.gd/UN25BA

**Comment by pmk65** [comment]
@snipercup You can't use `"format": "grid"` on arrays. Arrays only support the formats "tabs", "tabs-top" and default.
But you are right about the whitespace problem which is caused by empty button holder elements. Part of it can be solved with some CSS rules.
````css
.btn-group:empty, .form-group + div:empty {
  display: none;
}
.form-group {
  margin: 0;
}
````

**Comment by snipercup** [comment]
Thank you for your reply. I will try using the css rules and infotext and compact and close this issue if this meets the requirements.

I don't want to use tabs, I thought table is supported by arrays too? I could use tabs maybe if the header would display the first child of the nested array.

I'm using spectre in my application, if you change the example I posted to spectre it produces the same results.

**Comment by pmk65** [comment]
Array support "table" format too, but not "grid". (I was looking at the Array.js source and forgot that Table.js extends Array.js)
In your example the "items" property is set to "format";"grid" and "type":"array" which won't work.

**Comment by snipercup** [comment]
The reason I went for grid is because when I used table for the 'items' property, it 'forgets' its schema: https://is.gd/QLUPDA

That link is using the spectre css i'm using in my application but the theme makes no difference. Actually using tabs for the 'items' property produces the same result as using 'grid' so I might go for that.

**Comment by snipercup** [comment]
I experimented with your suggestions and it has improved somewhat but there is still much whitespace: https://is.gd/NAhpvn

I'm not sure what to expect from infoText, it does not display the info I put in at all.

I want to keep this issue open because I don't think I've reached a solution yet, i'd like to have the body_part and the amount on one line and each row would have only the minimum of margin so it's compact.

If there's anything more I could try please let me know.

**Comment by pmk65** [comment]
> 
> I'm not sure what to expect from infoText, it does not display the info I put in at all.
> 
Looks like `infoText` can't be used if `compact=true` (but only for table layout)

From looking at the source output  of your example, it looks like there's a H4 tag (the one containing the buttons) placed wrongly. It's placed inside the TR tag, but not inside a TD tag.
This causes the huge whitespace gap after each array element.

**Comment by snipercup** [comment]
Thanks for helping. The CSS you provided makes it more compact so it's getting closer to what I want. However there's still the thing where I press new body part, it creates a empty div instead of the select box and input field I would expect. I can only work with a tabs format right now in combination with the duplicate item option since add does not work.

**Comment by snipercup** [comment]
This is what I wanted:
![image](https://user-images.githubusercontent.com/50166150/71730978-db96c880-2e43-11ea-8f40-e9112bfb0099.png)

It uses a couple of css style rules:

[data-schemapath='root.body_parts'] div.je-panel {
  display: inline-block;
}
[data-schemapath='root.body_parts'] div.je-panel, td {
  margin: 0 !important;
  padding: 0 !important;
}
[data-schemapath='root.body_parts'] .form-group {
  margin: 0;
}
[data-schemapath='root.body_parts'] .btn-group:empty, .form-group + div:empty {
  display: none;
}
[data-schemapath='root.body_parts'] tr h4 {
  display: none;
}

The schema:


        "body_parts": {
            "type": "array",
            "id": "/properties/body_parts",
            "title": "Body Parts",
            "format": "table",
            "options": {
                "disable_collapse": false,
                "disable_array_add": false,
                "disable_array_delete": false,
                "disable_array_reorder": true,
                "enable_array_copy": true,
                "disable_properties": false,
                "collapsed": false,
                "hidden": false
            },
            "items": {
                "headerTemplate": "Body Part {{i1}}",
                "type": "array",
                "id": "/properties/body_parts/oneof0",
                "title": "Body Part",
                "format": "tabs",
                "default": [ "HEAD", 2 ],
                "options": {
                    "disable_collapse": true,
                    "disable_array_add": true,
                    "disable_array_delete": true,
                    "disable_array_reorder": true,
                    "disable_properties": true,
                    "collapsed": false,
                    "hidden": false,
                    "compact": true,
                    "infoText": "the amount"
                },
                "items": [
                    {
                        "type": "string",
                        "id": "/properties/body_parts/items",
                        "title": "Body Part",
                        "default": "HEAD",
                        "options": {
                            "hidden": false,
                            "compact": true
                        },
                        "$ref": "#/definitions/body_parts_enum", 
                        "propertyOrder": 60
                    },
                    {
                        "type": "integer",
                        "id": "/properties/body_parts/items/oneof1",
                        "title": "Amount",
                        "default": 2,
                        "options": {
                            "hidden": false,
                            "compact": true, 
                            "infoText": "the amount"
                        }
                    }
                ]
            },
            "propertyOrder": 70
        }


Also, by entering 

                "default": [ "HEAD", 2 ],

into the array, the issue of the empty new item is also solved. I'm going to close this issue.
