### ISSUE TITLE
const values not working

### ISSUE THREAD

**Issue by i5heu** [json-editor/json-editor#636]
### General information

- json-editor version: @version "2.0.0-alpha.0"

### Expected behavior
displayed value "bar"

### Actual behavior
all types in select

### Steps to reproduce the behavior
use json schema below

### Spec
https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "foo": {
      "const": "bar"
    }
  }
}
```

**Comment by schmunk42** [comment]
We currently only support up to JSON schema v4

**Comment by richturner** [comment]
@schmunk42 @robocoder Looks like this should be included in the latest release but `const` doesn't seem to work in the online demo which is running the latest version (`2.5.4`), do we need to do anything to enable this functionality?

**Comment by richturner** [comment]
Looking more closely what's been implemented is on the validation side; I would expect the UI not to render these `const` properties but I see a `type` dropdown and an input field:

```
"foo": {
    "const": "bar"
}
```

![image](https://user-images.githubusercontent.com/7072278/123313710-ad1e1900-d521-11eb-98c5-b57a89bc4b2b.png)

**Comment by robocoder** [comment]
it's a valdation; according to the spec
```
"foot": {
    "const": "bar"
}
```
is just shorthand for:
```
"foot": {
    "enum": ["bar"]
}
```

**Comment by richturner** [comment]
I can understand it being just for validation but I don't understand:

- Why it should then show in the editor UI
- Why the type can be changed
- Why the value can be changed

**Comment by robocoder** [comment]
Those are best answered by fleshing out your schema.

* If you don't want to show it in the editorm use the `hidden` option.
* To set the type, use `"type": "string"`.
* If you don't want the value to be changed, provide a default vaue and set the property to readonly.

Example:
```
"foot": {
   "type": "string",
    "enum": ["bar"],
   "options": {
     "hidden": true
  }
}

**Comment by richturner** [comment]
Thanks for the response, fairly new to JSON schema but I would have thought those options were implicit because of the nature of 'const'.

Anything other than the 'const' value would fail validation therefore there is nothing to specify/render but should be present in the generated data.

I'll take a look at using the 'hidden' option.
