### ISSUE TITLE
Release 2.0-beta-1

### ISSUE THREAD

**Issue by pmk65** [json-editor/json-editor#639]
ToDo before release:

1) Remove (comment out) inclusion of non-updated themes and iconlibs. #597 
2) Fix as many of the issues marked `Bug` 😉

**Comment by pmk65** [comment]
@marc7000 I would say it's ready for a release, now that #597 is merged.

**Comment by kameelyan** [comment]
Any idea when the next release would be? There's some theme changes with the AbstractTheme class I'm looking to use.

Thanks!

**Comment by marc7000** [comment]
Successfully published @json-editor/json-editor@2.0.0
