### ISSUE TITLE
Type enum with "value / label" pair on schema

### ISSUE THREAD

**Issue by sluc23** [json-editor/json-editor#64]
Enum could be set only with value = label, on select options.
Is there a way where schema could be set to get a different value than label to export on json?

**Comment by sluc23** [comment]
How this **enum_title** array has to be set if I'm working with several enum fields in the same editor?
Is there any online example of using it?

tx!

**Comment by schmunk42** [comment]
https://github.com/json-editor/json-editor/search?utf8=%E2%9C%93&q=enum_titles&type=
