### ISSUE TITLE
How do we create custom themes now with version 2.0

### ISSUE THREAD

**Issue by wsantos** [json-editor/json-editor#643]
### General information

How do I can create themes with the new 2.0.0 now that we don't have access to AbstractTheme ? Sorry the question here but I couldn't find any doc/wiki or issue explaining that.

**Comment by pmk65** [comment]
Doesn't this work?
````javascript
import { AbstractTheme } from '../theme'     
````

**Comment by wsantos** [comment]
That is how I'm doing basically but still receiving this error:

![image](https://user-images.githubusercontent.com/164633/71450011-2e3ff880-2751-11ea-90ce-b1c6b9651259.png)

My code: 
![image](https://user-images.githubusercontent.com/164633/71450033-8414a080-2751-11ea-814d-c1a9bb1379f5.png)

![image](https://user-images.githubusercontent.com/164633/71450034-8971eb00-2751-11ea-8c89-932d131cf16c.png)

**Comment by wsantos** [comment]
Here it's a jsfiddle with the same problem: https://jsfiddle.net/1omx7ufy/

**Comment by pmk65** [comment]
You also need to add your theme into `core.js`
First you need to input your theme.
````javascript
import { myTheme } from './themes/mytheme'  
````
And then in the `assignThemes` function, add your theme.
````javascript
  themes.mytheme = myTheme  
````

**Comment by wsantos** [comment]
So I need to have a builder in place ('webpack') to be able to create custom themes ? can't I just load jsoneditor from cdn and create my theme class anymore ?

**Comment by pmk65** [comment]
I have never tried adding custom themes that way.
From looking at `core.js`, the `AbstractTheme` function needs to be available outside `core.js`, which can be done in similar way the `AbstractEditor` function. (I'll make a patch)

Then you define/load your custom theme like this:
````javascript
var myTheme = JSONEditor.AbstractTheme.extend({
  // Custom Theme code here
})

JSONEditor.defaults.themes.mytheme = myTheme
````

**Comment by wsantos** [comment]
Thank you, I'll definitely do if I do improve anything, for this theme in particular is for an internal tool with custom styles, that's why, thanks for the patching it I really appreciate it.

**Comment by dornstein** [comment]
@pmk65 Thanks for that patch; I need it for the same use case.  I don't see it in the latest release, though.  Will there be a new release soon containing that?

**Comment by kameelyan** [comment]
Hey @pmk65, doing something similar here as well. Do you know when this will be released?
