### ISSUE TITLE
JSON editor not rendering (nodeType of null)

### ISSUE THREAD

**Issue by albydnc** [json-editor/json-editor#648]
- json-editor version: latest from CDN 2.0.0 alpha 1
JSON Schema is attached [schema8IO.txt](https://github.com/json-editor/json-editor/files/4073861/schema8IO.txt)
### Actual behavior
Editor not rendering. It is rendering fine with 2.0.0 alpha 0
```javascript
Uncaught TypeError: Cannot read property 'nodeType' of null
    at s (jsoneditor.min.js:17)
    at n (jsoneditor.min.js:17)
    at Array.map (<anonymous>)
    at n (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
    at r (jsoneditor.min.js:17)
```

**Comment by germanbisurgi** [comment]
it make sense to me, if its null its null and stop. But there is a case where it can be use. For example for inputs that can be multiple types:

something like [this](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC5ywM5hAGnATwA7yQHsAjAK1gGN0tcAnQ/WyVRUAWz3t1fCjkRAA3AIa0Iw4nAAEYPPCyEAdrADyAM0QBtULPwC0YxQHNMvGARAAhYSggUpABVi0USkAF8MOuQMUBXaGhTSHMBa1t7Jxc3dwBddwSgA&value=N4IgtgngDgTg9lEAuAdgVwDYYL5A&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default)?

**Comment by schmunk42** [comment]
I get these errors when validating agaginst v4 and v7

```
Required properties are missing from object: global, digital, analogInput, analogOutput, logic, pid, sms, network.
```

https://www.jsonschemavalidator.net/

But it seems, that's not the issue. Even, when removing the `required` section in top level, I get the same error for a valid schema.

@germanbisurgi Could you create a test with the schema provided (without "required" on top-level) and have another look.

**Comment by germanbisurgi** [comment]
The error message is caused by this line: 

<img width="769" alt="Bildschirmfoto 2020-02-14 um 11 36 00" src="https://user-images.githubusercontent.com/13135260/74523880-485eb180-4f1e-11ea-9c23-7b90303dab29.png">

**Comment by germanbisurgi** [comment]
#663 should fix the problem
