### ISSUE TITLE
Nullable fields input?

### ISSUE THREAD

**Issue by dornstein** [json-editor/json-editor#649]
Is there a way to cause blanks to be treated as null - at least for some fields?

I love this work and I'm trying to see if I can create a sufficiently usable form editing experience.  One of the things that feels awkward now is how optional fields are treated.  Take, for example, a nullable integer field.  The default editing experience for that appears to be a textbox into which the number can be typed and a dropdown that let's the user decide if the type should be "integer" or "null."  While I get what's going on there, I think many of my users will find this confusing.  They would expect a blank field to mean there's no value (i.e., null) and a number to mean it's got a value.  Is there any way to get this behavior out json-editor?

Of course, I'd really like something like this for other data types (e.g., nullable enums, strings, etc.), but I'm guessing if there is a way to handle the nullable enum case then I could generalize the pattern a bit for some of these other cases.

**Comment by germanbisurgi** [comment]
something like [this](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC5ywM5hAGnATwA7yQHsAjAK1gGN0tcAnQ/WyVRUAWz3t1fCjkRAA3AIa0Iw4nAAEYPPCyEAdrADyAM0QBtULPwC0YxQHNMvGARAAhYSggUpABVi0USkAF8MOuQMUBXaGhTSHMBa1t7Jxc3dwBddwSgA&value=N4IgtgngDgTg9lEAuAdgVwDYYL5A&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default)?

**Comment by dornstein** [comment]
Maybe I'm missing something.  Which field in that example allows blanks?

**Comment by germanbisurgi** [comment]
optional props? like [this](like this?)?

**Comment by jdwil** [comment]
@dornstein What did you wind up doing here? I thought it would be pretty straightforward to have an input that validates non-null values, but also allows nulls (without validation). Can't seem to find anything on it though...

**Comment by dornstein** [comment]
@jdwil I gave up.  I appreciated the example from @germanbisurgi but the usability of having a checkbox along with the input field jut isn't there for my users.  I hacked my way around it by processing empty strings like nulls in this specific case where this was an issue.  But having a more general solution for this in json-editor definitely prevents broader adoption for me.

**Comment by schmunk42** [comment]
Would `anyOf` work for you? https://stackoverflow.com/a/22588841

I think an integer can not be `null` according to JSON schema, or?

Closing, please reopen if needed.
