### ISSUE TITLE
Form not visible on Checked out project of interactive demo: https://json-editor.github.io/json-editor/

### ISSUE THREAD

**Issue by faraazbh** [json-editor/json-editor#653]
### General information
Suddenly, the form isn't visible . It's gone. completely
- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by schmunk42** [comment]
Because it is not `required` you need to use `show_opt_in`.

**Comment by schmunk42** [comment]
@pmk65 I have some issues with the demo pages.

https://json-editor.github.io/json-editor/ only applies (some) config changed, when moving with the cursor through the list.

Which is the `show_opt_in` entry in *options* here https://pmk65.github.io/jedemov2/dist/demo.html ?

**Comment by faraazbh** [comment]
@schmunk42 No I meant, the box where the form loads, that itself isn't visible on screen for any schema. 
problematic behaviour is observed in the project i've download and the online demo page. 
![image](https://user-images.githubusercontent.com/13655599/73723254-9c171100-474e-11ea-9e42-df77226d4833.png)

Issue not observed on this link demo https://pmk65.github.io/jedemov2/dist/demo.html
