### ISSUE TITLE
Unknown theme bootstrap3 in  interactive demo

### ISSUE THREAD

**Issue by mochi-c** [json-editor/json-editor#654]
![image](https://user-images.githubusercontent.com/36881499/73738230-1069a880-477f-11ea-94e8-40585f289e23.png)

**Comment by schmunk42** [comment]
They are no longer available in v2

**Comment by c0bra** [comment]
Seems like none of the demos are working for this reason. Unfortunately that makes it hard to check this library out properly.

**Comment by germanbisurgi** [comment]
Thanks c0bra, we fixed this in #660
