### ISSUE TITLE
String or Function?

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#655]
I don't believe this is currently possible (currently hacking it)...
But what I would love to see is being able to add a new type (lets call it function)...  So a field can be a string, or a function (selectable at runtime)...  
If it's 'string' and someone types in 'fred' the output is 
  "field":"fred".
if it's 'function' and someone types 'fred' the output is 
  "field":fred

The reason for this is to allow a function to be added 
  "fred": (function(value){return value*10})
Currently I'm checking to see if the string 'function' is part of the string, and removing the quotes... but this has some issue if someone has a string of 'function' in a string, we don't handle it.  

Is there a way to do this currently?
Thanks!

**Comment by schmunk42** [comment]
How about watchers? https://github.com/json-editor/json-editor#listen-for-changes

**Comment by Lilwolf** [comment]
I'm not sure if that would work.  I want the end user to be able to switch between them..
like
        "type": [
          "function",
          "string"
        ]
So there is a drop down they can select between 'function' and 'string' ...  the function wouldn't surround with quotes... but the string would.  (and best best case scenario, the editor for a function would be multi line).  

The watcher allows me to see if they editor something.  But I wouldn't know their intent.  
(( or am I missing a feature of the watchers that would be useful here? I haven't use them yet.))

And thanks for your reply!

**Comment by schmunk42** [comment]
Is this somehow covered by Json-Schema?

**Comment by Lilwolf** [comment]
Well, yes...  But the editor still need to have a type that is defined that is basically a string, but outputs without quotes to support it.  json-editor doesn't support every "type"... like a "type" of color is handled as a String with a format of "color"... but the output is still a quoted string.  The schema I'm using/converting to work with json-editor has a format of "function" that I just convert to "string" because it's the closest thing in the editor.  

I was really hoping there would be a hook to add a new type... select the editor... and convert the output..  

Thanks

**Comment by germanbisurgi** [comment]
There is no type function in json-schema AFAIK.
Also "field":fred will result in an error because fred will be interpreted as a variable, that is not set.

I would use rather watchers or dependencies
