### ISSUE TITLE
Can you have multiple formats?

### ISSUE THREAD

**Issue by Lilwolf** [json-editor/json-editor#657]
Question - Can you have multiple formats and have a drop down like you can with multiple types?

"type" of "string" and "format" of "color" works great, most of the time.  But it would be great if you can just type in the string, and forgo the editor, optionally... in rare cases (like creating a function that returns a color based on something).  Is there an option to do this?  I tried passing in an array of formats like you do with types... didn't work.  

Thanks

**Comment by germanbisurgi** [comment]
Nope, the format param together with the type will be used to choose and create the right editor for the scope and can not be changed on the fly.
It could be a interesting feature though.

**Comment by germanbisurgi** [comment]
but maybe [this ](https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QEEB2ACA9gIwFawGMwQAacATwAd4kd8jSRKAnTa5yWAZ0VADMIsaABMA8qhqhIMGiD6ZmAWwCGxMmCqyuYZhFQBzRrFQBXRYgDaIVJgmMCmaApABdMsNh9lJ6MSTZlZhAAXzIbCQAxBRU/KSg4RBAASXQPalRhLAx5JVV0MEx0bFh0AHJw2FLGDWpE7V0DRjZIWx4EUDTjD1QCQTb+QRFxWQqQ4NCQBydmKNzY8HjZFM6MrPQcmPzC4rKphSr1TTqdPUMyDdVEvaCyZohW3hAV7t7uR4EhMTska7Hx4KAA===&value=N4IgZglgpgNgJgeQHZRALhAYwPY2wJxABotcCAxAgWwEMAXdEAYgAY32QBfIA===&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction&required_by_default) can help
