### ISSUE TITLE
Fix Bootstrap 4 JSON Properties

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#662]
### General information

- json-editor version: 2.0

### Expected behavior

Nice JSON-Properties overlay

### Actual behavior

Text is too large, should be standard size

![Bildschirmfoto von 2020-02-14 10-57-23](https://user-images.githubusercontent.com/649031/74521024-fd8e6b00-4f18-11ea-9e4b-3a190f34ddb1.png)

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/ - it's also in the demo

---

Would be nice if this could be placed in a modal, but it should be implemented in a backward-compatible way.

**Comment by alhimik1986** [comment]
I want to add the related bugs:

![Без имени-1](https://user-images.githubusercontent.com/7689682/74922762-a7cf2c80-540a-11ea-870c-97d7d4398404.png)

**Comment by stroebjo** [comment]
@germanbisurgi are you already working on this? I cold provide a PR for this. 

I would suggest to switch the `h3` to a plain `div`. Solves the cascading font issue, and you probably could argue the smaller title is better anyway. ;)  

The make the checkbox labels clickable I would argue tue add `id`/`for` attributes int he core, this should also benefit other themes. 

> Would be nice if this could be placed in a modal, but it should be implemented in a backward-compatible way.

That would be nice, but I think besides making the current state more "bootstrap like looking" we can't use the bootstrap modal? At least not from the theme alone. This sounds like ja major / separate project to me.

**Comment by germanbisurgi** [comment]
fixed
