### ISSUE TITLE
How to express generic object

### ISSUE THREAD

**Issue by duchoang** [json-editor/json-editor#664]
### General information

- json-editor version: 2.0.0

I'm wondering how I could express a generic object with no specific properties in `json-editor`, example with this schema:

```javascript
{
  "title": "Example",
  "type": "object",
  "properties": {
    "type": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {}
    },
  }
}
```

I expect field `data` should have a dynamic `textarea` to fill in any generic json, is that possible to change the schema for this behaviour?

Here is the full example: https://jsfiddle.net/2eyr57tj/

**Comment by germanbisurgi** [comment]
Why not a string format textarea?

**Comment by duchoang** [comment]
thanks for the suggestion, just tried it, it works with the ui, but then the output json will not preserve the whole generic json, but a string like this:
```json
{
   type: "abc",
   data: "{\"field\": \ "value\"}"}
}
```
I guess it is not possible in schema to let json-editor auto parse the textarea to proper json?

**Comment by germanbisurgi** [comment]
Could JSON.parse the content

**Comment by duchoang** [comment]
Is there any way to declare that action in the schema, or I need to manually process the output json?

**Comment by germanbisurgi** [comment]
Manually, but you can listen for change events for that
