### ISSUE TITLE
Create Release 2.0.1

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#666]
### General information

- json-editor version: master

### Expected behavior

https://github.com/json-editor/json-editor/pull/660 available in npm package

### Actual behavior

no release

### Steps to reproduce the behavior

see https://github.com/json-editor/json-editor/pull/660

**Comment by kameelyan** [comment]
Checking in, do we know when this release will happen?

**Comment by marc7000** [comment]
I'll do it tomorrow morning...
