### ISSUE TITLE
defaultProperties not working

### ISSUE THREAD

**Issue by alhimik1986** [json-editor/json-editor#669]
### General information
Hi, friends.
Seems, I found the bug or I don't understand English.
If define the "defaultProperties", the defined properties must be visible by default. But it does not appear.

- json-editor version:
2.0.0
### Expected behavior
The property "city" must be visible by default, because it defined in "defaultProperties".
### Actual behavior
No properties (city and state) are not visible by default.
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "Person",
  "type": "object",
  "required": [
    "location"
  ],
  "default": {
    "location": {
      "city": "My city"
    }
  },
  "properties": {
     "location": {
      "type": "object",
      "title": "Location",
      "defaultProperties": ["city"],
      "properties": {
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by germanbisurgi** [comment]
hi, I want to solve this bug, but I need an extra information.
Does this happen only in the interactive page or also happens
on a project with an instance of the Jason - editor?

**Comment by alhimik1986** [comment]
This happens as in my project as  in demo page. If set value using jsoneditor.setValue(someValue) the hidden properties becomes visible regardless of defaultProperties.

**Comment by germanbisurgi** [comment]
I asked because the current interactive page is not working properly and few false positives bugs are coming out.

I made a pull request to fix this.

I also tested your schema against the new interactive page and works properly. Both with the compiled and the [jsdeliever](https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js) js files

Updates asap

**Comment by germanbisurgi** [comment]
Hi, the interctive page was updated. I tried your schema and works. Pls try out too :)

**Comment by germanbisurgi** [comment]
fixed
