### ISSUE TITLE
Is there a way to have a title and value for the checkbox object? (copied from jdorn repo issue #818)

### ISSUE THREAD

**Issue by dolv** [json-editor/json-editor#67]
Hi, I have the object like this:
```
"events": {
	"type": "array",
	"uniqueItems": true,
	"format": "checkbox",
	"minLength": 1,
	"items":{
		"type": "string",
		"enum": ["Induction event","Shipping event"]
	},
	"default": ["Induction event","Shipping event"]
}
```

I'd like to have a possibility to get mapped from title to values array from the checkbox array object according to the following map:
```
"eventsToValuesMAP": {
	"Induction event": "IND",
	"Shipping event": "SHP"
}
```
How to properly define the "events" to get desired effect? 
Thank you in advance.

**Comment by marc7000** [comment]
Hi,

check out the interactive demo...  I have added / updated your "events" Schema...
https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QFEBusB2YDOIA04AngA7xID2ARgFawDGY+IxATuaS5LLgqLOlh6hIMMigE4mYEmICGLFrMJMArhggBHFbACSYWAFseYFtoIAzciwOzGSOgAt6Aa0rkAHkwMQMAGUwA5mAOiACMBFCGQkSkiCDYJj4BTJgqBogA2iA6GAAmKgwQ5BgABPyYjAQAyg4QxMRJZRIgALoE7JDF0akGAPoicDxZOgByACJMVQASAAqtAL7zBLmw5rIq0HbDeQWdpeVYk7X1jQeMLYvzQA=&value=N4IgpgbmB2AuDOIBcBtEBJaATArgY1gEsB7aAAkhlhABoQBlAC0IAcXDoBzCqOEAXQC+QA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by dolv** [comment]
Hi, @marc7000 
That is exactly what I was looking for.
Much appreciated.

P.S. It could be usefull having your example in the array section of the README.md document. Please consider adding it there.

**Comment by dolv** [comment]
The issue has successfully been resolved - thans goes to @marc7000
