### ISSUE TITLE
show_opt_in option and editor.enable

### ISSUE THREAD

**Issue by timota** [json-editor/json-editor#671]
### General information
- json-editor version: 2.0.0

When editor has been created with show_opt_in option, a new tick appear on those props that are not required by default. But when im going to programmatically enable some editors with editor.enable - editor enables for editing but tick not in place, so resulted/final variable doesnt contain that key/value. 

Is this expected behaviour or another method should be used. 

Thanks in advance.

**Comment by germanbisurgi** [comment]
Does this happen only in the interactive page or also happens
on a project with an instance of the Jason - editor?

**Comment by timota** [comment]
It happens with instance 

```
editor = new window.JSONEditor(document.getElementById('editor_holder'), editorData(schema, startval));
```
Startvals are: 
```
    "env": {
      "hosttype_vars": {
        "data": {
          "vms_by_az": {
            "a": 1,
            "b": 0,
            "c": 0
          },
          "flavor": "t2.micro"
        },
        "index": {
          "vms_by_az": {
            "a": 0,
            "b": 0,
            "c": 0
          },
          "flavor": "t2.micro"
        }
      }
    }
```

Schema is: 

```
        "env": {
          "type": "object",
          "options": {
            "disable_collapse": true,
            "disable_edit_json": true,
            "disable_properties": true
          },
          "required": [
            "hosttype_vars"
          ],
          "properties": {
            "hosttype_vars": {
              "type": "object",
              "format": "categories",
              "options": {
                "disable_collapse": true,
                "disable_edit_json": true,
                "disable_properties": true,
                "collapsed": false,
                "compact": true
              },
              "required": [
                "data"
              ],
              "properties": {
                "data": {
                  "type": "object",
                  "title": "Data",
                  "$ref": "#/definitions/_service"
                },
                "index": {
                  "type": "object",
                  "title": "Index",
                  "$ref": "#/definitions/_service",
                  "description": "Service disabled by default. Put a tick if you want to enable this service"
                }
              }
            }
          }
        }
```

**Comment by germanbisurgi** [comment]
a definitions object is missing in your schema?

`"definitions": {
    "_service": {
      "type": "string",
      "minLength": 5
    }
  }`

**Comment by germanbisurgi** [comment]
You could use activate and deactivate

**Comment by timota** [comment]
in full schema i have all definitions. But issue is that when we have some fields declared as required and some not. and those options that not required and exists in startval - editor doesnt set them.

**Comment by germanbisurgi** [comment]
did you tried editor.activate() ?

**Comment by germanbisurgi** [comment]
I am testing in local and works correctly with the new interactive page. I believe soon (maybe today) a new release will be done.

**Comment by germanbisurgi** [comment]
fixed with new interactive page
