### ISSUE TITLE
All the collapsed items are expanded after deleting one of the items

### ISSUE THREAD

**Issue by lovelyserafima** [json-editor/json-editor#674]
Hi,

### General information

- json-editor version: 1.3.5

### Expected behavior 

All the collapsed items remain collapsed after deleting one of the items.

### Actual behavior

All the collapsed items are expanded after deleting one of the items

### Steps to reproduce the behavior

I cannot reproduce it in https://json-editor.github.io/json-editor. So is it a problem of json-editor version?

Thanks.

**Comment by lovelyserafima** [comment]
E.g. I tried with it - https://json-editor.github.io/json-editor/?schema=N4IgJAlgJiBcIAsAuSAOBnWB6LBTAHgIYC2qANrgHQDGA9sVoQE5OECe6l61CuxhlAFbpaAOxAAacN1784iFKmxZhYgLQy+A2kwDmWKKwBmSNQAYA7Fk38AxJJBRc3JhFRIIY+QEEABE1xUAPRcUSRCDzFfWiNfQl9UXCYRUQlfOlJCUTY0nV0siAAvCM9U6KYEskJqXAckNkT5WgAjQVxqJAcg2kSmD2c4UCMmAFcIJHRBkHrG+GZWNgdxvknYUBna+HQkV1FdEABfA6kAN1xdXHDmilX1hs2QefYlpBWpsACjeVsDXCMIUTjUroLBnXS6CC1I7HRx/AFAsS3EBgiGbO6zEAtNodBwBACOYwCMFgAG1kedUQA5Ei1U4UyEAGQgAGtagBdKTdXr9JEoyHU4ho6b3eTbXb7KROFxuSLieAAFV4vlENOisSQSrBl0I1yohzp4MZLKFG3kzVotAoWQcUuorncpXkABFaL4AJK+MjG3waiDoXxaq4UAD8h2hByAA&value=N4IgZgTgrglgLgZxALgNogIYAcsBsCmIANCAPYQYB2A5oSVvhhCALokBu+tcGARgUjShO1ajHwA5DAFtCyEFlI84pYiBFj8AGRgBrOXGj4AvkWFdNU2ShC8IpAMYPSuGGo3id+lGAy4EJizGQA==&lib_switcher=&prompt_before_delete&upload=function(t,e,i){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap4&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

But it works fine in json editor.

Thanks.

**Comment by schmunk42** [comment]
Likely, please try 2.0 and reopen if the issue persits.
