### ISSUE TITLE
Broken UI after upgrade to 2.0.0

### ISSUE THREAD

**Issue by lovelyserafima** [json-editor/json-editor#677]
### General information

- json-editor version: 2.0.0

### Expected behavior

Good looking ui

### Actual behavior

Some broken UI moments:
![image](https://user-images.githubusercontent.com/33148718/75541704-728c9500-5a2f-11ea-940f-ecfd6c727471.png)

-titles of objects are after properties and collapsing arrows
-deleting icons and sotring arrows are under the titles

Before upgrading it was pretty good:
![image](https://user-images.githubusercontent.com/33148718/75541931-d911b300-5a2f-11ea-8abd-15b8444ba9b2.png)

I didn't develop the part of our editor form, so I ask you to know what really should I fix?

Thanks.

**Comment by schmunk42** [comment]
Can you provide an example link (including the theme and settings used)?

**Comment by lovelyserafima** [comment]
> Can you provide an example link (including the theme and settings used)?

Hi, @schmunk42,

Thanks for reply. I found css file which manages our styles and seems fixed what I needed, so I'm closing the issue.
