### ISSUE TITLE
grid_columns does not work for bootstrap4

### ISSUE THREAD

**Issue by syssecfsu** [json-editor/json-editor#68]
I have tried many different options but still could not figure it out. I want to create a form with 2 columns but always get three columns no matter where I put the grid_columns option. I have linked the bootstrap 4 css and js files (the standard bootstrap4 template). 
Here is the code to create the form: 
   ```
    var editor = new JSONEditor(document.getElementById('editor_holder'), {
            disable_collapse: true,
            disable_edit_json: true,
            disable_properties: true,
            no_additional_properties: true,
            

            // Enable fetching schemas via ajax
            ajax: true,
            object_layout: "grid",
            grid_columns: 2,
            theme: "bootstrap4",
            // The schema for the editor
            schema: {
                $ref: "/resources/application.json",
            },

            
            // Seed the form with a starting value
            //startval: starting_value
        });
```
The json file is simple: 
```
{
  "title": "Application",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "title": "Name:",
      "minLength": 5
    },

    "dob": {
      "type": "string"
    },
    "gender": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },

    "program": {
      "type": "string"
    },
    "degree": {
      "type": "string"
    },
    "interests": {
      "type": "string"
    },
    "ug_university": {
      "type": "string"
    },
    "ug_major": {
      "type": "string"
    }
  }
  
}
```

Thank you for your time and help!

**Comment by schmunk42** [comment]
@germanbisurgi Could you add `grid_colums` (ie. dropdown with numbers 1-12) to the index.html (https://json-editor.github.io/json-editor/) and maybe some other options which can be customized, so we can test this online in the future?

**Comment by visualdatasolutions** [comment]
@syssecfsu  Have you tried supplying grid_columns in the schema nested under the property options? like this
`"dob": {
    "type": "string",
    "options": {"grid_columns": 6} 
},`
The property grid_columns refers to the number of grid columns out of 12 in a row that the field will take. You will get two equal width columns (6/12 = 50%) this way.
