### ISSUE TITLE
Range output is not updated when calling setValue

### ISSUE THREAD

**Issue by johannesodland** [json-editor/json-editor#683]
### General information

When using range format an extra range output element is created. This element is updated on input and change events, but is not updated when setValue is called. 

When initialising the editor with startval, or when calling setValue, the range input element is updated, but not the range output element. It keeps showing the default value.

- json-editor version:
2.1.0

### Expected behavior

After a call to setValue the range output should display the current value of the input element.

### Actual behavior

After a call to setValue the range output displays the default value and not the value of the input element.

### Steps to reproduce the behavior

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIMgHNdAXTYIKUhDWBoNbz9IswtCGHgoKj8pBRIZMnErKTJ4aLZXKiIyEWwsgCZGNjoEmDoROlQARgAOarIADzqG1ABOXoBfIbZEZTAKXkMQo3jEwzIeOBM2KFUGQjwwMChEKByIABYQIaA=

Change the age under JSON-output and watch the range input update, while the output value still shows 25.

**Comment by schmunk42** [comment]
@germanbisurgi Please create a test first.

**Comment by germanbisurgi** [comment]
fixed in #685
