### ISSUE TITLE
Bootstrap4 is not loading on the demo website

### ISSUE THREAD

**Issue by Mikescops** [json-editor/json-editor#69]
From the demo website (https://json-editor.github.io/json-editor/) the CSS Framework Boostrap is giving a blank page with an error in the console.

"uncaught exception: Unknown theme bootstrap4"

![screenshot](https://i.imgur.com/ZL2ZZcq.png)

**Comment by germanbisurgi** [comment]
@schmunk42 maybe it depends on this 

`<script src="//unpkg.com/json-editor"></script>`

**Comment by agladysh** [comment]
Same for the `materialize` and some other schemes. I think that the json-editor used in the demo is not of the latest version.

**Comment by germanbisurgi** [comment]
Its working now

https://json-editor.github.io/json-editor/
