### ISSUE TITLE
is there a way for getting source of JSON-Editor Interactive Playground?

### ISSUE THREAD

**Issue by faraazbh** [json-editor/json-editor#695]
### General information

How can I get css/jsoneditor_demo.min.css CSS file. Someone please help

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by robocoder** [comment]
https://github.com/pmk65/jedemov2
