### ISSUE TITLE
How to set action for the "button" format?

### ISSUE THREAD

**Issue by NemeZZiZZ** [json-editor/json-editor#700]
### General information
I want to set a function for button action, but can't understand, how to do this?

- json-editor version: 2.2.0

### Actual behavior
> No button action defined for "root.test.button"

### Steps to reproduce the behavior

```javascript
{
  "title": "button example",
  "type": "string",
  "format": "button",
  "options": {
    "action": ???
  }
}
```

**Comment by tohosaku** [comment]
Although not written in the README, the sample code is at the following URL.

https://github.com/json-editor/json-editor/blob/master/tests/pages/button-callbacks.html

**Comment by germanbisurgi** [comment]
it also documented here https://github.com/json-editor/json-editor#string-editors-input-attributes
