### ISSUE TITLE
what scene do you apply by using this lib?

### ISSUE THREAD

**Issue by hookenono** [json-editor/json-editor#71]
I'm designing an office data-config-system by using this lib,  
hope to understand your apply ideas !

**Comment by schmunk42** [comment]
Sorry, I do not fully understand your question. Could you elaborate more?

**Comment by hookenono** [comment]
Is this lib has any specific applications?

**Comment by schmunk42** [comment]
No, it "just" renders a (sometimes complex) form from a JSON-schema.
