### ISSUE TITLE
allOf wrapping array items causing issues with no_additional_properties

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#716]
### General information

- json-editor version: 2.1.0

### Expected behavior
No errors should be present when a car is added

### Actual behavior
An error is being thrown saying "No additional properties allowed but property <T> is set"

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWylUAjiJgmAJqgDaIDGSnIAumwhTIVKbBoaHTshoILBQ2LooIADCgQpaOoROUkIKMFBqQaBy2ADyRHaaaeGEMVIK8GQMhI5lbPER7Fw8Ch5ePjB+wbIA1hGFYQ0AsmS9cdoNiFBSMPAA5iAAvmx0YFZU8sGhxZGDq+tjCZGT03OLSyAm5pZUNij2PbouC08Lr2yIymAUvN6ezoQzdLJHhweBxVRVSJ4MBgKDHMgQAAsCkuFmsvDwgl4ayIZBE2HEKFx2EQVDYVhgiAgAixqOuVl4OEEqGJpPen2+kD4MxZcjZIEkvDIVgpsAQcl4rR07U6UxEZJAZA4ZAAHrySQqKYgyHhwj9RbwOLQwUS+ZrKTq9VhsAIIKT1fytZaqJLPNLfEFWebtbqXUkhEKRQ7vc6hVJkrSqNI1mVTRryRbfWGI9j1lR0sG2FQKkn/VisBBmXH+XneFh4FMwCTeFBIJmQE7c+GA2twukhTbeJ4KJ6zQmfXrS630y6BJMu19g68gA===

The issue seems to be the same as #237.  Logging a new bug on the latest version as that had some outdated comments. The comments is on this line now: https://github.com/json-editor/json-editor/blob/cfec910d219082995149babc7d65c3fe926f01bd/src/validator.js#L578

allOf/anyOf/oneOf are not working property with validation and the setting no_additional_properties. The above example is broken. Removing the allOf causes it work.

Removed allOf:
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWylUAjiJgmAJqgDaIDGSnIAumwhTIVKbBoaHTshoILBQ2LooIADCgQpaOoROUkIKMFBqQZpp4YQxUgrwZAyEjvls8RHsXDwKHl4+MH7BsgDWEVlhlQCyZG1x2pWIUFIw8ADmIAC+bHRgVlTywaE5kV1zC/0JkUMj41PTICbmllQ2KPatui6TNweIymAUvN6ezoSj6ck8cPBxqsWRPBgMBQHZkCAAFgURws1l4eEEvHmRDIImw4hQKOwiCobCsMEQEAEiJhJysvBwglQWJxbHujwp0F4o2pclpIEkvDIVnxsAQcl4dR0DSawxEuJAZA4ZAAHqzsRL8YgyHhws9ebwOLRfpi2YqCSq1VhsAIIDj5eylYaqILPMLfEEafrlaqbUkhFyeRbndauVJkiSqNJ5vldQq8QbXX6A0iFlR0t62FRClH3YisBAqWH2WneFh4MMwNjeFBIImQFbU/6PfNwukuSbeJ4KI69RGXWrc7X4zaBEMm49vTcgA===

**Comment by kameelyan** [comment]
This should get fixed here by adding allOf to the logic. https://github.com/json-editor/json-editor/blob/cfec910d219082995149babc7d65c3fe926f01bd/src/validator.js#L578

**Comment by schmunk42** [comment]
Closed, since #717 is merged.

**Comment by kameelyan** [comment]
@schmunk42 can we get a release of this? It's affecting some of our production and we need an updated npm package.

**Comment by schmunk42** [comment]
https://github.com/json-editor/json-editor/pull/721
