### ISSUE TITLE
Bootstrap 4 colour preview not working

### ISSUE THREAD

**Issue by drmrbrewer** [json-editor/json-editor#718]
### Expected behavior

The colour preview shows the actual colour selected.

### Actual behavior

It doesn't.  It just shows a thin, grey line.

### Steps to reproduce the behavior

Just load the demo with defaults:

https://json-editor.github.io/json-editor/

![tempsnip](https://user-images.githubusercontent.com/9009792/79500595-8d898780-8024-11ea-880b-70678f67b576.png)

If it makes any difference, I'm using Chrome Version 81.0.4044.92 (Official Build) (64-bit)

**Comment by schmunk42** [comment]
We might need to use a smaller padding for BS4 color inputs.

**Comment by germanbisurgi** [comment]
fixed

**Comment by drmrbrewer** [comment]
@germanbisurgi forgive my ignorance about the process, but at what point does it find it's way into the version loaded into the online demo at https://json-editor.github.io/json-editor/ ?

**Comment by germanbisurgi** [comment]
we do not make releases on a fixed pace but i believe soon will be the time. @schmunk42 what do you think?

**Comment by schmunk42** [comment]
@germanbisurgi Could you have a look at this one https://github.com/json-editor/json-editor/pull/704 

@marc7000 After that we need to have a look a the changelog and do a `2.2.0` release.
