### ISSUE TITLE
Release 2.2.0 removed AbstractIconLib and AbstractTheme

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#723]
### General information

json-editor version: 2.2.0

### Expected behavior
I expected JSONEditor.AbstractIconLib and JSONEditor.AbstractTheme to continue to exist in the latest release in order to create custom themes.

### Actual behavior
These properties have been removed and no longer exposed.

This is a pretty big deal and preventing us from upgrading to 2.2.0 to get the allOf bug fix.

**Comment by schmunk42** [comment]
Related? https://github.com/json-editor/json-editor/issues/658

CC: @germanbisurgi

**Comment by schmunk42** [comment]
@kameelyan Could you provide a test for this issue?

**Comment by kameelyan** [comment]
@schmunk42 https://stackblitz.com/edit/json-editor-723?file=index.js

Change the version on line 13 to 2.2.0 or 2.1.0 to see the issue in the console.

2.2.0:
![image](https://user-images.githubusercontent.com/590274/79899622-a7cfb680-83d2-11ea-9a0e-d40996fdc919.png)

2.1.0:
![image](https://user-images.githubusercontent.com/590274/79899647-b0c08800-83d2-11ea-8f5b-0c089abce58d.png)

As you can see, the properties on line 21 and 22 are now undefined in 2.2.0.

**Comment by schmunk42** [comment]
fixed by #724

**Comment by schmunk42** [comment]
@kameelyan could you confirm this is fixed on master?

**Comment by kameelyan** [comment]
@schmunk42 looks great, just need a release now. Thanks!

**Comment by schmunk42** [comment]
I'd like to include a fix for https://github.com/json-editor/json-editor/issues/725 as well.

CC: @germanbisurgi @marc7000
