### ISSUE TITLE
Random console.log made it into master/release

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#734]
https://github.com/json-editor/json-editor/blob/04aa4f09a84d5904c762d2fae4264c0822dca79a/src/validator.js#L247

**Comment by schmunk42** [comment]
I think we should strip all `conosle.log` for release.

Also the linter should throw a warning, or what's the best practice here?

CC: @germanbisurgi @amk0 @marc7000

**Comment by kameelyan** [comment]
I think logging logs and errors to console are fine, many logging software have started to use those to log errors. But I do think a process should be put in place for pull requests to validate new ones are accurate.
________________________________
