### ISSUE TITLE
Can't click text to select checkbox in properties

### ISSUE THREAD

**Issue by odscjames** [json-editor/json-editor#736]
### General information

- json-editor version: 2.2.1

Chrome and Firefox

options:

     theme:'bootstrap4', 

in case it matters

### Expected behavior

![Screenshot from 2020-04-29 15-21-53](https://user-images.githubusercontent.com/37832009/80607366-51472580-8a2d-11ea-89a7-3a5bcb7531c2.png)

When I click "notes", I expect the checkbox to be checked

### Actual behavior

Nothing happens

I believe this comes under an accessibility issue to, as I think screen readers etc will use this association.

### Technical fix

I can see the source code seems to be basically

    <input type="checkbox" style="width: auto;" class="form-check-input">
    <label class="form-check-label">&nbsp;Notes</label>

The input should be inside the label

    <label class="form-check-label"><input type="checkbox" style="width: auto;" class="form-check-input">&nbsp;Notes</label>

Or use the for attribute

    <input type="checkbox" style="width: auto;" class="form-check-input" id="NOTES">
    <label class="form-check-label" for="NOTES">&nbsp;Notes</label>

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJDAAmhZVCgREKAPSmqADzJ0I2KgDosdUxjJSdDpatkOOteAVNbzUyfUMIM1N/BABaEN9pAHNTHSkyIihYgAYAdlMEsgBiBR0aDCkYaDhAlBAAQQACKSoIFsQqeHJYBEawIkayRogqKQCWRucIMnhBCeSZmAAvMh74ealhgQwqBShBEcIwTm5xNhaARxEYFr0UAG0QWCh7BREpeQBdNjbIUdgaBonjAXrs0MDQYQACog15sMpKSrVBDQ2FUPoDdqiKQ7PYHMGKKCVeBJEAAXzY73k4OerzqAFUAEoAGVK5SRa0ITOZGOaNGxuLY+0OdUQRJgJIUJBkq0I7xg5LYkiggJpaMIADkwCrkEL8YQxcTSWxpbJxHUVZZyC0wmS7WxEMowBReKMpNJkHUJSr0jwansfAS8GBtYayBAACzkslAA==

**Comment by odscjames** [comment]
>       const unique = label.innerText

I may be miss-understanding how ``innerText`` is used here, but are we sure it's going to be unique?

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJDAAmhZVCgREKAPSmqADzJ0I2KgDosdUxjJSdDpatkOOteAVNbzUyfUMIM1N/BABaEN9pAHNTHSkyIihYgAYAdlMEsgBiBR0aDCkYaDhAlBAAQQACKSoIFsQqeHJYBEawIkayRogqKQCWRucIMnhBCeSZmAAvMh74ealhgQwqBShBEcIwTm5xNhaARxEYFr0UAG0QWCh7BUkoGhAAXTY2yFHYJ80E8YC9dsDnq86gAVUGvNhlJSVaoIQiwsF9AbtURSHZ7A7gxRQSrwJIgAC+bHeQNAkMJ6PhTwJhEQxJgpIUJBkq0IH0s5BaYXJwrYiGUYAovFGUmkyDq7I+6R4NT2PkJeDAYCgrPSEAALBTyUA=

Is one example where it's not.

Ok, that's a slightly silly example, but what about:

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJDAAmhZVCgREKAPSmqADzJ0I2KgDosdUxjJSdDpatkOOteAVNbzUyfUMIM1N/BABaEN9pAHNTHSkyIihYgAYAdlMEsgBiBR0aDCkYaDhAlBAAQQACKSoIFsQqeHJYBEawIkayRogqKQCWRucIMnhBCeSZmAAvMh74ealhgQwqBShBEcIwTm5xNhaARxEYFr0UAG0QNzOQHTAkkABdNjbIUdgaBonqsgbAoPZCABhEFsfaHOrHLg8BS/EZSAHINAgMEQrE43Z1AAqMHBu1hBwJiiglXgHzYJBkILqUCs5BaYQAvly2G8PniSbiQNCXnDKYjTiipH90TBAfzSaCBZTiQryfCqTS6cRpLJxMzWe4qJyudzFMowBReKMpWNCDAuqMyDwansfJS8GAwFBENSyBAACwgLlAA===

It looks like the 2 properties pop-up boxes both exist at the same time and are just hidden? In which case the id's will not be unique.

Also a simple id like that might even clash with something else on the page, a ``<h1 id="Title">Welcome</h1>`` or something.

This is why I didn't rust to try and fix this myself BTW - I'm happy enough hacking round the DOM but I don't yet know enough about the project to know:
* if moving input inside label would cause issues with other JS, etc
* what a good scheme to make a unique ID would be

Thanks for looking at this!

**Comment by germanbisurgi** [comment]
You are right again. Initially i try to put the input in the label (bootstrap3 way) but it clashed with styles (absolute positions in this case) so i tried the "for" attribute way.

I can easily make the label "for" and the input "id" attribute unique. I could append a (random * timestamp) for example. but before i go i want to know if for us and you is ok. 

May be will be  better if a use more time and fix the styles clashing when i put the input inside the label. Of course this will take time because i need to proof that it will not break other places where checkboxes are used

**Comment by germanbisurgi** [comment]
@schmunk42  what do you think?

**Comment by schmunk42** [comment]
> @schmunk42 what do you think?

Tests, tests, tests ;)

Also a method `I.dontSeeDuplicateUnqiueElements()` (or similar) would be useful.

**Comment by odscjames** [comment]
Should this issue be re-opened? (And thanks for looking!)

**Comment by Darkness126** [comment]
Is this issue fixed? If not I would like to try to fix this and create a PR.
