### ISSUE TITLE
Is it possible to tweak the UI to a multiple Tab/Tree like struct for complex Schemas?

### ISSUE THREAD

**Issue by faraazbh** [json-editor/json-editor#741]
### General information
Is it possible to tweak the UI to a multiple Tab/Tree like struct for complex Schemas?
I have certain schemas that have various level of composition & it is difficult to fill forms & interpret which property belongs to which object
- json-editor version:

### Expected behavior
Is it possible to view the form as a Tabs of different objects or a tree like structure?
### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by schmunk42** [comment]
Like this? https://github.com/josdejong/jsoneditor/

**Comment by faraazbh** [comment]
yes almost but my problem is I want to take input based on Java classes.
So i'm generating JSON schema of Java classes using Jackson, using the schema in json-editor to generate the form. But the classes are huge with composition so form is difficult to navigate.

Hence, I was considering tree structure. But the above solution that you've linked, that doesn't support json schema to tree conversion. OR can i add objects based on schema??

I'd really appreciate if I could get some pointers coz I'm kinda stuck because the form isn't very usable for my case

**Comment by schmunk42** [comment]
Maybe you'll find something here: https://json-schema.org/implementations.html#web-ui-generation

I think it's out of scope for us at the moment.
