### ISSUE TITLE
Custom Validator with Server Side Validation 

### ISSUE THREAD

**Issue by claria** [json-editor/json-editor#748]
Is it possible to use an ajax call to perform server-side validation on an input field using the custom validators?

The use case is the following: 
The user enters a special kind of formula in a text input field which can only be validated on ther server side. I would like to make an ajax call in the custom validator and update the errors array based on the result of the server call.

Is this possible?

**Comment by germanbisurgi** [comment]
https://github.com/json-editor/json-editor#custom-validation

**Comment by claria** [comment]
If iunderstand the custom validation section in the readme correctly, i could make a sync ajax call to the server and then return the errors array. 
Is there a way to do this in an async way? Otherwise i would block validation of the other fields until the server responds if i understand the code correctly.

**Comment by germanbisurgi** [comment]
something like this?

`
JSONEditor.defaults.custom_validators.push((schema, value, path) => {
    const errors = []
    if (schema.format === "date") {
        $.ajax({
            url: "validate.php",
            success: function(result) {
                if (result.error) {
                    errors.push({
                        path: path,
                        property: 'format',
                        message: 'Dates must be in the format "YYYY-MM-DD"'
                    })
                }
            }
        })
    }
    return errors
});`

**Comment by claria** [comment]
Exactly. However, your example only works if you set async: false. In my case, the server call takes about 1-2 seconds and during this time the editor is blocked if using sync ajax calls.

**Comment by germanbisurgi** [comment]
then i would use a javascript Promise with async and await.

**Comment by egze** [comment]
@germanbisurgi Would you be so kind and provide an example with a Promise?

Here is what I tried:

```js
JSONEditor.defaults.custom_validators.push(async (schema, value, path) => {
  const errors = [];

  const p = new Promise((resolve, reject) => {
    // this sends an event to LiveView with a onReply callback
    this.pushEventTo(this.el, "validate_value", value, (reply, ref) => {
      resolve(reply)
    })
  })

  const result = await p
  // process result and add to errors

  return errors;
});
```

This produces an error in the browser:
```
jsoneditor.js:14 Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
```

**Comment by schmunk42** [comment]
@germanbisurgi Please also add the example to the wiki, thx.

**Comment by germanbisurgi** [comment]
The JSONEditor is not able to process async validation functions. This could be a workaround for edge cases:

```javascript
jsoneditor.on('change', async () => {
  const editor = jsoneditor.getEditor('root.name')

  const promise = new Promise((resolve) => {
    // simulate Promise
    setTimeout(() => {
      if (editor.getValue() === 'invalid') {
        resolve({
          path: editor.path,
          property: 'test',
          message: 'The value is invalid'
        })
      } else {
        resolve(false)
      }
    }, 1000)
  })

  const result = await promise

  if (result) {
    jsoneditor.validation_results.push(result)
    jsoneditor.root.showValidationErrors(jsoneditor.validation_results)
  }
})
```
