### ISSUE TITLE
Type number is not being validated when include in an anyOf

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#751]
### General information

- json-editor version: 2.2.1

### Expected behavior
Type number should always validate correctly. 

### Actual behavior
When including anyOf and several types, type number is not validating at all.

### Steps to reproduce the behavior
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIMgHNdAXTYIKUhDWBoNbz9IsnhBAHkiT01zSxB4ETo8Q1MYbTSANTkRKhYAAgysnIBfFhSLQkQoKRh4H1z8wiLsEvKmlraFOlaAGSo2qGVUAEZa+rSM7Hk2LR0u4tKKkSWQav9qg7ZEZTAKXkMQo0JWqEMyHjgTFdUGQjwwMCh+sggAFl3qkA==

**Comment by Samibanley** [comment]
Has anyone looked into this? I wouldn't mind giving it a go, if it is available.

**Comment by schmunk42** [comment]
Sure.

**Comment by kameelyan** [comment]
Any update @Samibanley ?

**Comment by germanbisurgi** [comment]
Its working properly. It displays an error when number is selected because your current value is still an empty string
