### ISSUE TITLE
Format checkbox and minItems does not play well together

### ISSUE THREAD

**Issue by intco** [json-editor/json-editor#755]
### General information

I wish to use the editor to create/edit an object which has an "element_types" array that must contains at least one element chosen to a list of two elements.

- json-editor version: 2.2.1

### Expected behavior

The choices are displayed as checkbox list.

User must choice at least one.

### Actual behavior

Javascript error:

jsoneditor.min.js:18 Uncaught TypeError: Cannot read property 'add' of undefined
    at $.addInputError (jsoneditor.min.js:18)
    at v.showValidationErrors (jsoneditor.min.js:18)

### Steps to reproduce the behavior

Go to https://json-editor.github.io/json-editor/

Open the developer console

Paste the following schema and update "Update schema"

See the error in the Console tab of the developer console.

**Please note that if I remove the "minItems" properties all is working fine**

```javascript
{
  "title": "Config",
  "type": "object",
  "required": [
    "element_types"
  ],
  "properties": {
    "element_types": {
      "type": "array",
      "title": "Elment types",
      "items": {
        "type": "string",
        "enum": [
          "content",
          "module"
        ]
      },
      "uniqueItems": true,
      "format": "checkbox",
      "minItems": 1
    }
  }
}```

**Comment by germanbisurgi** [comment]
fixed in #943
