### ISSUE TITLE
create links from fields text

### ISSUE THREAD

**Issue by rikiNeustadt** [json-editor/json-editor#758]
### General information

- json-editor version:

Argent!!!!
please help me with this requirement:
 
i have to replace the text placed in the schema with links contains the value of field 
(in order to search for this text) 
is there anyway to do it? i tried to access the fields directly with jquery but it was too complex.
therefore i use <field>.getValue() and i want to set the value to link.
### example:
{
  "name": "Mike" 
}
i want to create link:  http//google.com#search=Mike (and display Mike as usual).

var name = item.getValue();
var htmlTag = link + name;
var itemlink = $("a")
        .attr("href", htmlTag)
        .attr('target', 'search_pdf')
        .val(name);

###  is there anyway for:
      item.setValue(itemlink)

if this case is impossible, is there nice way to add extra button nearby the field with this link?

Thx :)

**Comment by schmunk42** [comment]
https://github.com/json-editor/json-editor#hyper-schema-links

**Comment by rikiNeustadt** [comment]
Thx for quick answer. appreciate it
i saw this option, but i can't use it for array and i want the user to insert only string, and i want to replace it in function onChanged() with the value as i  described.
am i right?
or maybe i didn't get it correctly.

**Comment by schmunk42** [comment]
Can you provide a link to an example via https://pmk65.github.io/jedemov2/dist/demo.html

**Comment by rikiNeustadt** [comment]
huge thanks!!!!

i tried. but i can't. i get lot of errors there.
i paste here the exactly part i want to access:
```
{
    "flash": {
      "title": "Flash",
      "type": "array",
      "format": "table",
      "uniqueItems": "true",
      "items": {
          "type": "string"
          },
      "options": {
          "disable_collapse" : "true",
          "disable_array_reorder": "true"
      }
    }
}

```


i want to replace each item in the array for the link.

**Comment by rikiNeustadt** [comment]
anyone? it's argent......

**Comment by germanbisurgi** [comment]
For arrays you can use the `forEach()`.
But this is out of the scope of json editor. This is more like a JavaScript question.
You can learn more about forEach [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
