### ISSUE TITLE
NaN value on seleting the year

### ISSUE THREAD

**Issue by Obtin** [json-editor/json-editor#76]
Whenever I change the value from the default value in year box, it gives me NaN

![json](https://user-images.githubusercontent.com/25207205/40646734-b7beac16-6347-11e8-814c-a0f38426e50b.png)

**Comment by germanbisurgi** [comment]
Hi Obtin. Can you provide the JSON schema you used?

**Comment by germanbisurgi** [comment]
Ah I see. Is the basic example page.
The problem is that 2019 is not in the select options.

<img width="1084" alt="bildschirmfoto 2018-05-29 um 12 15 16" src="https://user-images.githubusercontent.com/13135260/40652931-fb690348-6339-11e8-944f-a7a8fc0eebd3.png">

**Comment by Obtin** [comment]
Thank you so much for your help @germanbisurgi
