### ISSUE TITLE
Looks for a $schema to add to my json file

### ISSUE THREAD

**Issue by afroradiohead** [json-editor/json-editor#764]
Is there a $schema I can add to my json?

```json
// person.json
{
  "$schema": "./jsonEditorSchema.json",
  "title" : "Person",
  "properties": ...
}

**Comment by schmunk42** [comment]
Can you elaborate further? I do not understand the issue you are having.

**Comment by germanbisurgi** [comment]
maybe this? https://github.com/json-editor/json-editor#json-schema-support

**Comment by afroradiohead** [comment]
@schmunk42 Sure so I want to add validation to my schema, for example:
![image](https://user-images.githubusercontent.com/5151401/84691532-2ccddc80-aef9-11ea-941c-dd67d8cced84.png)

I see @germanbisurgi linked me to https://github.com/json-editor/json-editor#json-schema-support. Is that the proper schema file to use for validation?

**Comment by germanbisurgi** [comment]
if i understand what you need is  "$ref"

**Comment by afroradiohead** [comment]
@germanbisurgi oh yes, actually that's what I need. Thanks for clarifying. Yeah does that exist?

**Comment by germanbisurgi** [comment]
I believe yes :)

[example](https://github.com/json-editor/json-editor/blob/17bde4a3bf6537ff294e859b62a1ca4b2d0f7e94/docs/person.json)

**Comment by afroradiohead** [comment]
@germanbisurgi That isn't exactly what I'm talking about.

Here's my thought process. I hope it better explains what I'm looking for:
- Typescript has interfaces, so I can hand my interface to another developer to ensure they create their object the way I want them to
- **What is the json equivalent of typescript interfaces? and does this repo have an example of that?**

**Comment by germanbisurgi** [comment]
I believe i understood and answered your question in the comment before. But i will try to use the typescript example.

typescript
```
interface LabeledValue {
    label: string;
}

function printLabel(labeledObj: LabeledValue) {
    console.log(labeledObj.label);
}
```

json schema
```
{
  "$ref": "basic_person.json"
}
```

where "$ref" = labeledObj and "basic_person.json" => LabeledValue. ("basic_person.json" is a file path)


[Here the example page](https://json-editor.github.io/json-editor/advanced.html)
