### ISSUE TITLE
Any way to match old startval to new json schema?

### ISSUE THREAD

**Issue by suyanzhi** [json-editor/json-editor#767]
### General information

- json-editor version:2.1.0

### Expected behavior
After I first save schema form,then I edit json schema, the second time I set startval and new json schema, , it should render the full picture of the true schema;
### Actual behavior
the page same wrong,it lose some fields (diff with the old schema) which the new schema has
When set option include startval and schema
### Steps to reproduce the behavior
1.first save schema form;
2. edit the json schema
3. set option include startval and schema
Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by SightStudio** [comment]
i'm facing same issue either

step 1. set schema 
```json
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "originProp": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

step 2. submit value to my Server RDB 
```json
{ "originProp": "'value" }
```

step 3. update schema 
```json
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "originProp": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    },
    "updatedProp": {
      "type": "string",
      "description": "This is updatedProp.",
      "default": "Please edit me."
    }
  }
}

step 4. get stored value and put editor in step3.
```json
this.editor().setValue({ "originProp": "'value" })
```

then ```updatedProp``` is disappear 

is there any way to display mismatched field in editor?

**Comment by SightStudio** [comment]
@suyanzhi 

i've just solved this issue by **getEditor()** for every path 

example)
```js
const result = {
   option : {
       prop1  : 'value1'
       prop2  : 'value2'
   } 
}
```

then use get editor like 
```js

const editor = new JSONEditor(element, option)

const prop1_editor = editor.getEditor('root.option.prop1');
prop1_editor.setValue(result.option.prop1);

const prop2_editor = editor.getEditor('root.option.prop2');
prop2_editor.setValue(result.option.prop2);
```

i think this is the only way to solve this issue for now.  (**setValue()** on root doesn't work)

**Comment by germanbisurgi** [comment]
how are you updating the schema?

**Comment by schmunk42** [comment]
No feedback, closing.
