### ISSUE TITLE
select element with empty default vaule

### ISSUE THREAD

**Issue by hookenono** [json-editor/json-editor#77]
### Schema:
```
"platform": {
    "title": "客户端类型",
    "type": "string",
    "enum": [
          "ios",
          "android"
     ],
     "default": ""
},
```
### Now:
![image](https://user-images.githubusercontent.com/3053496/40650258-78c48f9e-6365-11e8-9919-48d444f1bf16.png)
### Expected
![image](https://user-images.githubusercontent.com/3053496/40650307-91f0ec06-6365-11e8-8cfb-c5e3ed70a889.png)

### Question:
How I can get the expected result? tks!

**Comment by germanbisurgi** [comment]
You have to add the "" value to the enum

{
	"title": "Person",
	"type": "object",
	"properties": {
		"platform": {
			"title": "客户端类型",
			"type": "string",
			"enum": [
				"",
				"ios",
				"android"
			],
			"default": ""
		}
	}
}

**Comment by hookenono** [comment]
help

**Comment by germanbisurgi** [comment]
Hi hookenono. Try this

```
{
	"type": "string",
	"enum": ["value1", "value2"],
	"required": true
}
```

Here the interactive example

https://json-editor.github.io/json-editor/?schema=N4IgLgngDgpiBcIDOYBOBLAdgcxAGhBkwFcBbBAbRADcBDAG2JgEZ8aGmAmEAXQNRgBHYugEATBGiYBfIAA=&value=EQNwhgNgrgpgjMIA&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by germanbisurgi** [comment]
@schmunk42 I belive you are right. In the interactive page the json-editor is downloaded from  unphkg.com.

![unpkg](https://user-images.githubusercontent.com/13135260/40780078-8707d160-64d7-11e8-9a77-5107aca8cd60.png)

inspecting the code i notice that this version has not the enum + default fix.

However i am wondering why the first option in the select is empty when in the enum are only two values specified.
