### ISSUE TITLE
Can't generate UUIDs for array elements

### ISSUE THREAD

**Issue by L-A-F-B** [json-editor/json-editor#779]
### General information
I can load and run your UUID example, but when I wrap it with the code to turn the schema object into an array element, it does not work.  I'm a newbie, so maybe I'm doing something wrong.  Don't see a reference for a general discussion group, so I'm creating an issue.

- json-editor version:  Using the interactive playground at https://pmk65.github.io/jedemov2/dist/demo.html

### Expected behavior
Expect the editor to allow me to enter multiple array entries and assign them UUIDs.
### Actual behavior
Editor shows a button to add an item, but clicking on it has no effect.  If I remove the "format":"uuid" from the string, then I can interact with the form, as usual.
### Steps to reproduce the behavior
Run the editor on the schema code pasted here.  Click on +item.  Nothing happens.

Then remove the "format" and see that it is possible to enter text.

```javascript
{
  "type": "array",
  "items": {
    "type": "object",
    "id": "arr_item",
    "properties": {
      "uuid2": {
        "type": "string",
        "format": "uuid"
      }
    }
  }
}
```

**Comment by VadimTikhonyuk** [comment]
Got same problem

**Comment by germanbisurgi** [comment]
It fixed, here an [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cWwhTIVKbBoaQIkTAAm1rTsKIoUmPADmCkjLLiKDZ2jmywUNi6QYieXpEABLYOClJUAI52qY4o7iJUbPZURGQi2IEgeGTwVWQgAL5sSfYAglJSQk7aUSBkbR1hMBHdTfG97YIp6ZlU2bn5IINqyGggzt36XDwKJmYWMFYrTZ0u0e6xvtKy5Ud1t3dsiMpgFLzmplLLC/BQ5mQ8cPAFFBVAxCHgwGAoG52hAACz1OpAA==)
