### ISSUE TITLE
Hide radiobutton fields

### ISSUE THREAD

**Issue by juanmafcuesta** [json-editor/json-editor#787]
### General information

- json-editor version:

### Expected behavior

By default, when the radio is in the "NO" option, it should not show me this text  "especificarRadio". I would like that when selecting the radiobutton "SI. ESPECIFICAR" the field "especificarRadio" would appear.
### Actual behavior

I have a radiobutton where I have 2 options and a textarea which should only appear to me if I choose the option "YES. SPECIFY". Currently always always shows me the textarea "YES. SPECIFY". I have added the watch, class ... but all the tests have been wrong

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
            'radioReclutamientoRealizadoPersonal': {
              'type': 'object',
              'title': 'Reclutamiento realizado por personal ajeno al equipo investigado',
              'properties': {
                'reclutamientoAjeno': {
                  'title': '¿El reclutamiento va a ser realizado por alguien ajeno al equipo investigador?',
                  'type': 'string',
                  'format': 'radio',
                  'enum': ['No', 'Si']
                },
                'tipoCompensacion': {
                  'title': '¿Recibe algún tipo de compensación?',
                  'type': 'string',
                  'format': 'radio',
                  '**enum': ['No', 'Si. Especificar']**
                },
                '**especificarRadio**': {
                  'title': ' ',
                  'type': 'string',
                  'format': 'textarea',
                  'minLength': 4,
                  'default': ''
                },
              },
            },
```

**Comment by finhaa** [comment]
Hi @juanmafcuesta ! I hope you're fine! 

You need to use the option "dependencies" wich we can view [here](https://github.com/json-editor/json-editor#dependencies). Anyway, for solving your problem you can define your JSON Schema like this:

```
{
  "type": "object",
  "title": "Reclutamiento realizado por personal ajeno al equipo investigado",
  "properties": {
    "reclutamientoAjeno": {
      "title": "¿El reclutamiento va a ser realizado por alguien ajeno al equipo investigador?",
      "type": "string",
      "format": "radio",
      "enum": [
        "No",
        "Si"
      ]
    },
    "tipoCompensacion": {
      "title": "¿Recibe algún tipo de compensación?",
      "type": "string",
      "format": "radio",
      "enum": [
        "No",
        "Si. Especificar"
      ]
    },
    "especificarRadio": {
      "title": " ",
      "type": "string",
      "format": "textarea",
      "minLength": 4,
      "default": "",
      "options": {
        "dependencies": {
          "tipoCompensacion": "Si. Especificar"
        }
      }
    }
  }
}
```

**Comment by juanmafcuesta** [comment]
Yesterday morning I had it! What I didn't find was doing the same for a checkbox! To show or hide another field if I select a checkbox. Might you help me? Thanks for your help @finhaa, really!!!

**Comment by finhaa** [comment]
I believe there's no approach to checkbox dependecies, but i could be wrong. This approach to radio input doesn't solve your problem?

**Comment by schmunk42** [comment]
Closing, please reopen if there's still an issue.
