### ISSUE TITLE
SCEditor display bug

### ISSUE THREAD

**Issue by jbmolle** [json-editor/json-editor#79]
Hi,
I'm using the SCEditor plugin and when I click on Move up / down or Property Add buttons the texts in SCEditor disappear.
If I switch the SCEditor to source code, I can see the sources. But the WYSIWYG text is blank.
I reported this bug on previous jdorn/json-editor. Other people had the same problem. Actually the problem is due to SCEditor using iframe and losing their content when the iframe is reloaded.
There was a pull request on jdorn/json-editor to add WYSIWYG with summernote (#440 on jdorn/json-editor). I tested summernote with jdorn/json-editor and it was working great!
Do you think it would be possible to merge the code of aguegu in this new official version.
Thanks,
JB

**Comment by schmunk42** [comment]
@germanbisurgi Could you try to create a test for this, I've recently updated the tests to use CodeceptJS.

**Comment by germanbisurgi** [comment]
- Test added.
- jbmolle is right. Sceditors iframes loose their content when the iframe is reloaded. And their are reloaded when the array and the DOM change.

**Comment by schmunk42** [comment]
> Test added.

Shouldn't the test fail then? Or which tests are you referring to?

**Comment by germanbisurgi** [comment]
Created a pull request that adds extra checks for SCEditors working into arrays #104

**Comment by pmk65** [comment]
@schmunk42 Has this been implemented in #106? If so the issue can be closed.

**Comment by germanbisurgi** [comment]
The SCEditor is in the json-editor/tests/codeceptjs/editors/string-test.js
in an @optional test scenario.
It proves that it breaks but does not block the CI.

At line 92 there is a comment ->

// the last 2 tests will fail because Sceditors iframes loose their content
when the iframe is reloaded.

Am Di., 23. Okt. 2018 um 11:45 Uhr schrieb Peter Klein <
notifications@github.com>:

**Comment by pmk65** [comment]
Moving up and down (array setup) doesn't seem to cause any problems with current release.
But `Properties->Add` still does.

**Comment by schmunk42** [comment]
Having a more resilient editor would be cool, but the underlying issue is often related to the initialization of the used plugins.

**Comment by pmk65** [comment]
I looked at some of the editors from the list at https://github.com/JefMari/awesome-wysiwyg#standalone and I really like [Jodit](https://github.com/xdan/jodit) It's small fast, can integrate with Ace Editor and doesn't use iframe but textarea.
I just did a small test of integrating it into JSON-Editor without any problems. (Can't post link, as it's made with a new version of the Playground I haven't finished yet)

**Comment by schmunk42** [comment]
In general it would be great to have a plugin-system to add an additional editor without modifying the "core" code CC: @germanbisurgi @marc7000

**Comment by pmk65** [comment]
The way I integrated Jodit didn't require any core changes, as I just extend the `strings` editor. If Jodit lib is not present, it just fallback to the default `string` editor. Options for Jodit can be set either globally using `JSONEditor.defaults.options.jodit` or from the schema. (single property)
I'll put up an example link later.
