### ISSUE TITLE
How to update schema dynamically?

### ISSUE THREAD

**Issue by vimniky** [json-editor/json-editor#793]
### Expected behavior
Set schema dynamically

### Actual behavior
`editor.setSchema` is not a function. I have checked the source code, and can't find a setSchema method or something like that.

### Steps to reproduce the behavior

```javascript
const editor = new JSONEditor(element, {
  theme: 'bootstrap4',
 schema: {"key": "value"}
});

// throws a error: `editor.setSchema is not a function`
editor.setSchema(myNewSchema)


```

**Comment by germanbisurgi** [comment]
there is no setSchema method. You have to destroy the editor and recreate it with a new schema

```
editor.destroy()
editor = new JSONEditor(container,{
    schema: newSchema
});

```

**Comment by vimniky** [comment]
> there is no setSchema method. You have to destroy the editor and recreate it with a new schema
> 
> ```
> editor.destroy()
> editor = new JSONEditor(container,{
>     schema: newSchema
> });
> ```

Thanks for your reply.  Actually I need to update schema frequently. Destroy and recreate the whole editor again sounds very heavy lifting. I also notice that when editing the schema via the  UI, `editor.schema` does not get updated accordingly. How can I get the latest schema data?

**Comment by germanbisurgi** [comment]
Updating the schema ist not very advisable in my opinion. I don't know what you want todo do but maybe what you need are [dependencies?](https://github.com/json-editor/json-editor#dependencies). I didn't understand your last two points/question

**Comment by vimniky** [comment]
> Updating the schema ist not very advisable in my opinion. I don't know what you want to do but maybe what you need are [dependencies?](https://github.com/json-editor/json-editor#dependencies). I didn't understand your last two points/question, sorry :(

In my case, I don't have a predefined JSON schema. Instead, I'm using json-editor to generate the schema itself. To make users' life easier, I have also set up an Ace editor side by side with json-editor and try to sync the editing result.

**Comment by schmunk42** [comment]
Changing the schema will very likely mess up the data, I think you need to implement this on your own.

But PRs are welcome if you have a good generic solution.

**Comment by PydPiper** [comment]
fyi for those that are searching this and found this post trying to dynamically update their schema generated forms. I took a look at dependencies and that wasnt going to work since each dependency has to have a unique name that would be hard to target downstream, so my solution was to break out my 'larger' complete schema into many smaller schemas and call each of the subsequent schemas with `editor.on('change')` and `$.get("uri/to/fetch/next/json/shema", function(data){}`
