### ISSUE TITLE
infoText is not supported in Array type

### ISSUE THREAD

**Issue by cschloer** [json-editor/json-editor#797]
### General information

- json-editor version: 2.3.0

### Expected behavior

when using the `infoText` option with the array type, an infoText button shows up.

### Actual behavior
Nothing shows up.

### Steps to reproduce the behavior

Direct link to example: 
https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJkpUoQpIyy4lCHJ5sutpFgJkaEDHgkAKlQAe5kJ8Sw8ADmAASuJCFQ3uIAvmwwUXROmtq6FmCc3OJsEFKQVFKwNBog8GQMJVo6hAFSrkEgMU1xispgFLwFeVJOLvBRhjxw8ApQqhUWeGBgULVkEAAsjTFAA==

**Comment by germanbisurgi** [comment]
fixed in #943
