### ISSUE TITLE
password option

### ISSUE THREAD

**Issue by AndyEdmonds** [json-editor/json-editor#80]
it would be great to have a password option obscuring a text field, but permitting input.

**Comment by germanbisurgi** [comment]
```
{
  "type": "string",
  "format": "password"
}
```

interactive example =>

https://json-editor.github.io/json-editor/?schema=N4IgLglmA2CmIC4QBMCGZUgDTgJ4Ad4kB7AIwCtYBjMbEfAJ2MIclgGdFR9V32B3Yg2Rc8hRCHZgGEAHYBzOgDMhAW3QSefQcJABfA0A&value=N4IgDghgzlDuD2AnAJiAXCEBfIA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by AndyEdmonds** [comment]
Thanks - couldn't find that in the docs.

**Comment by schmunk42** [comment]
@germanbisurgi Can you add it to the docs, please.
