### ISSUE TITLE
does `enum` support title and value?

### ISSUE THREAD

**Issue by shaojun** [json-editor/json-editor#800]
I want the enum show in Editor as a user friendly string value, but when generate the json, it output as a integer, I tried like this:

`"myEnumProperty": {
      "title": "PleaseSelect",
      "type": "integer",
      "enum": [
        {
          "value": 0,
          "title": "Good"
        },
        {
          "value": 1,
          "title": "Bad"
        }
      ]
    }`

but not work:

![image](https://user-images.githubusercontent.com/3241829/88257818-39f89b00-ccf1-11ea-89cd-c5b6fec93d17.png)

**Comment by jeremiecourlivant** [comment]
[Try to change integer to object.
](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgohTIh2DQ0g6ggKLwRdPQ4tSZq5aOvo6ZIhUAMpUOrZsZhaEYJzc4mxU3nSoANqgAG5yIpYADAkw2pYgAOJgYAAmIAC+LAVFlgCM5ZWEAEJkjU0Auk2jbIjKYBS8hg5GhDDwUIZkPHAmCaoMhHh1UIhQUmQQACzNTUA)

**Comment by shaojun** [comment]
found the solution:

`"enum": [ 0, 1, 2, 3 ],
    "options": {
      "enum_titles": [ "displayStr0", "displayStr1", "displayStr2", "displayStr3" ]
    }`
