### ISSUE TITLE
Unable to render form using oneOf

### ISSUE THREAD

**Issue by StacyMader** [json-editor/json-editor#803]
### General information

I am trying to use oneOf with an object and array, but unable to get the form rendered. Using the link below, you can see the schema is rendered as valid, but no form.

- json-editor version: 2.3.0

### Expected behavior

Form renders.

### Actual behavior

Form does not render, though schema is considered valid.

### Steps to reproduce the behavior

Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbAzgdwJYBcDGALOAuK5oZZhU0AbAU12IHEyB7AIwEMyp6AnKZCAE2QBuyXgFdWAfjgAaSEWKoAngAcqwPHCYArCulTTZRDRAoB5AGbUA2gbkE5cuKVSVqcOk1b7C94s179SeghWAAUOehUOUgp4ajNWeAoZb3tHZVV1YC0dPWBknxgNJUCIWLV8GwK4dHoyMmYlRN5qVA4RKhS5AF98quAlcMjosrw7AsLgFj4Ris6%2BgBIOCgtyuABiAHpeZZ40ZCD4DaneMsqfLrOiC7mey7GfR3IM4hMBCg4OYRivcbg%2FAP2wTIYQi72GcQSSUuE0UKlcwGYH2YCh%2BfTMnAAtsxcplUMxGGVeg9gCIIMgAI7tACSqAoGJmrXaRNSWWKgJm9z6NTqDSaLTaHXGtzmEzQdI50MMJHS8OyulRv2AmAofneABU6Up6rT4QAhZh8KAAWnwICgiTIZgAdMcoF0LnlJRMBqCoshvuVOYrjtQveNiItlvDNtszLsSocfcAnVcY9chZd40QALoGYUTUPh9m%2BypwKOjS5pOGrYAQEQYxjvBVSpwuEv6w1rasTChljFWSUABmZcgAjD2iAAmAcwADMl2TA6KEZzIuIrfLAH1ax68NY5xNO1Be53OwBZAASAC9myze1AAGy7w8nx0b4iD7eD6%2FH08OYCj7dX%2Fev6Nz1M3JU6ZSscEpzHAyqqhwGoYlq2LPHAABkEAEkoADcp5FghCJIiid7EqSFLUrS9L8kyhbAOiHBYjixAWjkmHAGKpGepKWHwm2lYcG%2B85th297djG%2FYxsOMbjv%2BI7EBEM6sfecALhiy5PDM67%2BlKW47j%2Bt6Se%2B57fjePHvo%2BvbPlphlSp%2Bvb6b%2BMYAQmgEpEm1xdMAQA&value=ETI%3D&code=EQehAIBUAsFNwGYHsA2KkHcCWA7A5uCrrAM7gCGATvALbk4Am5ALkpQJ4WPjXkNI4U7AHTgAmkgCu4AMb0KDBrMklWNWUgbxyAIyQA3bdx2x0GYQB0cWBOAAUAKxKwGWVpXC5V9GbCS3sRkxhACkAZQB5ADkAUVd3AEpwJxc3NmEtVUokdjsEgG4rFPi2cABecBxYDHBA%2FnNw6Li0yjt%2BGUkaWBxmYQBHSVgOMNNYGXc7C2AAYicBAFpU93nkShophIAaZJcWcgLgIA%3D&style=ETI%3D&theme=bootstrap3&iconlib=bootstrap3&object_layout=normal&template=default&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=1&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=0&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1

```javascript
{
  "switch": {
    "title": "Global or individual?",
    "type": "object",
    "oneOf": [
      {
        "title": "Global",
        "additionalProperties": false,
        "type": "object",
        "options": {
          "collapsed": true
        },
        "properties": {
          "bands": {
            "$ref": "#/definitions/bands"
          }
        }
      },
      {
        "title": "Overrides",
        "additionalProperties": false,
        "type": "array",
        "format": "tabs",
        "uniqueItems": true,
        "options": {
          "collapsed": true
        },
        "items": {
          "type": "object",
          "headerTemplate": "Band - {{ self.band }}",
          "properties": {
            "band": {
              "$ref": "#/definitions/band"
            }
          }
        }
      }
    ]
  },
  "definitions": {
    "band": {
      "type": "number",
      "title": "Band #",
      "enum": [
        0,
        1,
        2,
        3
      ],
      "options": {
        "enum_titles": [
          "0 100MHz",
          "1 600MHz",
          "2 1200MHz",
          "3 1600MHz"
        ]
      }
    },
    "bands": {
      "headerTemplate": "&nbsp;",
      "type": "array",
      "uniqueItems": true,
      "format": "select",
      "items": {
        "type": "number",
        "enum": [
          0,
          1,
          2,
          3
        ],
        "options": {
          "enum_titles": [
            "0 100MHz",
            "1 600MHz",
            "2 1200MHz",
            "3 1600MHz"
          ]
        }
      }
    }
  }
}

```

**Comment by StacyMader** [comment]
Oops, possible duplicate of #777- sorry if that is the case.

**Comment by germanbisurgi** [comment]
This is valid JSON but the JSONEditor does not understands what "switch" is in this case (property of a type object editor?).

Plus you are defining the root as object and then redefining it as array in the bands definition.

I think what you want is something like this:

```
{
  "title": "Global or individual?",
  "oneOf": [{
    "title": "Global",
    "additionalProperties": false,
    "type": "object",
    "options": {
      "collapsed": true
    },
    "properties": {
      "bands": {
        "$ref": "#/definitions/bands"
      }
    }
  },
    {
      "title": "Overrides",
      "additionalProperties": false,
      "type": "array",
      "format": "tabs",
      "uniqueItems": true,
      "options": {
        "collapsed": true
      },
      "items": {
        "type": "object",
        "headerTemplate": "Band - {{ self.band }}",
        "properties": {
          "band": {
            "$ref": "#/definitions/band"
          }
        }
      }
    }
  ],

  "definitions": {
    "band": {
      "type": "number",
      "title": "Band #",
      "enum": [
        0,
        1,
        2,
        3
      ],
      "options": {
        "enum_titles": [
          "0 100MHz",
          "1 600MHz",
          "2 1200MHz",
          "3 1600MHz"
        ]
      }
    },
    "bands": {
      "headerTemplate": "&nbsp;",
      "type": "array",
      "uniqueItems": true,
      "format": "select",
      "items": {
        "type": "number",
        "enum": [
          0,
          1,
          2,
          3
        ],
        "options": {
          "enum_titles": [
            "0 100MHz",
            "1 600MHz",
            "2 1200MHz",
            "3 1600MHz"
          ]
        }
      }
    }
  }
}
```

**Comment by StacyMader** [comment]
Got, it. Thanks for the explanation!
