### ISSUE TITLE
Error while resolving absolute URL $refs

### ISSUE THREAD

**Issue by schaap-astron** [json-editor/json-editor#809]
### General information

- json-editor version: 9.0.3    https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.0.3/jsoneditor.js

### Expected behavior
I expect absolute URLs in $refs to be resolved and used a subschema. 

### Actual behavior
absolute URLs in $refs are not resolved, even though I check them by following them in the brower, and they are served. 

## example 1: no refs (this works)
my json data:
```
{
  "name": "foobar",
  "email": "foobar@example.com",
  "$schema": "http://localhost:8000/api/schemas/subtask_template/user_without_ref/1#"
}
```

and here's the schema directly copied from the $schema URL http://localhost:8000/api/schemas/subtask_template/user_without_ref/1#
```
{
  "$id": "http://127.0.0.1:8000/api/schemas/subtask_template/user_without_ref/1/#",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "required": [
    "name",
    "email"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 2
    },
    "email": {
      "type": "string",
      "format": "email",
      "pattern": "@example\\.com$"
    }
  }
}
```
When providing the json-editor with the above json data and schema, it nicely renders the data and if I edit the email address with an incorrect pattern, the editor nicely shows me that the data is not valid according to the schema. Great!

## example 2: absolture URL refs (this does not work)
(Almost) same json data as above (but with a different $schema)
```
{
  "name": "foobar",
  "email": "foobar@example.com",
  "$schema": "http://localhost:8000/api/schemas/subtask_template/user_with_ref/1#"
}
```

and here's the schema directly copied from the $schema URL http://localhost:8000/api/schemas/subtask_template/user_with_ref/1#
```
{
  "$id": "http://127.0.0.1:8000/api/schemas/subtask_template/user_with_ref/1/#",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "required": [
    "name",
    "email"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 2
    },
    "email": {
      "$ref": "http://127.0.0.1:8000/api/schemas/common/base/1/#/definitions/email"
    }
  }
}
```

As you can see this schema is almost identical, but the "email" property now points with a $ref to a reusable "base" schema.
Following this $ref by hand proves that it exists, and here's the contents:
```
{
  "$id": "http://127.0.0.1:8000/api/schemas/common/base/1/#",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "email": {
      "type": "string",
      "format": "email",
      "pattern": "@example\\.com$"
    }
  }
}
```
When providing the json-editor with the 2nd example's json data and schema, it fails raising an MissingRefError:
```
MissingRefError
message: "can't resolve reference http://127.0.0.1:8000/api/schemas/common/base/1/#/definitions/email from id http://127.0.0.1:8000/api/schemas/subtask_template/user_with_ref/1/#"
missingRef: "http://127.0.0.1:8000/api/schemas/common/base/1/#/definitions/email"
missingSchema: "http://127.0.0.1:8000/api/schemas/common/base/1/"
```
To be absolutely sure that the reported missing schema "http://127.0.0.1:8000/api/schemas/common/base/1/" actually does exist and is fetchable, I clicked/followed the link and presto, the schema is just served.

So, why can't json-editor resolve my absolute URLs in $refs?

**Comment by schaap-astron** [comment]
I've read https://ajv.js.org/#ref and it appears to me that absolute urls are "ignored", or as they state it: "$ref is resolved as the uri-reference using schema $id as the base URI" 

I'm gonna give this a try with "relative" URLs to the $id base URI...
meanwhile any advice is welcome.

**Comment by schmunk42** [comment]
You should post that here I think: https://github.com/josdejong/jsoneditor/issues/
