### ISSUE TITLE
(question) how can i switch&validate $ref form? 

### ISSUE THREAD

**Issue by Kim-Hyunki** [json-editor/json-editor#817]
### General information
- json-editor version:2.3.0

(question)  - howt to switch&validate$ref form? without error 
i googleed it, but i can't found sccessful answer 

### Expected behavior
switch form1 and form2

### Actual behavior
get error `Value must validate against exactly one of the provided schemas. It currently validates against 2 of the schemas.`
and form is broken

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/
https://is.gd/paM6ps

```javascript
{
  "type": "object",
  "title": "switchForm",
  "oneOf":[
    {
      "type": "object",
      "title": "form1",
      "properties": {
        "form1":{
          "type": "string"
        }
      }
  },
  {
      "type": "object",
      "title": "form2",
      "properties": {
        "form2":{
          "type": "string"
        }
      }
    }
  ]
}
```

**Comment by schmunk42** [comment]
You must enable `no additional object properties` otherwise the editor could not detect the type, I think.

https://is.gd/4GjO1E
