### ISSUE TITLE
Falsy values inside an array turn into null inside editor.setValue

### ISSUE THREAD

**Issue by Cardinal90** [json-editor/json-editor#820]
### General information

When you have an `object` schema and set a value, which contains an additional array property, falsy values turn into `null` if they are not the first items in the array.

- json-editor version: 2.3.0

### Steps to reproduce the behavior

1. Visit https://json-editor.github.io/json-editor/
2. Paste in the schema:
```js
{
  "type": "object"
}
```
3. Click "Update Schema" button.
4. Paste in the form data:
```js
{
  "booleans": [false, false],
  "strings": ["42", ""],
  "numbers": [0, 42, 0]
}
```
5. Click "Update Form" button.

### Expected behavior

All the data values are correctly inserted into the form

### Actual behavior

The last value in all three arrays is inserted as `null`

**Comment by schmunk42** [comment]
Strangely, when you paste the data again, it works correctly.

**Comment by nick-chal** [comment]
Any updates on this issue? I would like to give it a go.

**Comment by schmunk42** [comment]
Yes please, that would be great!

**Comment by robocoder** [comment]
Sounds like #929 fixes this.
