### ISSUE TITLE
dependencies and required interaction

### ISSUE THREAD

**Issue by cschloer** [json-editor/json-editor#839]
### General information

- json-editor version: 2.4.0

(This is an enhancement request)

### Expected behavior
Fields whose dependency is not met (and thus are hidden) do not trigger `required` during form validation.

### Actual behavior
A hidden input will stop a form from submitting because it has no value. I understand why this doesn't happen right now, because the element is just set to `display: none;`. Maybe it would be nice to have a way to set the `options` parameter based on whether or not the dependency is met?

### Steps to reproduce the behavior
```
value_x: {
       title: 'value_x',
       type: 'boolean',
       format: 'checkbox',
},
value_y: {
       title: 'value_y',
       type: 'string',
       format: 'date',
       options: {
         inputAttributes: {
           required: true,
         },
         dependencies: {
           value_x: true,
         },
       },
},
```

**Comment by cschloer** [comment]
On the topic of dependencies, it would also be nice to be able to "clear" the value of the dependent field when the dependency is lost. In the above example, when value_x is set to `false`, value_y should be able to be set back to `""`

**Comment by germanbisurgi** [comment]
Can you provide an example schema?

**Comment by cschloer** [comment]
```

**Comment by cschloer** [comment]
I believe this should reproduce the originally requested feature. When `value_x` is false, the input for `value_y` still has the "required" attribute.
```
const schema = {
  type: 'object',
  title: 'Test Form',
  properties: {
    value_x: {
           title: 'value_x',
           type: 'boolean',
           format: 'checkbox',
    },
    value_y: {
           title: 'value_y',
           type: 'string',
           format: 'date',
           options: {
           inputAttributes: {
               required: true,
           },
           dependencies: {
               value_x: true,
           },
     },
  },
}
```

**Comment by rupebac** [comment]
for me, this is only working with required_by_default": 1, but with required_by_default": true is NOT working

**Comment by schmunk42** [comment]
@rupebac Please open a new issue with an example schema, actually we have several tests running with `required_by_default: true`.

**Comment by rupebac** [comment]
> @rupebac Please open a new issue with an example schema, actually we have several tests running with `required_by_default: true`.

hello, I have opened a ticket here:

https://github.com/json-editor/json-editor/issues/1183

issue is still there
