### ISSUE TITLE
Validation Message for Pattern appearing on properties without pattern validation

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#848]
### General information
We have two fields with validation patterns. The first is a pattern, the second is a length. The validation error message for the length is showing the pattern validation message incorrectly.

- json-editor version: 2.4.0

### Expected behavior
The proper validation message should show.

### Actual behavior
The pattern validation message is being shown.

### Steps to reproduce the behavior
1) Change the list group dropdown from null to string.
2) You'll see the validation message references pattern, even though no pattern definition is applied to that property
![image](https://user-images.githubusercontent.com/590274/96727991-4ab0bf80-1379-11eb-8c6a-b9599eead6ef.png)

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAJEtXqUIZVCgQUAelMda8ALQ61ZAHTSA5qYAmUskSjWADABZTO1kAYgV4MgZCAGUqIxh4ZwAZGEQoAEkoNQVYKGwqQhS0gAJo0SkMKmLM7LYoQQgC/TBObnE2NyoiBJhYBGQ0EAgyIyopeAcIqMHh0fHCAD0ACgBtMmsALwBBawAtXgBdNc2d3d9rAE5DgCoAfgBKTRAAXzZ8xKhlBxg3DRBZAAeSSoH2UqAATIxfK8QO9nJ8HBApJAxvUfn9AcDQagAIy+aFvEHwr5gT5jDFkIFEz4Q/HQmFIlFSWA0P64NJ/OTYADyRFQK1AuXyhVSUGKUwKdQaTUUUCkCWcLxYWikXUIIXcXR6fSQplmWXGk0iBVeKrV+g1nW68F6cF1cIRjMazME6OeBxh7L4zmRIggfyFMqKYp9on9bDI8EEvP5gulhDS8sSOV6wv0ADU5CIqCxiomFQpNKq+RbNdbbf1TA6SWSpEq440JCJsPI6qmZZnsNnc/Bm/J3c8YaqAI4iGCq34oFaw0UKL28UN+kAetiIZRgCi8MbIqQDEAJA1kHh2nK6GV4MiqvAIVlsEdjie8PCCXhWsjN8QoOXdkBuVIQAQX3vccqDcXgcEEVAiDkRAc0UddN0gPgEigmC4MkXgyDcP8dTkXgnVRGBWRQaDsFgiMOEpVCyLgv9EDIPB8i3HDeEsBBqPI39UgYpisBbMgIFgjjaO4xiqHw5FnRZAZSM4uiePEy9PBfLDJ1kkT6LEzCpGU3hVWkTo6xItCOlEpilKEV8qHyLJhLYEEFO03SsAgSDjJoiMdMsrB4DlMAyN4KBIDsrjNPMryX06GzFJbPSNxkkzQscizIusuJxIENI4ooYTByAA

**Comment by kameelyan** [comment]
Following up on this bug, anyone able to look into this?

**Comment by germanbisurgi** [comment]
Hi @kameelyan, i made a PR for this issue. The problem was that the JSONEditor could not distinguish the two properties names because they start with the same name   "list" ->  "list_group". A temp workaround is to rename one of the two. But i should be fixed with the PR

**Comment by kameelyan** [comment]
Hey @germanbisurgi, do you know when the NPM release will be for this?

**Comment by germanbisurgi** [comment]
I just asked for it so... i believe soon :)

**Comment by schmunk42** [comment]
https://github.com/json-editor/json-editor/issues/969
