### ISSUE TITLE
Getting and setting values to a node via it's editor does not update the root json data

### ISSUE THREAD

**Issue by kameelyan** [json-editor/json-editor#849]
### General information
The 'edit json' button data is not being updated properly when setting value to a specific node in the data.

- json-editor version: 2.4.0

### Expected behavior
I expect the data in the edit json button to be accurate to the current data shown in the form.

### Actual behavior
The data is not properly updated when done via setValue on a specific node in the data.

### Steps to reproduce the behavior

Direct link to example: https://is.gd/tMG5uy

Looking at the Schema tab, you can see we are setting the modules property to two values in an array, Foo and Bar.
The JS/CSS tab, you can see we are getting the value of the modules via a specific node as defined in the documentation: 

`jseditor.getEditor('root.modules')`

The console log properly returns a value of [ ] after setting the value to [ ]. The form also properly shows there are no modules in that property. But clicking the 'edit json' button and viewing the data, the two modules are still in the data definition.
Furthermore (and most importantly), calling getValue on the primary instance of jseditor also returns the values in the modules array (incorrectly).
```
var x = jseditor.getValue();
console.log(x.modules); // Incorrectly returns 2 items in the array
```

**Comment by kameelyan** [comment]
We're using json-editor in a production environment right now and this is a pretty major breaking change for us. Mean to say that last night, but wanted to add it now.

**Comment by schmunk42** [comment]
This was OK in 2.3.x?

**Comment by kameelyan** [comment]
Hey @schmunk42 - we did some testing for you:
2.5.1 -- not working
2.5.0 -- not working
2.4.0 -- not working
2.3.0 -- not working
2.2.1 -- not working

We couldn't go further back as that introduces breaking changes.

**Comment by kameelyan** [comment]
Another piece, we found that if you first set the array to an empty array [ ], then set it to the value you want, it'll properly update the root.

An example of this:
https://is.gd/LeWQXx

**Comment by kameelyan** [comment]
Following up on this bug, anyone able to look into this?

**Comment by germanbisurgi** [comment]
I don't know why but i can't reproduce the error. I found that the array starts empty "`[]`".
After `setValue([])` remains the same empty array and its reflected in the edit json too (before and after).

**Comment by kameelyan** [comment]
@germanbisurgi I think you may be looking at the second example link of it working? The original post still isn't working.

I'll try and detail the steps to follow along with.

1) Go to the schema tab, verify that it's setting the initial data for the modules property to 2 items (Foo and Bar).

2) Go the JavaScript tab, verify it's logging the initial data for the node 'root.modules' (line 8), setting it to an empty array (line 9), and then logging the value again (line 10). Then it logs the data for the data.modules that's retrieved from the entire schema value, essentially 'root' (line15).

3) Open the console log, you should see 3 log lines:
a) It shows the 2 items logged from 'root.modules'.
b) It shows an empty array because we emptied 'root.modules'
c) It shows 2 items that shouldn't exist, because the modules property was emptied in **b**.

4) Go to the Form tab, and click on the json button. It's showing 2 items in the modules array, even though it should have been set to empty by line 9 in the javascript.

**Comment by germanbisurgi** [comment]
@kameelyan I tested on a fork of the repo to be sure that i am working with the right state of the library because has changed quite a bit in the last months.

**Comment by kameelyan** [comment]
@germanbisurgi is the interactive playground not fully up to date?

**Comment by germanbisurgi** [comment]
The 2 interactive pages use a CDN version with the latest build. I prefer to test with a fresh build because i will be sure that if is not working there then it needs a patch. Using older versions (also weeks) can make you work on problems that were already solved.

**Comment by germanbisurgi** [comment]
Assuming this issue were solved in new releases. Feel free to reopen.
