### ISSUE TITLE
Problems with requiring radio selection

### ISSUE THREAD

**Issue by majkinetor** [json-editor/json-editor#854]
This should work:

```json
{
  "properties": {
    "test": {
      "type": "string", 
      "format": "radio", 
      "default": "",
      "minLength": 1,
      "enum": [ "yes", "no"]
    }
  }
}
```

I.e. if nothing is selected validation fails, if anything is selected validation will pass.

Alterantives:

```json
{
  "properties": {
    "test": {
        "type": "string", 
        "format": "radio", 
        "default": "",
        "enum": [ "yes", "no"]
    }, 
    "test*": {
        "type": "string",
        "minLength": 1,
        "options": {
            "dependencies": {
                "test": ""
            }
        }
    }
  }
}
```

This without a selection lists error:

```
[
  {
    "path": "root.test*",
    "property": "minLength",
    "message": "Value required",
    "errorcount": 1
  }
]
```

Another method would be:

```json
{
  "required": ["test"],
  "properties": {
    "test": {
        "type": "string", 
        "format": "radio", 
        "default": "",
        "enum": [ "yes", "no"]
    }
  }
}
```

Which lists error:

```
[
  {
    "path": "root",
    "property": "required",
    "message": "Object is missing the required property 'test'",
    "errorcount": 1
  }
]
```

I believe first solution should be possible as it is self contained and logical, and less problematic in more complex scenarios.

**Comment by schmunk42** [comment]
> I.e. if nothing is selected validation fails, if anything is selected validation will pass.

When the property is not required, the validation passes.

See https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgIUyFSmwaGkFBri0RwRCqFEUKTHgBzBSRllTIKWQAmcBV6pEZCLY7gp09gAyVI5QyqgAjGzRInSoANogggZskiAAugC+RWyIymAUvLraUsgoIPbGnjxw8AqxalZ1eGBgUDaeEAAsClJUAI4iMKNevHiCvP6BwaaB2IhUbD6IEALzoxNTVDM4gqir6yVlFZB89mdyFyCSvN4+sAhyvFo6ejAGKOcNiAyBwyAAPe5rIFbMh4bBUSpvXgcWitAEPaEwRCw+G8LDYAQQdaQx4wuEI76WX7/QGbLE4hFkKSeeavEmY7Hkl7MoS8UbSfxSdl0zm4pkshZUeHGYUgaIM7kSrAQU7oqFscW8rDwWxgNa8KCQWVksU8+b+aWMgl88q1WkgE2Ms2Sy38Mg2G0UdlFIA==

**Comment by majkinetor** [comment]
> When the property is not required, the validation passes.

Take for example the other one I provided with dependency - nothing is required, however verification still fails.

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgIUyFSmwaGkFBri0RwRCqFEUKTHgBzBSRllTIKWQAmcBV6pEZCLY7gp09gAyVI5QyqgAjGzRInSoANogggZskiAAugC+RWyIymAUvLraUsgoIPbGnjxw8AqxalZ1eGBgUDaeEAAsClJUAI4iMKNevHiCvP6BwaaB2IhUbD6IEALzoxNTVDM4gqir6yVlFZB89mdyFyCSvN4+sAhyvFo6ejAGKOcNiAyBwyAAPe5rIFbMh4bBUSpvXgcWitAEPaEwRCw+G8LDYAQQdaQx4wuEI76WX7/QGbLE4hFkKSeeavEmY7Hkl7MoS8UbSfxSdl0zm4pkshZUeHGYUgaIM7kSrAQU7oqFscW8rDwWxgNa8KCQWVksU8+b+aWMgl88q1WkgE2Ms2Sy38Mg2G0UdlFIA==

**Comment by schmunk42** [comment]
Yes, the error is

```
[
  {
    "path": "root.test*",
    "property": "minLength",
    "message": "Value required",
    "errorcount": 1
  }
]
```

What would you expect?

**Comment by majkinetor** [comment]
> When the property is not required, the validation passes.

Even when the property is required, but it is empty, validation passes (if `remove_empty_properties` is not set). This is somewhat confusing because there is almost zero semantical difference between `{}` and `{ "x": "" }` or  `{"x":null}`, and with `required` option set, first one will not pass validation and second one will pass it thus you need to set special requirements on property itself (such as `minLength`).  

I think the main point of confusion arises here because of the bug I described in more detail in #343.
