### ISSUE TITLE
Inhibit pre-selection of radio button and dropdown element

### ISSUE THREAD

**Issue by faustmann** [json-editor/json-editor#855]
### General information

- json-editor version: 2.5.1

### Expected behavior
No pre-selection of a radio button of question A resp. a dropdown item of the gender list.

### Actual behavior
The first radio button resp. the first drop down item is selected.

### Steps to reproduce the behaviour
Option: Object Properties required is set

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgohTIh2DQ0gYiACpkA1jHgBzAFkqABNMMlgEVzMLQkQoKT9/UxhtSxAARREaSPgAAgBBBRIZCMIpMjCwBSp4ETpUAG0QAE0XNgA5aoBdNkhc5DQQAWExQmVpGAAvUjkQAF95tn9akMNo83T4xICauoaUZtkdYrU5XT6oVSkQbsWlxQmKXkMHI0I5CiFkNiu1dLwYDAUG2ZAgABYFFIqABHEQwaEhXh4QS8NZEMgibDiFAJbJsMKICAjXjQuEI0K8HCCVAY7CIKhsRBPKnQXh+WlyBlsSS8SphXJyXj2RxSZyDOnckBkDhkAAenPpjJAhLIeB0LwFvA4xkVUtV6qovCw2AEEAZeuVBo1IosYpgLhQkqt7jVGrIUgqqP5loJrsNfM9QlJVGkaxuTq5LsQbqNHq9aKoOiglmdbFqscDCawEBpkaVbHjwaw8ASYHpvCgkF9Kv97qDqLWybjptJYAoEqjfpjAaLjaTVBT/DI8TbFEtiyAA==

```javascript
{
  "title": "Person",
  "type": "object",
  "properties": {
    "isA": {
      "type": "string",
      "title": "Question A",
      "format": "radio",
      "enum": [
        "Yes",
        "No"
      ],
      "options": {
        "layout": "horizontal"
      }
    },
    "Gender": {
      "type": "string",
      "enum": [
        "male",
        "female",
        "other"
      ]
    }
  }
}
```
Is it possible to inhibit this preselection? In my case, it is important that the user actively chooses an option.
In the wiki I function editor.setValue(value, initial=false) where the parameter initial controls the initial set value. But I could not find how to set it via a json schema.
I also want to say thank you for the useful library. :)

**Comment by schmunk42** [comment]
You can set `"default":""`, see https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgohTIh2DQ0gYiACpkA1jHgBzAFkqABNMMlgEVzMLQkQoKT9/UxhtSxAARREaSPgAAgBBBRIZCMIpMjCwBRCqIjIRbHErBSp4ETpUAG0QAE0XNgA5aoBdNkhc5DQQAWExQmVpGAAvUjkQAF8Ntn822qlo83T4xIDW9s6UHtkdYrU5XXGoVQORre3FRYpeQwcjQjkFCEyDYzzU6TwYDAUBOZAgABYFFIqABHEQwZEhXh4QS8Wr1RrNBLZNhhRAQWa8ZFojGhXg4QSoerYRBUNiIL706C8PxMuSstiSXiVMK5OS8eyOKTOKbMgUgMgcMgADz5LLZIDJZDwOh+ot4HGMavlWp1VF4WGwAggrONGtNuslFmlMBcKDl9vc2t1ZCkFVxIrtpK9ZuFfqEVKo0n2Qc1IZ94dxtR0UEsHrYbW95t9/otkEZ7v5GpzEaw8ASYBZvCgkFjDuzibxVBT2atVLAFFlReDiCzYdzyaoqf4ZHi7Yodq2QA=

**Comment by faustmann** [comment]
Thanks for the quick reply.

But ```"default":""``` does not work with the Gender input (string, enum combination), isn't it?

**Comment by schmunk42** [comment]
Yeah, you would need an empty value and ie. `minLength > 0`.

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgohTIh2DQ0gYiACpkA1jHgBzAFkqABNMMlgEVzMLQkQoKT9/UxhtSxAARREaSPgAAgBBBRIZCMIpMjCwBRCqIjIRbHErBSp4ETpUAG0QAE0XNgA5aoBdNkhc5DQQAWExQmVpGAAvUjkQAF8Ntn822qlo83T4xICauoamwgU6PwAZNv8oZVQARjY2ju6QG7ldNiIaj+CjAz0MIBGW22ikWFF4hgcRkIcgoQmQbDBDEIeDAoJOZAgABYFFIqABHEQwUkhXh4QS8Wr1RrNBLZNhhRAQWa8UkUqmhXg4QSoerYRBUNiIWGC6C8PwiuTitiSXiVMK5OS8eyOKTOKaipUgMgcMgADwVYolIA5ZDwOnh6t4HGMFsNNrtVF4WGwAgg4tdVvd9u1Fl1MBcKANgfctvtZCkFXpaoD7JjHtVCaEPKo0n2KetabjmfptR0UEsUY+8Fjnvjia9kGFkcVVrrWaw8ASYDFvCgkHzQdrxYZVDLtZ9PLAFH1LdTiBrGfrpao5f4ZHik4oAa2QA==

**Comment by faustmann** [comment]
Thank you very much for your support :)
