### ISSUE TITLE
How to display an informative text only, without any question?

### ISSUE THREAD

**Issue by costateixeira** [json-editor/json-editor#857]
### General information
I want to display text like "Please skip this section if..." or "This question is about...". I do not want to use infoText. 
Setting as a readOnly string with a default value is one option, but, well, this looks like a question. Are there other ways to do this and display some text ?

- json-editor version:

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by schmunk42** [comment]
```
{
  "title": "json schema example",
  "type": "object",
  "description": "This is an example schema. Please edit me..."
}
```

How about using it on the top level?

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIda8AARLVsw1QAeZOhB0KogiLpTsuPBQBMaGKTGhx4QgAVZRhEQzDDMiNLa1sqYxU1MgA6QwAFHTJEBKoPGChDBhAAXzZEZTAKXiopKWlkFxh4KFqyHgD7U2cQPDAwKEQoKTIIABZSkqA

**Comment by costateixeira** [comment]
Hi, and thanks. That creates an empty box for the object, which means that I can only add it at top level indeed. Is there a way to add such text for example between 2 questions?

Thank you

**Comment by germanbisurgi** [comment]
There is the type info editor

**Comment by costateixeira** [comment]
Thank you, I had missed the info type. That solves my issue
