### ISSUE TITLE
how to delete an array row programmatically

### ISSUE THREAD

**Issue by Ypiskare** [json-editor/json-editor#860]
### General information

- json-editor version:  https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

### Expected behavior

Need to delete an array row programmatically

### Actual behavior

There is addRow() method for array, but but I couldn't find a method for delete row.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

**Comment by germanbisurgi** [comment]
there is no deleteRow() method and i believe there was never any intention of adding a feature to add or remove items programmatically. That addRow() is a sort of private method of the array editor
