### ISSUE TITLE
Question about GetValue()

### ISSUE THREAD

**Issue by mtxxx** [json-editor/json-editor#864]
- json-editor version: 2.5.1

Is there any way, how to get only values, entered into a form by a user?

editor.getValue() function return ALL data (including not editable).

I'm looking to way, how to get only editable data (user can edit, delete or change this data).

**Comment by germanbisurgi** [comment]
Not really. You could make everything "not required" and add the property `show_opt_in: true`. So the User should activate (easy visible checkbox at the corner of the editor) the editor to fill it
