### ISSUE TITLE
editor.setValue with a undefined enum value will cause that property disappeared

### ISSUE THREAD

**Issue by tlyau62** [json-editor/json-editor#866]
### General information

- json-editor version: 2.5.1

### Expected behavior

That enum field should not be disappeared

### Actual behavior

That enum field is disappeared.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

1. use this schema
```javascript
{
  "title": "enumclass",
  "type": "object",
  "properties": {
    "zzz": {
      "title": "zzz",
      "type": "string",
      "default": "",
      "enum": [
        "name",
        "name2"
      ]
    }
  }
}

2. set zzz value to empty on the form

3. click the "update form" button on the right panel.

4. now you will see that the field is gone.
```

**Comment by schmunk42** [comment]
You need to use `required_by_default` or `show_opt_in`.
You can enable the property again with the **Properties** button.
