### ISSUE TITLE
Value must be one of the enumerated values.

### ISSUE THREAD

**Issue by tlyau62** [json-editor/json-editor#867]
json editor fails to render if the enum contains the null value. The editor will report that "Value must be one of the enumerated values.".

This is the schema:
```json
{
  "title": "enumclass",
  "type": "object",
  "properties": {
    "zzz": {
      "title": "zzzz",
      "type": [
        "string",
        "null"
      ],
      "enum": [
        null,
        "name",
        "name2"
      ]
    }
  }
}
```

**Comment by schmunk42** [comment]
Why do you add it also to the enum?

You can not mix types in the enum, I think and It's already `null` when you change the type.

**Comment by jsphj** [comment]
@tlyau62 Were you ever able to find a workaround for this? I'm trying to work with nullable enums and am running into the same problem. [This issue](https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/233) makes it seem like your schema conforms to the spec and that this ought to work.

**Comment by klaussilveira** [comment]
Same boat over here. I would like to create a null option in the enum. You can choose one of the options of the enum, or null.

**Comment by schmunk42** [comment]
The tricky part is the mixure of types. Type selection is probably the very core ui function if needed.
It looks rather hard to me to trigger this functionality from a dropdown.

This would be a correct [schema](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOgXQhG870QyDYMTmJzATxeUHus3mMEWaBAAC9iWCQBCoSgicTCfcUVhUABtECOSjte7wFQAgC6bBhhEZIAIxHZRCwACYQFyAL4y5F9YWUqhgMBQFn4CAAFhAMqAA===):
```
{
  "title": "enumclass",
  "type": "object",
  "properties": {
    "zzz": {
      "title": "zzzz",
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "name",
        "name2"
      ]
    }
  }
}
```

What might be easier is to do this with a watcher and fill a hidden or read-only field somehow.

**Comment by schmunk42** [comment]
Do you really need `null` or could it also be an empty string or be missing completely?

**Comment by klaussilveira** [comment]
I think it could be missing completely. The use case allows for the option to be null as default. Imagine this:

```
type: 'integer',
enum: [1, 2, 3],
default: null,
```

So, field will start with `null`, and people will be able to choose 1, 2 or 3, but can't return back to null once it was set.

**Comment by schmunk42** [comment]
`show_opt_in` might be an option, see [example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUBXRBTA+vAhgLa75RQBOMARulFsihelgDQgTliHQ5VYBmYcrgAmWADZY6qJqxCZRA/OnFQcAN3zjmDWW0L4AHjjHQAFqgAMbGmQQ5EUUrkJgxqAIxsAxvmwOsJBhYdVwOSCxyKABPAPxybwtGcmY2RDMwAHccSM5yBhAYeDpyfG9YBBA2cO41CD86HANjSXgAcygzHGEysywRVH4tbDZhV1CcIfF/cIhI2HpB4blAwQTcbwRHJem5GE34cWpUEEFi/Ez6LiwAVirwKgArLHKccXxosFoT+CEDcXuiESWAMqFAsCgkhOgXQhG870QyDYMTmJzATxeUHus3mMEWaBAAC9iWCQBCoSgicTCfcUVgTo5KO17jDCKgANogAjEe7crAAJhAAF0AL5i5F9HmUqhgMBQRn4CAAFnuwgAjugYMIRLxYmIhiosSgpiMQCIYIgIO9YurNdqcAhxNEdqb0lkHTwijIUnJfjh8CJzRUCOIcDioniGCa5PhHkYXXJzYh8FRJDkgzhHohKsblmwkym05txO8INgE/mLYWwpw5hH8dHK8nUyRyKVYgGBrndk3q/62x9ulghGJyBWzVWW/32yYJFJ6d3TYE+/EZ5sIM7FzGB7EDhQwNMcFBIOOC1PV4OxJJGlpQ5xMlG8xPm2mL3q540EWp7wmxUA=).
