### ISSUE TITLE
Option: form_name_root does not seem to chance "root" to different value

### ISSUE THREAD

**Issue by mstaragrieb** [json-editor/json-editor#869]
### General information

- json-editor version: @latest

### Expected behavior
When changing the value in the schema "options" it should change the attributes created from root[] to {form_name_roo}[].

### Actual behavior
After change attributes still show "root"

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJhO3cW1hRsulCADCZKQsiwEyNCAAmMRGTxneWbAIiI5lBSIlRsbh5eVLxUbnwctPCowaHh7p7eEFKQVFKwNMkhYcTSdLzwZAy82WDiFiRgIAC+bFk5eTAFzrIA1uaa2uaKwTDwAOYKVPAidKgA2iAAKmDC5AoAQgCyAOoKABIILmQKAGLSLgqWqgBuggoAarsAui0gdGAuVPLOWjqEiCNxs02IIqDYNCBfkNRlAqGNcpNprMUHMAIwATnRjBYGPRADYcZiAOyE9EADlJ6JYACYAAz0mn01GM2nUlkAZhZABYWdi6bSCfySfyKfyqXTUbTGajmRK2RLORKuU9wlQiGQRNg6iLXh4iFQtBCoYQYXCEWwSDIyHUQFJraMJmxZAAPGB0GaEZhsKjOjDYESIGDXKibMiu93I9XYQJsKRglw4O4oKOBJpptiIZRgCgxKTZKROECmu08OBJYyqBiEPBgWoAu0QLnNJpAA===

```javascript
{
  "type": "object",
  "title": "Car",
  "options": {
    "disable_collapse": true,
    "disable_edit_json": true,
    "disable_properties": true,
    "form_name_root": "foo"
  },
  "properties": {
    "make": {
      "type": "string",
      "enum": [
        "Toyota",
        "BMW",
        "Honda",
        "Ford",
        "Chevy",
        "VW"
      ]
    },
    "model": {
      "type": "string"
    },
    "year": {
      "type": "integer",
      "enum": [
        1995,
        1996,
        1997,
        1998,
        1999,
        2000,
        2001,
        2002,
        2003,
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014
      ],
      "default": 2008
    },
    "safety": {
      "type": "integer",
      "format": "rating",
      "maximum": "5",
      "exclusiveMaximum": false,
      "readonly": false
    }
  }
}
```
Just don't know if this is known thing or I screwed something up.

**Comment by schmunk42** [comment]
Probably related to https://github.com/json-editor/json-editor/pull/863

Was this working correctly for you before?

**Comment by mstaragrieb** [comment]
No, trying to get it working, did I screw something up?

**Comment by mstaragrieb** [comment]
Been a minute on this, so I went hacking into the unmin script. I found the issue:
`if (this.jsoneditor.options.form_name_root) this.formname = this.formname.replace(/^root\[/, "".concat(this.jsoneditor.options.form_name_root, "["));`
    
If this is changed to:
`if (this.jsoneditor.schema.options.form_name_root) this.formname = this.formname.replace(/^root\[/, "".concat(this.jsoneditor.schema.options.form_name_root, "["));`
    
It works.

**Comment by mstaragrieb** [comment]
Also if set outside of the schema it works: `JSONEditor.defaults.options.form_name_root`

Weirdly     
`"schema": {
      "type": "object",
      "title": "Evernorth Questionnaire",
      "options": {
        "disable_collapse": true,
        "disable_edit_json": true,
        "disable_properties": true,`
triggers those to be disabled... Which feels like a mismatch somewhere.

**Comment by mstaragrieb** [comment]
Regardless I got it working, I am willing to close.

**Comment by mstaragrieb** [comment]
On further digging, if set with JSONEditor.defaults.options.form_name_root there seems to still be mismatching:
The schemapath and schemaid both still say root.

**Comment by germanbisurgi** [comment]
Yes, we fixed this in the lasts PRs. A release will be soon available

**Comment by schmunk42** [comment]
@mstaragrieb We've just merged https://github.com/json-editor/json-editor/pull/876 - please have a look

**Comment by schmunk42** [comment]
From your comment https://github.com/json-editor/json-editor/pull/876#issuecomment-744605452 I suppose we can close this. Thanks for reporting!
