### ISSUE TITLE
Spectre theme does not render checkbox inputs in a table

### ISSUE THREAD

**Issue by mstokes-f5** [json-editor/json-editor#873]
### General information

- json-editor version: 2.5.1

### Expected behavior
When an array of objects is rendered using the table format and contains a boolean property with the checkbox format the boolean property should get a checkbox in the table.

### Actual behavior
The bootstrap4 theme behaves as expected, but the spectre theme results in no checkbox.
![image](https://user-images.githubusercontent.com/61211686/101380906-f8652880-386a-11eb-8101-82f682061f6c.png)

### Steps to reproduce the behavior
The following schema can be used to reproduce the issue:

```json
{
  "type": "object",
  "required": [
    "members"
  ],
  "properties": {
    "members": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "intval",
          "boolval"
        ],
        "properties": {
          "intval": {
            "type": "integer",
            "default": 0
          },
          "boolval": {
            "type": "boolean",
            "default": false,
            "format": "checkbox"
          }
        }
      },
      "format": "table"
    }
  }
}

```

### Speculation on cause

I believe this happens since the checkbox does not have a label when rendered in a table, and `spectreTheme.getFormControl()` does not have a branch that handles checkboxes without a label. However, fixing that still results in inconsistent styling on the checkbox. In other words, a checkbox rendered in the table has a different style than one rendered outside the table.

**Comment by germanbisurgi** [comment]
fixed in #943
