### ISSUE TITLE
How to use this module in Angular-10

### ISSUE THREAD

**Issue by joshi-anshul** [json-editor/json-editor#886]
Hello,

Just a question that how can we use this module in Angular-10? Is there any alternative of this, that supports with Angular 10?
Thanks

**Comment by joshi-anshul** [comment]
@schmunk42, any help would be highly appreciable

**Comment by joshi-anshul** [comment]
Hello @schmunk42 @amk0 @germanbisurgi 
I'm waiting for the response :)

**Comment by germanbisurgi** [comment]
I used once with Vue importing it as a javascrupt module (import jsoneditor from json-editor). It does not have reactive features and it was made with no frameworks in mind

**Comment by joshi-anshul** [comment]
Thanks for the response @germanbisurgi 

short question - how can we use this selector -> `<json-editor schema="mySchema"></json-editor>`
is there any other module that need to be installed? Because I have not seen any selector in documentation


also when I tried to use `basic.html` code in angular-10 then I am getting following errors-
`main.ts:12 TypeError: json_editor__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor`

On this line -------------->	`var editor = new JSONEditor(document.getElementById('editor_holder'),{`

**Comment by joshi-anshul** [comment]
Now It's working for me

**Comment by IanMayo** [comment]
Hello @joshi-anshul  - I'm seeing the 'is not a constructor' error at runtime.

Can you share how you solved the issue please?

**Comment by guilhermebentomarques** [comment]
Hi @joshi-anshul, same of the @IanMayo  here.. Did you manage to solve the issue on angular 10/11 ?

Can  you share how you solve it?

Cheers
