### ISSUE TITLE
properties with enumSource & watch are not updated with jsoneditor.setValue(...

### ISSUE THREAD

**Issue by LAGENCECREE** [json-editor/json-editor#891]
Hello 
great lib, i'm new on it,

i discover a possible limitation using enumSource+watch,

```
"properties": {
              "dynamic_dropdown": {
                "type": "string",
                "title": "I'm a dynamic dropdown based on an array located on other node  :",
                
                "watch": {
                  "mylist": "root.myarray"
                },
                "enumSource": [ {
                  "source": "mylist",
                  "value": "{{item.id}}"
                } ]
              }
}
```
this technic work great to dynamicaly populate a select dropdown from another node,

**but when i reload data** _( jsoneditor.setValue( JSON.parse( JSON.stringify( SAVEDDATA) ) ); )_ 
**previously generated by json editor** _( SAVEDDATA = JSON.stringify( jsoneditor.getValue()) ) ,_

all the field are updated **excepted thoses with enumSource which initializes blanks.**

any idea ?

**Comment by niebert** [comment]
On change events cause the update of the enumSources an `setValue()` causes not an onchange event. If `setValue()` would cause an `onchange` it cause the risk that update `setValue()` could trigger an infinited onchange-setValue loops. A workaround could be trigger the onchange handler for the watched source content. Maybe a `watch_update()` after `setValue()` can be called for the root node. But that is just a recommendation, that might not be the best solution.

**Comment by LAGENCECREE** [comment]
thanks for your response , i will investigate this soon. 
i kept disabled ENUM field in the meanwhile.
