### ISSUE TITLE
Is it possible to specify the default selected item of a oneOf

### ISSUE THREAD

**Issue by kazepreaux** [json-editor/json-editor#895]
### General information

- json-editor version: 2.5.1

### Expected behavior
I would like to be able to specify within the JSON Schema which of the **oneOf** item is selected by default.

### Actual behavior
I have not found any way to do so

### Steps to reproduce the behavior
I used the **Name (oneOf)** example, and tried to get **First and Last Name** to be selected by default, instead of the 1st one.

I tried using **default** before the `"oneOf": [` in different ways, but I guess default would do nothing:
`"default": "First and Last Name"`
`"default": [ "First and Last Name" ]`

**Comment by schmunk42** [comment]
You can select the `oneOf` by providing an appropriate **default value**.

**Comment by kazepreaux** [comment]
Hi Tobias Munk, 
Thanks for the quick reply.
So if I take the example of **Name (oneOf)** on your playground, how would the JSON Schema look like with the **default value**?

I have tried providing `"default": ` like below:


```json
{
  "type": "object",
  "options": {
    "keep_oneof_values": false
  },
  "properties": {
    "type": {
      "type": "string",
      "options": {
        "hidden": true
      }
    }
  },
  "default": "first-last-name",
  "oneOf": [
    {
      "title": "Full Name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "fullName"
          ],
          "options": {
            "hidden": true
          }
        },
        "fullName": {
          "type": "string",
          "title": "Full name"
        }
      },
      "type": "object",
      "options": {
        "keep_oneof_values": false
      }
    },
    {
      "title": "First and Last Name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "first-last-name"
          ],
          "options": {
            "hidden": true
          }
        },
        "firstName": {
          "type": "string",
          "title": "First name"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        }
      },
      "type": "object",
      "options": {
        "keep_oneof_values": false
      }
    },
    {
      "title": "Other name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "other-name"
          ],
          "options": {
            "hidden": true
          }
        },
        "otherFirstName": {
          "type": "string"
        },
        "otherLastName": {
          "type": "string"
        }
      },
      "type": "object",
      "options": {
        "keep_oneof_values": false
      }
    },
    {
      "title": "More name",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "more-name"
          ],
          "options": {
            "hidden": true
          }
        },
        "moreFullName": {
          "type": "string"
        }
      },
      "type": "object",
      "options": {
        "keep_oneof_values": false
      }
    }
  ]
}
```

However it is not working as expected, as it is not selected `first-last-name` by default when generating the form.

Thanks in advance

**Comment by schmunk42** [comment]
`default` should be an object like

```
{
  "firstName":"",
  "lastName":""
}
```

**Comment by kazepreaux** [comment]
Ok, works great thanks!

I guess it would be good to add a clear example in the documentation, to make it easy to understand.

Do you want me to post what would help me and others understand the concept of default, so that it can get added to your documentation? (I might be able to post something at some point, but might not be today).

**Comment by schmunk42** [comment]
Sure, PRs always welcome.
