### ISSUE TITLE
Is it possible to have multiple "oneOf" containing object type properties with the same name?

### ISSUE THREAD

**Issue by kazepreaux** [json-editor/json-editor#896]
### General information

- json-editor version: 2.5.1

### Expected behavior
No validation error

### Actual behavior
Validation error:
Value must validate against exactly one of the provided schemas. It currently validates against 2 of the schemas.

### Steps to reproduce the behavior

Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbALgTwA4FM4C5bAPYCMArVAY3jgBpIY4dl4BLHCAZ0ynGhmwGtVVkA%2Bk1Q4AZgIBuAQwA2AV1StgWUbObpOAX0qcaEVAHlRbANpUuHLlzgN4M9Mux4ZOYtygBGCuatwpAE396BiZZAAUAJ1pUCIZFNlUZdR0ramBkKLRY%2BnjHS1S0gFkpeghI6OzcrHyCtNt7Njhi0qhyrLilFNq0jIqOthru7AARRWII%2BjpGCAGfIbrghsc4UeZxyZCZ4C75upQHLDhmeAmIAHM4Oe7tK9q4ADVZBVnOXewAEnp%2FRuAAYmdXNwvNtbt0bIsDthHvIHDtdnpDMZHGZXm92KD4QgIT8AKIADwyimY028qLR2ACQU24UyMX6jkSyQx8zgvXaOSU1WZmKQaBe5LBCH2P2OpwuILJArSqAgcgAtqZueS4PjCcxiUxLpKpQBdOFStK0Tac9Hag1wAAWX38MrYJ2eZvJmiVQxujsxqoiRJJeRdLKFfOWwFFpXF%2BvNWLskJVBK96p94alNCmTBNgwN1mAxBwcuQUlIdoiDozVmd7vmZYzbozNmFQfwRALEpruBTLH5JbgvH4Qn0YkkTyqUEZGirfq41YF6bR4KjP0eEykzlh498wEpwWmNL6HISalQicxbLpu995aGtcDXPP%2Ft50eDJ1DpJLmZl8sVN8xC%2FoS6Wq9qer%2FgUybGh2L5pFagS2o49qjuBlYlpOLbfr%2BkLTkmAb3iG5zPuBs5LIcwAocuuEvnAog4BEcpSGQQZSHI8CuDmyD2PAK6foKNprBMba4hAbERFAUhQGxeLwFAYhQHKpT0HK8pQAAzFAxAWlIET5gJzAAHSkZ2ragWe4GZtmuYaYWCiHhhZwTP4AjZvIcrto4ABslkCn4DFMbmrFoUBF7BqgakqSKgURCpAgAO70NwkyoEEUi6UZcBnKg8AAEqKHIMjwNCzxBil6WZdluWoJF0WxfFiV4cAXoQDaEQZcwWW0YRtX1Y1zVlTFaCVc2RmZvRjEAMqoPYTZYLBfkFAhL4zQac1Om5gp3j8DYkLRS13Pp0xplNPB8IIwj9tIMImiOfkLbsSFouhPLYkGBiEOtVVvH4gSbqEMhtCeQ6wZtwHpLSlS7RxqSXr5oMAytQbYWGe3SrKCrIvDmaPY2tEo4BkNg9tqZgdVkE2lsE1FnBs17ddGFo89hnVcIRgfv1ppMwsc5BgAwkw%2BikNMozwCUSQvXp7xekihG%2FAA9DaogycaEucxA3ObHzAtKCjMCUyWt0tvU95DRAuYACrqcgKv0ILfVM3AIuoGL2CS9Lss7RL%2BtGybZsW%2BrUCXbqFMXf9OPQ4Ra1NgHa5Gjt%2BMYd2h19uIJ0KGd%2B4Xf%2BmvzNr%2Fm6z8AAy9DHEL%2FobtSX1A%2FSKj7mHmbHsDUfuZhtcYUH2CwwXM7AG%2BSNYCiVvALn%2BfAJjlcAxHeO00lwCE9BJPFvBFND5mfctcz1VN34ETqYgWrk9jac8nWwdPaHfkgZHY8RjHvYiPHg5J0kZMCj7rrjljyr1%2FWh8Y%2Bej8axil1zdd058L3gBG4KAAAmKqb0qRbhLjuIcI5wyslLqea8gpmhlGQUODOQCfjoNaJgzo3IkFwJBq9YAqx1i8TPree6hEKE8U2K3Ncq8Hxii3ldTaMYThSDaA3LaWcgz4m4bwy2e8rzN0fDhAeX9OFEUHHwgGnxvhBn%2BC4NwEDRE0LZoREqTDMz0ztt3Kcx9IwEWwJ6b0mpNFtyLjA76NcGQVxMdXMuy8db7zcXpFhLdrEYQ7ozfqMY1Qai2IPFGJ9R6oMCRPa0U8RKkxRt%2FDhe0glxhCQotu3jJFw2xsw2h5jYyWK2PPcObZSHRJMnmca8SZ7bzqfNee4NVofz0cPMpGT%2FQXyOtfU6e474p1BrvboGdlr5IeGpH8JFfGYlsZ9exriEHOIIR0zOHiRliKwtk1p%2Fl%2FHI1yTjYif59kwBfnTdp1C9KT2JjU%2B%2BY59lDK%2FBM1CKzbweKOFs6Zr8BE6KeVMkpmYKJURoj8QaXkWKpXYuPLilDGGCP4jEISIlUBiQkqIKSMk5JykUspVS6lSAxG0tswUI8nJRPHpUsyMFSb%2FLXNZL4dkcAOVJVAVyXsPKMUqT5F5bd1BBQtCFPlXUKo%2FiJZiAqHViryPyqlCVOVBxCp6iKz5EY2oxFlT8VVDUirwAVXFJVNKcagpGmNJek1jkTkSX7HejS34H3RqKw05yyXnwOpfY6N8%2BnqAGVKB5BR1lQzGcAamR9sZQI%2BhAbc7JfrUqWSQ7lUM1nhNtRIthyqyG7K7myoNLTpFGVOWRXGzL%2FWYiueZW58054pOzfai5GEDEBKMsWsh3zsAKyVrzVKqsHX%2BRtnbOADtbZO1TPLLm60O383Nmrc1GsDUwCbXdbR2BXbIGNlIU2nbJ3dsFL2n4A6ZYQHDcwF2BsV3uw3Z7ad3tMZWqrDalhIcNomJJeUlsXS44Dl6Y4%2FpO9U6V3nazMxcBF7drDcXeZKDhxONDYDONtbMmJvNU0mGHyDVwAzVAIx49gO5vAvmvSz743%2BVLVS2piFK37KA3nJe%2F7A5vPXOvKQm8cN3NvSY%2B9OabUEbg2Qt9V8P2J09eWt4STprPwDkhu1NMXRJMfn%2FOYCFTlwEdgegyzq4BtrHUwD2L7MxfF3RpnmWnz2EMlDgjmo7DMQG05A5NNAOO3FA3Y5ZX6mSmZg1GnTa53hN2wbZ1hT5lVocRg2%2FynNYjIq0sMGiUhDb7C0gZ5WxnyBQDC6JSL0XYuBm5HhtpqnPGCmI9PITFqzS73UxZzYQ0PnOoTeI95qbf6HnK4rTTEBMsQ1eXV%2FzUi3JKbGAwn0hFW5BffHsshQ0ACK2d2HdB1L%2FW4%2F84RwGXau9dE6LY1ewHplRK2z3rZMwGxdy2T2res9YiT2AH02dmRG2BHnBOIPcz9TzmZvMIc65s1NvX27BbG5iVLEWov83a1pXba7tPJYB3idLwO6zZe%2B1xzbANCs3O5LJprwBl33AJYN%2FLtGuulDYilCIM3UhlcxzgOQYVUAAEFAhpIyRd%2BrAXGsYmW5T6nYRKLUaIX5wnqBiek9LBjw2slUBVakLmRnfP4WC%2BY2TkXJsDDbaR5mLJDXSuK7XQAOUlx11ZXWfGs7NE0egeBCg4H8FlVAuu5T6%2BWnRo3mu2fAEKGbgAYubVAYQaL8u49gdXLPncm7kREPApR%2FAveYXRq78vhcu%2BxxEEJQ00DEHoDLYg4GsG8%2FYzW%2Bbkp%2F7mDLJoYAQA%3D%3D%3D&value=ETI%3D&code=EQdwlgdgJg9iB0ApAygeQHIFEpgC4wCd4oBTAMwEMBXAG1wGd4BjCmmgIwqYGt6ACALx8A3gB0IfPqODV8TGAFsADjRK4S0gFwjx4yZID0BvsjVUlfMoT4B1MNzBKSOCnxowY3c3v3T6JCgImAAsAfXAHJxctSyoIJlwwGAl%2FQJCACgArfxx8AlDnPEIAGj5IJSpcAEodCX1JADdAvioCGkE%2BAHJg3Fwlek0jEgh4CMdCinhCAHMDEAMKJTB4JWClAH4uROSBAEcqEgIATwAyGjB6XAFUoOCTqwIFCivs5JPCMGnIAQAqE%2FoCDcQgJOnwANR8YbyUgAVQASgBJdLlSpVADcujq9QIZgIEggJBAfAACgRFBcSOkyHEEkkJOkcfQYDQGiQamIsfUymQ%2BMiIBVcPBVBBprhgnwADx8ADM7J8XP0ONwrQkjOZrPSAG0ALro%2BVcgC%2BmIVkjIagyrRoVXgYuGVJp23pjKUyX8cs5CqVKr4ztdJHgrwg6T1Hv0ButtqD1Pijt5UGeFHdJsVJCZLMp8dwk32hyO8CBwRDyfDGNDJf1BuK%2Buk0zUcNTtFwADVWAdwvZxtFgNpo7Tknxa7h6%2FRGy2aAcsjkivlCnlSozG0muV68T6G3QbXhVKX6pXq8AcdBDsPG%2B3IhMYr3HZPZ4QCrkSmuR3RSkoyf0l9jcRJNZ0JecunBPg3xgfogM6AA%2BToq1DSQ%2FxwBo%2BCYGgKHoegBGkMYAFpElwVRpCgoCFw3XDVHAiUDAQqCYOTeCwEQ5DUPQzCOyw%2BgIEcJxcAIiV6CeNhCIhYjBXYzi1HIvjWBoCCKKo6D9XqP8DHOKDtQDGBIHSTpOiLMMaL4I0IANUtMUxIw%2BAAFWCEhLGZdxwBFNxIFTPhAhsp5oGeQgjlc6A1woWAIBoPM%2BAATRgKgkIoCQAqgJCqEuRQkJgUhXPYGBWV8uL2BIez4HEMAeRvB8CDKCBLmipgSBgHkHNgBAUAwbBpxqbJbyIUhLjJI5g1LNqSo6AkiTquAkDQLASvSWAmCoBRhkFHNjlMVQEkIdJpAAYkDLD2qwh4FGkKpSkyZwE3RYAgA%3D%3D%3D&style=ETI%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=grid&template=default&show_errors=change&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=0&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=0&lib_autocomplete=1&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=0&lib_dompurify=1

**Comment by schmunk42** [comment]
Your schemas `block1` and `block2` are not unique (enough).
From the data it gets, the editor can not detect which type should be used.

**Comment by JoeShields-IHC** [comment]
Im getting the same error with similar object schemas, its a quiz so I might have item types: multiple choice, multiple choice with audio, multiple choice with video, multiple choice with image, so obviously the majority of the schemas for these are identical, is there a work around or a way to force it to be unique?

**Comment by schmunk42** [comment]
You could use `type_expression: true` instead of `type: expression`, not nice, but might work.
