### ISSUE TITLE
array of anyOf leaves bad menu elements

### ISSUE THREAD

**Issue by mark3smith** [json-editor/json-editor#897]
### General information

- json-editor version:
- Running in demo page.  Appears to be running 
- https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

### Expected behavior
Given two schemas in the anyOf statement, one with two properties named 'x' and 'y', the other with two properties named 'x' and 'z'.  Activating the dropdown choice element to switch between the two sub schema would generate screens with inputs for x and y, then change to two inputs for x and z.

### Actual behavior
The initial screen does have inputs for x and y, when you toggle to the second schema, inputs for x and z appear but a third input for y remains.

### Steps to reproduce the behavior
See the schema below, add an item to the list and toggle the item type between XY and XZ.

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
    "title" : "Test",
	"type": "array",
	"items": {
		"title": "Items",
		"anyOf": [
			{
				"$ref": "#/definitions/xz"
			},
			{
				"$ref": "#/definitions/xy"
			}
		]
	},
	"definitions": {
		"xy": {
			"title": "XY",
			"type": "object",
			"properties": {
				"x": {
					"title": "X",
					"type": "string"
				},
				"y": {
					"title": "Y",
					"type": "string"
				}
			}
		},
		"xz": {
			"title": "XZ",
			"type": "object",
			"properties": {
				"x": {
					"title": "X",
					"type": "string"
				},
				"z": {
					"title": "Z",
					"type": "string"
				}
			}
		}
	}
}
```

**Comment by schmunk42** [comment]
Please try setting `additional_properties` to `false`.

**Comment by mark3smith** [comment]
Thanks!
