### ISSUE TITLE
propertyOrder not working

### ISSUE THREAD

**Issue by kazepreaux** [json-editor/json-editor#905]
### General information

- json-editor version: Interactive Playground @latest

### Expected behavior
Order to be as per specified in JSON schema

### Actual behavior
Order ignored completely

### Steps to reproduce the behavior

Direct link to example: https://pmk65.github.io/jedemov2/dist/demo.html?schema=EQbwOgdgBFbA9gBwC4Et4QM5wFxXNDLMACaqYCGARgDYCmA%2BnWcgwFaYa5TIBOArnQA0kIsTKVajRLyR1eaOtmB4%2Bg0VAC%2BIwnAokW6CBRoAFWYnmLleAGYnMwjXDTJ63OAGU6yKADUKXlRqd2AdGDgZOQVUJW4CMTgAESUAYyCUI3iNROAoyxi4lXwcsWJMPlQIAHNswjKiFwBPSw9gCqCauHCGxtI6e34aZDbu0oa4JDQMGxL63ojgVPgAW0QKVJHitTpxss09mAP5o57cqaNZhN64CRDGZZoaCkRHbh2zstvye6YWdk4EHeAicJz6dykDHyVlisx2e20e0iFisTQA8rwSPJuABGUqI%2BZwAI0dTFa65aEKJoAFRau2KcAAkhBEPwtp9FgASXgDNoAYgA9FjbFVUNMsAKqqzkOZosgmmMwZNMjM6gtvpJ6AxHs9XvTVCCOeCfpDKdZgeowQSJnkUVSMVjeNwAEz4z5eCgANzo1Pgaq%2BwFcoTwHu9UF9iptZppdLaaLZ0sjAbNsP9Ns9gWCUjTN0DsYZ7UqXTCh3BAwoQy2IeAGaC9wAtBQk%2BqECqsDmW1K2QBBZCVKhsop4ckLPqIZ6pOgAC3gNEdbQCdakUAAMvB4ABrfiIOClsTW0eLZZrDZVnggvdaUvHBoH85tq6ljW%2FHUvN7bQ1P0gmrXMMUArgP0EI1FghLUUyHc9LVvI1kTldFMWxYoAGZ8Q0A9bgGUVxUfQlgAAYQwCA6E2IwUmQChUBoXCbVQEh%2BUIiBiNIjByMo6jmz6IN9WIRjmPFNiqOUWC81aAt4CoNgSPZJFbTlVMyS%2FTl5TE4dL2aVTyiLWoSzBXI6AgfgVm4ABtS9FkIhQ6AADwAOiSCgKNpSxbL46SyJ8djMCEKBLOQGz7McihnPpS8AF0QL6C5VUUvSAynOisSBIDdjio5r0iuA3JYiBPG0jtkzteUQraZlE10w84G5XkC0FYVsMuSUWTZWUCnlXc4rvANsvFErYsq0SeLgDoqh0yLQLSDJxVGCrRzgAyjNM8ziE8ABFFcOsPMLrwRETovbfrczAh5Z11d8DWAr9jr%2Bf8OEAi7QRba6ILhT84rgY91k2C1UtvN1Si8CA1mpXgXkEjjDtyOj%2BU8IHEBBsHPKEzjFm4tpYeB0HEHB4TZJUoaEEk6SUeIF6Cq5fHya4%2FNqxG4txuIBbjOKMy0r6PyAocpy6VsjH4axnGfI5uyueC%2FNwoZ5UcKp3IEoMAyfsvG9ei63I%2Bb8eRMCySHc0pgsqn86okIyr9PHgfheEnbsDB5TAaLmwa2jpnSTfe4AzYtydTHgBQZeIPXqwNugjadYBXZbalUBWOg8ooNY%2FY0gmg5DzaVcy4AEcQNFoZ1m0A60zoXc69PM4AOTjniRzzmmC9G1OYK%2FABZVAqEb%2BASCGOhy%2BjhPHYLZ36%2F2dPm6oAAxKi6FMRyp17%2FPhvysPi6%2FRcqCqEh7ZbOfCak77F4WVW%2Bg13gtYwTxLFSVARVSVqYUgquAy3iSd62HarT2h8qefSFXz1H70%2Buv8rA7rJQev%2FH80gioKVAV%2BT6p5FZWn%2BnhbsvBQYKlzv7MUwZiDINQSTOAtgfYrEcm0CiVB6zICQHgvu1ZAi4L3kQLqcAVzkDPPfOAOdqw0BYVQx%2BRNd4iTRgWZhFQqFk3QYsJ%2BxNxHU00vPQuJNciCOrMSUkktgBMyWmzCyRF3KsSRhDBmiw%2BaZxxgogMwiX5swiupVs0tpG5FgbvB6Stw65gzCSO%2BNit60IoGgtRBDeBELPC4agmByGUNmpvTBBNGT%2BRWLjNm7C4kbwdgAd0cqkGe9jkx9U4Sw2ykjd7LQPjaLhEANyzBMvfFsPIaBtCxJgdILdmAACE%2FHLUWFOHkth%2BRCiwhAMUjUQAgHhnSTQBx6GHk0NtNmJSoof2yUeVYX0zz2Gor9Ucys%2Fpv1kvtFJuRro%2F3OlBR6R1wE3SAYCP%2BV1zliOgW7RxZ54QIPmIwws8j0GJzaIUmSSpAzRKdgvESdy5gtmUjXapZZBjDHRk0CodAVi8yBTYvZftOmJQVilFxS83acncaSNSiTqG13piihZhLDxLJPE4k52L967V2eS0FZzNQnSeG%2BHiHwbmsouQBEBJywE8pBVyh5yy4FYpefud0wAuwyiKmgilhV5KeLdvnSFiwOGk3lX1NRW8B6RKOuWSsC5uwACVGTdhaSuAAomYiRTL1V9DlkleBUzXHpkzPcWeNc5F1wNTaYUFYYUFlrFmeg9Yen%2BoDKixZxBZW9n7IOfZDtxwbGnLOecBZFxhroKudcW4dyTM2YY4gjzrlaPEHQSwEAkoXxVZSmRBM%2FBmotVa21Rb6WzPdQGGyMglAn35Y6r5%2FdkVEoCUEtoqRMBTkCIWtRgbjUFmIqkqALSJIAAoACUdriAxsVQNMtKUS2YWrbWqBzKG3DurNagAGqYU11rPCeEZGiUug9O1upxS2Lh%2FlQZ1Oyew%2BiBYf3yBMDuq9u6%2BG%2FIGiCx1EioNosbYCj5JbUYAqzSYVRHTd0Ouwxq5qyAE1BAHP5ZNl68gTnTXOJC1YQp5s3Nud9lK5lPXOUczlb0G0HPOYAvl5auPGiFZAyCIqBNUpWfxsTJ6DJnvrWJ1GPrgDNvNZam1THP0Ca2cW5aVV8WV2wxByYCGo1RLcATNExnUPEHScgTJiGKTasUyBv9BTjPYZYwGMpFTTJwYDLU%2Bpk1mkkDaTum0XSarVjqv0wZMwBTDOjCFcZ6mVbWIrfaux%2B6uMfTFTS55mnilKzUXui9DtDmnQ5ZJgaAD%2FjAMq6V25wnXqXQrdl6lTzOOUukzWgydayO60UyuRk1JrWmu7BtDtKs6WTclQw9CkBNDACAA%3D%3D&value=ETI%3D&code=EQehAIEsDsGMBsCuATApgKQMoAoA6wALAFyIAcBnALjFmWgCtyA6BAexQDN4BDAJ1RasAtiG71uADxDxIAI3Ih6AR0SpeATxABmJjoCMilWvVMhMJo3wBKXNDBQ4SNFjyESFaiFoNmbTj35BETFJaTkFWFZ%2BRgBaInVSVG4CJOQQPSYAJiYDeMTk1KZZRGhkeAEzaAtya1t7GAQUDBx8YjIqGjpGFnh2ZC4%2BAUjg8SkZeRACblLy2T5mRhAAFiYABiYlyemy1DneBZrgG2hbADc%2BcG5YVExYXkhSInAAXnBkVlhEIVRoIiYjDSYVDlWBEKLYADk5DuDyIAG1yLxYAAqZ74K6oGLFSDwZCHAC6EKsAG5bJAOOBsBjbvdHkxEbBwAAyJngADuMHebKYGKs4AA3rZwOzOaxuRjBNAOJAAOb01BESFzcioAAK3CIBAhABpLtcabD6UimPxSDxrtgQNgmMjcLgQFY4QA9O0gfEAagAJCAZbr8J69NYSbYAL62OoQACSAFlVQB5ABKABUAIIAOSTlHAbVIniIHJIaiYMsgmsQsiYkFYIDySRS3GQ1RAqAk3CEZtQCjOF3I5fIRHu0Bl0Y1sBSvBe4A4JVBVeg2H7%2Bz5gugwv4REQvFX07gRDnU85I6IY872CUutgsmXQuF4HOE6Eo5S5F1vfkA5gMoTqBlLdJJ1XW97GmS5eF4bh1HATUNRFeB4HAWRUHAUhWFIRAeCIVBkBFTVwDfRdP3AR9j2fG9hWIk9yEnOF8X%2FMjwHsfhfwkcBEBVbCwTeBU1EqJDyUuPCPyHcBIl%2BbgYCozUkPwoSZXAAADJR5PomTeG%2FZjJ2gVA2XAdSAFEJFIM9dQhSAiTowDhXqTDwMwqCCF4dgZQIeykJQ1h4NYCkCKHKjtinKJLmgSCfLk6CiHo%2BxRKIcToEklI8L7WSFKU3UG2w0soNYVyFIo595NA8D1Hoz0mCSMcFwHF8pxnPdWHnSBXwHa9LNvfiFyStSfxbJhMP7SreCYaA21QKwWtvCaiKfTsmDQ8gCAG4NWuFENwGBFUoApDr3y65jes7RVF16hJRvGybyOm5g5oWxclvOsNWpDJb6MvbA8s7O7wBDf9vvDaB7zvPhIG4WRyio144RXYUIWG74ISzCF72B0HMW4HVwAhWt4YxmBMN%2FXh0ahSJEmxiEmAhUNtRvKHbxhkbSaRkHyixQmsYR2RWA8pJoEJ6FUNQUnyZvEMqcAmnodhgWEcZlGYlgVmTtJ0LeeJqWMaFwCRep%2Bi6bh6WgaZzFkAVkmEYAYXqrTZ3qgARBVxPgcgVf5wWKc10XhXFjHJYZg3ZYFky2Zx35ndN9W3ZWj2BR1n39fuQ2Yg4E21dMkOTL5sOyYjr6o693WU5l5mZWT0ncdDlONcj7XWvz3349lrVA8VhGy%2FT1XXeF0XaL%2B%2BwkxOgoGxAAAhXpWGQAh2FKN4NW4FUIv%2Bi5C9QPShxgVAbZnufJxpmQzCILMAE4D6jyW4%2BRsGdRvZBIHIM0IIAaVQdQEZ9qPyHYJFUCzVTPyPE9eGwEvcgVgo6YXbBhTsWYva9hlL%2Bfsc4swAAltizHmEEUgOJUCuAADzX1OAAPmwaQQhsh8H8n5JLEMIZsEgFIeAbBkBBLqHKM8CEXBWAakoPcZyRAIT4IFPyDOqAqE0MgPwmhxCiFMJYWw%2BqRAYjkEgAALy%2FnoVYpAJDEnADILSMQUiymIJQaAURHzwGJHwpk8AiDEnIbWKhTIZTWIkYQkAeD8G1E1qGCyANWCyHoKgUE4NwBwmrhNWu5tLYBLqtAO2MUcROz9DXIOEILa8EwhIJgG8Yp90SMwLJ3AmAW2gFbaJsSHYJPAJ3UJtNY4YwADI314YksJyTMDqH7KgIQhSPIgmicwAA4j8NQkBYBMAaf2dGVSxYx3pgjTA0B2xJnAqQMp8TJlJObhjVJ6TMkzxyTNeZ7YmCHNIEs7gKz7ZrOaTnapEtZkY2Vtc6GrT2lgOObJdZK1bD4h7hAfZA80gj05uPSe2FkCbwVN2Ccvj%2FGBJXiWLS%2BSt6vB3pAPeh9j43lPhjGFUTL6AWvrfHg6hH7P29vTN%2BH9rjf06r%2FaaADcWBJATeMBd8%2BpQJUogWBB0EHgGQTMXYaDhgYPKDgtxRCSFkIoSNERtCXGSNINI1ArCOByIUco1R6jNHaLXno1ABj97GN4KY8x%2BDLHWNsSdexjjiTOJoW4jxXzoC%2FTsH8%2Fu9ZAWjxBSUbColpRyVQn0qFgN67lCKf67eN4CC4yzAOVQUdKh1J%2BI4ggWZVhR13qWLMaio7RucjIHhsbeCqC8RGcA%2FyPXDy9RPH1Il6oRsDXOGoC8JwyBstweA4bZSRsAtG34Rb403kTcmzUaaM1oqzeAHNUaDEFsMVBYtqAo7cEQGCFUvSB2oFLQBAGGoYpjn5TsCcrwdzW3nI5VgRA9LXzBLwXUtZr2liiBeDgvpp4xTnmddqD6b1RDOlZCA34hCsFOEhaYkEWyNMIhW1IVbgU1qnlMAV%2BwSrYB%2FU%2BwaMA0JECsMdfIHrIRoEXKwdQ5lIoQBTCQK4LkpLlvdbBoFY8EPYWTWvLKOUsBxjTDER9t6HDYYPMCZAqH0O3srNAbDuHawAuwLAV9upwUfoVM9Vq9gzZId%2FMhQYvxKRsmWYkXgfJCV30ghwRyQgHA6MxKDD4ABrdjNnYC2ZEydXjURxOSdmtpxUuHYDkHIK4YzxL8B%2BmAI55zRwLL0QBsUEg9VJyifc7%2BIgQ9V1gnnBCQmWXPrCli%2Bl8TWleCIKTNGOpk4IQMJEjwfzaJgAcFnlObgcQ0WdnwC4sR2dctpfqj0We5Bxl%2FHSpCUEEgYikEcgZ%2BIMQsOrpiGgcomEsTdZ5jlhCy2eTIGQHpUDvwBtDIARCBAIzbPo2wHyZ4%2FCvbCk9Gh1zv7MMSdXbh848BIREnotd27iQ3MPc89JgjiMO3Zf%2FOdUS%2FY1o7aeK8LSOlts%2FEVIdjTAtVvCkS791dTBjNPjh78bAqBIfHHOjdtHHmnt4brKkSE%2FMVv0SehZCa9gUybbW3F1cnEZSOUQKQeiJOZt%2FFIN5vS5Rvi%2FC8%2FwX4QvOnw55KQRIpR1M4mQNgPL9UVMM4gPNMUyEJtqHiOAeLE9QMThiGt2BkEGuZTZOwXEeEJ46RV6ueLAvxdPDZCkVcY5FdQCoobtQWFLhUTZMCeATBQ%2F2Q1FCbMWvaPXw7awGUfl%2BBvHqkhSgeBVO2lajd%2FALAiCjfG%2FzNJ6g4gnSW6zw4uHo1oDOyD28AMC%2BTcgq8Ynd2MOk5w2L%2BHAX5J4LhIppr0IUiPgF5qWrnp%2BQXqvfdrzmowzAHxPJVbDfdcmF9wAs7LxLsfe14X%2BITBpSlFcLn%2FPOui8l8SGX9LFf6R27O9vrWy1KTna34%2F4U7Vl9F%2F35yI%2F%2FiYjAfBfANYJWAFvDKcDfHIOUESP%2BudDvo3l%2FofjnowPVDEFhBhliEQL8KXqgUQEgScEcD0Mdnfq%2Fl9NvsKB%2FnvgfkrjniNmNqflNrWJfvVNflXlgoTpNA9BNKtsiCAH9OrtmO4B0D6KWAQOWEEDWAWDZDWPRg2E2DZrICAAAKwAAcShSwSwqwHAAAbJoQoQoQfAAOx6BLCZBKGrCaEmHcBLAcAGFHwcCrCwBLC7AqGrCWHcCuIfCGCqAaAAD6%2F2hQQgyAAAxJ8P2MICgZDs2hNC3t9tPnzrhvVJCH4Q2JQOunirqBvhdtHI%2FmDk8PjvDppNpOADjgjmONML%2BGRo%2Frzo9n8FjiRMUXjgTrTmwcKC5jEW3nEUwAkZjNIcgJQCumCMKgtgHE%2FpvlkaDkwbkZDgUbDpDsNkjhUedFUdhpjjfCPmOPUXkb8M0V9McK0cvLEdUfERlrZk%2FFzujKetEg0fDtAW%2FltJsX8CceoBbGgC8K8HoFoDcbeNEfse0YceTjJodr0CqAsewU0cLNur8uWglKqnBGKIRFZonkhI%2BKUBqFEOblPPwA2PVPACYOAAAJrsAiQgTpQiRsRggWaRAvEgwgZgZTyIS9DchkhbSMDYGBQSQxRwCoBeQiilBihMCcZpg%2FZ8gsnT5EYDgkY162AikYbTE8lcj8mYBcY%2FbYDvCfAi5%2FAAjqBAi9Lgj4CBG4EoH3aJwmLWC6j%2BL94qa2A5FrT3b7I9rChLxZj4AABqKYCYkYKYQ8dSekIWN4LY42nYii9UTpwAekAAGqqAmHpJgJgJGFxr6YBG2moB2iGXUpGEmHpAmCmHUvgKGH9BcfuGDlzHUvHtgIyjhmMSGkSSeNRN3IBEWeUEwL0DKNgAKfSLJOSOoGWX4lErqAWQkY8bqC9qoNAd%2BidNycOUhM8NOTij2aCBCMyKyJOeAAAIQznQDoTwCfHtSwDUYCCcgthxgcCAIdojmrkzkxB6CfEAbgBmyQBIjoQXD8AcB%2B6ckBQ%2BoKY3y7m8DYSPGkHgDribjQC14TQcGTT2CYC3pITLkwD66bh1pwRRJzjb67knizRsQLSTmrZgVrgKhAWAxICoC15PRq7VkJTQ6bk%2FT5m1T7hM7ICpas5473a6ism8D7K6gjL1SIJEBCBbmVn2BW68C2Z8Cgrsa9ANhBSmZyLcBB7vzfBQCiQ3gxbLaTisXFgKgMXpZvYmTA43gO4FZqDFalaTicXQDcW8W176WQDYSvDyTj6sX7IhjeHeH2XT4j4EAhjySWXrYIB9YDYbZK6HZ560G77F4MEO4gn6XpTFF7aFbDYyBObowO5mwJW2ZmwdrwBzBOafSAVbgs7pZUUAT9mrh0XOl%2BzlCaUJGsVnQAymXmXwS2WVa%2BU1b4D1ZUT1ZzY9J8Dqoyh4Htb4JeW8FVnuWTh2X8hqXuUhhMBLzKSAQAz3g%2FaTjSlibJbKnuWfR7rUaHrlAAKsVDl8A%2Fb7WhqoBdpvpLzwprxIrKb04AV4V5V0WVXzh7U2kYb7LTXlVLoKVcU8VbmFW2DFXgB0UGQBn%2BZziPVMUYY1UXB1U%2FWjVNXVbkC1ZtWNZyxjxbrAD9WDWAS5UlWbbg3PUOUnRlSGT8Cg31QcWiT1VLQPT%2FU0XxZ0UNLtrwD433ZQ0Tgw28Vw2MLNWI2tUNYdWfCIRtaiIDU3X14aguS2WuVt6TVNmljJkh7llY0OkXBtqLWvDLVJYKhrUS0bVUYHooJqAQ23q6hq3MU6pM2nW6jlnkAXWIoQo4Y3U42A143LbG3PovW3pvVJngTwAU3fW8XU3UW7i0WbY%2Fb7KPUBbVWVnKWs6IIeRoDHqe3ubYG4HeHRSOQh7O7w6S7qm17tQ3YO7x24hqCV6zwpV9bDbBXkFhWl4O5OxjSVm4UbhbjEVkR6XLbF2J29b%2Bb%2BVDZBUn6hXn7WbLYN3eVx0J1FjnJy7IAK64jYClUfUs2Q2fRF2T2DTT0%2FCz3Rrz1A0k2Blg1u3VWr2d3r0y4z1z1K4M3y2%2B3L23pjQ3VqUepFjZ2%2FBpho3iYqhpJDyoCqr8DK6n0l13rJ2DTP2DRaQSBECYAQGfjHA00tr5X1QpXHbpVwRZX2Ynp01PUE4x0XCoXkXBJ1kq0TiE2JApilDqi4SvD3EsCbgu5Jh8DJaViNhEqliuDOXWA3UjVS3jW2knTkPICUMEBwh6D4hTW1jK3gCa2DSsXkBwjuX4jyhEBlWEXu1sX8MUMS1wirD4hwMWTSOdEZalFDjDEZEv7Ch%2F2UgAyPEOBSPsRt6yOjnMn2NiayNMBTDkBxhsjQCqh0FdmPGN1XZVn%2B4a0uMp33ZyOPF1nb7tRYT0gniPiLk2nxND4FI112ksjJOD6dJpN%2BN2nTmvD4CRjVHWBN2TRA18OJCR1MXbFOrb7i1UMKSuUz4eXvXHWzXnTtQGNuMeNeM%2BN%2BPYDrXXlVkLX3ZLVhODSrX3aDO60gWTSbUG3IZMVHWHUhrnwnX1qyhHXrN23rwO0o4kGPTgnOq7E%2BBqVdGYnICkZ9lYMb40z2Bxg%2FlqD64Uj12UA3j2DgAm5lXHUfMQBfNFH71k0AQ3kAuM0K11CZ4WOBQnkTg2OwXdMRNOOUiIsYbMC9PeO%2BOhXYABOfEAwhN2NqWyNwhRM3UTSxMsMJPcBJNxPZOPizR5MnQ0uUupMMuhX5MzlFMlNHBlMTQNkCDNlMUtO1O3gVOvUnTVNYQivwPnQNOS1NO8MtNTUzUxPONEsRPuOzx9NYuN4zOaiBP%2FnzUHVjOhNqVTMYZ6sEAHPCgLMEDbVG1YQrPm1LxW1rOGy7NXWO33607HPCjcGhhWDABAA%3D%3D%3D&style=EQYgVgzg9gdgtAUwCYEsAuUBOcBmWC2ABAN4A6MhhA7ikmgBYBchAzAAxsAOAHgNzkBfcuQB0AYygAbOPiRwAjACYS5SjTpNC8jgFJ%2BFSoXwBDbnHUNm2tntWGckhN2YxYCfYaPHMAcxTxHHDRmLj47ShNffzhMFB96YMJQj0NOYyRUGB8YuISQlMo0jP9swMS2fSEYcSkZOQAOABpCGulZOAA2Zta6uAAWbok2uRZB2vblMgNUCE5JYwBPZn9JfwQ4NGMAI0cUi01rWwMI03NaSy1dAsIHJxc3a8i%2FAIQgkJ5H72ec%2BPKP8MIRUy2Viv3yAKBJTgZXBMCqonwWzgoxa%2BAWyJUxy8UXgWygaAw%2BHeYSx%2BysV0EwmqYm8cjxSAWmM8%2BGi9AQuUS8n%2BWNuzi0%2FOMAFcMNdIVliZUqSI8Jh8HAJDA0JgpEzqOcDhS4VLlVRVU9ojCktyTjifnkjST4TAAPQAKkIGE4zAArDxCCgIIRjIR6MYxABrQi262iMRoMycZWcBCYNDouPRuBbYUYGCeqaUBxQYyJUEJSUwcj0FiqmZzRbMBVoBCKz0AQhQ%2BE4WE2iuuZMuNgLojA6ygW17YYA%2BkOq8rJOm7GX5ktCFWa2gIN2bfaIGgUJJJIQYAhkA6oF7Vj4KCgFZ7%2FIRkwTYEGQ9Tw3BI1Bo7H4wtE1fU0y7WqNMx2B8hCqGyHL%2Fskt6UoW1QEnAACOgoxoyGaXlAZgQL6SBQFQyxpggaBJFobpctwhC%2BFsxgABRsM01FJDRIhsAA7M6ACUBYiDB9D%2BPhyFDFgzAgAAnMJ7EwfgNaCqqHaHCkLLwB2igcMagLpMCzB9G6FR2ORAY%2BMqgowHIfGYAJOBmSkeKYEgMZWG60CrEgpE%2BORVE0W5SQiIobHaVg1nYJg6QoIKEDqcpeJoRhWEhIQrokdobpkZRtHJfRXmiWgcAQIKPg%2BAga4oDeyFij4%2F5uopymrDucAgWChCKBplqiDBWU5Xl66wBxGViIKmDQJgjRNRlLW5flsCMPQUAAG4xqqxmmeZ2l%2Bv6elQAZRlSPxhAgBwgmMWIODpZl2Uje1FCcHqXz%2BLCVQiP4nDCtC2bAiQN13Q9khPSUjDGEEM1FVAEDoAVMDMNs9nCu4diOsw9TKXmiSwySlDzoqzCkMApCkAgbDsOjKR4IquDGCykizujADipOcFxZ6EAAEsYkgOCUEB43Yc1bTte0HXYBNDSgABeCDMOVSM3LAGVUOytV9BwKSVesNXmvIKRKsYaYykSpH4jmCBUdZPjeQY6uNjmwPMLM%2Fg7pgWiegr3jujAOD%2BOgkNajAAAC%2FoIAsOABeJnqWzA1uqocqqUGrGsEMwyqbNWFEsM6gkG0blBVFanUyBJF1mErnLOskdhTTGWZUHAs5CiKkGiFsaDwCtgrnch04Vo7CvLiItfwBACAKkg3iMrM6ulh65azq4O4d2GEZRjGcZwG9GXWY41ZJimhWLbp%2BmGcwkdD5gC4Wb5MbyhtJkOgFaZpAfbbs2fzA7EtKTwy6ynQzFymUD%2BAsL4ZdyEH0XgEEDDNkBqdUGWxwbVing%2BJ8L556LzgA3JuU5R4zmYFxDINYO5%2B2JggZCnhKCWT8iLOyUhaCED0ruGA1wBDACAA%3D%3D&theme=bootstrap4&iconlib=fontawesome5&object_layout=grid&template=handlebars&show_errors=interaction&required_by_default=1&no_additional_properties=0&display_required_only=0&remove_empty_properties=1&keep_oneof_values=0&ajax=0&ajaxCredentials=0&show_opt_in=0&disable_edit_json=0&disable_collapse=0&disable_properties=0&disable_array_add=0&disable_array_reorder=0&disable_array_delete=0&enable_array_copy=0&array_controls_top=0&disable_array_delete_all_rows=0&disable_array_delete_last_row=0&prompt_before_delete=1&lib_aceeditor=1&lib_autocomplete=1&lib_sceditor=0&lib_simplemde=0&lib_select2=0&lib_selectize=0&lib_choices=0&lib_flatpickr=0&lib_signaturepad=0&lib_mathjs=0&lib_cleavejs=0&lib_jodit=0&lib_jquery=1&lib_dompurify=1

**Comment by schmunk42** [comment]
URI is too long, I guess you need to paste the schema.

**Comment by kazepreaux** [comment]
Hi, 
Sorry I found what was the issue, it seems like I had some kind of bad schema value somewhere, re-writing it worked.
