### ISSUE TITLE
hidden option is ignored on dependent properties

### ISSUE THREAD

**Issue by mstokes-f5** [json-editor/json-editor#906]
### General information

- json-editor version: 2.5.2 and `master`

### Expected behavior

A property that has both a dependency option set and the hidden property set to true should not become visible when the dependency is met.

### Actual behavior

Meeting the properties dependency makes it visible despite `hidden` being set to `true` in the options

### Steps to reproduce the behavior

```javascript
  {
      "title":"Template",
      "type":"object",
      "properties": {
        "enable_option": {
          "type":"boolean",
          "format":"checkbox"
        },
        "hidden_prop": {
          "type": "string",
          "options": {
            "dependencies": {
              "enable_option": true
            },
            "hidden": true
          }
        }
      },
      "required": ["enable_option"],
      "dependencies": {
        "hidden_prop": ["enable_option"]
      }
    }
```

**Comment by germanbisurgi** [comment]
fixed in #943
