### ISSUE TITLE
Not defining form_name_root result in "sa" path rather than "root"

### ISSUE THREAD

**Issue by Lord-Grey** [json-editor/json-editor#910]
### General information

- json-editor version: 2.5.2

### Expected behavior

If form_name_root property is not given, the editor path starts with "root".
Is my expectation wrong?

### Actual behavior

if `form_name_root: ''` (i.e. property given by empty name) -> path start with "root" -> OK
If form_name_root property is not given, the editor path starts with "sa" rather than "root".

![image](https://user-images.githubusercontent.com/48840279/106806966-df110a80-6668-11eb-9d75-3ae845c300a8.png)

**Comment by germanbisurgi** [comment]
"root" is the default

**Comment by Lord-Grey** [comment]
> "root" is the default

Yes. That corresponds to my expectation.
Nevertheless, if one does not define form_name_root: as part of properties, i.e. leave it out, the path does not start with root.
This is why I created the issue...

**Comment by germanbisurgi** [comment]
i checked and this is what it is rendered without the property set

<img width="362" alt="Bildschirmfoto 2021-02-08 um 09 11 42" src="https://user-images.githubusercontent.com/13135260/107192403-d8c6b980-69ed-11eb-844d-22b3d74d1204.png">

Are you using compilers or minimizers . They tend to change common variable names to shorter ones to reduce memory usage

**Comment by Lord-Grey** [comment]
> Are you using compilers or minimizers . They tend to change common variable names to shorter ones to reduce memory usage

Not I am aware of.

I will close the issue for now.
