### ISSUE TITLE
Validation not working on "ref" definitions

### ISSUE THREAD

**Issue by kazepreaux** [json-editor/json-editor#912]
### General information

I have simplified the example using a simple example in the Playground and add the failing scenario.

- json-editor version: https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.js in playground

### Expected behavior
Validation error when City is less than 6 character.

### Actual behavior
minLength is ignored, or at least validation is not triggered.

### Steps to reproduce the behavior

Direct link to example: https://is.gd/6zWaxN

Insert a name of less than 6 characters to `city`, no validation error is shown. (ref)
Insert a name of less than 6 characters to `city2`, the validation works. (inline)

**Comment by robocoder** [comment]
This is a typo in your schema. It should use `"$ref"`, i.e.,
```
"$ref": "#/definitions/city"
```

**Comment by schmunk42** [comment]
If not just a typo, please report.
