### ISSUE TITLE
infoText not working with bootstrap3

### ISSUE THREAD

**Issue by aerogt3** [json-editor/json-editor#919]
The info text option isn't working. In the link below, there should be a small tooltip above the name field. this is the case for botostrap4, but not bootstrap3.

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIeGQYgAumwQUpCGsDQa3r6WmuaWilBSMPAA5gquNBhJ0HAmVgBiLohQAARk8K4lADJkxSU+fmx0yVVUqVDKqAAsbBlEZCLY4lYAUoZqgiUAItImbJCwCMhoIMkkACpUAB7DIFA04gC+x4dsiMpgFLyGIUaEyftSZDy5pqp+VnhgYFDFTxAAZhAxyAA=

**Comment by germanbisurgi** [comment]
fixed in #943
