### ISSUE TITLE
Default field type

### ISSUE THREAD

**Issue by Jala015** [json-editor/json-editor#920]
Hi, is it possible to set a default _type_ to fields? Most of my fields are `"type":"string"` and it would be a lot easier if I could set that once. If I leave fields without _type_, I get a dropdown on the form.

**Comment by germanbisurgi** [comment]
Not currently, but i think is always a good idea to set the type prop in the schemas. [more info](https://github.com/json-schema/json-schema/issues/172)

**Comment by robocoder** [comment]
I use patternProperties.
