### ISSUE TITLE
Is there a way to interpret all description fields as infoText?

### ISSUE THREAD

**Issue by mkaut** [json-editor/json-editor#921]
There are two ways to add extra information about a field: the standard json `description` field and the json-editot-specific `infoText`. The former renders a a text under fields, while the latter as a button with on-mouseover text.

I like the button approach (takes less space), but would like to keep to schema as close to the standard as possible.
Hence, I wander if there is a way/option to interpret `description` as `infoText`, i.e., render it with the button?
And if not, could it be added?

**Comment by schmunk42** [comment]
You might need to create a custom theme.
Or you can look into the template engines, but I can't really tell how much is possible there.

**Comment by mkaut** [comment]
Thanks for a quick response.
In that case, it sounds much easier to change all description fields into option.infoText...
