### ISSUE TITLE
How to make Select2 option to work in React app?

### ISSUE THREAD

**Issue by ramesan76** [json-editor/json-editor#924]
I have used json-editor(2.5.1) in my react app. JSON Editor functionality works fine.

Now I want to have select2 instead of default multi-select list box. I have imported jquery and select2 modules in my react functional component. But I don't see the change in my editor.

Will select2 option work in React app? Is there anything to be done other than just importing the modules(Because for cleave.js, I just imported the module in my App.js and configured the schema properties to use it).

**Comment by germanbisurgi** [comment]
in this [example](https://github.com/json-editor/json-editor/blob/master/docs/select2.html) you can see how it is done

- add jquery
- add jsoneditor
- add select2.js
- add select2.css

update schema like this:

```
propname: {
  format: "select2",
  type: "string",
  options: {
    // Override defaullt options
    select2: {
      width: 'off'
    }
  }
},
```
