### ISSUE TITLE
html ignored for description schema in version 2.5*

### ISSUE THREAD

**Issue by aerogt3** [json-editor/json-editor#925]
In version 1.2.1, I was always able to use html markup in the "description" field for properties. But in versions 2.5.*, this no longer works. Below are two examples using the exact same schema - the first in version 1.2, which applies the bold tag and red styling, and the 2nd in (presumably) the latest version, where bold+styling are ignored.

Not sure if this is a bug, or if special syntax is required in newer versions to achieve this? Any advice would be appreciated :-)

https://bayikadel.s3.eu-central-1.amazonaws.com/jsonEditor_htmlTest.html

https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIAFKlNrwFUQRF0p2XHgqlUAjiJj2AJqgDaIeGQYgAumwQUpCGsDQa3r6WmuaWilBSMPAA5gquNBhJ0HAmVgBiLohQAAQAPHglxYI6ALwA5FjY0ihu9QB8ZPCuZQD0eO0lADJkxSU+fmx0yUNUqVDKqAAsbBlEZCLY4lYAUoZqgiUAItImbJCwCMhoIMkkACpUAB7bIFA04gC+359siMpgCi8QwhIyEZLvKRkHi5UyqPxWPBgMBQYpQiBLEDfIA===

**Comment by schmunk42** [comment]
Would that fix your problem?

https://github.com/json-editor/json-editor/blob/cb10e1cc2ca3d3be57e4e51827e6f2de74f76fe4/UPGRADING.md#option-description

**Comment by aerogt3** [comment]
Yes it does, awesome! Thanks a lot for the reply :-)

**Comment by sanjayradadiya** [comment]
label html needed
