### ISSUE TITLE
base64 title displayed in compact table

### ISSUE THREAD

**Issue by notgeorge** [json-editor/json-editor#941]
![Picture](https://user-images.githubusercontent.com/286052/111909549-fa6a8600-8a1a-11eb-82d8-be4b685b07ba.jpg)

**Description**
Base64 properties included in a table have their title duplicated in the form.

[Editor Example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgogiFUJkpUoQpIyy4lCHJ5sutjChrkaS9t0WwnbuLYQpkKlKwNBrEMDbwZAwhsFA2hABiYVQRUWxaOoSIUFIw8ADmIAC+bHgAbAAsREnR9nEWiTYABAAUeGSIVI0VjclYACZUfQCUCuluitm5BWwMfTBkIXi5+oIAovD9U4RtHRVFhQfFispgFLwBflJOILkOhjxw8KOqURZ4YGBQWYYQ5ftAA=)

**Potential Issue Location**
https://github.com/json-editor/json-editor/blob/cb10e1cc2ca3d3be57e4e51827e6f2de74f76fe4/src/editors/base64.js#L34

Just eyeballing this, but it appears that this should be preceded with an `if (!this.options.compact) ` similar to https://github.com/json-editor/json-editor/blob/cb10e1cc2ca3d3be57e4e51827e6f2de74f76fe4/src/editors/string.js#L72

Awesome project, thanks so much for all your hard work.

**Comment by germanbisurgi** [comment]
fixed in #943

**Comment by notgeorge** [comment]
Thanks!
