### ISSUE TITLE
oneOf/anyOf on top-level object adds a "Basic" tab at the beginning of the editor

### ISSUE THREAD

**Issue by fangq** [json-editor/json-editor#944]
### General information

- json-editor version: 2.5.3

the problem occurs when when a top-level object is defined using combined schema `oneOf/anyOf`, such as this
```
{
  "Forward": {},
  "Shapes": {},
  "Domain": {}
}
```

and when `"Shapes"` has the following schema
```
    "Shapes": {
      "title": "Shapes",
      "anyOf": [
        {
          "type": "array",
          "format": "table",
          "items": { ... },
        },
        {
          "type": "object",
          "required": [...],
          ...
        }
       ]
    }
```

the "Shapes" tab is shown as "Basic" and moved to the beginning of the editor tab list. 

If multiple top-level objects are defined with `oneOf/anyOf`, their tabs are removed and merged into the "Basic" tab.

I am not entirely sure if this is by design or unexpected. I understand that oneOf/anyOf requires additional drop-down menu to be selected for the object, but I feel that placing those under their respective tab remains more intuitive than adding the basic tab.

please let me know what you think.

### Expected behavior

the tab name should be consistent with the top-level object name, and also appears at the order that is consistent to the order of the corresponding object

### Actual behavior

instead, a new tab named "Basic" is inserted at the beginning of the list

### Steps to reproduce the behavior

[Direct link to example](https://json-editor.github.io/json-editor/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNShYUbFUIBlKlFjwA5sjZRBEXSnZceCqVQCOImE4AmqANogAYtIUZFJebHrKZNbmIAAi9GQw8CAAumwkMmTithiZVCbSMDQKEFKQVFKwRWj+gcFe1ZbWhGCc3OIWMNo2NVJBIQrpslkgJlIwoSBOru5U9b4AKgAMCvMAjAox4qkgJWUVhcjVSxogWjr65PumAASwDAqN3fAidHjlCh5URGQi2FmLbDoiRgdBeqABIFkAA8QWCUKsqABaADsAF82GsTmdugBReAeRImW4g3QWKxPF5vKQfL4/P6oRhIgCcgOBoLo4MBZBh7NQCJR6NiWU0nXOtnmJOuJly1wo4ygyge5IklPebE+31+WUZiJZkLZcIh0NhHPhSLRqMF4UiVRFXX0ESiCjI8EEAHkiD5NMrbMEpEIBtIhoRyHhzmxOmpDqAXe7PShvHaxSAAOJjCaPZqtBxsKZuTw+VPplJsXbWfa2ovjLGi7pp6tkpq2Fr2dqTFz52aF+ZkEwKPQwABeum2ZfKlWjIB7fYatcI06VTZAiSgeTVIA1dKyq1Z8BN4KtQ5sSe6A+Hi+6foDaSDmRDZDDpI3tK1PgAbACPywP9tI3RJ5mtjPK87yCkC8AAJKrv+qAAMxclCUFRnBlqocklosN6S4tm0jgdjMcwgLwACCUj+oI8zkrwCgkWRQhnlQ1FsLR5EAFowBAlHWExRGkWxHEMTxLFCOxEAxJkZDUaOpTlhOJzCRRVFYj6ihQGMpg0pq9K2G48BQAAHAoVDAYWukGQoZmrG+FkrrBABMCgroZEZ6VZjl6fZCiIIS5zocxfH0Ue1ENCpV6CJpW4+AC0XbIMd62KG4bLtBAEqSua7Uru+4oIsYGJEhMEoPBkLcgVhywYKCmiVxjHKUuiBqYSEWvrYg64AQbDGXCvhtfgCgmIOHEpJVAWCKJgl1d06UmOum4tUaBqmrl/l0WNHHieQwVYd0DXqX26ovtpIAgGhgpxLIiSTVmrYPHOtjnQkSS5vhBYJiAACyswwGQGwggobpjCYiQ1SWOwyeOBwnADMBA/AIOzvatjQ7D1yZNc3jRSwizJBehB4GAYA6C6zXaWpIhUGdf0I8mMQkkgcBILjvqrYGGTDIlT5/qlS7TaBB1aVk3hfsL2O7mVcEIeLRWCgAaoTLxUH4MBiiehBy9gCvXErSWAape0k8MJ1sJ9BI/dT3Qm99TMgGFrPBglD5JeBUt2RGKVXc22ZtnmBGFqCP2AiI0T7SASTSXscnVP7NaIyAxF4LQUjQAz1wABSAD3AZDXKsAD0dB0AAlNbwFUgbnL6nuvI5WBQcx8meg5EY5SEmn6eINneeF8XqqZc+Avl+B2XLSMdfdMRe60GpkCCGnJhF42FIgb3c3aTuFfZYia/GlXqyCkk5uEAASl8/o8DAABuVDXBB+JUFCafwPPpwqSXs2HduWVV7lqE/2wiDKGACgvByilCkIcZcelyhkDPggB4qh7i2HxmAKAu1IgABYTqoiAA===)

**Comment by germanbisurgi** [comment]
It is a feature and it is documented in the [readmy](basicCategoryTitle)

**Comment by schmunk42** [comment]
Yeah, it might be hard to detect, that it is a tab, because it has only `object` and `array`.

**Comment by fangq** [comment]
thanks, should have read README more carefully :)
setting `basicCategoryTitle` helps.
