### ISSUE TITLE
Readonly added to inputs when opening properties pane, but never removed

### ISSUE THREAD

**Issue by schjetne** [json-editor/json-editor#946]
### General information

- json-editor version: 2.5.2 and 2.5.3

### Expected behavior

When opening the properties pane/dropdown, and selecting visible fields, I should be able to edit the input after closing the properties pane.

### Actual behavior

When opening the properties pane and closing it, the inputs are set to `readonly="true"` with no way of removing the attribute.

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

Video example from the demo:
https://user-images.githubusercontent.com/399893/113694026-8a712680-96cf-11eb-9337-7092fd7c72d4.mov

**Comment by schjetne** [comment]
Correction: Looks like this bug was introduced with 2.5.3. I rolled back to 2.5.2 and it seems to be working.

**Comment by schjetne** [comment]
This seems to be the offending commit:

https://github.com/json-editor/json-editor/commit/0424e74f4b4b1f3b69cb8d57f190d339a0cd8894

It sets readonly to true on `disable()` but never removes it on `enable()`

**Comment by germanbisurgi** [comment]
this will be fixed when #943 will be merged

**Comment by germanbisurgi** [comment]
fixed in #943
