### ISSUE TITLE
Flex Box Array Please

### ISSUE THREAD

**Issue by PythonLinks** [json-editor/json-editor#948]
Greet software.  It really changed my thinking about client-server development. 

You have arrays, and you have left and right columns.  What I would like are flex box arrays.  I am doing translation software.  It would be great if the user could see the two languages side-by-side at-the-same-time.   But if they have 3 languages, they can either squeeze them all in, or have the additional languages in the next row.

**Comment by germanbisurgi** [comment]
Take a look to `grid-strict` in [object](https://github.com/json-editor/json-editor#objects)

**Comment by germanbisurgi** [comment]
Feel free to reopen
