### ISSUE TITLE
Fields remain read-only after closing the properties dropdown 

### ISSUE THREAD

**Issue by bkilinc** [json-editor/json-editor#949]
### General information
Fields become read-only when clicking "properties" button. But they don't return to writable state after closing the properties dropdown.

### Expected behavior
Fields should return to writable state after closing the properties dropdown.

### Actual behavior
Fields remain read-only when closing the properties dropdown .

### Steps to reproduce the behavior

1. open demo url in browser (latest firefox or chrome) https://json-editor.github.io/json-editor/
2. notice that all input fields are writable (name, age ...)
3. click "properties" button near "Person" title. Notice that dropdown is opened and fields became read-only.
4. click "properties" button again to close the drop down.
5. Notice that all fields are read-only. Not editable.

**Comment by schmunk42** [comment]
@germanbisurgi Please create a test for this.

**Comment by germanbisurgi** [comment]
I fixed this in #943
