### ISSUE TITLE
format:color 指定为 #fff 时，颜色为黑色

### ISSUE THREAD

**Issue by ohion** [json-editor/json-editor#952]
### General information
执行颜色为 #fff ，然而出来的颜色却是黑色，其他颜色都正常

- json-editor version:
2.3.0
### Expected behavior
![image](https://user-images.githubusercontent.com/33108657/114384218-03d1b300-9bc1-11eb-9aa8-0d7c0fcf52c4.png)

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/33108657/114384145-ee5c8900-9bc0-11eb-92fe-6ad1453e348d.png)

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  title: {
      type: 'object',
      title: '卡券主标题配置',
      properties: {
        color: {
          type: 'string',
          title: '字体颜色',
          description: '请注意要兼容亮色模式和深色模式',
          default: '#fff',
          format: 'color'
        },
        fontSize: {
          type: 'string',
          title: '字体大小',
          default: '14'
        }
      }
    }
}
```

**Comment by schmunk42** [comment]
use `#ffffff`

**Comment by germanbisurgi** [comment]
Translation: "The execution color is #fff, but the color comes out black, all other colors are normal."

it works if a valid schema is provided and the value is not in the "shorthand" form: #fff -> #ffffff
 
@ohion: 如果提供了一个有效的模式，并且值不是 "速记 "形式，它就会工作。#fff -> #ffffffff
