### ISSUE TITLE
Prepare 2.6.0-beta1

### ISSUE THREAD

**Issue by schmunk42** [json-editor/json-editor#969]
### General information

- json-editor version: new

### Expected behavior

complete (handpicked) CHANGELOG

### Actual behavior

many issues/fixes missing

### Steps to reproduce the behavior

see changes https://github.com/json-editor/json-editor/compare/2.5.3...master

**Comment by germanbisurgi** [comment]
The release is out :relaxed:

But i forgot to tag it 2.6.0-beta1 and i tagged 2.5.4 instead :flushed:

CDN was updated and the interactive example is working properly after hard reloading the browser :wink:
