### ISSUE TITLE
Where can I find the lastest typings to reference on vsco de ?

### ISSUE THREAD

**Issue by madruga8** [json-editor/json-editor#970]
### General information

- json-editor version:
latest 
### Expected behavior
install @types from latest version

### Actual behavior

get types from old version

### Steps to reproduce the behavior

Direct link to example: https://json-editor.github.io/json-editor/

```javascript
{
  "title": "json schema example",
  "type": "object",
  "properties": {
    "example": {
      "type": "string",
      "description": "This is an example schema.",
      "default": "Please edit me."
    }
  }
}
```

**Comment by robocoder** [comment]
This goes back to #708, no?
