### ISSUE TITLE
What is the best solution to display json out data in table format without a lot of rework ?

### ISSUE THREAD

**Issue by madruga8** [json-editor/json-editor#973]
I'm wondering how i could use data types from json editor to display data in a table component like datables.net or tabulator.

After look at both documentation i see that a lot of rework is needed to display data in table format from json, like reformating an linking all columns with the correct data type again.

It seems a lot of work and i dont know if its a smart solution.

Do you have any ideas about this ?

**Comment by germanbisurgi** [comment]
If you mean like a specialized datatables editor, yes it can take a while to make.

**Comment by robocoder** [comment]
I use both datatables.net and json-editor in a project at work. In my experience, choose the one that best works with the underlying data. For example, we use datatables.net (and Editor extension) when working with ORM enties and database tables. Meanwhile, we use json-editor when working with other objects (coincidentally stored as JSON blobs but we could theoretically transform to/from XML, YAML, etc).

**Comment by madruga8** [comment]
thanks for the answers !

as far i have searched.. what is missing on the market is a "datatables.net" that speaks the json schema language. but i could get along with tabulator-tables with some formatter tricks.
