### ISSUE TITLE
Request for a custom editor to create image/video designs on Canva?

### ISSUE THREAD

**Issue by surekap** [json-editor/json-editor#974]
[Canva Button](https://www.canva.com/button/documentation/js-api/)

Use Case:
We are using JSON schema editor to render forms in our application. The JSON schema defines a Quiz containing questions.
Some questions may contain an image or infographic etc.

When designing the quiz, it would be great to use an online editor. The canva button provides an easy way to create new designs. The JS api returns an export URL (which we are expected to download to our server immediately - not part of the scope of the JSON editor) and a "design id" which allows one to edit the design again in the future.

This editor could be used to edit images or short videos for many other use cases:

1. Create an instagram post as part of a marketing campaign (campaign defined as JSON schema)
2. Create/Edit a mockup as part of a feature request ticket in an issue tracker (ticket defined as JSON schema)
3. Create/edit training videos as part of an educational course (course defined as JSON schema)

Suggestions for other apps (other than Canva) are also welcome!

**Comment by schmunk42** [comment]
I think this is not in scope of JSON editor.
You can already extend it with custom editors.
