### ISSUE TITLE
How can I include an autocomplete- typing input in json-editor? 

### ISSUE THREAD

**Issue by txellferret** [json-editor/json-editor#978]
### Expected behavior
Include a typing input in the form. The list of suggestions should come from a json file, after an ajax request.
![image](https://user-images.githubusercontent.com/63742994/116896166-3d339680-ac34-11eb-87f5-9c55ab758f0d.png)

I don't know how to modify the json schema to inlcude these typing input.
Any help is appreciated!!

**Comment by robocoder** [comment]
Instead of `"type": "string"`, in your schema, use `"type": "autocomplete"`. Then code up your search callback.

**Comment by schmunk42** [comment]
Just added this: https://github.com/json-editor/json-editor/blob/7aae08475840b6b7bd018690e7b24bd8460c9ff9/README_ADDON.md#autocomplete

**Comment by txellferret** [comment]
Thank you so much!
