### ISSUE TITLE
Opening the properties dialog disables all input fields - even in published examples

### ISSUE THREAD

**Issue by arminus** [json-editor/json-editor#982]
### General information
- json-editor version: 2.5.3

### Expected behavior
- hide/show of object properties to have no impact on input fields editable state

### Actual behavior
- input fields are disabled after object properties hide/show

### Steps to reproduce the behavior
- go to any example, e.g. https://json-editor.github.io/json-editor/
- open any of the object properties
- close them again
- -> all input fields are visually disabled and cannot be edited
- slightly different behavior on https://json-editor.github.io/json-editor/basic.html
- -> visual disable of the input fields is reset after propertied close but it's still not possible to enter values after the options dialog close

- tested with Firefox 88 and Chrome 91

**Comment by shekurika** [comment]
Similar behaviour if you click the "JSON" button. Some fields (dropdown menus?) revert to editable if you close it, but most do not.

**Comment by germanbisurgi** [comment]
this was fixed in #943.
@schmunk42 we should make a new release.

**Comment by shekurika** [comment]
issue exists since 2.5.1, 2.5.0 works as expected.

**Comment by schmunk42** [comment]
> this was fixed in #943.
> @schmunk42 we should make a new release.

You are assigned for this ;) https://github.com/json-editor/json-editor/issues/969

**Comment by germanbisurgi** [comment]
Oh :D

**Comment by germanbisurgi** [comment]
Release with patch is out
