### ISSUE TITLE
Ways to return different element tags from the editor

### ISSUE THREAD

**Issue by centenico** [json-editor/json-editor#991]
### General information

- json-editor version: 2.5.4

### Question

I'm wondering if there is a simple way to implement a JSONEditor  which generate and returns different element tags, so for example instead of the usual `<select>` HTML element, I want to return something custom/or from the framework, like `<vaadin-combo-box>`.
I'd love to know if it's possible, and what should I do to implement that.

Thanks in advance for your time.

**Comment by germanbisurgi** [comment]
The following is a raw version of what every editor in this library do. Take a look [here](https://github.com/json-editor/json-editor/tree/master/src/editors) to see how it is done.
Keep in mind that those editors use a Theme object to build HTML. You could Create a Theme too or just build your HTML from inside your custom editor Class.

```javascript
import { AbstractEditor } from '../editor.js'

// create / extend base editor
class CUSTOM_EDITOR_NAME extends AbstractEditor {
  build () {}
  // other methods your stuff here
}

// add custom editor to JSONEditor's editors
JSONEditor.defaults.editors.CUSTOM_EDITOR_NAME = CUSTOM_EDITOR_NAME

// Add a resolver (a condition that will kick in your custom editor)
JSONEditor.defaults.resolvers.unshift(function(schema) {
  if(schema.format === "custom") {
    return "CUSTOM_EDITOR_NAME"
  }
})
```
