### ISSUE TITLE
Thankyou & Question

### ISSUE THREAD

**Issue by btsimonh** [json-editor/json-editor#996]
I've been using a modified jdorn version in production for 4 years - I was aware of this branch, but have some mods I need to assess in terms of replacing the functionality with the new functionality of this branch, or extending this branch.

So, thankyou for keeping the editor alive, and to everyone who has added new nice functionality!

However, in the immediate term I have a question:

I'm building a multi-level editor with many layered json-editors, where the user can edit 'layers' of data, which is all combined to form the final configuration.  show_opt_in is a fantastic addition, as it enables my users to decide what should be included in each layer themselves, and toggle between seeing the whole schema or just the part they wish to see.

However, with every change to a lower level config, I need to refresh the editors 'above' that layer, including finally the combined version (which I display as readonly).

The question is, is there a function which can be called to refresh everything an editor knows (I change the schema - e.g. set .default to the value of the lower level of json, and .options.infoText to indicate where this value was set - and I also change the json data) without destroying it completely and making a new editor?

e.g. if the user changes a value in a 'lower' json, this value should reflect 'up' into the editors above in near real time..
For  example in the picture below, I wish to be able to check and uncheck the left highlighted box.  I register the change from the editor, and modify the .default in the schema for 'combined', the value in the data for 'combined', and want to update the 'combined' editor once this is done with minimal disturbance to the screen?

a picture paint a thousand words, here is mine:
![image](https://user-images.githubusercontent.com/3137332/119499751-ed417e80-bd5e-11eb-9072-e93ab12d3e3c.png)

**Comment by germanbisurgi** [comment]
Hi and welcome! I apologize in advance in case i misunderstood the question.

It is (currently) not possible to update the schema and see the changes without destroying the old Editor and creating a new one.

Maybe the "anyOf", "oneOf", or "allOf" features could help there.

**Comment by btsimonh** [comment]
Thanks German,
good to see I did not miss anything obvious in the api.
I guess I'll need to get back into developing json-editor if I want this feature :).  I need to review my previous changes anyway....
br, simon
