### ISSUE TITLE
Fields that are not present in startval do not appear in form

### ISSUE THREAD

**Issue by Photosynthesis** [json-editor/json-editor#998]
### General information

- json-editor version: current version in use at https://pmk65.github.io/jedemov2/ and available through https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js

### Expected behavior

All fields defined in the schema would appear in the form, filled with any values provided in `startval`. This behaviour would be consistent whether `startval` was provided as an empty object, as an object with only some of the properties defined in the schema, or with all the schema properties defined.

### Actual behavior

When the `startval` parameter is not set, all the fields defined in the schema appear in the form. When `startval` is set, only those fields present as properties in `startval` appear. When `startval` is an empty object, no fields show up.

This may be intended behaviour. It seems inconvenient, though, because it means that `startval` values cannot be provided directly from a data source, but instead have to be merged with properties from the schema to make sure the fields appear correctly. 

A further problem is that when the schema includes validation rules, providing empty startval properties (in order that the fields will appear) can cause the form to load with validation errors displayed (even if no data has yet ever been entered into those fields). Given this, how can new fields that are added to a form that handles existing data be correctly implemented?

### Steps to reproduce the behavior

Direct link to example: https://is.gd/efXaSn

Schema
```javascript
{
  "title": "Person",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    },
    "age": {
      "type": "integer",
      "default": 25,
      "minimum": 18,
      "maximum": 99
    }
  }
}
```
Startval:
```javascript
{
  "name" : "Bob Boxer"
}
```

Thanks for a super useful project!

**Comment by schmunk42** [comment]
Related to https://github.com/json-editor/json-editor/pull/980#issuecomment-839568961

You either need to use `show_opt_in` or `required_by_default`. See also https://github.com/json-editor/json-editor#options

**Comment by Photosynthesis** [comment]
@schmunk42 Thanks for the reply. 

Unfortunately neither `show_opt_in` or `required_by_default` will work as far as I can tell, because these are not required fields. It has to remain possible submit the form without these fields filled in by the user, since they are optional fields. 

To rephrase my earlier question, how can (optional) fields in form that handles existing data be correctly implemented?

Danke!

**Comment by schmunk42** [comment]
What does not work with `show_opt_in` for you?
*Strings need a checkbox.*
